### ISSUE TITLE
Investigate Employee Demographic Details for Employees Having 2 Different Employee IDs

### ISSUE THREAD

**Issue by telusdcinco** [bcgov/performance#1003]
Noticed some employee demographic rows having almost similar values (Name, Employee ID, GUID, etc.).  
Some similar email addresses in different rows can be attributed to the reuse of email address for a similarly named employee.
There are a few rows that are too identical but differ in Employee ID value.

EE 191834 & 185010
EE 188727 & 182074
EE 186935 & 179099

**Comment by Travis-A-Clark** [comment]
@telusdcinco I just did a spot check of these three cases and all of them are no in the past employees list with a date deleted of June 14. Only one employee ID per user. Seems like this was fixed during the data cleanup with ODS and PeopleSoft.

Closing ticket.
