### ISSUE TITLE
Verify data clean up for Statistics and Reporting

### ISSUE THREAD

**Issue by steffipravasi** [bcgov/performance#1007]
This ticket is created from the findings of ticket #898 and #923

Some of the issues to be considered are:
1) HR: 193694	Radford,Nicholas	Nicholas.Radford@gov.bc.ca
Sys admin: Paula Milum
Org: BC Pension Corp
Conversation Summary - Next Conversation Due has total of 629 employees. But in the employee list there are 687 employees with 42 excused. The total should end up to 645 users. Which means 16 users are missing. Cannot find them

2)The total number of employees in the Conversations Summary area is 1303. In the Shared summary and Goals Summary it's 1322. Why is this different for conversations?

3) For the issue number 1, the difference is because the Shared Employees list has a total of 38 entries which contains duplicate users which are getting filtered out in the Conversations chart. This issue is similar to the one I reported in ticket #923 where each case for user is different. The entries are duplicate because either the employee id, email or org is different.
![Screenshot 2023-06-14 at 1.48.11 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/5a7137a0-e789-4b6a-afb4-13c9537d810c)

**Comment by steffipravasi** [comment]
Ji and Dennis has already worked on the issue and is ready for testing, so moving this ticket in testing piplline.

**Comment by steffipravasi** [comment]
1) HR admin: Shawna Wilson
Org: BC PSA
The org list for BC PSA has 55 excused employees when checked through Export function
But when checked from Statistics & Reporting for BC PSA, the excused employees number is 56
The extra employee displayed in Statistics & reporting is:![Screenshot 2023-07-11 at 2.04.34 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/6984cd67-c7d2-472b-b289-90a73f56de7a)

**Comment by Travis-A-Clark** [comment]
@steffipravasi Moving this back in to In Progress so that we can check out what this looks like in prod. Thanks!

**Comment by steffipravasi** [comment]
Region: Prod
Org: BC PSA
Total - 718
Excused - 49
Total - Excused = 669
Shared - 46

Excused Employee Summary:
Expected numbers: 
Excused: 49
Not excused: 669
Total: 718

Actual numbers: 
Excused: 48
Not excused: 670
Total: 718
Difference employee: 
145301	Booth,Jennifer Leigh		Jennifer.Booth@gov.bc.ca

Shared Employees Summary

Expected numbers: 
Shared: 46
Not shared: 623
Total: 669

Actual numbers:
Shared: 41
Not shared: 628
Total: 669

Difference employee: 
139914	Scriver,Stacy Catherine
153691	Best,Bryson
162013	Jefferson,Kate Marjorie Joyce
184562	Stuart,Nahmi Elizabeth
189124	Jacinto,Justice

Next Conversation Due chart

Expected numbers: 
Total employees: 669

Actual numbers:
Total employee number displayed on chart: 668
Total employee number displayed on sheet: 668

Difference employee: The following employee has 2 records.
169395	Coulter,Lauren
169395	Coulter,Lauren

**Comment by Travis-A-Clark** [comment]
@steffipravasi The employees you identified as different in the share report are all excused and should be excluded from the share, conversations, and goals, reports as a result.

Does that make sense?

**Comment by Travis-A-Clark** [comment]
I don't know why Booth, Jennifer Leigh is showing as "no" on the excused report. She is excused everywhere else and does not show up in the other reports. That's a weird one.

**Comment by steffipravasi** [comment]
@Travis-A-Clark yes my bad. I mixed up the excused employees. Apologies! So the only issue, for now, is employee Booth, Jennifer Leigh. Shall we assign the ticket to Ji to look into it?

**Comment by steffipravasi** [comment]
@jizhaogit its in prod

**Comment by jizhaogit** [comment]
@telusdcinco The employee Booth,Jennifer Leigh (Empid 145301) in prod is marked as "excused_flag = 1" but "due_date_paused = 'N'" .  i modified the report query to check employee excused from "due_date_paused" to "excused_flag".  please help do the code review.  thanks!

**Comment by jizhaogit** [comment]
as discussed,  we currently will check an employee if the excused_flag = 1 or due_date_pause = 'N', either one of them is marked the employee will be listed as excused employee.

**Comment by Travis-A-Clark** [comment]
After moving this to PROD and Dennis running the overnight processes, employee Booth, Jennifer Leigh still does not show up as excused in the Statistics and Reporting even though she is showing as excused in the Employee List and on the My Team page. Will look again on Monday.

**Comment by jizhaogit** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaHFHIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4f05385a54498837816d1b00179745f4c77ba335/image.png)
 
After the over night processing the data is now listed in the excused part of the report.
