### ISSUE TITLE
Missing Employees in the PDP (WCAT)

### ISSUE THREAD

**Issue by jessicahjwu** [bcgov/performance#1008]
I have noticed a few employees from WCAT (Ministry of Labour) that are missing in the PDP, whilst they have proper PeopleSoft records. Below is an example:
![image.png](https://images.zenhubusercontent.com/641a1dcfdf400e29dabf707e/022de232-3070-4e53-89e4-a3168dd865bb)
![image.png](https://images.zenhubusercontent.com/641a1dcfdf400e29dabf707e/1f34dc15-f2b8-49e2-82d7-bd523bc46ec1)

I couldn't find anything specifically different in Monica's PeopleSoft records and they are a regular employee with the government.

**Comment by telusdcinco** [comment]
The email address in missing from the ODS feed for employee 148844.  This needs to be discussed with ODS team.

**Comment by jessicahjwu** [comment]
Another question is: if this is related to an organization that has changed their email address from @gov.bc.ca to another domain (i.e. @wcat.bc.ca in this case), would there be more missing employees in other ministries/ sectors have have gone through the same process?

**Comment by Travis-A-Clark** [comment]
I think this issue may have been sorted by the JIRA and the updates we've made. I only see 1 person (!) in production that doesn't have an email address

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/e686479b-ec3e-4b92-9dec-b401fa3e5dcf)

Also, just under 300 that don't have a supervisor (down from over 1,000 in prod before).

Still a bit of clean up to do with last batch of past employee removal, but things are looking a lot better.

**Comment by Travis-A-Clark** [comment]
And Monica Sam is in the system:
![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/e00b9dc4-7245-44a4-8c55-ba32cccd1fa0)

**Comment by jessicahjwu** [comment]
Although Monica Sam is currently in the system, her email address appears to be incorrect from what the ministry has previously provided us with. Instead of @gov.bc.ca it seems like Monica should be using a @WCAT.bc.ca email domain, so she can receive the notifications. Same situation applies to Sarah Day, another employee who's email address was missing previously in the PDP. 

Currently confirming with the ministry on which email address should be the accurate one.

**Comment by Travis-A-Clark** [comment]
@jessicahjwu When you get a chance, can you confirm we can now close this ticket? I think we've solved.
