### ISSUE TITLE
Both SR and Sys admin tab highlighting at once

### ISSUE THREAD

**Issue by steffipravasi** [bcgov/performance#1014]
Ticket derived from Ticket #942
For any user who has the Sys admin and SR access, since the functionalities employee list and switch identity are same for both, if user is accessing any page from Sys admin, the SR tab also remains highlighted and vice versa. Also, if I open the employee list page from SR tab, then the Sys admin tab also expands highlighting the employee list page and vice versa for Sys admin.
Account used: Travis Clark
![Screenshot 2023-06-28 at 10.56.41 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/049bd12a-10a8-4ef3-b342-c2eb2309a9cd)![Screenshot 2023-06-28 at 10.56.34 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/5a66cdbf-9cb0-4b64-9279-fcf5ae3f6e78)

**Comment by jizhaogit** [comment]
a new update is ready in test.  SR account accessibility will override system admin account.

**Comment by steffipravasi** [comment]
The issue has been resolved as a user cannot have the Sys admin and SR role together as they will override. 

@Travis-A-Clark Two things to be noticed related to this ticket:
1) Manage Existing Access page in Access & Permissions will still have 2 entries as those entries are not automatically handled and needs to be deleted manually. If we want to delete it automatically, we will need to create a separate ticket. 
![Screenshot 2023-06-28 at 8.02.34 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/a1d5dcbb-7e52-4052-93c7-8b3f953d77d2)
2) The SR can edit the URL to other pages of the Sys admin and access the functionality
![Screenshot 2023-06-28 at 8.05.04 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/08fdfc16-d6b4-428d-8f82-c87c74e7c582)
