### ISSUE TITLE
Randomize Conversation Due Dates for Orgs Onboarding in July

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#1015]
As discussed, we need to randomize the first conversation due dates for employees so that they are not all "overdue" as soon as they log into the system. The dates should occur between November - December 2023. We can use the same randomization process that we used for early implementation sites (PSA, SDPR, RBCM).

The organizations onboarding in July are:

Children & Family Development​
Education & Child Care​
Emergency Management & Climate Readiness​
Finance​
Government Communications & Public Engagement​
Jobs, Economic Development & Innovation​
Labour​
Mental Health & Addictions​
Municipal Affairs​
Public Safety & Solicitor General​
Tourism, Arts, Culture & Sport​

**Comment by telusdcinco** [comment]
@Travis-A-Clark Just to confirm exact dates to use would be Nov 1, 2023 to Dec 31, 2023?

**Comment by Travis-A-Clark** [comment]
Let's go with Nov 1, 2023 to Dec 22, 2023.

I don't think we'll get anyone signing off over the holiday season. Thanks!

**Comment by telusdcinco** [comment]
New initial conversation due date calculation based on formula below.

{ [ Last 2 Digit of Employee ID ] / 100 * ( 52 days ) } + [ Initial Date ]

Example:  Employee ID = xxxx00
{ 0 / 100 * 52 } + { Nov 1, 2023 } = Nov 1, 2023

Example:  Employee ID = xxxx99
{ 99 / 100 * 52 } + { Nov 1, 2023 } = Dec 22, 2023

**Comment by steffipravasi** [comment]
@telusdcinco Just a note that the Org - Public Safety & Solicitor General​ cannot be seen in the org list

**Comment by steffipravasi** [comment]
Test validated. 
Conversation dates for all the orgs listed except Public Safety & Solicitor General​ are calculated based on the given calculation and dated between November - December 22, 2023
Moving for PO review.

**Comment by Travis-A-Clark** [comment]
@telusdcinco Just to confirm: will this impact SDPR / Public Service Agency / Royal BC Museum when used in PROD? We just want this to change the dates for people that are new to the platform.

**Comment by telusdcinco** [comment]
@Travis-A-Clark The new conversation due date will reflect for those who have not completed a conversation.  There is no hard-coded filter for ministries.

**Comment by Travis-A-Clark** [comment]
@telusdcinco Hmm. That's not ideal. What would it take to add that in? It could be an issue for future orgs that are not coming on board until end of Sept.

**Comment by telusdcinco** [comment]
![image.png](https://images.zenhubusercontent.com/60e88ef619e4760c8b3ee8bb/35afb58b-9384-4793-bf46-4c2ce07fdaa4)

**Comment by steffipravasi** [comment]
@telusdcinco Some of these users are from the list of the given organization but their conversation due date is not calculated in between Nov 1 to Dec 22. Can we look into it, please
1) user 186648	Malik,Sanchay	from BC Pension corp has
Next conversation date on page: 2023-01-07
2) Users 152575, 125023 from Children and Family Development displays conversation dates 2022-12-20, 2022-12-13 respectively
3) User 183058 from Emergency Management and Climate Readiness displays conversation dates 2023-01-07
4) User 000985 from Finance - 2022-12-20

**Comment by telusdcinco** [comment]
@steffipravasi 
The new change to the calc process was deployed yesterday afternoon.  Last night would be the 1st time the new calc will be applied.

186648 & 125023 lost the GUID in ODS employee demo, so not processed, old previous date was displayed
000985 & 152575 the Active status employee demo row is terminated (date_deleted has a value)
183058 was reflecting previous date even though backend the new date was calculated correctly. The overnight process to populate the static values used in lists did not run as per schedule at 4am.  The new conversation due date reflects after the process is run manually.

**Comment by steffipravasi** [comment]
@telusdcinco Not sure why the date displayed for user 183058 is incorrect. 
Actual: 2023-11-04
Expected: 2023-12-01

**Comment by telusdcinco** [comment]
EID 183058 joined July 4, the next conversation due date is joining date.
There is a calc rule that if the (join Date + 4 months) > random start date (nov 1, 2023), use (join Date + 4 months)
july 4 + 4 months => Nov 4, 2023...  which is greater than Nov 1, 2023.

**Comment by steffipravasi** [comment]
Ticket validated. 
Some users in the listed org will not have the conversation date between Nov 1 to Dec 22 due to multiple reasons:
- For new joining: There is a calc rule that if the (join Date + 4 months) is greater than random start date (nov 1, 2023), then use (join Date + 4 months)
- lost the GUID in ODS employee demo
- Active status employee demo row is terminated
Apart from these situations, the next conversation date is calculated with the given formula for the listed orgs excluding BC PSA, Royal BC museum, Social Development and poverty reduction
