### ISSUE TITLE
Create One Time Update Script to Fix Previously Terminated Employees

### ISSUE THREAD

**Issue by telusdcinco** [bcgov/performance#1020]
Create One Time Update Script to Fix Previously Terminated Employees

This is a required fix to correct Supervisor/Employee relationships in PDP.  Some terminated Managers may have remained active in PDP due to missed updates from ODS.  ODS only provides terminated details for 7 days.  After 7 days, the terminated employee row is no longer available.

ODS Employee Demo data pull process was recently updated to allow full data download.  Full data pull is currently scheduled on Sundays.  This full run should allow PDP to capture missed terminations for the week.

Script should update the terminated employees in PDP.  Any related tables wherein the employee is acting as Supervisor (like user profile, goals, etc.) should be updated so that the employee no longer reflects as the current manager.

**Comment by telusdcinco** [comment]
This ticket created ods_employee_demo table which is updated when a full data pull is ran for Employee Demographics.  The table is truncated when full data pull starts and will only contain rows found in ODS.  

Comparing ods_employee_demo and employee_demo table to determine which employees are no longer in ODS and assumed to be terminated.

**Comment by telusdcinco** [comment]
For testing purposes, please run the command with options specified below.

php artisan command:GetODSEmployeeDemographics --manual --nodateupdate --alldata

**Comment by telusdcinco** [comment]
Deployed to Test.

Next Steps:
- run a full ODS data pull in Test
- compare ods_employee_demo and employee_demo tables
- provide possible past employees that reflects as active in PDP for confirmation
- generate the update scripts to update the date_deleted value for listed employees

The steps may need to be repeated in Prod in case there are additional past employees in Prod that are not captured in Test.

**Comment by steffipravasi** [comment]
https://bcgov.sharepoint.com/:x:/r/teams/02915/Shared%20Documents/Product%20Team/ZenHub1020-ActivePastEmployees-Test.xlsx?d=w9a8285982c8247128bb3ec4782279a0f&csf=1&web=1&e=qfs4M6

**Comment by Travis-A-Clark** [comment]
@steffipravasi Is there anything different about the list that you posted?

**Comment by telusdcinco** [comment]
The script for #1020 will do the following:
- delete user_reporting_tos entries for matching employee IDs
- delete shared_profiles entries for matching employee IDs
- lock account in user profiles
- remove reporting_to in user profiles
- delete preferred_supervisors entries for matching employee IDs
- assign 2023-07-01 for date_deleted in employee_demo table

**Comment by telusdcinco** [comment]
Command to run:
php artisan db:seed --class=DataFix_1020_Set_Date_Deleted_For_Past_Employees

**Comment by telusdcinco** [comment]
@Travis-A-Clark @steffipravasi 
Script completed in Dev/Test.  Please validate.

**Comment by telusdcinco** [comment]
@steffipravasi Yes, the listings are still looking at pre-processed details from last night.  The listing details should correct after running 1 of the overnight process (PopulateUsersAnnex).
Just triggered the process in Test.

**Comment by steffipravasi** [comment]
Perfect. Thank you. I'll confirm once the process finishes

**Comment by steffipravasi** [comment]
The next level manager will be displayed after the overnight process. Will confirm it tomorrow morning.

**Comment by steffipravasi** [comment]
Test validated. the past employees are not displayed in the active employees list. Although the past employees' names appear in the Reports to name column as a supervisor, but that is because the employee had multiple profiles.
