### ISSUE TITLE
Conversation Templates: Update Text

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#1022]
### Resources > User Guide > How to use the conversation template

Add "Example Questions" heading (below "Example Scenarios" heading) to each template type with the text below.

Performance Check-In

- Overall, how would you describe your work since our last check-in?
- What progress have you made against your goals?
- Have your goals shifted? Tell me about that.
- What accomplishments are you most proud of?
- What challenges have you faced? What did you learn?
- What support do you need from me as your supervisor to perform at your best?
- In what areas do you need or want to improve? What would help you improve?
- What motivates you to get your job done?

Goal Setting

- What goals can you add to your plan to help achieve team priorities?
- What competencies and values will you focus on to achieve your goals?
- What do you need to learn to achieve your goals? What gaps do you want to address?
- What are the barriers to your success? How will you overcome them?
- Imagine what success will look like: this can inform your personal performance measures (remember to pick results that are within your control and/or influence)
- What personal goals would you like to include in your profile?
- What support do you need to meet your goals?

Career Development

- What are your career goals? What do you think you need to get there?
- What specific goals would you like to achieve in the next year, two years, longer?
- What positions or opportunities are you interested in exploring within the BCPS?
- What do you want your next position to be?
- How would you define “success” for your career?
- What positive impact do you want your career to have on the Public Service (both short term and long term)?
- What is one thing I can do to support your career development?
- What is one thing you can do to support your own career development?

Onboarding

- Do you have a clear understanding of the expectations for this role?
- Have you received access to all of the information, tools, and resources you need to complete your responsibilities?
- What support do you need from me as your supervisor?
- Are there any specific tools or training sessions that would help you be more successful?
- Which aspects of the job are you excited / worried about?
- How do you prefer to receive feedback and/or recognition for your work?
- What would help you feel connected to the rest of the team? 

Performance Improvement

- Tell me about how things have been going for you in your role. What is going well? Where do you see opportunities for improvement?
- To meet expectations, what support do you need? This could be coaching, tools, resources, additional training, etc.
- Between now and our next conversation, I would like you to work on 2-3 areas we’ve discussed as requiring development. What specific steps will you take to meet these expectations?
- We will follow up on these areas and discuss your progress during our next meeting. If needed, we can discuss an action plan for improvement in each of those areas when we meet again.
- What else would you like to share with me?
- What support would you like from me?

### My Conversations > Conversation Templates > Instructions

Update text: 

Review the information below to determine which template best suits your needs. You can find additional info in the [User Guide](https://performance-332842-test.apps.silver.devops.gov.bc.ca/resources?t=3) to see example scenarios and questions for each topic.

Once you've decided on a template for use, select the participant and hit "Start Conversation" to alert participants you want to meet. Conversations will still need to be scheduled independently in your outlook calendar.

### All Conversation Templates > Attestation Section

Please change the attestation questions to:

"We have reviewed goals and adjusted as necessary"

"Performance expectations are clear"

**Comment by JonTelus** [comment]
These changes were just pushed to TEST, build should be complete in 10 mins or so.

**Comment by steffipravasi** [comment]
@JonTelus 
Can we update the following text: 
1) My Conversations > Conversation Templates > Instructions
Change text to: Once you've decided on a template for use, select the participant and hit "Start Conversation" to alert participants you want to meet. Conversations will still need to be scheduled independently in your outlook calendar.
![Screenshot 2023-07-06 at 11.03.36 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/3ecba22f-9bcb-45c2-825c-8802c5c3ee1a)
2) All Conversation Templates > Attestation Section
Change text to: Performance expectations are clear![Screenshot 2023-07-06 at 11.06.47 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/d77a0563-6072-472d-a986-6b84cf739507)

**Comment by Travis-A-Clark** [comment]
**Remaining Work**

See Steffi's screen captures above for images.

### All Conversation Templates > Attestation Section

Please change the attestation questions to:

We have reviewed goals and adjusted as necessary

Performance expectations are clear

This was done for some of the templates, but not all. The "Onboarding" and "Goal Setting" templates do not have the new text.

### My Conversations > Conversation Templates > Instructions

Update the second paragraph to: 

Once you've decided on a template for use, select the participant from the dropdown list and hit "Start Conversation" to alert participants you want to meet. Conversations will still need to be scheduled independently in your outlook calendar.

**Comment by Travis-A-Clark** [comment]
One final edit! Because we moved a few other things around in the resources section, we now need to update the link in the Conversation Templates instructions area. New link should be:

https://performance-332842-test.apps.silver.devops.gov.bc.ca/resources/conversations?t=1

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/59b313ca-7bd0-44f5-ae01-ff58fa6de329)

**Comment by jizhaogit** [comment]
URL updated

**Comment by steffipravasi** [comment]
Link has been updated to https://performance-332842-test.apps.silver.devops.gov.bc.ca/resources/conversations?t=1
