### ISSUE TITLE
User not notified after session time out on the Home page

### ISSUE THREAD

**Issue by steffipravasi** [bcgov/performance#1026]
https://bcgov.sharepoint.com/:i:/r/teams/02915/Shared%20Documents/Product%20Team/Tickets%20Requirements/1026/47b98f65-9877-4148-9224-0c58407fec6f.png?csf=1&web=1&e=7eTmgA
![Screenshot 2023-07-11 at 11.05.14 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/47b98f65-9877-4148-9224-0c58407fec6f)Issue has been extracted from ticket #913

Discussions made so far: 
Steffi: One thing I noticed while testing is that the session does not expire when I am on the home page. Why is that? I left user on Home page for overnight, and in the morning saw that the session is not expired. Shouldn't it function the same way as others? 

Ji: That is strange!! the session life time should be global which currently in TEST is set as 2 hours. no idea why the dashboard can keep it alive.....

Steffi: Do we want to look into it? Even after 2 hrs on the home page, I was able to access the website without the system logging me out. I was hoping that maybe on the click event of any button, the time out might trigger.

Ji: sure we can look into it but should this be another issue out of this ticket?

**Comment by jessicahjwu** [comment]
@steffipravasi Please check if this is still an issue

**Comment by steffipravasi** [comment]
@jessicahjwu This is still an issue.

**Comment by steffipravasi** [comment]
@jessicahjwu Verified on Dev, this is not an issue. The session timeout for test is somehow set to 12 hrs which is why we didn't receive the time out page. On dev the time is 2 hrs and works fine. We can close the ticket now.
<img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeE9SQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9207ecc80b7782dfd8b2b8fddd34dac3701f8f37/Screenshot%202024-08-27%20at%207.41.57%E2%80%AFPM.png" alt="Screenshot 2024-08-27 at 7.41.57 PM.png" />
