### ISSUE TITLE
Stats and Reporting > Excused Employees > Update excel download file

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#1027]
Sys / HR Admin > Stats and Reporting > Excused Employee Summary

In the Excel download file, remove these columns:
![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/317f2027-bee8-4e38-b123-39a527c45135)
<br>

And replace them with these columns from the Sys / HR Admin > Excuse Employees tab so that there is consistency.

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/77748f32-3e3e-4507-b554-4bb100ec4957)

**Comment by steffipravasi** [comment]
Test validated and columns updated for HR and Sys admin

**Comment by Travis-A-Clark** [comment]
As discussed, please take a look at syncing up the Excel download file with the HR/Sys Admin Excuse listing.

**Comment by steffipravasi** [comment]
Downloaded the Excused employees excel sheet for HR and Sys admin and they are the exact now. 
Validated for BC PSA and Citizen Services org. 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN284QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f240160dae69b0189f0cf001c7ce921239483c59/Screenshot%202023-10-16%20at%2012.20.19%20PM.png)

Moving ticket for PO review.

**Comment by steffipravasi** [comment]
Downloaded the Excused employees excel sheet for HR and Sys admin and they are the exact now. 
Validated for BC PSA and Citizen Services org. 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN284QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f240160dae69b0189f0cf001c7ce921239483c59/Screenshot%202023-10-16%20at%2012.20.19%20PM.png)

Moving ticket for PO review.

**Comment by Travis-A-Clark** [comment]
I am still seeing multiple issues. @steffipravasi Can you please verify and send back to Ji if required?

1. HR Admin results are not being filtered by the orgs they are supposed to have access to. Logged in as Travis Clark who has HR Admin access for PSA and Pension Corp (about 1,300 employees). The excused employee chart shows all 40,000 employees.

2. Looking at HR Admin > Excuse Employees for PSA and filtering by excuse column shows 44 people either auto or manually excused. Going to Stats and Reporting > Excuse Employees shows 57 people excused. Downloading the Excel for the 57 people shows the 13 additional people actually have an excused status of "no". Why are they being counted?

3. Downloading an Excel file takes quite a bit of time, even for a small group. I thought it wasn't responding and clicked multiple times. Can we add a "Processing" notification or something to let people know that work is going on in the background?

**Comment by steffipravasi** [comment]
@jizhaogit 
1) Fail - Issue still occurs when we download the excel sheet for HR admin
https://bcgov.sharepoint.com/:i:/r/teams/02915/Shared%20Documents/Product%20Team/Steffi%20-%20Testing/1027/Screenshot%202023-10-24%20at%2012.56.37%20PM.png?csf=1&web=1&e=Uzl9op
2)Pass
3) Pass - response time is 2-3 seconds

**Comment by jizhaogit** [comment]
Thanks Steffi. can you please help verify the #1 fixing? it should be addressed this time.  thank you!

**Comment by steffipravasi** [comment]
Test pass and validated. 
There are some still issues with the total numbers on the chart and I've added a new ticket 1141.
