### ISSUE TITLE
Text Updates and Edits for PDP 2.0

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#1028]
### My Goals > Create New Goal modal > Goal Description

- [x] Remove extra comma after the word "important"

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/23a8c3eb-363e-4e36-bc6c-a5b229c9eac0)

### My Goals > Goals Shared with Me

- [x] Update description at top of page to say "These goals have been shared with you by a colleague. You can view and comment on these goals and collaborate with others to track progress. Note that whoever created the goal is the one that can change the goal status to achieved or archived."

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/246a3dd4-4b0a-4438-ae56-c24e2021bd2b)

### My Team / HR Admin / Sys Admin > Share Employee Modal

- [x] In the attestation area, correct the spelling of "legitimate". 

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/19d8f5ea-c987-42df-8d17-e08310bdae2c)

### HR Admin / Sys Admin > Excuse Employee > View Excused History

- [x]  Add description at top that says: "This tab lists all instances where an employee was excused from the PDP process in the past. It can be used to help understand and troubleshoot why an employee’s next conversation due date was previously paused or restarted."

### HR Admin / Sys Admin > Goal Bank > Add a New Goal to Goal Bank

- [x] Change the text in the Display Name information toggle tip to say: "Describe who created or approved the goal content (i.e. PSA Human Resources). If you don’t enter anything here, your own name will be shown as the creator of the goal throughout the platform. This could be confusing for users who may not know you or your role in the organization." 

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/5c79ffef-6713-4751-852c-cad1202cff05)

### HR Admin / Sys Admin > Goal Bank > Manage Goals in Goal Bank

- [x] Keep the description at top of the page and add a second paragraph that says: **Be very careful modifying or deleting goals that were created by other people!** Your changes will impact everyone in the audience, not just those in your authorized area. If in doubt, connect with the original goal creator to discuss before taking any action.

**Comment by steffipravasi** [comment]
Test validated and text updated for HR and sys admin.

**Comment by Travis-A-Clark** [comment]
@jizhaogit Would it be a big pain the butt to move the Display Name button up to the top of the page for HR Admin and Sys Admin > Goal Bank?

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/ddd636da-97a9-4dac-88fe-6779dbb158b8)

**Comment by jizhaogit** [comment]
input field relocated

**Comment by jizhaogit** [comment]
I tried that way but it is confused user experience because tags is mandatory required.  if we place the display name in the same line will confuse the error notify.  
Please let me know if we still want to go this way.

**Comment by steffipravasi** [comment]
Well I would like to be in the same line as tags field. @Travis-A-Clark It would be your call :)

**Comment by jizhaogit** [comment]
LoL,  it is an easy modification anyway.

**Comment by Travis-A-Clark** [comment]
Let's put it on the same line. It's only for HR and Sys Admin, so I am less worried about their user experience and any confusion about mandatory fields, etc. Let's save space! :-)

Thanks!

**Comment by steffipravasi** [comment]
@jizhaogit The tags field is overlapping the display name field![Screenshot 2023-07-13 at 2.20.16 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/1b3f3616-6ad7-4d9f-aa4b-dfb4dc5f2174)

**Comment by steffipravasi** [comment]
Yes, seems like too much of work for now. We can roll back for now and I'll create a new ticket to figure out this issue.

**Comment by jizhaogit** [comment]
commit reverted

**Comment by steffipravasi** [comment]
Added a ticket to change the position beside the tags field #1039
Currently the field is displayed below the tags field![Screenshot 2023-07-13 at 3.24.28 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/13e69fd0-164f-4d80-a625-60ee8279dfac)
