### ISSUE TITLE
Resource > User Guide Updates

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#1029]
- [x] **In the "Welcome" section, second paragraph, add links to the text noted below:**

In addition to the guide, there are [tutorial videos](https://performance-332842-test.apps.silver.devops.gov.bc.ca/resources/video-tutorials) available to walk you through some common scenarios. There are also specific resources for [Goal Setting](https://performance-332842-test.apps.silver.devops.gov.bc.ca/resources/goal-setting) and [Performance Conversations](https://performance-332842-test.apps.silver.devops.gov.bc.ca/resources/conversations) that go into greater detail about best practice in each area, and a [Frequently Asked Questions](https://performance-332842-test.apps.silver.devops.gov.bc.ca/resources/faq) area with information about both the performance development approach and the PDP tool.

- [x] **In the "My Conversations Section", the paragraph under the "Conversation Templates" heading, update the link to:**
 
https://performance-332842-test.apps.silver.devops.gov.bc.ca/resources/conversations
![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/d0b39561-aaec-4b9e-bc03-fecb8fcab216)

- [x] **Move "How to use the conversation templates" section out of the User Guide tab to the top of the Performance Conversations tab.**

**Comment by Travis-A-Clark** [comment]
@jizhaogit Now that I see how the "How to use the conversation templates" looks at the top of Performance Conversations tab, can we move it to the second position and have the "What is a performance conversation?" go back to the top spot? So just switch them around.

Thank you!

By the way, do you like how I am using more and more screenshots? I am trying to be as good as Steffi! :-)

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/08cab83c-b39c-4a08-8490-ffdf35b9eada)

**Comment by jizhaogit** [comment]
@Travis-A-Clark great job and clear request!

**Comment by steffipravasi** [comment]
@jizhaogit The tabs in performance conversations are not interchanged as per Travis' comment![Screenshot 2023-07-12 at 5.11.24 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/785a603f-5a72-4b26-889e-49579a1b39c5)

**Comment by jizhaogit** [comment]
it is pushed to test now. it was taking time for waiting the pushing done

**Comment by steffipravasi** [comment]
User guide updated and validated on test.
