### ISSUE TITLE
Resources > Tutorial Videos Update

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#1030]
Add text and links below to the tutorial videos tab of the Resources section. 

---
**[Overview of Performance Development](https://youtu.be/L99OpfoHCiY)**
The BC Public Service is updating the current performance management approach to focus on meaningful career and professional development conversations between employees and supervisors. This means changes to the process and culture of performance management, supported by a new Performance Development Platform (PDP) replacing MyPerformance by fall 2023.

**[Setting a Goal in the Performance Development Platform](https://youtu.be/s-3mR1Oni84)** 
The My Goals section of the Performance Development Platform is intended to be a flexible environment that allows employees and supervisors to create and track goals in a way that works best for their team. Employees and supervisors can set work, learning, or career development goals and track progress. Goals stay in the system until they are completed, put on hold or withdrawn which lets you create long- and short-term goals.

**[Performance Conversations in the Performance Development Platform](https://youtu.be/TuaLsDRZJ1E)**
The Performance Development Platform supports employees and supervisors to have the right conversation at the right time. The My Conversations section of the Performance Development Platform is where employees and supervisors record and sign off on performance conversations every 4 months. This is also where you can find the templates to support your conversations including onboarding a new employee, goal setting, career development, performance check-ins or performance improvement.

**[Team Goals in the Performance Development Platform](https://youtu.be/h80op_O03AY)**
The Performance Development Platform is intended to be a flexible environment allowing employees and supervisors to create and track goals in a way that works best for their team. Creating goals that are shared among team members allows everyone to collaborate on a common objective. 

**[Setting Goals for Direct Reports in the Performance Development Platform](https://youtu.be/rythd_z-9so)**
The Performance Development Platform is a flexible environment that allows employees and supervisors to create and track goals in a way that works best for their team. Creating a goal for your direct report’s Goal Bank is an opportunity to create a common goal that can be personalized by employees.

**[My Team Section of the Performance Development Platform](https://youtu.be/JFijaF1maaU)**
The My Team section of the Performance Development Platform provides supervisors a dashboard of direct report details and access to their profiles including a summary view of how many active goals each employee has, when their next performance conversation is due, and whether or not they have been shared or excused in the PDP.

**Comment by steffipravasi** [comment]
Text and links updated and validate on test -> Video tutorials.
