### ISSUE TITLE
Resources > Replace the FAQ content

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#1031]
**Remove the content that is currently displayed on this Resources > FAQ and replace with the below. Do not auto-expand any headers on page load. All content is displayed as:**

### Header text for the question that should be displayed on the header / accordion when it is collapsed
Regular text below for the answer that should be shown when the header is clicked and the accordion is expanded.

----
### 1. Why is performance development important?
Performance development serves a range of functions that promote employee performance and career growth and organizational competitiveness, including:

- Supporting skill development and career planning
- Aligning individual goals with organizational goals
- Increasing individual and organizational accountability
- Recognizing and rewarding good performance and managing underperformance
- Identifying and developing the necessary capabilities for an effective workforce
- Increasing productivity
- Building employee engagement.

### 2. How often do I need to have performance conversations?
The Performance Development process requires employees to have one conversation with their supervisor every four months (three per year). The old MyPerformance system also required three conversations per year (Planning, Focusing and Sign-Off). There has been no change to this requirement. However, now the nature, topic and timing of the performance conversation is more flexible and can reflect the current needs of employee and supervisor.

### 3. How do I add a goal to my PDP profile?
Check out the this [video tutorial](https://youtu.be/s-3mR1Oni84) for an overview of this topic or continue reading below.

There are two ways to include a goal in your PDP profile. You can:

- Create a new goal using the “Create New Goal” function; or
- Import a goal that has been assigned to you by your supervisor or organization using the “Add Goal from Goal Bank” function.

When you launch the “Create New Goal” screen, you will be asked to select a goal type, goal title, and goal tags to help you identify and sort your goals. All three sections are mandatory. You can access more detailed information on these sections by clicking on the information “i” icon next to each heading in the app. There are best practice tips to set effective goals available in the [goal setting section](https://performance-332842-test.apps.silver.devops.gov.bc.ca/resources/goal-setting) of the app.

The second way to include a goal in your PDP profile is to import a goal from your Goal Bank. This is a list of goals created for you by your supervisor or organization. Some goals will be marked as mandatory, but most are suggested starting points for you to consider. You can click on a goal to view the details and add it to your own profile. If needed, you can edit the goal to personalize it once it is in your profile.

### 4. How do I share a goal with a colleague?
Check out the this [video tutorial](https://youtu.be/h80op_O03AY) for an overview of this topic or continue reading below.

Sharing a goal with a colleague is easy to do. Navigate to your My Current Goals page and locate the goal that you want to share. Click on the drop-down list under the “Shared With” heading, type in the name of your colleague, and save your selection. You can repeat this process to add additional colleagues to the goal.

The colleagues you selected will now see your goal on the tab “Goals Shared with Me”. They will be able to access the goal and add comments.

If needed, you can remove a colleague from your goal by going back to the “Shared With” drop-down and clicking “x” next to their name.

The person that originally created the goal will be able to change the goal status and mark it as achieved or archived on behalf of the group. This will move the goal to the Past Goals tab for all users with access to the goal.

### 5. How do I set up a performance conversation with my employee / supervisor?
Check out the this [video tutorial](https://youtu.be/TuaLsDRZJ1E) for an overview of this topic or continue reading below.

The My Conversations section is designed to support employees and supervisors to have the right conversation at the right time. The topic of each performance conversation does not have to be the same. The PDP has templates to support conversations focused on onboarding a new employee, goal setting, performance check-ins, career development, and performance improvement. Each of these count as a performance conversation.

To request a conversation with your employee / supervisor, navigate to My Conversations > Conversation Templates. Select the template that best matches the conversation you’d like to have, select the appropriate person from the participants drop-down menu, and click “Start Conversation”. This will send a notification to the other person that you would like to meet and will create a conversation file on your “Open Conversations” tab under either the “Open Conversations with my Supervisor” or “Open Conversations with my Team” heading.

Note that the conversation will still need to be scheduled independently in your Outlook calendar at a time that works for both you and your supervisor. There is no direct connection between PDP and Outlook calendar.

### 6. I am a supervisor. How do I create a goal in my team’s Goal Bank?
Check out the this [video tutorial](https://youtu.be/rythd_z-9so) for an overview of this topic or continue reading below.

Navigate to My Goals > Goal Bank > Team Goal Bank and click the button to “Add Goal to Bank”. You create a goal here just as you would for yourself and then select team members to push the goal out to in the “Audience” drop-down. You can include yourself in the audience if you’d also like to see the goal appear in your own goal bank.

This option creates a separate copy of the goal for each user that copies it from the goal bank. This means that you can add different comments to each team member’s version of the goal, and the goal status can be changed to achieved or archived for each team member individually without impacting the other users.

You can remove a goal from your team’s goal bank by navigating to My Goals > Goal Bank > Team Goal Bank and deleting the entry. This will remove it from all team members Goal Banks as well. Note that, if someone has already copied the goal into their own profile, they will keep their version of the goal even if you delete the original from the Goal Bank.

### 7. I’m a supervisor. I want to view my employee’s goals and upcoming conversation deadlines. How do I do this?
Check out the this [video tutorial](https://youtu.be/JFijaF1maaU) for an overview of this topic or continue reading below.

As a supervisor, you have access to a My Team page that has info about your direct and shared reports. Here you can find a summary view of how many active goals each employee has, when their next performance conversation is due, and whether or not they have been shared or excused in the PDP.

Please note that the next conversation due date is calculated by the PDP as part of an overnight background process. That means that an employee’s due date will not be updated to reflect a signed-off conversation until the day after sign-off is complete.

Clicking on an employee’s name will take you to their profile where you can view the details of their goals and conversations. You can add comments to their goals or any open conversations right in their profile.

You will see a banner across the top of the page letting you know when you are viewing an employee’s profile. To return to your own profile at any time, click the “Return to my profile” button in the top right corner. Clicking “back” in your web browser could cause log-in issues, so please use the “Return to my profile” option instead.

### 8. I do not see the correct supervisor in the PDP / I do not see the correct direct reports in the PDP. What do I do?
Reporting relationship data is pulled from PeopleSoft (our HR system of record) once every 24 hours. This data cannot be modified in the PDP.

If you want to add a shared supervisor for an employee in the PDP, you can have the current supervisor share the employee by clicking on the Yes / No under the “Shared” column on their My Team page.

If the data in PeopleSoft is incorrect, you will need to submit a service request through AskMyHR using the category HR Software Systems Support > Position / Reporting Updates.

**Note:** Employees that report to a position number in PeopleSoft that is vacant are automatically assigned one level higher in the organization hierarchy. If that next level is also vacant, the employee will see on their home page that their current supervisor is “No supervisor”.

**Note:** Employees that report to a position number in PeopleSoft that has more than one active employee associated with it (“double-bunked” positions) will see a dropdown menu on their homepage that allows them to select which of the supervisors associated with the position number is correct for them.

If a supervisor shares a position number with one or more additional employees in PeopleSoft (i.e. the supervisor is “double-bunked” in their position) they may not see the correct employees by default. In this case, their employees will be able to select the correct supervisor from a dropdown menu on the homepage under the “Current supervisor” heading. Once the employee has made the selection, the supervisor will gain access to that employee in the PDP.

### 9. Is there an autosave function on the application?
Yes, currently 20 minutes. After 20 minutes of not saving your work, the PDP will autosave any open windows and launch a pop-up window to let you know what happened and why.

### 10. Is there a timeout on the application?
Yes, currently 120 minutes. This timeout supports the corporate IM/IT Security Policy. To get back into PDP, simply click on the link to return to the application.

### 11. Can I access the PDP from home?
Yes, you just need to have the tool’s website URL. You can type that into the browser and you will be prompted for your IDIR login information.

### 12. What notifications and reminders will the PDP send me? Can I choose how often to receive an email from the PDP?
By default the PDP will generate in-app notifications on your homepage and send an email whenever someone:

- Makes a comment on one of your goals
- Adds a new goal to your goal bank
- Shares your profile with another supervisor
- Wants to set up a performance conversation with you
- Signs-off on a performance conversation with you
- Disagrees with the content of a performance conversation with you

And also:

- One month before your next conversation due date
- One week before your next conversation due date
- When your conversation is past due
- One month before your team member's next conversation due date (supervisors only)
- One week before your team member's next conversation due date (supervisors only)
- When your team member's conversation is past due (supervisors only)

Users have the option of opting out of receiving some of these emails. Notification options can be set on the [Account Preferences page](https://performance-332842-test.apps.silver.devops.gov.bc.ca/user-preference). You can access this page by clicking on your username in the top right corner of the app.

### 13. Who can assist me if I need help with the PDP?
Supervisors are supposed to help employees with their PDP profiles whenever possible. All supervisors and employees are encouraged to review the Resources Section of the PDP for a helpful user guide, tutorial videos, and best practice tips for setting effective goals and having effective conversations.

If you can’t find the answer after reviewing this material, you can escalate your request to your ministry contact listed in the Contacts section of the PDP.

If you are experiencing a technical issue, first check to see if the answer is in the PDP User Guide. If you cannot find the answer, please submit a service request through AskMyHR to My Team or Organization > HR Software Systems Support > Performance Development Platform.

### 14. How do I access past MyPerformance files?
You will not lose access to your past MyPerformance files. The MyPerformance system will remain online during the transition to performance development and the PDP. Once that transition is complete, the MyPerformance files will be made available to you in a secure archive. You cannot copy MyPerformance profiles directly into the PDP, though you can copy and paste any relevant text into the new format.

Sign-off by both parties in MyPerformance is required for the profile to be archived and made available.

### 15. Why are there no ratings in the new approach to performance development?

- During consultations, we heard from employees and supervisors that ratings were a major source of stress and not helpful in improving performance or guiding career development.
- Performance development is focused on looking forward to improve future outcomes rather than looking backward to grade past accomplishments.
- Performance development is designed to encourage regular conversations between an employee and supervisor rather than focus on an end-of-year rating conversation.
- The use of templates to support conversations focused on appreciation, coaching and evaluation allow us to recognize strong performance and support performance improvement without the use of ratings.
- The BC Public Service did not regularly use information MyPerformance ratings to guide talent and compensation decisions.
             - Ratings were not a valid source of evidence to inform these decisions as they were distributed unequally and inequitably across organizations, job types, and employee groups.
             - There was always an additional step outside of the MyPerformance rating in the talent or compensation process used to evaluate candidates. 

### 16. How can I qualify for a Pacific Leaders Scholarship if there are no ratings as part of performance development?
Requirements for the Pacific Leaders Scholarship will not change. To be eligible, your supervisor must agree that you are, at minimum, achieving expectations in your current role and that your career goals are consistent with the current or future needs of government. This information is collected in the Pacific Leaders form that your supervisor must submit as part of the application process. Your study plans must be described in your in the PDP.

### 17. How will I qualify for MCCF in-range compensation movement if there are no ratings as part of performance development?
MyPerformance ratings were not the deciding factor in determining in-range movement. A separate process was conducted each year to identify successful candidates for in-range movement depending on the criteria and quotas identified. This separate process will proceed as usual.

### 18. What do I do if one of my employees is not performing up to expectations?

There are supports offered in the PDP to help address different stages of performance concerns through targeted conversations and goal setting. At any stage, you can reach out to an HR Specialist through AskMyHR for additional support in having these conversations. You may also consider requesting short term coaching to review how you want to show up in the conversation.

If performance concerns are just starting to emerge or are not deemed significant, you will want to use the “Coaching” and “Action Items” areas of the Performance Check-In template. This documents that you began the conversation with the employee, offered support and coaching, and agreed on relevant follow-up actions. You are still free to use other sections of the template to celebrate successes or document additional aspects of performance discussions.

If performance concerns are significant or persist over time, you will want to progress to the Performance Improvement template. This template is more explicit in identifying performance issues, supports to be provided, and timelines for meeting agreed improvement measures.

If performance improvements are not made within agreed upon timelines, you should reach out to an HR Specialist through AskMyHR. The information that you have recorded in the PDP will provide important context and evidence to support the process as it is escalated.

You can also check out the section on “Addressing a Performance Issue” in the [Conversations Resource section](https://performance-332842-test.apps.silver.devops.gov.bc.ca/resources/conversations) of the PDP for additional assistance.

### 19. What happens when an employee clicks “I disagree with the information contained in this performance review”?
The supervisor will be notified by email and a note will be added to their PDP homepage. The disagreement is registered in the system and will be visible when a report is run by the employee’s ministry or PSA. In addition to clicking the “disagree” option, the employee must still sign-off the conversation using their employee ID to complete the process.

### 20. I am a supervisor and my employee clicked “I disagree with the information contained in this performance review”. What do I do?
When an employee disagrees with the supervisor’s comments and/or assessment, the employee has the option to check off this box when signing off on the conversation.

This is another opportunity for the supervisor and employee to discuss the employee’s perspective so that the supervisor can seek to understand and consider the employee’s concerns and reasons for disagreeing with the conversation.

The [Conversations Resources](https://performance-332842-test.apps.silver.devops.gov.bc.ca/resources/conversations) area of the PDP can support you in this discussion. You may find the sections on “Asking for Feedback/Inquiring Into the Other’s Perspective” and “Addressing a Performance Issue” particularly helpful.

If you would like to speak with someone for guidance and advice, we could forward your Service Request to an HR Specialist. You may also want to partner with a Coach by signing up for individual Coaching Services. Please visit MyHR for more information on Coaching and requesting Coaching.

### 21. I am a supervisor and I don’t have enough time in my schedule to go through this process with my employees. Why do we need to do this?
The [Accountability Framework for Human Resource Management](https://www2.gov.bc.ca/gov/content/careers-myhr/managers-supervisors/employee-labour-relations/conditions-agreements/accountability-framework) requires that all supervisors in the BC Public Service:

- Organize, direct and manage the performance of staff to meet operational requirements; and
- Provide regular on-going feedback to their employees on their performance and support employees’ career paths.

The performance development process requires employees to have one conversation with their supervisor every four months (three per year) to meet these supervisor accountabilities.

In addition, performance conversations are a rewarding investment of time.

- They are foundational to the strength of employee-supervisor relationships. These relationships are integral to attracting, developing, and retaining talent.
- They provide clarity to the employee on what is expected of them and insights to the supervisor about what’s important to each employee and what motivates them.

### 22. I support a ministry and need to have HR Administrator access for the PDP. How do I receive this status?
Please submit a request for PDP Administrator Access through AskMyHR. Choose "I am submitting this request as or on behalf of - Myself" and select the "HR Software Systems Support>Performance Development Platform" category. You will be provided with a request form that will need to be completed and signed off by your Executive Director or equivalent. 

Once you have this access you can do the following:

- View the employee list for your organization (including reporting relationships)
- Run reports for your ministry
- Excuse and share employees
- Create goals for your organization’s goal bank

**Comment by Travis-A-Clark** [comment]
And for the last two bullets in this section, can you please make them sub-bullets so they are indented farther?  I can't do it properly in this comment box, I don't think.

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/2b74ac84-eb67-4fe1-bdfa-0359999ca8be)

**Comment by jizhaogit** [comment]
all requests should be done. please verify. thanks

**Comment by steffipravasi** [comment]
@jizhaogit 
1) For Question 5 replace the link of video tutorial to https://www.youtube.com/watch?v=TuaLsDRZJ1E&feature=youtu.be
2) For Question 6 replace the link of video tutorial to https://www.youtube.com/watch?v=rythd_z-9so

**Comment by jizhaogit** [comment]
URL updated

**Comment by steffipravasi** [comment]
Links updated and validated on Test
