### ISSUE TITLE
Create Notifications for Goal Sharing and Comments on Shared Goals

### ISSUE THREAD

**Issue by steffipravasi** [bcgov/performance#1032]
Test scenario: Mark is the owner of the Goal "Goal 1_ABC". The goal is shared with Dave Richmond and Shawna Wilson. 
Issues: 

1) Dave and Shawna should receive notification (email and in-app) when Mark shares the goal with them; similar to when a goal is added to their goal bank.
<br>

2) If any of the 3 users add a comment to the goal, the other 2 should receive In-app notification as well as email; similar to when a supervisor comments on the goal.
<br>

3) Dave replied to a comment made by Mark. The notification says that 'Mark Bakusko replied to your Goal comment.' for in-app and 'PDP - Mark Bakusko Added a Comment on One of Your Goals' for email
Expected: The user name 'Dave' in this case must be displayed for the notification![Screenshot 2023-07-12 at 2.05.53 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/76129b8f-3ec0-47de-84a1-6a8b854fd494)![Screenshot 2023-07-12 at 2.05.44 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/3b9acc4e-bc10-42f3-99be-bbf9a02b0a6c)![Screenshot 2023-07-12 at 2.06.36 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/5d413cbb-d6a9-453d-bd0d-af7889994b29)

**Comment by telusdcinco** [comment]
@jizhaogit Please review changes for #1032.

**Comment by telusdcinco** [comment]
Migration required for additional templates.

Run 'php artisan migrate'.

**Comment by steffipravasi** [comment]
@telusdcinco 
**Test Data**
_Account: Travis Clark
Goal: Indigenous and Canadian Histories 101
Goals shared with:
Jessica Wu
Shawna Wilson - Citizens Services
Zehra LeRoy
Alex Stewart - Transportation and Infrastructure
Jeanine Manji_

1) Travis Added these 5 people to the goal
Expected result: Only 5 emails in total must be received
Actual result: Received around 11 total emails in the following order to people: Jessica, Jessica, Jessica, Zehra, Jessica, Jeanine, Jessica, Jeanine, Alex, Zehra, Zehra
-Jessica was added first and thats why she received emails multiple times when another user was searched and added to the shared with list
The same issue happened with in-app notifications
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbjh5IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--e84ed501a5391e08e33df33278b3eb1121475924/Screenshot%202023-08-24%20at%2012.08.54%20AM.png)

- The same happened when the users were removed from the shared with list. 

2) Travis didn't receive a notification when Shawna added a comment to the goal

**Comment by telusdcinco** [comment]
Fixes for both issues above pending build in Test.

**Comment by steffipravasi** [comment]
@Travis-A-Clark Dennis and I came to know that we currently have a limit of 10 for the comments in the goals. So the 11th new comment is not displayed in the list (notifications that a new comment is added are received though). It might become confusing for such cases but I am also not sure if users might add more than 10 comments in a goal. Looking for your suggestions here. 
We'll have to address this issue in a separate ticket.

**Comment by steffipravasi** [comment]
Test validated and the purpose of the ticket is addressed.

**Comment by Travis-A-Clark** [comment]
@steffipravasi Let's create a ticket to explore options for goals with more than 10 comments. Thanks!

**Comment by Travis-A-Clark** [comment]
@telusdcinco What account preference setting is this notification currently attached to? Does it have a check to see if they selected "Makes comments on one of my goals" or anything like that?

As discussed, we will have to update this list as well. Another new ticket!

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc2MrIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--24d1b5f3e495820e224a4fabc1eb955a34f08e56/image.png)

**Comment by telusdcinco** [comment]
The email notifications checks the global org access, and the 2 checked items on the image above.  1 for sharing goals, and the other is for adding comments.

**Comment by Travis-A-Clark** [comment]
Perfect. That works for now. I think we will have to add another option that says "Shares a goal with me" instead of relying on the "Adds a new goal to my goal bank" box, but it's not urgent. Thanks!
