### ISSUE TITLE
Migration from Training to Production for PDP Version 2

### ISSUE THREAD

**Issue by telusdcinco** [bcgov/performance#1035]
Tracking activities to be done for the deployment of approved changes into Prod.

Below are the checklist for the PDP Prod deployment:

- [x] Pre-Deployment Notifications | @Travis-A-Clark 
- [x] Backup Prod DB & Confirm Prod DB backup | @warrenchristian1telus
- [x] Create a copy of Training branch for deployment into Prod named Training_Copy_20230713 | @telusdcinco @jizhaogit 
- [x] Create a copy of Prod branch as backup named Prod_Copy_20230713 | @telusdcinco @jizhaogit 
- [x] Merge Training_Copy_20230713 branch into Prod branch;  Validate deployment conflicts, if any | @telusdcinco @jizhaogit 
- [x] Add config entry. | @telusdcinco @jizhaogit 
1. XDG_CONFIG_HOME=/var/www/html/storage
2. EMAIL_NOTIFICATION_ENABLED=true
3. PRCS_SCHED_LOG_RETENTION=365
4. PRCS_DATA_LOG_RETENTION=7
5. PRCS_PULL_ODS_DEPARTMENTS=on
6. ODS_DEPARTMENTS_URI=https://analytics-api.psa.gov.bc.ca/apiserver/api.rsc/Datamart_ePerform_meta_dept_org_hierarchy/
- [x] Run scripts, in order. | @telusdcinco @jizhaogit 
1. Run "php artisan db:seed --class=DataFix_968_ChangeAccessOrganizationKey"
2. Run "php artisan migrate:status" to confirm migration script list.
3. Run "php artisan migrate" to run pending migration items.
4. Run "php artisan db:seed --class=DataFix_796_GoalBankOrg_DeptID"
5. Run "php artisan db:seed --class=DataFix_1015_Setup_Conversation_Batches"
6. Run "php artisan db:seed --class=DataFix_1019_Prod2_Rollout"
7. Run "php artisan db:seed --class=DataFix_1020_Set_Date_Deleted_For_Past_Employees"
- [x] Run commands, in order. | @telusdcinco @jizhaogit 
1. php artisan command:GetODSEmployeeDemographics;
2. php artisan command:GetODSDeptHierarchy;
3. php artisan command:BuildOrgTree;
4. php artisan command:SyncUserProfile;
5. php artisan command:GetODSPositions;
6. php artisan command:UpdateGUIDByEmployeeId;
7. php artisan command:PopulateAuthUsers;
8. php artisan command:PopulateAuthOrgs;
9. php artisan command:SetNextLevelManager;
10. php artisan command:BuildAdminOrgUsers;
11. php artisan command:CalcNextConversationDate;
12. php artisan command:BuildEmployeeDemoTree;
13. php artisan command:PopulateUsersAnnexTable;
14. php artisan command:CleanShareProfile;
15. php artisan command:MaintainLogs;
- [x] Validate Prod. | @Travis-A-Clark @steffipravasi 
- [x] Post-Deployment Notifications | @Travis-A-Clark

**Comment by telusdcinco** [comment]
High level plan for deployment:
[Uploading... image.png]

**Comment by warrenchristian1telus** [comment]
Hi @telusdcinco. Just a thought - we could use a task list for this to illustrate when steps are complete and know who needs to do what.

Example starter plan for deployment with assignment:

- [ ] Pre-deployment notifications
- [ ] Backup production DB | @warrenchristian1telus 
- [ ] Create a copy of training branch...etc.

**Comment by warrenchristian1telus** [comment]
@telusdcinco backup has been completed (30 minutes ago).

**Comment by telusdcinco** [comment]
@warrenchristian1telus Thanks.  We are just pushing remaining items to Training.

**Comment by telusdcinco** [comment]
@Travis-A-Clark Can this ticket be closed?
