### ISSUE TITLE
Error when searching in Sys/HR Admin Excuse Employees

### ISSUE THREAD

**Issue by telusdcinco** [bcgov/performance#1038]
Error when searching in Sys/HR Admin Excuse Employees

![image.png](https://images.zenhubusercontent.com/60e88ef619e4760c8b3ee8bb/1db4de8d-7118-4bd9-8242-a8a8f5131b9a)

**Comment by telusdcinco** [comment]
@jessicahjwu  @steffipravasi Fix migrated to Test.

**Comment by steffipravasi** [comment]
![Screenshot 2023-07-13 at 4.28.27 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/b95184fa-0f26-40db-9560-406aec02aa7f)
