### ISSUE TITLE
Receiving 500 server error when adding zero goal from goal bank 

### ISSUE THREAD

**Issue by steffipravasi** [bcgov/performance#1042]
When there is no goal in the my goal bank, user can still click on the select all button and the 'Add selected goals to your profile' button becomes enabled. When clicked, pages give a 500 error.
Expected: Can we keep the button disable until there is atleast one goal in the goal bank
Issue on test, prod![Screenshot 2023-07-14 at 9.22.26 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/53136133-6cdf-4dd0-8c7a-406eae208611)![Screenshot 2023-07-14 at 9.22.59 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/ee433cd8-80ed-450e-8f6a-b48d0d5c42e6)

**Comment by steffipravasi** [comment]
@jizhaogit Issue still persist on goal bank ![Screenshot 2023-07-14 at 1.37.14 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/ab5666ec-3fa1-404b-867f-f1be77f5fd71)

**Comment by jizhaogit** [comment]
@steffipravasi it should be addressed now.

**Comment by steffipravasi** [comment]
Test validated. Button remains disabled until a goal is selected.
