### ISSUE TITLE
Supervisor can add/edit team members Team Goal Bank' goal

### ISSUE THREAD

**Issue by steffipravasi** [bcgov/performance#1045]
If a supervisor switches the profile to the team member via My Team -> Team members, then he must have the option to view only in goals. But currently the supervisor can add/edit a new goal to the Team Goal Bank section in Goal bank for team members who are also a supervisor

Expected result: Limit the supervisor to view only
Accounts used on test: Supervisor: Bakusko,Mark and team member: Wilson,Shawna
Screenshots:
https://bcgov.sharepoint.com/:i:/r/teams/02915/Shared%20Documents/Product%20Team/Tickets%20Requirements/1045/f7c86fe9-8f3f-4ed1-be72-aef5a46d0fc4.png?csf=1&web=1&e=eHc2Qq
![Screenshot 2023-07-14 at 9.57.40 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/f7c86fe9-8f3f-4ed1-be72-aef5a46d0fc4)
https://bcgov.sharepoint.com/:i:/r/teams/02915/Shared%20Documents/Product%20Team/Tickets%20Requirements/1045/b4f0db34-9f5e-4dd9-8793-7536f0defa17.png?csf=1&web=1&e=ZuLCgy
![Screenshot 2023-07-14 at 9.57.43 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/b4f0db34-9f5e-4dd9-8793-7536f0defa17)
https://bcgov.sharepoint.com/:i:/r/teams/02915/Shared%20Documents/Product%20Team/Tickets%20Requirements/1045/f4bd4d73-c46c-4fb0-90de-eb6bd85cc54e.png?csf=1&web=1&e=4zlfsm
![Screenshot 2023-07-14 at 9.58.40 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/f4bd4d73-c46c-4fb0-90de-eb6bd85cc54e)

**Comment by jessicahjwu** [comment]
Steffi - please verify if the ticket is still relevant.

**Comment by steffipravasi** [comment]
@jessicahjwu Can you please confirm if we need to fix this. The supervisor can still add a new goal or edit goal through team goal bank in the Goal Bank tab after switching the profile through the team member via My Team -> Team members
i) Do we need to hide the 'Add Goal to bank' button
ii) Display a view only mode if the goal title is clicked
<img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHhQQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4cbfd6ef2a4e09cd1c295de23360caa6d13a83e7/Screenshot%202024-06-10%20at%205.00.24%E2%80%AFPM.png" alt="Screenshot 2024-06-10 at 5.00.24 PM.png" />

**Comment by jizhaogit** [comment]
@steffipravasi Hi Steffi, the topic we discssed in the meeting should be addressed. please help verify. thank you!

**Comment by steffipravasi** [comment]
Verified:
<img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnhkQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2b95307546f49aec8d51d17c448d0a70c89e4e47/Screenshot%202024-06-13%20at%201.57.10%E2%80%AFAM.png" alt="Screenshot 2024-06-13 at 1.57.10 AM.png" />
<img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjFkQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--97f2a936d86752c5c4d8ef1fe2b7cebb6398ea5b/Screenshot%202024-06-13%20at%201.57.01%E2%80%AFAM.png" alt="Screenshot 2024-06-13 at 1.57.01 AM.png" />
