### ISSUE TITLE
Error displayed when searching in Unlock Conversations

### ISSUE THREAD

**Issue by telusdcinco** [bcgov/performance#1047]
Error displayed when searching in Unlock Conversations

![image.png](https://images.zenhubusercontent.com/60e88ef619e4760c8b3ee8bb/7fd168c7-69b3-452d-b1ae-181e1c3a3431)

**Comment by steffipravasi** [comment]
Test validated. Page does not throw error when using the search fields for unlock new conversation and manage existing unlocked conversation page

**Comment by steffipravasi** [comment]
Changed to title to 'Manage Existing Unlocked Conversations'![Screenshot 2023-07-14 at 4.47.18 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/c30dfce7-56b6-49ca-bb78-be259307d67c)
