### ISSUE TITLE
Update excused reason and status realtime

### ISSUE THREAD

**Issue by steffipravasi** [bcgov/performance#1048]
Excused a user manually, the excused status changes instantly but the Reason, Excused By and Excused At changes by the overnight process.
https://bcgov.sharepoint.com/:i:/r/teams/02915/Shared%20Documents/Product%20Team/Tickets%20Requirements/1048/d3a9a859-6ee6-4ff6-9911-af5062e24ba0.png?csf=1&web=1&e=1GIhg9
![Screenshot 2023-07-14 at 12.25.36 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/d3a9a859-6ee6-4ff6-9911-af5062e24ba0)
Expected: Can we make those 3 fields display results real-time

**Comment by Travis-A-Clark** [comment]
Connected to ticket #1001

**Comment by jizhaogit** [comment]
@telusdcinco Hi Dennis, i cannot find the ticket # from our repo history.

**Comment by telusdcinco** [comment]
MIGRATION NOTES:

Just code changes.

**Comment by telusdcinco** [comment]
@jizhaogit Please review code changes.

**Comment by jizhaogit** [comment]
looks good to me. thank you!

**Comment by steffipravasi** [comment]
@telusdcinco 
Blocker: The Excuse employees page for Hr & Sys admin throws an Ajax error
<img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGdNQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f69023f85fd927fe658502c0a89eaf5d878da2fe/Screenshot%202024-03-26%20at%203.02.20%E2%80%AFAM.png" alt="Screenshot 2024-03-26 at 3.02.20 AM.png" />

**Comment by steffipravasi** [comment]
Functionality working as expected for HR & Sys admin 
<img width="1740" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1lPQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5f154afdb0f133d38451d9413dfd9af1350bb79e/Screenshot%202024-03-26%20at%209.31.11%E2%80%AFAM.png" alt="Screenshot 2024-03-26 at 9.31.11 AM.png" />
