### ISSUE TITLE
Receiving Ajax error on unlock new conversation search results

### ISSUE THREAD

**Issue by steffipravasi** [bcgov/performance#1049]
Issue on test and prod
When trying to search results by entering the org and all levels, gives an Ajax error
![Screenshot 2023-07-14 at 12.52.06 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/ecee847f-fd38-4fa6-accd-3997e4aa53c8)
Also, for search criteria and search fields gives an error![Screenshot 2023-07-14 at 12.58.38 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/707eefa4-6bee-4e8a-ac1c-e3b14480fc1b)

**Comment by telusdcinco** [comment]
Pushed fix to Test, pending build.

**Comment by steffipravasi** [comment]
Ticket is similar to #1047. Test validated.
