### ISSUE TITLE
System / Data Requirements & Considerations

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#105]
- Connection with moodle (LC)?
- Connection with PeopleSoft (pull data)
- Export performance data to data warehouse (push to cube)

**Comment by kevindavidb** [comment]
The current overnight interface is doing two things with an employee’s Manager ID – it is first just displaying it in the record (this is what you can see in the Employee Listing), and it is also performing some logic chaining together all the Employee ID – Manager ID relationships to form a hierarchy.   Where there is a discrepancy between these two processes, the supervisor can get a “System Access Denied” error, as the Employee ID is listed as the direct report of the manager, but the reporting hierarchy is broken.

In the new system, to be determined would be if simply having a manager ID on your record is enough to give plan access, or is there a need for this hierarchy building to support plan access or for reporting purposes.
