### ISSUE TITLE
Sys Admin > Access and Permissions: update "reason" field and table columns

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#1052]
**Create New Access page**
- [x] Change "Reason for Assigning" to "Access Description"
- [x] Change toggle tip text to: List org levels (i.e. BCPSA - All; or SDPR - Corporate Services) followed by the role of the individual (i.e. SHR, Ambassador, Reporting). Full example: BCPSA - Corporate Workforce Strategies: Ambassador.
<br>
![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/befd6d29-f541-4881-9be7-4036b0f2445f)
<br>

**Manage Existing Access page**

- [x]  Remove table columns: Level 1, Level 2, Level 3, Level 4, Dept ID, and BU Assigned.
- [x]  Add column: Access Description (that displays the info captured in the changes outlined above on Create New Access page)

**Comment by steffipravasi** [comment]
@Travis-A-Clark Some questions here:
- Are we referring to the classification or organization column in the requirement to remove the Business Unit column in the Manage Existing Access page
- Since we removed the columns, do we need Levels 1-4 in the search fields?

**Comment by Travis-A-Clark** [comment]
Yes, please remove Dept ID column.

We don't need levels 1-4 in the search function, but I'm okay with leaving them there. No harm at this point.

The Business Unit column (BU Assigned) looks like it has already been removed (screenshot below form prod)
![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/0d3135d2-b881-4ea0-a97a-1d187771346c)

Thanks!

**Comment by steffipravasi** [comment]
@telusdcinco Assigning ticket to you

**Comment by steffipravasi** [comment]
@telusdcinco 
The dept column is still displayed in the manage existing access page![Screenshot 2023-07-21 at 5.50.20 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/1925cf43-d9b1-4002-a574-f0ce77f75774)

**Comment by steffipravasi** [comment]
Test validated. 
Dept column has been removed.

**Comment by Travis-A-Clark** [comment]
I still see Dept ID on the manage existing area, but it's fine. Let's move it over.

**Comment by steffipravasi** [comment]
You will need to clear out your entire browsing history, cookies and cache. Then when I saw the change :D![Screenshot 2023-07-21 at 6.15.52 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/edc9b6fd-b158-436e-8890-dfcabfc93ce2)
