### ISSUE TITLE
Prod: Employee record page gives 500 error when downloading the pdf

### ISSUE THREAD

**Issue by steffipravasi** [bcgov/performance#1054]
The employee record page in Sys admin is giving an 500 server error when clicked on the button 'Bulk download' and 'Download' 
User: 163102![Screenshot 2023-07-14 at 3.21.22 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/623df7d3-4ebb-4b6e-a6a9-32b5d5a5c33f)![Screenshot 2023-07-14 at 3.21.51 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/1f5133c2-7a9d-4946-88b2-5a789fbe10f1)

**Comment by telusdcinco** [comment]
@steffipravasi @Travis-A-Clark 
This is related to #1055
