### ISSUE TITLE
Create script to update date_deleted for terminated employees in PDP

### ISSUE THREAD

**Issue by telusdcinco** [bcgov/performance#1057]
Follow up ticket to #1020, to correct currently active employees in PDP who is no longer active in ODS.  The termination update form ODS may have been missed causing the employees to remain active in PDP.

Below is the SQL used to retrieve possible terminated employees in PDP.

select employee_id, empl_record, employee_name
from employee_demo as d
where not exists (select 1 from ods_employee_demo as o where o.employee_id = d.employee_id and o.empl_record = d.empl_record and o.date_deleted is null limit 1)
and d.date_deleted is null
order by d.employee_id, d.empl_record;

**Comment by telusdcinco** [comment]
@Travis-A-Clark @jessicahjwu 

Below is the list of possible terminated employees generated from Prod.

https://bcgov.sharepoint.com/:x:/t/02915/EVYPyyFdgdBBpMt17TjDsmEBA5qvuihXt43Vyd7bcdcYAg?e=Fb0h8v

**Comment by Travis-A-Clark** [comment]
@telusdcinco Just to confirm, this will only delete the record identified and not all records for an employee, correct?

For instance, the person below shows up on your list. It's only for record 1 though. So record 0 will still be intact?

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/f853f069-874c-4ff4-80f8-4f16605f5c7c)

**Comment by telusdcinco** [comment]
Comparison is done using both Employee ID & Record.  If both records show up on the list, both have disappeared in ODS.  The plan will be to update both rows with a date in date_deleted.
Please confirm if this is a case where in 1 row is still active in PeopleSoft but not the other one.

**Comment by Travis-A-Clark** [comment]
Yes, record 0 is still active. I can see Samantha online right now. Record 1 could be deleted. Thanks!

**Comment by Travis-A-Clark** [comment]
I have done a spot check on about 20 of these. If only the identified record ID will be deleted, this list looks good. Thanks!

**Comment by steffipravasi** [comment]
@telusdcinco The following past employees from the list you provided appears in the current employees list and not in the past employees page
1) 048716 
2) 142275
3) 167862
4) 171827

**Comment by steffipravasi** [comment]
https://bcgov.sharepoint.com/:x:/r/teams/02915/Shared%20Documents/Product%20Team/Steffi%20-%20Testing/ZenHub1057-ActivePastEmployees-Prod.xlsx?d=wa09f74228ab1455fba2ca0e155971901&csf=1&web=1&e=DSsxqF

**Comment by steffipravasi** [comment]
177102	1	Nadan,Devisha

**Comment by telusdcinco** [comment]
Rerunning script below in Test.
php artisan db:seed --class=DataFix_1057_Set_Date_Deleted_For_Past_Employees_Prod

**Comment by steffipravasi** [comment]
The employee with id 177102 and record 1 is no more a part of the current employee list. Looks good. Moving for PO review.
