### ISSUE TITLE
My Goals > Add "i" toggle tip for "Shared With" column

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#1060]
**Please add an "i" toggle tip next to the "Shared With" column header (similar layout to the "Status" column on the page).**

Text for toggle tip:

You can use this function to share a goal with colleagues. This goal will appear on their “Goals Shared with Me” tab and they will be able view and add comments to the goal. 

Type the name of your colleague into the search field to find and select them. You can repeat this process to add additional colleagues if needed. You can also remove a colleague by clicking the "X" next to their name.

As the creator of the shared goal, you are the only one that can make major edits or change the status to achieved or archived.

**Comment by steffipravasi** [comment]
Test validated on test region
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaVVvIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a16fb4dcb938f7d38ed6ce83b6e0777c5ac6ba97/Screenshot%202023-08-22%20at%2012.25.25%20PM.png)
