### ISSUE TITLE
My Goals > Goal Bank > Add Goal: missing "Work" goal option

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#1061]
As a supervisor, when I create a goal for my team in the Goal Bank tab of My Goals, I don't have the "work" goal type option in the drop down. 

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/7085f8f6-625f-4d1b-8a01-56697f6c6a4c)

**Comment by steffipravasi** [comment]
Issue only encountered on Prod. Can see the work goal type in test so will need to verify once we push the ticket to prod.
Test:
![Screenshot 2023-07-17 at 12.36.01 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/c93b2e58-182b-4442-9db9-5578e90e987a)
