### ISSUE TITLE
Update HR / Sys Admin > Goal Bank Modals

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#1062]
### HR/Sys Admin > Goal Bank > Create New Goal

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/7a0e7736-b42c-4470-b27f-9d950087f96d)

Update text to: 

Are you sure you want to create the goal and assign to the selected audience? 

Only click "Add New Goal" one time. It can take up to 30 seconds to process. Clicking multiple times will generate multiple copies of the goal and all notifications.

### HR/Sys Admin > Goal Bank > Manage Goals in Goal Bank > Edit Individual Audience

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/a9ef003d-4d5c-4269-8006-e8b702902144)

Update text to:

Are you sure you want to add selected individuals to the audience? 

Only click "Update Goal" one time. It can take up to 30 seconds to process. Clicking multiple times will generate multiple copies of the goal and all notifications.

### HR/Sys Admin > Goal Bank > Manage Goals in Goal Bank > Edit Business Unit Audience

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/d94a25d6-a982-4324-b97b-7c308e6e114a)

Update text to:

Are you sure you want to add selected business units to the audience? 

Only click "Update Goal" one time. It can take up to 30 seconds to process. Clicking multiple times will generate multiple copies of the goal and all notifications.

**Comment by Travis-A-Clark** [comment]
@telusdcinco 

Changes applied except in Manage Existing Goals > Edit Individual Audience. Still see message below.

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/a5db3a9d-a851-4d39-b012-83326abe4d2c)

**Comment by Travis-A-Clark** [comment]
Actually, wording in first sentence of Manage Goals > Edit Business Unit Audience is also off.

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/796e763f-68f3-4b4d-8bc8-ea5dbff9beac)

Update text to:

Are you sure you want to add selected business units to the audience?

Only click "Update Goal" one time. It can take up to 30 seconds to process. Clicking multiple times will generate multiple copies of the goal and all notifications.

**Comment by steffipravasi** [comment]
@telusdcinco Only a minor change in Manage Goals > Edit Business Unit Audience. Can we remove the additional question mark please.
![Screenshot 2023-07-19 at 10.40.16 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/166edeef-3754-462a-a099-8c70d131ed0f)

**Comment by steffipravasi** [comment]
Text have been updated.
