### ISSUE TITLE
"My Conversation" page not fully loaded - missing text box descriptions

### ISSUE THREAD

**Issue by jessicahjwu** [bcgov/performance#1064]
Chris Mutadi, Employee ID 131454, PDP User ID 20750. He has had issues with the "My Conversation" page not loaded fully (missing descriptions of each text box):

![Chris Mutadi 1.png](https://images.zenhubusercontent.com/641a1dcfdf400e29dabf707e/77b49872-272c-4e65-8cd2-3cb260b8fd71)

It sounds like this issue happened occasionally, as we were able to see open conversations that are currently in his profile with all the descriptions loaded. The user uses Azureidir to log on.

**Comment by telusdcinco** [comment]
![image.png](https://images.zenhubusercontent.com/60e88ef619e4760c8b3ee8bb/81123be9-7351-458c-9972-15f84590b2ae)

**Comment by steffipravasi** [comment]
Not able to test or reproduce this issue on test in any of the browsers - Edge, Chrome, Safari, Firefox. Ji has applied a fix and we can push it to training and prod env and check if its happening for any user then.

**Comment by telusdcinco** [comment]
@jizhaogit @Travis-A-Clark Code changes also includes changes for #1065.

**Comment by Travis-A-Clark** [comment]
As discussed at this morning's scrum, I can replicate this issue in TEST and TRAINING when I log in through IDIR and go directly to the conversations page to set up a new conversation. Once it loads properly the first time, it continues to load properly all the times after. 

Error message received:

Uncaught TypeError: Cannot read properties of undefined (reading 'setReadOnly')
    at a.setReadOnly (ckeditor.js:290:473)
    at Object.success (upcoming?id=881&ownerrole=mgr:2227:69)
    at c (jquery.min.js:2:27742)
    at Object.fireWith [as resolveWith] (jquery.min.js:2:28487)
    at l (jquery.min.js:2:78789)
    at XMLHttpRequest.<anonymous> (jquery.min.js:2:81117)
upcoming?id=881&ownerrole=mgr:3152 hide

**Comment by steffipravasi** [comment]
Was able to reproduce this issue again. 
Noticed it happening only when the user logs in to the browser through IDIR for the very first time. Works fine once the page is refreshed or the conversation is opened again.
Test data: Logged into Edge for the first time with IDIR
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbmt3IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--44c6847ab5bb14acbdd1226f26e5c32df181e92a/Screenshot%202023-08-23%20at%203.37.29%20PM.png)

**Comment by jizhaogit** [comment]
As discussed, i enclosed all the initial js in the document ready.

**Comment by steffipravasi** [comment]
WIssue is still not fixed. 
Was able to reproduce the issue on Safari
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBalUzIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7916089844bd153464778dadd4e2745461e14b4b/Screenshot%202023-08-24%20at%201.53.01%20PM.png)
As discussed in the meeting today, we'll be pushing this fix to Training.

**Comment by Travis-A-Clark** [comment]
Pushing this update and continuing troubleshooting on ticket #1099.
