### ISSUE TITLE
Comments were not saved in "My Conversation" although user has clicked on the save button

### ISSUE THREAD

**Issue by jessicahjwu** [bcgov/performance#1065]
Chris Mutadi, Idir cmutadi, Employee ID 131454, PDP User ID 20750, has had issues happened before in which he put comments in on the "My Conversations" page, saved - but when he went back again the data was gone. Page was fully loaded with text box descriptions in this case.

**Comment by telusdcinco** [comment]
![image.png](https://images.zenhubusercontent.com/60e88ef619e4760c8b3ee8bb/29381c48-b8f1-4022-a4a6-d4eddc3638ec)

**Comment by steffipravasi** [comment]
Not able to test or reproduce this issue on test in any of the browsers - Edge, Chrome, Safari, Firefox. Ji has applied a fix and we can push it to training and prod env and check if its happening for any user then.

**Comment by telusdcinco** [comment]
@jizhaogit  @Travis-A-Clark   Code changes for this ticket is part of #1064.
