### ISSUE TITLE
Adding time stamp to the open conversations overview section

### ISSUE THREAD

**Issue by jessicahjwu** [bcgov/performance#1066]
To add two time stamps to the open conversation overview section, so users are able to see that information without having to click into each record:
1. Date created
2. Last updated

![image.png](https://images.zenhubusercontent.com/641a1dcfdf400e29dabf707e/1088a983-4f80-4d8f-bab4-86eba741cfad)

**Comment by steffipravasi** [comment]
@jizhaogit Two issues here:
1) Wondering why does all the conversations have the Last Updated date as today even though none of the conversations are updated?
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcDh3IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--72ea9d8f6538685dab3bfa2a135c911a22166281/Screenshot%202023-08-23%20at%204.14.54%20PM.png)
2) The completed conversations page does not open and throws an error
Account used: Travis Clark
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcW93IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--30a231a69b0f2f9462c01637e9cf5cb9b8e987f4/Screenshot%202023-08-23%20at%204.19.50%20PM.png)

**Comment by jizhaogit** [comment]
the sign off date added caused the data tale columns not matched.  issue addressed. thanks!

**Comment by steffipravasi** [comment]
@jizhaogit I've got a question. 
Will the Last Updated column only be updated when either of the users signs the conversation?

**Comment by jizhaogit** [comment]
that is correct. the "Last Update" is the latest date for employee sign off or supervisor sign off

**Comment by steffipravasi** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBck0yIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--9a3689256a49ffe3d88650697e22031b07b6092d/Screenshot%202023-08-24%20at%2012.32.50%20PM.png)

**Comment by Travis-A-Clark** [comment]
@jizhaogit The ticket works as expected. Thanks!

Just wondering if we could expand the definition of "last updated" to include saving new comments, etc. Basically, instead of latest sign-off date, could it be last saved date?

**Comment by jizhaogit** [comment]
@Travis-A-Clark yes we can, we have a "updated at" column in the table to store the latest update time. will move this ticket back to in progress for this modification.

**Comment by steffipravasi** [comment]
Test validated. Last updated column updates when comments are saved or signed-off.
