### ISSUE TITLE
Test comment text boxes for content and do not prompt the "losing unsaved changes" message if it's committed

### ISSUE THREAD

**Issue by jessicahjwu** [bcgov/performance#1067]
Can the system be implemented with an additional check on the conversation comments to see if the content is different from the last updated record? If there are changes and not saved, prompt the message of "if you continue you will lose any unsaved changes". And if it's been saved, do not prompt the message?

![image.png](https://images.zenhubusercontent.com/641a1dcfdf400e29dabf707e/78cc3055-1004-4c03-bb64-22f9e8b94231)

**Comment by steffipravasi** [comment]
Once the conversation modal is closed after auto-save, the 'Comment Saved' text keeps displaying even when opened again. Is it possible to remove the text? In fact the text stays even after one person signs off the conversation.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaElRIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b3879769c58beab2f66138cf61679a8093a70b2a/Screenshot%202023-08-17%20at%201.32.41%20AM.png)

**Comment by steffipravasi** [comment]
@jizhaogit as we discussed, this issue can be fixed while we are fixing the conversations modal

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaWtXIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--17400b36a1fa4b8d0fc40c28b1a67988ff48706b/Screen%20Recording%202023-08-17%20at%205.53.21%20PM.mov)

**Comment by jizhaogit** [comment]
@steffipravasi as we discussed, i updated the "comment save" application behavior.

**Comment by jizhaogit** [comment]
as we discussed. currently after the "auto save" notification populated and users clicked the confirm button, the red message "comment saved" will not show again.

**Comment by steffipravasi** [comment]
@jizhaogit The issue of displaying "if you continue you will lose any unsaved changes" message if auto saved and no changes are made still  persist in the following case.
Account used: Travis Clark

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbjhqIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d6ecc0e113286737ce775e7fa0dd52230f98b28e/Screen%20Recording%202023-08-21%20at%207.55.07%20PM.mov)

**Comment by jizhaogit** [comment]
@steffipravasi issue should be addressed. thanks!

**Comment by steffipravasi** [comment]
@jizhaogit I am sorry to do this, but the Save button is missing when the text is added or edited

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdmtwIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3728020f03aa17064b0bac62c3bf4c449e614ef3/Screen%20Recording%202023-08-22%20at%205.00.57%20PM.mov)

**Comment by jizhaogit** [comment]
this bug is cause by the ckeditor enclosing.  should be fixed now.

**Comment by steffipravasi** [comment]
Test validated and all the reported issues have been addressed.
