### ISSUE TITLE
In Sys/HR Admin Goal Bank, in-app notification gets turned off when "Adds a new goal to my goal bank" is unchecked in Account Preference.

### ISSUE THREAD

**Issue by telusdcinco** [bcgov/performance#1068]
In-app notification should be turned on in Sys/HR Admin Goal Bank.

![image.png](https://images.zenhubusercontent.com/60e88ef619e4760c8b3ee8bb/fa294bf1-3daf-41da-a41b-7b770a076ef4)

This prevents the recipient from getting in-app notifications when a goal is shared with the user.

**Comment by steffipravasi** [comment]
![Screenshot 2023-07-21 at 12.35.09 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/d55a692a-b47f-4cb9-bd01-a4b8e2b52cf8)![Screenshot 2023-07-21 at 12.35.23 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/b41cdbf6-4730-4125-92bf-74d205dbad9a)
