### ISSUE TITLE
Upgrade from PHP 8.0 to 8.1

### ISSUE THREAD

**Issue by telusdcinco** [bcgov/performance#1071]
Upgrade from PHP 8.0 to 8.1

**Comment by jessicahjwu** [comment]
Pipelines: Product Backlog
Sprints: Dec 18 - Dec 29, 2023
Estimate: 2
Epics: DevOps

**Comment by jizhaogit** [comment]
Dev is upgraded to PHP 8.1   Please help verify.  thanks!

**Comment by jizhaogit** [comment]
just code migration

**Comment by steffipravasi** [comment]
Very High-Level Page checklist for the upgrade testing: https://bcgov.sharepoint.com/:w:/r/teams/02915/_layouts/15/Doc2.aspx?action=editNew&sourcedoc=%7B1dc1cb82-4c5e-4d62-875a-43c0f4fc0dc5%7D&wdOrigin=TEAMS-ELECTRON.teamsSdk_ns.bim&wdExp=TEAMS-CONTROL&wdhostclicktime=1712630069334&web=1

**Comment by jizhaogit** [comment]
I just made 2 backup branches for training and prod:
jz-training-backup-20240412
jz-prod-backup-20240412
