### ISSUE TITLE
Notification Log Clean Up

### ISSUE THREAD

**Issue by telusdcinco** [bcgov/performance#1072]
Notification Log Clean Up

Notification Log page entries is growing.  Update MaintainLogs process to include Notification Logs in clean up steps.

**Comment by telusdcinco** [comment]
See #1074 for related issue(s).

**Comment by Travis-A-Clark** [comment]
As discussed, let's set the log to a six month retention period. Thanks!

**Comment by telusdcinco** [comment]
Add in .env for custom retention days.  Otherwise will default to 180 days.

PRCS_NOTIFICATION_LOG_RETENTION=180

**Comment by telusdcinco** [comment]
Modified existing process (MaintainLogs) to include clean up of notification_logs table based on value in PRCS_NOTIFICATION_LOG_RETENTION.

MaintainLogs currently runs daily at 6am.

Change pushed to Dev/Test, pending build.

**Comment by telusdcinco** [comment]
Log generated.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBajliIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--c0b34fed92f82b5220e55bf940dff7c33b31ecac/image.png)

**Comment by steffipravasi** [comment]
@telusdcinco Wondering why are we seeing the logs from Sep 2022? I am guessing we should only see logs from the past 6 months and not more than that. 
Env: Test
User: Travis 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBakpkIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6fa2e7eae3d8e97a9826cdfc8c5303aa19a56091/Screenshot%202023-08-31%20at%209.34.31%20PM.png)

**Comment by telusdcinco** [comment]
@steffipravasi The overnight process (MaintainLogs) needs to run for the changes to take effect.  Below is the process logs for Sept 1, 2023.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbmRnIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--0135f673408229804df2467a21139f759398369c/image.png)

**Comment by Travis-A-Clark** [comment]
Records in PROD still showing back to Sept 2022. Need to check on Monday.
