### ISSUE TITLE
Search Notifications throws an Ajax error

### ISSUE THREAD

**Issue by steffipravasi** [bcgov/performance#1074]
Searching the notification log by the recipient gives an Ajax error
Account: Travis
Recipient: Lisanne Watt![Screenshot 2023-07-21 at 5.32.50 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/b8c02dbc-3cc1-46ce-b2bc-73e5e2aeac68)

**Comment by Travis-A-Clark** [comment]
This looks to be a problem in TEST but not in TRAINING or PROD. Any idea why it would be different?

**Comment by telusdcinco** [comment]
As discussed with James, the non prod have a modified logic for retrieving notification logs.  In Dev the emails are pushed to Travis, while in Test the emails are pushed to Steffi.  In Prod, it is straight forward.

Also the notification log is growing with row counts below, as of 8/29 10:30
Prod: 131923
Test: 543606
Dev: 48411

May need an automated clean up for the notification log table.  Please provide retention period for the notifications.

To fix the timeout happening in Test, may need additional indexing on the table to improve query performance.

**Comment by telusdcinco** [comment]
Just noticed there is a ticket for Notification Log clean up #1072.

**Comment by steffipravasi** [comment]
Test validated and purpose of the ticket is achieved. No Ajax errors are thrown while searching through the notifications.
