### ISSUE TITLE
Average Active Goals in Goal Summary displays zero for all orgs

### ISSUE THREAD

**Issue by steffipravasi** [bcgov/performance#1075]
The Average Active Goals in Goals Summary page for Hr and Sys admin displays zero for any org selected.
Expected: The number must calculate for all orgs![Screenshot 2023-07-25 at 9.18.08 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/d96826b7-7a44-4b6d-aa67-38373b3d941e)

**Comment by steffipravasi** [comment]
@Travis-A-Clark Me and Ji need some clarification on how the number must be calculated to display here.

**Comment by Travis-A-Clark** [comment]
Total # of goals divided by the number of employees in the business unit selected. Only active, no past or excused.

**Comment by Travis-A-Clark** [comment]
This appears to be working in PROD but not TEST. Don't know if this is a quick fix / rollback or if it will take more time.

**Comment by Travis-A-Clark** [comment]
I'd like to push this at the same time as ticket #979.

**Comment by jizhaogit** [comment]
our test number is too small for 100% average, so i changed it to display 0.0000 number

**Comment by steffipravasi** [comment]
Org: BC PSA
Site results: Average Active Goals Per Employee
0.0849
Expected: 0.0804
Average Active Work Goals Per Employee - 0.0507
Expected: 0.0520
Average Active Learning Goals Per Employee - 0.0238
Expected: 0.0061
Average Active Career Development Goals Per Employee - 0.0060
Expected: 0.0245

**Comment by jizhaogit** [comment]
export excel for goals chart does not include private goals but average number includes the private goals

**Comment by steffipravasi** [comment]
@Travis-A-Clark Should the private goals be included in the average active goals count?

**Comment by jizhaogit** [comment]
to match the result between the average part and chart part we have 2 choices:
1. disable private calculation in the average part to map with charts
2. enable private chart in the charts to map with average.

**Comment by Travis-A-Clark** [comment]
I think it would be best if we included private goal counts everywhere. So enable them in the counts/charts.

**Comment by steffipravasi** [comment]
@Travis-A-Clark does that mean to add to this chart as well? If yes, we'll need to add a private goal column to the excel chart as well
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdkVoIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--493257d4cc9010ae61f9cb1f28bd46968476995c/Screenshot%202023-08-21%20at%203.01.30%20PM.png)

**Comment by jizhaogit** [comment]
yes i think so - to add private goals in everywhere of the statistic goal summary report

**Comment by steffipravasi** [comment]
Added a new ticket #1094

**Comment by jizhaogit** [comment]
ticket link with 1094

**Comment by steffipravasi** [comment]
@jizhaogit Is it possible to keep the height of these boxes same?
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcXdwIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--f763227075915978add72d2abe875063f52a720a/Screenshot%202023-08-22%20at%204.08.24%20PM%20copy.png)

**Comment by steffipravasi** [comment]
Test validated. 
Private goals have been added to the charts and counted in the Goal summary.

**Comment by jizhaogit** [comment]
Average number changed to 0.00 format

**Comment by steffipravasi** [comment]
Test validated and numbers looks good.
