### ISSUE TITLE
Expand Org Tree Levels to 6

### ISSUE THREAD

**Issue by telusdcinco** [bcgov/performance#1076]
Currently, PDP have page filters up to Level 4.  The org tree processed stores up to Level 5.  Due to some employees not showing up at Level 6, the org tree needs to expand to accommodate Level 6 details.

**Comment by telusdcinco** [comment]
The following processes needs to run once before changes will reflect.
- php artisan command:GetODSDeptHierarchy;
- php artisan command:BuildEmployeeDemoTree;
- php artisan command:PopulateUsersAnnexTable;

**Comment by jessicahjwu** [comment]
Julia Iwama, EE ID 178934 @steffipravasi

**Comment by steffipravasi** [comment]
Test validated. Employee 178934 is in the active employee list now and is able to login. 
Also verified the employees within the following Dept id shared by Dennis on teams:
134-1766
134-1768
134-1762
134-1589
134-5163
