### ISSUE TITLE
Date added and Created By fields in Goal Bank does not function correctly

### ISSUE THREAD

**Issue by steffipravasi** [bcgov/performance#1077]
Issue extracted from #822
1) My Goals -> Goal Bank -> My Goal Bank
If we select a date in the Date added field, the results are not being filtered and the accordion is collapsed with the date field not displaying the entered date 
Expected result: The results must filter, the entered date must display in the field and accordion must remain expanded![Screenshot 2023-07-31 at 11.42.05 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/3c4a648d-30da-4db7-b1ac-0466ddf5eb07)

2) My Goals -> Goal Bank -> Hidden Goals -> Date Added field
If a date is entered in the date field, the filters does not respond to the entered date. ![Screenshot 2023-07-31 at 1.55.54 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/83f2c211-c97c-42d5-8ced-f3a9d27a2d1c)

3) My Goals -> Goal Bank -> Hidden Goals -> Created By field
When a name is selected from the drop down, the results are not filtered accurately![Screenshot 2023-07-31 at 1.58.22 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/181c3147-31ef-45d7-8ba2-b65717d9c615)

4) When I am using the Created by field to search in the My Goal Bank section, the Hidden Goals results are also filtered with the entered created by
Issue also occurs vice versa.
![Screenshot 2023-07-31 at 1.58.22 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/492f113f-f857-4071-9d2d-b33d83e5d489)

**Comment by jizhaogit** [comment]
issue addressed

**Comment by steffipravasi** [comment]
@jizhaogit issue number 1,2,3 are not resolved yet. 
1 & 2) If a date is entered in the date field, the filters does not respond to the entered date.
My Goals -> Goal Bank -> My Goal Bank
My Goals -> Goal Bank -> Hidden Goals![Screenshot 2023-08-10 at 2.15.10 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/35ff5ae6-1c88-4331-8ad7-fb986d2f577f)

3) My Goals -> Goal Bank -> Hidden Goals -> Created By field
When a name is selected from the drop-down, the results are not filtered accurately
![Screenshot 2023-08-10 at 2.19.04 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/85550093-21ca-483b-a680-f92822e21a25)

4) Resolved

**Comment by jizhaogit** [comment]
issue 1, 2 and 3 should be addressed
