### ISSUE TITLE
Goal when tried to hide, adds to the current goals list instead

### ISSUE THREAD

**Issue by steffipravasi** [bcgov/performance#1078]
Supervisor: 169412	Hoyle,Meaghan	Meaghan.Hoyle@gov.bc.ca
Employee: 134118	Hannigan,Jessie L	Jessie.Hannigan@gov.bc.ca
Supervisor added a goal 'CareerGoalAug2' in the Team Goal Bank section
Employee Jessie can see the goal in the goal bank and has only one goal in the My Goal Bank section
Regardless of the Jessie checking any of these checkboxes and hits the 'Hide Selected Goals' button, user is navigated to the Current goals page and goal is added to current list![Screenshot 2023-08-02 at 2.20.18 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/0a724189-0ad3-40d0-94a0-1f569cae3ed7)
Expected: Goal must be hidden and not added to Current Goals
Browser: Chrome
Refer to the recording for clarification: https://bcgov.sharepoint.com/:v:/r/teams/02915/Shared%20Documents/Product%20Team/Steffi%20-%20Testing/1078.mov?csf=1&web=1&e=Rd6sPP

Issue related to ticket: #822

**Comment by steffipravasi** [comment]
@jizhaogit 
2 issues I have noticed here:
1) For an employee with only one goal in the goal bank, when tried to select the goal and hit the Hide goal button receives a 500 Server error![Screenshot 2023-08-08 at 1.15.16 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/c1670371-e152-4fbf-b302-8ca9f1fec343)
To reproduce we can use the employee account: 134118 Hannigan,Jessie L Jessie.Hannigan@gov.bc.ca
2) For employee with multiple goals in the goal bank, when the goal added from Team goal bank by supervisor![Screenshot 2023-08-08 at 1.14.16 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/9277ba1d-35d3-4fb2-8a91-eb9bf4076c36) is selected, the buttons does not enable
User account: Wilson,Shawna

**Comment by jizhaogit** [comment]
#1  the employee id have 2 employee records:
![image.png](https://images.zenhubusercontent.com/620163b737f8d3386467e70d/a71629b2-213a-4144-86d4-22baccab93c9)
please try not use this kind of case because it will cause query error about the goal processing

#2 issue fixed.

**Comment by steffipravasi** [comment]
@jizhaogit 
Issue 2 is fixed but Issue 1 is still occurring. This time I have used an employee with a single record and still received an error. 
Employee: 004637	| Nicole Jackson  | Nicole.Jackson@gov.bc.ca
Supervisor: 025787	Douglas Hill
![Screenshot 2023-08-10 at 2.01.21 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/38d9234e-9b8e-4575-a24e-46dc2bb141a9)

**Comment by jizhaogit** [comment]
issue is addressed

**Comment by steffipravasi** [comment]
Issue has been resolved and validated on test region. 
Accounts used: Employee: 004637 | Nicole Jackson | Nicole.Jackson@gov.bc.ca
Supervisor: 025787 Douglas Hill
Moving ticket for PO review.
