### ISSUE TITLE
Supervisor not assigned to user although user has multiple current supervisors

### ISSUE THREAD

**Issue by steffipravasi** [bcgov/performance#1082]
Env: Test and Prod
User: 169412 | Hoyle,Meaghan | Environment and Climate Change Strategy
The user has 2 supervisors listed in the supervisor list but none of them is selected as the current supervisor. Instead option 'No Supervisor' is displayed. 
Expected result: One supervisor must be selected/assigned as the active/current supervisor and user must not see the option 'No supervisor'
![Screenshot 2023-08-02 at 1.34.09 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/f39b9347-61fc-496c-b0b3-8bdcd4ced9cd)

**Comment by telusdcinco** [comment]
@Travis-A-Clark  @steffipravasi 
The "no supervisor" is displayed when user have not selected a supervisor before.  The default value may need to be reworded if confusing to the user.  Should it display "No supervisor selected", "Select a supervisor", or something else?

**Comment by telusdcinco** [comment]
"Select a supervisor" will be defaulted on the dropdown if the user (with multiple supervisors) have not selected a supervisor and there is no employee demo supervisor found.
Pushed to Test, Pending build.

Note that #857 will limit the dropdown listing based on selected primary job.

**Comment by steffipravasi** [comment]
Test validated. 
Multiple supervisors:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ2R6IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--451aa523019cd26c4c3d1deac0d71e1e91e2c16b/Screenshot%202023-09-06%20at%201.29.01%20PM.png)
No supervisor:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ2h6IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b249315457a52eac8b98d8a576f5239e7b78f54d/Screenshot%202023-09-06%20at%201.25.56%20PM.png)

**Comment by steffipravasi** [comment]
Ticket verified on prod:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdTZoIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--dd3ca244107e27c5daf9044fa203cfb7a52343b0/Screenshot%202023-09-14%20at%207.24.59%20PM.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdStoIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--dbd8ed735b92e5d7db7214dbbc1ef52069f29bbc/Screenshot%202023-09-14%20at%207.26.06%20PM.png)
