### ISSUE TITLE
Add Goal button must function when the goal is opened from the Hidden Goals section and Notifications

### ISSUE THREAD

**Issue by steffipravasi** [bcgov/performance#1084]
Once a goal is hidden, the goal can still be viewed by clicking the notification or the goal name and modal opens up. The 'Add Goal' button when clicked, must add the goal to the user's current goal bank.![Screenshot 2023-08-11 at 12.25.25 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/190b1315-a238-449a-80a2-f03a9ee8c81e)

**Comment by Travis-A-Clark** [comment]
@jizhaogit Hoping we can get this one turned around today if possible so we can push with the rest of the "Hidden Goals" updates. Hopefully this is a quick fix! Thanks.

**Comment by steffipravasi** [comment]
Issue resolved and validated on Test region.
User: Wilson,Shawna
