### ISSUE TITLE
Replace Employee ID with Employee Email in Dropdown Menus

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#1085]
This change should apply to the goal sharing dropdown menus and the employee sharing dropdown menus available to end users. Employee ID can still be used everywhere for HR and Sys Admin.

**My Current Goals > Share dropdown**

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/30984b27-675a-48e5-810e-087ad6057dcb)

**My Team > Share Modal**

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/711e3f0d-aad9-4297-8da1-71f6b480c8ed)

**Comment by steffipravasi** [comment]
@Travis-A-Clark Do we want to change the list from Hr admin/Sys admin -> Shared employees page -> Share modal
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBakFvIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--fe8fecc2ad357654a07ae22ab88f3617540bf290/Screenshot%202023-08-22%20at%2012.30.02%20PM.png)

**Comment by jizhaogit** [comment]
sys/hr share employee applied the same change as end user

**Comment by Travis-A-Clark** [comment]
@jizhaogit 

Is it possible to change the message that appears when the dropdown is searching for results? Currently it says "The results could not be loaded". Can we change this to "Searching for results." or something like that?

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcThvIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a000c46526806bc96f4611cd107ac850e041dcda/image.png)

**Comment by steffipravasi** [comment]
Putting the ticket back to In Progress for the latest change Travis mentioned

**Comment by jizhaogit** [comment]
the data loading message is updated as request.

**Comment by steffipravasi** [comment]
Test validated and issue resolved.
Search message updated and changes updated to Hr and Sys admin.
