### ISSUE TITLE
Remove past employee from Team members page

### ISSUE THREAD

**Issue by steffipravasi** [bcgov/performance#1088]
Issue extracted from #779
Milum,Paula who is a past employee from July 2023 still appears in the team members list - Share with me section for Travis clark
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaUlVIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5ac4faec84ebce70b2bc792affacf12d346cf9f6/Screenshot%202023-08-17%20at%2012.29.46%20PM.png)

**Comment by telusdcinco** [comment]
Fix pushed to Dev/Test, pending build.

**Comment by steffipravasi** [comment]
Direct reports verified on prod. Its difficult to verify the shared reports as the employees are already in the past employees list and cannot find the supervisor from the Share employees page.
