### ISSUE TITLE
HR/Sys Admin > Goal Bank > Manage Goals: update column information 

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#1092]
Currently we have one "Created By" column that lists the display name of the author of the goal. This value defaults to the individual's identity unless they added a "Display Name" value when creating the goal. Let's break this into two columns: Created By (which is always the individual name) and Display Name (which could be the individual name or the additional value if the author entered one).

Let's also add back in the Organization column (just top level) for the individual that created the goal.

So after Goal Created Date we would have: Display Name, Created By, Created By Organization...then the last three columns as they currently are.

**Comment by steffipravasi** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbGc5IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--2f0f6ec8e577bf0ba281a5f9405f2b31f99f71fc/Screenshot%202023-08-25%20at%2012.36.16%20PM.png)
