### ISSUE TITLE
Implement SnowPlow to track site visitors and provide analytics per DevOps Team request

### ISSUE THREAD

**Issue by telusdcinco** [bcgov/performance#1093]
Implement SnowPlow to track site visitors and provide analytics per DevOps Team request

**Comment by telusdcinco** [comment]
@Travis-A-Clark Pull this one back to Dev review as Warren have requested additional changes for SnowPlow.

**Comment by telusdcinco** [comment]
Added condition below to allow sending dev info to dev snowplow and prod info to prod snowplow(spt.apps.gov.bc.ca)
        @switch (env('APP_ENV')) 
            @case ('prod') 
                var testvar = 'spt.apps.gov.bc.ca';
                @break;
            @default
                var testvar = 'spm.apps.gov.bc.ca';
        @endswitch

**Comment by telusdcinco** [comment]
Waiting for Warren before pushing to prod.

**Comment by warrenchristian1telus** [comment]
Hi @telusdcinco - the test is now complete, and we can switch all implementations from SPM to SPT (production) Snowplow at your convenience.

**Comment by telusdcinco** [comment]
@Travis-A-Clark Warren informed me that Snowplow change can proceed to Prod.

**Comment by telusdcinco** [comment]
@warrenchristian1telus Snowplow deployed to PDP Prod.

**Comment by warrenchristian1telus** [comment]
Thanks @telusdcinco - GTX has been notified. We should have it in the dashboard soon.

**Comment by warrenchristian1telus** [comment]
It seems this has never been implemented on the Snowplow Dashboard. I've sent a reminder to Dan at GTX to see if we can get it enabled.

**Comment by warrenchristian1telus** [comment]
Snowplow has now been implemented on the PSA Analytics Dashboard.

Please note that authentication is required, and only available to select team members. If anyone else requires direct access to statistics, just let me know.
