### ISSUE TITLE
Add private goals to the statistic goal summary 

### ISSUE THREAD

**Issue by steffipravasi** [bcgov/performance#1094]
Ticket extracted from #1075
Can we include the private goals in all the goals summary charts: 
- Active Goals Per Employee
- Add new Active private goal chart
- Add private goal column in the excel sheets

**Comment by jizhaogit** [comment]
private goal added in the static goal summary page

**Comment by steffipravasi** [comment]
@jizhaogit Is it possible to keep the height of these boxes same?
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcXdwIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--f763227075915978add72d2abe875063f52a720a/Screenshot%202023-08-22%20at%204.08.24%20PM%20copy.png)

**Comment by steffipravasi** [comment]
Height Issue seems to be fixed on Sys admin side but not on Hr admin,
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbGNxIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--35239bf9ec6ec2ab9e9a2002b590e95f60405025/Screenshot%202023-08-22%20at%206.12.46%20PM.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbGdxIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ecdecc1ecf924e39b19faace9cc3bc83058b5875/Screenshot%202023-08-22%20at%206.13.17%20PM.png)

**Comment by jizhaogit** [comment]
Hr report box height is changed to the same as Sys report box

**Comment by steffipravasi** [comment]
Test validated
