### ISSUE TITLE
Fix 16 Prod users having multiple profiles, extension of #863

### ISSUE THREAD

**Issue by telusdcinco** [bcgov/performance#1095]
#863 addressed the issue of PDP creating multiple profiles when the user gets a different email for the same employee ID.  Since rollout in late March 2023, no new cases are detected in prod.  

However, I can find some duplicate profiles created between February and March 2023.  This period coincides with the gap between taking/generating the employee list and migration to prod.  During this period, 16 new profiles for existing employee IDs were created.

The list to be uploaded in MS Teams and linked here.

**Comment by steffipravasi** [comment]
@telusdcinco Can you please attach the list of employees from Prod to the ticket

**Comment by telusdcinco** [comment]
User list in below link

https://bcgov-my.sharepoint.com/:x:/r/personal/dennis_cinco_gov_bc_ca/Documents/ZH1095%20-%20Data%20Fix%20List.xlsx?d=w1b93f26e74964eb08b191747f13608c4&csf=1&web=1&e=qiSF0e

**Comment by telusdcinco** [comment]
@steffipravasi The user list is based on Prod user IDs.

**Comment by steffipravasi** [comment]
Since this ticket is related to Prod. Will verify it once we push the ticket to Prod. Moving it for PO review.
