### ISSUE TITLE
Conversation Templates: add example modal for each template type

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#1097]
Add links to each template name that launch a modal with blank example of the template so that users can review before they decide if they want to use it.
<br>

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcDBvIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5213c17cf306b36b924f4dacc314889a60612b34/image.png)

**Comment by jizhaogit** [comment]
@telusdcinco Hi Dennis can you please help do the code review? thanks!

**Comment by telusdcinco** [comment]
@jizhaogit Change looks good.

**Comment by jizhaogit** [comment]
@steffipravasi  Please trigger the template by click the conversation's name.  thanks!

**Comment by jizhaogit** [comment]
@steffipravasi good catch! issues addressed. thanks!

**Comment by steffipravasi** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ0ZXIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a22a634e5adc8db1ffe6cfd2a4f02bd339023b99/Screenshot%202023-08-30%20at%2010.23.41%20PM.png)

**Comment by jizhaogit** [comment]
elements disabled in template

**Comment by steffipravasi** [comment]
Test validated and issues have been addressed.
