### ISSUE TITLE
Conversation page does not load fully 

### ISSUE THREAD

**Issue by steffipravasi** [bcgov/performance#1099]
Ticket continued from #1064

Chris Mutadi, Employee ID 131454, PDP User ID 20750. He has had issues with the "My Conversation" page not loaded fully (missing descriptions of each text box):

Issue happened occasionally, as we were able to see open conversations that are currently in his profile with all the descriptions loaded. The user uses Azureidir to log on.

Noticed it happening only when the user logs in to the browser through IDIR for the very first time. Works fine once the page is refreshed or the conversation is opened again.
Test data: Logged into Edge for the first time with IDIR
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbmt3IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--44c6847ab5bb14acbdd1226f26e5c32df181e92a/Screenshot%202023-08-23%20at%203.37.29%20PM.png)

**Comment by jizhaogit** [comment]
@steffipravasi i applied a new fix for the modal loading issue. can you please help take a try from you end by using the idir?  thanks!

**Comment by steffipravasi** [comment]
@Travis-A-Clark I verified the issue on Edge, Chrome, Safari and Firefox and am not able to see it anymore. But it might also be possible because I have used all the browsers for testing before. Can you please help verify it if you have multiple browsers?

**Comment by Travis-A-Clark** [comment]
I am still getting the same issue. Logged in to the TEST environment with IDIR. Created a Career Development conversation with Zehra. Page didn't fully load (image below).

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBclZ0IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3bd90ea97e27ec1b173b006152625fbb66766b3e/image.png)

**Comment by Travis-A-Clark** [comment]
Just created a Goal Setting conversation and it's also blank. Didn't log out and back in. Still logged in to TEST, so it's an ongoing issue, not just on first log-in.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcmh0IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--c25cce8021e71a3ce1a02c3a0bd74c787cd7a877/image.png)

**Comment by steffipravasi** [comment]
@jizhaogit I am putting this ticket back to in-progress

**Comment by jizhaogit** [comment]
i added a 1.5 seconds delay for the modal open to let the system has more time to initial elements.  can you please try again? thanks

**Comment by Travis-A-Clark** [comment]
Creating a new conversation in the TEST environment. I see the 1.5 second delay, but then it still comes up blank.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdWR5IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--0458e5bd12f364ae4b6ce885e2d18398589e07e5/image.png)

**Comment by jizhaogit** [comment]
@Travis-A-Clark,Hi Travis, can you please help do a screenshot for the error message displayed in the browser's developer tool?

**Comment by Travis-A-Clark** [comment]
This message is from Edge:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaFZ6IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5d791217d3e4e62bdfe598176d9ec99b9fad47f6/image.png)

**Comment by Travis-A-Clark** [comment]
@jizhaogit It worked the first time in Chrome for me. However, using Edge with an InPrivate window, I still get the same issue:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbHlJIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--1fe582eeee987e4752f460ea4c938aff6fdbaef2/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbDZJIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5ce3c2874f0edbe6b21ba40b6e8073ddda2a208c/image.png)

**Comment by jizhaogit** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbVNJIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3167aea5be84a0fdceb4cee49ab0f0d42010fb16/image.png)

This is wired... as you can see from my screenshot, it works as expected in my edge InPrivate window...

**Comment by steffipravasi** [comment]
As discussed in the last scrum, will be moving this ticket to Prod to check if its still happening for users. 
Moving over to PO review.

**Comment by Travis-A-Clark** [comment]
Just noting that I still receive the following error when loading a conversation in Training. Will still push to PROD.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdEdoIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--bf43ed46fb05882826317ae070698e5cd405a580/image.png)
