### ISSUE TITLE
As a Sys Admin, I want to be able to edit the Resources section of the app directly

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#1101]
**Current Scenario**

Any updates to content in the Resources section requires the assistance of the dev team to enter text and push through the various environments.

**Desired Solution**

We develop an interface that allows Sys Admins to directly edit text in the Resources section, including adding new headings and content to existing pages. This could potentially be similar to what is already available for Sys Admins to edit the PDP welcome modal.

**Comment by jizhaogit** [comment]
@telusdcinco Hi Dennis,  please help do the code review. thank you!

**Comment by telusdcinco** [comment]
@jizhaogit Looks good to me.

**Comment by Travis-A-Clark** [comment]
@jizhaogit The interface makes sense and all of the content is there. However, when I make a change to the text I lose the formatting. For example, I changed the words "Performance Development Platform" to "PDP" on the video tutorials page and I lost all of the links to the YouTube videos and the title formatting from the page.

[Uploading... image.png]

**Comment by Travis-A-Clark** [comment]
As discussed, let's look at ways of incorporating a bit more of the html functionality in terms of supporting links, colours, etc. in the editor if possible.

**Comment by jizhaogit** [comment]
added feature for supporting hyper link

**Comment by Travis-A-Clark** [comment]
As discussed at this morning's meeting, I will move this through to training and prod as a first step for the editing interface. In future we will examine upgrades to the CK Editor and editing functionality.

Please ensure that none of the test data that I edited or added is moved into training or prod.
