### ISSUE TITLE
Resources > Video Tutorials: add video icon and clear link to YouTube

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#1108]
### Current Scenario

It is difficult to see where the videos and video links are in the layout of the information on the resources page. The link text is hard to see and it's not clear what will happen when you click on it.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbldCIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--cc60c8e7581000b36de4cd86cdc7cbcb95ba11fe/image.png)

### Desired Solution

Add some sort of video icon and clear indication that clicking on the video will take the user to YouTube.

**Comment by steffipravasi** [comment]
Test validated. Youtube video icon added and the link highlights with underline when hovered over.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcCtZIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--e7d29c0769cd37191aff70fad1e55db3847f4b04/Screenshot%202023-09-13%20at%202.39.40%20PM.png)
