### ISSUE TITLE
HR/Sys admin Goal Bank clears out entered data when throwing a required field validation

### ISSUE THREAD

**Issue by steffipravasi** [bcgov/performance#1112]
Hr/Sys admin -> Add a new goal to goal bank 
If we fill out all the fields except the mandatory(required) fields on the Add a new Goal page, and click on Add Goal button, the filled details from the fields clears out leaving the user a complete blank page having to enter all details again.
Required fields are: 
- Goal Title
- Tags
- Goal description

Expected result: Entered details must remain intact regardless of the validation messaged thrown. 
Issue for HR and Sys admin
https://bcgov.sharepoint.com/:v:/r/teams/02915/Shared%20Documents/Product%20Team/Steffi%20-%20Testing/1112.mov?csf=1&web=1&e=f4uLfw

**Comment by SubashreeS** [comment]
Retested the ticket in test environment and it is working fine. The details added while creating the goal, in the goal bank were retained correctly

**Screen Recording:**
https://bcgov.sharepoint.com/:f:/r/teams/02915/Shared%20Documents/Product%20Team/Steffi%20-%20Testing/Subashree%20-%20testing/Performance%20%231112?csf=1&web=1&e=FGfSun
