### ISSUE TITLE
Dashboard notification did not get deleted when the goal has been removed from the employee's goal bank

### ISSUE THREAD

**Issue by jessicahjwu** [bcgov/performance#1113]
**Current scenario:**

- HR Admin added a goal to the goal bank for the entire Justice sector
- HR Admin noticed that was an error and rectified it to be assigned to only the business unit of Western Communities Branch, Sys Admin has deleted the Justice sector form the list of "business unit" for that goal
- Rest of the employees In Justice, outside of West Communities Branch, can still see the notification on their dashboard although the goal has been deleted from their goal bank
- Rest of the employees outside of that branch can still add the goal to their own "My Goals" by clicking on "view" on the dashboard notification, though the goal does not exist anymore in their goal bank

**Desired outcome:**

- Dashboard notification to be removed once the business unit is no longer assigned to the goal

**Comment by jessicahjwu** [comment]
Confirmed the notification was hidden when the business unit was removed. However, when a higher level of org which contains the previously removed business unit was assigned for the goal, the user received multiple notifications of the same content. Please refer to ticket 1117.

**Comment by steffipravasi** [comment]
Test validated for HR and Sys admin.
