### ISSUE TITLE
Goal Bank - Multiple individuals cannot be added by search

### ISSUE THREAD

**Issue by steffipravasi** [bcgov/performance#1114]
When trying to add multiple employees by searching them through the search fields, results in only the last one remaining selected and being added to the goal. 
Expected result: We must keep all the selected employees saved and add them to the goal
Issue for Hr and Sys admin - Add and Edit goals
Additional: It would be nice to have a list that displays all the selected employees added through the search fields

https://bcgov.sharepoint.com/teams/02915/_layouts/15/stream.aspx?id=%2Fteams%2F02915%2FShared%20Documents%2FProduct%20Team%2FSteffi%20%2D%20Testing%2F1114%2Emov&referrer=OneDriveForBusiness&referrerScenario=OpenFile

**Comment by Travis-A-Clark** [comment]
@steffipravasi Is this related to ticket #987?

**Comment by steffipravasi** [comment]
@Travis-A-Clark this is a different issue but since they are related to the same page, I am going to merge this ticket to 987. Thank you!
