### ISSUE TITLE
Missing the tooltip info from all the conversations

### ISSUE THREAD

**Issue by steffipravasi** [bcgov/performance#1116]
For all of the conversations, there are tooltips icons displayed which doesn't function as tooltip and there is no content in the tooltip. 
Solution: Should we just remove the icons?
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBazZtIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--9424edc45a313a69fbf162156fa23f1f072d78e7/Screenshot%202023-09-15%20at%2011.37.40%20AM.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbEttIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--afe90dfbf24ca257dd6c510958f40cf42f5b8c2a/Screenshot%202023-09-15%20at%2011.37.21%20AM.png)

**Comment by telusdcinco** [comment]
@jizhaogit Please take a look at the missing tooltips issue.  It may be related to 1097 changes.

**Comment by jizhaogit** [comment]
thanks Dennis provide the tooltips code in the file.  i will go to check and fix the popup feature for displaying those tooltips.

**Comment by steffipravasi** [comment]
@jizhaogit Addressing a couple of issues here:
1) When opening the tooltip in any of the conversation templates, it doesn't close when clicked anywhere outside. 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc0RaIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--fa06cf0909317c004de5b89d952d944ca6316c24/Screenshot%202023-09-26%20at%2011.14.25%20AM.png)
2) Not sure why the conversations are not aligned anymore. Can we align them again?
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcy9aIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--65761787afa5d6fbca70c7df1a837a010a9d7d51/Screenshot%202023-09-26%20at%2011.24.34%20AM.png)

**Comment by jizhaogit** [comment]
1.  tooltips popup issue is fixed.  
2.  Steffi and i both agree no need to take action for this item because we found it only happens in Steffi's laptop's screen size 13"

**Comment by steffipravasi** [comment]
Test validated for templates and the conversation
