### ISSUE TITLE
Randomize first conversation due dates for third batch of organizations

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#1121]
Please set the first conversation due dates between December 7, 2023 and February 15, 2024 for the following organizations:

- Agriculture & Food
- Citizens' Services
- Energy Mines & Low Carbon Innovation
- Environment & Climate Change Strategy
- Forests
- Indigenous Relations & Reconciliation
- Post-Secondary Education and Future Skills
- Transportation & Infrastructure
- Transportation Investment Corporation
- Water, Land & Resource Stewardship

**Comment by telusdcinco** [comment]
@Travis-A-Clark After assigning Batch 3 to the above listed Orgs.  The list below are the remaining Orgs not assigned to any batch and assumed to be not accessing PDP.  The next conversation date calc will default to same as batch 3.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaDNHIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--2f7812961730bb9601db15ea7a1d3b02da54d964/image.png)

**Comment by telusdcinco** [comment]
New initial conversation due date calculation based on formula below.

{ [ Last 2 Digit of Employee ID ] / 100 * ( 71 days ) } + [ Initial Date ]

Example: Employee ID = xxxx00
{ 0 / 100 * 71 } + { Dec 7, 2023 } = Dec 7, 2023

Example: Employee ID = xxxx99
{ 99 / 100 * 71 } + { Dec 7, 2023 } = Feb 15, 2024

**Comment by telusdcinco** [comment]
Deployment requires running seeder script below.
php artisan db:seed --class=DataFix_1121_Setup_Conversation_Batch_3

**Comment by telusdcinco** [comment]
@jizhaogit Please review code changes for #1121.

**Comment by jizhaogit** [comment]
good to me. thanks and please go ahead for the migration.

**Comment by steffipravasi** [comment]
@telusdcinco 
Citizen services: 
166250	Menke,Katherine
 
192007	Sharma,Neha

Environment & Climate Change Strategy

099198	Demarchi,Diana N	Diana.Demarchi@gov.bc.ca	2023-01-07
193214	Barkway,Garrison	Garrison.Barkway@gov.bc.ca	2024-04-25
193216	Thin,Thomas	Rogan.Thin@gov.bc.ca	2024-04-07

Forests
187860	Parker,Taylor	Taylor.Rae.Parker@gov.bc.ca	2022-12-05
182703	Gaba,Aneesha	Aneesha.Gaba@gov.bc.ca	2022-12-13
167916	Gagnon,Susan	Sue.Gagnon@gov.bc.ca	2022-12-26
159650	Cote,Jeremy	Jeremy.Cote@gov.bc.ca	2023-11-27

193414	Swan,Lauren	Lauren.Swan@gov.bc.ca	2024-05-11
003834	Woodward,Robert Charles	Chuck.Woodward@gov.bc.ca	2024-04-26
135219	LaRue,Zachary	Zachary.LaRue@gov.bc.ca	2024-04-11
187517	Taylor,Justin	Justin.Taylor@gov.bc.ca	2024-04-05
195600	Sostad,Christopher	Christopher.Sostad@gov.bc.ca	2024-03-29
154713	Fox,Robert William	Robert.Fox@gov.bc.ca	2024-03-27
177111	Healey,Braeden M.	Braeden.Healey@gov.bc.ca	2024-03-27
173512	Smith-Hanson,Nadja	Nadja.Smith-Hanson@gov.bc.ca	2024-03-25
180714	Allen,Scott	Scott.1.Allen@gov.bc.ca	2024-03-20

**Comment by steffipravasi** [comment]
Citizen services: 
166250	Menke,Katherine
 
192007	Sharma,Neha

Environment & Climate Change Strategy

099198	Demarchi,Diana N	Diana.Demarchi@gov.bc.ca	2023-01-07
193214	Barkway,Garrison	Garrison.Barkway@gov.bc.ca	2024-04-25
193216	Thin,Thomas	Rogan.Thin@gov.bc.ca	2024-04-07

Forests
187860	Parker,Taylor	Taylor.Rae.Parker@gov.bc.ca	2022-12-05
182703	Gaba,Aneesha	Aneesha.Gaba@gov.bc.ca	2022-12-13
167916	Gagnon,Susan	Sue.Gagnon@gov.bc.ca	2022-12-26
159650	Cote,Jeremy	Jeremy.Cote@gov.bc.ca	2023-11-27

193414	Swan,Lauren	Lauren.Swan@gov.bc.ca	2024-05-11
003834	Woodward,Robert Charles	Chuck.Woodward@gov.bc.ca	2024-04-26
135219	LaRue,Zachary	Zachary.LaRue@gov.bc.ca	2024-04-11
187517	Taylor,Justin	Justin.Taylor@gov.bc.ca	2024-04-05
195600	Sostad,Christopher	Christopher.Sostad@gov.bc.ca	2024-03-29
154713	Fox,Robert William	Robert.Fox@gov.bc.ca	2024-03-27
177111	Healey,Braeden M.	Braeden.Healey@gov.bc.ca	2024-03-27
173512	Smith-Hanson,Nadja	Nadja.Smith-Hanson@gov.bc.ca	2024-03-25
180714	Allen,Scott	Scott.1.Allen@gov.bc.ca	2024-03-20
			

Transportation & Infrastructure

067938	Prehara,David W.	2024-04-30
169221	Buchanan,Maya	2024-04-13
Transportation Investment Corporation

067696	Grover,Brent	Brent.Grover@ticorp.ca	2022-12-26
067696	Grover,Brent	Brent.Grover@ticorp.ca	2022-12-26
175908	Dey,Avik RanJan	Avik.Dey@ticorp.ca	2023-11-05
175908	Dey,Avik RanJan	Avik.Dey@ticorp.ca	2023-11-05
131153	Wynnyk,Tracy	Tracy.Wynnyk@ticorp.ca	2023-11-28
171857	Chang,Richard	Richard.Chang@ticorp.ca	2023-11-30
179557	Martinez Atayde,Hermilo	Milo.Atayde@ticorp.ca	2023-11-30
171857	Chang,Richard	Richard.Chang@ticorp.ca	2023-11-30
148264	Neitz,Brennan	Brennan.Neitz@ticorp.ca	2023-12-04
			
Water, Land & Resource Stewardship

135890	Kaytor,Benita	Benita.Kaytor@gov.bc.ca	2024-05-06

**Comment by telusdcinco** [comment]
The random items checked in the list shows that the ones with older due dates (< Dec 7, 2023) have not GUID, and was not recalculated.  The ones > Feb 15, 2024 seem to have some excused periods calculated causing the next due date to be pushed forward beyond Feb 15, 2024.

**Comment by steffipravasi** [comment]
@Travis-A-Clark The list above is the employees which we might have to discuss on Monday. But apart from these employees, the dates are calculated correctly. Moving for PO review.
