### ISSUE TITLE
Users were unable to type in the comment boxes when starting a new conversation

### ISSUE THREAD

**Issue by jessicahjwu** [bcgov/performance#1126]
1. I selected the participant, and clicked on "Start Conversation":
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcUhxIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--2d4b7d298105f4d0d65549ae3ddca79ac81e10a1/MicrosoftTeams-image%20%282%29.png)

2. The comment boxes were greyed out, and I wasn't able to type in there:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcC9xIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3a106acf6cf25c625f724f3ded6e057551c66967/MicrosoftTeams-image%20%283%29.png)

However, when I closed the pop-up and went to "open conversation", I could type in the comment boxes when re-opening the record of the same conversation.

**Comment by jessicahjwu** [comment]
Checked in the test environment, I was able to type in the comment box:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcDdyIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ee8741fa1ccd075213b579bd2b738683085dfeea/image.png)

**Comment by telusdcinco** [comment]
@jessicahjwu Please let me know when this can move to Prod.

**Comment by jessicahjwu** [comment]
Fix was also in place in Training, I could type in the comment box:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbFRzIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7b95d348ecb1c8ed29313b755a25b0a551040751/image.png)

**Comment by telusdcinco** [comment]
@jessicahjwu  Deployed to Prod.  Please confirm.
