### ISSUE TITLE
User is unable to cancel creating a goal

### ISSUE THREAD

**Issue by SubashreeS** [bcgov/performance#1127]

**Comment by jessicahjwu** [comment]
Pipelines: To be estimated
No sprints nor epics assigned

**Comment by jessicahjwu** [comment]
@steffipravasi Please verify if this issue still exists

**Comment by steffipravasi** [comment]
This issue is on the Goal Bank page for HR/Sys admin and we might still need to fix it in the future as its a low priority

**Comment by jizhaogit** [comment]
@steffipravasi can you please help verify if the issue is addressed? thanks!
