### ISSUE TITLE
The original creator's name appeared when a goal pulled from the goal bank is shared with another employee/supervisor

### ISSUE THREAD

**Issue by jessicahjwu** [bcgov/performance#1128]
**Scenario**: The employee pulled a goal in the goal bank, and shared it onwards with another employee. However, the name of the original creator (Ana Nolasco) appeared on the goal instead of the display name (Ministry of Forest):
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2dIQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d4418f9213a00939be1bc7ff6bd4bc441ce50c9e/image.png)

**Question**: Which table is this "created by" name being pulled from? Can the term "created by" be changed to "shared by", or "modified by" if this name needs to be pulled from the owner (employee who grabbed the goal) to avoid confusion?

**Comment by jessicahjwu** [comment]
As discussed, please change the label from "Created by" to "Shared by" and display the name of the user (initial person who pulled the goal from the goal bank) who is sharing the goal with another person.

**Comment by steffipravasi** [comment]
Test validated. The field name has been replaced to 'Shared With'
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejQrQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--aad62ece47b1aa7261022efc26eaf50723841e62/Screenshot%202023-10-16%20at%203.05.01%20PM.png)
