### ISSUE TITLE
HR/Sys Admin > Goal Bank > Add Goal: improve filter and tree user interface

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#1129]
HR/Sys Admin > Goal Bank > Add New Goal > Step 2: Select Audience

As discussed at sprint review, let's try the following things:

- [x] Move "Business Unit(s)" to the first/default option and "Individual(s)" to the second option
- [x] Add an instruction below "Business Unit(s)" and above organization filter that says: "Use the filter below to find your organization. Click the "Generate Org Tree" button. Scroll down and select the business unit(s) from the org tree to assign the goal. If using "Static" option, make sure there is a check mark beside each business unit. If using "Inherited" option, make sure there is a check mark beside the top org level only; the goal will cascade down through all levels below automaticaly."
- [x] Change the "Filter" button to "Generate Org Tree". Do not auto-generate tree. Force user to click "Generate Org Tree".
- [x] Auto expand org tree once it is created.
- [x] Explore option to remove all check boxes from the org tree above the level selected in the filter. I.e. if someone has selected BC Public Service Agency > Employee Relations > Labour Relations and Total Compensation, then the tree would look like below with the checkboxes removed from the red areas.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGtUQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f6255d9828fcbf94ce2572af61932e7ef4ddbd3e/image.png)

**Comment by telusdcinco** [comment]
@Travis-A-Clark I have pushed the checked items (4 items) to Dev and Test.  The auto-expand seemed to have introduced a more issues than anticipated, so I will not include that change for testing.  Please let me know if we can move forward without auto-expand for now (and create a separate ticket for it).

**Comment by Travis-A-Clark** [comment]
Couple of requests:
- Can we not bold the instructions? It's a lot of bold!
- Can we remove the instructions when toggling to "Individual(s)" audience? They are only applicable to Business Units
- Can we move the "Generate Org Tree" and "Reset" buttons to a separate line below the filters?
- The tree is still auto-generating as selections are made. We had discussed forcing the user to click the button to create the tree.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNElVQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--75f35ae815fd44047e4b62c1cb5c40ed2874ad51/image.png)

**Comment by telusdcinco** [comment]
@Travis-A-Clark Sys/HR Admin Goal Bank page will auto-expands only 1 level from Ministry level.
