### ISSUE TITLE
Old position still showing up as active in PDP

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#1130]
Employee ID: 178226 
Name: Diaz, Maria Delia

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3NUQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--de12a5abab04a165c8f65ed388ba53a310e58ca4/image.png)

The first row above contains reports_to position # data and shows as active. However, the classification "Clerk R11" was discontinued many months ago. All Clerk R11s became "Clerk R12". That is the second row, and the one that should be correct. Can we explore why the first row still exists?

FYI: I did a search of all employees in the PDP, and this employee is the only Clerk R11. All the others seems to have effectively been removed.

**Comment by telusdcinco** [comment]
Issue should be resolved with he view update in #857.

**Comment by steffipravasi** [comment]
Test validated and issues have been resolved. 
Note: This ticket will be migrated to prod along with #857
