### ISSUE TITLE
Sys Admin not seeing HR Admin goals in Goal Bank

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#1132]
Environment: Test
User: Travis Clark

When viewing HR Admin > Goal Bank > Manage Existing Goals I can see all of the recently created goals for the PSA.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2doQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6bf6775a0d5bfd4301ec4354a514985e0a239f45/image.png)

When viewing Sys Admin > Goal Bank > Manage Existing Goals I don't see any goals after Oct 3. Sys Admin should see all goals in the system.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2toQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4336c9f6e3b2615b16443a234e0859147f7807fa/image.png)

**Comment by telusdcinco** [comment]
Issue:  Sys Admin cannot see HR Admin Goal Bank created, when author is the SysAdmin.

**Comment by steffipravasi** [comment]
Test validated. 
Cannot attach a screenshot somehow it's taking too long to upload.
