### ISSUE TITLE
User unable to Sign In to PDP, after new Employee ID was assigned to the user.

### ISSUE THREAD

**Issue by telusdcinco** [bcgov/performance#1136]
Issue 1:
PDP maintains a 1 user to 1 email policy.   Issue arises when the email is reused by by another user or by the same user but under a different employee id.  A log entry is generated in the process logs when an email address being processed from Employee Demographic (ODS), but there is no automated process to fix the issue.

Issue 2:
User Profile Creation automatically locks accounts that contains a date_deleted value in the employee demographics table.  There is currently no check for any other active employee demo data.  This will result in the user with multiple jobs to lose PDP access when 1 job is terminated, even though the other job is still active.

- [x] Modify User Profile Creation Process to allow reuse of email address in PDP.
- [x] Modify User Profile Creation Process to allow re-enabling of a locked account if the user is again allowed to access PDP.
- [x] Limit account locking in the User Profile Creation, to only lock out account that has no active employee demo data.

**Comment by telusdcinco** [comment]
In order to reuse an email address, added step to email address is updated to look like this "first.last@gov.bc.ca*****<47585><LOCKED>" when a user profile is locked.  This will allow first.last@gov.bc.ca to be available for the user profile creation.  

When the actual user email is in use in PDP, an exception is written to log to note the issue.  This remains the same as before.

In the case of employee 186935/179099, the auto fix will require 2 run cycles.  First run, will update the email address to "first.last@gov.bc.ca*****<47585><LOCKED>" format and lock the terminated employee id (186935).  Second run (next night), will allow for the creation of a new user profile for "first.last@gov.bc.ca".

**Comment by steffipravasi** [comment]
Employee id 186935 has no user record on test now. 
User Afroz,Sadia shows up with employee id - 179099 and can access the account
https://bcgov.sharepoint.com/:i:/r/teams/02915/Shared%20Documents/Product%20Team/Steffi%20-%20Testing/1136.png?csf=1&web=1&e=aAPXwQ
https://bcgov.sharepoint.com/:i:/r/teams/02915/Shared%20Documents/Product%20Team/Steffi%20-%20Testing/1136(2).png?csf=1&web=1&e=OVUHx2

**Comment by telusdcinco** [comment]
The following overnight processes will be manually executed after migration to Prod today.
php artisan command:SyncUserProfile > storage/logs/SyncUserProfile_1036.log;
php artisan command:UpdateGUIDByEmployeeId > storage/logs/UpdateGUIDByEmployeeId_1036.log;
php artisan command:PopulateAuthUsers > storage/logs/PopulateAuthUsers_1036.log;
php artisan command:PopulateAuthOrgs > storage/logs/PopulateAuthOrgs_1036.log;
php artisan command:SetNextLevelManager > storage/logs/SetNextLevelManager_1036.log;
php artisan command:BuildAdminOrgUsers > storage/logs/BuildAdminOrgUsers_1036.log;
php artisan command:CalcNextConversationDate > storage/logs/CalcNextConversationDate_1036.log;
php artisan command:PopulateEmployeeManagersTable > storage/logs/PopulateEmployeeManagersTable_1036.log;
php artisan command:PopulateUsersAnnexTable > storage/logs/PopulateUsersAnnexTable_1036.log;
php artisan command:PopulateOrganizationStatistics > storage/logs/PopulateOrganizationStatistics_1036.log;
php artisan command:CleanShareProfile > storage/logs/CleanShareProfile_1036.log;
