### ISSUE TITLE
Sys/HR Admin > Excuse Employees: Filters Not Working

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#1142]
Sorry, but ZenHub won't allow me to attach screenshots or files. I'll describe below.

Scenario:
- I log in as Travis Clark. I go to HR Admin > Excused Employees. I have access to 1,425 employees in total. 
- I filter the results by org unit. Level 1 = Corporate Services. I see 74 results. I select all employees checkbox at top left of table. I click "Excuse Employees" at the bottom of the page. It asks to confirm that I want to excuse all 1,425 employee that I have access to. It ignores the filter and the selections I made.
- This is true for all HR or Sys Admin cases Jessica and I tried. If you filter by org and then click the select all, it defaults to covering everyone your permissions allow you to have access to. I almost, accidentally, excused 41,554 users in production as a result.

Desired Solution:
- Only those users filtered and selected are effected by the excuse request

**Comment by telusdcinco** [comment]
The solution is only applied to Sys/HR Admin Excused pages.

**Comment by telusdcinco** [comment]
@steffipravasi Please let me know results on this ticket, as the solution is also applied for #1146 and #987.  Any change on this ticket may be needed to be applied on the other tickets.

**Comment by steffipravasi** [comment]
@telusdcinco The selection does not get stored when selecting few employees first, filtering the org and select all option. Can we save the previously selected entries as well?
https://bcgov.sharepoint.com/:v:/r/teams/02915/Shared%20Documents/Product%20Team/Steffi%20-%20Testing/1142.mov?csf=1&web=1&e=Hueu0y

**Comment by telusdcinco** [comment]
@steffipravasi 
I've added the fix to retain selected values before clicking Select All.  Pushing to Test, pending build.  Same fix applied to #1146.

**Comment by steffipravasi** [comment]
@telusdcinco One more issue I noticed
If we add a couple of employees and then select the Select All option, the total number in the confirmation message increases by the earlier selected employees and exceeds the total number of employees user has access too
https://bcgov.sharepoint.com/:v:/r/teams/02915/Shared%20Documents/Product%20Team/Steffi%20-%20Testing/1142/Screen%20Recording%202023-11-03%20at%207.42.21%20PM.mov?csf=1&web=1&e=uXypEu

**Comment by telusdcinco** [comment]
The confirmation message only displays the unique employee ID count.

**Comment by steffipravasi** [comment]
The issue of the count increasing on the confirmation message is fixed. But we need to discuss the duplicate entries count issue with Travis.

**Comment by Travis-A-Clark** [comment]
Confirmation message text:

Are you sure you want to excuse the # selected employee(s)? This will pause their next conversation due date and remove them from PDP reporting.

Note: Excuse status may not update until the next day.

----

As discussed, make the message scarier and more attention grabbing with colours, font, icons, whatever we can.

**Comment by telusdcinco** [comment]
Added fix to display message below when no item is selected.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1N4QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d2ed60781caa6ff37b0d37ab0053673d7dcf1ae6/image.png)

**Comment by telusdcinco** [comment]
New confirmation message.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1d4QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9aacd68a0c635678fd4ff071057f64620efe189d/image.png)

**Comment by steffipravasi** [comment]
Test validated. 
As discussed we'll move forward with the current fix.
