### ISSUE TITLE
Create HR Admin Resources Page

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#1143]
As an HR Admin, I want a dedicated page available to me in the Resources section. Format can be the same as other Resources page in the app. Put it between the FAQ and Contact Us tabs.

**Tab title = HR Admin Access**

**Accordion 1 title = HR Admin Access in the PDP**

Overview:

In order to protect user privacy, HR Administrator Access will be granted at the lowest organizational level possible that still enables an individual to fulfill their role and accomplish designated tasks. All requests for access will be reviewed by the employee's supervisor, executive director, and ministry HR team and ultimately be approved or denied by the Performance Development Platform team.

Within their authorized area, HR Administrators will be able to:
- View basic employee data and reporting relationships.
- Update shared supervisor relationships in the PDP.
- Edit the excused status of employees in the PDP.
- Run reports and export excel files that show number and type of active goals created as well as the number, type, and due dates of conversations captured in the PDP.

HR Administrators will NOT be able to:
- Access individual user profiles (other than their own).
- See the content of goals, comments, or conversations for any employee (other than themselves).

Training:

HR Administrators should carefully review the two documents below and reach out to their [ministry contact](https://performance.gov.bc.ca/resources/contact) if they have additional questions. 

- [HR Administrator Guide for PDP.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMlNTQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--beb78c601119204974a95090fa49bcb1463c3b72/HR%20Administrator%20Guide%20for%20PDP.pdf)

- [Guide to Creating Org Goals in PDP.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnFTQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--87d5a806c2a80b69478c0a68e0ea7433da8c7f12/Guide%20to%20Creating%20Org%20Goals%20in%20PDP.pdf)

Request Access:

Please complete the form below with required approvals and submit a [MyHR service request](https://psa.frontlinesvc.com/app/ask) with subject line "PDP HR Admin Access - YOUR NAME" using the routing: HR Software System Support > Performance Development Platform.

- [BCPSA Data Access Agreement.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjJTQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dacaa7fe6c1a6806ab640f229289ad825f784476/BCPSA%20DATA%20ACCESS%20AGREEMENT%202023_open%20with%20Adobe%20Reader.pdf)

**Accordion 2 title = HR Analytics Access to PDP Data**

Content to follow

**Comment by jessicahjwu** [comment]
@telusdcinco and @jizhaogit please update the comments with options that Warren has suggested.

In addition, if the option that was recommended doesn't work for us due to performance concerns (files size and users accessing those files at the same time will impact the performance), alternatives will be to save those files in the HR Admin Teams channel (and if folks w/o government email don't have access, we can email them in attachments). I've reached out to Rheannon and asked about whether or not we may post those HR Admin instructional vids in the PDP youtube channel, Rheannon will check with Comms to see if there's concerns over these non-approved videos. If they do, we might need to save the videos in Teams too.

**Comment by jizhaogit** [comment]
Accordion 1 title = HR Admin Access in the PDP is ready

**Comment by Travis-A-Clark** [comment]
@jizhaogit Thanks! I just finished adding all the rest of the text in the ticket description. Sorry I didn't have that ready earlier.

**Comment by Travis-A-Clark** [comment]
And the three sections within the accordion should be: Overview, Training, and Request Access. I couldn't find a good way to highlight that in the plain text of the ticket description.

**Comment by jizhaogit** [comment]
Accordion title 1 is done.  

will wait for Accordion 2 title = HR Analytics Access to PDP Data content/files.

**Comment by Travis-A-Clark** [comment]
Looks good! Just a few small changes and I think it's ready to go.

1. Please change the name of the tab at the top from "HR Admin Guide" to "HR Admin Access". Also, please move this tab near the end of the page between the "FAQ" and "Contact Us" tabs.
2. In the overview section, please remove the bullets from the lines that start with "Within their authorized area..." and "HR Administrators will NOT be..."
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFN4QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3664791685a99fccfcb02a40123a19562c273f38/image.png)
3. Please copy over the links from the ticket description above for "ministry contact" in the Training section and "MyHR Service Request" in the Request Access section.

**Comment by jizhaogit** [comment]
@Travis-A-Clark issue #1, #2 and #3 are ready in test

**Comment by Travis-A-Clark** [comment]
@jessicahjwu I think this looks good. Can you please review as well to make sure it makes sense for the process we discussed? Thanks! 

https://performance-332842-test.apps.silver.devops.gov.bc.ca/resources/hr-admin

**Comment by jessicahjwu** [comment]
Looks good to me too!
