### ISSUE TITLE
HR/Sys Admin > Stats and Reporting: add new categories to Next Conversation Due chart

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#1144]
**Current Scenario**

In the Next Conversation Due chart there is only one large "overdue" category. Whether you are one day overdue or one year overdue, you show up in the same place.

**Desired Solution**

Divide the "overdue" category based on how far past the conversation due date someone is. Instead of one single overdue category, create:

overdue < 1 month, overdue: 1 month to 4 months, overdue: > 4 months

Updated requirements discussed in the meeting on Dec 11
- Update text 'overdue: 1 month to 4 months' to 'overdue: 1-4 months'
- Add 'upcoming' word for the categories 1) > month 2) 1 week to 1 month 3) < week

**Comment by Travis-A-Clark** [comment]
We will also need to create a new notification to go out at the overdue by 2 weeks period. Resend the overdue notification. I will create a separate ticket for this.

**Comment by steffipravasi** [comment]
1) Searching for Citizen Services: The colours of the chart are not matching with description
<img width="839" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0pWQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--51a80aca086f69aabfefad2e57fe542cda723ef7/Screenshot%202023-12-12%20at%205.57.19%E2%80%AFPM.png" alt="Screenshot 2023-12-12 at 5.57.19 PM.png" />

2)For a slightly small screen like my 13 inch. There is some overlapping of text from the chart to the description at the bottom. 
<img width="742" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd05WQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--75f6d6641c80a0b556df4e8e9faf0114e4f79665/Screenshot%202023-12-12%20at%207.38.04%E2%80%AFPM.png" alt="Screenshot 2023-12-12 at 7.38.04 PM.png" />
Searched for BC PSA:
<img width="589" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1ZWQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b6a9f4a6ecdb4be5327178e4167e5e83668366a3/Screenshot%202023-12-12%20at%206.18.56%E2%80%AFPM.png" alt="Screenshot 2023-12-12 at 6.18.56 PM.png" />

3) Capitalize the 'O' character in the word overdue

4) Nice to have: On the hover of any part of the chart, only the colour from the chart highlights. It will be nice to have if even the chart description can be highlighted. Example: If I hover over the Overdue: 1-4 months, then along the chart, the text 'Overdue: 1-4 months' will be highlighted. 
<img width="744" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGhWQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--43d720c776b7f2a26aac210b08da4173594c6a6f/Screenshot%202023-12-12%20at%207.55.35%E2%80%AFPM.png" alt="Screenshot 2023-12-12 at 7.55.35 PM.png" />

**Comment by jizhaogit** [comment]
@steffipravasi i increased the chart's size, can you please try from your side again? thank you!

**Comment by steffipravasi** [comment]
@jizhaogit Thank you for fixing all the issues reported. Can I request you to fix issue number 3 too: Capitalize the 'O' character in the word overdue
<img width="989" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdzllQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2d952ebf9a1c8f0f8396773759bef414a36e787e/Screenshot%202023-12-14%20at%203.41.30%E2%80%AFAM.png" alt="Screenshot 2023-12-14 at 3.41.30 AM.png" />

**Comment by jizhaogit** [comment]
@steffipravasi  sorry forgot this issue. it is fixed. thank you!
