### ISSUE TITLE
Fix Stuck Disabled User Profiles

### ISSUE THREAD

**Issue by telusdcinco** [bcgov/performance#1145]
#1136 introduced a fix to allow reuse of email addresses with another user profile.  This is to handle rehire cases wherein the employee gets assigned a temporary employee ID and later gets reassigned to the previous employee ID.  

There is a bug in the change where a locked account remain locked even after the user should be enabled to sign in, based on ODS Employee Demo updates.  The code lines that would enable user account is currently checking the wrong status flag.

This fix should:
1) updated account lock flag to appropriate setting based on date_deleted value in Employee Demo
2) check against Access Organization whether the user's Organization is allowed to sign on into PDP.

To Test:
1) Verify test user account can or cannot sign in into PDP.
2) Disable/Enable logon option for user's organization on the Access Organizations page.
3) Run "SyncUserProfile" process.
4) Verify test user account by login into PDP.

**Comment by steffipravasi** [comment]
Test data used: For orgs: Citizens Services
001515 
001891
001290

For Guid: 
009742
010015
005494


For org and Guid: Destination BC Corp
040369
009620

**Comment by telusdcinco** [comment]
Query fixed in Dev and Test.

**Comment by steffipravasi** [comment]
Test validated. All the employees listed in previous can sign in after the process ran.
