### ISSUE TITLE
Prod Issue:  Temporarily Hide Select All from Sys/HR Admin Share Employee Page

### ISSUE THREAD

**Issue by telusdcinco** [bcgov/performance#1147]
Prod Issue:  Temporarily Hide Select All from HR/Sys Admin Share Employee Page

**Comment by telusdcinco** [comment]
This is a temp fix until permanent fix to resolve the Select All issue on Sys/HR Admin Share Employees page.

1) Hide Select All checkbox from Create New Shares page.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGVVQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b58706056008ac3693ae39e13470e03c489c5cab/image.png)

2) Display count on confirmation for saving Create New Shares page.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGFVQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--12cc38e323e86bbf314fef0ac3e586a817688232/image.png)

**Comment by telusdcinco** [comment]
@jessicahjwu Please see 2 changes in Test.  Does not include prevention of multiple select at the moment.

**Comment by jessicahjwu** [comment]
Checked in Test, the two changes look good to go. Since we have the count in the confirmation window we won't need to temporarily disable the multi-select function.

**Comment by telusdcinco** [comment]
@jessicahjwu @Abuchana @jizhaogit 
#1147 migrated to Prod.  
Changes pushed to Prod include:  
1) hiding the Select All checkbox in Step 1 & 2 on the Create New Share page.
2) confirmation message display employee count and supervisor count.

Email queue confirmed running after pod restart.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekdhQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d96307f9084b7d2c6acbb975ee4dcf248a4548b0/image.png)
