### ISSUE TITLE
Remove the limitation of comments in shared goal

### ISSUE THREAD

**Issue by steffipravasi** [bcgov/performance#1153]
Currently, the number of comments in the Shared goal is limited to 10 after which any new comments are not displayed. 

Requirement: Can we remove the limitation on the number of comments which can be added to the goal. 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXE1QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ba8a28967b280f413a55214769971de8df8a5854/Screenshot%202023-11-08%20at%207.46.55%20PM.png)

**Comment by jizhaogit** [comment]
the 10 comments limitation is removed

**Comment by steffipravasi** [comment]
Comment limitation removed.
 [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1RBQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3b52aefb286a7d22ade36854d002ed1281e74dda/Screenshot%202023-11-09%20at%205.04.45%20PM.png)
