### ISSUE TITLE
Remove the Dept id from the Shared With list

### ISSUE THREAD

**Issue by steffipravasi** [bcgov/performance#1155]
Ticket related to #1104

Issue must be addressed at all the places:

My Goals -> My current goals -> Shared with
My team -> Team members -> Shared column
HR/Sys admin -> Share Employees -> Shared modal

Comments from Travis: 
With all of the work on ticket #857 it has become apparent that we cannot actually share a goal just to one job profile for an employee...it goes on the same profile no matter which job is selected from share dropdown list. This wasn't clear when we started this ticket.

As such, I recommend going back and **removing the Dept ID from the drop down list so that the entries are shorter (like they were before with just email) and instead adding a filter to only display each name / email combination once in the dropdown list.** I believe this was an option Ji mentioned back when we started this ticket, and given the other realities of #857, this looks like the best option. Sorry to reverse course!

**Comment by steffipravasi** [comment]
@jizhaogit I think the requirement from Travis's comment was to adding a filter to only display each name / email combination once in the dropdown list. So the duplicate entries must only be displayed once. Is that possible?
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTNBQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b8fad1424cd260b60642c11f73177ac99de69685/Screenshot%202023-11-09%20at%205.46.48%20PM.png)

**Comment by jizhaogit** [comment]
request addressed. please help verify. thanks!

**Comment by steffipravasi** [comment]
Test validated
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOW5hQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a15199e12c3bda4fb485b047969e24877c359e4c/Screenshot%202023-11-15%20at%201.28.06%20PM.png)

**Comment by Travis-A-Clark** [comment]
I believe this change was already pushed to Production on Friday, Nov 10 as part of a ticket to add a "Select the employee" default option to the dropdown list for sharing goals. I will add this to the deploy to prod list just in case there is any additional code that needs to be pushed.
