### ISSUE TITLE
HR/Sys Admin -> Manage goals in goal bank -> Individual audience's filters not working

### ISSUE THREAD

**Issue by steffipravasi** [bcgov/performance#1156]
Issue 1: The filtering for org and their levels are not working. Eg: When selecting BCPSA as org, Corporate Services as Level 1. When clicking on Level 2 the results are not based on Level 1 but displays the whole list.

Issue 2: Reset button not working

Referencing the ticket to #987

**Comment by jizhaogit** [comment]
#1.  level changes based on upper level/organization changes addressed
#2.  reset button addressed

**Comment by steffipravasi** [comment]
@jizhaogit 
The filters are still not functioning properly.
1) When trying to filter level 3 - it takes a while displaying 'Searching' and then throws an error
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHpuQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--31f6fe524592057c1771b02c009544838096dca5/Screenshot%202023-11-17%20at%2011.57.44%20AM.png)

2) Also receiving error on reset button
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHZuQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f92db468f82bfbf08f44b2f3edf0c1e220c99cbb/Screenshot%202023-11-17%20at%2011.57.58%20AM.png)

**Comment by steffipravasi** [comment]
While keeping on filtering by the Levels before the results are loaded- the time taken to load the results is increasing and resulting in a timeout issue 
One solution to prevent this error is by only displaying the results on the click on the Filter button.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHY5QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3dcfcf3d67e0f33e6d8d1052eaced2ec26b3275c/Screenshot%202023-11-22%20at%2011.43.37%E2%80%AFAM.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHo5QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--01e677a82ff14447c3ff72774491cae20a8c550a/Screenshot%202023-11-22%20at%2011.43.54%E2%80%AFAM.png)

**Comment by jizhaogit** [comment]
modified the filter for only displaying the results on the click on the Filter button after doing the organization/level changes

**Comment by steffipravasi** [comment]
https://bcgov.sharepoint.com/:v:/r/teams/02915/Shared%20Documents/Product%20Team/Steffi%20-%20Testing/1156/Screen%20Recording%202023-11-23%20at%208.49.56%E2%80%AFPM.mov?csf=1&web=1&e=6655fo

**Comment by Travis-A-Clark** [comment]
Something else to clean up in the same space: entering any text into the search box located at the top of the goals list generates an error.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBek1IQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--07759249c691ad89a7952ef0a187e3e36f9b8e83/image.png)

**Comment by jizhaogit** [comment]
@steffipravasi please take a try

**Comment by steffipravasi** [comment]
@jizhaogit The filters seems to be working fine now. The only part left is Travis' comment regarding the search field
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWNIQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--85e40f850f324687b8a3d7cd2281d945efb9f0ea/Screenshot%202023-11-24%20at%204.35.06%E2%80%AFPM.png)

**Comment by steffipravasi** [comment]
Cannot see the Search field anymore. Not sure if that was the requirement.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVVRQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a550139b45bf0119dd05d95c8f52735b66701d00/Screenshot%202023-11-28%20at%2012.19.21%E2%80%AFAM.png)

**Comment by steffipravasi** [comment]
Moving this ticket for PO review as we have already removed the in-search feature.
