### ISSUE TITLE
Add "Vacant" supervisor display name for employees with no supervisor in ODS

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#1158]
### Current Scenario:

There are 305 employees in prod that display no supervisor information at all coming in from ODS. Based on our logic, that means that their supervisor and supervisor's supervisor position is likely blank in PeopleSoft.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjdjQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dd030870393abaacecb26aa0e4a4e876a02090f0/image.png)

<br>

On their homepage, under "My Current Supervisor", these folks used to see "No one". Now it displays a weird half size blank box instead.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjNjQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--502dccdf0877f9ab46e1fe990a134e483e0b73eb/image.png)
<br>

### Desired solution

As per ticket 857, the sequence to determine who to display as Current Supervisor is:

1. Supervisor Override
2. Preferred Supervisor selected from My Current Supervisor on the Dashboard
3. Positions Data
4. Next Level Positions Data
5. Employee Demo
6. Next Level manager from Employee Demo

Can we add a step 7 that displays supervisor name = "Vacant" if all of the above return no data?

- [x] When all 6 steps above return no data, Current Supervisor information on homepage displays "Vacant".
- [x] When all 6 steps above return no data, Current Supervisor name on HR/Sys Admin employee view displays "Vacant".

**Comment by steffipravasi** [comment]
Test validated. 
310 employees in the employee list have been assigned 'Vacant' as their Reports to field. 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkRwQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4a7dd1642a8d223ea27138433c7ee1a9759d4c81/Screenshot%202023-11-17%20at%206.18.22%20PM.png)
