### ISSUE TITLE
Resources: add tab to link users to their old MyPerformance profile from within the PDP

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#1159]
In the Resources section, add a new tab called "Accessing MyPerformance". Put it second to last between "HR Admin Access" and "Contact Us".

Content for the new tab:

The PDP replaced the previous performance management tool - MyPerformance - in summer 2023.

You can still access your past MyPerformance profiles and while you cannot copy records directly into the PDP, you can copy and paste any relevant text into the new format.

Note: only MyPerformance profiles that have been signed by both employee and supervisor will be kept in the system. Please make sure all required records are signed off by both parties.

[Access your MyPerformance Profile](https://employee.gov.bc.ca/epm/) (IDIR restricted)

**Comment by jizhaogit** [comment]
content added

**Comment by steffipravasi** [comment]
Accessing MyPerformance tab added on the Resources page
- Content added as per the requirements
- [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3dpQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2e949399485aab85da322524232bdc85907c7c24/Screenshot%202023-11-30%20at%203.03.24%E2%80%AFPM.png)
