### ISSUE TITLE
Copy Microsoft Word modal for conversation exit with unsaved changes

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#1160]
### Current Scenario

When a user enters comments into a conversation template and exits without saving, they receive this message:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3ZnQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--042537dbc4055e921a5dc8c87b35b08a2b2fd3b4/image.png)
<br>

Can we update so that it is more like Microsoft products that have three options instead of two in the same scenario?

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2pnQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6f92e025fa0a0d88d832a4d72f549c53716e457e/image.png)
<br>

### Desired Solution

- [x] Remove individual "Save" buttons for each individual box and introduce a "Save All" button that saves all comments on the user's side of the template at once.
- [x] Switch from default browser confirm dialog to custom modal dialog.
- [x] When there are unsaved changes and a user attempts to exit the conversation, display message: "Save changes to this conversation?". 
- [x] Three options Save, Don't Save, Cancel. If the user clicks "Save", all updates on their side of the template are saved before closing. "Don't Save" exits without saving any changes and removes unsaved content from boxes (reinitiate comments). "Cancel" returns them to the template to continue editing.

**Comment by Travis-A-Clark** [comment]
Other thought:

Can the comment box "Save" button remain visible if comments are unsaved? Currently the save button appears when someone types in a box, but then disappears when they leave the box even if the comments were not saved.

**Comment by jizhaogit** [comment]
confirm dialog is built by default browser. if we want have more customizable confirmation dialog we need to change it to use modal dialog.

**Comment by Travis-A-Clark** [comment]
Updated the description to reflect changes to "Save All" option and move from browser confirm dialog to custom modal dialog.

**Comment by jizhaogit** [comment]
ready for test. thanks

**Comment by steffipravasi** [comment]
@jizhaogit 
1) The Don't Save and Cancel button functionalities are interchanged. 
Expected result: As per the requirement in the ticket description - "Don't Save" exits without saving any changes and removes unsaved content from boxes (reinitiate comments). "Cancel" returns them to the template to continue editing.
Actual result: Currently Don't save button is functioning how the Cancel button is expected to work and vice versa.

2) The Save Comments button is added but on the far right hand side, which becomes difficult to find for the user especially the employee. Initially when I added the comments, I couldn't find the Save All button so it can be the case of employees too. Can we add the Save Comments button on the left hand side for employees and on the right side for supervisors? Maybe we can hide the supervisor button when employee view is open. 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXYvQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--11e703912b6cfabceed15b4a9152cef27421588a/Screenshot%202023-11-22%20at%2010.53.06%E2%80%AFPM.png)

**Comment by jizhaogit** [comment]
@steffipravasi the updates is ready for test

**Comment by steffipravasi** [comment]
Assigning ticket to Ji to fix the Cancel button -> Retain the unsaved comments

**Comment by Travis-A-Clark** [comment]
Hey! This is looking good. Two requests:

1. Can we add a second "Save Comments" button at the top of the comments section as well? Some of the templates are really long and I can see users not scrolling down to the bottom. 
2. Can we add a check to see if any content has changed before we put up the confirmation modal? If no content has changed, the modal does not need to be displayed. The conversation window can just be closed.

**Comment by steffipravasi** [comment]
@Travis-A-Clark Do we also need the cross/close button on the top right corner of the confirmation modal?

**Comment by Travis-A-Clark** [comment]
@steffipravasi If it is there, it should perform the same function as "Cancel". Just close the modal and return the user to the template to continue editing if needed.

**Comment by steffipravasi** [comment]
@jizhaogit we'll need to copy the Cancel button function to the close button as well.

**Comment by jizhaogit** [comment]
i will recommend to remove the close button on the top right confirm modal if it is not necessary and only reproduce the cancel button.   keep the UI simple will otherwise the "close" will also makes user concern what happened to their inputted content.  then we will have to invite another confirmation...  that will be too heavy. 

let me know what you think. thanks.

**Comment by Travis-A-Clark** [comment]
Sure, we can remove the close button from top-right. Thanks.

**Comment by jizhaogit** [comment]
1. confirmation modal close button moved.
2. "save comment" button inserted in both top and bottom of the comments area
3. an "changed" checker is applied to determine if need to show the confirmation modal while close the conversation modal.

**Comment by steffipravasi** [comment]
@Travis-A-Clark @jizhaogit When clicking on the Save comment button ton he top, the Save comment confirmation message is displayed at the bottom resulting in clicking the button multiple times thinking nothing is happening on the click. 
Is it possible to display it at the top if top button is clicked or bottom if clicked at the bottom? Or displaying it somewhere common where its visible from both ends?
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUlIQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2aad604ec5b62e85873257fee9d81b7c5334084c/Screenshot%202023-11-24%20at%201.50.46%E2%80%AFPM.png)

**Comment by jizhaogit** [comment]
lets me see if i can divide the saving message to belong with button

**Comment by jizhaogit** [comment]
@steffipravasi Please take a try

**Comment by steffipravasi** [comment]
@jizhaogit The button have been added at the top but we need to do a some more work around

1) The employee view when opened first time can only see the buttons on the employee side
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGNIQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5249b4c97f465e68d741c3ea039aec27f3cd8c4e/Screenshot%202023-11-24%20at%204.08.35%E2%80%AFPM.png)

2) When opened the supervisor side on the conversation, can see the buttons on both end. Although they go away when refreshed the page.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGdIQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--feafd43905308c8ca92830682b7015105070de5d/Screenshot%202023-11-24%20at%204.07.02%E2%80%AFPM.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGtIQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c8cdc1d787e8230d9a7746e4c5f7e2687d91e814/Screenshot%202023-11-24%20at%204.06.52%E2%80%AFPM.png)

3) Somehow, the employee and supervisor both can edit both the sections now - i.e employee and supervisor's both
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDBIQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fb4db224f2b84fc185dd4cd42350b2a321d26486/Screenshot%202023-11-24%20at%204.11.14%E2%80%AFPM.png)

**Comment by steffipravasi** [comment]
Test validated. Buttons looks good now.
