### ISSUE TITLE
Next conversation due date not updating even after conversation is complete

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#1161]
Multiple instances being reported of employees and supervisors both signing off on conversation and not having their next conversation due date properly calculated afterwards. Even after the overnight process runs, the next conversation due date remains unchanged and follow-up notifications continue to be sent. This has been an issue in the past that Dennis has resolved. Appears to have been reintroduced with all of our updates pushed on Thursday, Nov 9.

For example, Kathleen McPhie and her supervisor signed off on her conversation on November 14. 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXpoQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--811604ee9b18b91d14a637ad49bf07eb92400f95/image.png)

However, Kathleen's next conversation due date was not recalculated. It still shows November 16, 2023 when it should be March 14, 2023 (the date of her last conversations sign-off plus 4 months).

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTdoQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e7b0c0b3059b216b3ff46d3ffb76afca49141b95/image.png)

**Comment by Travis-A-Clark** [comment]
Just checking the job audit log, you can see that the number of rows being updated overnight has fallen significantly. Last week before our latest updates there where hundreds of due dates updated each day:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0RoQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a1408bca923b3b6fae0c9729d20a652cad020527/image.png)
 <br>

So far this week, it's far less each day:
 [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0hoQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--190ed934ce3ae4ee29091ccd1a89b0fbb9effcb8/image.png)
 
Looks like it is not processing all criteria that it used to so is missing a bunch of folks.

**Comment by jizhaogit** [comment]
issue addressed. 
if ($jr 
                            **_&& $jr->excused_type_** 
                            && $jr->next_conversation_date 
                            && $initNextConversationDate 
                            && $jr->next_conversation_date <> $initNextConversationDate) {}

highlighted code will skip all the un-excused employees.

**Comment by Travis-A-Clark** [comment]
In both Test and Training environments, can confirm that it appears conversation due dates are now being correctly recalculated and displayed on:
- Employee's My Conversations page
- Supervisor's My Team page
- HR/Sys Admin employee's view
- HR/Sys Admin stats and reporting

Going to deploy to production and let run over the weekend.
