### ISSUE TITLE
Add "Export" button to the "Access and Permission" tab in Sys Admin

### ISSUE THREAD

**Issue by jessicahjwu** [bcgov/performance#1162]
Currently there's no option to export the existing HR Administrator details to an excel spreadsheet, we would need to add the function in for reporting out to ministries:
https://bcgov.sharepoint.com/:i:/r/teams/02915/Shared%20Documents/Product%20Team/Tickets%20Requirements/1162/image%20(4).png?csf=1&web=1&e=kPT2wF
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHJqQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--de0e319f3a077f0e0d70c9e491b86b9ab6eaca03/image.png)

**Comment by jessicahjwu** [comment]
Pipelines: Product Backlog
No sprint assigned
Estimate: 2
Epics: DevOps

**Comment by telusdcinco** [comment]
MIGRATION NOTES:

Just code changes.

**Comment by telusdcinco** [comment]
@jizhaogit Please review code changes.

**Comment by jizhaogit** [comment]
thanks Dennis. good to me

**Comment by steffipravasi** [comment]
Functionality working as expected
<img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXorQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7c97bf754569ee3cfd311de760d7613e34f99e5a/Screenshot%202024-03-21%20at%201.12.53%E2%80%AFPM.png" alt="Screenshot 2024-03-21 at 1.12.53 PM.png" />
<img width="696" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTcrQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--009135a4822e4c0d255a923253a77fc2be0e111e/Screenshot%202024-03-21%20at%201.14.04%E2%80%AFPM.png" alt="Screenshot 2024-03-21 at 1.14.04 PM.png" />
