### ISSUE TITLE
Create a process to remove PDP permissions when an employee changes jobs - Service Reps

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#1163]
**Current Scenario**
A user is granted Service Rep access. That access stays in place until someone goes in and manually removes it. The user could change jobs multiple times and no longer have any legitimate reason to need the access. This creates a privacy concern.

**Desired Solution**
As part of the overnight processes, review all users with Service Rep access and flag those that have a change in position # or dept ID. Remove access for these users.

If the user still requires access, they can request it again and PDP team will provide.

**Comment by jessicahjwu** [comment]
Pipelines: Product backlog
No sprint assigned
Epics: Contact Centre - Admin Support, DevOps, HR Rep - Admin Functions

**Comment by telusdcinco** [comment]
MIGRATION NOTES:

Run 'php artisan migrate'
Run  '

**Comment by telusdcinco** [comment]
Will be scheduled to run daily at 12:55 am.
<img width="496" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnk4QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6d0157cefa214a5395acb946644b6487049745c6/image.png" alt="image.png" />

**Comment by telusdcinco** [comment]
@jizhaogit Please review code changes.

**Comment by jizhaogit** [comment]
looks good to me. thanks!

**Comment by jessicahjwu** [comment]
Question - for existing employees who have Service Rep access but have already moved out of dept ID 100-3510 - will they get removed of the access with the overnight process when update is pushed out?

**Comment by telusdcinco** [comment]
Below is the change flow for #1163.

1.	Created new audit table to store historical dept id and position number for Service Reps.
2.	Run a script to get current list of Service Reps in Access & Permission, and store current dept id and position number in the new table.
  a.	This will be used as initial dept id and position number for future comparison.
3.	Updated creating/revoking of Service Rep roles in Access & Permission, to create/update the audit entry for each Service Rep.
  a.	When a user is granted Service Rep role, a new entry is added in the audit table along with dept id and position number
  b.	When a user is removed as Service Rep, the existing audit entry is updated with current date to mark the entry as deleted.
4.	Overnight process will check dept id and position number from last ODS data pull against the audit table.
  a.	Service Rep that have a different different dept id or position number will get the role removed, and the audit entry will get updated with the removal.

For mass removal of Service Rep role, we can use a script to remove the access by using backend updates/deletes.
For small number of revocation of Service Rep role, it can be done through Access & Permission page.
