### ISSUE TITLE
My Goals > Share Goals: Add a confirmation modal

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#1164]
**Current Scenario**

A user can select any other employee from across government from a dropdown list and share a goal with that person. It only takes one click, and there is no confirmation message to ensure the user hasn't accidentally selected the wrong person. This is resulting in incorrect shares and notifications for incorrect users.

**Desired Solution**

Create a modal that has asks the user to select the employee(s) they would like to share the goal with and then prompts them to confirm their selection before proceeding. Similar to what we have for My Team > Share Employee modal.

Text for modal:

You can use this function to share a goal with colleagues. This goal will appear on their “Goals Shared with Me” tab and they will be able view and add comments to the goal.

Type the name of your colleague into the search field to find and select them. You can repeat this process to add additional colleagues if needed. You can also remove a colleague by clicking the "X" next to their name.

As the creator of the shared goal, you are the only one that can make major edits or change the status to achieved or archived.

INSERT DROPDOWN LIST

SHARE and CANCEL buttons at bottom.

CONFIRMATION pop up required to proceed. "Are you sure you want to share the goal with the selected employee(s)?"

**Comment by jessicahjwu** [comment]
Pipelines: Product Backlog
No sprint assigned
Estimate: 3
Epics: Emp - Goal Setting

**Comment by steffipravasi** [comment]
1) Incomplete text for the modal:
Please refer to the ticket description for the exact wordings of the text.
Actual: <img width="920" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGFEQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fb1be44a3d58803cfe3ba5cf74816242e4b1ea6b/Screenshot%202024-06-21%20at%203.56.27%E2%80%AFPM.png" alt="Screenshot 2024-06-21 at 3.56.27 PM.png" />

2) The Close button must work the same way as the Cancel button
Actual: Close button shares the employee and closes the modal
Expected: The close button must cancel the share and close the modal

3)

**Comment by jizhaogit** [comment]
issues #2, #3, and #4 should be addressed.  #1 content is more like a instruction but not a confirmation message. lets talk in our meeting about it.

**Comment by steffipravasi** [comment]
1) Content verified
<img width="900" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOU9PQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--906332577e6710a7ce259773c2a00960ac24ba0e/Screenshot%202024-06-25%20at%2012.28.38%E2%80%AFPM.png" alt="Screenshot 2024-06-25 at 12.28.38 PM.png" />
2) Fixed
3) Fixed
4) Not fixed

**Comment by jizhaogit** [comment]
@steffipravasi could you please provide the test employee's id/name so that i can switch to the account and do the debug? thanks!

**Comment by steffipravasi** [comment]
As discussed in the meeting, issue 4 is not related to this ticket so we can neglect it for now.
