### ISSUE TITLE
Cancel button in the pop-up confirmation Saves the data instead of Cancelling

### ISSUE THREAD

**Issue by steffipravasi** [bcgov/performance#1165]
1) Edit goal -> Click on Save button -> Pop up : Are you sure you want to update Goal ?
2) My team -> Shared -> Add employee in the shared list -> Click on Share profile -> Pop up : Are you sure you want to share the selected profile(s)?
3) HR/Sys admin -> Shared -> Add employee in the shared list -> Click on Share profile -> Pop up : Are you sure you want to share the selected profile(s)?

**Comment by jizhaogit** [comment]
detected JavaScripts error. increased scores for more detail testing

**Comment by steffipravasi** [comment]
1) The shared details remains stored on Cancel and is displayed when sharing another employee
Test account: Shawna Wilson
Steps to reproduce: 
- My team -> Shared 
- Shawna selected user profile Shuang Yu to share
- Shawna added a user in the Shared with field, filled out all the fields 
- Clicked on Share profile
- In the modal -> Click on Cancel
- In the Employee Profile Sharing page -> Click on Close
- Select another user Lisa Nichols -> Share employee
- Notice that the page remains pre-filled with the previously entered information
Expected result: The share page must remain cleared everytime it opens
2) Same issue as above is observed in HR/Sys admin -> Share employee

**Comment by steffipravasi** [comment]
Test validated. Functionality working as expected. 
On cancel button click, the modal closes and entered details are cleared out.
