### ISSUE TITLE
Shared employees with "Vacant" supervisor positions do not show up on My Team page

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#1166]
### Current Scenario:

There are 305 employees in prod that display no supervisor information at all coming in from ODS. Based on our logic, that means that their supervisor and supervisor's supervisor position is likely blank in PeopleSoft.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjdjQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dd030870393abaacecb26aa0e4a4e876a02090f0/image.png)

<br>

You can share these folks with another supervisor in the PDP. They show up on the shared supervisor's dropdown participant list for conversations and goal bank list for audience. Emails reminders are sent and the functions all seem to work.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1hjQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4f0774eec2f9d8d28d14a23351eef7423524d66d/image.png)

<br>

HOWEVER, they don't show up on the shared supervisor's My Team page:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2pjQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2ee7131348eb3ce83f63e1eee0a4e723205e2321/image.png)

### Desired solution

- [ ] When employee with no current supervisor in ODS is shared with another supervisor in PDP, they show up on that shared supervisor's My Team page.

**Comment by Travis-A-Clark** [comment]
Example:

Sys Admin > Share Employees: select two employees from the same organization and business unit.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTNwQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--734933818fdf3b0b15c0342c740de9f7c6a30805/image.png)

Barbara McCoy (employee ID 122756) reports to "Vacant" supervisor.
Sara Blake (employee ID 132277) reports to "Jawanda,Keranjeet".

Share both employees with Cassandra Graber (employee ID 150777).

Switch identity to Cassandra and view My Team. Only Sara Blake appears. Barbara McCoy is not visible. This is true for all people that report to "Vacant" supervisor.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeS9wQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f35c253e3b9dc767a885482c68bbb76e7fbf5c6b/image.png)

We need everyone to be visible after they have been shared.

**Comment by jizhaogit** [comment]
issue addressed, test case 005320 	McClean,Arthur in TEST env

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejcyQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--758cecd5c5962c4d0832ce1a002c696208b5b552/image.png)

**Comment by Travis-A-Clark** [comment]
@jizhaogit I don't think this solved the initial problem. As per my example in the comment above, the issue was an employee that reports to "vacant" being shared with another employee. Your example deals with an employee who reports to an existing real supervisor being shared with an employee who reports to "vacant". It's backwards. :-)

The initial problem still persists.

These two employees are both shared with Cassandra Graber. Barbara McCoy reports to "vacant" supervisor. Sara Blake reports to a real existing supervisor.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0wyQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--69a6155bbcc8a2fb6d8d36062d18d919494a6d64/image.png)
<br>

Cassandra Graber only sees one of them on her My Team page. She does not see the one that reports to a vacant supervisor.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0QyQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--77ae572cfb5b0a0639f146c91fd2f38064ade637/image.png)

**Comment by jizhaogit** [comment]
thanks Travis, issue should be addressed. in TEST env, if you switch account/login to Cassandra Graber and check her "shared with me" list you should be able to see the below 2 employees:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNW4zQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--39f103b16d44d5bdb3abb7aa0837bf0112fe7741/image.png)

**Comment by steffipravasi** [comment]
Test validated and employee reporting to 'Vacant' position appears in the team members page for the shared supervisor.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUg1QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--007b3ab54dbe675fe024e99b4a6cfdbd84a7b7e2/Screenshot%202023-11-21%20at%2011.51.10%E2%80%AFPM.png)
