### ISSUE TITLE
User must receive notification when Audience list of the goal is updated by supervisor from Team goal bank

### ISSUE THREAD

**Issue by steffipravasi** [bcgov/performance#1167]
Users receive notifications when the Individual Audience list for the goal is updated and new users are added. 
Can we use the same logic for users when the supervisor or shared supervisor updates the Audience list and add new users.

**Comment by jessicahjwu** [comment]
Pipelines: Product Backlog
No sprints assigned
Estimate: 2
Epics: All - Goal Bank

**Comment by jizhaogit** [comment]
@telusdcinco Hi Dennis, could you please help do the code review? thanks!

**Comment by telusdcinco** [comment]
@jizhaogit  Change looks good.

**Comment by steffipravasi** [comment]
@jizhaogit Issue still not fixed.
User: Shawna Wilson
Steps to Reproduce: 
- Shawna added a new goal from My Goals -> Goal Bank -> Team Goal Bank -> Add Goal to bank
- While adding a goal, Shawna only added Lisa to the audience list and created the goal
- After that Shawna updated the audience list and added Jessica , Christopher and Shuang to the list. 

Expected result: Jessica , Christopher and Shuang should receive notifications about the goal. Note Lisa should not receive the notification again.
Actual: They didn't receive any notification
<img width="496" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd05jQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a823bd30451c445ec59042c814495f529e7d0c74/Screenshot%202024-02-14%20at%202.50.20%E2%80%AFPM.png" alt="Screenshot 2024-02-14 at 2.50.20 PM.png" />
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1JjQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--78a4ae0a288027413b0f9b24772e713b1704e346/Screenshot%202024-02-14%20at%202.50.54%E2%80%AFPM.png" alt="Screenshot 2024-02-14 at 2.50.54 PM.png" />

**Comment by jizhaogit** [comment]
Hi Steffi, can you help verify again? thanks

**Comment by steffipravasi** [comment]
Test validated and functionality working as expected now.
