### ISSUE TITLE
HR/Sys Admin > Add Goal to Goal Bank: give Admin option to send or not send emails when adding goal

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#1169]
**Current Scenario**

When a HR/Sys Admin adds a goal to the goal bank or adds a new audience to an existing goal, emails are automatically sent to all impacted employees. Each employee does have the option to turn off these notifications in their account preferences area. However, most people leave this option turned on, so there is a ton of email traffic generated.

**Desired Solution**

Let's give the Admin an additional option as part of Step 3 of the Add New Goal process that says: "Send an email notification to all employees about the new goal? Yes/No". With an "i" info toggle tip that says: "All employees will receive a notification on their PDP homepage about the goal. By selecting "Yes" to this question, you will also send an alert to their email prompting them to log in and view the new goal."

**Additional requirements - Dec 14**
Add the Step 3 to the Manage Goals in Goal Bank -> Editing Goal by Individual audience and Business Unit

**Comment by jizhaogit** [comment]
change of Individual Audience is also added

**Comment by steffipravasi** [comment]
@jizhaogit 2 issues to fix here
1) Manage Goals in Goal Bank -> Editing Goal -> Individual audience. If HR/Sys admin adds individuals and selects Yes  in Step 2. The individuals do not receive emails on Save Changes button (The users do have settings on in their profiles as well as the organization)
2) Please add step 2 Send an email notification to all employees about the new goal? to Manage Goals in Goal Bank -> Editing Goal -> Business Unit Audience

**Comment by jizhaogit** [comment]
1, i found that the mail process in test is not running.  just want to verify that do we have mail feature enabled in TEST? if it is yes i will need to turn on the mail process as we do in PROD
2. Thanks @steffipravasi, pages are ready

**Comment by steffipravasi** [comment]
@jizhaogit We have added the option in Manage Goal -> Business unit Audience page, but it is not functioning as expected. I edited a goal by adding a new business unit and selecting No for emails, but still received an email notification.
<img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeCtZQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--10714f611a00328cfec2e56e249da4dd9025183d/Screenshot%202024-01-03%20at%203.57.25%E2%80%AFPM.png" alt="Screenshot 2024-01-03 at 3.57.25 PM.png" />
<img width="1060" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUdZQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8b0c637b351ae71715a6c0d4abebccadb09b8007/Screenshot%202024-01-03%20at%204.01.15%E2%80%AFPM.png" alt="Screenshot 2024-01-03 at 4.01.15 PM.png" />

**Comment by jizhaogit** [comment]
confirmed that in the Manage Goal -> Business unit Audience page, the "No" radio's checked value is same as "Yes". that caused the issue.  error is fixed. please help verify. thanks

**Comment by Travis-A-Clark** [comment]
In Manage Goal page, when adding new individual or business unit audience:
- Change wording of email notification option to: "Send an email notification to new employees about this existing goal?"
- Confirm background logic to make sure we can send email only to new audience members while not sending email to any audience that was selected when the goal was first created.

**Comment by steffipravasi** [comment]
The message is only updated on the Business unit audience page and we've missed to update it on the Individual audience page. 
<img width="1036" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHFyQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2b8b047b45c3bed79087814634e3650f477ca89a/Screenshot%202024-01-09%20at%2012.43.34%E2%80%AFAM.png" alt="Screenshot 2024-01-09 at 12.43.34 AM.png" />
-------------------------
Confirmed the logic and the emails are only sent to the new audience added to the goal.

**Comment by jizhaogit** [comment]
the updated message is also applied on "the individual audience" page

**Comment by jizhaogit** [comment]
the updated message is also applied on "the individual audience" page
