### ISSUE TITLE
Open conversations are not visible to supervisor or employee

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#1171]
### Current Scenario

Supervisor: Allan Leghorn (eID 145357)
Employee: Jing Miao (eID 183775)

Allan can see Jing on his My Team page and in the conversation participant dropdown list. Jing can see Allan in the conversation participant dropdown list. They both have tried creating multiple conversations with each other (see audit log entries below).

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenNQQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7d7af9f53981a5744837ae7079c33af85fd0b60a/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMElQQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9a98e4c102edf511ac9079baa57bb20768c8e177/image.png)
<br>

Each of those conversations generated an in-app and email notification to the participants.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFVQQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--72c74e41f5b607bc788975f1d3826dd93791d504/image.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDRQQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6600f6147dcf9a4470a85543fab427e506096d26/image.png)
<br>

However, the conversations are not accessible and are not displayed on the Open Conversations tab.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMG9QQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--551d2c94d14d9e26beaa0e4b7852db07a093cdf8/image.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDhQQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7c80d7616a8dea28779d931f16cb4afcb8cf842f/image.png)

### Desired Solution

Created conversations are visible on the Open Conversations tab and are editable by both employee and supervisor.

This could be related to work on ticket #1168 which is also about supervisor/employee relationship and data display.

**Comment by jizhaogit** [comment]
issue addressed.

**Comment by steffipravasi** [comment]
Functionality working as expected now. 
- Verified with the gives employee-supervisor. 
- Tried creating new conversations from both ends and both can view the created conversations in the list. 
- Notifications are received correctly
- [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVFpQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4294ed3053a71a84cdd89860ababf2af796c4e98/Screenshot%202023-11-30%20at%202.35.45%E2%80%AFPM.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVVpQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--81301befb991617c19dd46db011c9f31ee1fd371/Screenshot%202023-11-30%20at%202.39.03%E2%80%AFPM.png)
