### ISSUE TITLE
Missing full list of goal tags in resources section

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#1172]
The full list of goal tags and descriptions that used to be available in the resources section is gone.

The link was:
https://performance.gov.bc.ca/resources/goal-setting?t=5

Perhaps it got lost with the updates to allow Sys Admins to edit the resources section?

We need the content back ASAP.

**Comment by Travis-A-Clark** [comment]
@jizhaogit Can you also please update "View full list of tag descriptions" link in the Create New Goal modal to reflect the new URL. https://performance-332842-test.apps.silver.devops.gov.bc.ca/resources/goal-setting?t=8

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFlhQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--132195a7cbac8b26ffdce1ced6d3df8d79b740cb/image.png)

**Comment by steffipravasi** [comment]
Functionality working as expected. 
- Full tags list added in the Resources section
- Link in the tooltip replaced
- Link of tags added in HR/Sys admin view.
