### ISSUE TITLE
Remove the dataTable build-in search feature

### ISSUE THREAD

**Issue by steffipravasi** [bcgov/performance#1173]
Ticket requirement from #1156
- HR/Sys admin -> Manage goals in goal bank page
https://bcgov.sharepoint.com/:i:/r/teams/02915/Shared%20Documents/Product%20Team/Tickets%20Requirements/1173/Screenshot%202023-11-29%20at%202.00.06%E2%80%AFPM.png?csf=1&web=1&e=b8Svfz
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFFiQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--41dd9e5b4635693f8138c8769c8fac825af27d9c/Screenshot%202023-11-29%20at%202.00.06%E2%80%AFPM.png)

- Manage Goals in Goal Bank -> Business Unit Audience
https://bcgov.sharepoint.com/:i:/r/teams/02915/Shared%20Documents/Product%20Team/Tickets%20Requirements/1173/Screenshot%202023-11-29%20at%202.01.43%E2%80%AFPM.png?csf=1&web=1&e=P1shhb
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFliQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--50fa1f8e8ff170a4eebb24be4638126839442440/Screenshot%202023-11-29%20at%202.01.43%E2%80%AFPM.png)

**Comment by jessicahjwu** [comment]
Pipelines: Product Backlog
Sprints: Jan 29-Feb 9, 2024

**Comment by steffipravasi** [comment]
Test validated and the requirements of the ticket have been addressed.
