### ISSUE TITLE
HR/Sys Admin >Stats and Reports: Goal Tags not displaying properly in list

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#1177]
I just recently added seven new goal tags to the PROD environment. It appears to have screwed up the display on the Stats and Reporting page where only every second goal tag is now displayed with a title. Can we have this list so that it displays all and extends to accommodate new tags added in future? It can keep going down the page.
SS reference: https://bcgov.sharepoint.com/:i:/r/teams/02915/Shared%20Documents/Product%20Team/Tickets%20Requirements/1177/1177(1).png?csf=1&web=1&e=l88vtO

<img width="714" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWN1QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3a5485df20b265a8f58f0b6020bcd09984aaf160/image.png" alt="image.png" />

**Comment by jessicahjwu** [comment]
Pipelines: Product Backlog
Spints: Jan 1-12, 2024
Erpics: HR Rep - Admin Functions, Sys Admin - Functions

**Comment by steffipravasi** [comment]
@jizhaogit 
1) The Sys admin view looks good but HR admin's view is still not fixed and is not seeing the complete list as Sys admin
HR admin: 
<img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNktaQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a32bb135040d73a4875bddf62b3c33fd75143c2c/Screenshot%202024-01-04%20at%2012.57.45%E2%80%AFAM.png" alt="Screenshot 2024-01-04 at 12.57.45 AM.png" />
Sys admin:
<img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNk9aQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--db7e0e56e86011f3791188066cca9007d2317332/Screenshot%202024-01-04%20at%2012.58.14%E2%80%AFAM.png" alt="Screenshot 2024-01-04 at 12.58.14 AM.png" />

**Comment by jizhaogit** [comment]
HR chart view is adjusted as Sys chart view

**Comment by steffipravasi** [comment]
Test validated. Functionality working as expected.
