### ISSUE TITLE
Add details to job audit log for UpdateGUIDByEmployeeID

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#1178]
Related to ticket #854

Please add details to the job audit log for

command:UpdateGUIDByEmployeeId

Currently, we only see the number of how many rows are updated each day as part of the overnight process. I would also like to see who the employees were.

I hope this might help troubleshoot some issues with disappearing goals in the application. Investigating if there is a connection between changes in GUID and changes in profile content.

**Comment by jizhaogit** [comment]
For testing,  the change is pushed to Training. please verify the audio log from Training site.
