### ISSUE TITLE
Update auto save message

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#1179]
Currently, the autosave message says: "You have been inactive for more than 15 minutes. Your goal has automatically been saved."

This is not technically true, as a user could be actively typing in a new goal when the message pops up. It's actually timed to the opening of the create new goal modal.

Please change the message to: "You have not saved your work in 20 minutes. To protect your work, it has been automatically saved."

And confirm that the autosave time in Prod is indeed 20 minutes (not 15 as stated in the old message).

**Comment by steffipravasi** [comment]
@Travis-A-Clark For create new goal, the message for auto save is updated, but after the message We have one more pop up msg that displays 'Your goal is saved' when clicked ok -> The goal modal closes. 
This might become an issue for user creating a new goal and actively typing 
https://bcgov.sharepoint.com/:v:/r/teams/02915/Shared%20Documents/Product%20Team/Steffi%20-%20Testing/1179/Screen%20Recording%202023-12-14%20at%203.22.21%E2%80%AFAM.mov?csf=1&web=1&e=sR7ny1

**Comment by steffipravasi** [comment]
@jizhaogit To confirm Auto-save time in prod is 15 mins. Would we change it to 20 mins when we deploy this ticket to Prod?

**Comment by jizhaogit** [comment]
@steffipravasi Hi Steffi, all the goal auto save and conversation auto save are set to 20 mins in prod now.

**Comment by steffipravasi** [comment]
Create new goal issue will be addressed in ticket #1183.

**Comment by steffipravasi** [comment]
Somehow I am not receiving the auto save message for edit goals
<img width="789" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjlpQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0a324bd085f3354ae126eee42cd747291b9ee205/Screenshot%202023-12-14%20at%205.46.34%E2%80%AFPM.png" alt="Screenshot 2023-12-14 at 5.46.34 PM.png" />

**Comment by steffipravasi** [comment]
Not receiving the auto save message on edit goals
