### ISSUE TITLE
Improve the confirm / save dialog for Create New Goal modal

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#1183]
Apply the conversation save logic from ticket #1160 to the Create New Goal modal.

- [x] Switch from default browser confirm dialog to custom modal dialog.
- [ ] When there are unsaved changes and a user attempts to exit the goal, display message: "Save changes to this goal?".
- [ ] Three options Save, Don't Save, Cancel. If the user clicks "Save", all updates are saved before closing. "Don't Save" exits without saving any changes and removes unsaved content from boxes (reinitiate content). "Cancel" returns them to the Create New Goal modal to continue editing.

Teams folder Location: https://bcgov.sharepoint.com/:f:/r/teams/02915/Shared%20Documents/Product%20Team/Tickets%20Requirements/1183?csf=1&web=1&e=QRoZXD

**Comment by Travis-A-Clark** [comment]
Is it also possible to copy the way the conversation template saves content? Currently, when you click "Save" on the Create New Goal modal it closes the modal and takes you to the My Current Goals list. It would be better if it were like the conversation modal. When you click "Save" on a conversation, the window remains open and a message is displayed saying "Comments saved". The only way to exit the modal is to click the "X".

**Comment by steffipravasi** [comment]
@Travis-A-Clark Should we apply the same fix edit goal as the page neither has a Cancel button or a Back button. We can address this in a new ticket.

**Comment by steffipravasi** [comment]
1) Save Changes does not close the modal but instead displays the message 'Your goal has been saved'
Expected: If the user clicks "Save", all updates are saved before closing.

2) Create new goal -> Add goal title & tags -> Click on close button -> Save changes -> Add goal description -> Click the close button again. 
Note that the modal is closed without neither saving the goal description and displaying the confirmation modal
(This issue might be resolved if we fix issue number 1) 

3) If the user fills out the Goal Type and Tags field -> Clicks on the close button -> Modal is closed without displaying the confirmation message or saving the goal. The expected result is that the Goal title field must be validated and an error must be displayed.
Looks like the Goal saving is based on the Goal Title.

4) User receives the Save changes to this goal message after clicking OK to the auto-save message. 
The auto-save message says that the changes have been auto-saved. Once user clicks on ok, they should be left on the create goal page where they left and not show the save changes to this goal message
<img width="1382" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0dZQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1bf59c148029a2935f3117e24251875d4550bb80/Screenshot%202024-01-03%20at%205.30.24%E2%80%AFPM.png" alt="Screenshot 2024-01-03 at 5.30.24 PM.png" />

5) The ticket requirements must also be applied to the Create new goal modal in My Goals -> Goal Bank -> Team Goal Bank -> Add goal to bank

**Comment by jizhaogit** [comment]
1, 2, 3 are all fixed.  thanks!

**Comment by steffipravasi** [comment]
1) The Save changes dialog is now displayed even when there are no changes made
I guess it should only display when there is a change made 
2) We need to add validation to check for any changes made even after Saving the goal. 
Added details to the goal and saved it. Now made changes and clicked on the close button or anywhere outside the modal, then my edits are now gone.
Should we keep the Save Changes button at the bottom of the create goal? Currently, once the goal is saved, the Save changes button is hidden
3) Goal is added twice when user Saves the goal,  is on the create new goal modal and the auto save functionality saves the goal again
<img width="364" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWFvQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--612b55ed5e0dba03dd624653bc0b8dce6b1852e2/Screenshot%202024-01-08%20at%2011.16.12%E2%80%AFAM.png" alt="Screenshot 2024-01-08 at 11.16.12 AM.png" />
4) Once user clicks on ok on the auto-save message, they should be left on the create goal page where they left and not close the goal modal completely

**Comment by jizhaogit** [comment]
This is a problem. Our 'create new goal' page ONLY has a create function and does not have an update function. This causes all the 'save' buttons or auto-save actions to save a new goal. Originally, this design was intentional because, before we made modifications, the modal would automatically close when a goal was saved, regardless of whether the 'save' button was clicked or the auto-save feature was triggered. However, now that we want the modal to remain open after saving, this has become an issue.

**Comment by steffipravasi** [comment]
@jizhaogit I didn't tag you in the comment because I was hoping to have a chat about it with Travis in the meeting first 😅

**Comment by jizhaogit** [comment]
@steffipravasi  LoL...  just want to explain the issue from my dev side

**Comment by jizhaogit** [comment]
1. done
2/3  i added back the auto-save pop up message, please help verify
4. done

**Comment by steffipravasi** [comment]
Did not receive the auto-save pop up message but instead just a message on the top saying 'Your goal has been saved". Not sure if this is a change added
Also, The second time the auto-saves happens the message was updated to Your Goal has been Updated. Shouldn't it always say 'Your goal has been saved? https://bcgov.sharepoint.com/✌️/r/teams/02915/Shared%20Documents/Product%20Team/Tickets%20Requirements/1183/3.mov?csf=1&web=1&e=ZrLeWE

**Comment by steffipravasi** [comment]
Goal save and Auto save function working as expected.

**Comment by Travis-A-Clark** [comment]
@steffipravasi If I go in to edit a goal after I created it, I get a 500 error when I save changes. Is this happening for you as well?

<img width="1078" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGI0QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--be2e022dbe9b7616a2cc1fb12a8e21c2353c9bf7/image.png" alt="image.png" />

**Comment by steffipravasi** [comment]
Yes Travis, I noticed that when I was testing accessibility and added the bug in the same ticket #1211 thinking its related. However, to address the issue quicker, I have added a new ticket #1213 and assigned to Ji. Thank you!
