### ISSUE TITLE
Shared employee not showing on supervisor's My Team list

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#1185]
### Scenario

Employee name: Carly Shaw
Employee ID: 150340
Supervisor name: Richard Leong
Supervisor ID: 009065

In both PROD and TEST. Carly is shared with Richard.

<img width="1057" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3BjQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fb44d2496a22e3f72749bd4035b4c452ad069e33/image.png" alt="image.png" />
<br>

However, Carly does not show up on Richard's My Team page.
<img width="289" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2hjQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5e79da225c0a73280b3e87534997d476209c7376/image.png" alt="image.png" />

**Comment by Travis-A-Clark** [comment]
Seems very similar to ticket #1166.

**Comment by jizhaogit** [comment]
<img width="1713" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHBjQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--541919953bbf20a60a101c59c4d056db0a10ac5a/image.png" alt="image.png" />

after i switch account to empid 009065 i can see the "My Team" link and the page works as expected.

**Comment by Travis-A-Clark** [comment]
Yes, but as per the description above, the employee that was shared with this supervisor is not visible on the Shared with Me list of My Teams page.

Carly Shaw should be there but is not shown.

**Comment by jizhaogit** [comment]
Hi Travis, i checked prod database about the shared with data, details as below:

mysql> select id, employee_id, name from users where employee_id = '150340';
+-------+-------------+------------+
| id    | employee_id | name       |
+-------+-------------+------------+
| 26934 | 150340      | Carly Shaw |
+-------+-------------+------------+
1 row in set (0.00 sec)

mysql> select * from employee_shares where user_id = 26934;
Empty set (0.01 sec)

looks like the employee Carly Shaw has no sharing record.  i will need go to check the dashboard "My Profile is shared with" list to see how it is generated

**Comment by jizhaogit** [comment]
Detail that found:

Our shared with list will not include those employees that the "reporting_to" field in users table is same as the login user id.  in this case, Carly Shaw's reporting_to is still stored as Richard Leong's user id.  but in the admin employee list, the his direct report supervisor is marked as Provencher,Genevieve.
After manually modified the "reporting_to" filed from Richard Leong to Provencher,Genevieve this issue is got fixed.  
@telusdcinco Dennis, when you come back can you please help check the backend process to see what caused the gap that users table's reporting_to' field is different with users_annex table's 'reporting_to_employee_id' field?  thank you!

**Comment by Travis-A-Clark** [comment]
@jizhaogit It looks like this issue has returned. Perhaps the "reporting_to" field that you manually updated was overwritten by one of the auto overnight processes?

**Comment by jizhaogit** [comment]
@Travis-A-Clark manually trigger the fix process does the fix for the data error.  its need daily running since ODS daily process is running every day.

**Comment by steffipravasi** [comment]
Verified this issue on Test region and employees are displayed in the Supervisor's team page

**Comment by jizhaogit** [comment]
a sync process is added in daily process PopulateUsersAnnexTable to update users.reporting_to = users_annex.reporting_to_userid
