### ISSUE TITLE
No action happens on changing/selecting my current supervisor

### ISSUE THREAD

**Issue by steffipravasi** [bcgov/performance#1187]
An employee with multiple supervisors have the option to switch their supervisors. 
But when selecting a supervisor from the drop-down list, the page does not respond in any way after confirming in the confirmation dialog box. Hence, it results in employee making changes multiple times.
 
Although the changes are reflected when page is refreshed,

Expected outcome: Add an obvious response to let the employee know about the change
<img width="159" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2hoQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1f3499d82ae1a68d32832a71b054541f32e2ab63/Screenshot%202023-12-14%20at%203.28.00%E2%80%AFPM.png" alt="Screenshot 2023-12-14 at 3.28.00 PM.png" />

**Comment by Travis-A-Clark** [comment]
This is a bug introduced recently. In the past, when a user selected a supervisor from the dropdown list, a process was initiated to update all of the reporting relationship info and the page was refreshed. It could take 2-5 seconds before the process was complete and the page refreshed. Now there is no action taken.

This was part of the design of ticket #857. Perhaps it was undone through the updates run two weeks ago.

We really need to get this process fixed once and for all. We have had a lot of tickets in this area that seem to fix one piece but break another. Let me know if there is anyway I can help.

**Comment by Travis-A-Clark** [comment]
Could this be something as simple as the auto refresh being missed from the sequence after the button click to select supervisor from dropdown list?

@steffipravasi From what you can tell, are all of the functions actually updating? Just not the page refresh?

**Comment by steffipravasi** [comment]
yes the Supervisor - employee relation is updated. 
So without refreshing if we check the supervisor's end, we can see the updated results.

**Comment by Travis-A-Clark** [comment]
Okay. So, hoping this will be a relatively quick fix for @jizhaogit then. Fingers crossed! :-)

**Comment by Travis-A-Clark** [comment]
I'd like to push this at the same time as 1186. We can do both together and push next week once we are comfortable with the supervisor selection process, and the impact on the supervisor My Team page.

**Comment by steffipravasi** [comment]
Test validated. 
Page refreshes after 1-2 seconds of changing the supervisor and the changes are reflected on the profile.
