### ISSUE TITLE
Move the overnight auto email send process to 7:30am PST

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#1188]
Currently, all of our overnight processes are initiated around 2:30am PST. This means that users are receiving auto emails in the middle of the night. We have received complaints that these are waking people up. They need to have their phones on in case of emergency so cannot ignore the alerts.

Would it be possible to move just the email send process to trigger at 7:30am PST instead? Everything else can run as normal. Thanks!

**Comment by jessicahjwu** [comment]
Pipeline: To be estimated
No sprints assigned yet

**Comment by telusdcinco** [comment]
@jessicahjwu Please provide additional info on type of email received.  I don't see anything email to be triggered at 2:30am.  Earliest I can see was 6:15am for the Conversation Due Date Notifications, which can re rescheduled at 7:30am.  There is also the 8am notifications, which should not be an issue.

**Comment by telusdcinco** [comment]
Changed email notification sending process to 7:30am.
<img width="650" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTBmQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5188b412b5e9f6aacc2c73fff9a458bffd58ee8e/image.png" alt="image.png" />

**Comment by telusdcinco** [comment]
@steffipravasi Please confirm on or after Feb 2nd for the time change from the process logs.

**Comment by steffipravasi** [comment]
The emails process triggered at 7:30PT on Feb 2
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK01rQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ad435207908365e884d44cd548f63122f3b23763/Screenshot%202024-02-02%20at%2011.46.14%E2%80%AFAM.png" alt="Screenshot 2024-02-02 at 11.46.14 AM.png" />

**Comment by steffipravasi** [comment]
The emails process triggered at 7:30PT on Feb 2
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK01rQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ad435207908365e884d44cd548f63122f3b23763/Screenshot%202024-02-02%20at%2011.46.14%E2%80%AFAM.png" alt="Screenshot 2024-02-02 at 11.46.14 AM.png" />

**Comment by jessicahjwu** [comment]
@Travis-A-Clark do you remember which ministry that raised this? I can check with them to see what types of notifications the user was getting, and if it's still happening. Thanks!

**Comment by Travis-A-Clark** [comment]
@jessicahjwu You can find the initial comment from FIN in the Teams Channel:

[12/13/23 1:17 PM] McPhie, Kathleen FIN:EX
Timing of Auto-Generated Email Notifications
Hello,
We have received questions and wonder if it is possible to adjust the timing of the PDP auto-generated notification emails to avoid them coming in the middle of the night as some staff need to have their phones on in case of emergencies? 
Thank you.

----

Judging from the auto responses coming in to the PDP.NoReply mail box, it still looks like things are being sent around 2:50am.

<img width="395" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMEVzQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d7ba4f93804871c3c2e043dae2fcf63a72dd130f/image.png" alt="image.png" />

**Comment by telusdcinco** [comment]
Further investigation reveals that the Prod copy of kernel.php (process schedule) is not in sync with the rest of the environments.  Prod is showing NotifyConversationDue process running at 2:30am when it should be running at 6:15am as per previous setting, and will be modified to 7:30am with this change.

<img width="1847" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNm9zQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--af6aadab64c274a532e765a7df78c0e57e8768f0/image.png" alt="image.png" />

**Comment by telusdcinco** [comment]
Note to Migrator:

Force copy kernel.php from Training to Prod.

**Comment by jessicahjwu** [comment]
Discovered that the change in time for pushing out notifications intended in [#995](https://app.zenhub.com/workspaces/performance-development-60020b0a13a09c0014af2469/issues/gh/bcgov/performance/995) was not pushed to Prod

**Comment by telusdcinco** [comment]
Prod confirmation.

<img width="689" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGRNQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a24646032070f90b971b36ebdbbcf8aea19e6796/image.png" alt="image.png" />
