### ISSUE TITLE
Investigate performance lags and server errors in PROD

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#1190]
PROD is noticeably lagging performance wise with goals and conversations pages taking 5-10 seconds to load rather than the near instant performance in the past. 

Some pages don't load and are showing 500 or 504 errors:

<img width="869" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVoxQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--89a0ae8cae6b2fb87dd4f0e968e23c0c8ea1f8cc/image.png" alt="image.png" />
<br>
<br>
 
Other pages do load slowly showing performance errors in Edge developer tools. Example below from the My Goals page:

<img width="675" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTExQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--138717f980e77c42eddf556054486ac91852ab21/image.png" alt="image.png" />

**Comment by jizhaogit** [comment]
@Travis-A-Clark 
<img width="512" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMForQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--989ec1af45f98c9c77093043aa090adc4efce1a8/image.png" alt="image.png" />

The memory usage is return to normal after we increased the RAM and CPU number. Memory is up to 2.4Gi, and was capped at 2Gi before. it looks very likely that was killing everything. Just needed a little room to breathe

**Comment by steffipravasi** [comment]
Ticket to be validated on prod
