### ISSUE TITLE
Backup of ZenHub Board for PDP

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#1191]
Need to backup ZenHub content before we lose our license to the board. 

@jessicahjwu will add some additional details in the comments sections of priority tickets to ensure we don't lose valuable info. All comments will remain visible in GitHub even without ZenHub board.

@jizhaogit will run the API based backup in line with the processes outlined on Digital Journeys ticket: 

https://github.com/bcgov/digital-journeys/issues/1515#issue-2044285792

**Comment by jizhaogit** [comment]
Email from ZenHUb about extension to January 15
"After the discussion with the accounting, contracts and leadership teams, we are happy to offer you a grace period for the Zenhub Enterprise Licence contracts. The updated service termination date is January 15th, 2024."
DJ team will still back-up board, take a screenshot and save files to Teams folder as a precaution.

**Comment by jizhaogit** [comment]
second backup done at 2023-12-28

**Comment by jizhaogit** [comment]
third backup done and 2024-01-08
