### ISSUE TITLE
Duplicate the Confirm/Save dialog for Create goal to Edit Goal

### ISSUE THREAD

**Issue by steffipravasi** [bcgov/performance#1194]
Ticket reference #1183

The edit goal page neither has a Cancel button or a Back button.
Can we discuss the ticket in the grooming meeting to find a way to improve the buttons?

----------------------------------------------------------------

March 14 Requirements Discussion :
1) Change Back to List button ticket #972
2) Add a Back button on the edit page
3) Add a Cancel button besides the Save button. The Cancel button will not save any added changes to the goal.

**Comment by jizhaogit** [comment]
As we discussed in scrum meeting, added "back to list" button in both goal edit and goal detail pages

**Comment by steffipravasi** [comment]
@jizhaogit I have one question and 2 bugs
Bug:
1) The back to list button on the edit page, must be renamed to Back only since back to list does not make sense as the previous page is not the list. Can we change it to 'Back' only?
<img width="1327" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3p1QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8f93c467b35f88affb1109486cd5cb1104edb162/Screenshot%202024-03-19%20at%202.06.30%E2%80%AFAM.png" alt="Screenshot 2024-03-19 at 2.06.30 AM.png" />
2) The Back to list button does not function as expected when following the steps:
- Open a goal
- Click on edit
- Click on back to list
- On the view goal page, again click on back to list button
- Notice that the back to list button takes user to the edit page instead of going to the list
--------------------------------------------
Question:
Is it possible to change the confirmation modal from browser to similar to the one we have on other places of app?
<img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1h1QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--35c16e17e11295020dceed523801c1befcb00bb3/Screenshot%202024-03-19%20at%201.03.37%E2%80%AFAM.png" alt="Screenshot 2024-03-19 at 1.03.37 AM.png" />
<img width="812" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0R1QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--469e85d75ecbcc5f76cda013ec45092ff463fcb2/Screenshot%202024-03-19%20at%202.13.54%E2%80%AFAM.png" alt="Screenshot 2024-03-19 at 2.13.54 AM.png" />

**Comment by jizhaogit** [comment]
i added 1 more score point to change the alert browser build in function to use the modal dialog.

**Comment by Abuchana** [comment]
Change alert dialogue to modal dialogue

**Comment by jizhaogit** [comment]
the confirmation modal is added.

**Comment by steffipravasi** [comment]
1) Fixed
<img width="912" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0wwQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c07e05b6e57b98ba4f0845dc78c4bb582c442220/Screenshot%202024-03-19%20at%2011.17.19%E2%80%AFPM.png" alt="Screenshot 2024-03-19 at 11.17.19 PM.png" />
2) Fixed
3) Fixed
---------------------------------------------------------------------------
@jizhaogit I can still see the browser confirmation modal on the click on Cancel and Back button after making changes. Have we deployed that fix to test yet?
<img width="1465" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1gwQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bbbb9cb2bb48f508b6cdb7947ed217ac00e3fc8c/Screenshot%202024-03-19%20at%2011.19.17%E2%80%AFPM.png" alt="Screenshot 2024-03-19 at 11.19.17 PM.png" />

**Comment by jizhaogit** [comment]
!. the alert box was missed to be removed.  thanks for the catching and it is now addressed.
2. i also found that the auto save time range was set as 3 minutes in the edit page.  it is now be adjusted to 20 minutes.

**Comment by steffipravasi** [comment]
Working as expected
