### ISSUE TITLE
Remove judiciary from the ODS data pull

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#1195]
- [x] - Jessica to confirm no information is contained in the PDP for the people in 105-1115
- [x] - Jessica to confirm no information is contained in the PDP for the people in 105-1200
- [x] - Dev to remove the Dept IDs from the ODS pull
- [x] - Dev to remove the impacted people from the PDP (or hide their info)
- [x] - Dev to update the reports and employee lists
- [ ] - Dev to back up the database

We need to remove provincial and superior court judges from the PDP. I had asked that the ODS team remove them on their end so that they were not pulled into the PDP to begin with. The ODS team has responded by asking that we alter the PDP query of ODS to exclude these department IDs on the PDP end of things.

Can we please flag and remove dept ID Provincial Court Judiciary (105-1115) and Superior Court Judiciary (105-1200) from the ODS data pull that feeds the PDP? This should stop the PDP from creating profiles for these employees and effectively delete these employees from the PDP process.
[ZH1195_Excluded_Employee_List.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1JRQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8b3e9c4470a619c04b0f1b5191c37778e81850b9/ZH1195_Excluded_Employee_List.xlsx)

1) Justice	Judiciary - Superior Court	Superior Court Judiciary	Superior Court Judiciary	Superior Court Judiciary			

2) 'Justice', 'Judiciary - Provincial Court', 'Provincial Court Judiciary', 'Provincial Court Judiciary', 'Provincial Court Judiciary',

**Comment by jizhaogit** [comment]
code change looks good to me.   thank you!

**Comment by telusdcinco** [comment]
Migration Notes:

Run 'php artisan migrate'
Run 'php artisan db:seed --class=DataFix_1195_Setup_Excluded_Departments'

*May require re-running overnight processes to see effect immediately.

**Comment by steffipravasi** [comment]
@telusdcinco Is it possible for you to give me the list of employees in these 2 departments? I cannot find them in the employee or past employees list of course but without the details just with the department id, it is difficult for me to verify.

**Comment by telusdcinco** [comment]
@steffipravasi Follow the link for list of employees under the excluded departments.

https://bcgov-my.sharepoint.com/:x:/r/personal/dennis_cinco_gov_bc_ca/Documents/ZH1195_Excluded_Employee_List.xlsx?d=w3c41bc4e047347c8986b40551d5a274a&csf=1&web=1&e=V46G34

**Comment by steffipravasi** [comment]
@telusdcinco A quick question, are we expecting the users to appear as supervisor?
<img width="750" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2hQQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f9b454ebc041905863bc74775cf16809c1ea1575/Screenshot%202024-02-12%20at%205.22.59%E2%80%AFPM.png" alt="Screenshot 2024-02-12 at 5.22.59 PM.png" />
<img width="948" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3BQQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e45d2ed080b70bac750389392629baac8bc7815c/Screenshot%202024-02-12%20at%205.27.28%E2%80%AFPM.png" alt="Screenshot 2024-02-12 at 5.27.28 PM.png" />

**Comment by telusdcinco** [comment]
@steffipravasi 

Items 1 to 3 have been resolved in Test.

Item 4 should be a separate issue.  The error occurs for specific organization/level1/level2 combinations only.

Item 5 is no longer an issue.

**Comment by steffipravasi** [comment]
@telusdcinco 
Statistics & Reporting -> Goal Summary -> When trying to filter all the Levels for the excluded orgs -> Clicking on search button -> Receiving 500 Server error
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjVjQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f880a9ed7d7751217d814a522dc67ba70c053f55/Screenshot%202024-02-14%20at%204.07.09%E2%80%AFPM.png" alt="Screenshot 2024-02-14 at 4.07.09 PM.png" />
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjljQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--70be312748e6837f5a88127bf266b815136a2787/Screenshot%202024-02-14%20at%204.07.28%E2%80%AFPM.png" alt="Screenshot 2024-02-14 at 4.07.28 PM.png" />
<img width="410" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0JjQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cb8a467ad96c3eed5a73532d337df0adbc48822e/Screenshot%202024-02-14%20at%204.07.14%E2%80%AFPM.png" alt="Screenshot 2024-02-14 at 4.07.14 PM.png" />

**Comment by telusdcinco** [comment]
Last issue is relating to dividing by zero in the calculations.  This should be a separate ticket.

<img width="317" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUJuQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fa5f0ee93439cc7c0b73217d0c8efb9e8402c31a/image.png" alt="image.png" />

**Comment by jessicahjwu** [comment]
Feb 23 - Changes deployed to PROD, will check on Monday Feb 26 to validate.
