### ISSUE TITLE
User does not receive email notification 

### ISSUE THREAD

**Issue by steffipravasi** [bcgov/performance#1196]
Bug found while testing ticket #1169
HR admin: Shawna Wilson
Goal name: Hello
- From Goal Bank -> Manage goals in goal bank -> Individual audience -> Shawna filtered the Justice org to 
- Justice -> BC Corrections -> Corr-Community Corrections -> Community Corrections-Fraser Reg -> Delta/West Surrey Comm Correct
- The list has total of 10 employees. 
- By choosing the select all option, Shawna selected YEs to the send notification option and assigned the goal
- The Individual audience list displays 10 employees
- But the email notification only had 9 employees
- User 126735	Howes,Amanda is missing
- Confirmed tAmanda's profile setting and she has the setting on to receive email notifications
- <img width="1117" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3VwQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bc21bef228e9d00754c03009f558925858d03d88/Screenshot%202024-01-08%20at%202.45.31%E2%80%AFPM.png" alt="Screenshot 2024-01-08 at 2.45.31 PM.png" />
<img width="1232" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3lwQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5d27822ade42df555a8934e97b3408b31a86a86e/Screenshot%202024-01-08%20at%202.45.52%E2%80%AFPM.png" alt="Screenshot 2024-01-08 at 2.45.52 PM.png" />

<img width="860" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzZwQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ad787e59651fcb16a9327e2f03b303b73ea290c3/Screenshot%202024-01-08%20at%202.47.09%E2%80%AFPM.png" alt="Screenshot 2024-01-08 at 2.47.09 PM.png" />

**Comment by Travis-A-Clark** [comment]
Excused employees should not receive email notifications. Still check to make sure it's operating as intended, but if employee is excused they shouldn't receive emails. Thanks!

**Comment by jizhaogit** [comment]
protected function notify_employees($goalBank, $employee_ids) {
        // Filter out the employee based on the Organization level and individual user preferences. 
        $filtered_ee_ids = UserDemoJrForGoalbankView::join(\DB::raw('access_organizations USE INDEX (access_organizations_orgid_unique)'), function ($on1) {
                return $on1->on('access_organizations.orgid', 'user_demo_jr_for_goalbank_view.organization_key')
                    ->whereRaw("access_organizations.allow_email_msg = 'Y'");
            })
            ->leftjoin(\DB::raw('user_preferences USE INDEX (user_preferences_user_id_index)'), function ($on2) {
                return $on2->on('user_preferences.user_id', 'user_demo_jr_for_goalbank_view.user_id')
                    ->on(function ($where2){
                        return $where2->whereRaw("user_preferences.goal_bank_flag = 'Y'")
                            ->orWhereNull('user_preferences.goal_bank_flag');
                    });
            })
            ->whereIn('user_demo_jr_for_goalbank_view.employee_id', $employee_ids)
            **->whereNull('user_demo_jr_for_goalbank_view.excused_type')**
            ->pluck('user_demo_jr_for_goalbank_view.user_id')
            ->toArray(); 
...

confirmed that the excused employees will not get email notification from the goalbank assignment.
