### ISSUE TITLE
Auto excuse department ID 105-2111

### ISSUE THREAD

**Issue by jessicahjwu** [bcgov/performance#1199]
Request from the Registrar at the Employee Standards Tribunal to auto excuse their department:
Organization: Justice	
Level 1: ABCs and Other Tribunals	
Level 2: Employment Standards Tribunal	
Level 3: Employment Standards Tribunal
Dept ID: 105-2111

**Comment by telusdcinco** [comment]
Migration Notes:

Run "php artisan db:seed --class=DataFix_1199_Amend_Excused_Departments" to add 1 dept ID to be excluded.
Run "php artisan command:CalcNextConversationDate" to update excused statuses.
Run "php artisan command:PopulateUsersAnnexTable" to update static details.

**Comment by telusdcinco** [comment]
@jizhaogit  Please peer review the code change.

**Comment by jizhaogit** [comment]
thank you Dennis. looks good to me!

**Comment by telusdcinco** [comment]
Test setup completed.
<img width="624" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3dTQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6cb839e8f2dc026536c7dfbb23ec2a12ad078adc/image.png" alt="image.png" />

**Comment by steffipravasi** [comment]
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTRaQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3ccaeb65f2106d74ee16b709ef3879f7dc4a47ef/Screenshot%202024-01-31%20at%204.07.29%E2%80%AFPM.png" alt="Screenshot 2024-01-31 at 4.07.29 PM.png" />
