### ISSUE TITLE
Goal title field remains highlighted even after adding the title

### ISSUE THREAD

**Issue by steffipravasi** [bcgov/performance#1201]
Issue derived from #1183
Steps to reproduce:
- Open Create new goal modal
- Leave title field empty
- Add goal tags
- Click on close button
- Save changes button
- Add the Goal title
- Remove all the selected Goal tags
- Click on close button
- Save changes button
- Notice that the Goal title field still remains highlighted in red

Expected result: Once the goal title field is added, it must not remain highlighted on the click of Save Changes button
<img width="921" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1RQQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bcf06182e92bc88b5cfd605d69d72fae93a7b99f/Screenshot%202024-01-16%20at%203.50.57%E2%80%AFPM.png" alt="Screenshot 2024-01-16 at 3.50.57 PM.png" />

**Comment by steffipravasi** [comment]
@jizhaogit Issue is not fixed yet. Please follow the steps to reproduce and notice that the goal title field is still highlighted in red colour
<img width="1254" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0cxQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e67b2675dc2b6a9e655b3de2640e14bea683d117/Screenshot%202024-07-04%20at%201.00.27%E2%80%AFPM.png" alt="Screenshot 2024-07-04 at 1.00.27 PM.png" />
Recoding attached : https://bcgov.sharepoint.com/:v:/r/teams/02915/Shared%20Documents/Product%20Team/Steffi%20-%20Testing/Screen%20Recording%202024-07-04%20at%201.01.40%E2%80%AFPM.mov?csf=1&web=1&e=2Q83Z9

**Comment by jizhaogit** [comment]
thanks Steffi, this issue should be address too., the fix was on the bottom "save" button

**Comment by steffipravasi** [comment]
Issue addressed at Create new goal -> My current goals
