### ISSUE TITLE
Server Errors: recipient_ID

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#1202]
Explore and fix the cause of the recipient_ID errors coming up in the error log. Add info to this ticket on progress as it becomes available.

This is part of the broader effort to improve performance and stability in the PROD environment.

**Comment by jizhaogit** [comment]
Linked issue: #1203

1) Updated notification_log_recipients to log recipient_id avoid null
2) fixed bug for viewProfileAs in team list
3) fixed bug for date_deleted in users table (which is not a column for users table)

**Comment by Travis-A-Clark** [comment]
I think it makes sense to use the system log to check in every few days once the fix is in place and track the number of errors to ensure they are going down.
