### ISSUE TITLE
Information from ODS (supervisor info) doesn't sync with PDP user annex table

### ISSUE THREAD

**Issue by jessicahjwu** [bcgov/performance#1206]
User Demo is showing the same info as ODS, however it's disconnected with the other two tables that we're using to determine supervisor - employee relationships.

Example 1 - Kathleen Bell is reporting to Julia McLean in the PDP, however in PeopleSoft and other applications she's reporting to Beverley McKenzie who's the right supervisor.

Example 2 - Sienna Randolph is reporting to Niomi Paulmert in the PDP, however in PeopleSoft she's reporting to Bryna Warren who's the right supervisor

Example 3 - Meaghan Hoyle shows up in Employee List as reporting to Chris Trumpy who's the correct supervisor, and same in the direct report list for Chris. However, when they each go in to their PDP, Chris doesn't have Meaghan on the list of Direct Reports and Meaghan's current supervisor shows up as "vacant".

**Comment by steffipravasi** [comment]
@jizhaogit Example 1 and 2 are fixed. However, for example 3, PDP still displays 'Vacant' as the supervisor for Meaghan Hoyle. Also, Meaghan does not appear in the direct reports list for supervisor Chris Trumpy.
<img width="1270" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzd3QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5f92fbeec0613e87a10eba2ca50112443516a219/Screenshot%202024-01-23%20at%202.34.56%E2%80%AFPM.png" alt="Screenshot 2024-01-23 at 2.34.56 PM.png" />

Requirement from ticket: Example 3 - Meaghan Hoyle shows up in Employee List as reporting to Chris Trumpy who's the correct supervisor, and same in the direct report list for Chris. However, when they each go in to their PDP, Chris doesn't have Meaghan on the list of Direct Reports and Meaghan's current supervisor shows up as "vacant".

**Comment by jizhaogit** [comment]
@steffipravasi  the #3 issue should be addressed now. could you please help verify again? thanks!
