### ISSUE TITLE
Privacy Incident: View Goals

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#1207]
The URL to access a goal in the platform is performance.gov.bc.ca/goal/### where the ### is the goal ID. Any user, by simply changing the goal ID, can view any goal for any employee across the entire system. Goals should only be viewable by those with access to see them (i.e. employee, supervisor, anyone the goal has been shared with). View access should be the same as access to comment on the goal.

Let's address in two phases:

1. Randomize the goal ID to the 8-character alphanumeric hash like F3KA21PE and run a script to update all existing goal IDs in the database.
2. Apply the same permissions to the “view goal” function that already apply to the “comment on goal” function.

This looks like an extension of work done on ticket #583.

**Comment by Travis-A-Clark** [comment]
Ji and I chatted. We are moving straight to option 2 and updating the security permissions. It looks like it will be quicker and will address the issue at root.

**Comment by jizhaogit** [comment]
added access restriction checking for view goal features.   what we want: ONLY goal's owner,  owner's supervisor, all the managers that the owner be shared with and the users who have been shared with the goal can access the goal.

**Comment by Travis-A-Clark** [comment]
We also need to address the ability to change the user ID number in the links from the My Team page (shown below) that allows a supervisor to view any other employee. 

Example:

https://performance.gov.bc.ca/my-team/view-as/13619

You can change the user ID at the end of the URL and view any employee profile. This is true for all the links coming from My Team. They should only be able to access the employees displayed on their My Team page.

<img width="1353" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOExjQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a92b98a256d7b74f6fbc98926e393f6b949a60e0/image.png" alt="image.png" />

**Comment by jizhaogit** [comment]
a new fix is read in test for this detected issue.

**Comment by steffipravasi** [comment]
The My Goals page, link and permission looks good now. 
The Direct reports is still not fixed completely. Supervisor can only view the Direct reports list of some employees and for some, the permission error is received. Ji is looking into the issue. 

Employee: 000910	Wilson,Shawna

Supervisor: 099465	Robinson,Sheila

**Comment by jizhaogit** [comment]
can you please try again? thanks!

**Comment by Travis-A-Clark** [comment]
Further to the conversation about My Team page above, the same logic has to be applied to each link on that page. The example links below

Clicking on employee name - https://performance.gov.bc.ca/my-team/view-as/13619
Clicking on number of employee goals - https://performance.gov.bc.ca/my-team/view-as/13619/goal.current
Clicking on employee next conversation - https://performance.gov.bc.ca/my-team/view-as/13619/conversation.templates
Clicking on employee direct reports - https://performance.gov.bc.ca/my-team/direct-report/13619

In all of those instances, changing user ID allows for access to unauthorized content. The direct reports is fixed. The employee name, goals and conversations links are not.

**Comment by jizhaogit** [comment]
Clicking on employee name - https://performance.gov.bc.ca/my-team/view-as/13619
done

Clicking on number of employee goals - https://performance.gov.bc.ca/my-team/view-as/13619/goal.current
done

Clicking on employee next conversation - https://performance.gov.bc.ca/my-team/view-as/13619/conversation.templates
done

Clicking on employee direct reports - https://performance.gov.bc.ca/my-team/direct-report/13619
this is done in 2024-01-18's deployment.

**Comment by steffipravasi** [comment]
Test validated. The above links are not accessible by changing the user ID's.
