### ISSUE TITLE
Next Conversation Due Dates - Transportation Investment Corp

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#1208]
A new organization, the Transportation Investment Corporation, is joining the PDP. They have asked that all of their employees be assigned a next conversation due date of March 31, 2024.

In the past, @telusdcinco  has randomized the due dates for various organizations. Hoping he can set everyone within this org to the same date.

@jessicahjwu Please let Emma Power and Sarah Nannery from TIC know once this has been actioned.

**Comment by Abuchana** [comment]
@telusdcinco can you provide an estimate for this ticket? It might be something we want to do this sprint instead of one of the others. Jessica will decide based on your estimate. Thank you!

**Comment by telusdcinco** [comment]
Employee List Results:
<img width="1237" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWxvQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--49bb56b4847dc61d2366754cc6450fcad87b79da/image.png" alt="image.png" />

**Comment by telusdcinco** [comment]
@jizhaogit Please review code changes.

**Comment by jizhaogit** [comment]
Thank you Dennis. code looks good

**Comment by steffipravasi** [comment]
@telusdcinco Wondering why some of the users does not have the conversation due to March 31?
<img width="1246" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWQxQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fd7d07cacc8c7089722492d2148dff578ff68c7c/Screenshot%202024-02-20%20at%203.30.57%E2%80%AFPM.png" alt="Screenshot 2024-02-20 at 3.30.57 PM.png" />

**Comment by telusdcinco** [comment]
@steffipravasi Please confirm if these are multi-job cases.  The conversation due date may have been calculated based on the primary job details.

**Comment by telusdcinco** [comment]
@steffipravasi Please confirm if these are multi-job cases.  The conversation due date may have been calculated based on the primary job details.

**Comment by steffipravasi** [comment]
<img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMloxQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1c6f8301c4c0fdb93eac663f272eb99de5616301/Screenshot%202024-02-20%20at%203.40.20%E2%80%AFPM.png" alt="Screenshot 2024-02-20 at 3.40.20 PM.png" />

**Comment by steffipravasi** [comment]
@jessicahjwu Currently, for new hired employees, the next conversation due date is calculated based on their joining date. So joining date + 4 months. This is the reason we have around 30-35 employees who do not have the due date as March 31. Do we want to keep the same logic or change their due date to March 31?

**Comment by telusdcinco** [comment]
@jessicahjwu What will happen to the next due date after March 31, 2024?  Currently setting everyone in Transportation to March 31, 2024 due date, will make any new employees (after March 31) delinquent since their new due date is before their join date.

**Comment by telusdcinco** [comment]
@steffipravasi 

Updated rule for Batch 4
For TI Corp employees hired on or before March 31, 2024, the first next conversation due date will be  March 31, 2024.
For TI Corp new hires after March 31, 2024, the first next conversation due date will be hire date + 4 months.

Exceptions:  For multi-job cases the next conversation due date may be based on the other ministry.

**Comment by steffipravasi** [comment]
@telusdcinco This one employee still has the conversation date set to April 18. Did we miss any scenario?
174820	Varghese,Prince	Prince.Varghese@ticorp.ca

Also, for employees who are excused currently, if they become un-excused before March 31, then their date must also be March 31. Can you confirm if we have already addressed this scenario please.

**Comment by telusdcinco** [comment]
@steffipravasi 174820 is a multi-job case.  The TI Corp is empl record 1, citizens services is empl record 0.  The next conversation due date is being calculated using empl record 0.

**Comment by steffipravasi** [comment]
Test Data:
All below employees are excused manually:
1) 003020	Gergley,Chantelle Jeanette

2) 004952	Gow,Lisa A
completed convo with supervisor James Harvey after excused

3) 010447	Fritz,Debra A
Debra completed a conversation with Brennan Neitz who is the team member
Debra also completed a conversation with  Jennifer Ng who is the supervisor

4) 017240	Flood,Leanne
Signed conversation with supervisor Griffin,Shannon
5) 062368	Cheung,Phoebe
Phoebe completed conversation with Wong,Wincy - team member
6) 067696	Grover,Brent
has an open conversation with the supervisor
7) 007043	Bain,Nancy A (Auto-excused)

**Comment by steffipravasi** [comment]
After un-excusing the above employees and running the overnight process, confirmed that the employees conversation date will still remain March 31
<img width="259" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0tsQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--45ec29644921bb699793f040a29085f2558d3e58/Screenshot%202024-03-01%20at%201.19.43%E2%80%AFPM.png" alt="Screenshot 2024-03-01 at 1.19.43 PM.png" />
