### ISSUE TITLE
As an HR rep, I want to see a report listing which employees have set a goal

### ISSUE THREAD

**Issue by eyjwarren** [bcgov/performance#121]

**Comment by freshjwarren** [comment]
@Travis-A-Clark : Here's an idea for a BI walking skeleton

**Comment by freshjwarren** [comment]
@Kousthubha-M : Can you help turn this into a minimum viable story for reporting? What's the simplest thing that could be reported based on what's currently in the database?

**Comment by Kousthubha-M** [comment]
@freshjwarren We can report goal list with current status and who has created the goal filtered with dates.
