### ISSUE TITLE
Edit Goal gives 500 server error

### ISSUE THREAD

**Issue by steffipravasi** [bcgov/performance#1213]
When editing a goal from Current goals and clicking on the Save button throws the 500 Server Error.
<img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0Q1QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0ac1c8ab26990a609f29099e2be6e6cd6290feaa/Screenshot%202024-01-24%20at%2010.11.48%E2%80%AFPM.png" alt="Screenshot 2024-01-24 at 10.11.48 PM.png" />

**Comment by steffipravasi** [comment]
Test validated.

**Comment by jizhaogit** [comment]
Package pushed to prod on 2024-02-02 at 8:30 PM PST
