### ISSUE TITLE
Daily Notification Updates

### ISSUE THREAD

**Issue by telusdcinco** [bcgov/performance#1218]
- Update the distribution list
    - Travis to be removed
    - Employee 11 & Employee12 to be removed
    - James opted out
    - Kunal opted out
    - Jessica to be added
    - Ji to be added
  
- Modify email list location from code to the environment config maps
    - No code change required for list changes
    - May only require pod restart for change to take effect

Current List:
<img width="724" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd29hQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ea8b834929cf3998c9a2fb8274547c8b549e0e2a/image.png" alt="image.png" />

**Comment by telusdcinco** [comment]
Migration Notes:
Add lines below in Config Map.
<img width="560" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeU1hQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--86e0f1e56d8bbb3d618a9af95bc8316080198431/image.png" alt="image.png" />

**Comment by telusdcinco** [comment]
@jizhaogit  Please review code changes.

**Comment by telusdcinco** [comment]
@jessicahjwu @jizhaogit Dev have been updated.  Jessica and Ji should get the Daily Notification from Dev starting tomorrow morning at 8:00am

@jessicahjwu Updated Dev email notifications from Travis to Jessica.  Any goals/conversation notification will now go to Jessica's mailbox.

**Comment by jizhaogit** [comment]
thank you Dennis.. good for me .

**Comment by telusdcinco** [comment]
Updated with Steffi's email.
<img width="695" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVFlQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--70838462538b635ca03e5f1c1567ca88af75c54e/image.png" alt="image.png" />

**Comment by telusdcinco** [comment]
The cron job settings in Dev is different from the other environment settings, which prevented the daily notification from triggering this morning.  The cron job setting is matched with Test, and the notification from Dev should start coming in tomorrow 8am.

**Comment by steffipravasi** [comment]
Email notification received
<img width="1836" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWdrQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2b8dfc1135f780b34c2452f1164a88ae4b545fbe/Screenshot%202024-02-02%20at%2011.04.30%E2%80%AFAM.png" alt="Screenshot 2024-02-02 at 11.04.30 AM.png" />

**Comment by jessicahjwu** [comment]
I have been getting those notification emails since Feb 2 at 8am, all good.

**Comment by telusdcinco** [comment]
Prod confirmation.

<img width="1527" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHBNQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--06fc5613611f37a992911a0e138256f491c49d2a/image.png" alt="image.png" />
