### ISSUE TITLE
Replicate the Create New Goal from My Current Goals to Team Goal Bank

### ISSUE THREAD

**Issue by steffipravasi** [bcgov/performance#1219]
The features we updated for Create New Goal in My Current Goals needs to be replicated and applied to Create new goal in My Team Goals.
Issue: In ticket #1205, we have made the audience list to be unchecked as default. But if the user, for example, checks one employee from the audience list, and leaves the screen. After the auto-save, the dialog box with the auto save message is displayed, and once user clicks on Okay, there is another dialog box with message Goal saved. Once user clicks on Ok, the goal page closes automatically and the emails are sent out without giving the user option to add more audience.

Reference for features: #1183

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGsyQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1f42ee147281fc5055b0c0a6deef53c7b535f825/Screen%20Recording%202024-02-07%20at%2012.26.43%E2%80%AFAM.mov)

**Comment by jizhaogit** [comment]
@steffipravasi   it is ready for testing. for saving the testing time, i currently set the auto goal saving time as 1 minute.  please let me know if you want to adjust it. thanks!

**Comment by steffipravasi** [comment]
1) If goal modal is tried to close without making any changes, then the dialog box must not be displayed
<img width="1454" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMml6QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3b9c0717bcc45fef730fbdbbb19c4dc504bf96f6/Screenshot%202024-03-05%20at%2012.26.43%E2%80%AFPM.png" alt="Screenshot 2024-03-05 at 12.26.43 PM.png" />
2) Change the buttons similar to Create Goal in current goals
<img width="420" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzZ6QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bd5cd170d29da94be77056fa0ab9e46153fb762d/Screenshot%202024-03-05%20at%2012.37.26%E2%80%AFPM.png" alt="Screenshot 2024-03-05 at 12.37.26 PM.png" />
Current goals reference:
<img width="1350" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEd6QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3e8a4754178b5270b3207802763eda13d68fb33a/Screenshot%202024-03-05%20at%2012.39.29%E2%80%AFPM.png" alt="Screenshot 2024-03-05 at 12.39.29 PM.png" />
3)

**Comment by jizhaogit** [comment]
@steffipravasi #1 and #2 are addressed. but i didn't see #3 content. would you please help update it? thanks

**Comment by steffipravasi** [comment]
@jizhaogit The Goal bak page is not accessible right now
<img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1cxQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3afbf1498e81afd3690465f78c11a7822778f1d1/Screenshot%202024-03-05%20at%204.32.32%E2%80%AFPM.png" alt="Screenshot 2024-03-05 at 4.32.32 PM.png" />

**Comment by jizhaogit** [comment]
@steffipravasi  Sorry it is because one of an accessibility fixing file was missed.  should be good to check now.  thanks.

**Comment by jizhaogit** [comment]
@steffipravasi  those issues should be address, please help verify. thanks!

**Comment by steffipravasi** [comment]
@jizhaogit Issues 1-3,5-7 have been fixed except:
4) The validation check must not display the message if there are no changes made. Goal is saved with the auto-save feature -> Did not make any changes to the goal -> Clicked on close button -> Still receiving the pop-up message to save my goal
Expected: If no changes are made, then we do not need the confirmation message
<img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUhEQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--16592e9f2223a54a86826d9e94a4bf5e0620f624/Screenshot%202024-03-07%20at%204.42.55%E2%80%AFPM.png" alt="Screenshot 2024-03-07 at 4.42.55 PM.png" />

---------------------
Question for @jizhaogit. The following issue might need to be fixed at both the places: Current goals -> Create new goal and Team goal bank -> Create new goal
Please follow the following steps:
- Fill out some of the mandatory fields of the goal but not all
- Hit the close button
- Click on Save changes
- Message 'There are one or more errors on the page. Please review and try again.' must be displayed
- Click on Close button again without making any edits
- Notice that the goal modal closes itself.
Expected: Is it possible to give the same confirmation modal everytime until user clicks on Don't save or makes edit and saves the goal completely? If yes, do we want to fix it in this ticket or a new one?

**Comment by jizhaogit** [comment]
@steffipravasi since we decided to take the ticket for the goal UI updating i will say lets stay all the requirements in here since it is already big now.  i will keep working the requests you listed and will see if i can get them ready tomorrow (2024-03-08)

**Comment by steffipravasi** [comment]
All issues have been fixed and validated.

**Comment by jessicahjwu** [comment]
Getting error messages when trying to access the Goal Bank tab in Training:
<img width="1194" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjdQQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--73c23f50af99e830353310f37fdc66aee13fd3e8/image.png" alt="image.png" />

<img width="1038" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMi9QQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c5a1f877acc4f15ed0da448c3fb2b9543226ad02/image.png" alt="image.png" />
