### ISSUE TITLE
Your Goal is Saved message is displayed on the My Current Goals page when a goal auto saves from the Team Goal Bank

### ISSUE THREAD

**Issue by steffipravasi** [bcgov/performance#1220]
When the supervisor is creating a new goal from the Goal Bank -> Team Goal Bank -> Create new goal, and while editing the goal the goal is created/saved by the auto-save functionality, then the 'Goal is saved' msg is displayed on the My current goals page which does not make sense. 
Expected result: We are not expecting the msg 'Your goal is saved' message to be displayed anywhere except the create/edit goal modal
<img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0ZGQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5bad4bd32354d7642174ae1c61c036f773c6b3a8/Screenshot%202024-02-09%20at%202.39.48%E2%80%AFAM.png" alt="Screenshot 2024-02-09 at 2.39.48 AM.png" />
<img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0pGQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--709bee5e8914f24adfa0d0e62fe3c1b8de5515a3/Screenshot%202024-02-09%20at%202.39.43%E2%80%AFAM.png" alt="Screenshot 2024-02-09 at 2.39.43 AM.png" />
<img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd05GQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5f86ab8ad136d07be9973edacf02772b5c49b7c7/Screenshot%202024-02-09%20at%202.40.11%E2%80%AFAM.png" alt="Screenshot 2024-02-09 at 2.40.11 AM.png" />

**Comment by jizhaogit** [comment]
@steffipravasi due to the change of #1219,  this issue should be also solved. would you please help verify? thanks

**Comment by steffipravasi** [comment]
Issue fixed and working as expected now.
