### ISSUE TITLE
Supervisor isn't able to view direct reports of their direct reports

### ISSUE THREAD

**Issue by jessicahjwu** [bcgov/performance#1224]
Previously in the platform, supervisors are able to click on the number of direct reports on their "My Direct Reports" table, click on any of the names and be able to view goals/ conversations of those employees who report to the supervisor's direct reports:
<img width="1364" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFJQQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2949ea81952a7105c9807eacf4daf4e3b637b7b3/image.png" alt="image.png" />

<img width="1414" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHBQQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ee334da382e3d7784c7a3ea985d673aaa1abda67/image.png" alt="image.png" />

However, users reported (as of last Friday) that this function is not working anymore and the page returned as "You don't have the right permission to access this employee's file.":
<img width="858" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHRQQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1044e86d7795bca0cc87201acadd03e7b805a9ca/image.png" alt="image.png" />

Business requirement is that the supervisors of a team should be able to access conversations and goals of anyone below them in the org structure, through the abovementioned path.

**Comment by jizhaogit** [comment]
@steffipravasi
modified the reportingHierarchy checking for the direct report team members' page. please help verify. thanks

**Comment by steffipravasi** [comment]
@jizhaogit Receiving Server error when clicking on the number of Direct Reports to view
<img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFZaQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--10c84a7062f4170203bdfca90f95ce8437a99601/Screenshot%202024-02-14%20at%209.36.31%E2%80%AFAM.png" alt="Screenshot 2024-02-14 at 9.36.31 AM.png" />

**Comment by jizhaogit** [comment]
found the error is cause by mysql version diff between my dev local test.   a new function is applied to align the result.

**Comment by steffipravasi** [comment]
@jizhaogit 
still receiving the error <img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0JhQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--69c6022b2ef3d338a5bb973e3beb6e29c27efd23/Screenshot%202024-02-14%20at%2011.34.48%E2%80%AFAM.png" alt="Screenshot 2024-02-14 at 11.34.48 AM.png" />

**Comment by steffipravasi** [comment]
Shawna Wilson has Shuang Yu as direct reportee -> Shawna can see direct reportees of Shuang
Amarjot Sign is the direct reportee of Shuan Yu -> Shawna cannot see the direct reportees of Amarjot. 
Business requirement is that the supervisors of a team should be able to access conversations and goals of anyone below them in the org structure, through the above mentioned path.
<img width="1760" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2hhQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--db038d6303690fe4adfe97bd587495ec63f76607/Screenshot%202024-02-14%20at%2012.07.39%E2%80%AFPM.png" alt="Screenshot 2024-02-14 at 12.07.39 PM.png" />
<img width="1472" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3BhQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--05d108d7d0f36502c86c7f426b025939cd46bd74/Screenshot%202024-02-14%20at%2012.07.51%E2%80%AFPM.png" alt="Screenshot 2024-02-14 at 12.07.51 PM.png" />

<img width="646" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3RhQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fd1b802931801cb714926d95e438f8e9324b582d/Screenshot%202024-02-14%20at%2012.07.58%E2%80%AFPM.png" alt="Screenshot 2024-02-14 at 12.07.58 PM.png" />

**Comment by jizhaogit** [comment]
Hi Steffi, can you please help verify again?  after chat with Dennis we moved to use users_annex table for the supervisor referrences.  thanks

**Comment by steffipravasi** [comment]
Functionality working as expected.

**Comment by steffipravasi** [comment]
The error received when viewing the goals & conversation or clicking on the profile name for the direct reports for anyone below them in the org structure
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK05vQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--beaa04e1f9cd57181565889b0998e8294c6c4c97/Screenshot%202024-02-16%20at%203.24.32%E2%80%AFPM.png" alt="Screenshot 2024-02-16 at 3.24.32 PM.png" />
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1JvQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e13abb027a5067a29247a48d344bf76a4d10cf3d/Screenshot%202024-02-16%20at%203.24.44%E2%80%AFPM.png" alt="Screenshot 2024-02-16 at 3.24.44 PM.png" />
