### ISSUE TITLE
Update Conversation Templates: Onboarding Template

### ISSUE THREAD

**Issue by jessicahjwu** [bcgov/performance#1226]
Onboarding Template

When to Use This Template

Use this template when an employee is new to the BCPS or new to their position. It will help to clarify expectations for the role, provide organizational context, define short-term goals, build the foundation of a trust-based relationship, and set an employee up for success. 

Preparing for the Conversation

Employee

•	Review resources available on MyHR including:
o	New Employee Journey
o	What to Expect During Probation
•	Review your job description, corporate or organizational plans, and other performance expectations that have been communicated to you by your supervisor.
•	Create a list of any questions you have for your supervisor about your role, your team, or the organization.
•	Come prepared to discuss styles of communication and ways of working to help build a strong and effective relationship moving forward.

Supervisor

•	Review resources available on MyHR including:
o	Setting Up a New Employee
o	Probationary Status
o	New Employee Journey
•	Confirm the employee has been given a copy of their job description and any corporate or organizational plans such as the ministry service plan.
•	Come prepared to discuss styles of communication and ways of working to help build a strong and effective relationship moving forward.
•	Note that this suggested approach is customizable based on the employee and their experience, considering things like:
o	Whether they are new to the BCPS or a transfer
o	Their tenure with the public service
o	The length and depth of their work experience prior to this role 

Suggested Discussion Questions

Participants can choose some or all the questions below, or develop questions of their own, to help guide discussions. Significant outcomes and action items should be captured in the comments section of the template.

Resources and supports:
•	Have you received access to all the information, tools, and resources you need to complete your responsibilities? 
•	Are there accommodations that are needed for you to succeed in this role or participate in the workplace? 
The role:
•	Do you have a clear understanding of the expectations for this role?
•	Which aspects of the job are you excited about? 
•	Which aspects of the job are you worried about?
•	Are there any job duties you would like clarification or support on? 
•	What challenges, if any, have you encountered while training or when performing your duties? What can we do address those challenges?
•	Are there any specific tools or training sessions that would help you be more successful?

Understanding organizational context:
•	What stood out for you when reviewing the Corporate Plan?
•	What questions do you have about your ministry’s vision, mission and mandate etc.? 
•	What questions do you have about how your role contributes to the ministry Service Plan?

Working together (supervisor and employee):
•	What motivates you at work?
•	What type of communication style and tools work best for you?
•	How do you prefer to receive feedback and/or recognition for your work? 
•	What would be the best use of our one-on-one time? 
•	What support do you need from me as your supervisor? 
•	What are your long-term goals within the BC Public Service and how can I support you to reach them?

Working with the team:
•	How are you settling into the team? 
•	What would help you feel connected to the rest of the team? 
•	Do you have any questions about the org chart and structure?
•	Do you have any questions about the team culture? 

Transferring employees:
•	What were your development goals in your previous role? 
o	Are there any that are appropriate to transfer over?
•	Do you have any questions about how ways of working in this role differ from your last role, such as communication, approvals, and culture? 
•	How can I best support you as you transition into this new role?
•	Of the list of mandatory training, are there any courses you haven’t completed?
•	How comfortable do you feel with the tools and resources provided?

Closing:
•	Is there anything else I should know?  
•	What specific areas do you intend to work on before we next meet? 
•	How would you like to work together to address challenges?
•	What feedback do you have about the onboarding experience? 

Comments and Action Items

Employee 

Comments (optional)

Action Items (optional) – capture actions to take as a result of this conversation [Mouse over info: “Indicate follow-up activities and areas for further discussion. Consider creating a goal in My Goals to track progress.”]
 

Supervisor 

Comments (optional)

Action Items (optional) – capture actions to take as a result of this conversation [Mouse over info: “Indicate follow-up activities and areas for further discussion. Consider creating a goal in My Goals to track progress.”]
 

Sign-off

[Yes/No] We have reviewed goals and adjusted as necessary.
[Yes/No] Performance expectations are clear.

Enter employee ID to sign:

[Checkbox] Team member disagrees with the information contained in this performance review.

Refer to this link for alignment: https://bcgov.sharepoint.com/:w:/r/teams/02915/Shared%20Documents/Product%20Team/Conversation%20Templates%20-%20Updates%20-%202024%2001%2030.docx?d=w3fbd39c84b02478b8fb58d60183e158e&csf=1&web=1&e=O39CEf

**Comment by steffipravasi** [comment]
Looks good from my end
<img width="1334" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMU9JQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--91381f1adbaf7c48ebd597fce9a8640b0550407f/Screenshot%202024-02-23%20at%203.54.02%E2%80%AFPM.png" alt="Screenshot 2024-02-23 at 3.54.02 PM.png" />
<img width="664" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVdJQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e02935c20e41238b0566b9828df8bb36802aa308/Screenshot%202024-02-23%20at%204.04.59%E2%80%AFPM.png" alt="Screenshot 2024-02-23 at 4.04.59 PM.png" />
