### ISSUE TITLE
Reporting relationships showing incorrectly in PDP even when PeopleSoft shows the accurate supervisor

### ISSUE THREAD

**Issue by jessicahjwu** [bcgov/performance#1228]
**Employee = Aika Rennie ID187462, Supervisor = Julie Kline ID130391**

Currently in PS:
<img width="1000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVpWQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6cc11cd3d297d8e3556fd0cc059e9ef3960f4615/image.png" alt="image.png" />

Currently in PDP, it shows that Aika reports to David Majcher:
<img width="762" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWhWQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--986062d72c53e5bb1082e72e485942b39c6bd30e/image.png" alt="image.png" />

Julie's position number shows up the same in the PDP as in PS:
<img width="1319" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWRWQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4fdcb7a97ad2f0305901aac25352322f26c2ffe1/image.png" alt="image.png" />

I've looked through Aika's PS records, and they have never reported to David in the past either. David and Julie both report to the same supervisor, however, they each holds a different job title and position number. Julie also mentioned that she has been getting notifications about Aika's conversation due dates.

Please check in the backend to see which table is showing this incorrect information, and where does it originate from. We will need a permanent solution for similar issues, as there has been a handful of these cases.

**Comment by telusdcinco** [comment]
Positions data shows that Aika's position number rolls up to David's position number.  ODS provides Julie as the manager for Aika.  PDP is currently following the order list below for obtaining the manager info.
1) Supervisor Override (none)
2) Position data (getting David as manager)
3) Next level from position data
4) ODS supervisor detail (getting Julie as manager)
5) Next level supervisor from ODS

To resolve the issue:
Option A:  Get the position hierarcy corrected from PS side.
Option B:  Use the supervisor override page to update the supervisor for Aika.
