### ISSUE TITLE
PDP Prod DB Issue

### ISSUE THREAD

**Issue by telusdcinco** [bcgov/performance#1229]
PDP Prod DB Issue

Database pod was not able to start up causing log in issue to PDP.

**Comment by telusdcinco** [comment]
<img width="864" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOEZiQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--898adc820e85ef21a7aa3d84330101253001f1e2/image.png" alt="image.png" />

**Comment by kkapoor-fresh** [comment]
Looking into it.  Just to double check ,were there changes made to the DB from our end(structural or query)?

**Comment by telusdcinco** [comment]
No change in DB.  I’m only aware of Silver cluster activities that may have triggered a pod restart.

**Comment by telusdcinco** [comment]
<img width="730" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3RiQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1d310a8e9031edd38d3cef5b05c3ac54291ca713/image.png" alt="image.png" />

**Comment by telusdcinco** [comment]
PDP Prod is back.

**Comment by warrenchristian1telus** [comment]
Yes - JFrog service/account has been restored. This shouldn't be an issue again, until we can transition to the BC DevHub instance.
