### ISSUE TITLE
Receiving Ajax error when filtering the employee list

### ISSUE THREAD

**Issue by steffipravasi** [bcgov/performance#1230]
Issue separated from #1195
When filtering trough the following levels in the Employee list page for Sys admin, Ajax error is received.
I figured out that the filters are working correctly till BC Corrections only. Receiving error when filtering anything in Level 2 of BC corrections
Justice -> BC Corrections 
<img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3BjQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6d13eb418185edbe8dd8c1766ec29f76309d47c6/Screenshot%202024-02-14%20at%204.19.15%E2%80%AFPM.png" alt="Screenshot 2024-02-14 at 4.19.15 PM.png" />

**Comment by telusdcinco** [comment]
MIGRATION NOTES:

Run 'php artisan migrate'.

**Comment by telusdcinco** [comment]
@jizhaogit Please review code change.

**Comment by telusdcinco** [comment]
Updated the backend data retrieval queries.  Change applied to both Current and Past lists.  Export function also updated.

**Comment by telusdcinco** [comment]
The load time improvements on the Employee List page can be applied to the rest of the Sys Admin pages.

**Comment by steffipravasi** [comment]
Functionality working as expected
<img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemIrQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2a1710c6486b480f68e8ba07c8653da94dd9a2d4/Screenshot%202024-03-21%20at%201.20.33%E2%80%AFPM.png" alt="Screenshot 2024-03-21 at 1.20.33 PM.png" />

**Comment by jessicahjwu** [comment]
@telusdcinco I wonder if we can apply the changes to HR Admin function first then onwards to Sys Admin? I will create another ticket for the similar (maybe) issues in the Stat and Reports page.
