### ISSUE TITLE
Divide by Zero Error in Statistics and Reports

### ISSUE THREAD

**Issue by telusdcinco** [bcgov/performance#1235]
Divide by Zero Error in Statistics and Reports

This ticket is to fix the calculation error in the Statistics and Reports that would result in a division by zero error.

Separated this issue from #1195 as this fix needs to be a priority.

**Comment by telusdcinco** [comment]
@jizhaogit Please review code change.

**Comment by jizhaogit** [comment]
thanks, Dennis. the change looks good.

**Comment by steffipravasi** [comment]
<img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjEwQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3ff555318069e542c8aae9e7bc12e6938f1647f8/Screenshot%202024-02-20%20at%201.32.04%E2%80%AFPM.png" alt="Screenshot 2024-02-20 at 1.32.04 PM.png" />
