### ISSUE TITLE
Create a process to remove PDP permissions when an employee changes jobs - HR Admins

### ISSUE THREAD

**Issue by jessicahjwu** [bcgov/performance#1237]
**Current Scenario**
A user is granted HR Admin access. That access stays in place until someone goes in and manually removes it. The user could change jobs multiple times and no longer have any legitimate reason to need the access. This creates a privacy concern.

**Desired Solution**
As part of the overnight processes, review all users with Service Rep access and flag those that have a change in position # or dept ID. Remove access for these users.

If the user still requires access, they can request it again and PDP team will provide.

**Comment by telusdcinco** [comment]
@jizhaogit  Please review code changes.

**Comment by jizhaogit** [comment]
@telusdcinco change looks good to me. thanks Dennis!

**Comment by steffipravasi** [comment]
Test data: 
148546	Thorogood,Paula
 
193485	Innes,Matthew
 
194946	Jones,Trystan
 
000278	James,Karen A
<img width="1117" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnYwQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--81fe2621cb2d9c5dc4f31014895f999508b3458f/MicrosoftTeams-image%20%285%29.png" alt="MicrosoftTeams-image (5).png" />
After updating position number in historical table.
<img width="1127" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnowQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--382315ce5cddc1d2aaac0dcc7d472d776e2d4fa4/MicrosoftTeams-image%20%286%29.png" alt="MicrosoftTeams-image (6).png" />
After Running the process.
<img width="482" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjMwQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--298f366d34df194a9d18a91fd4d9a889fc810419/MicrosoftTeams-image%20%287%29.png" alt="MicrosoftTeams-image (7).png" />
<img width="1262" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjcwQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cb7a939e953e079fc2abfeab02e7dc091ad22dc7/MicrosoftTeams-image%20%284%29.png" alt="MicrosoftTeams-image (4).png" />
