### ISSUE TITLE
Next conversation due date beyond four months

### ISSUE THREAD

**Issue by jessicahjwu** [bcgov/performance#1238]
User Miao Xu, 190841, did not seem to have logged any conversations in the PDP but is getting a conversation due date on Aug 31, 2024:
<img width="1256" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDZoQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c7b1af3f7ac7008c3ac3919fa9f26a0ac1f00dc0/image.png" alt="image.png" />

Looking at the notifications on his dashboard, he got conversation due date on Jan 1, 2024 (in Dec 2023) but he never actioned on it. Audit report also shows that email notifications were sent for Jan 1 due date. 
<img width="1588" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDJoQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--14dbfb16b364031761de1989765dfc9055f88efc/image.png" alt="image.png" />

Question: Why would he be getting the Aug 31, 2024 due date if nothing has been actioned?

**Comment by telusdcinco** [comment]
@jessicahjwu Identified a bud in the additional excused days added to next conversation due date calculation.  Impacted by the issue are those with completed excuses (with start and end dates).

**Comment by telusdcinco** [comment]
@jizhaogit Please review code change.

**Comment by jizhaogit** [comment]
thanks Dennis, looks good to me.

**Comment by steffipravasi** [comment]
<img width="1550" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWl6QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--523c8ee0f84a45fc242090a124a779845919067f/Screenshot%202024-03-05%20at%2012.20.19%E2%80%AFPM.png" alt="Screenshot 2024-03-05 at 12.20.19 PM.png" />
