### ISSUE TITLE
Team Goal Bank audience list 

### ISSUE THREAD

**Issue by jessicahjwu** [bcgov/performance#1239]
Supervisors Shelly Leary and Tracy Leung each created team goals for their team. However, the audience list is presented differently on most of the goals than the two goals below:
<img width="1527" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVdoQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1e0397082793608f7f2fa6d818edbf76be6984d5/image.png" alt="image.png" />

<img width="1343" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWFoQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3bf923d834018d8f5b3cd5ee1cea638aae9b83ec/image.png" alt="image.png" />

Question: They had issues reassigning the two goals in the first picture previously, as the list did not allow them to re-select audience. I went in just now and although they should be able to re-select now, why would the audience list be displaying differently for those two team goals?

**Comment by jessicahjwu** [comment]
Jessica will try and re-create the issue in Test/ Training

**Comment by jessicahjwu** [comment]
Couldn't re-create the same issue in Training. Checking with user if they can create a "test" goal in the team goal bank and if the issue continues, also verifying which browser they were using at the time of creating those two goals.

**Comment by jessicahjwu** [comment]
Reached out to the users, and their responses are as follows (March 5):
**Tracy:**
I am and previously was using Microsoft Edge as the browser when creating these goals. I believe PGT starting using Edge as our default browser for all applications around the summer of 2022, before the PDP platform was launched.

I also just tried to create a test goal and I had the same results as Shelly, it was created at the top of the Team Goal bank which pushed an existing goal to page 2 with the same glitch on audience, causing us to not be able to assign new or change existing audience members. This means it is still not working.

**Shelly:**
, I created a test goal just now which, as a result, was added to the top of the list and therefore pushed a third goal to page 2 with the same results.  I am using Microsoft Edge as suggested. It’s still not working. 

 <img width="782" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenpIQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d0241fbac1abb0a22887fa6d2e884ab992ab8368/image.png" alt="image.png" />

**Comment by jessicahjwu** [comment]
@jizhaogit I was able to replicate the issue once Team Goal Bank is expanded to the second page. It should be something in the application that has triggered that

<img width="1327" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkhuQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ef1b7e2a40d0757f6f1f0ecd9fd73a90b40099ee/image.png" alt="image.png" />

**Comment by steffipravasi** [comment]
@jizhaogit The limit of goals on one page is increased to 20. Can we please change it to 10 to be consistent?
<img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHdqQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cb5f217f3cbcc6f09f531cb4afa8eb0ad7a9879c/Screenshot%202024-03-31%20at%2010.30.25%E2%80%AFPM.png" alt="Screenshot 2024-03-31 at 10.30.25 PM.png" />

**Comment by jizhaogit** [comment]
Hi @steffipravasi  the page length is changed back to 10 rows now. thanks!

**Comment by steffipravasi** [comment]
Looks good
<img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHdsQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a9258effa427d7c807f3661092165704b8933606/Screenshot%202024-04-01%20at%2011.45.19%E2%80%AFAM.png" alt="Screenshot 2024-04-01 at 11.45.19 AM.png" />
<img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDBsQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1416a69e840ed2a087c88744857e8c9a5d1b0808/Screenshot%202024-04-01%20at%2011.45.35%E2%80%AFAM.png" alt="Screenshot 2024-04-01 at 11.45.35 AM.png" />
