### ISSUE TITLE
Create two additional video links in the Resources section, under "Video Tutorials" tab

### ISSUE THREAD

**Issue by jessicahjwu** [bcgov/performance#1241]
There are currently six video links in the "video tutorial" tab, please add two more (item 3 and 5):

1. Overview of PD
2. Setting a Goal in the PDP
3. **Effective Goals in the Performance Development Platform** (embed link: https://youtu.be/hv-MxU2_mKQ)
Goal setting in the PDP helps provide direction and vision for career growth and development. Watch this video to learn about why effective goals are important.
4. Performance Conversations in the PDP
5. **Having productive conversations in the Performance Development Platform** (embed link: https://youtu.be/EC6xgSpaNng)
Regular performance conversations support the relationship between supervisors and employees by building trust and providing the opportunity to collaborate on setting goals to determine what career growth and performance indicators look like. Watch this video to learn about why productive performance conversations are important.
6. Team Goals in the PDP
7. Setting Goals for Direct Reports in the PDP
8. My Team section of the PDP

**Comment by telusdcinco** [comment]
@jizhaogit Please review code change.

**Comment by telusdcinco** [comment]
MIGRATION NOTES:

Run 'php artisan migrate'.

**Comment by jizhaogit** [comment]
code good for me. thanks

**Comment by steffipravasi** [comment]
Functionality working as expected
<img width="1320" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmpQQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--625b3ad6ab8c67a026018e760997bcb3405fe44d/Screenshot%202024-03-11%20at%206.41.53%E2%80%AFPM.png" alt="Screenshot 2024-03-11 at 6.41.53 PM.png" />
