### ISSUE TITLE
Conversation modal must remain open when Saving changes through the Close button

### ISSUE THREAD

**Issue by steffipravasi** [bcgov/performance#1242]
Enhancement separated from ticket #1102
Issue: If user adds comments -> Clicks on close button -> Clicks on Save changes button -> The conversation modal closes completely and thus does not let user have the option to Send Notifications
Solution: 
1) Only leave the user on the modal itself when there are comments/updates added but not saved and user clicks on close button and Save changes button
2) If user clicks on Close again without clicking the Send notifications button then close the modal
3) If the user again makes updates, repeat step 1

**Comment by telusdcinco** [comment]
MIGRATION NOTES:

Code change only.

**Comment by telusdcinco** [comment]
@jizhaogit Please review code changes.

**Comment by jizhaogit** [comment]
@telusdcinco Thank you Dennis, code change looks good to me.

**Comment by steffipravasi** [comment]
Functionality working as expected
