### ISSUE TITLE
Auto-save feature does not work correctly for Edit goal

### ISSUE THREAD

**Issue by steffipravasi** [bcgov/performance#1244]
The auto-save functionality for edit goal does not save the edits made. 
Once the auto-save message pops-up, and user clicks Ok the changes made to the goal are removed and not saved instead of saving those changes.
Bug found from ticket #1194
[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTd1QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2c6986c8c6de3f37f4138732f0baa049d811c7d1/Screen%20Recording%202024-03-19%20at%201.15.07%E2%80%AFAM.mov)

<img width="954" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOS91QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--96db842c168adfb15f3e5207a41b93984f795c74/Screenshot%202024-03-19%20at%201.51.56%E2%80%AFAM.png" alt="Screenshot 2024-03-19 at 1.51.56 AM.png" />

**Comment by jizhaogit** [comment]
found a bug in the saving process.  changed the point from 1 to 2 for debugging

**Comment by steffipravasi** [comment]
@jizhaogit I am still getting the issue
Steps: 
- Go to edit goal
- Make some changes
- Click ok to the auto save confirmation modal
- Click on back button 
- The changes are not saved
https://bcgov.sharepoint.com/:v:/r/teams/02915/Shared%20Documents/Product%20Team/Tickets%20Requirements/1244/Screen%20Recording%202024-04-03%20at%201.48.54%E2%80%AFPM.mov?csf=1&web=1&e=tlxC9Q

**Comment by jizhaogit** [comment]
Thanks Steffi, issues should be addressed.

**Comment by steffipravasi** [comment]
Functionality working as expected
