### ISSUE TITLE
Fix empty section showing at the bottom of the Access & Permissions page

### ISSUE THREAD

**Issue by telusdcinco** [bcgov/performance#1245]
Fix empty section showing at the bottom of the Access & Permissions page.

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXp4QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7a0cfb08d53ab0219ffc4f82d9b3a3384fdfb6dd/image.png" alt="image.png" />

**Comment by telusdcinco** [comment]
MIGRATION NOTES:

Just code change.

**Comment by telusdcinco** [comment]
@jizhaogit Please review code change.

**Comment by jizhaogit** [comment]
Thank you @telusdcinco, code looks good to me.

**Comment by steffipravasi** [comment]
Looks good
<img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMi8wQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--47f20d5b99908f87b5ed3aad75b9ae551f0dd0b6/Screenshot%202024-03-19%20at%2010.49.45%E2%80%AFPM.png" alt="Screenshot 2024-03-19 at 10.49.45 PM.png" />
