### ISSUE TITLE
Add "Last Modified Date" and "Last Modified By" columns in the Goal bank table

### ISSUE THREAD

**Issue by jessicahjwu** [bcgov/performance#1251]
Currently in the Goal Bank table under "Manage Goals in Goal Bank" tab doesn't capture the last updated date/ last modified date, it's difficult for Ministry contacts to know when and by whom made the edits. Is it possible to add two columns to the table between columns "Created By Organization" and "Individual Audience":
1. Last Modified Date
2. Last Modified By

<img width="1380" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOEgvQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f195bb11cb3fd596cd5c454c1ae5c084af117914/image.png" alt="image.png" />

The full table columns, from left to right order:
Goal Title - Goal Type - Mandatory - Goal Creation Date - Display Name - Created By - Created By Organization - Last Modified Date - Last Modified By - Individual Audience - Business Unit Audience - Action

**Please ensure each cell is read correctly through screen reader, labels should provide users with specific name of the item in the cell**

**Comment by jizhaogit** [comment]
we have captured updated_at in goals but don't have updated_by info.   after talked with Dennis, we found we can use audits info to collect the latest updated by info.  i modified the ticket's score to 2 based this requirement.

**Comment by steffipravasi** [comment]
@jizhaogit I've got a question. Why are some of the cells in the Last Modified By column?
I see that if the goal is not modified yet, then the last modified columns will display the goal created date and by details. Just wondering why are these cells empty?
<img width="1656" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGdaQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2605cd121b351feecf32ee60dd10d6e047e4fa04/Screenshot%202024-03-28%20at%201.36.28%E2%80%AFAM.png" alt="Screenshot 2024-03-28 at 1.36.28 AM.png" />

**Comment by jizhaogit** [comment]
@telusdcinco Hi Dennis, would you please help advise if we have audits log for the audience changing process? thank you!

**Comment by jizhaogit** [comment]
As discussed in the meeting. Issue 2 will not be done in this ticket.

**Comment by steffipravasi** [comment]
Issue fixed and working as expected now
<img width="1889" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1lkQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e3061af3bb357c278ee0b8321186aa0ac1b4c9cd/Screenshot%202024-03-28%20at%201.33.10%E2%80%AFPM.png" alt="Screenshot 2024-03-28 at 1.33.10 PM.png" />

**Comment by jessicahjwu** [comment]
Please make sure the name displayed in the "Last Modified By" column follows the demographic data "last name,first name"

**Comment by telusdcinco** [comment]
MIGRATION NOTES:

Just code changes.

**Comment by steffipravasi** [comment]
Test approved for all the following changes:
- Performance issue (takes 2-3 seconds to load now)
- Individual column sorting (columns can be sorted now)
- Make the displayed names follow consistent format, as provided in the employee demographics (Some fields are left empty because the employee is Sys admin which is the username and the column displays the demographic data)
- Apply fixes in both Sys and HR Admin Goal Bank pages.
<img width="380" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFZOQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--77afeb0cc4618cd7b1606c3a44d6a94379358b2b/Screenshot%202024-04-10%20at%2012.42.33%E2%80%AFPM.png" alt="Screenshot 2024-04-10 at 12.42.33 PM.png" />
