### ISSUE TITLE
Signed-off conversation disappeared in Supervisor's profile, whilst it's still visible in employee's "completed conversation"

### ISSUE THREAD

**Issue by jessicahjwu** [bcgov/performance#1253]
Scenario: Supervisor Tina Robinson (107897) and her direct report Cherry Chen (198799) had a performance check-in conversation signed off on Mar 19. Whilst this conversation is still visible in Cherry's profile under "completed conversations", it has disappeared from Tina's PDP. Checked the reporting relationships in PDP for Tina, and Cherry is still listed as her direct report. Also checked in Audit log, there has not been any further actions taken for conversation ID 52417 after it has been signed off by both parties.

I was able to re-create the same issue in training. Please check if the system is not detecting the reporting relationships correctly in the backend which has caused Tina not being able to view the signed off conversation.

In Training:
1. I created the conversation using Tina's identity (via Switch Identity) with Cherry Chen on Mar 22, updated the content, signed-off using both Tina and Cherry's identity:

<img width="1489" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTBJQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ea1189bf4c9e424dfdab41d8870b618b1c688107/image.png" alt="image.png" />
 
2. Conversation appears in Cherry's profile but not Tina's either when I selected Cherry as the search criteria or without any search items:
<img width="1590" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMklJQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2f68a9cc85c7abab87d4ecd1a93e10495d88aa90/image.png" alt="image.png" />
<img width="1543" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmNJQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d0aa98f85aaf3a9a1e6f62645bb5fa9474767ba3/image.png" alt="image.png" />

**Comment by telusdcinco** [comment]
@jessicahjwu 

The issue cannot be replicated in my local, Dev and Test.  Only occurring in Training and Prod.  The issue relates to employee sharing.

The completed conversations do not display on Supervisor's "Completed Conversations with my Team" list when the another employee is shared with the supervisor.  Currently, the supervisor (Tina) has been shared with someone, probably a delegate for another manager.

The intention may have been to only include direct report's closed conversations on the list.  Please confirm this.  

The filter to exclude shared direct report's closed conversations is causing the issue, and may need to be fixed.

**Comment by telusdcinco** [comment]
MIGRATION NOTES:

Just code change.

**Comment by telusdcinco** [comment]
@zhongjixiehou Please review code change.

**Comment by jizhaogit** [comment]
code change looks good to me. thanks Dennis.
