### ISSUE TITLE
Created By column in Manage Goals in Goal Bank remains empty

### ISSUE THREAD

**Issue by steffipravasi** [bcgov/performance#1257]
Bug found when testing ticket: #1251
The column 'Created By' does not have data for any of the goals regardless of who created it. Looks like there is a bud in displaying the information on the front-end
Issue observed for Sys admin only. HR looks good

Sys admin: 
<img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHdaQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--544c06f433907085d1d721808f27262569288af7/Screenshot%202024-03-28%20at%201.55.36%E2%80%AFAM.png" alt="Screenshot 2024-03-28 at 1.55.36 AM.png" />

HR admin:
<img width="1288" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODBaQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--75d6bce6ad642135830751c1d027415bf9e4acc3/Screenshot%202024-03-28%20at%201.58.21%E2%80%AFAM.png" alt="Screenshot 2024-03-28 at 1.58.21 AM.png" />

**Comment by jessicahjwu** [comment]
In PROD, the "created by" column is working properly:
<img width="1633" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBell5QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ad32b0073403134285b6534992c421881373420d/image.png" alt="image.png" />

Can we make sure there's no difference in coding between Test and Prod before pushing out#1251?

**Comment by telusdcinco** [comment]
MIGRATION NOTES:

Just code changes.

**Comment by telusdcinco** [comment]
Issues due to #1251 changes.
 - Created By column values fixed.
 - Fixed all the column sorting.
 
<img width="640" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdzQwQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d748b2bd215ffc8e9ab08b3529c1a16dc8a6fe9f/image.png" alt="image.png" />

**Comment by telusdcinco** [comment]
@jizhaogit Please review code changes.

**Comment by jizhaogit** [comment]
@telusdcinco thank you Dennis.  code change looks good to me.

**Comment by steffipravasi** [comment]
@telusdcinco There are still some fields in the Created By column which are empty
<img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0UzQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6acf6f7341e61615fd05e31030fc0d81c67e6de6/Screenshot%202024-04-04%20at%203.23.44%E2%80%AFPM.png" alt="Screenshot 2024-04-04 at 3.23.44 PM.png" />
Also, not sure what caused this but the width of the Goal title column is occupying most of the page
<img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1kzQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bf5307435bad009c341fb76705513d945f2c6003/Screenshot%202024-04-04%20at%203.28.33%E2%80%AFPM.png" alt="Screenshot 2024-04-04 at 3.28.33 PM.png" />
The column sorting issue is still not fixed

**Comment by steffipravasi** [comment]
@jessicahjwu We have a confusion here
The created by column uses the demographic data that displays Lastname, Firstname whereas the modified by column displays the user name Firstname Lastname. 
Do we want to standardize how the name appears? Mostly all places in the tables use the demographic data i.e LastName, FirstName
<img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlU0QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--86dc7f56c5f7017acf9c5493564a4229bfe056a9/Screenshot%202024-04-04%20at%2011.37.45%E2%80%AFPM.png" alt="Screenshot 2024-04-04 at 11.37.45 PM.png" />

**Comment by jessicahjwu** [comment]
Thanks for catching this @steffipravasi ! Can we standardize all columns using the demographic data? I foresee we will need another ticket for this.

**Comment by steffipravasi** [comment]
Issue has been fixed
<img width="380" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3BPQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c917e35e8fe81354f5806aa5e050417d47e53437/Screenshot%202024-04-10%20at%2012.42.33%E2%80%AFPM.png" alt="Screenshot 2024-04-10 at 12.42.33 PM.png" />
