### ISSUE TITLE
Names with apostrophes do not show up in search results in "My Org" or "Employee List" 

### ISSUE THREAD

**Issue by jessicahjwu** [bcgov/performance#1264]
**Scenario: HR Administrator was searching for an employee name "Becki O'Rae", and got error message:**

<img width="1172" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGxoQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--64b7501f41f383c248a642057da19894d2694b21/image.png" alt="image.png" />

**She tried without the apostrophe, however the result did not return with Becki's name:**

<img width="1370" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGhoQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--132f2f03a8cbc612309d97bbebd56f66c8af71e9/image.png" alt="image.png" />

Then she tried with Becki, the result returned as expected and the last name was displayed with apostrophe:

<img width="1209" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODFoQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f1a8bc543f74ac9af837db8bb0f938062bdb4a8a/image.png" alt="image.png" />

Does the search text field not recognize symbols? How should we look for last name with apostrophes?

**Updated Apr 17, 2024 - Please modify changes in the whole application where free text search is available:**
### HR Admin:
- [x] My Organization
- [x] Share Employees: 
       Create New Share
       View or Delete Existing Shares
- [x] Excuse Employees
       Managed Excused Status
       View Excused History
- [x] Goal Bank
       Add a New Goal to the Goal Bank (Step 2: Select audience: Individuals)
       Manage Goals in Goal Bank
### Sys Admin:
- [x] Employee List
- [x] Share Employees: 
       Create New Share
       View or Delete Existing Shares
- [x] Excuse Employees
       Managed Excused Status
       View Excused History
- [x] Goal Bank
       Add a New Goal to the Goal Bank (Step 2: Select audience: Individuals)
       Manage Goals in Goal Bank
- [x] Supervisor Overrides
      Create New Supervisor Override
      View or Delete Existing Supervisor Override
- [x] Unlock Conversations
       Unlock New Conversation
       Manage Existing Unlocked Conversations
- [x] Notifications
       View Past Notification
       Create New Notification
- [x] Access and Permissions
       Create New Access
       Manage Existing Access
- [x] Switch Identity
- [x] System Security
       Access Log
- [x] Auditing
### Service Representative
- [x] Employee List
- [x] Switch Identity

**Comment by telusdcinco** [comment]
As discussed with PO, this fix will be expanded to all text searches within Sys/HR Admin pages.  Updated the estimate additional time required.

**Comment by telusdcinco** [comment]
MIGRATION NOTES:

Just code changes.

**Comment by telusdcinco** [comment]
@jizhaogit Please review code changes.

**Comment by steffipravasi** [comment]
@telusdcinco 
The "'" filters on the following pages do not work:
- View Past Notification
- Create New Notification
<img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3lBQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ca865dc8bedabb0151faa57e6a3a0b6b79e1d538/Screenshot%202024-04-22%20at%2012.58.48%E2%80%AFPM.png" alt="Screenshot 2024-04-22 at 12.58.48 PM.png" />

**Comment by telusdcinco** [comment]
@steffipravasi Forgot to mention that Notification filter is actually not working and just keeps of reloading default list.  The search fix is implemented on the page, but the loading issue should be a separate ticket.

**Comment by steffipravasi** [comment]
New ticket added for the Notifications page.
Issue fixed for other pages for HR and Sys admin.
