### ISSUE TITLE
HR/Sys admin - Cancel button still processes the employee share

### ISSUE THREAD

**Issue by steffipravasi** [bcgov/performance#1265]
Issue on the page HR/Sys admin -> Share employees -> Create new shares
Steps to reproduce:
- Select employee in Step 1
- Select employee in Step 2
- Enter reason for step 3
- Click on Cancel button
- Notice that the employee is still shared

Expected result: On the click of the Cancel button, the share process must not go through and the fields must clear out.

**Comment by jessicahjwu** [comment]
@steffipravasi please check if the cancel button is working as expected through the Supervisor sharing path. If not, please create another ticket to fix that one.

**Comment by telusdcinco** [comment]
May be similar to #1246.

**Comment by steffipravasi** [comment]
Cancel button working as expected for the supervisor sharing.

**Comment by telusdcinco** [comment]
@steffipravasi @jessicahjwu 
Fixed in my local.  
Found similar issue in Sys/HR Admin Add New Goal.  Please confirm other pages too.
Should other similar issue be added to this ticket.

**Comment by telusdcinco** [comment]
@steffipravasi @jessicahjwu 

Please replicate ticket for similar issue found in the following pages:
- Sys/HR Admin Add New Goal
- Sys/HR Managed Excused Status

**Comment by telusdcinco** [comment]
MIGRATION NOTES:

Just code change only.

**Comment by telusdcinco** [comment]
@jizhaogit Please review code change.

**Comment by steffipravasi** [comment]
@telusdcinco tickets 1271, 1272 added

**Comment by jizhaogit** [comment]
code change looks good to me. thanks!

**Comment by steffipravasi** [comment]
Functionality working as expected
