### ISSUE TITLE
Sys/HR Admin Add New Goal - Cancel button still processes the function

### ISSUE THREAD

**Issue by steffipravasi** [bcgov/performance#1271]
Issue on the page HR/Sys admin -> Goal Bank -> Add new goal
 HR/Sys admin -> Goal Bank -> Manage Goal in goal bank -> Individual audience page
 HR/Sys admin -> Goal Bank -> Manage Goal in goal bank -> business unit audience page
Ticket similar to #1265
Steps to reproduce:

Fill out all the details on the page
Click on Cancel button
Notice that the employee is still shared
Expected result: On the click of the Cancel button, the process must not go through and the fields must clear out.

**Comment by steffipravasi** [comment]
@telusdcinco updating the ticket as a fix will also be needed for the audience page/s in Manage goals

**Comment by telusdcinco** [comment]
@jizhaogit Please review code changes.

**Comment by jizhaogit** [comment]
code change looks good to me. thanks!

**Comment by steffipravasi** [comment]
Issue fixed and functionality working as expected:
HR/Sys admin -> Goal Bank -> Add new goal
HR/Sys admin -> Goal Bank -> Manage Goal in goal bank -> Individual audience page
HR/Sys admin -> Goal Bank -> Manage Goal in goal bank -> business unit audience page
