### ISSUE TITLE
Sys/HR Admin Excuse employees - Cancel button still processes the function

### ISSUE THREAD

**Issue by steffipravasi** [bcgov/performance#1272]
Ticket similar to #1265
Issue on the page HR/Sys admin -> Excuse employees
Steps to reproduce:

Fill out all the fields on the page
Click on Cancel button
Notice that the employee is still shared
Expected result: On the click of the Cancel button, the share process must not go through and the fields must clear out.

**Comment by telusdcinco** [comment]
MIGRATION NOTES:

Just code change only.

**Comment by telusdcinco** [comment]
@jizhaogit Please review code change.

**Comment by jizhaogit** [comment]
code change looks good to me. thanks!

**Comment by steffipravasi** [comment]
Manage Excused Status page - Functionality working as expected
