### ISSUE TITLE
Sys Admin Supervisor Override - Cancel button still processes the function

### ISSUE THREAD

**Issue by steffipravasi** [bcgov/performance#1273]
Ticket similar to #1265
Issue on the page Sys admin -> Supervisor Override
Steps to reproduce:

Fill out all the fields on the page
Click on Cancel button
Notice that the employee is still shared
Expected result: On the click of the Cancel button, the share process must not go through and the fields must clear out.

**Comment by telusdcinco** [comment]
MIGRATION NOTES:

Code change only.

**Comment by telusdcinco** [comment]
@jizhaogit Please review code change.

**Comment by jizhaogit** [comment]
Thank you Dennis, looks good to me.

**Comment by steffipravasi** [comment]
Issue fixed and functionality working as expected

**Comment by jessicahjwu** [comment]
Noticed that when supervisor override happened in Training, the user's dashboard did not get updated with the new supervisor's name even though the supervisor override history in Sys Admin reflected the change. Will wait till update is in Training to see if there's any different, and if issue persists, will create another ticket.

**Comment by jessicahjwu** [comment]
Noticed that when supervisor override happened in Training, the user's dashboard did not get updated with the new supervisor's name even though the supervisor override history in Sys Admin reflected the change. Will wait till update is in Training to see if there's any different, and if issue persists, will create another ticket.

**Comment by telusdcinco** [comment]
The supervisor updates will propagate overnight, after the nightly processes have completed.
