### ISSUE TITLE
Sys Admin Create Notifications - Cancel button still processes the function

### ISSUE THREAD

**Issue by steffipravasi** [bcgov/performance#1275]
Ticket similar to #1265
Issue on the page Sys admin -> Create Notifications
Steps to reproduce:

Fill out all the fields on the page
Click on Cancel button
Notice that the employee is still shared
Expected result: On the click of the Cancel button, the share process must not go through and the fields must clear out.

**Comment by telusdcinco** [comment]
MIGRATION NOTES:

Code change only.

**Comment by telusdcinco** [comment]
@jizhaogit Please review code change.

**Comment by steffipravasi** [comment]
Issue fixed and functionality working as expected
