### ISSUE TITLE
Provide log-in's for the Able Tech team

### ISSUE THREAD

**Issue by jessicahjwu** [bcgov/performance#1277]
We will have the contractor to help with accessibility requirements review and end-using testing, based on tickets that Steffi has created and Ji/ Dennis' work on development. 

We will need to provide the below:

- [ ] Zenhub access - @Abuchana are we able to provide additional access?
- [ ] PDP Testing (Users might not have government IDIR)
- [ ] PDP Training (Users might not have government IDIR)

**Comment by telusdcinco** [comment]
@jessicahjwu 

The below functional accounts will be setup, and can be shared by Able Tech.  Passwords will be sent separately
1. sysadmin3 - for Sys Admin access
2. hradmin3 - for HR Admin access assigned to Royal Museum
3. service3 - for Service Representative access
4. manager3 - for Supervisor access
5. employee3 - for Employee access

Similar accounts will be created in Test? or in Training? or both?

**Comment by telusdcinco** [comment]
MIGRATION NOTES:

DO NOT MIGRATE TO PROD.  Only intended for Test and/or Training setup.

Run in Test and/or Training only:
php artisan db:seed --class=DataFix_1277_Create_Evaluator_Functional_Accounts

**Comment by telusdcinco** [comment]
@jizhaogit  Please review seeder script.  (NOT for migration to Prod, deploy only in Test and/or Training).

**Comment by jizhaogit** [comment]
Thank you very much Dennis! looks good to me!

**Comment by telusdcinco** [comment]
@jessicahjwu   IDs for Able Tech created in Test.  Please confirm if IDs are required in Training as well.  Password will be sent to your mailbox.

**Comment by jessicahjwu** [comment]
All login's are working properly, employee3 and manager3 have reporting relationships. Credentials were created only for accessing Test.
