### ISSUE TITLE
HR/ Sys Admin Function: Last Modified Date and Last Modified By columns in Goal Bank did not reflect the accurate HR Administrator details

### ISSUE THREAD

**Issue by jessicahjwu** [bcgov/performance#1279]
HR/ Sys Admin Function: The "Last Modified Date" and "Last Modified By" columns in the goal bank are not pulling from the accurate data which reflects the HR Administrator information, business requirement is to have those two columns show the details of the when and who the HR Administrator made changes. Related to #1251.

**Comment by telusdcinco** [comment]
@jessicahjwu Please attach/add specific details when incorrect details was being displayed on the Last Modified Date/By in PDP Prod.

**Comment by telusdcinco** [comment]
Goal comment audit is being used for goal changes also.  Updated to only limit looking at actual Goals.

**Comment by telusdcinco** [comment]
@jizhaogit Please review code changes.

**Comment by jizhaogit** [comment]
Thank you @telusdcinco changes look good to me.

**Comment by jessicahjwu** [comment]
Jane McKinnon is not one of the HR Administrators from SDPR, however, the last modified by and date appeared to be under her name:
<img width="682" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUw4QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e45e416ee307ec1f89076e2687c1ba8de6662095/image.png" alt="image.png" />

Heather Thorturn is not one of the HR Administrators, but seemed to have duplicated the goal:
<img width="808" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVA4QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--eae65c93d883fcee600223e03392369f8ff63a1e/image.png" alt="image.png" />

**Comment by telusdcinco** [comment]
MIGRATION NOTES:

Code change only.

**Comment by steffipravasi** [comment]
Test data:
HR admin1: has access to Justice
000318	Harlow,J. Robert	Bob.Harlow@gov.bc.ca
HR admin2: has access to Justice & SDPR
001247	Lewke,Sandra	Sandy.Lewke@gov.bc.ca
HR admin3: has access to Justice & Citizen Services
002737	Halpert,Mary R	Social Program Officer R24	Mary.Halpert@gov.bc.ca

Scenario1: Robert added a new goal - CareerGoalMay23 for the Justice org
Last modified date & Last modified by column displays correct details : Yes
Hr admin Mary added 10 individual audience from Citizen services to the goal
Last modified date & Last modified by column displays correct details : No
Last modified column still displays the record of Harlow,J. Robert

**Comment by telusdcinco** [comment]
@jessicahjwu @steffipravasi 
Currently, the Last Modified Date & Last Modified By columns depends on Audit entries generated when the actual Goal record is updated.  Adding individual or organization audience does not trigger the generation of a Goal Bank audit entry, as these details are stored on a different table.
It is possible to force the creation of an audit entry whenever an audience is added/removed from a Goal Bank.  The audit should be then be picked up by the Last Modified Date/By column.  This change will require a separate ticket.

**Comment by steffipravasi** [comment]
For testing purpose:
Test data:
HR admin1: has access to Justice
000318	Harlow,J. Robert	Bob.Harlow@gov.bc.ca
HR admin2: has access to Justice & SDPR
001247	Lewke,Sandra	Sandy.Lewke@gov.bc.ca
HR admin3: has access to Justice & Citizen Services
002737	Halpert,Mary R	Social Program Officer R24	Mary.Halpert@gov.bc.ca

Non- HR admin from Justice org: 
000297	Schultz,Michael	Michael.Schultz@gov.bc.ca
135215	Froehlich,Sherry	Sherry.Froehlich@gov.bc.ca
From SDPR: 
001247	Lewke,Sandra

Scenario1: Robert added a new goal - CareerGoalMay23 for the Justice org
Last modified date & Last modified by column displays correct details : Yes
Hr admin Mary added 10 individual audience from Citizen services to the goal
Last modified date & Last modified by column displays correct details : No
Last modified column still displays the record of Harlow,J. Robert

Scenario2: Michael adds the goal to his current goals from goal bank
Last modified date & Last modified by column displays Robert’s details : yes

Scenario 3: Michael editing the goal from his current goals page
Last modified date & Last modified by column displays Robert’s details : yes

Scenario 4: Sherry adds the goal to goal bank and shares the goal with Sandra 
Sandra and Sherry adds comments to the goal
Last modified date & Last modified by column displays Robert’s details : yes

Scenario 5: Sandra tries to access the link https://performance-332842-test.apps.silver.devops.gov.bc.ca/hradmin/goalbank/editdetails/1369
Expected is Sandra will not be able to access the goal: 
Last modified date & Last modified by column displays Robert’s details : yes
