### ISSUE TITLE
As an employee I want to see definitions for each of the goal fields

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#128]
- [ ] Add italic text with definitions as default in goal fields (see comments for specific wording)

- [ ] Add a question mark icon by the "Goal Type" heading for mouse over (see comments for wording)

**Comment by Travis-A-Clark** [comment]
Type of goal: #Choose from drop down

Goal: #Descriptive title of goal

What: #Concise opening statement (what will be achieved)

Why: #Define why this goal is important to you and the organization (value of achievement)

How: #Plan or steps to be taken to achieve the goal

Measures of success: #Qualitative and quantitative measures of success

Target date: #Anticipated date of goal completion

**Comment by Kousthubha-M** [comment]
- Adding bootstrap tooltip for the goal type description
- Adding place holders for definitions of goal fields

**Comment by Travis-A-Clark** [comment]
@phoebesolomon This is the user story that deals with the default text for the add new goal function. I just expanded based on our scrum this morning. Any thoughts or comments? I am a bit worries that there is too much text in the "Goal Type" mouse over but if it's presented properly hoping it should be okay. Thanks!

**Comment by phoebesolomon** [comment]
@Travis-A-Clark I think I need to mock it up in the wireframes first and then we can decide? I think it will be easier to visualize that way

**Comment by Travis-A-Clark** [comment]
@phoebesolomon Works for me. I've asked KK to move on to tickets #30 and #50 while we finalize this one. Thanks!
