### ISSUE TITLE
Update SSL Certificate

### ISSUE THREAD

**Issue by warrenchristian1telus** [bcgov/performance#1281]
I have just received the updated SSL certificate. We will need to implement before the expiry on May 17.

@telusdcinco Can you please let me know when will be a good time to implement? Not sure if we can avoid OT here. We can discuss with Shane if we'll need that. The update itself should only take a minute. I wouldn't expect any issues or outage, but there is always some risk.

Lowest traffic times are over lunch and of course outside business hours. I would suggest trying for implementation at noon. This would give us roughly an hour to deal with any issues, while not many people are using it.

**Comment by telusdcinco** [comment]
@jessicahjwu @jizhaogit
FYI on activities.

@warrenchristian1telus 
Which environments will affected?

**Comment by warrenchristian1telus** [comment]
The SSL certificate only applies to the production URL.

**Comment by telusdcinco** [comment]
@warrenchristian1telus 
As discussed with PO, you may implement this week after office hours.  Please let us know if Friday around 5pm is okay?

**Comment by warrenchristian1telus** [comment]
SSL Certificate has been updated for 2024.

![image](https://github.com/bcgov/performance/assets/70002196/ed95c239-47df-4286-9924-d2a9a3e5605a)
