### ISSUE TITLE
PDP Prod Issue:  Daily Process to Sync GUID is Failing

### ISSUE THREAD

**Issue by telusdcinco** [bcgov/performance#1289]
The daily overnight run to sync up new GUID coming from ODS to the local PDP profile has failed since May 16, 2024.

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTc3QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--be44f074419e31a26d1b07cf2274d5ba3df20183/image.png" alt="image.png" />

**Comment by telusdcinco** [comment]
@jessicahjwu Please confirm if this scenario requires a data fix on PS side as well.  Job 0 is active but lacks GUID, email, supervisor info (probably because it shows as a POI).  Job 1 should be the one used in PDP profile.

Fix:  Will apply code change to make sure process uses employee demo row with valid GUID. 

<img width="1139" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNno4QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--385999ac0b27e60e2b28f3e40cc88d0dce0e2cec/image.png" alt="image.png" />

**Comment by telusdcinco** [comment]
@jessicahjwu Root cause may be related to EE 193773.  The employee may have recently been excluded (Dept ID 105-1200).  Added fix to prevent process from updating GUID of excluded users.

**Comment by telusdcinco** [comment]
@jizhaogit Please review code changes.

**Comment by telusdcinco** [comment]
MIGRATION NOTES:

Code change only.

**Comment by jizhaogit** [comment]
@telusdcinco looks good to me. thanks!

**Comment by telusdcinco** [comment]
@steffipravasi 
Pulled back to In Progress to address bug fix.  The initial fix does not cover multi-job scenario.

**Comment by telusdcinco** [comment]
Process now runs successfully in Prod.

<img width="787" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWhIQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--aa2d6214441775120fd4882cd5595c1074a8dfd7/image.png" alt="image.png" />
