### ISSUE TITLE
PDP Prod Issue:  Daily Notification for Conversation Due Dates is Failing Intermittently

### ISSUE THREAD

**Issue by telusdcinco** [bcgov/performance#1290]
The overnight process to send notification (7 and/or 30 days) for next conversation due dates have been failing a few times as shown below.

<img width="1613" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMm43QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--aa2d1f1cecc48fa15ac1feae2a8ce4f9f9803557/image.png" alt="image.png" />

**Comment by telusdcinco** [comment]
Partial error message in Prod:
<img width="1157" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHd2QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ee73ade445d08620a154c64da5fcdd99e6fcdbb5/image.png" alt="image.png" />

Full error message in Test:
<img width="1383" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeW92QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--54cf4bf9d79e511198ff780582c051cc25446615/image.png" alt="image.png" />

**Comment by telusdcinco** [comment]
The application may be reaching a limitation in terms of email count being sent for the Conversation Due Data Reminders.  

Issue is currently persistent in Test, failing almost everyday (except Wednesdays).

Will require to re-confirm email sending limitations from Exchange team.
1.  What is the current email transaction count limitation?
2.  Is there a time limitation on the email sending session for each transaction?

**Comment by telusdcinco** [comment]
Had discussion with Chris from CITZ team regarding email limitations, and if there were changes down since PDP went Live.

The following items came up and may require further investigation.
1. Rule out issue with smtp load balancer as a cause for the intermittent disconnection.  Chris will provide the 4 IP addresses for the smtp servers used in round robin by the load balancer.  This is to see if 1 of the smtp servers have an issue.
2. CHES? is an API based email sending tool available in OpenShift.  It another layer on top of the existing smtp server, that should manage email queueing.
3. Check if email triggered is surpassing limitation of 3600/hour for each sender email.  Might be a good idea to have a separate email sender for non-prod.  


For the meantime, the recommendations below should be able to help ease the congestion.
1. Turn off email sending in non-prod.
2. Create a separate email for non-prod.


Potential solutions
1. Convert direct email in the notification process to use queue.
2. Look at queue configuration if additional settings to only send email within limitations.

**Comment by telusdcinco** [comment]
Error message in Prod, 20204-06-07:

<img width="1376" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXBIQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e75a9ab7dc4d600abe193297c678a5f7366f79a4/image.png" alt="image.png" />

**Comment by telusdcinco** [comment]
Overnight process NotifyConversationDue was designed to use queue.  The queue was turned off in #803 due to issue with cron pod accessing the log files.

Just need to flip the switch to use queue instead of direct email.  Validation is required to confirm if the access issue was fixed after #803.

**Comment by telusdcinco** [comment]
@jizhaogit Please review code changes.

**Comment by telusdcinco** [comment]
MIGRATION NOTES:

Code change only.

**Comment by telusdcinco** [comment]
Nothing front to test.  The process ca\n be viewed from Schedule Job Audit
 page.  Manual run completed successfully.  Will review weekend runs on Monday to see if any issue with code change.

**Comment by jizhaogit** [comment]
@telusdcinco thank you Dennis, changes look good to me.

**Comment by telusdcinco** [comment]
<img width="884" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMEZUQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0eb7a350d7e8633b11ed4c2f4c8b8d60a8b765dc/image.png" alt="image.png" />

**Comment by telusdcinco** [comment]
<img width="859" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVphQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--15cba7cbc7d86362d37091a0f692068ee04eb382/image.png" alt="image.png" />
