### ISSUE TITLE
PDP Prod:  Missed Termination Updates from ODS

### ISSUE THREAD

**Issue by telusdcinco** [bcgov/performance#1297]

**Comment by telusdcinco** [comment]
Link below for list of PDP employee records not found in weekend full download.  Usually means the records are terminated and no longer exist in ODS.

https://bcgov-my.sharepoint.com/:x:/r/personal/dennis_cinco_gov_bc_ca/Documents/ZH%231297%20-%20Possible%20Missed%20Terminations.xlsx?d=wf21e9e0a080b41149205912fc379c216&csf=1&web=1&e=oGKpDM

**Comment by jessicahjwu** [comment]
Jessica to confirm on the list of employees if they have been terminated.

**Comment by telusdcinco** [comment]
@jessicahjwu I've reattached the file.  Please let me know if the link below works.

https://bcgov.sharepoint.com/:x:/r/teams/02915/Shared%20Documents/Product%20Team/ZH%231297%20-%20Possible%20Missed%20Terminations.xlsx?d=wab1fdeb772be40339c41d8da921065ee&csf=1&web=1&e=W1npQW

**Comment by telusdcinco** [comment]
For the list provided in the attached spreadsheet...  

When the employee moves to a different job, ODS does not provide the closure for the previous job and just provides the info on the new job.

**Comment by telusdcinco** [comment]
MIGRATION NOTES:

- Code changes
- Migration required (Run 'php artisan migrate')

**Comment by telusdcinco** [comment]
Turned on the audit for employee_demo table.
- Updates to EmployeeDemo model will create entries in audits table (System Administration > Auditing)
- Auditing page currently only displays changes done by existing users.  Updates done by processes are not displayed but can be viewed with developer assistance.

When running GetODSEmployeeDemographics process (full download)
- A check will be performed for missing employee demo records from ODS.  The date_deleted will be assigned current date/time to indicate that the employee job entry is terminated

**Comment by steffipravasi** [comment]
Test data
| 027950      |           0 | Wahl,Diane M            | Diane.Wahl@gov.bc.ca              | 2023-09-26 09:12:31 | NULL         |
 
| 164312      |           0 | Heatherington,Mackenzie | Mackenzie.Heatherington@gov.bc.ca | 2023-07-13 09:11:03 | NULL         |
 
| 177102      |           0 | Nadan,Devisha           | Devisha.Nadan@gov.bc.ca           | 2024-06-01 09:10:00 | NULL         |
 
| 200364      |           0 | Shen,Norine             | Norine.Shen@gov.bc.ca             | 2024-03-21 09:12:21 | NULL         |
 
| 189786      |           0 | Brinoni,Meghann         | Meghann.Brinoni@gov.bc.ca         | 2023-11-18 09:09:05 | NULL         |
<img width="391" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelRUQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--abf02fa4551673676d30e970632f50c4ae5a2c8c/image%20%288%29.png" alt="image (8).png" />
<img width="424" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelhUQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a10e70d12f1df0af17513e8aaf521ca53b95ecd5/image%20%287%29.png" alt="image (7).png" />

**Comment by telusdcinco** [comment]
Deployed to Production

**Comment by telusdcinco** [comment]
Sample audits generated during 2024-07-14 full ODS data pull in Prod.

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTNkQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--308825f7f9ad3298b2bc6565aa2fbd8623e3b4e7/image.png" alt="image.png" />

1. an employment status change
2. effective date change
3. name change
4. supervisor change

**Comment by telusdcinco** [comment]
Possible bug caused by this change.

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDNsQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cd5e9b37da7de395a3fbd1eef21058e7293d0437/image.png" alt="image.png" />

**Comment by telusdcinco** [comment]
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeW5sQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d888cebb452e1e6a0652f65e84e0f20297aa162e/image.png" alt="image.png" />

**Comment by telusdcinco** [comment]
@jessicahjwu
All #1297 changes have been reverted from Dev/Test/Training/Prod.
This ticket can be closed.
