### ISSUE TITLE
PDP Prod Issue:  ExportDatabaseToBI Process Failed With Memory Allocation Error Message

### ISSUE THREAD

**Issue by telusdcinco** [bcgov/performance#1298]
ExportDatabaseToBI process failed with memory allocation error message.

This is the new error message after applying fix #1288.

<img width="1741" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWhJQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--df557c2fb7d93e376fffcf2e651eb27d74fbb369/image.png" alt="image.png" />

**Comment by warrenchristian1telus** [comment]
Hi @telusdcinco - can you provide more details on this issue? Where would this run - in the application pod(s) or the scheduler? Can we reproduce in another environment? Can you point me to the appropriate error log?

From what I can see, all the pods have ample memory and never appear to reach the limit. However there may be a difference between memory being available and being allocated (such as with app memory configuration settings in PHP/Laravel, etc.).

Can we setup a test case to work on to address the issue, in dev or test?

**Comment by telusdcinco** [comment]
The process output file is located at var/www/html/storage/logs/ExportDatabaseToBI.log.

The scheduled job runs in a cron pod.  Running the process manually can be done through the app pod.

The original issue does not happen in non-prod (Test).  Assuming there is not much delta change in Test, that there is not much to send out to ODS bound for BI.

We can trick the process in Test to send everything by resetting the last pull date to an earlier date.

**Comment by warrenchristian1telus** [comment]
@telusdcinco Can we setup test to mimic this situation? How can I reset the last pull date to replicate and (re)test?

Do you know if we get the same error/issue when running from the app pod rather then cron? I don't think there is a way to access the historical logs/files from finished cron jobs. It only keeps the last 3, and  they all just say "INFO  No scheduled commands are ready to run.".

I think if we can replicate this on the test app pod, that would help to capture any logged events, and not have them disappear on us. And if it succeeds, may point to a configuration issue with cron (not enough memory compared to app pods, etc.).

**Comment by telusdcinco** [comment]
MIGRATION NOTES:

Code change only.

**Comment by telusdcinco** [comment]
@jizhaogit  Please review code changes.

**Comment by jizhaogit** [comment]
thank you Dennis, looks good to me

**Comment by telusdcinco** [comment]
[Uploading... image.png]
