### ISSUE TITLE
Tooltip in create/edit goal does not function/respond

### ISSUE THREAD

**Issue by steffipravasi** [bcgov/performance#1302]
We have tooltips for mostly all of the fields in create new goal or edit goal but none of the tooltips are working or responding on the click action.

**Comment by steffipravasi** [comment]
@jizhaogit The tooltips are fixed for edit goal but not for create new goal modal. Can we please fix that too?

**Comment by jizhaogit** [comment]
@steffipravasi since this issue is listed separated from the edit current goal ticket.  will move it to "Dev review" until #1018 be done

**Comment by steffipravasi** [comment]
This is no more an issue and the tooltips in create and edit goals are responding correctly now.
