### ISSUE TITLE
Checking Employee Data - Secondee

### ISSUE THREAD

**Issue by jessicahjwu** [bcgov/performance#1303]
Please check in the backend for EEID#198870 (Zachary Matieschyn) on his status (i.e. GUID, IDIR. etc.), I could not locate the user in Employee List hence the user could not access PDP. This individual is not a regular BC Public Service employee but a secondee. However, the job code POI001 should have been included to have access to PDP. Reference profile is EEID#162514.

**Comment by telusdcinco** [comment]
EEID#198870 is missing GUID in employee demographic data.  The employee will not be able to sign in at this time.

EEID#162514 looks fine and should be able to sign in into PDP.
