### ISSUE TITLE
User getting 500 Server Error message whilst trying to launch "My Goals" page

### ISSUE THREAD

**Issue by jessicahjwu** [bcgov/performance#1304]
User Karina Boarato, EEID 192159, has tried to access the "My Goals" page but unsuccessful. She keeps getting the 500 Server Error message when clicking on the menu option.

Please check and see if there's anything in the backend that's preventing her from going to that module, she is fine going into other pages in the platform.

**Comment by steffipravasi** [comment]
This  scenario looks good. Will keep an eye on similar ones
<img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHgxQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c25ea18c003a6f4a235ecd35b2c24e88c71b155e/Screenshot%202024-06-19%20at%2012.20.32%E2%80%AFAM.png" alt="Screenshot 2024-06-19 at 12.20.32 AM.png" />

**Comment by telusdcinco** [comment]
Deployed to Prod.

**Comment by jizhaogit** [comment]
issue addressed:  there are 2 users who have totally same name are shared on one goal with this employee.  
user id 40012 and 55759 are both have same name Michael Jeffery. that caused the user id array index is diff with user name array index.

**Comment by steffipravasi** [comment]
<img width="1606" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGZ3QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--73a936dde5e3745207d0b2280b50b2bed0f0b1c4/Screenshot%202024-07-18%20at%2012.39.45%E2%80%AFPM.png" alt="Screenshot 2024-07-18 at 12.39.45 PM.png" />

**Comment by jizhaogit** [comment]
good catch!  the Michelle Jeffery is in "names" table,  but we can find the middle name difference from the employee table.  i will switch to use the employee table for the name issue. 

Thank you Steffi!

**Comment by steffipravasi** [comment]
@jizhaogit Shall I put the ticket back to in progress?

**Comment by jizhaogit** [comment]
The latest fix is applied in test.  please help verify. thank you!

**Comment by steffipravasi** [comment]
1) 200360	Mckinnon,Angela
003050	McKinnon,Angela
2) 174942	Jeffery,Michael
196610	Jeffery,Michael John
<img width="1832" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHdOQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8630d225bb79df4469f7a5b27c8bec957816f5ef/Screenshot%202024-07-25%20at%2012.22.25%E2%80%AFPM.png" alt="Screenshot 2024-07-25 at 12.22.25 PM.png" />
Tried sharing goal with users with similar or duplicate names, and the my current goals page is loading

**Comment by jessicahjwu** [comment]
I'm still getting 500 Error page returned after clicking on "My Goals" when switching to Karina's profile.

**Comment by steffipravasi** [comment]
@jizhaogit Jessica is correct, the page doesn't load anymore
<img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzBQQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b4e2e7b0a02084bfda0d92c78b07242eb843283a/Screenshot%202024-07-25%20at%2011.56.08%E2%80%AFPM.png" alt="Screenshot 2024-07-25 at 11.56.08 PM.png" />

**Comment by jizhaogit** [comment]
should be addressed.  can you please verify? thanks!

**Comment by steffipravasi** [comment]
My current goals page is loading now.
<img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXdTQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3828dbe66b650db5b532fdf820c9421fc5ca565c/Screenshot%202024-07-26%20at%2012.45.13%E2%80%AFAM.png" alt="Screenshot 2024-07-26 at 12.45.13 AM.png" />

**Comment by telusdcinco** [comment]
Deployed to Training.
