### ISSUE TITLE
CKEditor Version Update 

### ISSUE THREAD

**Issue by jessicahjwu** [bcgov/performance#1325]
CKEditor needs to be updated to the latest version in Edge, users are getting this warning message currently when trying to input comments in "My Conversation":
<img width="1026" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeSt4QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fea0139310739c6c9d90637fe96045fec7a1d994/image.png" alt="image.png" />

**Comment by steffipravasi** [comment]
@jizhaogit Somehow, the open conversations page is not working. Can you please check?
<img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHUxQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--565086a6d9b7e5ee26021f4d784184c7f0dffb33/Screenshot%202024-07-04%20at%201.52.20%E2%80%AFPM.png" alt="Screenshot 2024-07-04 at 1.52.20 PM.png" />

**Comment by steffipravasi** [comment]
@jessicahjwu @jizhaogit We won't be able to deploy this ticket to training today as it is blocked by the ticket #1326 which is caused due to Dennis' latest fix.

**Comment by steffipravasi** [comment]
Verified the editor on edge, chrome, firefox and safari.

**Comment by jessicahjwu** [comment]
@jizhaogit warning message is still appearing in Training both in My Conversation and My Goals:
<img width="991" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUM1QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0049f3d4c78b0dead4973654230767ee9fa8835d/image.png" alt="image.png" />

<img width="967" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUc1QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--25944b1e9accf594a477073f5228c5e9d5a4b1c5/image.png" alt="image.png" />

**Comment by steffipravasi** [comment]
@jizhaogit The errors are not popping up on Test so wondering if there's any difference ?
