### ISSUE TITLE
Open and completed conversation page throws 500 Server error 

### ISSUE THREAD

**Issue by steffipravasi** [bcgov/performance#1326]
**Testing Blocked for ticket 1325**
The open & Completed conversations page do not open and throws 500 error. 
<img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHUxQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--565086a6d9b7e5ee26021f4d784184c7f0dffb33/Screenshot%202024-07-04%20at%201.52.20%E2%80%AFPM.png" alt="Screenshot 2024-07-04 at 1.52.20 PM.png" />

**Comment by jizhaogit** [comment]
issue should be addressed

**Comment by steffipravasi** [comment]
Issue addressed. Thanks Ji!!
