### ISSUE TITLE
Inconsistent number of direct reports displayed in Employee List VS My Team

### ISSUE THREAD

**Issue by jessicahjwu** [bcgov/performance#1329]
Heidi Carota has five direct reports and it's also the correct number of employees showing on Employee List:
<img width="1424" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWEvQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0f56566ec3a5fafcb0eb988ade4ef983011a8df3/image.png" alt="image.png" />

However, when her supervisor, Tracy Leung, looks into the list of direct reports of Heidi's, the number is displayed as six:
<img width="1578" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUsvQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4210aebfb6378da518fdf55c958d5b4df340ab72/image.png" alt="image.png" />

When Tracy clicks on the number of direct reports, the list of names shows only five people:
<img width="1579" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVMvQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ee3cf1ccb24dfd51221670497e66639c8d97ac5e/image.png" alt="image.png" />

Please investigate the reason why the number of direct reports when Tracy looks into her My Teams page is displayed as six people for Heidi.

**Comment by telusdcinco** [comment]
MIGRATION NOTES:

Code changes only.

**Comment by steffipravasi** [comment]
The given user Tracy Leung can see the correct number of direct employees for Heidi Carota
<img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGoxQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--03b94ecda3dc49c4fd1c19208c3684daf5012de2/Screenshot%202024-07-19%20at%201.00.25%E2%80%AFPM.png" alt="Screenshot 2024-07-19 at 1.00.25 PM.png" />
<img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOG4xQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c03bfc9d33ed0a7cb032e61341c9b52866f0c129/Screenshot%202024-07-19%20at%201.00.25%E2%80%AFPM.png" alt="Screenshot 2024-07-19 at 1.00.25 PM.png" />

**Comment by telusdcinco** [comment]
Deployed to Training.
