### ISSUE TITLE
PDP Profile - checking if employee is missing any data in the backend

### ISSUE THREAD

**Issue by jessicahjwu** [bcgov/performance#1330]
Gbolahan Sunmonu #202167 shows active in PeopleSoft since May 2024, however we cannot locate their records in PDP under employee list with Sys Admin access (and the user still cannot access PDP). Please check if the user is missing GUID, or if there's any abnormalities in the backend that's preventing their profile to be created.

**Comment by telusdcinco** [comment]
The EE has GUID but no email address in ODS employee demographics.  This has prevented the creation of a user profile.
