### ISSUE TITLE
Supervisor could not see names of direct reports in Team Goal Bank audience list

### ISSUE THREAD

**Issue by jessicahjwu** [bcgov/performance#1332]
Trudie Manoloudis, EEID 028837, is unable to see names of her direct reports in the team goal bank goal audience list that she previously created and assigned to team members:
<img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjdTQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f84720ee29623221ca426882cbe2c161efffd549/image.png" alt="image.png" />

I was able to replicate the issue in Test and Training:
<img width="1428" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnpTQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dbc8a47506bcd18b84565eeab43ea8d11400117f/image.png" alt="image.png" />

<img width="983" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0RTQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5d17cf5aaeac7a7a2bc94ddb4c6e334ec5aa0c82/image.png" alt="image.png" />

I've checked in her list of direct reports in the My Team page and names are appearing correctly.

**Comment by telusdcinco** [comment]
Issue due to change by #1326.

**Comment by telusdcinco** [comment]
MIGRATION NOTES:

Code change only.

**Comment by steffipravasi** [comment]
Audience list appears correctly for the user
<img width="1710" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3JYQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bd3daff74a88f4da7e73391ac791501daff85011/Screenshot%202024-07-12%20at%2012.46.56%E2%80%AFPM.png" alt="Screenshot 2024-07-12 at 12.46.56 PM.png" />
<img width="636" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3ZYQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--46971000821dbab01fe9d2eadc66106ce70a1187/Screenshot%202024-07-12%20at%2012.46.40%E2%80%AFPM.png" alt="Screenshot 2024-07-12 at 12.46.40 PM.png" />

**Comment by telusdcinco** [comment]
Deployed to Production
