### ISSUE TITLE
Incorrect email notification regarding updates made to a conversation

### ISSUE THREAD

**Issue by jessicahjwu** [bcgov/performance#1333]
There have been several users reporting that they have received email notifications (as well as seeing dashboard notifications) regarding updates they have made to their own conversations. Users stated that they have not made any changes to those conversations, and emails were falsely sent.

1. The user, Lynn Montgomery, received an email notification at 9:04am on Jul 4, 2024:
<img width="1886" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1RTQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0d5f04d222e88237d36a04d853deb85972d7893b/image.png" alt="image.png" />

2. There were no records of Lynn making any updates to conversations at during that period according to the audit log:
<img width="1331" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMy9TQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7e0744a166a206e16fa771738680099aabfc05b4/image.png" alt="image.png" />

3. In the notification log, only the in-app notification sent record can be found:
<img width="1322" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFRTQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dd0c55a49be2a7fc6a644396f66eba0e9bb75a26/image.png" alt="image.png" />

Items to be looked into:
1. Email notifications/in-app notifications should not be sent/shown if updates were not made to a conversation
2. The user shouldn't be receiving an email notification on updates made by themselves, the purpose is to notify the other participant in the conversation
3. Notification log should have both email and in-app notification records

**Comment by telusdcinco** [comment]
Name displayed in email header based on the conversation creator.  The conversation was created by Lynn but was updated by the direct report.  The notification headers shows the "[conversation creator name] Has Updates on Your [converation name]".

The fix is to use the current user's name (person who click on "Send Notification" button).

**Comment by telusdcinco** [comment]
@jessicahjwu
Discovered that there are no notifications sent out when the persons making modification to the conversation are not part of the participant list.  This will happen if manager drills down to a direct report's employees and make changes to their conversations.

The new issue should be resolved in a another ticket.

**Comment by telusdcinco** [comment]
MIGRATION NOTES:

Code change only.

**Comment by steffipravasi** [comment]
1. Karen created a conversation with Barbara
Karen made updates and sent notification. 
Notification sent currently with Barbara name: YES
Barbara made updates and sent notification. 
Notification sent currently with Barbara’ name: YES
2. Karen created a conversation with Crystal
Karen made updates and sent notification. 
Notification sent currently with Crystal name: YES
Barbara made updates and sent notification. 
Notification sent currently with Crystal name: YES
3. Barbara created a goal with Karen
Karen made updates and sent notification. 
Notification sent currently with Barbara name: YES
Barbara made updates and sent notification. 
Notification sent currently with Barbara’ name: YES
4. Crystal created a goal with Karen
Karen made updates and sent notification. 
Notification sent currently with Crystal name: YES
Barbara made updates and sent notification. 
Notification sent currently with Crystal name: YES
<img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOEFUQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1860583c0bc91d5cc2819323c49a072a9b2417fc/Screenshot%202024-07-26%20at%205.21.17%E2%80%AFPM.png" alt="Screenshot 2024-07-26 at 5.21.17 PM.png" />
