### ISSUE TITLE
Users receiving conversation past due notifications (email and in-app) for employees that do not report to them

### ISSUE THREAD

**Issue by jessicahjwu** [bcgov/performance#1335]
Kimberly Lowe who is an Executive Director in Ministry of Finance, has received email and in-app notifications regarding an employee, Anna Trotto's conversation is past due. Anna doesn't report to Kimberly, nor work in the Ministry of Finance:
<img width="1645" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzNlQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--297fcf2568901eab73acd7da8bcef40fa3b719c6/image.png" alt="image.png" />

<img width="1049" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKy9lQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d948ad20746c585290ac7d3674e7caf4762c8640/image.png" alt="image.png" />

This is one of the examples that we have received, this is a system-wide issue impacting multiple users. At this time, there's no evidence of these incorrect "supervisors" being able to access those employee profiles as the list of direct reports in the platform is still accurate:
<img width="1762" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1BlQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--00916f99e42165ca45e7127557becf232b6552ce/image.png" alt="image.png" />

Please investigate and provide the fix as a priority.

**Comment by telusdcinco** [comment]
@jessicajwu Issue relates to picking up manager details when going thru all the pending overdue notification.  Confirmed with Kimberly Lowe/Anna Trotto case.  Please provide additional cases (employee IDs) for me to confirm.

**Comment by jessicahjwu** [comment]
Further scenarios of the similar issue:
Dawn Mascotto receiving overdue conversation notification for Aleesa Paulson
Jordan Petty receiving overdue conversation notification for Heather Scott
Leisha Stepaniuk receiving overdue conversation notification for Latoya Lewis

**Comment by jessicahjwu** [comment]
Shelley Harper receiving overdue conversation notification for Chantelle Sinclair and Keegan Miller

**Comment by telusdcinco** [comment]
@jessicahjwu  Compared the code in Prod against my local/Dev/Test, and found some changes that were not applied since last year which may contribute to getting the wrong supervisor IDs.  Change does not exist in Training also.

Re-applying the fix to Dev/Test for Steffi to confirm/test.

**Comment by steffipravasi** [comment]
List of employees with 30 days, 7 days and 1 day overdue conversations
<img width="196" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlhsQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--619a41612a1853782f0b21cd64d04d0f34ec4f0c/image.png" alt="image.png" />

**Comment by jessicahjwu** [comment]
Turned off notifications for all organizations as of July 16 at 11:30am. Switched PSA notifications back on, did the following testing at 7pm on July 16:

- [ ] Create New Conversation - success, 404 error did not appear
- [ ] Create New Conversation - notification sent to intended supervisor, Margaret Burrows (in-app/email)
- [ ] Update Conversation Comments - success, able to save comments
- [ ] Update Conversation Comments - success, able to notify the other participant
- [ ] Update Conversation Comments - success, notification sent to intended participant, Margaret Burrows (in-app/email)
- [ ] Share Goal - success, able to share a goal with Margaret Burrows
- [ ] Share Goal - success, notification sent to the intended recipient, Margaret Burrows (in-app/email)
- [ ] Add Comments to Goals - success, able to add comments to a goal
- [ ] Add Comments to Goals - success, notification sent to the intended recipient, Margaret Burrows (in-app/email)

**Comment by jessicahjwu** [comment]
Jul 17:

- [ ] Create Goals in Goal Bank - able to create a goal and assign to a business unit (employees matching with PS)
- [ ] Create Goals in Goal Bank - able to create a goal and assign to individuals
- [ ] Create Goals in Goal Bank - notification sent to intended recipients (in-app/email)
- [ ] Batch Email - 8am notifications were sent to the correct supervisors

**Comment by jessicahjwu** [comment]
Issue for this particular ticket has been resolved after rolling back ticket #1297.

**Comment by steffipravasi** [comment]
@jessicahjwu Should we park this ticket in testing until we roll out the fix for 1297?
