### ISSUE TITLE
Remove two department ID's from overnight process

### ISSUE THREAD

**Issue by jessicahjwu** [bcgov/performance#1336]
Related to #1138, dept ID 105-1115 and 105-1200 should have been removed from the overnight process are now re-appearing in the platform:

<img width="1460" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVhrQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4a41f9ffeebc1ad10317708181122dbb5d482efd/image.png" alt="image.png" />

<img width="1423" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNm5rQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--08343a04524b042830a1956ecfc84af7fec2c0fe/image.png" alt="image.png" />

Please investigate and make sure those two pay lists are removed from the overnight process, and that those employees are not visible in the platform nor being able to access the platform.

**Comment by telusdcinco** [comment]
#1297 may have affected the GetODSEmployeeDemographics process.  The process process and updates PDP Excluded flag for excluding indicated depts.  Currently, 105-1115 and 105-1200 are configured to be excluded.

#1297 changes rolled out Friday EOD, was rolled back and impacted processes were rerun.

**Comment by jessicahjwu** [comment]
<img width="1581" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2psQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--907b71b4644f91cb05be4bf3f8d909e446b93464/image.png" alt="image.png" />

<img width="1584" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM25sQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--810e62a522e5376c644ee29edf0bef2c0b39c5fc/image.png" alt="image.png" />


@telusdcinco the two department ID's are still showing in Test

**Comment by telusdcinco** [comment]
Related to #1297 issue in Prod.

**Comment by telusdcinco** [comment]
@jessicahjwu I'm using this ticket for applying related fix to PDP exclusions for $1297.

Change done in GetODSEmployeeDemographics process for updating PDP Excluded flag.

**Comment by telusdcinco** [comment]
@jessicahjwu
#1336 changes have been removed from Dev/Test.
This ticket can be closed.
