### ISSUE TITLE
Employee Profile Sharing Dropdown List Delay

### ISSUE THREAD

**Issue by telusdcinco** [bcgov/performance#1337]
It's been noticed that the dropdown list for sharing employees in My Team's Employee Profile Sharing modal page, is taking too long to return values.  This part of the application have remained almost the same for the past 2 years, and can be updated to improve the performance by applying the changes below.
- not using LIKE in the SQL when there is no search keyword entered
- improve the SQL joins or use a newer/recent static table for the return employee listing
- add index to the SQL for consistent searching patterns
-

**Comment by jessicahjwu** [comment]
Related to #1304

**Comment by telusdcinco** [comment]
@jessicahjwu @steffipravasi

The fix works very well and the dropdown is very responsive.
 
Should we change the behavior of the dropdown to not display anything when the user have not entered a single letter, so that the dropdown do not display same default full list as shown below?

<img width="243" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGNCQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--00b7bb026e0567bc5c35376e70b7a3af98a5748b/image.png" alt="image.png" />

**Comment by telusdcinco** [comment]
Fixed the format issue for the missing email address.

Also updated the name to use the Employee Demo name and not the User Profile name.

<img width="441" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTBCQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c8664a5b8cbe8355dbeed720c04b93bd68c0a155/image.png" alt="image.png" />

**Comment by steffipravasi** [comment]
@telusdcinco 
1) The shared with list again won't load in my current goals
<img width="684" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzBNQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--098411c50e96ce2949e8cec52bd9172cc0833421/Screenshot%202024-07-25%20at%2010.11.46%E2%80%AFAM.png" alt="Screenshot 2024-07-25 at 10.11.46 AM.png" />

**Comment by telusdcinco** [comment]
@steffipravasi  This ticket is for the My Teams page issue.  I think the My Goal is a different ticket.

**Comment by steffipravasi** [comment]
The list in my goal is also loading now
<img width="678" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBellOQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--08b19b21904c7a0c3dfc2d3880888647fccdee75/Screenshot%202024-07-25%20at%2011.27.26%E2%80%AFAM.png" alt="Screenshot 2024-07-25 at 11.27.26 AM.png" />

**Comment by telusdcinco** [comment]
@jessicahjwu @steffipravasi
Updated the dropdown search to allow searching from both employee demo or user profile names.
User can now search using "John Smith" or "Smith,John" formats.

**Comment by telusdcinco** [comment]
@jessicahjwu
There is significant performance degradation on the dropdown by searching in 2 name formats.
Recommend to simplify the search by first+last name, and displaying the result in first+last name format also.  This should make the resulting name format consistent, and users will see the the same name format as they type.

**Comment by telusdcinco** [comment]
@jessicahjwu
MyTeam Share Profile dropdown reverted to yesterday's version which passed Test and pending Migration to Training.
Please do a quick validation in Test, before I move to Training.

**Comment by telusdcinco** [comment]
Deployed to Training.

**Comment by telusdcinco** [comment]
Found code difference implemented in #1155, not found in Training and/or Prod.  Pushed the missing code to Training.
