### ISSUE TITLE
Reporting relationships did not reflect correctly after supervisor has been selected

### ISSUE THREAD

**Issue by jessicahjwu** [bcgov/performance#1343]
Nuo Shen, EEID 200364, reports to a double-bunked supervisor Anthony LeFresne. Although they have selected the right supervisor in the platform the reporting relationships did not get reflected correctly and it's impacting their ability to have a conversation:
<img width="975" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMk1ZQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e97366b6d1900a31fdf9d2c710ed03162a887d93/image.png" alt="image.png" />

<img width="975" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMlVZQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--350879113f45b8b492c91468cc660da0569aa868/image.png" alt="image.png" />

<img width="1385" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMllZQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d83448713018dbab8b8f3b825fb166791e647d67/image.png" alt="image.png" />

**Comment by telusdcinco** [comment]
@jessicahjwu Codes have been recently modified for #1016 fixes.  The dropdown is currently broken.  It does not store the selected manager.

@jizhaogit Please review with #1016 changes that may have impacted the dropdown.

**Comment by telusdcinco** [comment]
Ignore link to #1351 merge request.

**Comment by telusdcinco** [comment]
Issue may have been introduced with #857.  Issue occurs when the employee selecting the preferred manager has multiple jobs and has a terminated job record 0.  The wrong position number is being stored in this case.

Fix will use the position number from the primary job selected (whenever possible) as introduced in #857.

**Comment by telusdcinco** [comment]
MIGRATION NOTES:

Code change only.

**Comment by telusdcinco** [comment]
#1016 change currently have impacted the dropdown selection functionality and needs to be fixed.  This should be addressed by #1016 before going live.

Currently, this fix can only be tested in Training (which does not have accessibility changes applied.

**Comment by telusdcinco** [comment]
The #1016 change impacting testing for this fix has been removed, and will be re-applied after this change goes to Prod.

@steffipravasi This can now be tested in Dev/Test.

**Comment by steffipravasi** [comment]
Test validated and works as expected
<img width="1020" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMk4vQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f95e5cf9ff596dacd8633fa72e6b4f8fb0901488/Screenshot%202024-08-22%20at%205.43.24%E2%80%AFPM.png" alt="Screenshot 2024-08-22 at 5.43.24 PM.png" />
<img width="1367" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMlIvQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--75f47556ff83e4b8ae45808df26a7ac711237651/Screenshot%202024-08-22%20at%205.43.37%E2%80%AFPM.png" alt="Screenshot 2024-08-22 at 5.43.37 PM.png" />

**Comment by telusdcinco** [comment]
Deployed to Training.

**Comment by telusdcinco** [comment]
Deployed to Prod.
