### ISSUE TITLE
Build and deploy the Performance application(PHP part) in Openshift

### ISSUE THREAD

**Issue by kkapoor-fresh** [bcgov/performance#138]
1. Create/modify the Docker file for PHP app to build in Openshift.
2. Manually deploy the PHP app as a new application on Openshift using the Dockerfile.
3. Verify all resources such as buildconfigs, deploymentconfigs/deployments, image streams, pods, replica sets, routes are successfully created.
4. The application is successfully reachable at the the DNS generated by route resource in Openshift.

**Comment by freshjwarren** [comment]
@kkapoor-fresh : Can we split this into smaller stories so we can track the progress on a more fine-grained level?
