### ISSUE TITLE
Verify all resources are successfully created in OpenShift

### ISSUE THREAD

**Issue by freshjwarren** [bcgov/performance#154]
- [ ] buildconfigs
- [ ] deploymentconfigs/deployments
- [ ] image streams
- [ ] pods
- [ ] replica sets
- [ ] routes

**Comment by kkapoor-fresh** [comment]
The PHP app is available at http://performance-docker-app-332842-test.apps.silver.devops.gov.bc.ca/

**Comment by kkapoor-fresh** [comment]
All resources are successfully created in Openshift
