### ISSUE TITLE
Manually deploy the MYSQL DB as a new application on Openshift

### ISSUE THREAD

**Issue by freshjwarren** [bcgov/performance#155]
**Acceptance criteria:**
- [ ] The MYSQL DB is successfully integrated with the PHP app container.
- [ ] The PHP+MYSQL app is reachable at the DNS of the PHP route resource.

**Comment by kkapoor-fresh** [comment]
The PHP+MYSQL app is reachable at the DNS of the PHP route resource.
http://performance-docker-app-332842-test.apps.silver.devops.gov.bc.ca/
