### ISSUE TITLE
As an employee I want to see scheduling and topic information for upcoming conversations with my supervisor

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#158]
"Upcoming Conversations" tab; similar to "current goals" tab. This can be a list view.

- [x] Fields to display include: date of conversation, topic of conversation, view/edit/delete.
- [x] Default to be sorted by date (nearest date at the top; i.e. a conversation scheduled for June shows up before a conversation scheduled for July)
- [x] Conversations with a date that occurs in the past should show up with some type of warning icon/colour to alert the employee that the scheduled conversation was not signed off. Perhaps an additional mouse over with: "This conversation is past due!".

**Comment by phoebesolomon** [comment]
@Travis-A-Clark @Kousthubha-M see Figma - Wireframes are complete for this ticket.

**Comment by Travis-A-Clark** [comment]
@phoebesolomon @Kousthubha-M I think it looks awesome! Thanks so much for the quick work on this, Phoebe.

The one thing we will have to figure out is: once I've scheduled a conversation, it shows up on "upcoming conversations". I need to be able to edit the scheduling/topic/participant info (which Phoebe has done up already); but I also need to be able to "launch" the conversation template itself. It's the tie in to ticket #162. 

Basically, I schedule a career conversation with John Smith for July 10, 2021. It then shows up as a link in my "upcoming conversation" tab. When I actually go to have that conversation, I need to be able to click somewhere on that link to launch the actual template that my supervisor and I use to enter information and sign-off.

So maybe there is an "edit", "delete", and a "launch" icon? Or "open" icon? We need to make it clear that one icon opens the scheduling details, and the other icon opens the actual conversation template and sign-off process. Make sense?

**Comment by phoebesolomon** [comment]
> @phoebesolomon @Kousthubha-M I think it looks awesome! Thanks so much for the quick work on this, Phoebe.
> 
> The one thing we will have to figure out is: once I've scheduled a conversation, it shows up on "upcoming conversations". I need to be able to edit the scheduling/topic/participant info (which Phoebe has done up already); but I also need to be able to "launch" the conversation template itself. It's the tie in to ticket #162.
> 
> Basically, I schedule a career conversation with John Smith for July 10, 2021. It then shows up as a link in my "upcoming conversation" tab. When I actually go to have that conversation, I need to be able to click somewhere on that link to launch the actual template that my supervisor and I use to enter information and sign-off.
> 
> So maybe there is an "edit", "delete", and a "launch" icon? Or "open" icon? We need to make it clear that one icon opens the scheduling details, and the other icon opens the actual conversation template and sign-off process. Make sense?

Yes, @Travis-A-Clark that makes sense. With regards to the conversation template, is this a downloadable document that the employee and supervisor would fill out? Or is it more of a type form that they fill in?

**Comment by Travis-A-Clark** [comment]
@phoebesolomon The conversation template is really the key part of the process. It is the piece that employees and supervisors actually fill in info and sign-off for compliance. So, it has to be type form that is fillable and securely stored in the platform as part of the permanent employee record.

Basically, the scheduling/editing of conversation topics and dates is only important as a logistical piece, whereas the conversation template contains all the real data we need to keep.

So, even in the past conversations tab, the key will be able to continue to access and edit the contents of the template, not the contents of the meeting invite/scheduling.

Happy to chat further!

**Comment by phoebesolomon** [comment]
@Travis-A-Clark thanks for clarifying that, I thought for some reason when you mentioned edit/delete you were referring to the scheduling details of the conversation. I am working on this revision now and will let you know when its complete. Thanks for your help :)

**Comment by Travis-A-Clark** [comment]
@phoebesolomon We do have to be able to edit/delete the scheduling details; so that's still valid. Once a conversation is scheduled, however, there needs to be that additional piece that launches/opens the actual template for them to fill in. So there are two aspects that are editable: the scheduling details, and the content of the form.
