### ISSUE TITLE
As an employee I want the ability to schedule new conversations with my supervisor.

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#164]
- [x] Option to "Add New" on the conversations tab
- [x] Pop up that includes fields for: Participants (drop down of linked profiles, i.e. supervisor / shared supervisor; this can include dummy data for now so just make up a couple of names); Date (calendar); Topic (drop down with "Regular Check-In", "Career Conversation", "New to Position", "End of Probation", "Performance Improvement").
- [x] Include link to support resources at bottom of pop-up (similar to "add new goal"

Ideally, the date calendar function would be connected to Outlook calendar availability; is this possible?

Overall, this will likely be quite similar to the "Add new goal" functionality and interface.

**Comment by phoebesolomon** [comment]
@Travis-A-Clark @Kousthubha-M see Figma

**Comment by Travis-A-Clark** [comment]
@phoebesolomon @Kousthubha-M 

Awesome! Only comment is that I'm not sure we need the "Title" field for conversations. They can likely be identified easily enough by Topic and Date. The Title will likely often just be the same info repeated. Thoughts?

**Comment by phoebesolomon** [comment]
> @phoebesolomon @Kousthubha-M
> 
> Awesome! Only comment is that I'm not sure we need the "Title" field for conversations. They can likely be identified easily enough by Topic and Date. The Title will likely often just be the same info repeated. Thoughts?

Yeah, after thinking it through I realize that the 'Title' field is unnecessary, because it would not be any different than the Topic. I will revise this
