### ISSUE TITLE
Create dev, test, & prod environments

### ISSUE THREAD

**Issue by freshjwarren** [bcgov/performance#166]
Enables changes to be tested without being released to production and without interrupting other development.

For discussion: Would a staging environment be helpful at this time?

**Comment by freshjwarren** [comment]
@kkapoor-fresh : If this is 8 days of effort, let's split it up.

**Comment by kkapoor-fresh** [comment]
@freshjwarren Is this creating the CI/CD pipeline with different stages/env? We can start with creating the pipeline till deploying to the DEV env.  The envs in this case, I am assuming would be different namespaces with the instance of Performance apps running on the existing Openshift cluster.

**Comment by freshjwarren** [comment]
@kkapoor-fresh : No automation required for this ticket. Just the ability to manually deploy to three environments.

**Comment by kkapoor-fresh** [comment]
@freshjwarren  Ok. Can we get access to rest of the environments on which to deploy to?

**Comment by freshjwarren** [comment]
I believe that @Kousthubha-M has access to all of them in the OpenShift console.

**Comment by Kousthubha-M** [comment]
@freshjwarren I can grant Kunal access to rest of the namespaces.

**Comment by kkapoor-fresh** [comment]
@Kousthubha-M Yes please. That would be good.

**Comment by Kousthubha-M** [comment]
@freshjwarren @kkapoor-fresh Kunal, I just granted you access to all namespaces. Let me know if you can access.

**Comment by kkapoor-fresh** [comment]
DEV: https://performance-docker-app-332842-dev.apps.silver.devops.gov.bc.ca/login

TEST: https://performance-docker-app-332842-test.apps.silver.devops.gov.bc.ca/login
