### ISSUE TITLE
Set up GitHub Secrets to store credentials

### ISSUE THREAD

**Issue by freshjwarren** [bcgov/performance#168]
Removes the risk of malicious actors getting credentials that are stored insecurely.

**Comment by kkapoor-fresh** [comment]
@freshjwarren Just to clarify here, the GITHUB secrets are mainly created to be used in GITHUB Actions workflows which we plan to use for creating CI/CD pipelines.

**Comment by freshjwarren** [comment]
@kkapoor-fresh : At this point, it's just to use Github Secrets as a manual password manager. Then the secrets will already be available when the Actions workflow is set up.
