### ISSUE TITLE
Environments shall only expose ports for HTTP (80) and HTTPS (443)

### ISSUE THREAD

**Issue by freshjwarren** [bcgov/performance#169]
Reduces the risk of attack by blocking connections to ports where other services may be running.

**Comment by freshjwarren** [comment]
@kkapoor-fresh : Does it make sense to split this up into an issue for each environment?

**Comment by kkapoor-fresh** [comment]
@freshjwarren This is basically converting the app from http to https. I would we should work through implementing and testing all these tickets in a single dev env first.

**Comment by kkapoor-fresh** [comment]
The app is now accessible at https endpoint  below:
https://performance-docker-app-332842-test.apps.silver.devops.gov.bc.ca/login
