### ISSUE TITLE
Set a calendar event to renew security certificates

### ISSUE THREAD

**Issue by eyjwarren** [bcgov/performance#171]
Prevents security certificates expiring without warning.

**Comment by telusdcinco** [comment]
@Kousthubha-M  Was there any document or emails on the the certificates?  If possible, please share with me.

**Comment by telusdcinco** [comment]
- [ ] 

- [ ]

**Comment by telusdcinco** [comment]
No action required at this time, as the SSL certs are handled by another team.

**Comment by telusdcinco** [comment]
Do we still need this ticket?
