### ISSUE TITLE
(DESIGN-185) Edits to Goals Home Page

### ISSUE THREAD

**Issue by phoebesolomon** [bcgov/performance#200]
- [x]  Change "Add New Goal" to "Create New Goal"
- [x] Change "Past" to "Past Goals"
- [x] Add ability to delete goal (perhaps an "X" in top right corner?) with confirmation ("Are you sure you want to permanently delete this goal?")

**Comment by phoebesolomon** [comment]
@Kousthubha-M @Travis-A-Clark I added a trash can symbol to the goals cards on the home page in the top right corner, and also added a 'delete goal' button to the actual goal card in the bottom right corner. As suggested, I also mocked up the 'confirm deletion' modal that pops up if a user tries to delete a goal. See attached
![Goals Tab - confirm deletion](https://user-images.githubusercontent.com/81586302/117203607-371cf180-adbd-11eb-9a03-efdf0a68fd54.jpg)
![Goals Tab](https://user-images.githubusercontent.com/81586302/117203609-37b58800-adbd-11eb-9e1c-268b6889a4c0.jpg)

**Comment by Travis-A-Clark** [comment]
@phoebesolomon Awesome. Looks good! Thanks. :-)
