### ISSUE TITLE
(DESIGN - 213) Sprint 4 - Improvements

### ISSUE THREAD

**Issue by phoebesolomon** [bcgov/performance#233]
On conversations template:

- [x] Remove "Edit" button and make comments boxes active when clicked

For conversation sign-off:

- [x] Text in comments boxes not required for sign-off; can be empty

- [x] User must select either "agree" or "disagree" before signing off; if neither option is selected highlight text and throw error message: "You must indicate whether you agree or disagree with this content before signing off".

- [x] If checkbox for "My supervisor and I reviewed progress of my goals..." is not checked then highlight that checkbox and throw warning message: "You should work with your supervisor to review and update your goals as part of this conversation. Are you sure you want to sign-off?"

- [x] If checkbox for "I received guidance from my supervisor..." is not checked then highlight that checkbox and throw warning message: "You should discuss performance expectations with your supervisor as part of this conversation. Are you sure you want to sign-off?"

- [x] If user clicks "yes" to confirm then sign-off is complete; if user clicks "no" then sign-off is denied and user is returned to template to edit.

Changes to the attestation; list the three statements below and add agree/disagree columns after to the right of the statements.

- My supervisor and I reviewed progress of my goals and adjusted as necessary.
- I received guidance from my supervisor and understand what is expected of me between now and our next scheduled meeting.
- I accept the content of this record of conversation.

If any of the agree/disagree are not checked, then throw the error message: "You should discuss performance expectations, adjust goals, and capture significant conversation outcomes as part of this process. Please indicate if you agree or disagree with each of the statements before signing off".

**Comment by phoebesolomon** [comment]
On conversations template:

- [ ] Remove "Edit" button and make comments boxes active when clicked

For conversation sign-off:

- [ ] Text in comments boxes not required for sign-off; can be empty

- [ ] User must select either "agree" or "disagree" before signing off; if neither option is selected highlight text and throw error message: "You must indicate whether you agree or disagree with this content before signing off".

- [ ] If checkbox for "My supervisor and I reviewed progress of my goals..." is not checked then highlight that checkbox and throw warning message: "You should work with your supervisor to review and update your goals as part of this conversation. Are you sure you want to sign-off?"

- [ ] If checkbox for "I received guidance from my supervisor..." is not checked then highlight that checkbox and throw warning message: "You should discuss performance expectations with your supervisor as part of this conversation. Are you sure you want to sign-off?"

- [ ] If user clicks "yes" to confirm then sign-off is complete; if user clicks "no" then sign-off is denied and user is returned to template to edit.

**Comment by phoebesolomon** [comment]
@Kousthubha-M @Travis-A-Clark see attached - I am pretty sure this addresses all the main points in the description 
![Group 267](https://user-images.githubusercontent.com/81586302/119014106-a40bbc00-b965-11eb-8c7c-40aaa01c31b5.png)
![Group 268](https://user-images.githubusercontent.com/81586302/119014109-a4a45280-b965-11eb-9b4e-bb071212f997.png)
![Group 269](https://user-images.githubusercontent.com/81586302/119014112-a4a45280-b965-11eb-8d14-57a983d388b4.png)
![Group 270](https://user-images.githubusercontent.com/81586302/119014115-a53ce900-b965-11eb-8c47-f37e2a0b4837.png)



above.

**Comment by Travis-A-Clark** [comment]
@phoebesolomon I provided some updates in the description. Let me know if you have any questions. Thanks!

**Comment by phoebesolomon** [comment]
![Group 317.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/0bf4690d-6d09-4b38-9399-ef2c330d9ee4)![Group 318.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/0ce738f4-7c4c-46e9-9b58-8d3f4f5d36c8)![Group 319.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/9b62e5aa-7742-49cf-b217-a102b8649574)![Group 320.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/f9fd0754-7700-47ec-bbf8-b38ed6074086)![Group 321.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/562a3047-c085-4054-99eb-35bfc7eb3bde)![Group 322.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/f506cd01-b6c3-4558-b686-ec1b541c461b)![Group 323.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/13792561-baf6-4e48-8914-a6137dd406d7)

**Comment by Travis-A-Clark** [comment]
@phoebesolomon Looks good. Thanks for making the changes so quickly.
