### ISSUE TITLE
Sprint 5 - Goal Tab Fixes

### ISSUE THREAD

**Issue by phoebesolomon** [bcgov/performance#235]
**Current Goals page:**

Display linked goal info at bottom of goal card (design below). Add functionality to unlink here as well. 
- [x] Design
- [ ] Dev
![Sprint 5.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/87f339ae-75af-47ec-947e-140ef9af3f9a)

If goal status is changed from "Active" throw message: "Changing the status of this goal will move it to your Past Goals tab. You can click there to make the goal active again at any time. Proceed? Yes/No"
- [ ]  Design
- [ ] Dev
![Frame 14.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/a4f85b56-160f-4699-bf7f-25443590e3c2)
![Updated Past Goals Page.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/43803f56-77a6-4c63-8a2c-28b18054514e)

Increase the clickable area of the goal to launch the expanded goal view. At least add ability to click goal title as well as date. If entire whitespace can be clickable, that would be great.
- [ ] Dev

When a goal is unlinked, it should return to the pop-up list of supervisor goal's again.
- [ ] Dev

**Goal Library page:**
When using search function: is it possible for the accordions to expand to show where the identified goal is stored? For example, searching for "stakeholder" does identify the correct goal (Stakeholder Relationships) but since the accordions default to closed, the user does not see this goal. They have to expand the menu themselves, then search. Or search and then expand the menu. Can the search result trigger the menu expansion?
- [ ] Design
- [ ] Dev

Add ability to see and remove search terms that are currently in use. For example, if I search for "stakeholder" I should see that the results have been filtered by that term and I should be able to remove that term to then see all results without filter. Phoebe had a design concept for this with a search term listing and ability to "x" out terms no longer required.
- [ ] Design
- [ ] Dev

In organization menu, show the goals as "created by" Division X or Branch X rather than Supervisor.
- [ ] Design
- [ ] Dev
![Frame 17.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/97d63b66-d702-419d-956b-e273d2230c7a)

Remove the "Select Goal" column and the "Add Goal" button at bottom right
- [ ] Design
- [ ] Dev

Clicking the goal title launches the goal card: remove dates from top of goal card (user adds their own dates if they use the goal); add the "Add Goal" function to the card. 
- [ ] Design
- [ ] Dev
![Frame 16.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/8f593a0d-a144-4d72-ac93-1ee446a1aa79)

**Create New Goal:** (note changes in text; please check for typos when coding as there are a number of mistakes in current test environment version)

Change the Goal Title mouse over text to: A short title (1-3 words) used to reference the goal throughout the Performance platform. 
- [ ] Design
- [ ] Dev
![Frame 8.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/6468c1e0-32ed-4ec9-8985-dd563ee59c7d)

Change the What mouse over text to: A concise opening statement of what you plan to achieve. For example, "My goal is to deliver informative MyPerformance sessions to ministry audiences". 
- [ ] Design
- [ ] Dev
![Frame 9.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/c9b0bc08-b7e2-4be0-a942-ad6f639b6e86)

Change the Why mouse over text to: Why this goal is important to you and the organization (value of achievement). For example, "This will improve the consistency and quality of the employee experience across the BCPS". 
- [ ]  Design
- [ ] Dev
![Frame 10.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/d004b6b5-1229-4ac0-833b-8b2ef93708a4)

Change the How mouse over text to: A few high level steps to achieve your goal. For example, "I will do this by working closely with ministry colleagues to develop presentations that respond to the need of their employees in advance of each phase of the performance management cycle". 
- [ ] Design
- [ ] Dev
![Frame 11.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/d5efbd63-c23b-453e-b3fc-49d052f8ccfa)

Add "s" to Measure"s" of Success and change mouse over text to: A qualitative or quantitative measure of success for your goal. For example, "Deliver a minimum of 2 sessions per month that reach at least 100 people". 
- [ ] Design
- [ ] Dev
![Frame 12.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/6fea79ac-4d5e-4196-a62f-ac075881a183)

**Supervisor's Goals pop-up**: we need to differentiate these goals from the ones in the goals library; UET shows users were confused by the repetition of names and content.

Replace "Stakeholder Relationships" with Building Partnerships (content in comments below). Replace "Coaching Leadership Style" with Lease Agreement (content in comments below).
- [ ] Design
- [ ] Dev

**Past Goals Page:**

Change the "Measures of Success" info for all goals to: "An increase in X by Y%".
- [ ] Design
- [ ] Dev

Fix menu heading: change "Employee" to "Status" (it's the last menu column)
- [ ] Design
- [ ] Dev

Add delete function (trash can icon?) 
- [ ] Design
- [ ] Dev
![Past Goals Page.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/70be0b77-5418-40f2-8327-03dd5beccdcc)

If goal status is changed to "Active" throw message: "Changing the status of this goal will move it to your Current Goals tab. You can click there to access the goal again at any time. Proceed? Yes/No" 
- [ ] Design
- [ ] Dev
![Frame 14.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/a4f85b56-160f-4699-bf7f-25443590e3c2)
![Updated Past Goals Page.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/43803f56-77a6-4c63-8a2c-28b18054514e)

**Comment by Travis-A-Clark** [comment]
@phoebesolomon I like this a lot. Displaying the extra info about which supervisor goal is linked at the bottom of the card as well is a nice add.

**Comment by phoebesolomon** [comment]
@Travis-A-Clark @Kousthubha-M see attached - this is to address the issue above regarding the search function. The user can enter in keywords in the search bar as 'filters', and if there are goals existing in the library that contain those keywords, the 'Your Organization' and 'Your Supervisor' will automatically expand to show the results and highlight the keywords used. ![Frame 7.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/b8d1fff0-9c25-4c56-b1d5-1faf7baba3c7)

**Comment by Kousthubha-M** [comment]
@phoebesolomon  This is looking good!! I’ll check on how to implement this.

**Comment by phoebesolomon** [comment]
@Kousthubha-M I realized I made a mistake with the mockup - so I have re-uploaded the revised version. See above

**Comment by phoebesolomon** [comment]
@Kousthubha-M @Travis-A-Clark updated past goals page![Updated Past Goals Page.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/40003469-834b-483a-9494-a857c5b6a6bb)

**Comment by phoebesolomon** [comment]
@Kousthubha-M @Travis-A-Clark in response to the point above _"Clicking the goal title launches the goal card: remove dates from top of goal card (user adds their own dates if they use the goal); add the "Add Goal" function to the card."_

![Goal Pop-up - Goal Library.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/1fe33776-7e7c-49b0-a721-65637bf76e57)

**Comment by phoebesolomon** [comment]
@Travis-A-Clark @Kousthubha-M in response to _"Change the Goal Title mouse over text to: A short title (1-3 words) used to reference the goal throughout the Performance platform."_

![Enter Goal Title - hover.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/387cff2c-62b4-4425-a029-95746bf7c860)

**Comment by phoebesolomon** [comment]
@Travis-A-Clark @Kousthubha-M in response to _"Change the What mouse over text to: A concise opening statement of what you plan to achieve. For example, "My goal is to deliver informative MyPerformance sessions to ministry audiences"._

![Frame 9.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/3da9089f-2d6c-4d2b-9a06-696547d9d82e)

**Comment by phoebesolomon** [comment]
@Travis-A-Clark @Kousthubha-M in response to _"Change the Why mouse over text to: Why this goal is important to you and the organization (value of achievement). For example, "This will improve the consistency and quality of the employee experience across the BCPS"._

![Frame 10.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/11c37a2a-190e-4f66-bbc8-e8e624a5c300)

**Comment by phoebesolomon** [comment]
@Travis-A-Clark @Kousthubha-M in response to _"Change the How mouse over text to: A few high level steps to achieve your goal. For example, "I will do this by working closely with ministry colleagues to develop presentations that respond to the need of their employees in advance of each phase of the performance management cycle"."_

![Frame 11.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/815c25de-1650-4f38-ab2e-164b70bad0fc)

**Comment by phoebesolomon** [comment]
@Travis-A-Clark @Kousthubha-M in response to _"Add "s" to Measure"s" of Success and change mouse over text to: A qualitative or quantitative measure of success for your goal. For example, "Deliver a minimum of 2 sessions per month that reach at least 100 people"."_![Frame 12.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/433abe96-cac5-4697-a034-5d0b278b3d2d)

**Comment by phoebesolomon** [comment]
@Travis-A-Clark @Kousthubha-M in response to _" If goal status is changed to "Active" throw message: "Changing the status of this goal will move it to your Current Goals tab. You can click there to access the goal again at any time. Proceed? Yes/No"_![Frame 13.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/f099e1f2-7e20-4980-9c87-3449f815efef)![Frame 14.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/d03e3059-1df6-46ee-aabd-dfdcb8ca4522)
