### ISSUE TITLE
File iStore order for Outlook/Exchange integration

### ISSUE THREAD

**Issue by freshjwarren** [bcgov/performance#240]

**Comment by freshjwarren** [comment]
Draft sent to Donna but I'm skeptical that it's the right format, so I suspect to get it back.

**Comment by Travis-A-Clark** [comment]
@freshjwarren Are you able to connect with KK on this? We had questions about the need for all the siteminder info when we already have Azure setup. Also not sure if we have to wait for CITZ support before we can start exploring on our end.
