### ISSUE TITLE
As a supervisor I want to see a dashboard that summarizes important info about my employees.

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#255]
This is just the overall design ticket. Separate tickets for each function have been created and will be added to future sprints. First, let's get the layout in place and then start adding functionality.

This page will have two sections: an actions section up top and a dashboard section below.

The actions section will have functions to:

Add Goal to Library: mouse over text "Create a goal for your employees to use in their own profiles."
Share My Goals: mouse over text "Choose which of your own goals are visible to your employees."

These are just action buttons that launch pop ups similar to what employees use for creating new goals and scheduling conversations. Will add separate ZenHub cards for each pop-up. Then beneath those action items, we have the summary dashboard.

Dashboard headings should include:

Employee name
Active goals (# of active goals)
Upcoming conversation
Last conversation
Shared (Yes or No)
Excused (Yes or No)

- [x] Design
- [x] Dev
- [x] Deploy

KK to create supervisor1@example.com log-in to show difference between supervisor and employee views.

- [x] Dev
- [x] Deploy

**Comment by phoebesolomon** [comment]
Supervisor Dashboard - My Employees Tab![Supervisor Dashboard - My Employees.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/b925fc3a-9500-4c5a-8eb3-c3ad72f60ab3) ![Supervisor Dashboard - My Employees-1.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/49b2e95f-0b6c-42e0-b88a-3119801ae420)

Supervisor Dashboard - Performance Statistics ![Supervisor Dashboard - Performance Statistics.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/147f9791-4d08-4a60-adb4-77790cb11ded)

Supervisor Dashboard - Goals Hierarchy - Option 1 ![Supervisor Dashboard - Goals Hierarchy - Option 1.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/9ea1ae22-ffcb-478a-88bf-cef541a9259e)

Supervisor Dashboard - Goals Hierarchy - Option 2 ![Supervisor Dashboard - Goals Hierarchy - Option 2.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/a0b4dc95-53af-4f14-b29e-65fbf3bc2d22)

Supervisor Dashboard - Goals Hierarchy - Option 2 (Expanded Goal) ![Supervisor Dashboard - Goals Hierarchy - Option 3 - Expanded.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/72a521b7-c86c-4e5f-abd3-4d744983e5d1)

**Comment by Travis-A-Clark** [comment]
@phoebesolomon I'm not sure the toggle for sharing will cover things. As outline in ticket #53 it's not only if the employee profile is shared, but with who. So, if the employee profile is shared, and the supervisor wants to change who it is shared with, will they have to toggle the switch off and then back on again? How would they access the next level. Let's discuss when you have a chance. Thanks!
