### ISSUE TITLE
As a supervisor I want to see summary performance statistics for my employees.

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#256]
Replicate the HR Admin > Statistics and Reporting tab in the My Team area so that a supervisor can see information on their team. 

MVP: supervisor only sees reports for their direct reports and shared (delegated) reports.

Ideal: supervisor has filter that allows them to select their own direct reports or their own direct reports + everyone that reports to them in the hierarchy.

**Comment by Travis-A-Clark** [comment]
From Phoebe:

Supervisor Dashboard - Performance Statistics ![Supervisor Dashboard - Performance Statistics.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/147f9791-4d08-4a60-adb4-77790cb11ded)

**Comment by jp-Telus** [comment]
@Travis-A-Clark 

Summary Performance Statistics report are built for My team (Note: those direct report and shared employees are included in the calculation).

I did the test on DEV and looks good to me. 

Test case 
Amy.Lee@gov.bc.ca
2 direct reportee
2 shared profiles

Show 4 employee in the statistics reports.

Please confirm the TEST migration. Thank you.

**Comment by jp-Telus** [comment]
@Travis-A-Clark 

Confirmed that this ticket was migrated to TST. Please kindly proceed the testing.

**Comment by steffipravasi** [comment]
@jp-Telus 
Test status: **Fail**
Env: Test
User: Lori.Willms@gov.bc.ca
The Reset button does not function when clicked. The user can be searched though the search button and when reset button is clicked, the fields are reset but the graph below is not set to default.
![Screen Shot 2022-09-12 at 6.58.41 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/e075f9b4-303d-40f3-bb84-78ba7422e20b) 
![Screen Shot 2022-09-12 at 6.58.54 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/f6860a86-5b6e-49f3-81b2-7825af60805f)

**Comment by jp-Telus** [comment]
@steffipravasi 

This issue fixed and migrated to TEST region. BTW, I also fix this statistics and reporting page in HR Admin and System Admin area. Thank you

**Comment by steffipravasi** [comment]
Test status: Fail
Env: Test
User: Shannon.Baskerville@gov.bc.ca
@jp-Telus I think the issue is not fixed yet. The default graph is not shown on the click of Reset button. Please follow the steps below to reproduce:
i) Login as Shannon
ii) Go to My Team -> Statistic and Reports -> Shared Employees Summary
iii) The graph has 1-yes and 5-no
iv) In the search function search for Advanced Education and Skills Training -> Deputy Minister's Office. The graph will change to 0-Y and 1-No.
v) Click the Reset button
vi) The search fields are set to default and the graph must show 1-yes and 5-no.

**Comment by steffipravasi** [comment]
Test status: PAss
Env: Test
The graph not showing the default results when Reset button is clicked is fixed. 
![Screen Shot 2022-10-12 at 6.13.28 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/92adaa89-8079-4113-b241-68e2a57a874a)
Ticket ready for PO review

**Comment by Travis-A-Clark** [comment]
We are going to push this ticket to production because of interdependencies with ticket #773. We are then going to hide it on the nav menu in production so that no one accesses it until we resolve some data accuracy issues.
