### ISSUE TITLE
As an employee, I want to be able to copy my supervisor's goal to use as the basis for my own goal.

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#258]
**In My Supervisor's Goals Tab**

In addition to being able to view supervisor's goal, add ability to copy the supervisor's goal and add it to your own Current Goals tab as an active goal. Similar to the add from goal library function. This will allow employee's to copy their supervisor's goal and then modify it once it's in their Current Goals to make it their own.

Add action buttons to bottom of goals cards in My Supervisor's Goals to:
View: with mouse over text "Click to view the details of this goal."
Copy: with mouse over text "Click to copy this goal to your Current Goals tab and make it your own."

If user clicks copy throw message: "This goal will be copied to your Current Goals tab. You can access and edit it there without impacting your supervisor's goal. Continue?"

- [x] Design
- [x] Dev
- [x] Deploy

**Comment by phoebesolomon** [comment]
![Frame 20.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/a21f3e79-69f0-4632-b4a2-87eb95a28caf) ![Frame 30.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/9a7341ab-f009-4632-a866-24867c9c21e1) ![Frame 31.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/32d287a5-be86-40d1-b2fb-98af5e8fd509)
