### ISSUE TITLE
Official Performance Evaluation Definition 

### ISSUE THREAD

**Issue by tanyasheena** [bcgov/performance#264]
If we can define what an official performance evaluation is then we can keeps the existing retention schedule

**Comment by Travis-A-Clark** [comment]
Working with Tanya and our colleagues in Privacy and Security. Hoping we can make revisions something like below. All TBD.

ORCS 57240-20: Employee Personnel Files
SO: upon retirement, resignation, or employment termination from the BC public service
SA: 10 years
Currently includes “formal performance evaluations”. Would like to specify that the only data from the new Performance Development platform that qualify as “formal performance evaluations” are records of discussion stored in the “Conversations” module.

ORCS: Information Systems Overview
Currently does not list MyPerformance or any Performance systems. Will have to consider adding to the new Performance Development platform.

ARCS ADMIN 400-20: Ministry/Agency Planning and Performance Files
SO: when no longer required for planning or performance evaluation and reporting
SA: 2 years
Would like to add reference to the “Goals” module of the new Performance Development platform here.

ARCS ADMIN 1350-20: Employee Supervision and Development
SO: when no longer required by manager/supervisor or upon expiry of retention periods stipulated in the collective agreement (e.g., disciplinary records)
SA: nil
Would like to add reference to the “Competencies” module of the new Performance Development platform here.

**Comment by Travis-A-Clark** [comment]
Final revision submitted to GRS through Jennifer O'Neill
