### ISSUE TITLE
MyPerformance Home Page Design

### ISSUE THREAD

**Issue by phoebesolomon** [bcgov/performance#280]

**Comment by phoebesolomon** [comment]
![BC PSA - Performance Development - Low Fidelity Wireframes.png](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/bafe5bf1-7d78-4bf7-8f0d-4f6e5dac0838)![BC PSA - Performance Development - Low Fidelity Wireframes (1).png](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/e6952aa9-3dc5-4aaf-8b13-17a78e49193b)![BC PSA - Performance Development - Low Fidelity Wireframes (2).png](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/8dea86fe-843b-4cc4-9081-12cfc473b934)![BC PSA - Performance Development - Low Fidelity Wireframes (3).png](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/5ce78f41-38ed-423b-afc1-b7877e131dd1)

**Comment by phoebesolomon** [comment]
@Travis-A-Clark see above

**Comment by jenerick100** [comment]
Hi Phoebe, these look great. My only comment is on the final page and it is incredible minor - can we remove the reference to an annual performance conversation? It is exciting to see these come together.

**Comment by phoebesolomon** [comment]
![Home Page - 1.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/7bb682bc-2658-4420-80b8-24b89e2d8006)![Home Page - 2.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/b1e8603d-0d88-43bc-a2ff-8a1198f25552)![Home Page - 3.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/0d6ba773-ac0f-45a4-a327-c0c2185f768f)![Home Page - 4.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/a73d77db-d54a-426a-97b2-ad01b0cd5b3a)
