### ISSUE TITLE
As an employee I want to see who has access to my profile (supervisor, shared access, etc)

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#282]
Making the design functional; adding in the information mouse over text as well.

**Comment by Travis-A-Clark** [comment]
![Home Page - 2.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/b1e8603d-0d88-43bc-a2ff-8a1198f25552)![Home Page - 3.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/0d6ba773-ac0f-45a4-a327-c0c2185f768f)![Home Page - 4.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/a2fc9a86-77b7-480e-a740-6adb3b6c3084)

**Comment by phoebesolomon** [comment]
@Travis-A-Clark @Kousthubha-M wanted to confirm if he can go ahead with the designs seen above? I know that we will be changing the language a little bit, but we wanted to get your input before proceeding

**Comment by Travis-A-Clark** [comment]
@phoebesolomon @Kousthubha-M Yes, all good! Please go ahead. with coding. Any future changes should, hopefully, be minor. Thanks!
