### ISSUE TITLE
Specify data to come in and out of the ODS

### ISSUE THREAD

**Issue by freshjwarren** [bcgov/performance#284]
Re-opening this ticket now that we have established test connection to ODS.

Kevin, Dennis, Rene and Travis to meet and discuss.

Dennis to work with ODS team to set up request for specific fields.

**Comment by Travis-A-Clark** [comment]
@kevindavidb Can you provide an update here re: work being done to validate any of the assumptions baked in to our v 1.0 data flow spreadsheet? Do you need anything additional from me?

@freshjwarren @kevindavidb When should we look at setting up the meeting with Phil and the rest of the Telus / PSA team on this? My schedule becomes a bit more normal by Thursday of next week.

**Comment by Travis-A-Clark** [comment]
Version 1.5 in place; test data available from PeopleSoft via ODS. See ticket #322 for additional work.
