### ISSUE TITLE
As an employee I want to see my default BCPS picture included in my Performance profile

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#288]
Currently all BCPS employees can upload a picture to their Microsoft account that is displayed in applications such as Outlook and Skype. Once we have access to active directory info, I am hoping we can pull this picture into the Performance app as well.

In the meantime, can we add random default images like the ones we include in the Goals tab for discussion?

**Comment by Travis-A-Clark** [comment]
![Home Page - 1.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/7bb682bc-2658-4420-80b8-24b89e2d8006)

**Comment by telusdcinco** [comment]
As discussed previously, there are some limitations on access the employee's profile picture for display on the page.
The default profile image on Home Page: My Current Supervisor will be removed for now.
