### ISSUE TITLE
Improve breadcrumbs / directory path on My Team tab

### ISSUE THREAD

**Issue by phoebesolomon** [bcgov/performance#289]
It would be great to discuss organizing the breadcrumbs into more of a "navigation" format so that the user can easily navigate back to a certain point in their journey. This is especially important for the executive persona because they will be navigating to so many different pages within the "my team" tab, and based on the current design, they would have to click back on so many individual tabs to get back to where they started. 

We also want to make it easy for them to switch between different lists of direct reports under different individuals. I'm not sure if "breadcrumbs" is the right word because what I am describing is more of a directory path, similar to how files are organized on Windows. I've attached some images below for reference. ![Screen Shot 2021-08-30 at 2.24.26 PM.png](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/643ed6cc-e0e6-4f60-9fee-9d5dafd06283)![2-18_Fig_C.png](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/1dc459cd-5110-4101-933a-6f3c85d2036c)

**Comment by phoebesolomon** [comment]
It would be great to discuss organizing the breadcrumbs into more of a "navigation" format so that the user can easily navigate back to a certain point in their journey. This is especially important for the executive persona because they will be navigating to so many different pages within the "my team" tab, and based on the current design, they would have to click back on so many individual tabs to get back to where they started. 

We also want to make it easy for them to switch between different lists of direct reports under different individuals. I'm not sure if "breadcrumbs" is the right word because what I am describing is more of a navigation path, similar to how files are organized on Windows. I've attached some images below for reference. ![Screen Shot 2021-08-30 at 2.34.18 PM.png](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/09691dcd-ae37-410e-8ac2-126dab20c881)

**Comment by phoebesolomon** [comment]
My Suggestion:

![HR Admin Dashboard.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/07fde9fd-1704-4a40-8bd4-3bcbef5ca913) ![HR Admin Dashboard 01.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/16934874-a838-4bbc-9e39-7ebf78e99895) ![HR Admin Dashboard 03.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/429a4211-ba34-43ec-9632-a707f12349f3)![HR Admin Dashboard 04.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/55ae9270-9bce-4ab9-8152-2fe1c83cd98b)

**Comment by phoebesolomon** [comment]
@Travis-A-Clark just assigning you so you can see the mockups for this new "breadcrumb" concept. I know we won't be tackling it until next sprint but just wanted to have the mockups available before I leave on vacation.

**Comment by Travis-A-Clark** [comment]
@phoebesolomon I really like the concept because it does open up lots of possibilities if we add additional functionality at some point in the future. One thing I am not certain about, what would the navigation lead to if you were to hover over "excused" or "active goals" etc? As in, would it just show the status, or would it be clickable to take you to that info? And it it's clickable, maybe it doesn't need to be an additional arrow/level, just a clickable part of the list. That would mean that only the "Direct Reports" would have the arrow to continue expanding out the drop down. Not sure if I've communicated that properly, but basically thinking whether we need the additional level of navigation or if we can make things clickable earlier in the chain.

**Comment by phoebesolomon** [comment]
@Kousthubha-M @Travis-A-Clark needs estimate - not sure where we left off for this ticket.
