### ISSUE TITLE
Sprint 14 - Goal Tab Fixes

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#293]
**In Create New Goal tab**
- Goal type: change order of drop down menu to - work, learning, career development
- Measures of success mouseover: change text to "A qualitative or quantitative measure of success for your goal. For example, "Deliver a minimum of 2 sessions per month that reach at least 100 people"".

**In Goal Card**
- Add functionality to the comments section to allow users to either add a new comment OR reply directly to an existing comment. Potential for multiple comment threads on a single goal.
- Add author stamp to the comments made. Current we see that profile picture of the individual that posts, but it would be good to have the author's name and the date stamp posted more clearly.
- In goal status change "Goal not met" to "Not met" and change "Cancelled" to "Cancelled or deferred".
- Add an info mouseover by the goal status drop down that says: Active = currently in progress or scheduled for a future date; Achieved = supervisor and employee agree objectives met; Not met = substantial portion incomplete by target date; Cancelled or deferred = shift in plans but want to archive goal for future reference. If possible put each of these statements on their own line in the pop up info box to make it cleaner looking.

**In My Supervisor's Goals**
- Logged in as Supervisor 1: when I click on the My Supervisor's Goals tab I see the goal that I (Supervisor 1) have shared with my own employees. I should only see goals here that were shared with me by other users (such as Executive 1). Not sure exactly what's happening here. Can you take a look?

**Comment by phoebesolomon** [comment]
@Kousthubha-M 
"Goal type: change order of drop down menu to - work, learning, career development"
![Frame 9.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/5c0786aa-42ee-4115-9ccf-90933e70694e)

Measures of success mouseover ![Frame 12.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/3bc10d06-40ca-484c-ae4e-d08a16492d45)

Commenting in goal card
![Frame 40.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/bde24c9e-3e5b-4040-a4d7-48c323c4224c)

Goal status dropdown on goal tile ![Sprint 5.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/8addbe30-42ec-4b57-8ffd-ff7203756f92)![Sprint 5-1.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/f4780038-d7cc-4276-b945-360543de6a4a)

Goal status dropdown in goal card:
![Frame 42.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/759e5f5c-a2d9-4ec7-9fef-aaa7fd977f79)![Frame 43.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/486e2012-8de8-4234-9dbf-aa70291db33d)

My Supervisors Goals: ![Frame 41.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/eb6e7771-b685-492c-8507-f761234692a4)

**Comment by Kousthubha-M** [comment]
@Travis-A-Clark Except the first 2 items in "Goal card", rest items are developed and deployed.

**Comment by Travis-A-Clark** [comment]
Thanks @Kousthubha-M ! Looks good.
