### ISSUE TITLE
As an HR Admin I want to be able to see a dashboard of employees within my business unit 

### ISSUE THREAD

**Issue by phoebesolomon** [bcgov/performance#296]
See ticket #71 for updated design.

- [x] Design
- [ ] Dev
- [ ] Deploy

**Comment by phoebesolomon** [comment]
![HR Admin Dashboard.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/131ac88a-4a12-4d97-957d-57fd93e21060)

**Comment by phoebesolomon** [comment]
@Kousthubha-M needs an estimate. Please move to 'Product Backlog' when estimation is complete.

**Comment by Travis-A-Clark** [comment]
Moving remaining work to ticket #691.
