### ISSUE TITLE
Conversations Tab - Sprint 15 Revisions

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#302]
**Conversations page**
- Add "Conversations Templates" as first tab before "Upcoming Conversations".

**Conversations Templates tab**
- Add text at top of list: "Select a topic below to set up a performance conversation. Templates include suggestions for when to select a given conversation topic, questions to consider when having the conversation, and an attestation and sign-off area to formalize the results."
- List of conversation topics, similar to the employee list, with search function at top. Topics to include: Onboarding, End of Probation, Goal Setting, Performance Check-In, Recognition, Performance Improvement, Career Planning, When a topic is clicked, it launches the template (see details below...I will provide the updated text). 

**Conversation template** (see attachment for text for all sections)
[https://app.zenhub.com/files/329107952/2505e886-45d5-44e3-ba8a-a072a1c7bbed/download](https://app.zenhub.com/files/329107952/2505e886-45d5-44e3-ba8a-a072a1c7bbed/download)

- Add current template name in heading bar at top of template modal
- Top section: "When to Use This Template" expandable heading that explains why/when to use the selected template.
- Second section: "Meeting Info" that includes Topic (default to whichever topic the user clicked on to launch the template but allow them to scroll through and view other templates without having to close out and select again from the original list); Participants (default to include user who is creating the meeting); and button to "Use This Template" that acts as a save function that moves the template to your upcoming conversations area.
- When a user clicks "Use This Template" throw message: "This will send a notification to all participants that you would like to schedule a conversation and will move this template to your upcoming conversations tab. Continue?"
- Third section: template content questions, comments box, and sign-off
- Add Supporting Materials box to bottom of template

**Schedule functionality**
- Remove "Schedule New Meeting" action button in top right of screen.

**Compliance messages across top of screen**
Logic is still that a conversation must be completed every 4 months. Shifting the messaging.
- Message should be: "Your last performance conversation was completed on [DATE]. You must complete your next performance conversation by [DATE]." That second date is 4 months after last completion date.
- If no conversation has ever been completed, message should be: "You have not completed any performance conversations. You must complete your first performance conversation by [DATE]." That second date is position start date plus 4 months (this info will come from ODS once it's set up).
- If conversation has not occurred in over 4 months, message should be: "You are required to complete a performance conversation every 4 months at minimum. You are overdue. Please complete a conversation as soon as possible."

**Comment by phoebesolomon** [comment]
Conversations Page and Templates Tab - Layout Option 1:
![Conversation Templates - Option 1.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/349aa35b-e935-4170-aede-931043d5e2e4)
Conversations Page and Templates Tab - Layout Option 2:
![Conversation Templates - Option 2.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/7aaa98a8-fb6c-4932-8d22-d9e8a64522b4)
New Conversation Template Design:
![Conversation Templates - Option 2 - Template Pop-up.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/0f278468-d5c8-42f1-8514-7fb61a597463)
Conversation Template Activated:
![Conversation Templates - Option 2 - Template Pop-up - Activated.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/2c305d3c-56c4-44b7-856b-68258320442e)
Schedule Conversation - Confirmation Message:
![Conversation Templates - Option 2 - Template Pop-up - Activated-1.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/55e64c11-4fbd-4d28-a3b7-cbc4fa3e6c3f)
Compliance Messages:
![Conversation Templates - Warning Message 1.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/ce84d390-29ae-47c7-b32c-effd0956bfde)![Conversation Templates - Warning Message 2.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/b0e66db8-394c-4c90-a0f2-8f95647874e4)![Conversation Templates - Warning Message 3.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/d4689ea9-c9f9-4602-98be-64f000a7731d)

**Comment by Travis-A-Clark** [comment]
@phoebesolomon I think this looks really good! One suggestion: can we make the warning messages yellow until the conversation deadline is passed and then make that final one red? So, the only red one would be: "You are required to complete a performance conversation every 4 months at minimum...". And a follow-up, where does the user go when they "click here" in that warning message?

As for the overall design, I am fine with sticking with option 1 for consistency if you think that's best. Visually, I do prefer option 2 though, so if you aren't worried about consistency as much, let's go with that one.

Thanks!

**Comment by phoebesolomon** [comment]
@Travis-A-Clark I will fix the warning messages and upload the mockups to this ticket shortly. And re: "click here", I realize that doesn't make sense because we are not using the "schedule a conversation" modal anymore so I will revise that. 

I'm not too concerned about consistency for the conversation templates page and I prefer option 2 as well, so yes, let's go with that.

**Comment by Travis-A-Clark** [comment]
Thanks, @phoebesolomon ! Looks great.

@Kousthubha-M Please see revised designs and descriptions for conversations area above. Ready for coding. Let me know if you have any questions.

**Comment by Travis-A-Clark** [comment]
@Kousthubha-M Thanks for this! I can only see two small things left:

- Add text at top of list: "Select a topic below to set up a performance conversation. Templates include suggestions for when to select a given conversation topic, questions to consider when having the conversation, and an attestation and sign-off area to formalize the results."

-  Continue the compliance message into the "Conversation Template" tab as well (across the top same as the other tabs).

Thanks!
