### ISSUE TITLE
As a user I want instructions and examples for using the goals tab

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#304]
Develop and post support docs to the Performance platform.
- Best practice and examples for the goals section (see attachment for text)
- Housed on the "Resources" page under the "Goal Setting" tab (delete current links, include as a page within the platform, not a link to a PDF)
- Also to be linked from the "create new goal" modal; replace the placeholder text with link to "Resources" section of the platform.

[https://app.zenhub.com/files/329107952/e7d6db77-b705-4d7a-8dc7-2ec5ec4474e2/download](https://app.zenhub.com/files/329107952/e7d6db77-b705-4d7a-8dc7-2ec5ec4474e2/download)

**Comment by phoebesolomon** [comment]
![Resources - What is goal setting.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/1710c171-49f3-46c1-bfbc-418d8265416c)![Resources - Why are goals important_.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/f0fab9bf-c01a-45a4-9985-0ba80ef54b9e)![Resources - Why are goals effective.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/75d888b3-bb30-4fc3-af04-843e0619c322)![Resources - What does a good goal statement look like.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/95f6e01e-c7fa-499b-a7d4-90a03f54f942)![Resources - Examples of work goals.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/481368cc-5859-463a-9c11-9f899bf76a93)![Resources - Examples of learning goals.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/f613b327-962c-4f42-bdea-a1fb443bec0a)![Resources - Examples of Career Goals.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/a406081f-9afb-4498-9841-91c0dcdfa5b1)
