### ISSUE TITLE
Page Titles (Goals, Conversations, etc)

### ISSUE THREAD

**Issue by phoebesolomon** [bcgov/performance#309]
Page titles should be added for the supervisor view as well

**Comment by phoebesolomon** [comment]
See below![Goals.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/72817d92-c9b9-4580-9061-3047a5b24739)![Conversations.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/aef616ae-2e91-4bf8-8dc1-5b0aa80f543f)![Resources.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/1562d6bb-45d5-4c26-abd6-f92b10bf8546)

**Comment by Travis-A-Clark** [comment]
@phoebesolomon This makes sense to me. No concerns. Just a reminder that we will also need the updated heading for the My Team tab in the supervisor view. Currently it says:

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/375f9474-6ad5-43af-a233-2f0b2c67e276)
