### ISSUE TITLE
Complete Using Prod Data in Non-Prod Environment Security Checklist

### ISSUE THREAD

**Issue by freshjwarren** [bcgov/performance#310]
Igor requested that we complete [this document](https://app.zenhub.com/files/329107952/bd48e661-b602-45a5-af64-9c61af72c413/download) if we are storing personal information in the test database.

- [ ] Complete document
- [ ] Get executive sponsor to email approval to Igor

**Comment by Travis-A-Clark** [comment]
First draft submitted to Igor March 20. He has requested a few revisions that I will give back to him in the next few days.

**Comment by Travis-A-Clark** [comment]
Completed and approved - March 31
