### ISSUE TITLE
Revisions to Goal Bank/Library

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#319]
- Change name to Goal Bank
- Remove "supervisor" and "organization" headers; no longer needed since the user will be able to filter by "created by" as a field
- Add descriptors to each goal to increase search functionality: created by, date created, mandatory/suggested, work/learning/career development
- Will require revisions to Add Goal to Bank for supervisor and HR Admin; will need to be able to add additional tags (i.e. mandatory or suggested, work or learning, etc)

**Comment by phoebesolomon** [comment]
Employee View:
![Goal Bank Tab - Created By Dropdown.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/36a21653-2193-45a8-ab6f-137117840005)![Goal Bank Tab - Date Dropdown.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/8130abaa-bde6-41f2-8c58-041b10d41f28)![Goal Bank Tab - Goal Type Dropdown.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/f254d97d-4d33-462c-8731-aa89f2b995e6)![Suggested Dropdown.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/f52d06c4-6bef-4038-aaa1-02256fadf781)![Goal Bank Tab.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/6e19ee3e-bd1c-4d74-8a30-b6acc4c3e67b)
Supervisor View:
![My Team Page.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/599b0828-3096-4332-b02f-6537b28228f1)![Goal Bank Page.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/47f10d73-03c2-4150-a12a-c2338afad1c0)![Goal Bank Page-1.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/ebbed7cc-58e5-4294-a719-da5eefdc9aac)
HR View:
![HR Admin Dashboard - HR Functions - Design Option 5.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/f3956c3a-5c41-4879-8100-be99dc9ff4b7)![HR Functions - Suggest a Goal.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/d137f8f0-3d31-4f06-82cf-449d5a385800)
