### ISSUE TITLE
Test data pull from ODS

### ISSUE THREAD

**Issue by kevindavidb** [bcgov/performance#322]
There is test employee data available in ODS for us to pull into the OpenShift MyPerformance - can we see if we can import it, and validate if correct.

**Comment by telusdcinco** [comment]
Based on Dev team discussions, we'll need to have the GUID fully resolved and have the endpoints created for Performance, similar to the one for PECSF.  Creating the endpoints may require additional information on the fields/data that need to be pulled from ODS.

**Comment by telusdcinco** [comment]
Meeting scheduled to PS developer to discuss PS/ODS current data.
Reviewing the code done for PECSF for the ODS testing.

**Comment by telusdcinco** [comment]
Successfully pulled the demo data for 1 of the 2 end points for performance.  The 2nd end point doesn't seem to have any data.

**Comment by telusdcinco** [comment]
Deployed code to pull data from ODS demo table.
Executed the command manually to trigger the code.  dev table populated with values from ODS.
