### ISSUE TITLE
Resolve issue with TES accessing TEAMS

### ISSUE THREAD

**Issue by Abuchana** [bcgov/performance#329]
Team members from TES cannot access messanger or files in TEAMS. Seems to be an issue on the TES side. 
Ask Jared to help if needed

**Comment by Travis-A-Clark** [comment]
Need to connect with 7-7000 support; may be a delay due to issues surrounding provincial flooding.

**Comment by telusdcinco** [comment]
Thanks for letting us know.


Thanks and regards,

Dennis Cinco
Developer Team Lead - TELUS
O: +1 (604) 453 2149   M: +1 (778) 980 8585

Vacation Alert:  November 22, 2021

Visit us today at telussourcingsolutions.com - the future is friendly®
telus.com<http://telus.com/>  Facebook<https://www.facebook.com/telus>  Twitter<https://twitter.com/telus>  YouTube<http://www.youtube.com/telus>  Linkedin<https://ca.linkedin.com/company/telus>

P Please consider the environment before printing this email.

This email is for the sole use of the intended recipient and may contain confidential, proprietary and/or privileged information. If you receive this email in error, please contact the sender and delete this message from your computer.
