### ISSUE TITLE
Revisions to HR Admin Mockups 

### ISSUE THREAD

**Issue by phoebesolomon** [bcgov/performance#330]

**Comment by phoebesolomon** [comment]
My Organization Page - Part 1:
![HR Admin Dashboard Part 1.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/7fee4272-4552-47ec-b9b6-60834dbeb30d)

My Organization Page - Part 2:
![HR Admin Dashboard Part 2.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/003b1d67-90fd-46ee-9d63-6c149e1beb00)

HR Admin Functions Tab - Part 1:
![HR Admin Dashboard - Functions Tab Revised Part 1.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/6e7af3bf-1614-4ea5-acd4-d6056bad9926)

HR Admin Functions Tab - Part 2:
![HR Admin Dashboard - Functions Tab Revised Part 2.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/1d1a29d5-01ff-40d5-9ee0-cd35a825fcc5)

HR Function 1 - Add Goal to Goal Bank:
![HR Functions - Add Goal to Bank.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/0d619e88-d4c5-401a-90e3-94bf37280078) ![HR Functions - Add Goal to Bank - Organization Dropdown.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/65d032fc-3925-4d7b-aec8-f260efa7d8d1)![HR Functions - Add Goal to Bank - Level 1 and 2 Dropdown.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/f6b75bff-7af3-4ec2-a266-eaca2fd794f1) ![HR Functions - Add Goal to Bank - Level 3 Dropdown.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/05002115-a58c-4376-8e8c-8ea016edb39b)![HR Functions - Add Goal to Bank - Level 1 Selected.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/ec85e89d-724b-4bef-87dc-c439741c5732)![HR Functions - Add Goal to Bank - Executive Employees Selected.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/480f4254-8c3d-48bb-b0be-bce033b27de9)

HR Function 2 - Sharing Employees:
![HR Functions - Share Employees Function Page.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/f88887d2-eb43-4eaf-b5c6-45c3b1aee83e) ![HR Functions - Share Employees Function Page - Select Employees to Share.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/af70d505-672f-4f51-bcda-949a8a44497e)![HR Functions - Share Employees Function Page - Select Employees to Share - Level 2.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/18908e57-5c2b-40ee-9e9d-229ba6b2f538) ![HR Functions - Share Employees Function Page - Step 1.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/18dbe98c-d495-4981-9a5e-1ba76dc5967d)![HR Functions - Share Employees Function Page - Step 2.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/1a3d8cde-7c02-478a-a1d0-8f638126ae36)![HR Functions - Share Employees Function Page - Step 3.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/d46f69ba-41c1-43a9-9229-58c597a7434a)

HR Function 3 - Excusing Employees:
![HR Functions - Excuse Employees Function Page.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/15fe46bc-18d8-4954-b87b-a286aece7db5) ![HR Functions - Excuse Employees Step 1.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/3ddf765a-9126-4dd5-9596-7ebc21670496)![HR Functions - Excuse Employees Step 2.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/ac298e20-62c2-4da5-8ec8-3a5942fc67b9)![HR Functions - Excuse Employees Step 3.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/84fe4912-08f2-4caa-9f9c-74e1581a5115)![HR Functions - Excuse Employees Step 4.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/adba3102-bc5c-4ad1-90a9-c08f891e7e30)

HR Function 4 - Notifying Employees:
![HR Functions - Notify Employees Function Page.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/816b02ea-b034-420a-b400-766379efb339)![HR Functions - Notify Employees Step 1.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/a9cae177-b304-40c7-81a2-1f2d44576683)![HR Functions - Notify Employees Step 2.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/7f260516-e5d3-4e98-9757-3336fd4657c0)![HR Functions - Notify Employees Step 3.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/3f510bb4-9d5e-4ddc-b133-92387af3f3aa)

**Comment by Travis-A-Clark** [comment]
@phoebesolomon This is awesome! Thanks for continuing to revise and improve (and sometimes go back to old designs). The only thing missing are the "Date" fields in the Add Goal to Goal Bank function. Now that we have mandatory goals included, we will need to provide HR Admin, Sys Admin, and supervisors with the ability to add dates to the goals when they add them to the library. Everything else looks good to go for testing.

**Comment by phoebesolomon** [comment]
@Travis-A-Clark revised - see above.
