### ISSUE TITLE
Investigate Org Hierarchy Data

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#335]
Product Team to connect with B.I. (Alan, Stu, etc.) to better understand content of org hierarchy and process to update. Determine best way to integrate data into ODS and then pull into Performance platform.

**Comment by r3n3941m3** [comment]
with reference to the Org Hierarchy Spreadsheet provided by Travis (as of October 28th), there are organizations on Level 4 and as per Allan O'Neil, the level can be referred to as Program Office.

With reference to PerfDev Data Point v1.5 (002) spreadsheet, we need to add another column at the end to contain the Program Office data

**Comment by r3n3941m3** [comment]
Items for discussion with Allan O'Neil:

1. Some entries in the Org Hierarchy does not have a specific Dept ID code.
2. Discussion need to be done for entries identified as Unallocated which are occupying the higher level order of some Department IDs

**Comment by Travis-A-Clark** [comment]
@r3n3941m3 Thanks for this, Rene! Can you also please add an estimate to the ticket (approximate number of days you think will be required to complete this ticket).

**Comment by r3n3941m3** [comment]
estimating 2 for now, pending the action items on remaining items to be discussed with DW folks

**Comment by r3n3941m3** [comment]
Answers I gathered from the ODS meeting regarding Org Hierarchy data

1. Some entries in the Org Hierarchy does not have a specific Dept ID code.
- Not all nodes in the Org Hierarchy structure in Data Warehouse is linked to a specific Department ID from PeopleSoft where the employees are attached. These nodes were created for Org Structure purposes and have distinct Node IDs.
- Nodes referenced to PeopleSoft Department IDs also have distinct Node IDs

2. Discussion need to be done for entries identified as Unallocated which are occupying the higher level order of some Department IDs
- Nodes labelled as Unallocated have distinct Node IDs

**Comment by r3n3941m3** [comment]
Data Formats for Org Hierarchy:

Format 1: This currently exists in ODS
![image.png](https://images.zenhubusercontent.com/6154aa68e730b566493cd7a2/53eb9b73-35b7-42a2-bb22-dbbdc47e6d52)

Format 2: This is from DW table structure for reference on available fields only. 
![image.png](https://images.zenhubusercontent.com/6154aa68e730b566493cd7a2/a292b074-0f5f-4507-9b0a-bf4df5636ebe)

**Comment by r3n3941m3** [comment]
@Kousthubha-M , can you check what can work well for you to implement the drill down functionality? I can setup a meeting so we can discuss next week

**Comment by Travis-A-Clark** [comment]
Travis, Rene and KK to meet to clarify requirements. 

Travis and Rene will meet Stu Hemerling to discuss next steps and timelines.
