### ISSUE TITLE
Push Goal and Conversation pages to the Test Space

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#338]
- Once latest changes incorporated, push the Home, Goals, and Conversations pages to the test namespace. 
- Add "Stakeholder Relationships" to the Goal Bank as a mandatory goal and a couple of others as suggested goals.
- Add two different goal samples to the My Supervisor's Goals tab (you can use any of the goals from the Goals Resources tab examples if you need additional content)
- Ensure all ministry logins are active in Test space (i.e. PSA1, PSA2, EDUC1, EDUC2. etc). The position start date for all these accounts should be Nov 1, 2021 (for purposes of the conversations deadline messages)

**Comment by Travis-A-Clark** [comment]
Hey @Kousthubha-M 

I see the goals in the Goal Bank now, but still nothing in the My Supervisor's Goals section. Can you take a look? Thanks!

- Add two different goal samples to the My Supervisor's Goals tab (you can use any of the goals from the Goals Resources tab examples if you need additional content)

**Comment by Kousthubha-M** [comment]
@Travis-A-Clark I guess you're logging in with general employee login. These goals are added to the additional users profiles. Try logging in with one of the additional user logins

**Comment by Travis-A-Clark** [comment]
@Kousthubha-M You are correct. Thanks!
