### ISSUE TITLE
Create items for ODS interface test

### ISSUE THREAD

**Issue by telusdcinco** [bcgov/performance#345]
Below are the steps that can be done in preparation of the ODS integration test.

- Request for temp tables for storing performance data.
- Request for end points to performance data, for get/post

**Comment by Travis-A-Clark** [comment]
@telusdcinco Is this related to ticket #360 as discussed earlier today? Can I put this ticket in the sprint backlog for this sprint as well or is it separate?

**Comment by telusdcinco** [comment]
We can close this one and just track ODS test on #360
