### ISSUE TITLE
Quick Fixes for Conversations Template

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#346]
**Conversation Templates Tab**

Change order of sections to:
- Meeting Info
- When to Use this Template
- Preparing for the Conversation
- Suggested Discussion Questions
- Supporting Materials

Leave Meeting info section expanded. For all other sections, introduce accordion headings like the "When to Use This Template" section. All collapsed on launch so all headers are visible.

**Upcoming Conversations Tab**
- Change the heading "Questions to Consider" to "Suggested Discussion Questions" to match the templates.
- Remove the red warning that appears on conversations saying that they are past due; we don't have a date scheduled for each specific conversation anymore so this isn't require (see reference below)
![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/10a4488e-b475-4d36-9143-9272b11303c7)

**Comment by Kousthubha-M** [comment]
@Travis-A-Clark  The changes have been deployed.
