### ISSUE TITLE
Goal Bank Tab Mockups

### ISSUE THREAD

**Issue by phoebesolomon** [bcgov/performance#350]

**Comment by phoebesolomon** [comment]
![System Admin Dashboard - New Design - My Organization.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/87eb02b0-3095-431f-bebd-83f20365482b) ![System Admin Dashboard - New Design - Goal Bank 1.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/a70c59aa-3dd4-4bfa-9575-f36154200867) ![System Admin Dashboard - New Design - Goal Bank 2.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/eac7f830-4215-47f4-9ac6-b023119a534a) ![System Admin Dashboard - New Design - Goal Bank 3.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/2528a800-bd53-4e5f-a8c3-ffeedeab1b02) ![System Admin Dashboard - New Design - Goal Bank 4.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/5e7d9109-ed3f-4eb5-98ca-23d817ec3310) ![System Admin Dashboard - New Design - Goal Bank 5.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/0da47409-7594-44bc-a454-41ee5ce1acbb)

View goal audience:
![System Admin Dashboard - New Design - View Goal Audience 1.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/725190fc-0b1e-4414-aa43-e74636bfad01)
![System Admin Dashboard - New Design - View Goal Audience 2.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/cf9251a9-b902-487c-a039-27c48615ef61)

Edit goal bank:
![System Admin Dashboard - New Design - Edit Goal Bank 1.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/c29a6cc9-855d-4b55-902b-cb5fcb3dc378) ![System Admin Dashboard - New Design - Edit Goal Bank 2.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/688b90a3-ddec-4a69-9b6a-ab8b6dd47f0b) ![System Admin Dashboard - New Design - Edit Goal Bank 3.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/7f5f9c23-8128-41e6-882b-f4f093d5f3cf) ![System Admin Dashboard - New Design - Edit Goal Bank 4.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/8daf28d8-6920-45ec-ae24-c806b3dfebd9)

**Comment by phoebesolomon** [comment]
![System Admin Dashboard - New Design - Goal Bank 1.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/23aa2906-6bfd-4d01-bfbf-8d2ae9b363be) ![System Admin Dashboard - New Design - Goal Bank 2.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/ab0515d7-0572-43a8-8396-afeeb0ec165f) ![System Admin Dashboard - New Design - Goal Bank 3.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/ded74870-4344-4ac3-a920-e6f7bb8856af) ![System Admin Dashboard - New Design - Goal Bank 4.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/d19dc3e4-f0c6-4822-b65d-d8e4bed4ed10) ![System Admin Dashboard - New Design - Goal Bank 5.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/d6005965-a0a9-4034-833a-7c8d16b2ac61) 

View goal audience:
![System Admin Dashboard - New Design - View Goal Audience 1.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/1443fd73-cd21-489c-8032-bd7c5b5f9f9a) ![System Admin Dashboard - New Design - View Goal Audience 2.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/91f41a20-750d-4e57-8f62-1dc75764fc72)

Edit Goal Bank:
![System Admin Dashboard - New Design - Edit Goal Bank 1.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/5a12bd5f-f52a-43e4-b71e-483a663a2a0d) ![System Admin Dashboard - New Design - Edit Goal Bank 2.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/36c6ee7b-5983-47a6-8b59-458c174debb7) ![System Admin Dashboard - New Design - Edit Goal Bank 3.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/a258c640-4c0e-4bc8-9ff6-c5ccb7d341c4) ![System Admin Dashboard - New Design - Edit Goal Bank 4.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/db356df4-b9f0-4e69-abd6-3ab04084641c)

**Comment by Travis-A-Clark** [comment]
@phoebesolomon Apologies if I have just forgotten something, but is there a reason that the view goal audience section is different here than it is for the other Sys Admin functions? I'm not clear on the purpose of the additional modal since we have the selection process and the editing process. Thanks!

**Comment by phoebesolomon** [comment]
@Travis-A-Clark goal audience modal mockups have been deleted

**Comment by Travis-A-Clark** [comment]
Let's make the search / functionality options more consistent. Top line with the organization levels. Second level with the Goal Type, Mandatory/Suggested, Goal Creation Date (search range), Goal Title.

Change Goal Start Date and Goal Target Date in the table columns to single column: Goal Creation Date.

**Comment by phoebesolomon** [comment]
![System Admin Dashboard - New Design - Goal Bank 1.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/bd616197-140d-4d81-a8d5-935230c78779)

![System Admin Dashboard - New Design - Goal Bank 2.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/e86e2444-c435-4458-aec1-671e4f8067a4)

![System Admin Dashboard - New Design - Goal Bank 3.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/c0eac966-b2a3-4d3f-a51a-29ad6476f567)

![System Admin Dashboard - New Design - Goal Bank 4.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/140b7d96-9ca7-4c4d-bcdb-993d61061f14)

![System Admin Dashboard - New Design - Goal Bank 5.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/b2c533a8-59f7-4790-839f-8ee84cc15e74)

![System Admin Dashboard - New Design - Goal Bank 6.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/faf11b35-9932-4657-96f8-bb636df631e2)

Edit Goal Bank Feature:

![Edit Goal Bank 1.png](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/4fee102f-cb4a-45ac-a0ac-70e676bb4428)

![Edit Goal Bank 2.png](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/2d7e365c-61aa-47a1-9912-c5b396bdd2f4)

![Edit Goal Bank 3.png](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/aae138a4-47e4-45c0-9130-b63f552b2012)

**Comment by phoebesolomon** [comment]
![System Admin Dashboard - New Design - Goal Bank 1.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/c8c97643-5407-4536-a54d-0b3c7a4682c4)

![System Admin Dashboard - New Design - Edit Goal Bank 2.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/9c5ae6ea-dd5d-4d76-9486-5a9924772f5f)

![System Admin Dashboard - New Design - Goal Bank 3.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/5ce10c8d-bb99-42e7-a661-77e6ebca7b23)

![System Admin Dashboard - New Design - Goal Bank 4.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/4c6b01b7-bac3-4ec0-bdaa-7cbd81eca04a)

![System Admin Dashboard - New Design - Goal Bank 5.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/aff2982c-c109-4ec7-93aa-164432c949c4)

![System Admin Dashboard - New Design - Goal Bank 6.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/7a0b7d59-757c-4273-8b9a-5e98803b3837)

Edit Goal Bank:

![System Admin Dashboard - New Design - Edit Goal Bank 1.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/0754c7e8-e3c4-4b39-aeb0-e77973877efc)

![System Admin Dashboard - New Design - Edit Goal Bank 2.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/4193bfee-b874-4626-b350-3e9fb3c27745)

![System Admin Dashboard - New Design - Edit Goal Bank 3.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/10d7f274-2fbd-4458-9998-bc2381b87e4e)

![System Admin Dashboard - New Design - Edit Goal Bank 4.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/9ef1c02a-bd63-4f7b-bead-a17836e633fb)

**Comment by telusdcinco** [comment]
Latest version deployed.

Pending work...
- Complete the Audiences Org Tree selection/storing process.
- Split Add new Goal and Manage Existing Goals.
   - Manage Goal to display list of existing Goals
   - Clicking on existing goal displays the Edit version of Add New page.
- Change the filter to display Search Criteria and Search button only on 2nd row.

**Comment by telusdcinco** [comment]
Latest version to be deployed to Dev.

Pending items:
- Org Hierarchy

**Comment by telusdcinco** [comment]
Applied the modified filters...
Applied the Org Tree from James' Notification, still a few glitches to fix.
HR/SYS Admin accounts created.  
Use sysadmin1@example.com or sysadmin2 or sysadmin3 for Sys Admin access.
Use hradmin1@example.com or hradmin2 or hradmin3 for HR Admin access.

**Comment by telusdcinco** [comment]
Updated items under Goal Bank menu.

- Updated Manage Goal Bank
1. using the new Org Tree filter and key search
2. using the new display grid
3. goal list includes goals with is_library flag turned on
4. deferred data loading
5. Org level labels using Level 1, Level 2, Level 3, Level 4

- Add to Goal Bank in progress

- Known issues:
1. Search filter group box extends beyong page margin when browser window is resized

**Comment by telusdcinco** [comment]
Deployed the latest version for SysyAdmin in Dev for testing.  HR Admin still pending
Goal Bank fixed to display admin shared goals.
Admin Goal Bank is now based on business unit (org), org list can be updated.

**Comment by telusdcinco** [comment]
Tix #471 is part of this change.  
Noticed that the Delete button for Goals and Goal Org is not currently working in Dev.  Will be looking into it now.

**Comment by telusdcinco** [comment]
Delete buttons fixed.
HR restrictions in effect based on organization entities assigned to the HR user.
