### ISSUE TITLE
Shared Employees Tab Mockups

### ISSUE THREAD

**Issue by phoebesolomon** [bcgov/performance#351]
Change wording under Shared Employees heading to: "Below is a list of employees in your organization that are currently shared."

When a user completes the process and hits "Share Profiles" button, throw a summary modal that shows the details of their selection and asks them to confirm / continue or cancel / go back.

**Comment by phoebesolomon** [comment]
![System Admin Dashboard - New Design - Share Employees 1.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/394b8277-6947-4b0f-b850-c51980b9bb09) ![System Admin Dashboard - New Design - Share Employees 2.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/e0bf64f7-9b6e-430a-881f-c8b2e6babb85) ![System Admin Dashboard - New Design - Share Employees 3.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/ec1d400c-d0f5-4c06-aae0-b2d9145b08c9) ![System Admin Dashboard - New Design - Share Employees 4.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/f24eb3d5-b4b7-4e51-998a-5eb43b5fe54e) ![System Admin Dashboard - New Design - Share Employees 5.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/26f02908-9c3d-44f7-bcb4-6b83113e3d8a)

**Comment by phoebesolomon** [comment]
![System Admin Dashboard - New Design - Share Employees 1.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/17f4f01e-cbab-4111-b88a-71b359884962) ![System Admin Dashboard - New Design - Share Employees 2.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/165e5b7a-33df-44db-ac59-07af2036b691) ![System Admin Dashboard - New Design - Share Employees 3.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/0bc9c80e-3e28-4b65-a48e-487e54a6c711) ![System Admin Dashboard - New Design - Share Employees 4.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/c50102ac-0c1c-4fd0-8b2d-e66dc8ef4c0b) ![System Admin Dashboard - New Design - Share Employees 5.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/14b11816-a6f6-4a80-a6fe-5e24aec6fdea)

**Comment by Travis-A-Clark** [comment]
This looks great. Let's just change the wording under the Shared Employees heading at the top to: "Below is a list of employees in your organization that are currently shared".

**Comment by telusdcinco** [comment]
In development.  Initial mockup pending Dev deployment.
- Share an Employee
- Manage Shared Employees

Pending items:
- Org Hierarchy

**Comment by telusdcinco** [comment]
Modified filters in progress.

**Comment by telusdcinco** [comment]
Updated items under Share Employees menu.
- Updated Manage Existing Shares
1. using the new Org Tree filter and key search
2. using the new display grid
3. deferred data loading
4. Org level labels using Level 1, Level 2, Level 3, Level 4

- Known issues:
1. Search filter group box extends beyong page margin when browser window is resized

- Share an Employee changes in progress.

**Comment by telusdcinco** [comment]
Latest deployed in Dev, which utilizes 2 sets of Dept Tree interface.  Investigating issue upon filtering that the 2nd set of values are being cleared.

**Comment by Travis-A-Clark** [comment]
Still dealing with the two org trees; list view works fine

**Comment by telusdcinco** [comment]
Deployed modified Employee Shares for Sys Admin.  The program will now create a setup for each employee sharing with other employees.  Pending applying the config to the employee lookup in Goals and Conversation pages.

**Comment by Travis-A-Clark** [comment]
@telusdcinco received the following error message when creating a new shared employee from Sys Admin page:
<br>
![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/61ff065f-a960-4e3a-976e-79484779375a)
<br>

Also, as an HR Admin, on the shared employees tab, I should only be able to see and modify shares for employees in my organization, not the whole public service. Need to apply the same filter on the 'Manage Existing" shares page as elsewhere in HR Admin.
<br>
Just a quick fix to the date format for the "updated at" date...it's showing day of week rather than day of month (see below).
<br>

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/dcb6f982-a601-49d3-9151-11be5054adae)
<br>

Not seeing the shared employees in the drop down on the delegated supervisor's Goals page.

**Comment by telusdcinco** [comment]
Deployed latest changes to Dev.

**Comment by Travis-A-Clark** [comment]
Also just noted that when a share is created, the confirmation comes up but does not wait for me to click before disappearing and confirming share.
