### ISSUE TITLE
Excused Employees Tab Mockups

### ISSUE THREAD

**Issue by phoebesolomon** [bcgov/performance#352]
Change text under Excused Employees heading to: "Below is a list of all employees in your organization that have been excused from the performance development process."

Change text under Excuse New Employees heading to: "All employees are expected to have an up to date performance profile and complete at least one performance conversation every four months. Employees may be excused only if they fit into one of the categories in the dropdown menu below."

When a user completes the process and hits "Excuse Employee" button, throw a summary modal that shows the details of their selection and asks them to confirm / continue or cancel / go back.

**Comment by phoebesolomon** [comment]
![System Admin Dashboard - New Design - Excuse Employees 1.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/52dfa9a0-a290-4405-a6a7-bfe2a23dc136)
![System Admin Dashboard - New Design - Excuse Employees 2.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/1ad08c0b-e969-4a93-b117-1d89126af41f)
![System Admin Dashboard - New Design - Excuse Employees 3.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/6904258d-fa5e-41d1-862b-ddcd2e6965ed)
![System Admin Dashboard - New Design - Excuse Employees 4.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/d1bdd883-4cce-4787-9daf-3f7e5c09aba1)
![System Admin Dashboard - New Design - Excuse Employees 5.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/ebef69d0-1a27-4769-abfb-5d6bf4dcd20a)
![System Admin Dashboard - New Design - Excuse Employees 6.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/6c83a66e-c0cd-48b1-a272-13bb35976723)
![System Admin Dashboard - New Design - Excuse Employees 7.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/e9da90c6-aa38-47c0-ba5f-b251f6263704)
![System Admin Dashboard - New Design - Excuse Employees 8.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/e0f821f6-eec7-4647-adc4-c9d247880a38)
![System Admin Dashboard - New Design - Excuse Employees 9.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/cc69657b-d3bd-40a7-afe4-a4af1850547d)

**Comment by telusdcinco** [comment]
Latest version deployed.

Pending work...
- Attach the Audience portion of the form
- Adjust filter items. (From/To dates need to be retained?) Apply similar filter with Search Criteria and Search button on 2nd row.

**Comment by telusdcinco** [comment]
Pending Dev deployment.
- Excuse an Employee
- Manage Excused Employees

Pending fixes:
- Org Hierarchy

**Comment by telusdcinco** [comment]
Modified filter and Tree changes in progress.

**Comment by telusdcinco** [comment]
Updated items under Share Employees menu.

- Updated  Manage Existing Shares
1. using the new Org Tree filter and key search
2. using the new display grid
3. deferred data loading
4. Org level labels using Level 1, Level 2, Level 3, Level 4

- Share an Employee in progress

- Known issues:
1. Search filter group box extends beyong page margin when browser window is resized
