### ISSUE TITLE
Previous Employees Tab

### ISSUE THREAD

**Issue by phoebesolomon** [bcgov/performance#355]
Change text under Previous Employees heading to: "Below is a list of all employees that have had a record created in the performance platform. You can use this to access historical records."

**Comment by phoebesolomon** [comment]
![System Admin Dashboard - New Design - Access and Permissions - Previous Employees.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/3ba8f517-2957-416a-9c0a-294821928a24)

**Comment by telusdcinco** [comment]
Pending item:
- Fix issue with Organization being reset to All after clicking Search button

**Comment by telusdcinco** [comment]
Current Employees with same status.

**Comment by telusdcinco** [comment]
Move back to In Progress to apply changes for modified filter.
Applying modified filter changes to these pages.

**Comment by telusdcinco** [comment]
Updated Manage Existing Share in Dev

**Comment by telusdcinco** [comment]
Deployed to Dev for review/testing.

**Comment by Travis-A-Clark** [comment]
@telusdcinco I'm still not seeing any employees in the past employees list. As previously discussed, employees should show up here if they were in the PeopleSoft demo data at one point in time and then disappeared from a newer data pull indicating that they are no longer an employee. We still need access to their PDP records. Is this logic in place?

**Comment by telusdcinco** [comment]
The terminated employees in ODS are not actually deleted.  As with previous discussions with Justin before, the date_deleted column will be populated for employees that are no longer with the company.  As of yesterday, there were a few hundred of employees that got values for date_deleted.  Investigating why these employees are not displaying on the Past Employees page.
