### ISSUE TITLE
As an employee, I want to send a notification to participants when I want to schedule a new conversation.

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#356]
We currently throw this message when a conversation template is selected for use:

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/6fbdfada-9d7f-405a-b8a6-c7bfd4fe9a50)

Let's add the resulting notification to the home page of the participants selected in the template. This will also generate an email once we have that functionality established.

**Comment by Travis-A-Clark** [comment]
This has been completed on @jp-Telus local but yet to be deployed to Dev space. Moving to "done" for now.

**Comment by jp-Telus** [comment]
**Work Done**

This change was completed and tested on local. The email notification will send out and also logged in the notification log table. Under the "notification" menu item, HR admin can review the past email notification. 

Note: In the DEV and TEST region, all the notification email will always sent to "travis.clark@gov.bc.ca".


The changes was pushed to REPO and deployed on DEV and Test.
