### ISSUE TITLE
Theme and present feedback from Nov user testing

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#358]
- [x] Rene and Phoebe to provide themed feedback to Travis
- [x] Meet to discuss and revise
- [x] Present to Product Team

**Comment by r3n3941m3** [comment]
[https://app.zenhub.com/files/329107952/af546d7f-9cf7-42f9-b812-8dfb1b0dcc93/download](https://app.zenhub.com/files/329107952/af546d7f-9cf7-42f9-b812-8dfb1b0dcc93/download)

**Comment by r3n3941m3** [comment]
Feedback on Goals functionality Highlights

**Comment by r3n3941m3** [comment]
Feedback on Conversations functionality Highlights[https://app.zenhub.com/files/329107952/60f8ce19-afa3-49a5-a548-4c4c2cc2eff7/download](https://app.zenhub.com/files/329107952/60f8ce19-afa3-49a5-a548-4c4c2cc2eff7/download)

**Comment by Travis-A-Clark** [comment]
@r3n3941m3 Thanks for this! I will take a first scan of the feedback and we can all meet to discuss soon. As for your two pieces of personal feedback, both are being addressed by KK in ticket #348. We are on it! :-)
