### ISSUE TITLE
Pre Team Test Fixes

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#369]
**Notifications List**
- [x] Add “view” action button beside delete garbage can icon (consistent with other pages where you can either click the “view” button OR click anywhere in the title/object to access)
<br>

**Create New Goal Module**
- [x] Under “Supporting Material” link to the Goal Setting tab of the resources section with the text “Goal Setting Resources”
- [x] Change "Target Date" to "End Date"
<br>

**My Current Goals**
- [x] Remove “s” from “Add Goal(s) from Goal Bank”
<br>

**My Past Goals**
- [x] Remove “Action” heading from last column; make consistent with other objects that simply have the view and delete functions available at the right hand side of the object.
<br>

**Goal Bank**
- [x] Add “view” action button and make list items clickable anywhere across to access (consistent with access options for other objects in the platform)
<br>

**Conversation Templates**
- [x] At the top of each template module, below the header and above the "When to Use this Template" section, add text that says: Review the information below to determine if this is the best template for you to use. Then select participants and hit "Use this template" to alert participants you want to meet. Conversations will still need to be scheduled independently in your Outlook calendar.
- [x] Under "Supporting Materials" heading, replace existing text with link to the Conversations tab of the Resources section of the site that say "Learn more about effective performance conversations".
<br>

**Completed Conversations**
- [x] Remove the delete functionality for completed conversations. In order to edit or delete conversations, they must be un-signed by participants which moves them back to the "Open Conversations" area. Anything in completed conversations should be considered an official record that cannot be amended.
<br>

**My Team**
- [x] I still have issues with fitting all columns on screen. If I resize my browser view, I can fit the everything, but then when I reload it moves off screen again (even at the smaller scale). Is there something here that is auto-formatting that doesn’t work with Chrome?
<br>

**Resources**
- [x] User Guide tab, put a note saying “User Guide is under development”.
- [x] Conversations tab, use same structure as Goal Setting tab and copy over text from attached document
- [x] Contact tab, change text to “For additional support, contact Travis Clark, Lead for Performance Management (with a link to my email address Travis.Clark@gov.bc.ca)

[https://app.zenhub.com/files/329107952/8e1abc41-dea5-4855-adc2-fbe4f621812b/download](https://app.zenhub.com/files/329107952/8e1abc41-dea5-4855-adc2-fbe4f621812b/download)

**Conversations Sign-Off**
All of the below worked in a previous build, so hopefully can be restored.
- [x] If a supervisor tries to add comments in the employee box, they are blocked from doing so (which is good) but the Save and Cancel buttons still pop up beside the box which is confusing. Can the save and cancel options only appear for comments boxes that users are permitted to use?
- [x] There used to be warning messages thrown if someone selected “Disagree” to any of the radio buttons and then tried to sign off but they seem to have disappeared. The messages said something like “Participants should discuss goals and performance expectations and try to come to a shared acceptance of the content in this record before signing off. Do you still want to proceed?”. Can you take a look to see if that logic still exists somewhere in the code?
- [x] Employee and supervisor need the ability to un-sign once they have signed to allow them to continue to edit the template if the need to make more changes or re-open the template once it has been moved to “completed”. So, when something is not signed, they see the “Enter 6 digit employee ID to sign” and when it already is signed they see “Enter 6 digit employee ID to un-sign”.
- [x] The warning message at the top of the screen is not always recognizing when  a conversation has been completed. Even when a conversation is completed is still says “You have not completed any performance conversations”. See image below.
![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/9a7d1a27-9392-41c0-9d44-2da650111296)

**Conversation Templates**
- [x] Remove the templates for Recognition and Onboarding
- [x] Update text in remaining templates with content in the attached (there are further instructions for various sections included in the attached word doc as well)

[https://app.zenhub.com/files/329107952/e944a737-7dc0-4cae-a34c-37cd46ce7f39/download](https://app.zenhub.com/files/329107952/e944a737-7dc0-4cae-a34c-37cd46ce7f39/download)

**Create a New Goal**
- [x] Let’s make only the Goal Title and What comment boxes mandatory. Remove the requirements and error messages from Why, How, Measures of Success, Start Date, and End Date.

**Add Goal to Bank**
- [x]  Change the header of the modal from “Suggest a goal” to “Add Goal to Bank”
- [x] Let’s make only the Goal Title and What comment boxes mandatory. Remove the requirements and error messages from Why, How, Measures of Success, Start Date, and End Date.

**Notifications** (Lowest priority: please complete Conversations and Goals work first. Thanks!)
- [x] I get notified if I reply to a comment on my own goal. Supervisor 1 comments on Employee1’s goal. Employee1 receives a notification (good). Employee1 goes in and replies to Supervisor1’s comment. Employee1 receives a notification about their own reply (can we remove this?). 
- [x]  Notifications are not being marked as read on the home screen after I view them. I click on the notification, view the comment on the goal, and when I return to the home screen it still shows 1 new notification marked with the blue indicator.
- [x] Supervisor1 does not receive a notification if Employee1 adds a comment to a goal from the My Supervisor’s Goals tab. Can we add this?

**Comment by telusdcinco** [comment]
Solved 1st one (Notification View button) without any change. Apparently, I revised the code used to track "Goal Comments" to accommodate the new "Goal Replies". The View button will not be visible for old notification entries, but will show for newly created notifications.

**Comment by Travis-A-Clark** [comment]
@telusdcinco Is it possible to have it visible for all notifications, new and old?

**Comment by telusdcinco** [comment]
The "old" notification I'm referring to are the test notifications created prior to adding the Goal Reply notification.
We can ignore the old test notifications, as these were created with an older tag.  
The View button will always be visible moving forward for Goal Comment/Reply.

**Comment by telusdcinco** [comment]
I have deployed all fixes to Dev except for:

My Team
 I still have issues with fitting all columns on screen. If I resize my browser view, I can fit the everything, but then when I reload it moves off screen again (even at the smaller scale). Is there something here that is auto-formatting that doesn’t work with Chrome?

**Comment by telusdcinco** [comment]
The features below seem to be working fine.  Please confirm in Dev.

Employee and supervisor need the ability to un-sign once they have signed to allow them to continue to edit the template if the need to make more changes or re-open the template once it has been moved to “completed”. So, when something is not signed, they see the “Enter 6 digit employee ID to sign” and when it already is signed they see “Enter 6 digit employee ID to un-sign”.

The warning message at the top of the screen is not always recognizing when a conversation has been completed. Even when a conversation is completed is still says “You have not completed any performance conversations”. See image below.

**Comment by telusdcinco** [comment]
Just realized the issue on the item below depends on who created the conversation.  If the employee created the conversation, the employee will see correct message.  If the supervisor created the conversation, the employee will see an incorrect message.


"The warning message at the top of the screen is not always recognizing when a conversation has been completed. Even when a conversation is completed is still says “You have not completed any performance conversations”. See image below."

**Comment by telusdcinco** [comment]
I did not realize I closed the ticket.  I just reopened it.

**Comment by Travis-A-Clark** [comment]
@telusdcinco There may still be an issue with the notifications function. When a supervisor comments on an employee goal, the employee sees the notification on their goals page but the notification does not appear as new or unopened on their home page.

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/ce453191-d331-4418-b185-8956f9f4f47a)
![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/0e75c458-03ef-423f-af0a-66df4cc501fe)

Also, can we send a notification to the supervisor if employee replies to a supervisor comment on an employee goal. In other words, notifications when someone replies to a comment you made on a goal.
