### ISSUE TITLE
As a supervisor, I want to be able to re-open a conversation for up to two weeks after initial sign-off.

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#376]
Currently supervisors and employees can un-sign a completed performance conversation at any time to re-open and edit the content. We should introduce a time limit on this function so that the conversation can only be un-signed within two weeks of initial completion. After the two week limit passes, the conversation should become view only and "lock" and the option to re-open should only be available to HR or System Admins. 

We will also need to add a comment at the top of the Completed Conversations page that says: "Conversation records can be un-signed and edited for up to two weeks from initial completion date. After the two week period, a request to unlock the conversation record will need to be submitted to your HR Administrator if changes are required."

This is connected to ticket #377 for the HR / Sys Admin function.

**Comment by Travis-A-Clark** [comment]
@Kousthubha-M Has this been pushed to the Dev space? I'm not seeing any locked or unlocked options on completed conversations in my view.

**Comment by Kousthubha-M** [comment]
@Travis-A-Clark Yes, It's deployed but except the lock and unlock buttons. As this needs a two week period, for testing purpose I signed off a conversation as employee and supervisor and manually edited the date in the database to 2 weeks earlier. You can see that in the closed conversations.

**Comment by Travis-A-Clark** [comment]
@Kousthubha-M I'm just going to assign this back to you to make sure we don't forget the lock/unlock icons in the design. Thanks!

**Comment by jp-Telus** [comment]
@Travis-A-Clark 

The unlock function were retested and found several issues. I fixed them in the ticket #377. Thank you.

**Comment by jp-Telus** [comment]
@steffipravasi 

The changes are included in #377. Thank you,

The both signed conversation are shown in the 'The completed conevrsation', if the unlocked by administrator or within the 14 days, the icon will be showned 'unlocked'. And both party can unsign the conversation. Once unsign, the ticket will be shwon in the 'Open conversation'.

Thank you.

**Comment by steffipravasi** [comment]
The conversation completed date does not change. Example: For the below conversation, the supervisor signed it on Sep 20 and Team member signed it on Nov 18, the date beside the conversation must be Nov 18?
![Screen Shot 2022-11-18 at 3.55.52 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/de0e68ae-c75a-4ba4-b80e-02a957cbdff9)

**Comment by jp-Telus** [comment]
@steffipravasi 

Good finding. I have fixed the program to show the latest signoff time either employee or supervisor.  I have deployed on both DEV and TEST. I bundle this fix with the ticket #377. 

Thank you.

**Comment by steffipravasi** [comment]
Test status: Fail
Env: Test
Users: Shannon Baskerville(supervisor), Kelly Whitford
Data-id = 16
The conversation is locked even when the supervisor has signed it on Nov 22,2022. 
Kelly had signed the conversation some time ago, when Shannon signed it, the conversation must remain open to edit for the next 14 days
![Screen Shot 2022-11-22 at 3.23.36 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/bcd92354-1749-43c5-9859-26bde5336cae)

**Comment by jp-Telus** [comment]
@steffipravasi 

Good findings, I have to update the program to handle this business logic, either within next 14 days or unlock_until <= today date.

Fixes have been deployed on  DEV and TEST region. (the fix was commit and bundle with ticket #377).

Thank you.

**Comment by SSubashree26** [comment]
Completed validating this ticket in the testing environment and the issue that Steffi had mentioned no longer exists.

Screen recording:
https://bcgov.sharepoint.com/:u:/r/teams/02915/Shared%20Documents/General/Testing/Testing%20screenshots/Performance%23%20376/Performance%20376.zip?csf=1&web=1&e=yRQEvo
