### ISSUE TITLE
As Sys Admin, I want to be able to "unlock" conversations for employees.

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#377]
This is related to ticket #376 for the employee / supervisor side of "unlocking".

Context:
Supervisors and/or employees should be able to un-sign and reopen a completed conversation for up to two weeks from initial completion date. After that point, the conversation will "lock" and will not be available to un-sign. HR and System Admins should have the ability to "unlock" the conversation and provide another window for supervisors and employees to un-sign and edit the content.

- [x] Create an "Unlock Conversations" page for Sys/HR Admin with two tabs: "Unlock a Conversation" and "Manage Existing Unlocked Conversations". 
<br>

- [x] "Unlock a Conversation" tab should have a list of all completed conversations for their organization. Add function to "unlock" conversations in addition to the "view" functionality. There should be a visual indicator of conversations that are locked and those that are unlocked/open. Selecting "unlock" will launch modal that tells HR/Sys Admin: "Unlocking this record of conversation will allow participants to un-sign and edit the content. The conversation will remain unlocked until the date entered below." Then have a "Lock Date" calendar field and submit/confirm button.
<br>

- [x] "Manage Existing Unlocked Conversations" will list only those conversations in the organization that are currently in "Unlock" status. The Admin will have the ability to edit the lock date, or to lock immediately,

**Comment by phoebesolomon** [comment]
**HR Admin**

Main Conversations Tab
![HR Admin - Conversations Tab Main Page.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/4fc62973-2d7e-4863-9708-bca5f5ad170d)

Update Conversation Lock Date
![HR Admin - Lock Details - Part 1.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/a6389766-1522-4321-834f-45de7184c668)

![HR Admin - Lock Details - Part 2.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/efb6e475-a9ff-422a-a48d-5f4a713426ff)

Unlock Conversation
![HR Admin - Unlock Conversations Part 1.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/4174bc2f-f75d-4b08-966a-1ad35531b21d)

![HR Admin - Unlock Conversations Part 2.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/adb992a9-f0b1-40e3-9cf3-c73ca3789f8c)

![HR Admin - Unlock Conversations Part 3.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/51b10c70-9254-4ffb-b409-a612cec6441a)

**System Admin**

Conversation Tab Main Page
![System Admin - Conversations Tab Main Page.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/ef54be50-9cc5-4bce-871a-44a512c08c13)

Update Conversation Lock Date
![System Admin - Update Lock Date Part 1.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/50633f84-8a2d-4723-a21c-40d242b449cb)

![System Admin - Update Lock Date Part 2.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/11a6a544-1b02-47e0-a1f6-12e41d9acbdb)

Unlock Conversation
![System Admin - Unlock Conversations Part 1.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/fd47c29d-8076-49ff-81fd-eb6cb75553c5)

![System Admin - Unlock Conversations Part 2.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/ca90777d-b3ad-464e-ba08-f4462b4dc2e2)

**Comment by phoebesolomon** [comment]
Refer to Figma for designs for this ticket and ticket 435 - https://www.figma.com/file/Zsvxg6Q0lbJfl9sEqkWmC0/Perf-Dev?node-id=0%3A1

**Comment by phoebesolomon** [comment]
**HR Admin**

![HR Admin - Unlock Conversations _ Unlock New Conversation Part 1.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/1ae62299-ba4b-40cc-a247-c5d71f6abfdf)

![HR Admin - Unlock Conversations _ Unlock New Conversation Part 2.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/05af8bfc-c15a-4026-aa9d-05187771d746)

![HR Admin - Unlock Conversations _ Unlock New Conversation Part 3.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/609eb9e1-ca57-4f85-ac2b-dfafa7ef40a8)

![HR Admin - Unlock Conversations _ Manage Existing Unlocked Conversations Part 1.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/b51d6d17-8e5b-488b-97e7-2f07b2f46918)

![HR Admin - Unlock Conversations _ Manage Existing Unlocked Conversations Part 2 - edit conversation lock date part 2.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/c07a3b9c-b121-4409-ac88-a54165330043)

![HR Admin - Unlock Conversations _ Manage Existing Unlocked Conversations Part 3 - edit conversation lock date part 3.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/efb64206-0bfe-4249-83da-bdb47b0af1bf)


**System Admin**

![System Admin - Unlock Conversations _ Unlock New Conversation Part 1.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/1fb2b3de-d15b-4a32-8ed6-044cc4ed1429)

![System Admin - Unlock Conversations _ Unlock New Conversation Part 2.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/82262b34-49a8-40dc-a9c1-2bc4fefdd845)

![System Admin - Unlock Conversations _ Unlock New Conversation Part 3.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/628049bb-cf68-4c96-b368-32fbdcec0d06)

![System Admin - Unlock Conversations _ Manage Existing Unlocked Conversations Part 1.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/04d5062b-3968-4f93-a54b-4f6c827d2668)

![System Admin - Unlock Conversations _ Manage Existing Unlocked Conversations Part 2 - edit conversation lock date part 1.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/fd6f6675-ef76-4cf4-8fcb-53e70a1f31af)

![System Admin - Unlock Conversations _ Manage Existing Unlocked Conversations Part 3 - edit conversation lock date part 2.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/c379e1fa-ae55-4054-bbce-482d71cc5b5e)

**Comment by jp-Telus** [comment]
The development on both tabs "Unlock conversation" and "managed Unlock converstions" has been completed and ready for deployment.

**Comment by jp-Telus** [comment]
Issue:  Travis' reported the 'unlocked conversation' listing is not correct, including those are not signoff. 

Per KK recent data structure change, "Conversation is marked complete when both employee and supervisor sign off. So conversation complete date would be one of the 'sign_off_time' or 'supervisor_signoff_time' depending who signed off last."

Work Done
Apply the new logic on both 'Unlock Conversation' and 'Managed Unlocked Conversation" tabs, is ready for deployment .

Thanks

**Comment by Travis-A-Clark** [comment]
@jp-Telus I have still not been able to successfully test this function. I asked Dennis to backdate a conversation so that it would show up as locked. It was locked on the employee page, but did not show up under "unlock conversation" for the System Admin menu. Maybe you can I can meet and work through an example so I can see it working properly. Thanks!

**Comment by jp-Telus** [comment]
When I look into the conversations in DEV region, I have encountered the issue, looks like is data integrity issue and cause no data returned to displayed on the unlocked conversation page. 

> $ php artisan tinker
> Psy Shell v0.11.5 (PHP 8.0.11 — cli) by Justin Hileman
> >>> \App\Models\Conversation::whereNotNull('initial_signoff')->get();
> PHP Error:  Call to a member function reportingManager() on null in /app/app/Models/Conversation.php on line 82
> >>> \App\Models\Conversation::all();                                 
> PHP Error:  Call to a member function reportingManager() on null in /app/app/Models/Conversation.php on line 82
> >>> 

I did test this on my local machine, no issue.

@telusdcinco , could we do some clean up on the data or any suggestion?

Thank you.

**Comment by Travis-A-Clark** [comment]
@jp-Telus When I unlock a conversation as a Sys Admin, it appears that the employee and supervisor still see the conversation as locked in their Completed Conversations page and still receive the message below when accessing the conversation. Have yet to successfully test all the way through.
<br>
![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/1ef7c103-3b0c-451e-bd3e-501b51c94e77)

**Comment by steffipravasi** [comment]
Env: Test
User: Shannon Baskerville
HR Admin cannot see the Unlock Conversation option in the HR Administration menu. Can see it in Sys Admin.
![Screen Shot 2022-11-02 at 12.20.11 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/6bd54c83-2d83-495a-b618-9f5ed169287e)

**Comment by jp-Telus** [comment]
@steffipravasi 

Thank you for your time to explain and I have revised the program per what we discussed and your documentation. Please kindly move forward to test. Thank you,

**Comment by steffipravasi** [comment]
Cannot sign some of the Open conversations. Eg: Performance Check-In with users Rebecca Fontaine and Julie Muir

**Comment by steffipravasi** [comment]
1) The Suggested Discussion Questions tab does not show any data within. Works fine for the 'Preparing for Conversation' tab below.
![Screen Shot 2022-11-21 at 9.40.02 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/7711ed41-a72c-41d3-849c-be4c0f5569f9)

**Comment by jp-Telus** [comment]
@steffipravasi 

All 3 issues are fixed and deployed on DEV and TEST regions. Please kindly proceed with your testing. Thank you,

**Comment by SSubashree26** [comment]
James has already deployed the changes in dev and test for the cosmetic observations (except for observation 2) mentioned in this document 

https://bcgov.sharepoint.com/:w:/r/teams/02915/Shared%20Documents/General/Testing/Testing%20screenshots/Performance%23377/Observations%20%23377_7%20Dec%202022.docx?d=w5648120517a74264a68d5a09a8afeb61&csf=1&web=1&e=3YXmYv

**Comment by SSubashree26** [comment]
@jp-Telus Unable to perform a search with the "Clarification" search criteria

https://bcgov.sharepoint.com/:v:/r/teams/02915/Shared%20Documents/General/Testing/Testing%20screenshots/Performance%23377/Unable%20to%20search%20with%20classification.mov?csf=1&web=1
