### ISSUE TITLE
As a supervisor, I want to see the conversation area when I view my employees profiles.

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#378]
**My Team Page**
- [x] When a supervisor clicks on an employee in the My Employees table, expand the supervisor view to include the conversations page for that employee. The supervisor should be able to view, add comments, and sign-off on conversations they are a participant in by accessing them through this employee view. They should also be able to set up a new conversation with the employee through the Conversation Template page.

**Comment by Travis-A-Clark** [comment]
@Kousthubha-M 

I logged in as Executive1 to test out this functionality. A couple of notes:

- [ ] When I click on Supervisor1, I can view their goals and conversations area. Awesome! :-)
<br>

- [ ] However, I seem to have the permissions of Supervisor1 rather than Executive1 when I'm on this screen. Not only can I view the conversations, I can add comments as Supervisor1 and schedule new conversations between Supervisor1 and their employees. We need to restrict this. Executive1 should continue to have the permissions of Executive1 even when viewing Supervisor1's profile.

For example, as Executive1, I have the ability to schedule conversations with Supervisor1, 2, and 3 (screen shot below).
![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/b1988456-f420-42e0-af8c-271b14cdbd20)

When I click on Supervisor1 from the My Team tab, I now have the ability to schedule conversations on their behalf with a different list of participants (see below).
![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/55e31977-d33f-4866-b6b9-be40d235a6a0)

As Executive1, I should only have the ability to set up a conversation between myself and my direct reports. So, when viewing Supervisor1's profile, I should only be able to set up a conversation that includes Executive1 and Supervisor1.

- [ ] The view function for open conversations is also not functioning quite right. If I click on an open conversation that I am not a participant in (i.e. between Supervisor1 and Employee1) then I should only be able to view, not add comments or sign off. Currently, it looks like I can do those things (see below).

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/9de871bf-f047-44d6-828e-4e937fbe0784)

There are also seems to be an issue with displaying content such as the Suggested Discussion questions and the sign-off info at the bottom (note the exclamation marks rather than participant names). We had this issue before and Dennis was able to troubleshoot.

Please take a look through and let me know if you have questions. Happy to set up a time to chat. Thanks!

**Comment by Kousthubha-M** [comment]
@Travis-A-Clark Understood! Will look into these first.

**Comment by Kousthubha-M** [comment]
@Travis-A-Clark Fixed the above items. Please have a look when you have time.
