### ISSUE TITLE
ODS - Org Hierarchy Data and End Points

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#384]
Ensure that all org hierarchy data required to create the org "tree" view and the HR / System Admin drill down functions is being pulled into the ODS and that the Performance platform has access to these end points.

**Comment by r3n3941m3** [comment]
New End point created for a new data set that includes the OrgHierarchyKey and ParentHierarchyKey against the Department ID

**Comment by r3n3941m3** [comment]
Data Extract from the New End Point Data validated. 

Notice from the sample filtered Data from BC Pension Corp Tree:
1. Hierarchy Structures in Level 2 are not PS DeptIDs. They are DW specific tree structure.
2. Level 3 Executive is not a PS DeptID and is directly under Level 1. It skipped Level 2.
3. Level 4 Executive is not a PS DeptID and is also a DW specific tree structure.
4. Level 5 are the actual PS DeptIDs.

Attached:[https://app.zenhub.com/files/329107952/e57b2e9c-07cd-45b4-a6bf-e5ba58e2ad71/download](https://app.zenhub.com/files/329107952/e57b2e9c-07cd-45b4-a6bf-e5ba58e2ad71/download) Dept Org Hierarchy List Review (Data Set format #2).xlsx

**Comment by r3n3941m3** [comment]
This Issue is pending testing from Dennis to try to access the data extract from the new Data Endpoint created.
