### ISSUE TITLE
As a supervisor, I want a dedicated Team Goals page in the My Team area to organize shared goals and goal banks.

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#386]
- [x] Sub navigation for Team Goals added under My Team heading.
- [x] Team Goals has tabs for Share My Goals and Team Goal Bank (note new designs below).
- [x] Remove Share My Goals and Add Goal to Bank action buttons from top right; remove current Goal Bank tab from My Team landing page (moved under Team Goals page).

**Share My Goal page**
- [x] See new design below with status drop downs and shared with functionality in a card format similar to My Current Goals area.

- [x] Also add text at top: "By default, all of your goals are private. Use the page below to make goals visible to selected employees. This lets team members know what you are working on and may serve as inspiration for team members' own goals."

**Goal Bank Page**
- [x]  Change name to Team Goal Bank
- [x] Add text at top of page: "Create a goal for your employees to use in their own profile. Goals can be suggested (for example, a learning goal to help increase team skill or capacity in a relevant area) or mandatory (for example, a work goal detailing a new priority that all employees are responsible for). Employees will be notified when a new goal has been added to their Goal Bank."
- [x] Note new design; similar to My Current Goals

**Comment by phoebesolomon** [comment]
![Team Goals _ Share My Goals.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/199e6615-f07c-4dce-9b26-3e1db32d61f8)

![Team Goals _ Goal Bank.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/195738eb-249f-4a39-be94-d150076d017e)

**Comment by Travis-A-Clark** [comment]
Hey @phoebesolomon I think this looks good. One suggestion: perhaps move the private/shared toggle above the Share With drop down since the toggle needs to be switched before the drop down becomes active. Thanks!

**Comment by Travis-A-Clark** [comment]
@phoebesolomon 

**Share My Goal page**
- [ ] Can we put the private/shared toggle above the shared with drop down list? Also, can we make it more obvious what position the toggle is in and what it means? Thinking maybe "Private" on the left of the toggle and "Shared" to the right of the toggle with a highlight to show which side is currently selected?

- [ ] Also add text at top: "By default, all of your goals are private. Use the page below to make goals visible to selected employees. This lets team members know what you are working on and may serve as inspiration for team members' own goals."

**Goal Bank Page**
- [ ]  Change name to Team Goal Bank
- [ ] Add text at top of page: "Create a goal for your employees to use in their own profile. Goals can be suggested (for example, a learning goal to help increase team skill or capacity in a relevant area) or mandatory (for example, a work goal detailing a new priority that all employees are responsible for). Employees will be notified when a new goal has been added to their Goal Bank."

**Comment by phoebesolomon** [comment]
Share My Goals:

![Team Goals _ Share My Goals - Part 1.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/8aef6ea2-d8f9-4ca7-aaf5-3bac39f35b4d)

![Team Goals _ Share My Goals - Part 2.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/4d5cd354-9d71-4bbf-9935-e7ee5fd273e8)

![Team Goals _ Share My Goals - Part 3.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/717f658b-25e5-4785-907c-5439ae0c569a)

Team Goal Bank:

![Team Goals _ Goal Bank.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/62d7a3e7-46eb-4873-ab0b-7b9614ce7b95)
