### ISSUE TITLE
As a supervisor, I want a dedicated Team Conversations page in the My Team area to organize and complete conversations with my direct reports.

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#387]
- [x] Add Team Conversations sub-navigations below My Team page.
- [x] Mimic Conversations tab functionality already in existence (templates/set up, open, and completed).
- [x] Introduce search/filter functionality for open and completed conversations so supervisors can easily find conversations by employee, topic, or date.
- [x]  Include only conversations with direct reports in this area; conversations with one's own supervisor will be organized and completed in the original Conversations tab.

**Comment by phoebesolomon** [comment]
![My Team Dashboard.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/8942f419-73da-4588-9002-15374cee6704) 
![Team Conversations Tab - Templates.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/c9de576d-2af4-46bb-9d3d-7a74e09db764)
![Team Conversations Tab - Open Conversations.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/bb8de218-7d3d-436c-9dd5-61a447a6494d)
![Team Conversations Tab - Completed Conversations.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/ebb9e071-40b6-42d1-9687-d31bc142101a)

**Comment by Travis-A-Clark** [comment]
@phoebesolomon Looks good! Can we make the date search a date range rather than a specific date? Thinking that supervisors might want to see all conversations in a past month, or year, or whatever rather than knowing exactly what day the convo took place. Otherwise good to go. Thanks.

**Comment by Travis-A-Clark** [comment]
@phoebesolomon Also, just realized we won't need the date filter at all on the Open Conversations page since dates are only associated with sign-off. We have removed the date scheduling aspect for the time being. Thanks!

**Comment by Travis-A-Clark** [comment]
@phoebesolomon thinking through all the lock/unlock stuff I think it actually makes sense to include a lock/unlock icon along with the view icon for completed conversations. Open conversations can be viewed or deleted (until signed). Completed conversations can be viewed only (need to be un-signed and moved back to Open Conversations to be edited or deleted). Completed conversations could have a lock icon that is "unlocked" for two weeks after sign-off is complete and then the icon switches to "locked". Mouse over for the icon: "Participants have two weeks from initial sign-off to re-open and edit the content of this conversation record. After that, a request must be made to your HR Admin to unlock the record."

Repeat this for the employee view of Conversations as well (the original conversations page).

**Comment by phoebesolomon** [comment]
@Travis-A-Clark noted. Thanks

**Comment by Travis-A-Clark** [comment]
@phoebesolomon Just remembering that we also created a notifications tab for the My Team Page (ticket #63). Let's add this as an additional sub navigation item here for consistency in design. Perhaps also updated #63 to reflect that new sub navigation design. Thanks!

**Comment by phoebesolomon** [comment]
![Team Conversations Tab - Templates.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/fc1227c2-79f9-4548-8c75-0242e64ad081)

![Team Conversations Tab - Open Conversations.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/05704108-4dd9-4bbe-a708-500a78de46b9)

![Team Conversations Tab - Completed Conversations.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/881bc1d7-7df4-449c-9542-93b1daf7c7e1)
