### ISSUE TITLE
Create a Data Scoping Documentation for the data to be migrated to the new MyPerformance Database

### ISSUE THREAD

**Issue by r3n3941m3** [bcgov/performance#389]
Line up a documentation to identify the features that needs to be moved to the new My Performance Database

**Comment by Travis-A-Clark** [comment]
Hey @anjuyadav22 I’m using ZenHub in GitHub, [click this link](https://app.zenhub.com/workspaces/performance-development-60020b0a13a09c0014af2469/board) to join my workspace and see other features available in GitHub or [download the ZenHub extension](https://www.zenhub.com/extension) and sign up with your GitHub account. 
  _Posted using [ZenHub](https://www.zenhub.com)_

**Comment by Travis-A-Clark** [comment]
I think we are taking MyPerformance decommissioning activities out of the PDP workflow. Separate JIRA to conduct work.

Closing ticket.
