### ISSUE TITLE
As a System Admin I want information in the app, including batch notifications, to process at regular intervals (chron jobs)

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#393]
Work with Kunal and anyone else required to get the chron jobs set up in OpenShift.

**Comment by Travis-A-Clark** [comment]
@Kousthubha-M to update following meeting with Kunal

**Comment by kkapoor-fresh** [comment]
@Travis-A-Clark Sure. I will have that story incuded in the roadmap for Performance. Please correct me if I am wrong here , I believe the script  for sending the  email  is already there , we basically need this to be scheduled to run on a weekly basis.

**Comment by Travis-A-Clark** [comment]
@kkapoor-fresh You are correct, @jp-Telus developed the script to send the email notifications. We just need the option to be able to hold them and send them on a schedule rather than immediately. Thanks!
