### ISSUE TITLE
Create New Goal Modal Updates - Feb 2022

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#398]
**All Text Boxes**
- [x] Allow lists, bullets, line breaks, etc. in text.

**Goal Type**
- [x] Make drop down same format as "Status" drop down where the info mouseovers are directly next to the drop down menu items.
- [x] Change description of Career Development goal to: "Career Development Goals are not required but are desirable in order to improve and grow. They tend to be medium- or long-term."

**Goal Description**
- [x] Combine the What, Why, and How sections into one larger text box called "Goal Description". Have a line of text beneath the Goal Description header that says: "Each goal should include a description of **WHAT** you will accomplish, **WHY** it is important, and **HOW** you will achieve it." Bold the words "what", "why", and "how" in the sentence and keep the info tip mouseover after each of them just like current format.

**Supporting Materials**
- [x] Replace the title "Supporting Materials" with an information / help icon (perhaps a question mark) and the direction to "Click here for goal setting resources and examples (opens in new window)".

**Save Function**
- [x] If any data has been entered and the user attempts to close the Create New Goal modal, throw warning: "If you continue you will lose any unsaved information. Continue/Cancel."

**User Testing Results**
If interested, check out results on Creating a New Goal.
[https://app.zenhub.com/files/329107952/3e406287-d950-4e84-a28c-0686973ce3f5/download](https://app.zenhub.com/files/329107952/3e406287-d950-4e84-a28c-0686973ce3f5/download)

**Comment by phoebesolomon** [comment]
![New Goal Modal.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/8425dd6e-7b1b-4d16-aaa0-64bf9a147500)

![New Goal Modal - Career Development Hover.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/3a034c16-832b-42b9-8689-3f90d17da085)

![New Goal Modal - Need Help.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/7fa94690-ce67-4dfe-a89f-d9a4c890bb23)

![New Goal Modal - Close Without Saving.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/570a6be0-6f1b-4d33-b715-4ba9614ce1f3)

**Comment by phoebesolomon** [comment]
![New Goal Modal.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/1109f522-8011-40f7-a655-6882bd429fd5)

![New Goal Modal - Career Development Hover.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/95f2d6ed-d9b6-49ba-be03-457ee4027b50)

![New Goal Modal - Need Help.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/b607953f-a4b8-4e47-a58d-a4e598395539)

![New Goal Modal - Close Without Saving.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/fe5ca8c8-d2ac-42b1-adc1-845443ff876d)

**Comment by Travis-A-Clark** [comment]
@phoebesolomon One quick note: can we still have the info tooltips after the What, Why, and How words in the Goal Description section? I think making it clear the definition and example for each is still really important. Thanks!

**Comment by Travis-A-Clark** [comment]
@Kousthubha-M I know you've started working on this so I am assigning to you. Please review the various items in the ticket description and mark the ones you have already done.

Also, once you have changed the create new goal modal, we will have to change the goal fields in all the other areas to match. The expanded goal card, adding a goal to the goal bank, the goal bank display, etc. will all need to move from a "What, Why, How" format to a "Goal Description" format. I can create another card for that if needed.

**Comment by Travis-A-Clark** [comment]
@Kousthubha-M Only one small change that isn't quite right:

Change description of Career Development goal to: "Career Development Goals are not required but are desirable in order to improve and grow. They tend to be medium- or long-term."
