### ISSUE TITLE
Current Goals Page Update - Feb 2022

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#399]
**Navigation Heading**
- [x]  Change "Goals" to "My Goals" in left hand navigation bar and section header

**My Current Goals view**
- [x]  Add information / help link (possible question mark icon): "Click here to access goal setting resources and examples (opens in new window)."
- [x] A few comments suggested that the red colour for the "Not Met" status was too harsh. Can we choose another colour (purple maybe??). Whatever looks okay and is not red.

**Goal Cards**
- [x] Minimize footprint to allow more cards to be displayed per page. 
- [x] Remove the "What" description and just keep the goal title.
- [x] Add indication of Goal Type
- [x] Align all action buttons (status, view, delete) in one place
- [x] Shorten "Goal created by" to "Created by"
- [x] Display who actually created the goal. For example, if I pull a goal from the Goal Bank created by Marlo Waldie and add it to my Current Goals, it should still show as Created by: Marlo Waldie even though it's in my profile now.

**Full Goal view**
- [x] Add submit (rather than ctrl+enter) and edit buttons. Time stamp submit and edit actions.
- [x] Allow line breaks, lists, bullets, etc in comments
- [x] If comment entered but not submitted and user tries to navigate away from page throw warning: "If you continue you will lose any unsaved information. Continue/Cancel"
![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/98f48a37-5875-42cc-b763-993d6ad83782)

**Comment by phoebesolomon** [comment]
**Navigation Heading / My Current Goals View / Goal Cards:**

![My Goals Part 1.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/6e314464-dd14-4275-9cad-680b4e491b57)

![My Goals Part 2.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/9ceaed11-1abb-4c8c-a32a-b9a99ff03732)

**Full Goal View:**

![Comment Submit Button - Inactive.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/186ed45d-e5c5-4d26-aef5-511c3b2b565a)

![Comment Submit Button - Active.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/93f0011a-9908-4b30-8d19-7a422d151c62)

![Continue without submitting.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/d7cdb535-6fea-4f68-85e4-29bb5633e83e)

Editing comment / time stamp:

![Edit Comment - Part 1.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/b09b0ae2-7ccf-469e-8e09-6dafd8e61681)

![Edit Comment - Part 2.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/146e35bf-b6be-4dc7-b41a-97c6974eb225)

![Edit Comment - Part 3.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/f9d7ec98-4d58-451a-93ea-d42500092f87)

![Edit Comment - Part 4.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/b17de7fb-7bef-4cc1-a157-7cf5cb2257f6)

**Comment by Travis-A-Clark** [comment]
@Kousthubha-M There are four items left on this ticket (see unticked boxes above). Can you take care of these. Thanks!

**Comment by Kousthubha-M** [comment]
@Travis-A-Clark Sure, will do!

**Comment by Travis-A-Clark** [comment]
@Kousthubha-M 
- [ ] If comment entered but not submitted and user tries to navigate away from page throw warning: "If you continue you will lose any unsaved information. Continue/Cancel"

If I try to leave, I get the message which is good. In the app can we change "may lose" to "will lose" just to be clear? Also, if I "Cancel" to stay on the page, I am unable to submit my comment. When I hit submit, I receive the same warning message again even though I'm not trying to go anywhere.

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/ae20f518-4ad7-43a0-bfc6-a0238e434c85)

**Comment by Travis-A-Clark** [comment]
@Kousthubha-M Functionality for the comments works now. Thanks! Can we add the same logic around throwing the warning message when someone is in the edit screen for a goal? Currently, if I go in to edit a goal, I can "Go back to list" or navigate away and I lose the changes I made if I haven't yet saved.
