### ISSUE TITLE
My Supervisor's Goals Update - Feb 2022

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#400]
**My Supervisor's Goals page**
- [x] If no goals shared, change message at top to: "Your supervisor is not currently sharing any goals with you." If goal(s) shared, keep message as is.
- [x] Just like My Current Goals update (ticket #399), minimize the footprint and update content of goal cards.

**Goal View page**
- [x] Add ability to copy goal from within the full goal view screen, not just the card view.
- [x] Add submit (rather than ctrl+enter) and edit buttons to comments area. Time stamp submission and edit actions.
- [x] Allow line breaks, lists, bullets, etc in comments
- [x] If comment entered but not submitted and user tries to navigate away from page throw warning: "If you continue you will lose any unsaved information. Continue/Cancel"
![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/0de5bd15-9bb5-46bd-b199-f6e019c6449b)

**User Testing Results**
Check out results on viewing and copying supervisor's goals.
[https://app.zenhub.com/files/329107952/98c6713a-efa7-4928-99cd-d400671932bb/download](https://app.zenhub.com/files/329107952/98c6713a-efa7-4928-99cd-d400671932bb/download)

**Comment by phoebesolomon** [comment]
My Supervisor's Goals Page:

![My Supervisor's Goals - Not Shared.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/abdeea95-3c99-4eee-8297-5ea931c3c46e)

![My Supervisor's Goals - Shared.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/e6f440fc-4fd0-4957-8e75-7f1fa6e808d4)

Goal View Page:

![Copy Supervisors Goal - Part 1.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/a7673648-bb48-4a64-9dc6-27f2469f814e)

![My Supervisor's Goals - Shared.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/8befeafa-a6ec-47e4-9dd5-664e7dae695e)

**Comment by Travis-A-Clark** [comment]
@Kousthubha-M There's just one small thing left to do here (the message thrown if the window is closed before changes are saved). Can you take care of this? Thanks!

**Comment by Kousthubha-M** [comment]
@Travis-A-Clark Yeah, for sure!

**Comment by Travis-A-Clark** [comment]
@Kousthubha-M Same issue here as ticket #399. After I type anything in the goal comments, I get the warning message about losing content if I leave the page no matter what action I try to take (submit, close window, back to list, etc).

**Comment by Travis-A-Clark** [comment]
@Kousthubha-M Realizing that the employee should not be able to delete the supervisor's goal. I should have caught that before. Sorry! Please remove the delete icon and functionality from this tab.

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/88c701c4-277e-4f16-9723-ed4d1d17cce8)
