### ISSUE TITLE
Goal Bank Update - Feb 2022

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#401]
- [x] Add description at top that says: "The goals below have been created for you by your supervisor or organization. Click on a goal to view it and add it to your own profile."
<br>

- [x] Change order of search/filter to: Goal Title, Goal Type, Date Added, Created By, Mandatory/Suggested. Line up with column headings below if possible (not required).
<br>

- [x] Populate Created By drop down with names of all creators in the list below. If no goals in Goal Bank, list is empty.
<br>

- [x] Reintroduce functionality to add goal directly from list (rather than having to click to view first) as well as adding multiple goals at once (check boxes and add all). Some users noted that there supervisor might put 3 or 4 mandatory goals in that the whole team needs to do and they'd like to be able to search for them and then add them all at once.
<br>

- [x] Limit goals to the appropriate audience. During user testing, all goals added to the Goal Bank by all users were visible to all employees. They are only meant to be visible to the users selected by the goal creator, not to everyone else. (See screen shot below for example of what users saw during testing).
![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/54f70519-bc3b-4ac3-ae41-fbd3b2916688) 
<br>

**User Testing Results**
View results related to adding goals from Goal Bank.
[https://app.zenhub.com/files/329107952/ae0b68c6-8c22-4382-84ea-72c6957eb2a3/download](https://app.zenhub.com/files/329107952/ae0b68c6-8c22-4382-84ea-72c6957eb2a3/download)

**Comment by phoebesolomon** [comment]
![Goal Bank Revised.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/139e8b0c-541a-41b3-bf9c-3613f4ad920b)

![Add Goals from Goal Bank.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/2f0cec84-b441-4f37-aac3-1948bb282f76)

![Created By Dropdown.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/364aa402-61cf-422f-8fa2-24ce3b3790aa)

**Comment by Travis-A-Clark** [comment]
@Kousthubha-M Hoping you can take the rest of this ticket so Dennis can return to his work on the System Admin page. Let Dennis and I know if you have any questions. Thanks!

**Comment by Travis-A-Clark** [comment]
@Kousthubha-M We are getting closer on this! Still some things to fix:

- [ ] The filter for goal type isn't aligned correctly. When you search for career development goals it displays learning goals. Can you make sure that the filter and the results match?
- [ ] Can we make the drop down filter selections automatic rather than having to click "filter" after selecting from the drop down menu?
- [ ] The list of goals only displays the ones that should be available to the employee which is great. The "Created By" drop down displays the names of any one who has created a goal in the system still; not just the ones that created goals that are visible that that employee. Can we fix this?
- [ ] Can we move "Measures of Success" in the goal card above the date fields?
- [ ] Clicking "Add Goal" in the goal card doesn't do anything; the card remains open and the goal is not added to My Current Goals.
- [ ] Selecting goals from the list and using the "Add Selected Goals to your Profile" returns an error message:
![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/33fdfaea-597a-4194-97a0-8c8d75f62506)

**Comment by Travis-A-Clark** [comment]
@Kousthubha-M All the fixes look good. Thank you! The only thing that's not working correctly is the Date Added filter. When I select a date range and click "apply" nothing happens. I need to select one of the other drop down options (goal type, or created by) before the date added filter takes effect. See below.

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/16ac6993-af74-46bf-b4b1-a58e4af5e30d)
