### ISSUE TITLE
Work with B.I. team to develop historical and comparative reporting capabilities

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#409]
- Historical reporting using the org hierarch: triangulating where an employee was at a point in the past so that reports are accurate
- Synching access for reporting permissions in the Performance app itself and in the BI warehouse; if we grant someone HR admin access in the platform it won’t mean much if they are still blocked from seeing reports or accessing dashboards form the warehouse.
- Determining how the real-time reporting shows up in the platform; we need a basic current snapshot available in platform; additional detailed reporting or historical comparisons can be done in the warehouse or wherever required.

**Comment by Travis-A-Clark** [comment]
Met with Stu Hemerling from B.I. team on March 2. Sent him follow up documentation on March 4. Waiting to hear back on next steps.

**Comment by Travis-A-Clark** [comment]
Meeting with Stu again next week. In the meantime, came up with plan to develop in-app reporting to meet MVP requirements at launch. See ticket #436.

**Comment by Travis-A-Clark** [comment]
Follow-up meeting with Stu on March 17.

**Comment by Travis-A-Clark** [comment]
Stu to set up meeting with Justin, Dennis, James, and me. Need to discuss additional time stamping an "as at date" fields for performance data tables to assist with historical and comparative reporting. Want to have the data tables collecting all necessary info and stable before pilot.

**Comment by telusdcinco** [comment]
Created the Data Push to ODS and deployed to Dev.  Triggered the process to send the data.

php artisan command:ExportDatabaseToBI
