### ISSUE TITLE
Branding and Logo Creation for new performance app

### ISSUE THREAD

**Issue by phoebesolomon** [bcgov/performance#416]

**Comment by Travis-A-Clark** [comment]
Jen and Travis are meeting with a rep from government comms on March 14 to seek clarification on any branding and colour scheme requirements.

@phoebesolomon do you want to drop a few examples of the logo and colour schemes in here for reference? I can show them to the government comms person as an example if they want to see what we are suggesting. Thanks!

**Comment by phoebesolomon** [comment]
[https://app.zenhub.com/files/329107952/07ac809c-2468-4dc3-bacb-63704c185b08/download]

**Comment by phoebesolomon** [comment]
@Travis-A-Clark I've attached all the branding and logo options below - I have also sent Jen these same items in the form of a zip file as well if that's easier.

 ![Option 1 Logo -  Revised.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/c49d4095-4c3d-4065-bd3c-1194d6930b3b)

![Branding Colours - Option 1.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/c9738bc3-5912-4dd6-bf22-55718dab0395)

![Branding Colours - Option 2.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/ec9160d8-a664-43f7-a54c-929e3708ccfe)

![Branding Colours - Option 3.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/136f90c5-c037-4da0-9ed5-b23ea7a29f2b)

![Branding Colours - Option 4.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/3433092b-e651-42f4-82cb-04d0b418ffd4)

![Branding Colours - Option 5.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/7f3daff4-6043-44ed-801a-40b863694920)

![Option 1 Logo -  Revised.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/a343c7c0-d2fb-43ec-ab1a-9768c7b5261e)
