### ISSUE TITLE
Create generic Performance Development email address and inbox

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#420]
Set up Performance.Development@gov.bc.ca 

Grant access to Travis and Jen.

**Comment by Travis-A-Clark** [comment]
@Abuchana Would you be able to help get this mailbox set up? Let me know if you have any questions. Thanks!

**Comment by Abuchana** [comment]
@Travis-A-Clark you bet I can.

**Comment by Travis-A-Clark** [comment]
iStore request was submitted March 7. Followed up with CWS admin March 23.
