### ISSUE TITLE
ASAP - Fixes for Testing

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#424]
**Create New Goal**
- [x] The information in  the "What" section is not being recognized. Even when it's filled in I still get the error message and it won't let me save. I also can't create a different goal by closing out and starting again. I'm stuck. Caching issue? See example below.

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/62f12def-d2b6-47fb-9f9e-05cec14013b1)

**Seed Data**
- [x] As in last round of testing, we need to seed data in My Supervisor's Goals, Goal Bank, and Open Conversations.

**Team Conversations**
- [x]  Update page header from My Conversations to Team Conversations to match navigation.

**Team Goals**
- [x] When no goals to share: add space before "create new goal" link. It's running together with the word Please in front of it.

**My Team**
- [x]  When I click on the date for Next Conversation Due for an employee it takes me to their profile but lands me on their current goals page. Can this land on the Conversations page instead? So, if I click on the number of active goals, it takes me to their goals page, and if I click on the the conversation due date it takes me to their conversations.

**Conversations**
-  [x]  After I create a conversation, it automatically sends me to the "Open Conversations" tab of My Conversations. Even if I have set up the conversation with an employee. So the conversation is actually under "Open Conversations" of the Team Conversations area. As a result it takes me to a blank page.

 **My Team**
- [x] The My Team navigation cannot be closed. Once you expand it, it stays expanded. When you click on it again, it just reloads in expanded format.
- [x] We don’t need “Notifications” or “Performance Statistics” in the left hand nav bar for testing
- [x] We don’t need “Performance Statistics” or “Goal Bank” on the My Team header

**My Team - Employee View**
- [x] As a supervisor, when I click on an employee from the My Team page to view their profile, I can set up a  conversation with them. However, when I click on that conversation to add comments or sign-off, I am given the employee permissions and access rather than the supervisor permissions and access. See example below (as a supervisor, I should be able to enter comments and sign-off the supervisor areas, not the employee areas).

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/3d377118-497f-4607-9c10-1fd916355bdd)

**Team Goals - Share My Goals**
- [x] Status defaults back to private after you navigate away from the share my goals page; cannot actually share with employee

**Create New Goal Modal**
- [x] The formatting toolbar isn’t available here (seems functional in edit mode and providing comments); can we add?
- [x] If possible, can we expand the default size of the What, Why, How, and Measures of Success text boxes? Especially after we add the formatting toolbar, it may look very cramped.

**Comment by telusdcinco** [comment]
Partial changes pushed to master repo, pending deployment.

**Comment by Kousthubha-M** [comment]
Pushed the changes related to My team & conversations. Deployment to test, dev is complete
