### ISSUE TITLE
As a supervisor, I want a central location to see conversations with my team and conversations with my own supervisor.

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#431]
Currently conversations with my supervisor appear under My Conversations and conversations with my team appear under Team Conversations. Can we create "Conversations with my Supervisor" and "Conversations with my Team Members" areas in the Open and Completed tabs of My Conversations? Use the logic KK developed to split the conversations based on what role you are playing when setting up the conversation but rather than have them live under Team Conversations and My Conversations, we split them all up under My Conversations.

- [x] Create "Conversations with my Supervisor" and "Conversations with my Team Members" sections of the Open Conversations tab of the My Conversations page.
- [x] Create the same sections in the Completed Conversations tab of the My Conversations page.
- [x] Remove the Team Conversations page from the left navigation.
- [x] Make the "Conversations with my Team Members" sections visible only if the user is a supervisor (direct reports or shared employee).

**Comment by phoebesolomon** [comment]
@jchow11 here is the low-fi version of the required designs for your reference :) 

![Open Conversations.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/15b3db9b-7bdb-4aac-839b-2832fadec70c)

![Completed Conversations.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/99f121cb-845d-41a9-8261-1f8b0c101955)

**Comment by Travis-A-Clark** [comment]
@phoebesolomon @jchow11 Just a note to mention we should make sure to incorporate the lock / unlock logic from tickets #376 into the design. There's an extra piece of text up top and the lock icon on all completed conversations.

**Comment by jchow11** [comment]
![Team Conversations Tab - Completed Conversations.jpg](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/cc7c7c0c-a3dd-4ef1-b831-6ef77603f0c4)![Team Conversations Tab - Open Conversations.jpg](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/bf712e10-deba-43f9-8ca7-6bb2931e5c37)

**Comment by Travis-A-Clark** [comment]
@jchow11 Looks great. Much appreciated! I will re-assign to Kousthubha for his dev estimate.

**Comment by jchow11** [comment]
![My Conversations Tab - Completed Conversations](https://user-images.githubusercontent.com/98112490/158642875-2c34960e-b41e-40fd-89a5-ac01d071f783.jpg)
![My Conversations Tab - Open Conversations](https://user-images.githubusercontent.com/98112490/158642892-cdd7daf4-8bc4-4dc6-b298-363b441d62c7.jpg)

@Travis-A-Clark the header should actually say "My Conversations" instead of "Team Conversations". Here are updated wireframes to reflect this. Thanks.

**Comment by Travis-A-Clark** [comment]
@jchow11 Good catch! Thanks for that. Can you please delete the previous versions and just leave the latest in the ticket for Kousthubha? Cheers!

**Comment by Kousthubha-M** [comment]
@Travis-A-Clark All the items in the ticket are complete. Tested locally. Changes currently are in my local. Will move to "Ready for Review" when the deployment is done.

**Comment by Travis-A-Clark** [comment]
@Kousthubha-M This is looking really good! Big improvement from having them in two different areas. Two things:
- [ ] For the search functionality on both Open and Completed conversations tabs, let's change the employee name from a drop down to a free text that you can type in and hit enter (like the goal title search on the goal bank). It's possible that an employee will be looking for a conversation that they signed off with a previous supervisor years ago, so that person may not appear in their drop down list of current supervisors. Let's also go with the same date search option on the Closed conversations page as the Goal Bank as well (single nav with from and to dates for Date Completed).
- [ ] The only glitch I have found in the functionality so far is that, as Supervisor 1, I do not have access to fill in any of the comments boxes in the open conversations with my employees. They are all greyed out (see below). Everything seems good for entering info in the the open ones with my own supervisor.
![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/a16fa8fc-4c31-4ae5-908a-c65ccb44d885)
