### ISSUE TITLE
As a supervisor, I want to be able to add a goal to the Goal Bank from the My Goals area

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#434]
Currently the supervisor only sees goals suggested to them in the Goal Bank of the My Goals area. They have to go to the Goal Bank area of the My Team - Team Goals to add a goal for their team. Let's combine the two functions in the My Goals area and deleted the My Team - Team Goals tab.

- [x] Divide the goal bank into two sections: the top section is the current view and remains available to all employees. The bottom section is the message and functionality currently available in My Team-Team Goals-Goal Bank and is only available if the user is a supervisor (direct report or shared employee).
- [x]  Ensure goal creators can edit the Goal Bank audience after they create the goal in case they want to share with more/less users.

**Comment by jchow11** [comment]
![My Goals _ Goal Bank.jpg](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/49538612-5598-4cdf-9aa8-1e7761741fb3)![My Goals _ Goal Bank _ Add Goal To Bank.jpg](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/20d8d955-1619-467d-b620-5acf500f7acf)

**Comment by jchow11** [comment]
@phoebesolomon for your review.

**Comment by jchow11** [comment]
![My Goals _ Goal Bank.jpg](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/8d6093f0-f596-4f0c-946a-1240a8967e5e)![My Goals _ Goal Bank _ Add Goal To Bank.jpg](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/05db3d7f-546a-4edf-ab6d-d51f8b39a95b)

**Comment by jchow11** [comment]
@phoebesolomon for your review.

**Comment by Travis-A-Clark** [comment]
@jchow11 @phoebesolomon Awesome! Will assign to KK for dev estimate. Thanks!

**Comment by Travis-A-Clark** [comment]
@Kousthubha-M After thinking about it some more, I think it would be better to change the "Share with" wording for the Goal Bank to "Available to". I want to make it different than the goal sharing process for supervisors and I think using the word share in both places will be confusing. Can you please change the "Share with" to "Available to" in the Add Goal to Bank modal and in the Team Goal Bank goal cards? Thanks!

**Comment by Kousthubha-M** [comment]
@Travis-A-Clark Are we going with "Audience" or "Available to"? I see "Available to" in one of the emails this morning.
