### ISSUE TITLE
Sample mockups of app interface with new performance development branding applied

### ISSUE THREAD

**Issue by phoebesolomon** [bcgov/performance#445]
- [ ] Employee/Supervisor
- [ ] HR Admin
- [ ] System Admin

**Comment by jchow11** [comment]
![Colour Overview.jpg](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/1e96f5ea-ecff-49ec-8e91-c5bcb16ff6ee)![Menus.jpg](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/789bdcaa-da81-4e0d-8f43-8de833aa86b2)![Colours.jpg](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/aab19a68-4001-466f-bcba-108914b14c66)![Icon.jpg](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/61a6b36b-6eba-4cf5-93df-b4f8de9aec5e)![Button.jpg](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/2a75f6d4-737c-4a6f-972a-204b4b02fce7)![Branding - Goal Bank.jpg](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/2292f82c-c67f-4a9b-bc66-2122960eb8ee)![Branding - My Goals.jpg](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/675fe6a7-ed24-4f17-97ff-dbb0f6a48daf)![Branding - HR Admin.jpg](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/d3fbfe7c-73b6-47b2-b272-d3e47a6ad11f)![Branding - Create New Goal.jpg](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/ffed622f-4f93-4112-a4e5-b23873743a59)

**Comment by jchow11** [comment]
![Colours.jpg](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/661132f9-d10d-4de3-8058-35fcd930b6dc)![Icon.jpg](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/eeeda31d-baff-4e39-beb6-8dfbb85bfd16)![Button.jpg](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/50457a81-c416-409c-88fe-56b72f99aa57)![Menus.jpg](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/b798f29e-8126-43f5-990b-841e390494b4)![Colour Overview.jpg](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/bff51ee9-310a-497f-8452-6d4f039a885f)![Branding - EmployeeSupervisor.jpg](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/568e54d3-a5aa-47b2-8996-4ee1b66444ac)![Branding - Goal Bank.jpg](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/9a95d718-ab44-4035-9493-809f56493753)![Branding - HR Admin.jpg](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/2b18aecf-6626-4320-86da-baff2265e38f)[Uploading... Branding - Sys Admin.jpg]

**Comment by jchow11** [comment]
![PDP Logo.png](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/e6b000b2-27cb-4f6d-b901-ce9d307f9542)

Logo.

**Comment by jp-Telus** [comment]
_Work Done_

- New logo shown on login page (background color changed) and sidebar. small version logo display on mini sidebar display
- The user profile picture on main sidebar will be disappeared on mini sidebar 
- Sidebar background color, active/hover menu items
- The text color tab bar per standard, bold on current active tab 
- BCSans font installed and applied
- Component colors 

This changes was pushed to Rep,  ready for deployment and test

**Comment by telusdcinco** [comment]
The changes have been deployed to Dev.

Looks very good.  Kudos to Jordan & James!

**Comment by jp-Telus** [comment]
Both the logo size and menu text color was changed per recommendation, wait for the upcoming DEV deployment. Thank you.
