### ISSUE TITLE
As an employee, I want to be able to add tags to my goals to indicate the topic of the goal more clearly.

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#454]
**Create New Goal**
In addition to the goal type (work, learning, career development), let's add the option to allow employees to tag their goals with descriptors from a pre-populated list. So, for example, we could create a list of goal tags like: Finance, Technology, Communications, Human Resources, etc. Then, when I create a work goal, I could tag that goal with "Finance" and that would become a searchable field. Like the "Labels" function here on ZenHub. This will help a lot with reporting capabilities. Without the tags, we would need to rely on keyword searches from the title or description fields.

**Goal Cards**
The tags would be visible and editable on the expanded goal card just like the other fields.

**Comment by jchow11** [comment]
![New Goal Modal - Goal labels.jpg](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/2be8f1a2-b4a6-415d-bb76-b175a1476d09)![New Goal Modal - Drop Down.jpg](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/e7a9c2a7-d949-4c28-a174-7e3f2f1a67e2)![New Goal Modal - Selected Goals.jpg](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/e217d869-ffb4-45bf-971f-8b9e724b6f2a)![New Goal Modal - Expanded goal card.jpg](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/fe93dadc-430f-46cc-82c3-1131858bbd48)

**Comment by jchow11** [comment]
![New Goal Modal - Goal tags.jpg](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/ddb99d34-7759-44c0-9317-ec41e3409000)![New Goal Modal - Drop Down.jpg](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/0199d678-607b-4a5f-b114-3282102177fe)![New Goal Modal - Selected Goals.jpg](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/307ff4d1-747d-478d-bf6a-41bd26a24b8d)![New Goal Modal - Expanded goal card.jpg](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/d8ff6cc8-25e8-43f3-a38c-07b199fe8791)

**Comment by Travis-A-Clark** [comment]
@jchow11 Thanks for this! I think it looks good but would suggest that we don't add the colours to the tags; let's keep them text only. This list may end up being quite long once we finish populating it, so we my run out of distinct colours. I also don't want to confuse with the goal status (active, achieved, etc) that also have colours associated. Can you please remove and repost? Thanks!

**Comment by jchow11** [comment]
![New Goal Modal - Goal tags.jpg](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/62bd19a6-f113-452d-80a0-1373710aaef2)![New Goal Modal - Drop Down.jpg](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/66b385c8-742b-4ed8-830e-b40c17332609)![New Goal Modal - Selected Goals.jpg](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/b7ccb08d-bec3-4562-815a-5ef12845c80e)![New Goal Modal - Goal Detail.jpg](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/c11b8057-4f88-4477-9b6d-ed41cbc222cd)

**Comment by Travis-A-Clark** [comment]
@Kousthubha-M This is great! Can we implement the same drop down format that James has on the Create New Notifications tab for HR Admin (see below)? There's a drop down list but also a text box to help narrow your search. This will be helpful because I think the list of tags could end up being quite long.

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/c36baa0f-e5c4-47d0-8968-2f4964d2c389)
