### ISSUE TITLE
As a Sys Admin, I want to generate PDF files of employee records to respond to Freedom of Information requests

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#455]
We must be able to provide employee records when we receive a request through a Freedom of Information request. These requests are generally for a single employee over a set period of time. For example, we might receive a request for "All of Travis Clark's performance evaluations from date of hire to 2022". We need to design a quick and easy interface to allow us to pull just the records that we need and export them in PDF format.
<br>

Fields that I think we will need:
- Employee ID
- Date range
- Record type: a checkbox list to indicate whether we need active goals, past goals, open conversations, completed conversations, or all.
- Export option: single PDF or separate PDFs for each record (this may be dependent on coding options).

**Comment by Travis-A-Clark** [comment]
Current MyPerformance System process shown below. Must print to PDF one file at a time. Select "Printer Friendly", choose printer options, print or save single PDF.

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/2f1f9131-55ab-4ece-af62-feb5c7ea4865)
<br>

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/b05927f9-69d7-4b4e-9fd2-283810a98467)
<br>

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/baffccf0-0b2a-4032-968c-70e73f4d4bdf)

**Comment by jchow11** [comment]
![Sys Admin - Generate Records to Respond to FOI Requests Pt 1.jpg](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/e3943c54-11c2-46fe-98d7-c2e62f8875cb)![Sys Admin - Generate Records to Respond to FOI Requests Pt 2.jpg](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/01573702-bea9-45a7-9a69-eccce7ad64ba)

**Comment by Travis-A-Clark** [comment]
@jchow11 This looks good to me! We may need some alteration once we run it by the Dev team as I am not totally sure what our options are for exporting files. This is a great starting point for discussion though. Thanks!

**Comment by jizhaogit** [comment]
based on the chat with Travis, added some details:
1. add a new tab in the Statistics and Reports page name it "Performance Evaluation Records"
2. the records ONLY can be listed when user provides BOTH employee id and time range.

**Comment by jizhaogit** [comment]
@telusdcinco please help do the code review. thank you very much!

**Comment by telusdcinco** [comment]
@jizhaogit Looks good.  Please proceed with change.

**Comment by jizhaogit** [comment]
@steffipravasi @Travis-A-Clark For the current phase i ONLY open the report in the system admin's module.  and the output, for now, is only the single item output in HTML style.  let's chat about it to make the decision about the next step. thanks.

**Comment by Travis-A-Clark** [comment]
@jizhaogit A couple of comments:

1) I get a 500 Error whenever I try to access an active or past goal, so I can't see what the output looks like.
<br>

2) For the open and completed conversations, I think we can remove the "owner" field at the top. Can we also add date fields for when each of the sign-offs occurred (supervisor and employee)? The only other thing we will need to do is make sure that there is some branding (like the Performance Development Platform logo and colour scheme) as part of the output so that it looks consistent.
<br>

3) Let's rename the report to "Employee Record".
<br>

4) The completed conversations area appears to show each conversation twice. So, for Travis Clark in TEST, I only have three complete conversations in my profile:


![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/a8197568-4ce0-4790-90f3-9817121bb883)

But the report shows six complete conversations.

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/877a31cd-e518-4189-8b19-5114c5cac873)
<br>

5) Let's include the date for each row in the results as well.

**Comment by jizhaogit** [comment]
@Travis-A-Clark  
#1 500 error addressed. 
#2 "owner" column removed,  sign off time added, 
#3 report name changed to "Employee Record"
#4 duplicate records are cleaned from the list.

**Comment by jizhaogit** [comment]
1.  added "create at" column for active/past goals and open conversation table and added "latest signoff" in the complete conversation table.
2. moved the goal's description and measure of success to a separate area.

**Comment by Travis-A-Clark** [comment]
@jizhaogit I think the changes all look good! Can we add a message that comes up if the search criteria doesn't return any results for one of the selected areas (active / past goals, open / completed conversation)? So if I select all 4 areas and then enter a date range that doesn't return results in one of them it would still show the heading with a message that says: "There are no records for the employee ID and date range selected".

**Comment by Travis-A-Clark** [comment]
@jizhaogit When I click on the download, I don't get a PDF, just an HTML window without much formatting. Are we also going to have the bulk download option?

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/d4ab1842-8406-4a2d-b57a-0b6bdfa120ca)

**Comment by jizhaogit** [comment]
@steffipravasi ready for test. thanks!

**Comment by steffipravasi** [comment]
1) When I entered an employee id and hit the Search button without selecting the dates or Record type, site throws a 500 Server error
![Screenshot 2023-04-11 at 1.18.59 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/0bb52c14-2a6c-47ea-92ca-28786cca90a2)

**Comment by jizhaogit** [comment]
fixed detected issues. thanks, @steffipravasi. except for the following items:
#2  If Sys Admin selects Record type as Past Goal, can we hide the other record types which display error as 'There are no records for the employee ID and date range selected.' which is incorrect as it is not true. There are records to display for those record types, but are not displaying because they are not selected from the Record type field.
**need to check with @Travis-A-Clark  about the message content or hide the session when it is empty**

#6 Open conversation does not display the conversations with the Team members
**currently the page ONLY list conversations that role is employee**

#10 Missing completed conversations for user Rebecca Fontaine
**same as #6**

**Comment by steffipravasi** [comment]
1) Pass

**Comment by jizhaogit** [comment]
@steffipravasi for the active goal missed in your list. we are currently filtering the items with the **creation date**.  Since you created the goal today (04/12) but the query searches the items' create date which is less than "**2023/04/12 00:00:00**" it will not be listed in the result.  we can modify the query to search the date range to "**23:59:59**" for covering the current date.   thanks

**Comment by jizhaogit** [comment]
@steffipravasi  
1. the current date created item missing issue is addressed. 
2. past goal title is added back

**Comment by steffipravasi** [comment]
Facing some issues with the Completed conversations list: 
1) User: Shannon Baskerville (043323) has a supervisor Shannon Salter currently. I am guessing that Shannon had Julie Muir as her supervisor in the past. Cory Scott is an employee shared with Shannon. 
Issue: i) The employee record now displays completed conversations between Cory and Shannon ii) completed conversation between Shannon and Julie is missing from employee record. The date range I have eneterd is quite wide from 2020-01-01 to 2023-04-12
![Screenshot 2023-04-12 at 6.11.48 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/7851c241-1fe2-472d-ac77-643b9ecf58a9)![Screenshot 2023-04-12 at 6.11.59 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/94e673dc-7e66-42ec-8f2e-a27fc7bfb24b)![Screenshot 2023-04-12 at 6.20.12 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/3b2e239a-8de9-43e9-9481-febc48a48a31)

2) User: Rebecca Fontaine(056770) has 4 completed conversations with the supervisor Chad Hoskins but employee record shows only one. The date range I have eneterd is quite wide from 2020-01-01 to 2023-04-12
![Screenshot 2023-04-12 at 6.23.35 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/3f2e9cc9-7301-4d61-b8a6-f4a69534fa08)

**Comment by jizhaogit** [comment]
check from the database found a bug that if 2 users had shared relations and later on be switched it will cause some un-excepted issues which will list the team member items in the supervisor list.  the bug is addressed.

**Comment by steffipravasi** [comment]
1) User: Shannon Baskerville
Shannon has 12 active goals, but can see 14 goals in the employee record. The unmarked ones in the following list are displayed extra
![Screenshot 2023-04-14 at 1.32.42 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/90d5ed27-535f-4d37-aa07-48bc6e7a88d9)

**Comment by steffipravasi** [comment]
1) If Record type Past Goal is selected, can we hide the other record types instead of displaying the error as 'There are no records for the employee ID and date range selected.' which is incorrect as There are records to display for those record types, but are not displaying because they are not selected from the Record type field.
2) If the main comment from the goal is deleted, should we display the sub comments in the pdf ? For example in the screenshot below, the highlighted sections are not displayed in the pdf because their main comment is deleted.
![Screenshot 2023-04-14 at 1.39.26 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/fc078ca5-f114-42dd-af31-81a9e38cdb75)![Screenshot 2023-04-14 at 1.41.21 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/2ba794ee-8780-4711-a070-e678b36a51d2)

**Comment by jizhaogit** [comment]
as talked with Travis, we now use the same logic as goal detail does in goal pdf

**Comment by steffipravasi** [comment]
Test validated. The issue for deleted comments not displaying is fixed.
![Screenshot 2023-04-20 at 2.27.10 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/c8dd4953-8ff5-40d9-bf52-906db1cac188)
Ticket ready for PO review

**Comment by Travis-A-Clark** [comment]
@jizhaogit This is great. Thanks!

A (hopefully!) final thing I noticed. The only section of the the open / completed conversations we don't have in the PDF is the section with the two radio button questions right before the sign-off. Can we add this in under the comments areas for employee and supervisor? So it would be Employee Comments section, then Employee Attestation section (which would just have the two questions with the yes / no selection displayed, then the Supervisor Comments, then the Supervisor Attestation.

Sorry to keep adding to this. I just want to make sure we get it right so we don't need to re-open later. Thanks agian!

**Comment by steffipravasi** [comment]
@jizhaogit Receiving the server error on clicking Bulk download for Open and Completed conversation

**Comment by jizhaogit** [comment]
@steffipravasi the 500 error is fixed

**Comment by jizhaogit** [comment]
the required additional line space is added.

**Comment by steffipravasi** [comment]
@jizhaogit 
1) I am seeing 2 different views of Attestation in bulk download
![Screenshot 2023-05-05 at 5.10.03 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/08fee01c-e3f7-408e-bc72-49a8ae9fdb6e)
![Screenshot 2023-05-05 at 5.10.12 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/174460d2-cf98-4a83-af9b-a02e768852f8)
2) Also wondering if the order of conversations displayed in employee record and the bulk download pdf must be the same?. Issue for open and closed conversations

@Travis-A-Clark Should we display the Attestation section even if the conversation is not signed? If yes, then would we prefer to display just the question or No as an answer?
Current view :
![Screenshot 2023-05-05 at 5.24.06 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/d05c137c-4046-410e-b073-89c11ad1ac33)

**Comment by jizhaogit** [comment]
1. the layout for attestations is all set to the same.
2. Currently if the attestation is not checked it will show as "N/A".    only when the option is checked as "No" the attestation will be marked as "No"

**Comment by steffipravasi** [comment]
The Onboarding conversations shows a little misalignment between supervisor and employee
![Screenshot 2023-05-09 at 2.47.27 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/3d67a03a-674e-4b78-93cd-ee5440bc42a4)

**Comment by jizhaogit** [comment]
1. layout issue be addressed
3. the sort order is based on items' created time. latest to earliest.

**Comment by steffipravasi** [comment]
There is a difference between the number of conversations displayed in the Completed section. Can see 5 entries in the record but the bulk download has 9 entries.
User: 000135
Start date: 2022-01-09, End date: 2023-05-09
[https://app.zenhub.com/files/329107952/d84d46ac-52b4-4634-b37c-1a08680ad4d2/download](https://app.zenhub.com/files/329107952/d84d46ac-52b4-4634-b37c-1a08680ad4d2/download) 
![Screenshot 2023-05-09 at 2.54.18 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/2b60d24f-bbad-45c6-bce0-9963da04d883)

**Comment by steffipravasi** [comment]
Test validated. Issue resolved. The bulk download items are now matching with the search results date entered and entries displayed.
Moving ticket for PO review.
