### ISSUE TITLE
ODS Employee Demo pull does not complete  in Dev environment.

### ISSUE THREAD

**Issue by telusdcinco** [bcgov/performance#456]
ODS Employee Demo pull does not complete  in Dev environment.

**Comment by telusdcinco** [comment]
![image.png](https://images.zenhubusercontent.com/60e88ef619e4760c8b3ee8bb/a6dca903-5580-4f1a-b00a-95019f08f066)

**Comment by kkapoor-fresh** [comment]
On a best practice note, It is not recommended to fetch such a large amount of data in a single fetch which results in RAM getting exhausted.  Is it possible to fetch in chunks of smaller sizes? Use some kind of parallelism, maybe while transferring such large amounts of data. Currently, the API call is trying to use 4GB of memory while fetching and this I believe might grow further as the data in ODS increases. 

I believe your local system will reach a bottleneck as well when the requested fetch size increases beyond your local system's RAM.

We can go only as far as the Openshift namespace memory limits is concerned.

**Comment by kkapoor-fresh** [comment]
I increased the memory of the pod/container to 8GB but didnt't make much of a difference
- resources:
        limits:
          cpu: 500m
          memory: 8Gi
        requests:
          cpu: 100m
          memory: 8Gi

**Comment by will-freshworks** [comment]
Closed as stale and not currently replicatable. Please re-open if a priority
