### ISSUE TITLE
Fixes - April 2022

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#457]
- [x] Incorporate spell check into input text boxes (can we add this to the formatting tool bar?)
- [x] On the comments section of the goal cards, can we add function to edit / delete comments? If I make a comment and submit it but realize I have made a mistake or want to change things, I don't have any option to edit or delete.
- [x] On the "My Current Goals" page for supervisors, add info mouse over by the Shared With drop down: "By default, all of your goals are private. Use the "Share with" option to make a goal visible to selected employees. This lets team members know what you are working on and may help team members' set their own goals."
- [x] Conversations template: limit to selecting only one participant

**Comment by Travis-A-Clark** [comment]
@Kousthubha-M Is it possible to fit the "i" information icon by the "Shared With" mouse over on the goal card? The info is there, but there's nothing to indicate you should mouse over to view. Thanks!

**Comment by Kousthubha-M** [comment]
@Travis-A-Clark Understood! Will do. Thanks
