### ISSUE TITLE
As a supervisor, I want to be able to set up and sign off conversations with any employees that are shared with me.

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#461]
Currently, if I an employee is shared with me, I can view their goals and conversations area. I can also comment on their goals. However, I cannot set up or sign off on a conversation with them.

If an employee is shared with me, I should have all the same access as their original supervisor, including the ability to set up and sign off conversations.

**Comment by Kousthubha-M** [comment]
@Travis-A-Clark Fixed the issue where conversations aren't visible when viewing as employee profile. Changes should be in Dev shortly. Thanks

**Comment by jizhaogit** [comment]
Current situation:   
1) employee 1 is shared with supervisor 2.   and supervisor 2 creates a new conversation to employee 1.   supervisor 2 CAN do the sign-off processing for this conversation item.  
2) supervisor 2 CAN NOT do the sign-off processing for supervisor 1's conversation to employee 1.

**Comment by telusdcinco** [comment]
Please use the new Dev/Test links below.

New Dev and Test URLs, with auto-deployment enabled:
https://performance-332842-dev.apps.silver.devops.gov.bc.ca/                 
https://performance-332842-test.apps.silver.devops.gov.bc.ca/

**Comment by Travis-A-Clark** [comment]
@jchow11 No, only the supervisor indicated as a participant in the conversation can sign off. View only on other open and completed conversations. This might change in the future if a need is identified, but this is it for MVP. Thanks!

**Comment by jchow11** [comment]
@Travis-A-Clark Gotcha. Currently the supervisor who is NOT a part of the conversation cannot sign off, but the "yes/no" radio buttons are still available and they can still see the contents of the conversation. It is my recommendation that the radio buttons are disabled. 

Is there a privacy/security risk of having the conversation contents available for view to this supervisor seeing as they are not a participant? It might be best if they cannot see the conversation at all.

**Comment by jchow11** [comment]
@jizhaogit As per our working session with Travis, this just needs one small change:

As a supervisor, all conversations between my employee and another supervisor should be read-only. We will want to disable the "yes/no" radio buttons in the sign-off section.

**Comment by Travis-A-Clark** [comment]
@jizhaogit I think we have gone backwards on this one again. 

Scenario: Zehra has been shared with Martha. Martha sets up a conversation with Zehra. When Martha goes to the open conversation to enter comments and sign-off, she does not have the correct access. As a delegated supervisor, Martha should have access to all of the supervisor text fields and the supervisor radio buttons. Instead, Martha has access to the employee text field and does not have access to any radio buttons (see below). Let me know if you want to meet about this again.
<br>
![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/ba436359-b1d5-4206-a4f0-7cc1a74f1fbf)

**Comment by jizhaogit** [comment]
Can you please provide me with which "Martha" who has the issue?  I cannot reproduce this issue from my local or dev site.

**Comment by Travis-A-Clark** [comment]
**Scenario**: Emma Bennett is shared with Travis Clark (delegate supervisor). They set up a conversation. It appears correctly in Open Conversations. Both people sign-off. When it moves to Completed Conversations it is not processed correctly. It shows up twice: once as a conversation with Emma's supervisor which is correct, and once as a conversations with Emma's team which is incorrect (see screen shot below). It is also not having the intended impact on the Next Conversation Due date. It should be the same as signing off with direct supervisor.
<br>
![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/b00efa25-5be2-4871-b36a-8f5eea47c95b)

**Comment by Travis-A-Clark** [comment]
@jizhaogit The Next Conversation Due date is now being updated properly so that is all good. 
<br>

However, I opened a new Career Development conversation with Emma Bennett and Travis Clark, signed off from both sides, and it still appears twice in Emma's Completed Conversations list. Once under each heading. It should only be in her Conversations with my Supervisor area.
<br>
![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/0d3ae92d-1d1c-4997-b375-99f728e610cd)
