### ISSUE TITLE
Log-in Landing Page

### ISSUE THREAD

**Issue by jchow11** [bcgov/performance#469]
**Description**
Log in page for production env. once we are using real user data and users sign in via. Microsoft SSO and their government IDs.

**User Story**
As a user, I want to be directed to a branding landing page so that I know I am logging into the Performance Development Program.
As a user, I want to log in with my BC govt ID through Microsoft SSO. 

**AC (Acceptance Criteria)**
-Log in with BC gov ID (main)
-Log in with email (secondary)
-Landing page with PDP branding, logo and CTA which leads to Microsoft SSO 
-Need help? Contact your IDIR security administrator or the 7-7000 Service Desk at:
Phone: 250-387-7000
Email: 77000@gov.bc.ca

**Designs**
![Log in-1.jpg](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/057f5012-3bdb-4d1b-8e10-861724b92990)
Upon click of "Log in as a System Administrator":
![Log in - Email.jpg](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/93909d33-922a-476f-81ad-86fdb4406dd7)

**Comment by jchow11** [comment]
@Travis-A-Clark what information needs to be collected when a new user is registering for a new account? Ex. Email, password, confirm password, first name, last name, employee id, etc? Please specify in the AC section above.

**Comment by jchow11** [comment]
@Travis-A-Clark updated designs as per our discussion around retaining the ability to sign in using email.

**Comment by Travis-A-Clark** [comment]
@jchow11 Yeah, that's probably a good idea. The email log in is really just a backdoor for Sys Admin folks. Maybe we can actually have a separate login page for the secondary email log in and have that URL only available to those that need it.

**Comment by jchow11** [comment]
@Travis-A-Clark Is there any other use case for logging in with an email address other than for Sys Admin access? If only Sys admin users are set up to be granted access using their email to log in, perhaps this design could work:

![Log in.jpg](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/247df632-9298-45ad-a096-1bc5fd63dbad)

**Comment by Travis-A-Clark** [comment]
@jchow11 Yes, I think that works. It's clear and I don't think people will accidentally log in the wrong way. Maybe we can just minimize the size and prominence of the Sys Admin button? Potentially even put it below the Need Help? section.

**Comment by Travis-A-Clark** [comment]
@jchow11 I think the last one makes sense. Text link rather than button. Can you delete the other designs and then assign to Dennis? He can assign to whoever has capacity to implement. Thanks!

**Comment by jp-Telus** [comment]
The login landing page was developed, and ready for depolyment. There are 2 option you user can select, login in as a administrator or login in with BC Govt Login ID.

Thank you.
