### ISSUE TITLE
As a supervisor I want to be able to excuse my employee from the performance development process

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#47]
Clicking on the Excused - Yes/No link of the supervisor dashboard should launch a modal that allows supervisors to choose when and why to excuse an employee from the performance development process. Need a calendar interface to indicate that date from which the employee has been excused and an end date (if known) for when the employee will return.

Headings to include:
- From date
- To date (default to eternity)
- Reason (drop down that includes: medical leave; secondment; other leave.

- [x] Design
- [ ] Dev
- [ ] Deploy

**Comment by Travis-A-Clark** [comment]
Current view of excusing an employee in MyPerformance:

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/00fe754c-64dd-4fd1-b533-e391103e46e7)

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/ea56e6ef-d989-40bf-bc95-838b537b0d44)

**Comment by phoebesolomon** [comment]
![Supervisor Dashboard - My Employees 6.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/cd6960b4-6e94-4fb6-bb67-ab881026ac7d)
![Supervisor Dashboard - My Employees 7.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/2e7207a0-b7ab-4a61-a354-e6d7f4d5a88c)
![Supervisor Dashboard - My Employees 8.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/9a3053f2-8f4b-4d8b-8d7f-d8038e41d9a1)
![Supervisor Dashboard - My Employees 9.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/2399f631-918f-4097-85a3-b14590eb3ee3)
![Supervisor Dashboard - My Employees 10.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/c82e9752-5245-40c5-a67c-203882fa6f5c)
![Supervisor Dashboard - My Employees 11.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/fceb7f2e-5a30-4f4e-8113-fad81e43eea1)

**Comment by phoebesolomon** [comment]
@telusdcinco see above
