### ISSUE TITLE
As an employee, I want a clear understanding of when and why to use tags when creating a goal

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#475]
- [x] Shift "Tags" element to top of Create New Goal modal beside "Goal Type"
- [x] Change hoverover tooltips to toggletips (click to activate, stay persistent until user clicks outside or exits the tip)
- [x] Add toggletip definition for Tags element ("i" beside the header) that says: Tags help to more accurately identify, sort, and report on your goals. You can add more than one tag to a goal. The list of tags will change and grow over time. 

- [x] Add link in "Tags" toggletip directing the user to the Resources > Goal Setting FAQs 

- [x] Update list of available tags (see attached)
[https://app.zenhub.com/files/329107952/ad896cd3-0152-4821-b19c-366efb9e8c3e/download](https://app.zenhub.com/files/329107952/ad896cd3-0152-4821-b19c-366efb9e8c3e/download)
<be>

**Designs**
![Create New Goal s.jpg](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/7e3c3277-a779-45bf-bd25-eb27f402ca04)
![Create New Goal _ Goal Tags _ Dropdown.jpg](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/3160711a-77fc-482c-8e3d-ef5235940a8f)
![Create New Goal _ Goal Tags _ Toggletips 1.jpg](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/16550d1e-163d-4a56-9d9e-daa5087fba95)
![Create New Goal _ Goal Tags _ Toggletips 2.jpg](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/c9e4efe1-b673-4818-a1ac-67c204cf15ae)
[Uploading... Create New Goal _ Goal Tags _ Toggletips 3.jpg]
![Resources _ Goal Setting _ Goal tags.jpg](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/dc0130d5-6058-483f-b2ff-93bcb8bfa092)

**Comment by Travis-A-Clark** [comment]
@jchow11 Just added a couple of extra wrinkled to the ticket description. Late night thoughts I needed to capture! Apologies for the timing. Thanks.

**Comment by jchow11** [comment]
![Goal tags _ Full List.jpg](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/a8c77fd6-a51c-486e-8a70-038441da1ab0)![Create New Goal _ Goal Tags _ Dropdown.jpg](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/9a39148d-1f26-4d60-aa5d-229e41fe29fa)![Create New Goal _ Goal Tags _ Hover Definition.jpg](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/62dad2a9-3375-4830-b057-5499bae32ba4)![Create New Goal _ Goal Tags _ Create new tag pt. 1, option 1.jpg](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/7b16223c-0688-4f78-8aec-95989fe1d20a)![Create New Goal _ Goal Tags _ Create new tag pt. 1 option 2.jpg](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/30f829b6-8eaa-4cac-8ad1-eaa25b6fbf3c)![Create New Goal _ Goal Tags _ Create new tag pt. 2.jpg](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/ffe2b878-6d7a-4115-affa-f00efdda5c3f)

**Comment by Travis-A-Clark** [comment]
@jchow11 This looks great! I like the text only version of the "Create new tag?" action button. Thanks!

**Comment by jizhaogit** [comment]
ready for deployment

info icon can not be added into multiselect options. still need to find out a way

**Comment by Travis-A-Clark** [comment]
@jizhaogit As discussed, please update the list of tags in the drop down menu using the content linked in the ticket description.

Also, please add the info tool tip for the Tags header that reads: Tags help to more accurately identify, sort, and report on your goals. You can add more than one tag to a goal. The list of tags will grow over time."

Thanks!

**Comment by jizhaogit** [comment]
The new tags list is imported and migrate script is ready in repo.  
currently working on:
1) information icon to show a detail description of the currently selected tag in the dropdown list
2) show tags in the goals list table

**Comment by jizhaogit** [comment]
new design is updated. code pushed to repo. waiting for deployment

**Comment by jchow11** [comment]
@jizhaogit Everything passing. Looks great Ji!

1 small UI change & typo:

- [ ] "View full list of tag description" missing an "s" at the end

- [ ] Add underline to link "View full list of tag descriptions"

**Comment by jizhaogit** [comment]
changes is pushed in the repo

**Comment by jizhaogit** [comment]
changes deployed

**Comment by Travis-A-Clark** [comment]
@jizhaogit Just noticed one more thing. Even after I have selected multiple tags, the mouse over still says "none selected". Can we please remove this pop up? Thanks!
<br>
![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/721b9ab7-e7bc-4832-bb0e-92cb8dc86408)

**Comment by jizhaogit** [comment]
ready for reviewing in dev

**Comment by Travis-A-Clark** [comment]
@jizhaogit The list of tags is now long enough that it runs out of room, especially at higher magnification in the browser (see below where the bottom 4 or 5 tags are not visible). Can we add a scroll to the list of tags drop down? Thanks!
<br>
![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/e2875797-b7f3-48ec-ba2f-432465ba24c3)
