### ISSUE TITLE
Conversation Templates - Edits June 2022

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#481]
- [x] In Conversation Templates, when you add a participant to the conversation, use normal text and remove light grey background because this makes it difficult to read and is not accessible (see image below for example of current state that needs to be fixed)
<br>
![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/76168e6d-ecea-4071-9661-9f36001b03fc)
<br>

- [x] In Open Conversations and Closed Conversations tabs, the most recent conversations should appear at the top of the lists.
<br>

- [x] In Open Conversations, remove ability to edit participants. There's lots of issues with this, so easier to remove.
<br>

- [x] Open conversation sign-off: only allow sign-off if employee ID entered matches the employee ID of the individual signing off. Right now, I can still enter any six digits I choose. It should only allow me to sign off using my actual employee ID pulled from PeopleSoft/ODS.
<br>

- [x] Add Onboarding template (content linked below)
[https://app.zenhub.com/files/329107952/02178862-350a-4cf0-8ad8-0bd77a1fd0bd/download](https://app.zenhub.com/files/329107952/02178862-350a-4cf0-8ad8-0bd77a1fd0bd/download)
<br>

- [x] Edit Career Development template (linked below)
[https://app.zenhub.com/files/329107952/b2175cc5-71af-464c-9ae4-9508db666f15/download](https://app.zenhub.com/files/329107952/b2175cc5-71af-464c-9ae4-9508db666f15/download)<br>
<br>

- [x] Performance Improvement template: make all three text boxes under "Information to Capture" mandatory
<br>

- [x] Update Conversation Templates layout (design below). Includes moving the message about selecting participants and the "When to Use this Template" information from the modal to the main page.

Templates main page
![My Conversations _ Conversation Templates.jpg](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/e3148bde-d014-41be-b7ba-14599c656875)
<br>

Templated modal
![My Conversations _ Conversation Templates _ Modal.jpg](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/9a9a6d40-f93a-4075-8ef1-9473baa04823)

**Comment by jizhaogit** [comment]
two new updates pushed in the repo
1. change modal layout as discussed in the meeting
2. change "Onboarding Template" name to "Onboarding"

need artisan migrate to sync data.

**Comment by jizhaogit** [comment]
fix deployed in dev
