### ISSUE TITLE
My Conversations > Completed Conversations - Design 2.0

### ISSUE THREAD

**Issue by jchow11** [bcgov/performance#484]
**Designs**

Moved "My Conversations" to the white nav bar and sectioned out each important part of the page into collapsible sections. This allows the user to focus on one specific part at a time. 

![My Conversations _ Open Conversations _ Completed Conversations (Instructions).jpg](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/d2a46430-6cc7-4208-a262-7792f21a608f)

![My Conversations _ Open Conversations _ Completed Conversations (With my supervisor).jpg](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/2a436212-ebc3-40eb-9c0f-74fcacb400a7)

![My Conversations _ Open Conversations _ Completed Conversations (With my team).jpg](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/5f15e668-a143-4cd5-9785-64f07da4cf80)

**Comment by Travis-A-Clark** [comment]
Just a note here that I'd be interested in seeing a design that puts the page title (Share Employees in the example below) moved to the header bar. Then have the description (below the Share an Employee in the example below) moved into a collapsible/expandable element with a title like "Page Instructions" that is minimized by default. Would save a lot of space and create a consistent look across the top of most pages.
<br>

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/7164cd22-f311-45ff-aa7c-51c1eeef8415)

**Comment by jchow11** [comment]
@Travis-A-Clark Here's an example using the Completed Conversations tab.

![My Conversations _ Open Conversations _ Completed Conversations (Instructions).jpg](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/d2a46430-6cc7-4208-a262-7792f21a608f)

![My Conversations _ Open Conversations _ Completed Conversations (With my supervisor).jpg](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/2a436212-ebc3-40eb-9c0f-74fcacb400a7)

![My Conversations _ Open Conversations _ Completed Conversations (With my team).jpg](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/5f15e668-a143-4cd5-9785-64f07da4cf80)

**Comment by Travis-A-Clark** [comment]
@jchow11 I really like this! Does the repeated use of collapsible content create any accessibility issues?

**Comment by jchow11** [comment]
**Accessibility Best Practices for Accordions**
http://web-accessibility.carnegiemuseums.org/code/accordions/
https://www.aditus.io/patterns/accordion/

**Comment by jizhaogit** [comment]
@steffipravasi below is the issues update:
1. There was some conversation history miss data in the participant history cause the team member ddl listed some unexpected users. after manually cleaning up the issue is addressed.  Please info me next when you have this issue again, we can work together and do the cleaning from my end again and verify the result.

2. open conversation expend session will affect conversations list show/close.    this issue is addressed

3. filter for employee/supervisor sign status should work as expect now

4. the column for deleting items now will show without sorting icons.

**Comment by steffipravasi** [comment]
1) The completed conversation does not display entries more than 10 even though we have the pagination at the bottom
User: Nicola Lemmer has more than 10 completed conversations with My team but cannot see it. 
![Screenshot 2023-05-02 at 3.48.05 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/cd1b67e7-87b0-4a24-9e3d-24c60a5b0016)
Can we check it for the Conversation with my supervisor too

**Comment by jizhaogit** [comment]
@steffipravasi  
1. pagination feature works as expected now
2. the participants in both open and completed conversations are shown as "supervisor, employee" now.

**Comment by steffipravasi** [comment]
Pagination added, Participants lit sorted.

**Comment by steffipravasi** [comment]
Since the issues in this ticket and #623 are the same, will be using 623 to track the isses and park this ticket in testing pipeline untill all the issues for 623 and 484 are resolved.

**Comment by steffipravasi** [comment]
The filter issues are fixed similar to ticket #623. 
Moving the ticket for PO review.
