### ISSUE TITLE
UI Fixes - Goal Cards

### ISSUE THREAD

**Issue by jchow11** [bcgov/performance#485]
**Description**
Fixes to spacing issues and hierarchy issues for elements of goal cards.

**Steps to Reproduce**
Log in as employee or supervisor, navigate to "My Goals".

**Actual Results**
- Exiting "Shared with" drop down menu on goal cards by clicking anywhere on the goal card causes the goal card to be launched 
- Buttons on goal cards are not evenly distributed and look messy with new fix of 2 lines
- Dates are long and cause some cards with longer month names to drop down to 2 lines, which misaligns that card to others when window size is reduced

![7682bf8a-789c-49bd-bafc-b7377cc7b73a.png](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/0f165d10-4810-4415-aec6-78bd44c0b61b)

![Screen Shot 2022-05-18 at 10.21.10 AM.png](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/69769ca4-6a07-4aae-8cbf-0d666148c362)

![Screen Shot 2022-05-18 at 10.21.40 AM.png](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/323642ce-1980-4b8d-926d-e5aea3e2f761)

**Expected results**
- Exiting "shared with" drop down menu by clicking anywhere outside, closes the menu but does not launch the goal card or any other action items
- Buttons on goal cards are cleaned up
- Delete button is moved down to the bottom of card and displayed in red
- Dates reduced to a standard size (3 letter abbreviation possibly), long arrow image is replaced with something more space-saving

**Designs**
Shared with - spans goal card width
Status - left align
Delete and view buttons - right align
![My Goals _ Current Goals.jpg](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/987b8b45-34a1-49ff-9e14-8ea345c1ad32)

![My Goals _ Current Goals _ Dropdowns.jpg](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/e0cb2aee-7d10-4108-b575-b3dc6df51bda)

**Comment by jizhaogit** [comment]
changes deployed in the repo

**Comment by Travis-A-Clark** [comment]
@jchow11 Is the design in Dev consistent with what you were looking for? We still need to change the hover over to toggle tool tips, but other than that?

**Comment by jizhaogit** [comment]
fix is pushed in the repo

**Comment by jchow11** [comment]
@jizhaogit @Travis-A-Clark 
Changes look great! Awesome job, Ji :) 

We have one new UI issue– "Goal Status" should be on the second line. Current state below:
![Screen Shot 2022-07-05 at 9.23.48 AM.png](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/5b8cf4c2-4ed7-4cb2-9ed7-0dffeff17c9f)
