### ISSUE TITLE
Sys/HR Admin Search Functions

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#490]
We need to be consistent with the individual/org search interface. Using the model below as the starting point, let's make the following changes:

- [x] Add "Classification" to the search criteria dropdown
- [x] Auto filter when organization levels are selected rather than entering and clicking filter. Similarly, when clicking reset, remove all filters and search criteria automatically rather than having to click filter again.
- [ ] Can we not populate the list at all until at least one search / filter criteria is entered? Ji did this for Switch Identity stuff. Perhaps this would help minimize some of our data load issues as well.

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/dd3cfb8c-d364-4e09-af2a-780876d76d76)

**Comment by telusdcinco** [comment]
I reviewed the ODS data and we are not receiving Classification.  The closest we have is a classification_group, but the values is far from what Travis have indicated.

Below is the link to the CDATA endpoint, for confirming the fields available in ODS.
https://analytics-testapi.psa.gov.bc.ca/apiserver/api.rst#Datamart_ePerform_employee_demo

**Comment by Travis-A-Clark** [comment]
@telusdcinco Still not seeing this same search functionality on: Employee List, Excused Employees, Unlock Conversations. Looks good on Shared Employees and Goal Bank. This will also be applied to HR Admin views, correct? Thanks!

**Comment by Travis-A-Clark** [comment]
@telusdcinco 

1) Filters don't seem to be working on Sys Admin > Past Employees. Entering any filter criteria returns no results.
<br>
2) On SysAdmin > Share Employees > Manage Existing is it possible for the search field to scan not only the employee name and ID but also the delegate name and ID? Results could return any row in which a name or ID appears, regardless of whether it is employee or delegate.

**Comment by telusdcinco** [comment]
1. Fixed -> Issue is with retaining current page is true, data will show by clicking previous page below the grid.  Now turned off, meaning page will reset to Page 1 upon filtering/resetting.

2. Done -> Name now searched within Name, Delegate Name and Created By.  Employee ID now searches within ID and Deledate ID.

**Comment by telusdcinco** [comment]
3. Fixed -> HR Admin will only see self created goals.
4. Fixed -> HR Admin will only see employees for which access is granted.
5. Dev should have the latest copy tested in prod where data is displayed as of yesterday afternoon.

**Comment by Travis-A-Clark** [comment]
@telusdcinco Thanks for all this! Still not seeing any data in the HR Admin view of Statistics and Reports. It loads with zero cases for each screen.

**Comment by jp-Telus** [comment]
Issue replicated on my local database, the additional cirteria was added to include those assigned program, divisioin , branch, level4 are 'blank'.

Deployed and validate on DEV region. I did the test with the Heather.Davey@gov.bc.ca, assign all 'BC Public Service Agency' organization, the count showed 617 EEs.

Please validate your signon. Thanks

**Comment by Travis-A-Clark** [comment]
@jp-Telus I logged in as Travis Clark (set up for HR Admin for Health) and I do see employees in the Statistics and Reports. Thanks!

A couple of things:

1) When I view HR Admin > My Organization I see 1,690 employees. When I view HR Admin > Statistics and Reports I see 1,726. Any idea why there's a difference?

2) It's still much slower to load than Sys Admin > Statistics and Reports. Is this just due to the extra filters being applied?

3) The .csv file for Shared Employees has a small error. The organization, level 1, level 2, info is all off by one column. Level 1 info is being displayed in the organization column, level 2 info is being displayed in level 1 column, etc. For example, the screen shot below, Health should be in the organization column for all rows.
<br>

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/e0e8c53b-ff0e-40eb-912a-45173c807a17)

**Comment by jp-Telus** [comment]
Item 1 - Dennis is helping on comparing the difference count.

Item 2 - Due to apply more checking on organization structure field to retrict the HR admin access, it show down since there are lots of blank and null value in level2, level3 and level4. For improve performance, it will take a lots of efforts.
 
Item 3: Good findings, and resolved the export issue on both HR Admin and Sys Admin area.
