### ISSUE TITLE
Fixes for My Current Goals - June 2022

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#499]
**Create New Goal**
- [x] Do not allow the goal end date to be earlier than the goal start date. Once a start date is selected, only allow end dates of that day or a future date. This should be the same when creating a goal for yourself or adding a goal to the goal bank.
<br>

- [x] Mandatory fields are: Goal Type, Goal Title, Goal Description. Optional fields are: Tags, Measures of Success, Start Date, End date. This is the same whether adding a goal for yourself or adding a goal to the goal bank. Please update the logic and add appropriate error messages if someone tries to create a goal without one of the mandatory fields filled out. As per image below: remove the second "The title field is required" and update "The what field is required" to "The description field is required.
![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/ae71f637-7cd3-4574-ac1b-6bc522f83d70)

**Edit Goal**
- [x] Mandatory fields of Goal Type, Goal Title, and Goal Description still require content. A user should not be able to delete the content from these fields and then save the goal with empty fields. Disallow this action and use the same error messages as in the Create New Goal action above. Allow deletion of Tags, Measures of Success, Start Date, End Date.

**Comment by jizhaogit** [comment]
changes deployed in the repo

**Comment by Travis-A-Clark** [comment]
@jizhaogit Just one small change still to be made. Can we please update the error message (shown below) from "The what field is required" to "The goal description is required"
![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/4bb87095-91fc-4aa3-af0f-7742817fcc37)

**Comment by Travis-A-Clark** [comment]
@jizhaogit It also looks like the changes were not implemented to the "Edit Goal" page. Still need the appropriate error messages added.
<br>
- [ ] Mandatory fields of Goal Type, Goal Title, and Goal Description still require content. A user should not be able to delete the content from these fields and then save the goal with empty fields. Disallow this action and use the same error messages as in the Create New Goal action above. Allow deletion of Tags, Measures of Success, Start Date, End Date.

**Comment by jizhaogit** [comment]
updates are deployed in dev

**Comment by jchow11** [comment]
**Date:** June 16
**Env:** Dev
**Log-in used:** Sys Admin 1

All changes in ticket description have been made and PASS. Some small changes to-do, documented below.

### Changes

- [ ] Left-align dropdown items for Goal Tags
![Screen Shot 2022-06-16 at 4.42.37 PM.png](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/5321d837-2001-48ed-a497-ac3fe6f75724)

- [ ] Change "What" to "Description 

- [ ] Change "Measure of Success" to "Measures of Success"
![Screen Shot 2022-06-16 at 4.45.34 PM.png](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/2b3b8654-4a0c-4e45-8149-ad7d7216ffc1)

**Comment by jizhaogit** [comment]
UI changes are deployed in the repo

**Comment by jizhaogit** [comment]
changes deployed in dev
