### ISSUE TITLE
As an employee I want the option to link my goal to my supervisor's goals

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#50]
- [ ] Supervisor goals can be dummy data at this point; ability for supervisor to add and share goals will come later

- [ ] Successful linking should result in addition of clickable notification/icon on relevant employee goal page; when clicked, pop up with appropriate supervisor goal displayed

**Comment by phoebesolomon** [comment]
@Travis-A-Clark @Kousthubha-M wireframes ready for review in Figma

**Comment by Travis-A-Clark** [comment]
@phoebesolomon @Kousthubha-M I think it looks great; ready to roll! Thanks.
