### ISSUE TITLE
Fixes for My Past Goals - June 2022

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#500]
- [x]  Remove "Edit Goal" option when viewing past goals. Only goals with "Active" status should have the option to edit content.
<br>

- [x] Update columns displayed to: Goal Title, Goal Type, Tags, Start Date, End Date, Status
<br>

- [x] Add search functionality above past goals list similar to My Goal Bank search functionality with fields: Goal Title (open text), Goal Type (dropdown), Tags (dropdown) , Start Date (allow selection of date range), End Date (allow selection of date range), Status (dropdown)

**Comment by Travis-A-Clark** [comment]
@jizhaogit Similar to ticket #739 it looks like there is an issue with the goal type "any". I created three goals, one work, one learning, one career development. I set them all to different statuses and they should all show up in the past goals list by default. However, I only see the work goal. If I select "learning" or "career development" from the filter drop down, the other goals appear.
<br>

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/402a0060-d56d-4eb8-862a-c9593cee9087)

**Comment by jizhaogit** [comment]
1. removed "Any" option from "Create new goal" modal
2. fixed search function for "past goals"

**Comment by Travis-A-Clark** [comment]
Let's go with one tag per row in the list view. Thanks!

**Comment by Travis-A-Clark** [comment]
@jizhaogit Oh! And can we also please add the column sorts for the table so that people can sort ascending/descending by any column? We should try to add this in all places that there are tables of this type. Thanks!

**Comment by jizhaogit** [comment]
1. status added in the filter
2. "Any" button in the date range picker now is working
3. sort order feature is added in the columns headers

**Comment by steffipravasi** [comment]
Test status: **Fail**
Environment: Test
The tags are not displayed in the goal for an employee regardless of the goal being current or past. Due to this issue, search by tag function is not working. There are no results displayed when the tag is selected. 
![Screen Shot 2022-08-25 at 2.54.01 PM.png]
(https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/5d1ad394-66ff-4fda-be7d-177c20ae5aad)
![Screen Shot 2022-08-25 at 2.54.42 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/4eb34b0e-1156-42e0-af5f-4530dcd55223)
![Screen Shot 2022-08-25 at 2.54.01 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/4866d3e5-175c-4795-b5df-d372c10b04bb)

**Comment by jizhaogit** [comment]
Hi Steffi, i think the item you picked title is "Learn automation" is different between Kelly Whitford in the post goals and Shannon Baskerville in the goal bank.
below is the URL for each goal item:

**Kelly Whitford**
https://performance-332842-test.apps.silver.devops.gov.bc.ca/goal/89

**Shannon Baskerville**
https://performance-332842-test.apps.silver.devops.gov.bc.ca/goal/76

**Comment by steffipravasi** [comment]
Test status: **Fail**
Environment: Test
Test data: Kelly Whitford, Kelly.Whitford@gov.bc.ca, Id: 006357

i) The sort feature is not sorting the columns in ascending/descending order. This is for all the columns. 
ii) When a sort is done and user tries to navigate to the second page, the sorting is removed and the default style data is displayed.

Expected results: 
i) Title, Goal type, tags, start date, end date, status can be sorted in ascending/descending order
ii) When for eg Goal type is sorted and user navigates to the second page, the sorting must remain consistent through all the pages.

**Comment by jizhaogit** [comment]
will re-check the sort feature

**Comment by jizhaogit** [comment]
order sort is re-designed. 
please note for the **date sorting**, it is sorted by date number. so Aug, 1st will be sorted after Jul 1st in ASC sorting.  Also the **goal type** items is sorted by their ID due the query generator.  it will may not be able to 100% fit with the alphabet sorting order.

**Comment by steffipravasi** [comment]
The past goal page is giving a 500 Server error when opened @jizhaogit 
![Screen Shot 2022-08-29 at 3.26.56 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/629fe2c4-f68f-4f51-8629-4ace9e505903)

**Comment by jizhaogit** [comment]
a fix is applied in dev for fixing the 500 error.

**Comment by steffipravasi** [comment]
Test status: Pass
Environment: Test
Test data: Kelly Whitford, Kelly.Whitford@gov.bc.ca, Id: 006357
The sort feature works for all the fields in ascending or descending order. The sort remains consistent for all the pagination.
