### ISSUE TITLE
As a supervisor I want to be able to select personal goals to share/link with my team

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#53]
**On supervisor dashboard:**

Add function to action items area to "Share My Goals". Add mouse over: "Make one or more of your own goals visible to your employees."
- [x] Design
- [x] Dev
- [x] Deploy

Click "Share My Goals" to launch a pop-up with list of supervisor's active goals. Pop-up includes Goal Title and Share Status (perhaps a toggle?) that allows supervisors to assign each goal as "Shared" or "Private" and a Share With drop down list (see comments below for example) that is only activated when the toggle is moved from Private to Shared. Default is "Private". 
- [x] Design
- [x] Dev
- [x] Deploy

If status is changed to "Shared" activate "Share With" drop down menu for user to select who will see the goal (see comments below). Default is All Direct Reports. If user clicks OK throw warning: "Sharing this goal will make it visible to the selected employees. Continue? Yes/No". If user clicks Cancel then close Shared With drop down menu and auto toggle status back to "Private".
- [x] Design
- [x] Dev
- [x] Deploy

If a previously shared goal is changed to "Private" throw warning: "Making this goal private will hide it from all employees. Continue? Yes/No"
- [x] Design
- [x] Dev
- [x] Deploy

**Comment by phoebesolomon** [comment]
![Frame 22.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/804d485a-e0c1-42e8-9bef-62baef35b80b)![Frame 23.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/50e9dfc8-6faa-4e5b-b2cb-b87a9fc17381)![Frame 24.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/b6b42330-be1e-484f-b90e-728afbb305dd)![Frame 25.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/8bdbf8a9-20f9-466e-a22a-e70704734168)![Frame 26.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/91e8fd1a-28b4-49fb-baff-b033e3964376)![Frame 27.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/e376f81b-f2da-4fea-95df-830dd95588af)![Frame 28.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/441e810c-5ca7-4ad5-8dbe-efa44f79a877)

**Comment by Travis-A-Clark** [comment]
@phoebesolomon As discussed, this design element should be incorporated into the Supervisor dashboard rather than the Goals tab. I'm going to move this back into product backlog for now as I know you are working on epic #44. Thanks!

**Comment by Travis-A-Clark** [comment]
Here is how Excel deals with sorting and selecting from lists of people. Could we have something similar where the default is that All Direct Reports is selected with similar options to select and search for individuals? 

All selected by default
![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/f01330db-f376-408b-a70f-86c9d3ae6e14)

Deselected certain individuals
![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/f8e5ca5c-22ce-476c-b511-74c6d540a1d5)

Deselect all
![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/f9501a1d-fd6d-4b41-b43e-aabf6ccf152c)

Select a few individuals
![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/8045195d-199a-4699-84b7-0c62e80b5012)

Search function (don't worry about the "add to filter" stuff)
![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/cd19d1f9-9ae0-4977-bc88-62c1308c8a68)

**Comment by Travis-A-Clark** [comment]
Supervisor Dashboard - User Clicks "Share My Goals" ![Supervisor - Share My Goals - Dashboard.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/c337b685-9b61-4b65-9a8d-e8a4c0d2486f)

**Comment by phoebesolomon** [comment]
Updated designs for Supervisor Dashboard below:

Mouseover: "Make one or more of your own goals visible to your employees." ![Supervisor Dashboard - My Employees.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/87558cab-91b0-4de7-bfc8-6645f111f70c)

Click "Share My Goals" to launch a pop-up with list of supervisor's active goals. Pop-up includes Goal Title and Share Status (perhaps a toggle?) that allows supervisors to assign each goal as "Shared" or "Private" and a Share With drop down list  that is only activated when the toggle is moved from Private to Shared. Default is "Private". ![Supervisor - Share My Goals - Dashboard.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/8b201f2c-80eb-4332-bd78-1bc92bf64edd)

If status is changed to "Shared" activate "Share With" drop down menu for user to select who will see the goal (see comments below). Default is All Direct Reports. If user clicks OK throw warning: "Sharing this goal will make it visible to the selected employees. If user clicks Cancel then close Shared With drop down menu and auto toggle status back to "Private". ![Supervisor - Share My Goals - Dashboard 1.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/43034b88-f031-4116-8f38-c9897362c69c) ![Supervisor - Share My Goals - Dashboard 2.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/3fc85750-9ada-418f-afc6-731d178a0e19) ![Supervisor - Share My Goals - Dashboard 2.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/500180e2-90c4-45e9-9c30-817187d7e3b8) ![Supervisor - Share My Goals - Dashboard 4.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/da5fe545-4ded-4768-b3a6-2b755f1187b5)
