### ISSUE TITLE
Fixes for Supervisor / Shared Access - June 15 2022

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#548]
- [x] Limit access to either the goals section, conversations section, or both depending on the level of access granted. Other sections (My Team, HR Admin, System Admin) should never be shared.
<br>

- [x] When I am viewing an employee's profile, clicking on the Performance Development Platform logo currently takes me to that employee's dashboard/home page. This should be disabled since a supervisor does not need to see the employee's home page.
<br>

- [x] When viewing a shared employee's My Goals section, you should only be able to see the goal and add comments. Not delete, change "Shared with" or Status.
<br>

- [x] When using a conversation template, the only participant that shows up should be the employee that you are viewing. Should not be able to set up conversations with your own supervisor or anyone other than the employee whose profile you are viewing.
<br>

- [x] As an employee that has been shared with another supervisor, I should only have access to the employee parts of the open conversation and sign-off process. Currently, I have the supervisor access rather than the employee access (see below). We need to reverse this. This is related to ticket #549
![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/a2a000a6-e71f-4f1a-91bb-f081eff292aa)
<br>

- [x] It looks like currently when I add a conversation with a shared supervisor, that conversation shows up twice, once in the "Conversations with my Supervisor" and once in the "Conversations with my Team" list. The logic needs to be fixed so that when I am an employee, conversations with my shared supervisor only show up under "Conversations with my Supervisor". See screen shot below where the Onboarding conversation with Tanya is at the top of both lists. If I delete one, it removes both.
![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/3980ac80-9f73-4024-8d1f-58a083bbc51f)
<br>

- [x] Change "My Goals" to "Employee XX's Goals" at the top of the page just like the sub headers (see current screenshot below)
![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/72a30004-0568-4f49-b1d5-c70db730f3cc)
<br>

- [x] Change "Conversations" to "Employee XX's Conversations" at the top of the Conversations page. Change  warning message from "You must complete..." to "Employee XX must complete..." (see current screenshot below)
![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/259a475f-780a-48d5-93b2-96c83a91f864)
<br>

**Comment by jizhaogit** [comment]
added the last item fix in the repo.
