### ISSUE TITLE
As an employee I want to be able to see my conversations with past supervisors

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#551]
- [x] Revisit criteria for pulling open and completed conversations for employees when supervisor changes
<br>
Employee should always have access to any conversations that they were involved in. When a supervisor changes, the supervisor loses access to the employee, but the employee keeps access to any open or completed conversations.

**Comment by telusdcinco** [comment]
Past employee listing is based on the whether date_deleted has a date value in employee_demo table.
Current employee listing is populated when date_deleted field is not assigned for the employee.

**Comment by steffipravasi** [comment]
@Travis-A-Clark The employee will be able to access the past conversation, all the fields must be in a view only mode, but should the employee id entering section be removed along with the Un-Sign button?

**Comment by SSubashree26** [comment]
Completed validating this ticket in the test environment. Both the supervisor and the employee is able to see the conversations if there is a change in the supervisor. Also they are able to edit, sign, close, unsign and open those conversations.

Screen Recordings:
https://bcgov.sharepoint.com/:u:/r/teams/02915/Shared%20Documents/General/Testing/Testing%20screenshots/Performance%23%20551/Performance%20551.zip?csf=1&web=1&e=yTuNoe
