### ISSUE TITLE
Provide access to the performance (load) dashboard/reports to other developers

### ISSUE THREAD

**Issue by Abuchana** [bcgov/performance#552]
Give access to the performance dashboards/reports so other developers can monitor, report out, and address status

**Comment by kkapoor-fresh** [comment]
@Travis-A-Clark @Abuchana @telusdcinco I have added Dennis and Ji as users with view access on the Dashboards in sysdig. 

You can try logging into sysdig using this link https://app.sysdigcloud.com/#/login
Select "Log in" with "OpenId" option to login.  You will be prompted for "company name"  as an authentication. I willl send you the company name via email. 

Once in ,you can navigate to the left panel  on the screen and select Dashboards->"my dashboards". You will find a dashboard named "Pod status and Performance" which primarly will tell you about the CPU and Memeory status per pod.
