### ISSUE TITLE
Update HR and Sys Admin views of Add Goal to Bank to match latest formatting

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#554]
We need to add the same descriptions and info toggle tips to the HR and Sys Admin view of adding a new goal to the goal bank that is visible from the supervisor view. Some text is missing from HR and Sys Admin view and the toggle tips are not active.
<br>

Update this:
![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/87c03c2e-bcfc-4638-9ca3-68a03faef88f)
<br>

So it matches this:
![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/2c531d4a-01e7-4feb-91ac-8f894eb28df6)
<br>

**ADDITION**
Looks like we also need the info toggle tips on the edit goal screen (see below); please add.
![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/813f6c91-5658-4837-9c7e-ba8faab4c120)

**Comment by acincotelus** [comment]
changes deployed to DEV:
HR and Sys Admin views of Add Goal to Bank
My Goals>Edit Goal
