### ISSUE TITLE
When creating a new goal in Create New Goal page, prevent user from clicking the Save Changes button while goal is being saved/created

### ISSUE THREAD

**Issue by telusdcinco** [bcgov/performance#555]
In Create New Goal page, multiple goals are created when user clicks on the Save Changes button more than once.

![image.png](https://images.zenhubusercontent.com/60e88ef619e4760c8b3ee8bb/032ce4dc-af8b-44c9-b333-2cce11bab2e9)

**Comment by steffipravasi** [comment]
Test status: **Fail**
Env: Test
User: Shannon.Baskerville@gov.bc.ca
The Save Changes button keeps on loading when the button is clicked without entering any data on the page.

Steps to reproduce:
i) Go to My Goals->Create new goal
ii) Click the Save changes button without entering any data
iii) The Save Changes button now keeps on loading even if all the details on the form are entered.
![Screen Shot 2022-09-12 at 8.48.52 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/7c7e8e95-3d77-434f-9fd5-b7e6fc5bc8b2)

**Comment by steffipravasi** [comment]
Test status: Pass
The button does not keep loading when Save changes button is hit without entering any data.
