### ISSUE TITLE
Text Edits - Sys Admin and HR Admin - June 2022

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#578]
See attached Word document for a number of updates to be made to the HR Administration and System Administration pages. Thanks!

[https://app.zenhub.com/files/329107952/17d5425c-e165-4056-bbba-72b7c4cb2c9a/download](https://app.zenhub.com/files/329107952/17d5425c-e165-4056-bbba-72b7c4cb2c9a/download)

**Comment by acincotelus** [comment]
changes deployed to DEV
