### ISSUE TITLE
Resources Section Updates - July 2022

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#589]
Please see below for a list of update for the Resources section of the app. Let me know if you have any questions!

- [x] Update User Guide tab content to say: "User guide and tutorial videos for all basic functions will be available soon."
<br>

- [x] Update Contact tab content to say: "For additional support, email Performance.Development@gov.bc.ca or submit a ticket through [AskMyHR](https://www2.gov.bc.ca/gov/content/careers-myhr) to My Team or Organization > HR Software Systems Support > Performance Development Platform."
<br>

- [x] Update Goal Setting tab using the word document attached below.

[https://app.zenhub.com/files/329107952/c3cbd379-a318-4aa2-98e6-a455dae306a1/download](https://app.zenhub.com/files/329107952/c3cbd379-a318-4aa2-98e6-a455dae306a1/download)
<br>

- [x] Update Conversations tab using the word document attached below.

[https://app.zenhub.com/files/329107952/2e10f780-0e73-41a8-bd04-c426bf9d4e3e/download](https://app.zenhub.com/files/329107952/2e10f780-0e73-41a8-bd04-c426bf9d4e3e/download)

**Comment by acincotelus** [comment]
Deployed to DEV:
User Guide tab content
Contact tab content 
Goal Setting tab (pending What are goal tags)
Conversations tab

**Comment by acincotelus** [comment]
Goal Tags update to be completed on ticket #590

**Comment by Travis-A-Clark** [comment]
@acincotelus Thank you! 
<br>
On the contact tab, is it possible to clean up the email address? It looks like we are seeing it twice. Also, please make the word "AskMyHR" a link to https://www2.gov.bc.ca/gov/content/careers-myhr. 
<br>
![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/55166625-e6eb-4e69-8677-25d748849af1)

**Comment by acincotelus** [comment]
Deployed to DEV - updates on Contact tab (clean up email address and "AskMyHR" link)
