### ISSUE TITLE
Updated List of Goal Tags - July 2022

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#590]
Can we please update the Goal Tags seed data for all areas of the app to the following list? Thanks!

Accessibility
Accounting
Clerical
Client Service
Communication
Computer and Information Systems
Diversity and Inclusion
Economics
Education and Training
Finance
Human Resources
Innovation
Law
Marketing
Operational Planning
Reconciliation and Decolonization
Strategic Planning
Talent Management

**Comment by jizhaogit** [comment]
Need tags' descriptions.

**Comment by jizhaogit** [comment]
migrate file is deployed in the repo

**Comment by Travis-A-Clark** [comment]
@jizhaogit A couple of quick things:

1) The link to the full list of descriptions (see below) needs to be updated. It currently ends in t=4 and I think it now needs to end in t=5. Please update anywhere this link appears.
![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/6af14ac8-4882-4aef-b8b7-731720d7c657)
<br>

2) A couple of the definitions are incomplete in both the goal tag drop down and in the Resources tab. Can you please update the two definitions below.
<br>
Diversity and Inclusion: Related to supporting a diverse workforce and enhancing inclusion in the workplace to ensure the BC Public Service is reflective of our province and inclusive of Indigenous peoples, minority communities, immigrants, persons with disabilities and the LGBTQ2S+ community.
<br>
Reconciliation and Decolonization: Related to establishing and maintaining a mutually respectful relationship between Indigenous and non-Indigenous peoples in this country and dismantling the process by which one nation asserts and establishes its domination and control over another nation’s land, people, and culture.
<br>
Thanks!
