### ISSUE TITLE
As a supervisor I want to see the employee ID along with name when sharing profiles

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#591]
Add employee ID to name field in search drop down to differentiate people with same name.
<br>

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/1b41e019-1859-4e64-991c-1004edc2657e)

**Comment by telusdcinco** [comment]
Deployed to Dev

**Comment by Travis-A-Clark** [comment]
@telusdcinco this looks good! just noticed that there is no scroll bar on the share profile modal so if the employee is shared with multiple people, the bottom of the modal is inaccessible. Can you please add the scroll functionality? Thanks!

**Comment by telusdcinco** [comment]
Vertical scroll bar is pending.

**Comment by Travis-A-Clark** [comment]
Remaining work moved to ticket #665.
