### ISSUE TITLE
UI Fixes - Nav Bar

### ISSUE THREAD

**Issue by jchow11** [bcgov/performance#592]
**Description**
Cleaning up the visual hierarchy of the main sidebar navigation.

**Current State**
- Hover colour and active colour are the same - #FCBA19
- Sub-items under "My Team" have the same visual hierarchy as the other menu items
- "My Team" text changes to white sometimes
![Screen Shot 2022-07-05 at 2.14.48 PM.png](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/7eb41fbb-4c22-4710-a5e2-d9570b2b6f6b)
![Screen Shot 2022-07-05 at 2.14.58 PM.png](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/1e8dfd60-a01b-489e-915c-e9c0c55b8473)

**Desired State**
- [x] Change hover colour to #1A5A96 for the background, #FFFFFF for text
![Screen Shot 2022-07-05 at 2.33.28 PM.png](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/f73e9abd-298d-4c39-a510-ecc05c68ef72)

- [x] "My Team" subitems expand upon click of "My team", but "My Team" should not display as selected, because it is not yet selected
![Screen Shot 2022-07-05 at 2.56.03 PM.png](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/48ae8f06-03e0-4460-ba16-3b597ee67af8)

- [x] Once a "My Team" subitem is selected, the subitems displays in #FCBA19 text (no background), and "My team" displays as selected with a #FCBA19 background
![Screen Shot 2022-07-05 at 2.22.54 PM.png](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/71c78c22-bd9a-4642-9127-e3492a8bc3a4)

**Comment by jchow11** [comment]
@Travis-A-Clark some UI fixes to clean up the menu. I realized I have been creating tickets and putting them in the product backlog rather than tagging you for review! Moving those to "Ready for Review" and assigning you so that you can give me feedback and move them around as you please.

**Comment by jizhaogit** [comment]
pushed in dev

**Comment by steffipravasi** [comment]
Test status: Pass
The item hover colour changes to #1A5A96 for the background and #FFFFFF for text. 
The parent item does not get selected until a subitem is selected. Once a subitem is selected it displays in #FCBA19 text with no background, and parent menu displays as selected with a #FCBA19 background.![Screen Shot 2022-08-04 at 11.08.46 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/c7de76be-38e6-4eca-882a-b877959365ee)

**Comment by Travis-A-Clark** [comment]
@steffipravasi A couple of things:

1) It still looks like there are instances where there is white text on yellow background which I believe we want to get rid of.
![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/5302e48a-e4ab-42c6-b138-19f50adbc92d)
<br>

2) I don't think the My Team drop down is displaying as Jordan intended. Please reference the last two designs in the ticket description.
<br>

3)  It doesn't look like the changes are reflected in Microsoft Edge. Is there an additional step to take for different browsers?

**Comment by jizhaogit** [comment]
1. as talked in the meeting. changed the sub-item mouse hove background color
2. removed actives sub-item's background color for fitting change request
