### ISSUE TITLE
As a sys admin I want to be able to create/save/edit goal banks for all BCPS employees

### ISSUE THREAD

**Issue by Abuchana** [bcgov/performance#60]
Extension/expansion of HR Admin functionality. Not limited by department ID or ministry. Create goals that are accessible to all BCPS employees.

**Comment by phoebesolomon** [comment]
![Goal Bank Function - Dropdown Items.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/185e1e51-441b-493f-ab36-fad85dca1f44) ![Goal Bank Function Main Page.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/797a28c9-2b1c-4e60-94ba-d2d191d2d37a) ![Goal Bank Function - Ministry Dropdown - Level 2.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/2fb62052-7c7e-4e97-90e1-95922330406b) ![Goal Bank Function - Ministry Dropdown - Level 3.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/a3d435e9-2659-47a0-8ee4-c2c83a19a366) ![Goal Bank Function - Ministry Dropdown - Level 4 selected.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/af0e68ea-f99a-42ae-80bf-949f2d5ccf01) ![Goal Bank Function - Enter Goal Details.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/f3653337-3873-4b0f-b228-c8f919dad9f9)

**Comment by phoebesolomon** [comment]
![Goal Bank Function Main Page.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/4200e56f-2743-4f76-b35d-d8c7f3153468) ![Goal Bank Function - Dropdown Items.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/80389e50-52d5-4766-b8f1-928f8f96ab2d) ![Goal Bank Function - Ministry Dropdown - Level 2.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/301e8a42-9ccd-4b43-a6d1-90d02e34f7c2) ![Goal Bank Function - Ministry Dropdown - Level 3.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/9fef0bda-b965-451d-8c48-d6be79ccdfa4) ![Goal Bank Function - Ministry Dropdown - Level 4 selected.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/f1319764-72b2-46df-b86b-d76fd8678b76) ![Goal Bank Function - Enter Goal Details.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/4d4231e8-226d-4f09-a7c4-d6d458e22fa8)

**Comment by Travis-A-Clark** [comment]
@phoebesolomon I think we will want to invert this process: as a Sys Admin I will want to see a list of all the goals that have been created and be able to edit the goal and who it is assigned to, rather than seeing a list of all employees and then editing the individual goal bank.

**Comment by phoebesolomon** [comment]
Edit Goal: 

![Edit Goal Bank 6.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/5ef733e7-8f95-408a-a1aa-d25d5209937f) ![Edit Goal Bank 7.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/e08ed2b5-786d-42e1-bd1b-a4767430dc67) ![Edit Goal Bank 8.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/cfd1bcc2-2603-4923-897d-0e0ce3331d02) ![Edit Goal Bank 9.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/05270a24-545d-4b14-b3d2-cb7c5ab023b0)

Remove Employee Goal Audience:

![Goal Audience.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/3bae094d-96ef-47c7-8bc8-ecd5318ad879)
![Remove employee from goal audience.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/7470af01-9aab-40eb-a214-c0d1b84ed289)

**Comment by phoebesolomon** [comment]
![Edit Goal Bank 6.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/c91fec6b-59d6-4971-9de9-4e32d1db2036) ![Edit Goal Bank 7.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/cfeb5ca3-5cb7-41f8-9464-4b20aa444dc8) ![Edit Goal Bank 8.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/ee0d26db-8981-41b5-a6e1-7755b822c79f) ![Edit Goal Bank 9.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/b71e6863-9b48-4c79-870e-e42f54f1eb93)

Remove employee from goal audience (method 2):
![Goal Audience.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/bfb1c8f6-009a-42bf-88fa-4b15d2ae46d8) ![Remove employee from goal audience.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/2259152c-fdbc-4718-96cb-7306f308bc5c)
