### ISSUE TITLE
Page Titles for Accessibility

### ISSUE THREAD

**Issue by jchow11** [bcgov/performance#608]
### Test Cases
![Screen Shot 2022-07-07 at 9.33.28 PM.png](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/e9daacc9-fd7a-49e2-8260-be7332be7d86)

---

- [x] **ISSUE:** Page title is too general. Currently "Dashboard"
**SOLUTION:** Change title tag (< title >)to "Dashboard - Performance Development Platform"

**Comment by jchow11** [comment]
Hey @Travis-A-Clark ! I've created this ticket for your review for accessibility items found through my audit of the Dashboard/homepage. These are specific to the Homepage, I am capturing items which are applicable to the whole app in a different ticket.

**Comment by acincotelus** [comment]
@Travis-A-Clark  @jchow11 
Deployed to DEV and TEST the following updates:
Change title to "<page> - Performance Development Platform"
Example:
Dashboard - Performance Development Platform
My Goals - Performance Development Platform
My Conversations - Performance Development Platform
Team Members - Performance Development Platform
My Organization- Performance Development Platform
Share Employees - Performance Development Platform
Excuse Employees- Performance Development Platform
Goal Bank - Performance Development Platform
Statistics and Reports - Performance Development Platform
Employee List - Performance Development Platform
Unlock Conversations - Performance Development Platform
Notifications - Performance Development Platform
Access and Permissions - Performance Development Platform
Switch Identity - Performance Development Platform
Resources - Performance Development Platform

![image.png](https://images.zenhubusercontent.com/622f754395f085119242a764/bc3b9b8a-54aa-4b7f-861c-6d5e77395265)

![image.png](https://images.zenhubusercontent.com/622f754395f085119242a764/413ad2c7-6bca-420d-8026-d4ed7b608d8a)

**Comment by Travis-A-Clark** [comment]
@jchow11 Would you be able to separate out and create new tickets for the parts of this work that still need to be done? I'd like to rename this ticket to be specifically about the page titles that Ama updated so that we can include this ticket in the next deployment to production without losing sight of the remaining work. Thanks!

**Comment by jchow11** [comment]
@Travis-A-Clark Done. I've created tickets #740 and #741 for the rest of this work. Can this be moved to "Done"?
