### ISSUE TITLE
Update Tooltips and text for Open Conversations

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#611]
After a user has selected the performance check-in template, they go into the open conversations to add their comments and sign off on the performance review. Can we please make the following two changes to the Information to Capture areas (see screenshot below):
- [x] Change the hover over tips to the toggle tips use elsewhere on the site
<br>
- [x] Change the text for each header to include that it is the supervisor that is responsible to enter the content.
- "Appreciation (optional) - supervisor to highlight what has gone well"
- "Coaching (optional) - supervisor to identify areas where things could be (even) better"
- "Evaluation (optional) - supervisor to provide an overall summary of performance"
<br>

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/efcf6a05-7fd0-40a3-a024-1f6d91e150cf)

**Comment by acincotelus** [comment]
Deployed to DEV
