### ISSUE TITLE
Update Text on Sys/HR Admin > Shared Employees

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#613]
In step 3 of the Share an Employee tab for both Sys Admin and HR Admin, there is an info tip that currently doesn't have any content (see below).

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/1f4a133e-74a4-463d-87fa-afc6b1ee3657)
<br>
**1) Can we please add toggle tip content that says:**

Provide a brief explanation of why the profile elements are being shared. For example:
- Sharing profile with co-supervisor
- Sharing goals section with project team lead
- Sharing conversations section with hiring manager per employee request
<br>
**2) Can we edit the description text to say:**

Supervisors and administrators may share all or part of an employee's PDP profile with another supervisor or staff for a legitimate business reason. The full profile or the Conversations section should only be shared with people who normally handle employees' permanent personnel records (i.e. Public Service Agency or co-supervisors). The Goals section can be shared more broadly (i.e. with project team leads) to encourage collaboration and feedback on specific goals.  

An employee may also wish to share their profile with someone other than a direct supervisor (for example, a hiring manager). In order to do this - the employee's consent is required.

To continue, please use the functions below to select the employee profiles that you would like to share, the person you would like to share the profiles with, which elements you would like to share, and your reason for sharing the profile.
<br>
**3) Can we update the confirmation message that appears when you create a new share to say:**

Are you sure you want to share the selected profile(s)?
<br>
![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/3d09cf74-f4ee-4439-b6f7-8f79e6282111)

**4) Apply same changes to My Team > Share Employee modal**

All of the same text and toggle tip changes need to be reflect in the supervisor view of employee sharing reached from the My Team page. Screenshot below.
<br>
![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/1b4878be-b694-4273-a6fb-e359b276d810)

**Comment by Travis-A-Clark** [comment]
Thanks, @acincotelus ! Only one small update for My Team > Share Employee modal. Please change the hover over tooltip to the toggle / clickable tool top as it is elsewhere. Everything else is good to go.

**Comment by acincotelus** [comment]
Deployed to DEV - Reason for Sharing tooltip ( from hover to clickable )
