### ISSUE TITLE
Text Updates - July 11 2022

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#619]
**My Team > Team Members**
- Once you have selected a team member (direct report or share with me) and you are viewing their profile, update the message in the bar across the top of the profile to say: "You are viewing _EMPLOYEE_'s profile. Click "Return to My Profile" to go back to your own."
![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/8f7ec6c0-4fdd-47e7-a4ee-9d258df06668)
<br>

**My Team > Team Members**
- When you click on the Excuse Yes/No and the modal pops up, update the text to say:
All employees are required to complete at least one performance conversation every four months. Employees may be excused from completing a conversation only if they fit into one of the categories listed in the dropdown box below. Excusing them will remove the employee from any reporting and will pause the employee’s conversation deadlines during the date range selected.

Declaration
I wish to excuse the _EMPLOYEE_ from the Performance Development process during the date range selected.

! Note: By doing so, these employees will not show up in PDP reports
<br>

**Sys Admin (and HR Admin) > Excuse Employees > Excuse New Employee**
- When clicking Excuse Employees in step 4, update confirmation message to say: "Are you sure you want to excuse the selected _number_ users?"
<br>

**Sys Admin (and HR Admin) > Goal Bank > Add Goal to Goal Bank**
- When clicking Add Goal in step 3, update confirmation message to say: "Are you sure you want to create the goal and assign to the selected audience?"
<br>

**Sys Admin > Access and Permissions > Create New Access**
- When clicking Assign Employee in step 4, update confirmation message to say: "Are you sure you want to grant administrator access to the selected employee(s)?"
<br>

**Sys Admin > Switch Identity**
- Once you have selected a user and switched identity, update the message in the bar across the top of the profile to say: "You are logged in as _EMPLOYEE_. Click "Revert Identity" to return to your own profile."
![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/06173a53-5694-4afb-9cce-15a798dff9c8)
<br>

**Comment by acincotelus** [comment]
Deployed to DEV
My Team > Team Members
Sys Admin (and HR Admin) > Excuse Employees > Excuse New Employee
Sys Admin (and HR Admin) > Goal Bank > Add Goal to Goal Bank
Sys Admin > Access and Permissions > Create New Access
Sys Admin > Switch Identity

**Comment by Travis-A-Clark** [comment]
@acincotelus 

For the excuse modal on My Team > Team Members, I screwed up the text for the !Note section. Please update to: "! Note: By doing so, this employee will not show up in PDP reports." Thanks!

**Comment by acincotelus** [comment]
Update on " Note"  on  Excuse modal on My Team > Team Members deployed to DEV
