### ISSUE TITLE
Improve display of info in Access and Permissions > Manage Existing

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#624]
How could we easily search as currently listed to find out who had HR Admin access for a specific organization? We see the individual's info, but not the info of the organization they are associated with. Even just an org level indicator where we then clicked for the full details to see which areas in the organization.
<br>

Also, there is a "save change" option on the Edit Employee Access modal, but there are no changes that can be made. You either leave it as is, or remove all access for the user.

**Comment by telusdcinco** [comment]
The "Save Changes" button allows for updating 'Reason for assigning".

**Comment by telusdcinco** [comment]
@Travis-A-Clark 
Do we change the filter function?  If any of the org filter is selected, the user list is filtered based on the user's org access (not the users current organization).

**Comment by Travis-A-Clark** [comment]
@telusdcinco Don't start on this unless you think it will be an easy fix. I chatted with Jessica and propose that we make some simpler adjustments capture in ticket #1052.

**Comment by Travis-A-Clark** [comment]
If you haven't started on this, we can close the ticket and refer to #1052 instead.

**Comment by telusdcinco** [comment]
Refer to #1052 for altered requirements.
