### ISSUE TITLE
SEE TICKET 794 - My Team > Team Members: add ability to edit/delete "excused" status

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#625]
### This ticket has been replaced by ticket 794

Currently a supervisor can excuse an employee for a specified date range. However, they can't edit or delete that date range once created. They need to have this ability added.

**Comment by telusdcinco** [comment]
Fixed the status display for Excused on the My Team > Team Member page.  The Yes/No value now validates current date having in between start and end dates for excused.

The dates can be cleared by clicking on the date field and selecting "Clear".  After saving the Yes/No status will be validated when the page refreshes.

When the excused dates have expired the excuse start/end dates are ignored and not processed.  The Excused status will display a "No".

**Comment by Travis-A-Clark** [comment]
@telusdcinco I am having a brain fog here because I specifically remember writing out comments on this ticket before, but they are clearly not here. Sigh. Here's what I am thinking.

The logic works exactly as you intended, so that's great. I think we can improve the interface a bit though.

- Can we add a button that says "Reset Dates" that resets both date boxes without having to know to go in and clear date info.
- Let's change the "Process" button at the bottom of the modal to say "Update" and throw a confirmation message when it is clicked: "Are you sure you want to update the excused status of this employee?"
<br>

**Comment by telusdcinco** [comment]
Another thing I forgot to mention is that, when the Excuse dates are no longer valid or in future dates, the start and end dates are not being displayed in the modal.  
Impact:  If there is future dated excuse, someone can setup other dates without  knowing there were excuse dates setup already.
Maybe the current start/end dates should be displayed on the modal popup, even though they may be expired,  Also, may give the user an insight on what the last excused dates were.

**Comment by telusdcinco** [comment]
Recent Changes:
- Currently stored Start/End excuse dates and reason shown in modal page when editing Excuse Dates.  
- Reset Dates button added to quickly assign a null to Start/End Dates while on the modal page.
- "Proceed" button re-labeled to "Update".
- Added confirmation before saving the changes on the modal page.

**Comment by steffipravasi** [comment]
@telusdcinco I am not able to view any excused employee in the Manage Existing Excused employee section even after adding an employee to excuse.

Env: Test
User: Supervisor - Shannon.Baskerville@gov.bc.ca, Excused employee - Nicola.Lemmer@gov.bc.ca 
![Screen Shot 2022-08-29 at 8.22.46 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/c65c256f-7ef8-4005-8aaf-6cb8851b0281)

**Comment by telusdcinco** [comment]
Fixed HR/Sys Admin Manage Excuse.

**Comment by steffipravasi** [comment]
@Travis-A-Clark 
1) HR admin -> Excuse employee -> Manage existing employee, should the manage existing employee list only show the currently excused employees?
2) should we have better indicator and not just Yes/No, to show Future/Expired/Current/Non-Excused cases. Right now, if the excused dates are in the future, then it shows No which becomes hard to predict except going inside to view the details
![Screen Shot 2022-08-31 at 11.58.24 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/728b1341-b3d1-488c-b6b2-a08bd98797d6)
