### ISSUE TITLE
SEE TICKET 772 and 773 - Create "Excused" logic to remove employees from reports and pause conversation deadlines

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#627]
This ticket has been replaced by ticket 772 for excused status and conversation deadlines, and ticket 773 for reporting issues.

Also need to "pause" the next conversation due date for an employee while they are on excused status. For example, if my next conversation due date is April 10 and I go on excused status from Feb 10 to August 20, then my next conversation dude date should be October 20 (April 10 minus Feb 10 equals 2 months; August 20 plus 2 months is October 20). 

Should also update message across the My Conversations area to say: "Employee is excused until _DATE_".

**Comment by telusdcinco** [comment]
Mty Conversations messages (compliance and alerts) have been updated to:
- display "Employee is excused..." when the current date is between the start/end excused dates for the employee.
- display a modified next conversation date based on the formula above.

Changes to statistics and reports are pending, and will require additional effort.  

Additional change may be required on the My Teams page to display the modified Next Conversation Date.  Pending discussion with PO.

Possible change may be required on the Yes/No value for Excused column, to reflect future/past excused status.  Pending discussion with PO.

**Comment by Travis-A-Clark** [comment]
@telusdcinco As discussed, a couple of additional changes to make:

- [ ] Store Next Conversation Due date rather than calculating each time; consider daily chron job
- [ ] Add "Upcoming" in addition to "Yes" and "No" as possible excused status

Moved additional Statistics and Reporting updates to ticket #773.

**Comment by telusdcinco** [comment]
The Upcoming status have been added to most of the related pages.  The process for determining next conversation dates is just started and will impact other tickets related to Excuse and Conversation Dates.

Current changes are still in my local only, as pushing partial changes may confuse the tester.
