### ISSUE TITLE
Conversation sign off - JSON string displays 

### ISSUE THREAD

**Issue by jchow11** [bcgov/performance#629]
**Description**
Bug discovered in Ticket #549. JSON string displays rather than the application interface in certain situations where a user is trying to sign/unsign conversations.

**Steps to Reproduce**
Using the un-sign functionality to re-open the conversation, enter an incorrect employee ID (i.e. 123456) and received the screen below. Travis able to reproduce, Jordan and Ji not able to reproduce consistently.
![6d018956-9e33-4fb5-b296-01363d6c2444.png](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/74a81f0b-15b4-43f4-99b7-f8886f4d2f88)

**Comment by Travis-A-Clark** [comment]
@jizhaogit I think I figured part of it out! If I click on the Sign or Un-Sign button directly with the mouse, everything behaves as expected. However, if I click the enter key on my keyboard instead, I get the JSON string.
