### ISSUE TITLE
Switch Identities Search Bug

### ISSUE THREAD

**Issue by jchow11** [bcgov/performance#634]
**Description**
Bug when searching for an employee within the Switch Identity function of the System Admin user.

**Steps to Reproduce**
-Log in as a system admin
-System administration > Switch Identity
-Select a dropdown for "organization" or "level"

**Expected Results**
-User can type to search for key words in each drop down
-Results populate within the dropdown and the user can select a response

**Actual Results**
-Error message upon clicking dropdown "the results could not be loaded"
-Same error message appears when user types keywords into the search of the dropdown, no results appear.
![Screen Shot 2022-07-12 at 11.13.55 AM.png](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/1f3b9149-0e15-4c8a-9b4f-32482596ae44)

**Comment by telusdcinco** [comment]
@Travis-A-Clark @steffipravasi Issue is fixed in Dev/Test

**Comment by telusdcinco** [comment]
Solution contains changes related to #785/#796.  Migrate to Prod only when Dept ID changes goes to Prod.

**Comment by steffipravasi** [comment]
Test validated. Issue resolved for all the levels:
![Screenshot 2023-05-15 at 10.21.39 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/45185ea2-f726-45b1-a12c-11c4eeea66a0)
Moving for PO review.
