### ISSUE TITLE
Create a My Account space for users to set preferences and upload profile picture

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#636]
My Account to be added as nav item under user name. Content to include:

- Upload/edit profile photo

- Notifications (could be a list with toggles for a couple of options and defaults without options for others; all of these things will generate notifications on the home page)

I want to receive an email when someone:
       - Makes a comment on one of my goals **No** / Yes
       - Adds a new goal to my goal bank **No** / Yes
       - Shares my profile with another supervisor **No** / Yes
       - Wants to set up a performance conversation with me **Yes** (no greyed out)
       - Signs-off on a performance conversation with me **Yes** (no greyed out)
       - Disagrees with the content of a performance conversation with me **Yes** (no greyed out)

I want to receive an email:
       - One month before my next conversation due date No / **Yes**
       - One week before my next conversation due date No / **Yes**
       - When my conversation is past due **Yes** (no greyed out)

**For supervisors only**
       - One month before my team member's next conversation due date No / **Yes**
       - One week before my team member's next conversation due date No / **Yes**
       - When my team member's conversation is past due **Yes** (no greyed out)

- Add profile pic to top right banner and remove profile pic from left navigation bar

**Designs**
![Account Preferences.png](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/1e085b81-fb9e-4a4b-94e0-14584dc3121e)

Testing: [636](https://bcgov.sharepoint.com/:w:/r/teams/02915/_layouts/15/doc2.aspx?sourcedoc=%7BC927248D-1A0D-4298-8F00-CF1C5B4BD4FB%7D&file=636.docx&action=edit&mobileredirect=true&wdPreviousSession=814fc565-6d25-45d4-8b4b-297ac9cf8086&wdOrigin=TEAMS-ELECTRON.teamsSdk.undefined)

**Comment by jchow11** [comment]
@Travis-A-Clark I think it makes sense to keep the log out button as a second drop down from the top bar. This is a convention used widely and something our users should be used to, rather than the user navigating to account preferences to log out. I think the top banner gives good separation between the page title and the body of content since we have some complex hierarchy with tab navigation and accordion sections on many of our pages. Let me know what you think of the design!

**Comment by Travis-A-Clark** [comment]
@jchow11 This looks great! I am going to put this back in estimates for the dev team. Thanks.

**Comment by steffipravasi** [comment]
@jchow11 So are we removing the profile icon and name from the left panel? It's marked in the below attached screenshot for reference. Also, are the name and email non-editable fields? 
![Screen Shot 2022-08-23 at 10.15.39 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/50596c7c-f376-4858-b54a-b5f8666ab238)

**Comment by jchow11** [comment]
@steffipravasi Oh no, sorry I think I was using a different template. The profile photo and name in the left column should stay. 

Name and email are not editable in my design, and my understanding is that they should be linked to the user's BC Gov information – @Travis-A-Clark confirmation on this?

**Comment by jp-Telus** [comment]
The following business areas are improved to send out email notification using the notfication template (also checking the newly developed user preference options), here are the list with the tempklate name for your reference:

1.  Goal (GoalController) 	
	Template: SUPERVISOR_COMMENT_MY_GOAL	(Makes a comment on one of my goals)
	Template: EMPLOYEE_COMMENT_THE_GOAL   (Makes a comment on one of my goals)
2. 	Goal Bank HRADMIN/SYSADMIN pages (GoalBankController)
	Template: NEW_GOAL_IN_GOAL_BANK  (Adds a new goal to my goal bank)
3.  My Team (MyTeamController)
	Template: NEW_GOAL_IN_GOAL_BANK  (Adds a new goal to my goal bank)
	Template: PROFILE_SHARED  (Shares my profile with another supervisor)
4. 	Share Employee (EmployeeShareController)
	Template: PROFILE_SHARED	(Shares my profile with another supervisor)
5.  Conversatioin (ConversationController)
	Template: ADVICE_SCHEDULE_CONVERSATION (Wants to set up a performance conversation with me)
	Template: CONVERSATION_SIGN_OFF    (Signs-off on a performance conversation with me)
	Template: CONVERSATION_DISAGREED   (Disagrees with the content of a performance conversation with me)
6.  Daily Schedule Process (command called NotificationProcess run at 1:00am PST)
	Template: CONVERSATION_DUE (Send out email notification when conversation is overdue)
	Template: CONVERSATION_REMINDER (Send out email notification when conversation will be due in 1 week or 1 month)
		
_The following criteria are required when the email could send out to the users:_
a. email configuration on the system level is 'on' (PRCS_EMAIL_NOTIFICATION=on) in .env file
b. the 'allow email message' is Yes on the remployee's organization (defined in the Access Organization under System security).
c. the user's system preference is Yes on "Adds a new goal to my goal bank"

Note: Non-Production environment, the test email account is defined in .env, the name is MAIL_TO_ADDRESS_FOR_TEST		
	MAIL_TO_ADDRESS_FOR_TEST=travis.clark@gov.bc.ca
		
		
**_Migration Instructions_**
1. php artisan migrate		
2. php artisan db:seed --class=GenericTemplateSeeder
3. php artisan view:clear
4. php artisan cache:clear

**Comment by jp-Telus** [comment]
@Travis-A-Clark 
Please kindly review and update the template language and any additionl bind variables needs. Once you done, I will capture in the seeder for migration. Thanks

**Comment by Travis-A-Clark** [comment]
@jp-Telus I have finally updated the template language! Thank you for your patience.

One note: I don't think we need to have two templates for the goal controller. They ended up being identical we should be able to just use the EMPLOYEE_COMMENT one for all situations. 

Also, I have not been able to generate any emails in the Dev environment today. It looks to be enabled on the Org Access table, but actions just generate in-app messages not emails.

Please push these to test so that Steffi can start reviewing. Can we have the hard coded email address in the Test environment be for Steffi instead of me? Thanks!

**Comment by jp-Telus** [comment]
@Travis-A-Clark 

The template was seeder and will ready for deploying on other regions.

Here are my reply to your comments:

Item 1: I have changed tthe description on "SUPERVISOR_COMMENT_MY_GOAL" to "** NOT IN USE **" and changed all the template from  "SUPERVISOR_COMMENT_MY_GOAL"  to "EMPLOYEE_COMMENT" in the controllers.

Item 2: I think this could be related to the account preference setting, by default, the account preference, the first 3 option always default "unchcked", see the screenshot

![image.png](https://images.zenhubusercontent.com/60e73283e3a918390563e770/1367a878-2186-4c91-947a-cace67776875)

If still not working, could you please provide more detail for troubleshoot. Thank you.

Item 3: I have requested the TEST deployment via email. 

Thank you.

**Comment by Travis-A-Clark** [comment]
Thanks @jp-Telus! I think you are right that I hadn't updated the preferences for the employee I was using as test. I received a number of notifications this afternoon from Dev environment so I think it's working okay.

I did notice one issue with the SCHEDULE_CONVERSATION template. It looks like the binding for next conversation due date is displaying more information than just the date. Instead of just adding in "02-Nov-22" it is adding in "Next performance conversation is due by 02-Nov-22". See example below. Can it just add the date?

"The deadline to complete your next performance conversation is Next performance conversation is due by 02-Nov-22."

**Comment by jp-Telus** [comment]
Work done
The Due date in the email just the date portion without time. Fixed and migrated to TEST region.

**Comment by steffipravasi** [comment]
Have we missed to add the profile section in Account Preference?

1) User is not able to select the option "Shares my profile with another supervisor" in account preference alone.
Case1: If the employee is not a supervisor and the option is tried to be checked and saved, then the option is not stored. 
![Screen Shot 2022-09-14 at 11.37.48 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/0ef28695-f101-4504-a1e6-3811a5dd7528User: Indiana.King@gov.bc.ca)
Case2: If the employee is a supervisor and the option is tried to be checked and saved, then the site gives a 500 server error.
![Screen Shot 2022-09-14 at 11.39.11 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/34bb23eb-55b5-4126-9536-3423b1c27dda)

**Comment by steffipravasi** [comment]
The conversation part for employee and supervisor will be tested later as there is not much possibility of changing the conversation due dates. We'll be looking to solve the above listed issues first and then closing this ticket for now.

**Comment by jp-Telus** [comment]
The reported issues are resolved now and test in DEV region.

**Comment by Travis-A-Clark** [comment]
@telusdcinco As mentioned on Teams, hoping we can have the options for "one month..." and "one week..." default to selected rather than unselected as in the initial design. 

Also, between the title "Notifications" and the first list of options please insert the instruction: "All of the activities below will generate a notification on your PDP home page. Please indicate which activities should also generate an email notification for you."

**Comment by telusdcinco** [comment]
Pushed changes to Dev/Test for testing.
