### ISSUE TITLE
Updates to HR/Sys Admin > Improve Share Employees interface

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#637]
- [x] Change title of first tab to "Create New Share " and title of second tab to "View or Delete Existing Shares"

**Create New Share**

- [x] Update instructions at top of page: "Supervisors and administrators may share an employee's PDP profile with another supervisor or staff for a legitimate business reason. The profile should only be shared with people who normally handle employees' permanent personnel records (i.e. Public Service Agency or co-supervisors). An employee may also wish to share their profile with someone other than a direct supervisor (for example, a hiring manager). The employee's consent is required in order to do this."

**Updates to Step 1**

- [x] Update title to "Step 1: Select Employee(s)"
<br>

- [x]  Add instructions: "Use the search functions to find the employee(s). If you are managing the status of a single employee, you can click on the Yes/No under Share Status in the employee row to make the changes directly. Otherwise, select the employee(s) you want to manage and proceed to Step 2 below."
<br>

- [x] If user clicks Yes/No under Shared column, launch same share modal as My Team > Share modal.

**Updates to Step 2**
- [x] Change Step 2 to: "Step 2: Select shared supervisor". Add instructions below: "Select who you would like to share the selected employee(s) with. Then proceed to Step 3."
- [x] Remove Steps 2A and 2B.
<br>

- [x] Leave the rest steps 2, 3, and 4 areas on the page as is.
<br>

**View or Delete Existing Shares**

- [x] Add instructions: "Each row below is a separate shared relationship in the PDP. You can search by employee or delegated supervisor to find the relationship you are looking for and view or delete as needed."
<br>

- [x] Update search fields to: Employee ID, Employee Name, Delegate ID, Delegate Name. Default to Employee Name.
<br>

- [x] Enable multiselect / muti-delete so that Admin can search for and delete all relationships for an employee or delegated supervisor at once.

**Comment by jessicahjwu** [comment]
The arrows for sorting on the table under the "Manage Existing Employee Shares" tab aren't working. although the same function works under "Share an Employee" tab.

System Admin > Share Employees > Manage Existing Employee Shares

**Comment by telusdcinco** [comment]
@Travis-A-Clark 
I've restored the org details on the 1st tab and did not change the filter.  The first tab does not show duplicates at the moment.  Shared status is clickable to allow user to remove all shares for each employee.
Multi-select/delete added on the 2nd tab.

**Comment by telusdcinco** [comment]
Bug reported in #1000, was fixed in this ticket.

**Comment by steffipravasi** [comment]
Tracking the requirements in the document: https://bcgov.sharepoint.com/:w:/r/teams/02915/_layouts/15/Doc.aspx?action=editNew&sourcedoc=%7Bc053df23-4c67-4429-b5c0-13f3e792c00f%7D&wdOrigin=TEAMS-ELECTRON.teamsSdk.openFilePreview&wdExp=TEAMS-CONTROL&wdhostclicktime=1687377336743&web=1&cid=a5fd7403-09fc-420d-a441-ea426a990560

**Comment by steffipravasi** [comment]
Keeping this ticket in testing pipeline as Travis will be updating the requirements of it.

**Comment by Travis-A-Clark** [comment]
@telusdcinco I updated the description for the ticket. I believe the bullets below are the ones that require attention.

- [ ] Change title of first tab to "Create New Shares" and title of second tab to "View or Delete Existing Shares"

**Create New Shares**

- [ ] If user clicks Yes/No under Shared column, launch same share modal as My Team > Share modal.
<br>

- [ ] Change Step 2 to: "Step 2: Select shared supervisor". Add instructions below: "Select who you would like to share the selected employee(s) with. Then proceed to Step 3."
- [ ] Remove Steps 2A and 2B.

**View or Delete Existing Shares**

- [ ] Add instructions: "Each row below is a separate shared relationship in the PDP. You can search by employee or delegated supervisor to find the relationship you are looking for and view or delete as needed."
<br>

- [ ] Update search fields to: Employee ID, Employee Name, Delegate ID, Delegate Name. Default to Employee Name.

**Comment by telusdcinco** [comment]
@Travis-A-Clark All items done except for pop-up modal.  Fixing employee listing when modal is displayed.

![image.png](https://images.zenhubusercontent.com/60e88ef619e4760c8b3ee8bb/2022b296-6c80-4908-a6ac-e9ead9d2d4eb)

**Comment by steffipravasi** [comment]
Issue for HR and Sys admin
1)  Can we change the style for each tags in the share with section
![Screenshot 2023-07-05 at 10.58.54 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/8d29f010-a335-444b-a0d3-1b3e20fc2d8d)
For consistency we want the tag colour to be made blue just the way in Goals page for all the shared with modals
![Screenshot 2023-07-05 at 11.01.24 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/d1ede925-9ab4-4a45-a0f6-c44a424d46fc)
2) If a user is already being shared, then the Shared column in table displays Yes, but when we click on the Yes the modal does not show any users with whom the employee is shared with![Screenshot 2023-07-05 at 11.02.40 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/14fd2031-5d86-45bb-979a-0cb5f1d989df)![Screenshot 2023-07-05 at 11.02.56 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/ca033ba7-2df2-469a-a256-a98fbec8f404)
Expected result:![Screenshot 2023-07-05 at 11.05.00 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/553c2808-b74a-4029-bb6e-7d15af8a23a3)
3) The agreement checkbox in the modal is not validated. The modal must give an error if Share profile button is clicked without checking the agreement checkbox
Expected result:![Screenshot 2023-07-05 at 11.07.54 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/efd4ebf3-d249-4b6b-a583-d2024fb4b3e9)
4) Not able to share multiple employees at once. The shared column still displays No after sharing by using step 1,2,3 and the Share button
https://bcgov.sharepoint.com/:v:/r/teams/02915/Shared%20Documents/Product%20Team/Steffi%20-%20Testing/Screen%20Recording%202023-07-05%20at%2011.13.04%20AM.mov?csf=1&web=1&e=SlGlFm
5) Can we make the Delete selected button as a secondary button with app theme coloured![Screenshot 2023-07-05 at 11.21.38 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/ab0e7ce7-eea8-459e-9193-f75a4408f34a)

Testing blocked: Removing shared employees from the modal

**Comment by Travis-A-Clark** [comment]
@jizhaogit @steffipravasi 

Can we please prioritize this fix? We are training HR Admins tomorrow (Tuesday) and Thursday and this function is one of the key elements.

**Comment by telusdcinco** [comment]
There seems to be a commit missing in Test that did not make to Test.  Code changes reapplied in Dev and pushed to Test.

Also noticed that some changes for #637 got mixed with #977.  It would be best to migrate these 2 changes together.

**Comment by telusdcinco** [comment]
@steffipravasi @Travis-A-Clark 
Popup modal reflects the changes now in Test.  There was no logic change, except for the color change done today for the employee share listing and buttons on the modal page.

**Comment by steffipravasi** [comment]
@telusdcinco @jizhaogit Still facing this issues
1) The style for tags is still a little different. Cross/Cancel is overlapping the text![Screenshot 2023-07-11 at 1.04.12 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/b203957f-f674-4a41-99f5-21979134861a)
2) Not able to share multiple employees at once. The shared column still displays No after sharing by using step 1,2,3 and the Share button
https://bcgov.sharepoint.com/✌️/r/teams/02915/Shared%20Documents/Product%20Team/Steffi%20-%20Testing/Screen%20Recording%202023-07-05%20at%2011.13.04%20AM.mov?csf=1&web=1&e=SlGlFm
3) HR admin -> Share employees page is giving 500 server error![Screenshot 2023-07-11 at 1.26.22 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/4a745c8e-dd73-49bd-912c-6ddfb77a60d8)
4) The employee name in the Shared modal is missing![Screenshot 2023-07-11 at 1.32.42 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/d8b3a4a1-e44e-481a-8cec-9ab4921ed4a5)

Testing blocked for HR admin

**Comment by telusdcinco** [comment]
Fixed except for Item #1.

**Comment by jizhaogit** [comment]
@telusdcinco  #1 get fixed in DEV.

**Comment by jizhaogit** [comment]
@telusdcinco  #1 get fixed in DEV.

**Comment by telusdcinco** [comment]
@steffipravasi All changes pushed to Test.

**Comment by steffipravasi** [comment]
All the issues listed above have been validated on test for HR and Sys admin. 
Moving ticket for PO review.
