### ISSUE TITLE
Updates to HR/Sys Admin > Excuse Employees

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#638]
Update the Excuse Employee modules to align with new approach to excusing employees outlined in tickets #772 and #794.
<br>

- [x] Excuse New Employees tab is renamed to Managed Excused Status
<br>

- [x] Update search criteria drop down to include: Employee ID, Employee Name, Excused, Reason, Excused By
<br>

- [x] Update table columns: Employee ID, Employee Name, Classification, Organization, Excused, Reason, Excused By, Created At
<br>

- [x] Excused column is Yes / No. Clicking it launches the same modal supervisors see in ticket #794.
<br>

- [x] Reason column has 5 possible values: PeopleSoft Status (if excused based on inactive/leave status), Classification (if excused based on classification level), Casual Employee (if selected as part of manual excuse), Leave Not Captured in PeopleSoft (if selected as part of manual excuse), Student (if selected as part of manual excuse). See ticket #772.
<br>

- [x] Excused by has 2 possible values: System (if excused due to PeopleSoft status or classification), _EMPLOYEE NAME_ if manually excused
<br>

- [x] Created At is the date when excuse status began.
<br>

- [x] Manage Existing Excused tab is renamed View Excused History. Management of active excuse cases will be done through the redesign of the main tab. This tab should now have a view only list of past excused employees with start and end date.
<br>

- [x] Table columns: Employee ID, Employee Name, Classification, Organization, Excused, Reason, Excused By, Start Date, End Date
<br>

- [x] Search criteria drop down to include: Employee ID, Employee Name, Excused, Reason, Excused By
<br>

**Comment by telusdcinco** [comment]
Excused Reason column is not added as it is not currently kept historically.  Will require additional changes on the Conversation Due Date Calc process.  
The user name may not display correctly due to the stored data available.  May require a fresh Clac re-populate or trigger calc update by updating the manual Excused value.

**Comment by Travis-A-Clark** [comment]
Findings so far:
<br>

- HR Admin > Excuse Employees: processes for quite a while and then returns Ajax error without listing any employees.
<br>

- Selecting an org filter successfully loads employee list. However, launching the excused modal and then updating the excused status returns to an unfiltered employee list so it errors out again.
<br>

- There are three columns that currently are not displaying correctly (as per Dennis' comments above, these may still under construction): Reason, Created By, Created At

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/f5de69b3-d730-4680-95ab-0faf5c9688d8) 
<br>

- Search Criteria dropdown for things like Excuse Type does not filter results and returns an error message
<br>

- Please also remove the end of the sentence at the top of the page that says: "...during the date range selected".

**Comment by telusdcinco** [comment]
Still looking into timeout issue on Manage Excuse page.  The My Organization loads in Test, but still takes a long time to display.

Pending the page reload issue, clearing the selected criteria after saving the modal.

Excuse By column fixed.

Excused At column fixed.

Search text now working.  Looking into improving performance for HR Admin, currently pending.

Search criteria fixed.

"During the date range selected..."  removed from page.

**Comment by telusdcinco** [comment]
My Org page now loads in Test.

**Comment by steffipravasi** [comment]
Reason in the search criteria drop down missing
Expected: Update search criteria drop down to include: Employee ID, Employee Name, Excused, Reason, Excused By
![Screen Shot 2022-11-01 at 1.57.01 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/5f958095-ecc3-4f67-8933-c8c9d24d7bc6)

**Comment by telusdcinco** [comment]
@steffipravasi  The excuse reason was added to the search criteria.  Please reconfirm in Test.

**Comment by steffipravasi** [comment]
Env: Test
Excuse reason added to the search criteria drop down. 

@Travis-A-Clark Would you suggest the declaration statement to be changed to something else? I think the part 'during the date range selected.' does not make sense now
![Screen Shot 2022-11-01 at 4.44.47 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/03175c01-6d31-42c0-8eca-73c8538f308a)

**Comment by steffipravasi** [comment]
@Travis-A-Clark I have 2 questions for you. 
1) Example: If an employee (LeRoy,Zehra )has been excused by Travis Clark, and HR admin Heather Davey updates Zehra's excused reason, should the Excused By column display Travis or must be changed to Heather?
2) In the managed excused status tab: Select a filter and let employee list load -> launching the excused modal and then update the excused status -> Should the user be brought to the filtered list and searched criteria must remain until reset?

**Comment by Travis-A-Clark** [comment]
@steffipravasi 

1. I think we can leave this with the original person that excused the employee. We may have to add a column for "updated by" at some point in the future.
2. It would be great if the filters could stay in place, but this is not a make or break at this point. If it's a quick fix, then yes. Otherwise, future enhancement consideration.
3. Yes, let's add the reason column in.

When  looking at the page in Test this morning I noted a couple of things (not sure when they first appeared):

1. I see that the reason column is not being populated for Manual excused status. 
2. Clicking on the excuse reason column to sort it, it generates an Ajax error.
3. Clicking View Excused History also generates and Ajax error.

**Comment by steffipravasi** [comment]
Adding findings to this [document](https://bcgov.sharepoint.com/:w:/r/teams/02915/_layouts/15/Doc.aspx?action=editNew&sourcedoc=%7B1a94186a-7a5a-455f-b5f3-6d0bda6c1165%7D&wdOrigin=TEAMS-ELECTRON.teamsSdk.openFilePreview&wdExp=TEAMS-CONTROL&wdhostclicktime=1667409904243&web=1)

**Comment by telusdcinco** [comment]
Following changes ready for testing in Test.
- removing '- during the date range selected' from the Excused pages.
- adding Excused Reason column on the Manage Excused History
- filtering by Excused Reason on the Manage Excused History

**Comment by steffipravasi** [comment]
Test status: Pass
Env: Test

- Date range selected is removed
- The excused reason column is not left empty after the overnight process
-
