### ISSUE TITLE
Update "Need Help" Link on My Current Goals

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#643]
Please replace the current "Need Help" link on My Current Goals with: https://performance-332842-dev.apps.silver.devops.gov.bc.ca/resource/user-guide?t=2 where that will go to the User Guide and auto load the second tab about "My Goals Section".

I think the User Guide needs to have the tab links set still; it doesn't behave the same way as Goal Setting or Conversations resources when you add the ?t= at the end of the URL.

Let me know if you want to chat!

**Comment by acincotelus** [comment]
Deployed to DEV - "Need Help" link on My Goals>My Current Goals
