### ISSUE TITLE
As an employee, I want to see a welcome modal when I log on that tells me the latest news about the PDP

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#644]
Capturing our email conversation here. As discussed, in the future we may want to look at creating an interface in the System Admin Menu that allows the Admin to update the content of this message. Sort of like the notifications template section James set up for emails. Not urgent. For now, let’s just have the original message up for launch. Thanks!

----
Version 1.0 - July 18

Welcome to the Performance Development Platform (PDP)! Please check out the resources section and click on the info icons throughout the platform to learn more about all the new functions. 

Everything is in place for you to use the PDP to:
- Set work, learning, or career development goals and track progress against agreed upon measures of success
- Have the performance conversations you need to have when you need to have them

We will continue to make improvements to the platform in the coming weeks and months. Not everything will be perfect on day one. Please see below for a few things we are currently working on.

Updates planned for V1.01 
- Bringing all pages up to accessibility standards WCAG 2.1 AA
- Enabling and updating the “Excused” employee function
- Enabling the PDP email notification system; notifications are currently only displayed on your homepage 
- Improving various designs and page layouts

Thank you for your participation and patience as we work together to make the PDP a success!

**Comment by telusdcinco** [comment]
Deployed to Dev

**Comment by Travis-A-Clark** [comment]
Not showing in prod when logging in with Azure ID.
