### ISSUE TITLE
Add new homepage notifications

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#646]
In addition to the actions that currently generate homepage notifications, we need one for the following scenarios:

- A supervisor or delegated (shared) supervisor has added a goal to your goal bank. This can use the exact same format as the HR/Sys Admin has added  a goal to your goal bank notification that already exists.
<br>

- A delegated (shared) supervisor comments on your goal. This should be the same flag and message as when your direct supervisor comments on your goal.
<br>

- Your Next Conversation Due date is one month away
   Message: REMINDER - your next performance conversation is due in 1 month
<br>

- Your Next Conversation Due date is one week away
   Message: REMINDER - your next performance conversation is due in 1 week
<br>

- Your Next Conversation Due date is overdue
   Message: OVERDUE - your next performance conversation is past due
<br>

- An employee checks the box to "disagree" with a performance review. They see the pop-up shown below and we need to create the notification and email to go along with this.

Notification for home page should be:

_USER_ has selected the "disagree" option on a performance conversation with you.
Topic; Date

<br>

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/3c36656d-58dc-4bc7-aea8-45a044682353)

**Comment by Travis-A-Clark** [comment]
@jp-Telus Is it also possible to ensure that the status of the homepage notifications changes from "unread" to "read" after the user clicks "view" on the notification? It works for some of them but not all which makes it difficult to tell which notifications are new and which you have already looked at. Thanks!

**Comment by jp-Telus** [comment]
Two changes done and deployed on DEV region
----
1. The dashboard message added to supervisor when an employee checks the box to "disagree" with a performance review. 
2. To ensure that the status of the homepage notifications changes from "unread" to "read" after the user clicks "view" on the notification

**Comment by Travis-A-Clark** [comment]
Both these elements look good. Thanks!

Will wait for other elements to be implemented before pushing all to prod at one time.

**Comment by jp-Telus** [comment]
For item 3- 5 related to conversation due, it will be depend on the ticket #712, need to determine whether the in-App messages should add on the user's home page, currently only pilot group are allow ro login.

Working on Ticket 712 now.

**Comment by jp-Telus** [comment]
Completed the  Item 3 - 5, related to generate homepage notifications when the  Next Conversation is due in month, in week, or overdue. This process was schedule on daily basis (run at 1:00am daily), and the logic and table was created for keep track the homepage notifications, avoid message generated multiple times. And also the generated message also log in the tables, the page for review that is located
Menu > System Administrion > Notifications > View Past Notification

Push to DEV region

Migration Notes
1. php artisan migrate 


Pending Item (1) and (2), need some clarification and way to create the test data. 

Thanks

**Comment by jp-Telus** [comment]
Completed Item 1 and 2 

_Item 1_
The message was added to the user home page, when a supervisor or delegated (shared) supervisor has added a goal to your goal bank. 

_Item 2_ 
The message was added to the user home page when a delegated (shared) supervisor comments on your goal. And also fixed the issue related to the new added conversation homepage message always marked as "read" in the GoalController..

Deployed to DEV on Aug 4, 2022

**Comment by Travis-A-Clark** [comment]
@jp-Telus I realized there is one additional notification that would be good to have if possible. Let me know if there are any issues. Thanks!

When an employee profile (goals, conversations, or both) is shared with a delegate supervisor.

Message to show: 
Your profile has been shared with _USER_
Date; elements (goal, conversations, full profile)

**Comment by jp-Telus** [comment]
@Travis-A-Clark. The followings were completd and deployed on DEV region related to shared employee profile:

1. Home page notification was added to employee when his profile was shared by using "Share Employees" in System Administration 
2. Home page notification was added to employee when his profile was shared by using "Share Employees" in HR Administration 
3. The Home page was updated for display the Shared Profile notification message

Thanks.

**Comment by Travis-A-Clark** [comment]
@jp-Telus Everything seems to be working in Dev. I haven't been able to test the conversation due date notifications since all of the dates are too far out. Perhaps I can get @telusdcinco to manually override a few dates in the Dev environment so that I can see it in action.

For the notification that an employee profile has been shared, can we also trigger this when a supervisor shares the profile through the My Team > Team Members area? We have it for when HR/Sys Admin share the profile, but not currently for when the supervisor shares the profile.

**Comment by jp-Telus** [comment]
The program was updated and deployed on DEV region:

-- the new dashboard notification was added when a supervisor shares the profile through the My Team > Team Members area, similiar to HR/SYSAdmin sgare the profile.
