### ISSUE TITLE
Text updates for Resources > User Guide

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#647]
Some edits to the text after having a chance to reflect for a day or two. Thanks!

- [x]  In the Welcome section. Remove "feel free to" from this sentence: If you have technical trouble, please "feel free to" Contact Us and we will do our best to help.
<br>

- [x]  My Goals Section > My Current Goals > Add an additional line space before the "My Current Goals" underlined header.

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/5e348313-9df6-4944-920e-4b919519f335)
<br>

- [x]  My Goals Section > My Current Goals > Bullet 2. Remove "just" from this sentence: Some goals will be marked as mandatory, but most are" just" suggested starting points for you to consider.
<br>

- [x] My Goals Section > My Past Goals. Add the word "list" to this sentence: This "list" can be a useful reference point to recall all the work you’ve done when preparing for performance conversations or applying for a new position.
<br>

- [x] My Goals Section > Goal Bank. Remove the word "just" from this sentence: Some goals will be marked as mandatory, but most are "just" suggested starting points for you to consider.
<br>

- [x] My Conversations Section. After this sentence "The My Conversations section is designed to support employees and supervisors to have the right conversation at the right time." add this sentence "Visit the [Performance Conversations ](https://performance-332842-dev.apps.silver.devops.gov.bc.ca/resource/conversations)resource for more information on best practices."
<br>

- [x] My Conversations Section > Conversation Templates. Add an extra line space before the "Conversation Templates" underlined header.

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/a752e54e-2254-41f1-bc5f-1b02de144f7a)
<br>

- [x]  Please also rename the Resources > Conversations tab to Resources > Performance Conversations

**Comment by acincotelus** [comment]
Deployed to DEV
