### ISSUE TITLE
Add scroll bars to list of tags

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#665]
The list of tags is now long enough that it runs out of room, especially at higher magnification in the browser. This is true everywhere the tags dropdown is in place. Can we add a scroll to the list of tags drop down?

**Comment by jizhaogit** [comment]
1. apply scrollbar in my goals -> create new goal modal
2. apply scrollbar in goals bank -> add goal to bank modal
3. apply scrollbar in HR admin -> goal bank -> add goal to bank
4. apply scrollbar in Sys admin -> goal bank -> add goal to bank

**Comment by steffipravasi** [comment]
Test status: **Pass**
Test environment: Test
The scrollbars are added in the list of tags, goal modal and share modal.
![Screen Shot 2022-08-08 at 5.10.23 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/bb3e8708-95bc-4a5a-936b-0388c67e15e4)
