### ISSUE TITLE
Add auto save to text fields in My Conversations > Open Conversations

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#667]
Currently a user has to click the save button to commit their changes. If they don't, the could accidentally sign-off the conversation without actually saving their comments. Can we ensure that clicking outside the text box will auto save what is inside?
<br>

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/ef810019-a27b-4cca-8349-6bfbe50b65dd)

**Comment by steffipravasi** [comment]
@Travis-A-Clark Are we looking to save the data in the text field only when the user clicks the "x" button on top or the "Sign with my employee id" button? 
If we try to save it right when the user clicks anywhere outside the comment box, then the Cancel button will be of no use unless we hide both the buttons when auto save is done. But then what if user didn't intend to save it?

**Comment by Travis-A-Clark** [comment]
@jizhaogit As per our team discussion, there are actually two things required for this ticket:

1) Remove the Save and Cancel buttons; save content when user clicks outside of the text box

2) Create a time-based autosave function so that users don't lose information when their session times out.

**Comment by jizhaogit** [comment]
as talked in the meeting.  now we set autosave processing in every 15 minutes.

**Comment by steffipravasi** [comment]
Completed conversations should not be editable without un-signing the conversation. Right now, users can edit the conversation without un-signing and can type in the answers. The answers gets stored in the conversation by auto save after 15 mins. They are not stored when the cancel or “x” button is clicked though. 
![Screen Shot 2022-09-09 at 1.13.58 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/7874b73d-ad5d-4873-91d2-f60cd110e4f1)

**Comment by jizhaogit** [comment]
@steffipravasi  thanks for the testing.  would you advise should we disable the radio option selection on the signed conversation?

**Comment by steffipravasi** [comment]
@jizhaogit I think yes, as far as my understanding changes should only be made after un-signing the conversation :)

**Comment by steffipravasi** [comment]
Test status: PAss
Changes can only be made after un-signing the conversation. The auto save option does not populate for signed and completed conversations.

**Comment by jizhaogit** [comment]
@Travis-A-Clark Our current session time base auto save message is: **Your comments is autosaved.**

**Comment by Travis-A-Clark** [comment]
@jizhaogit Can we please change to: Your comments have been autosaved.

Thanks!

**Comment by jizhaogit** [comment]
done and ready for testing.

**Comment by steffipravasi** [comment]
@Travis-A-Clark the message has been changed to 'Can we change the message when closing the conversation window to: Save your comments before closing?'. Is the Yes/No supposed to be the name of the 2 buttons? 
 ![Screen Shot 2022-09-23 at 10.29.13 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/2792e530-f337-405f-9eb1-693abd3bd29b)

**Comment by Travis-A-Clark** [comment]
@steffipravasi Yes, the intention was to have the two button options named Yes and No. Thanks!

**Comment by jizhaogit** [comment]
@Travis-A-Clark the confirm box is defaulted and not able to custom button lables.
ref: https://html.spec.whatwg.org/multipage/timers-and-user-prompts.html#dom-confirm

Should we change the notify content?

**Comment by Travis-A-Clark** [comment]
@jizhaogit Let's change the notification to: **Click "OK" to save content and exit. Click "Cancel" to exit without saving.**

**Comment by jizhaogit** [comment]
new content changed and ready for test.  Thanks!
