### ISSUE TITLE
My Goals > Goal Bank > Add Goal to Bank: incorrect version of info toggle tips

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#672]
The toggle tips in PROD on the add goal to bank modal are from a previous version. Slightly different content and different functionality (see below). They should be the same as the toggle tips on My Current Goals > Create New Goal.
<br>

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/b70ab42f-e58a-446c-9ffe-d4370023bd57)

**Comment by acincotelus** [comment]
Deployed to DEV

**Comment by acincotelus** [comment]
updates deployed to Test environment
