### ISSUE TITLE
Assigning HR Admin access automatically creates My Team tab even if user is not a supervisor

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#673]
This wasn't the case before, but now when I grant a user with no direct reports HR Admin access, they also get the My Team navigation added to their navigation bar. When clicked it gives the error below (since they don't have any direct reports or employees shared with them).
<br>

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/9f680b20-fe1e-4cca-8575-7001d7ddd7e4)

**Comment by steffipravasi** [comment]
Test status: Fail
Env: Test
@jizhaogit 
Users: Stefanie.Cepeda@gov.bc.ca, Lauren.Stocks@gov.bc.ca
The above users have 0 direct reporters. When they are assigned an HR admin access with one organization, we can see all the HR admin tabs, but there is no employee data available in the list nor the assigned organization can be seen.
![Screen Shot 2022-09-13 at 12.37.59 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/6a5270d5-308d-48ea-b5ce-3e528f31fd3b)

Also, If the same user is assigned a different org, then the org list must show all the assigned business units in the list.
