### ISSUE TITLE
Errors in prod when deleting an HR Admin goal from goal bank

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#682]
When deleting a goal added to the goal bank by HR Admin, the logs in production show issues related the goal, like tags, shared with etc.

**Comment by telusdcinco** [comment]
Fixed change pushed to Dev

**Comment by Travis-A-Clark** [comment]
As discussed, this issue re-emerged when HR Admin from Social Development added a goal. He was prompted to confirm the delete, said yes, but the goal was not removed.
