### ISSUE TITLE
Test updates for Resources - User Guide - Part 2

### ISSUE THREAD

**Issue by Abuchana** [bcgov/performance#689]
![image.png](https://images.zenhubusercontent.com/6005ca03d883b372a058fe50/b31c1d4e-6561-4755-ba97-c75f5e48cdfb)
This should read: "display as a clickable card"
![image.png](https://images.zenhubusercontent.com/6005ca03d883b372a058fe50/86f92fa9-c876-465e-97ef-7cc777c50cbe)
This should read: "you can reactivate"
![image.png](https://images.zenhubusercontent.com/6005ca03d883b372a058fe50/276f0a16-b882-42e0-b771-9ef0c223a304)
This should have a period at the end of the sentence

**Comment by acincotelus** [comment]
ready for deployment (DEV) the following updates:

- My Current Goals
![image.png](https://images.zenhubusercontent.com/622f754395f085119242a764/345e29f0-5cf3-4cb4-8a29-d1c7c29fc6a4)

- My Past Goals
![image.png](https://images.zenhubusercontent.com/622f754395f085119242a764/881d5e74-4de0-4388-9020-952ee0475712)

- Open Conversations
![image.png](https://images.zenhubusercontent.com/622f754395f085119242a764/43d1776a-3a01-4a6f-90ab-75e88941f7cc)

**Comment by acincotelus** [comment]
deployed to DEV

**Comment by acincotelus** [comment]
updates deployed to Test environment
