### ISSUE TITLE
HR/Sys Admin > Goal Bank > Manage Existing: editing goal defaults to "mandatory" status

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#690]
When I save a goal, I can save it as either mandatory or suggested. No matter what I save it as, when I go to edit it, it defaults back to "mandatory", That means that, unless I remember to always switch back to "suggested" the status could unintentionally be changed.

**Comment by telusdcinco** [comment]
Fix deployed to Dev and Test.

**Comment by Travis-A-Clark** [comment]
Looks like it works in Test. Thanks!
