### ISSUE TITLE
HR/Sys Admin functions: clicking "select all" ignores filters and selects all employees

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#692]
Scenario: using any of the HR/Sys Admin functions the include selecting from an employee list. I can add filters to select organization, level 1, 2, 3, etc. and the results in the employee list are filtered. However, if I "select" all for that filtered list, the action is performed on every single employee I have access to, not just the ones displayed on the list.

**Comment by telusdcinco** [comment]
Fix pushed to Dev and Test

**Comment by Travis-A-Clark** [comment]
@telusdcinco was this fix pushed for all the different HR/Sys Admin pages? I think it works on Goal Bank, but not in other areas liked Shared Employees (where I just shared the entire public service with myself).

**Comment by telusdcinco** [comment]
Yes, I still have not pushed this to other than Goal Bank.


Thanks and regards,

Dennis Cinco
L4 Software Development - TELUS
O: +1 (604) 453 2149   M: +1 (778) 980 8585

Visit us today at telussourcingsolutions.com - the future is friendly®
telus.com<http://telus.com/>  Facebook<https://www.facebook.com/telus>  Twitter<https://twitter.com/telus>  YouTube<http://www.youtube.com/telus>  Linkedin<https://ca.linkedin.com/company/telus>

P Please consider the environment before printing this email.

This email is for the sole use of the intended recipient and may contain confidential, proprietary and/or privileged information. If you receive this email in error, please contact the sender and delete this message from your computer.

**Comment by Travis-A-Clark** [comment]
Thanks, Dennis. It seems to function as intended on the add goal to goal bank area. Using select all selects all those displayed on the page, whether it is 10, 25, 50, or 100. The manage existing goals > edit goal area, as well as all the other functions for HR/Sys Admin still need the fix as discussed.

**Comment by telusdcinco** [comment]
Fixes for below, pushed to Dev and Test.
- HR/Sys Admin Edit Goal by Individual
- HR/Sys Admin Share Employee
- HR/Sys Admin Excuse Employee
