### ISSUE TITLE
HR/Sys Admin > Add Goal to Goal Bank: business units are not mapping correctly

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#693]
Scenario: as a Sys Admin I add a goal to the goal bank and select audience by business unit. The goal is created and saved, a notification is posted to the employee's home page, but the goal is not displayed in the employee's goal bank and they are not able to view or add it to their profile.

**Comment by telusdcinco** [comment]
Fix for HR and Sys Admin Goal Bank:  Correctly assign BU to goals  when creating and updating the goals.
Fix deployed to Dev.
