### ISSUE TITLE
HR/Sys Admin > Add Goal to Goal Bank: add supervisor / non supervisor as a variable for selecting individual audience

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#701]
We currently identify supervisors in the PDP based on the info coming from ODS as well as whether they are identified as a delegate supervisor in the PDP itself. If either of those things are true, we grant access to the My Team tab of the app. Can we use the same logic to identify supervisors in the Individual Audience of the Goal Bank and include it as a column in the table? Column header "Supervisor" with values "Yes" or "No". We could then use this variable as a selection criteria for pushing goals out to individual audiences.

**Comment by jizhaogit** [comment]
@telusdcinco it look good to me. please go ahead for the migrate. thanks

**Comment by steffipravasi** [comment]
The goal bank page does not load and gives a 504 error for HR admin and Sys admin
![Screenshot 2023-03-07 at 10.49.34 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/24cef373-87d8-485e-9ac3-247b3703c945)

**Comment by jizhaogit** [comment]
@telusdcinco @steffipravasi related issue reported in ticket #916 
https://app.zenhub.com/workspaces/performance-development-60020b0a13a09c0014af2469/issues/gh/bcgov/performance/916

**Comment by steffipravasi** [comment]
@telusdcinco The checkbox for Direct Supervisor looks a little off as it is not aligned with any element and is quite far from other elements from top and left side
![Screenshot 2023-03-08 at 1.47.57 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/089ff686-0ea9-4044-a46d-3cfa9fae7330)

**Comment by Travis-A-Clark** [comment]
@steffipravasi @telusdcinco Would it be possible to add a drop down menu before "Search Criteria" on the left called "Supervisor Status" with the options All, Supervisors Only, Non-Supervisors Only?

**Comment by telusdcinco** [comment]
@steffipravasi @Travis-A-Clark I'll make the changes and show in Test tomorrow.

**Comment by telusdcinco** [comment]
Completed changes required.

![image.png](https://images.zenhubusercontent.com/60e88ef619e4760c8b3ee8bb/72ef56f6-8ef7-41cf-bcdb-cf3b8edc6d40)

**Comment by steffipravasi** [comment]
The Goal bank page for HR Admin is not loading at all and gives a 504 Time out error. 
![Screenshot 2023-03-13 at 12.18.03 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/07381659-8029-4d08-bfc0-a8da00cb1d1f)
Testing blocked.

**Comment by steffipravasi** [comment]
Ticket validated.
The Supervisor status field is added to the Goal bank page for HR admin and Sys Admin![Screenshot 2023-03-13 at 12.26.30 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/110c3a91-73c8-4e1a-b632-9531d4de9030)

Moving Ticket for PO review

**Comment by Travis-A-Clark** [comment]
@telusdcinco To confirm for this ticket: when I select "Supervisors Only" is it also showing me supervisors that have no direct reports from PeopleSoft but that have been delegated as a supervisor (employee shared with them) in the app?

**Comment by telusdcinco** [comment]
@Travis-A-Clark @steffipravasi Added "delegated" managers to the Supervisor list when filtered.

**Comment by telusdcinco** [comment]
@Travis-A-Clark   Please let me know if 'Supervisor Only' and 'Non Supervisor Only' labels are confusing, when the app actually filters the Designated managers also.  Example below, the employee is not a Manager so it shows 'No' under Supervisor column, but shows up if Supervisor Only is selected.

![image.png](https://images.zenhubusercontent.com/60e88ef619e4760c8b3ee8bb/5fdca0d9-4c99-4765-9cbc-377948e90bcc)

**Comment by Travis-A-Clark** [comment]
@telusdcinco Good catch. Let's do two things:

1. Change the drop down options to: Has Reports in PDP / Does Not Have Reports in PDP
2. Add an info toggle tip that says: This filter includes direct reports from PeopleSoft and delegated reports in the PDP.

**Comment by steffipravasi** [comment]
Test staus: Pass
Drop down and tool tip added to supervisor status:
![Screenshot 2023-05-02 at 10.39.19 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/db5db056-9fa6-48d2-896b-c2c04ad3116c)![Screenshot 2023-05-02 at 10.39.27 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/5326cf60-890c-4c39-88f4-8d2ea2c8e610)
Test validated for HR admin and Sys admin
