### ISSUE TITLE
Text update for Resources > User Guide > My Team Section

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#702]
At the end of the Shared Status section, please add the sentence:

"If you require assistance with sharing an employee, please submit a ticket through [AskMyHR](https://www2.gov.bc.ca/gov/content/careers-myhr) to My Team or Organization > HR Software Systems Support > Performance Development Platform."

**Comment by acincotelus** [comment]
Deployed to DEV
Text update for Resources > User Guide > My Team Section
![image.png](https://images.zenhubusercontent.com/622f754395f085119242a764/7deb9c08-001c-472f-8cf8-390b3576481f)

**Comment by Travis-A-Clark** [comment]
@acincotelus Can you please create a new paragraph for that sentence. Thanks!

**Comment by acincotelus** [comment]
Updates deployed to DEV. - new paragraph for the new sentence (see below screenshot).

![image.png](https://images.zenhubusercontent.com/622f754395f085119242a764/d15e1a2c-4b8c-497e-8784-bc28a766828d)

**Comment by acincotelus** [comment]
updates deployed to Test environment
