### ISSUE TITLE
HR Admin > Statistics and Report: Excel downloads return 500 Server Error

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#703]
The only excel file that is being generated is the Shared Employees report. All others in Goals, Conversations, and Excused generate error message like below. Don't know if it's relevant, but the end of the URL generated for that page looks odd with the three commas for an ID. Everything works for Sys Admin.

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/6f880d82-f28b-498f-9352-1db0d40f89c7)

**Comment by telusdcinco** [comment]
Ambiguity issue (org levels) in the backend SQL.

**Comment by telusdcinco** [comment]
Ready for test in Test.
