### ISSUE TITLE
(TEST) - My Goals > Goal Bank - filters and search no longer work

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#704]
The filters and search are not working on the My Goals > Goal Bank page in the TEST environment. They are working in PROD so something recent has caused them to break.

Also, is there any pagination in place if the list of goals in the goal bank gets super long? Can we add in pagination after 10 goals like we do for employee lists and whatnot in other areas?

**Comment by telusdcinco** [comment]
Fix deployed to Dev and Test

**Comment by Travis-A-Clark** [comment]
@telusdcinco filters and search look like they are fixed in Test. Thanks!

**Comment by telusdcinco** [comment]
Fixed the missing Admin BU goals from My Goals>Goal Bank.  Deploying to Dev and Test.
