### ISSUE TITLE
(TEST) - HR/Sys Admin > Goal Bank - serious performance degredation

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#706]
In the TEST environment, loading the Add Goal to Goal Bank has slowed quite a bit and the Manage Existing Goals has slowed a ton (15-20 second load times...sometimes returning Ajax error). The more goals added to the bank, the slower it is getting. Sys Admin will have to deal with hundreds of goals, and it's already crashing with 8 or 9.

Can we do a code review to see what is using all the computing power and slowing everything down?

**Comment by telusdcinco** [comment]
Replaced Business Unit Audience count from employee count to BU count.  Deployed to Dev and Test.

**Comment by Travis-A-Clark** [comment]
@telusdcinco the BU count has sped things up a ton. Very nice!

There is a problem though: goals added by BU are no longer being displayed in the employee goal banks. The ones that displayed before no longer showed up, and I created a new on in TEST called "Sys Admin BU Test 2 - July 20" assigned to Public Service Agency, and it doesn't show up either. It's back to generating a notification on the homepage for the users but not showing up in their goal bank.

Can you please take a look to see what's up? Thanks!
