### ISSUE TITLE
My Goals > Goal Bank - Add supervisor name to Created By list

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#707]
The Created By field has been switched from pulling employee ID to having a dedicated Created By variable associated with it. It is pulling and displaying these names for HR and Sys Admins who add goals to the goal bank. We also need it to pull and display the names of supervisors who add goals to their team's goal bank.

It seems to work in Dev, but not in Test or Prod.

**Comment by telusdcinco** [comment]
After retesting the assignment for Created By field, the function seems to be working fine in Dev and Test.  I will be looking into Prod data to see if there are recent Goals created by Supervisors, and confirm if the Created By column is being populated properly.

**Comment by Travis-A-Clark** [comment]
@telusdcinco Agree, it looks good in Dev and Test. Also checked Prod and it is working. Must have been a version control thing in the past. Sorry about that!
