### ISSUE TITLE
HR/Sys Admin: work to normalize number of employees listed across functions

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#708]
Depending on the function (i.e. employee list, shared employees, statistics and reporting) the number of employees for an organization varies. We believe this is due to different ways that info is being filtered and employees are being identified (GUID vs employee ID for example).

We need to explore and determine a single way of counting and displaying employees so that the counts match across the platform.

**Comment by telusdcinco** [comment]
@Travis-A-Clark 
Please confirm if this ticket is still necessary.  We have moved away from using GUID as a key identifier.  
Most of the modules are now using the same view to populate the employee lists, so the count should match.  Statistics and Reports is an exception, as most of its queries requires specific aggregation functions.  The count issue in Stats and Report is currently covered by an active ticket.
