### ISSUE TITLE
(TEST) - My Team > Shared and Excused modals: text formatting has been lost

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#709]
In test environment, the formatting for the modals has been lost, It is all bold text. It still looks good in production. I don't want to inadvertently push the bad version from test into prod at any point, so can we please fix in test? Same with the Excuse modal.

What it looks like in test (incorrect):

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/33a40a75-24ff-44fc-9c1b-f7675d622bfb)

<br>

What is looks like in prod (correct):

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/f3266beb-9f6d-4cb3-bc01-b13977669e8c)

**Comment by acincotelus** [comment]
@Travis-A-Clark  fix to the text format on My Team > Shared and Excused modals (issue related to #672) - deployed to DEV

**Comment by acincotelus** [comment]
@Travis-A-Clark - deployed to TEST
