### ISSUE TITLE
Add hyperlinks option to the text editor

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#711]
Please add the function to add hyperlinks when creating/editing goal descriptions and measures of success.

**Comment by Travis-A-Clark** [comment]
This looks good in Dev! Please push through to test and prod. Thanks!

**Comment by Travis-A-Clark** [comment]
@jizhaogit It looks like there is one place that the hyperlinks didn't get added to the editor. As HR or Sys Admin > Goal Bank > Manage Existing Goals. If you open a goal to edit it, the hyperlink option is not there and any hyperlinks that were previously in place disappear.

This isn't urgent, but can we add here as well? Thanks!

**Comment by jizhaogit** [comment]
@Travis-A-Clark , the link button is applied in HR/Sys admin > Goal Bank > Manage Exisiting Goals page.  pushed in dev.

**Comment by Travis-A-Clark** [comment]
Thanks, Ji! Looks good.
