### ISSUE TITLE
Text Edit > Replace "ticket" with "service request"

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#713]
We have received a request from our colleagues at our contact center to change a small thing in our application. In the Contact Us and in the User Guide we use a phrase like "submit a ticket through AskMyHR" and they want us to replace "ticket" with "service request". I think it also shows up in places like the info tool tip for Current Supervisor on the homepage.

Can you please do a search for the word "ticket" and replace with "service request" so that it reads "submit a service request through AskMyHR"?

Thank you!

**Comment by acincotelus** [comment]
@Travis-A-Clark Deployed to DEV
updates on the following (for keyword: ticket):
- Dashboard>My Current Supervisor tooltip
- Resource>Contact 
- User Guide>My Team Section (Shared Status) 

Please review and advise if you also want to change/update the text on the following:
- My Conversations>Completed Conversations 
![image.png](https://images.zenhubusercontent.com/622f754395f085119242a764/cda7d668-42e3-4b70-bfba-b3a67ce9b6f8)

- Resource>User Guide>My Conversations Section>Completed Conversations
![image.png](https://images.zenhubusercontent.com/622f754395f085119242a764/97c662ff-1b34-44cd-9f20-903f5317512d)

**Comment by acincotelus** [comment]
@Travis-A-Clark Deployed to TEST
updates on the following (for keyword: ticket):
Dashboard>My Current Supervisor tooltip
Resource>Contact
User Guide>My Team Section (Shared Status)

**Comment by Travis-A-Clark** [comment]
@acincotelus Good catch on those other two spots! Yes, please update "request" to "service request" so that we are consistent. Thanks.

**Comment by acincotelus** [comment]
@Travis-A-Clark Deployed to DEV and TEST
updates on:
My Conversations>Completed Conversations
Resource>User Guide>My Conversations Section>Completed Conversations
