### ISSUE TITLE
As an employee, if I report to a vacant position, I want my supervisor to default to the next highest person in the org hierarchy

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#714]
To mimic current MyPerformance logic. If a position is vacant, the employees that report to that position are automatically assigned to the supervisor of the vacant position.

**Comment by kevindavidb** [comment]
Travis, the legacy system originally worked this way and it was one of the first things I remember being asked to change. The impact was that all the reporting gaps rolled upwards, and senior people had extremely long "My Team" lists. It is not uncommon to have two vacancies in a row, for instance.  Instead, we implemented the Vacancy strategy, where a dummy ID in performance held the spot in the hierarchy (these are the V-#s)
