### ISSUE TITLE
My Conversations > Open Conversations - Add text editors to input boxes

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#715]
Apply the same text editor from the Create New Goal area to the text fields in all the conversation templates.

**Comment by Travis-A-Clark** [comment]
@jizhaogit When an employee enters comments in the conversation input box, the text editor is there and the comment looks correct. However, when the supervisor views those comments, the text is not displayed properly. All of the formatting tags are displayed (see below). This is also true when a supervisor enters comments and an employee views them.

<br>

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/a9f221f9-01e0-454e-8b48-6d2279eede00)

**Comment by jizhaogit** [comment]
apply ckeditor to readonly input field for displaying right content without html tags
