### ISSUE TITLE
My Goals > Goal Bank > Team Goal Bank - Remove toggle tip

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#719]
Please remove the toggle tip from the "Add Goal to Bank" button. The description is already displayed above the button. Thanks!

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/db5917e8-1002-432b-a5b6-c961b4d8dca5)

**Comment by acincotelus** [comment]
@Travis-A-Clark updates deployed to DEV and TEST

**Comment by Travis-A-Clark** [comment]
Thanks, @acincotelus !
