### ISSUE TITLE
HR/Sys Admin > Statistics and Reporting - Improve "Print" layout

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#720]
The Print to PDF option in the Statistics and Reporting area functions as intended, but the formatting and layout for the PDF is not very attractive or user friendly (see below for screenshot of page 1 of the Goals report). Do we have the ability to provide formatting / spacing options for the PDF to make the function more useful for those wanting to share reporting information in PDF email attachments, etc?

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/b8cfd100-8c7c-4294-aff0-a41605de59a4)

**Comment by jp-Telus** [comment]
Investigating how to print out the dynamic generated graphic (ajax), there are couple of pakcage but required special software install on the HOST (Linux):

1) mikehaertl/phpwkhtmltopdf -- The wkhtmltopdf and - optionally - wkhtmltoimage command must be installed and working on your system. 

2) barryvdh/laravel-dompdf  -- this one no special package need on the OS platform but can print the dynamic graphic 

3) jspdf + canvas (html2img) -- pure javascript solution, compatible issue with other javascript library.

**Comment by jp-Telus** [comment]
Try to use seperate style to control the printing output with the browser built-in print function. The seperate style to control:
1. don't print filter
2, better page break, no break on the chart
3. add the title and generate date on the print output   

Deployed on DEV. Please review and comment

**Comment by Travis-A-Clark** [comment]
@jp-Telus I think this is a definite improvement. We might come back to try to improve again later, but it's not a priority at the moment given all the other work to do. Thanks for this!
