### ISSUE TITLE
Sys Admin > Goal Bank > Manage Existing - Individual audience search/filters don't work

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#722]
When I go to edit/delete individuals for an existing goal bank goal, the filters and search don't work. See below where I've entered a bunch of random search criteria but the list below remains unchanged. Seems to work for HR Admin, just not Sys Admin.

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/2a79d9cf-9f1e-4f11-ab71-a9adb5f07b53)

**Comment by steffipravasi** [comment]
Test status: PAss
All the search filters for modify goal are working fine now along with the Reset button. Tested for individual and business unit.
Ticket ready for PO review

**Comment by Travis-A-Clark** [comment]
Everything looks good. Will move to production at end of sprint.
