### ISSUE TITLE
Home > Notifications: users are incorrectly receiving notifications for goals added to other business units

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#726]
Scenario: an HR admin in SDPR has access to the Accessibility Directorate and the Research, Innovation and Policy Division. They added a goal to the goal bank for those business units. The goal was added to those employee's goal banks successfully. However, SDPR employees in all of the other divisions also received the same notification on their home page even though the goal was not meant for them and did not get added to their goal bank.

The add goal function looks to be working, but the notification is being sent to too many people.

**Comment by telusdcinco** [comment]
Fix deployed to Dev and Test.
