### ISSUE TITLE
My Goal > Goal Bank: auto sort by dated added column

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#727]
Let's default to having the newest goals listed at the top of the page.

**Comment by steffipravasi** [comment]
Test status: **Fail**
Test environment: Test
The Goals list in the Goal Bank are sorted in a descending order.
Expected result: The newest goals should be listed at the top of the page. This should be the default sort.
Actual result: The newest goal is displayed at the bottom of the list.
![Screen Shot 2022-08-08 at 9.57.05 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/abe358dc-cc3c-4b21-a350-1f176d01a332)

**Comment by Travis-A-Clark** [comment]
@jizhaogit the sort still doesn't seem to be working. See screen shot below where the goal added on Aug 10 is in the middle and the oldest goals are still on top. Should be newest on the top, oldest on the bottom. Thanks!

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/a4e4657d-59b6-44d4-93e2-e8243f712d6e)

**Comment by jizhaogit** [comment]
modified query to fitting with UI request
