### ISSUE TITLE
Tags dropdown tooltip on Sys Admin>Goal Bank>Add a New and Manage Goals (Edit)

### ISSUE THREAD

**Issue by acincotelus** [bcgov/performance#730]
When user edit a goal with tags, the Tags dropdown tooltip does not close when you click anywhere on the page. 
![image.png](https://images.zenhubusercontent.com/622f754395f085119242a764/e1e82ffa-1d5b-4990-92c2-6ff5ecdb10a1)

Update the Tags dropdown tooltip (same as My Goal>Create New Goal and Edit Goal Add New Goal ) on Sys Admin>Goal Bank and HR Admin Goal Bank (Add and Manage Goals)

**Comment by acincotelus** [comment]
@Travis-A-Clark updates deployed to DEV and TEST
Sys Admin/HR Admin
Goal Bank > Add a New Goal
Goal Bank > Manage Goals (Edit Goal)

**Comment by Travis-A-Clark** [comment]
Looks good. Thanks!
