### ISSUE TITLE
HR/Sys Admin > Statistics and Reporting: shift to chron job to create HR Admin access

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#731]
**THIS HAS BEEN DEPLOYED TO PRODUCTION - Sept 23, 2022.** Keeping ticket open to discuss enhancements and will create new ticket for new work if required. Additional work moved to ticket #809.

Purpose

- Create a chron job to sync HR Admin access with correct employees for statistics and reporting to speed up load times.

Result

The new schedule process (chron job) called (command:BuildAdminOrgUsers) was schedule at 1:30am everyday. This process is based on the "Access and Permissions" setting (table: admin_orgs) and also the Shared Profile (table: shared_profile) to collect and normalize the relationship of the user and their authorized employees.

**Comment by jp-Telus** [comment]
Work done so far
1. Identified the slowness query, mainly the time used in checking access security (admin_orgs). 
2. create a process (name: command:BuildAdminOrgUsers) and new table called admin_org_users to be pre-populated the assigned employee to the the granted user, also including the delegated employee (shared Profile) assigned to the granted user 
3. also add the new process to run daily after the user profile sync process
4.  update the statictics and reporting page by using the new pre-populate security table

Result: 
Average speed on the Goal Tag : 5 secs
Average speed on the Conversation Tag : 2 secs
Average speed on the Shared Profile Tag :  1 sec
Average speed on the Conversation Tag :  1 sec

**Comment by Travis-A-Clark** [comment]
@jp-Telus Does this chron job also take care of populating the reports themselves once an hour rather than in real time? As in, if I open the Goals Summary page, is it loading a real time data pull or chron job info about active goals, etc?

**Comment by Travis-A-Clark** [comment]
@jp-Telus I think we should consider moving to reports that are updated once per hour rather than pulled in real time. I think pulling real time data for thousands and thousands of goals is going to slow things way down. That was actually the initial intent of this ticket if I recall (just looking at the ticket description).

Are you able to do a test to compare response times if large goal data sets are accessed in real time vs accessed from a static hourly pull?

**Comment by jp-Telus** [comment]
@Travis-A-Clark 

I agree that the page timing is still not prefect and still need 5-7 secs especially on the Goal page.

Could you please create a new ticket for the pre-calculate the statistics figures for each reports ? I need to design a staging table for storing the pre-calulcated result for users per difference statistics), it will be a take a some time since each page has difference calulcation requirements. 

Thank you.

**Comment by Travis-A-Clark** [comment]
Pushing this to deployment and moving remaining work to #772.

**Comment by Travis-A-Clark** [comment]
@jp-Telus This is now in Production and is working as intended. It speeds up the load times, even for the Goal Summary page, significantly. However, it has introduced a new issue. If we assign HR Admin access to someone, they can go to the Statistics and Reporting area immediately, but they see all zero counts and no employees until the chron job runs at 1:30am the next morning.

Question: is there anyway to have trigger the command:BuildAdminOrgUsers when the HR Admin access is created rather than waiting until 1:30am?
