### ISSUE TITLE
As an HR Admin I want the ability to see more than one organization

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#732]
**Scenario**

I am an HR Admin who is responsible for three different organizations and I want to be able to see all three when I go to the My Organization, Shared Employees, Goal Bank, etc. under my HR Admin navigation. Currently I only see the first organization. The others are not visible in the drop down.

**Comment by telusdcinco** [comment]
I have been able to assign multiple Organizations to the same HR Admin.  Unfortunately, the increase in the employee list causes the longer load times on the pages like My Organization.  

The HR Admin can select from the organization list as granted to the user from Access and Permissions.

Further look required to see if the data retrieval can be improved to facilitate loading of longer employee lists.
