### ISSUE TITLE
Sharing an employee who reports to "blank" with a delegate supervisor causes all sorts of issues

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#734]
Currently there are ~3,000 employees that are shown as reporting to blank (see attached for list form July 27). If an HR or Sys Admin shares one of these 3,000 employees with a delegated supervisor, that delegated supervisor will receive an error when they attempt to view the employee's profile. It will also cause permissions issues and force the delegated supervisor to log out and re-authenticate to regain access.

We verified this with a number of cases. Sharing an employee that already has a value in the reports to column works well. Sharing an employee with no value (vacant, etc) causes all sorts of trouble.

[https://app.zenhub.com/files/329107952/8b4b59eb-9b34-4a51-8bc0-c154d19179d2/download](https://app.zenhub.com/files/329107952/8b4b59eb-9b34-4a51-8bc0-c154d19179d2/download)

**Comment by telusdcinco** [comment]
Code change deployed to Dev and Test.

**Comment by jchow11** [comment]
@Travis-A-Clark @jp-Telus  is this ready for Steffi to test? If so, could you provide steps to reproduce?

**Comment by Travis-A-Clark** [comment]
@jchow11 @jp-Telus I was just in the process of testing. Everything looks good so I am going to move it to Deploy to Prod.
