### ISSUE TITLE
My Team > Team Members: Add scroll bar to Share Employee modal

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#737]
The My Team > Team Members > Share Employee modal requires a vertical scroll bar. The info fits until an employee is actually shared, and that forces text off the bottom of the page with no way to scroll down to view.

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/ca1962c9-5ad0-4014-a7d7-c713b694f15b)

**Comment by Abuchana** [comment]
@jizhaogit, can you add an estimate to this ticket please? Thanks!
