### ISSUE TITLE
In TEST env: create new goal modal defaults to goal type "any"

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#739]
There should not be a goal type "any"; three options are work, learning, career development. Default should be "Work" as it is throughout the rest of the app.
<br>

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/a05bc9fa-6e39-4c3f-a58e-8a61ce044286)

**Comment by jizhaogit** [comment]
related with #500

**Comment by Abuchana** [comment]
@jizhaogit, can you add an estimate to this ticket please? Thanks!
