### ISSUE TITLE
Headings - Font Size and Non-Consecutive Use

### ISSUE THREAD

**Issue by jchow11** [bcgov/performance#740]
**Description**
Headings and subheads are used to form an outline of the page. This helps non-sighted users to understand how the page is structured, and it makes it easy for screen reader users to navigate. 

**User Story**
As a non-sighted user or a sighted user with limited mobility, I want the heading structure of each page in the app to be sequential and consecutive so that my screen reader understands how to logically navigate each page.

**Acceptance Criteria (this ticket is "done" if)**

- There is one h1 per page (no more, no fewer)
- Headings are used consecutively (h1 is main title, h2 is next level down, then h3, etc)
- Headings don't skip levels (ex. h1 is main, then h4 is the next subhead = bad)
- Headings follow the BC Gov standards outlined below
![Screen Shot 2022-08-11 at 12.07.50 PM.png](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/cf02cfc4-789d-4e41-bfd4-05f9345c10c9)

**Comment by Abuchana** [comment]
@jchow11, are you able to provide more details for this ticket too? Assignee, estimate, any labels that apply e.g., "bug"... Thank you!

**Comment by jchow11** [comment]
@Abuchana another Travis question :P

**Comment by steffipravasi** [comment]
Closing this ticket as I will be creating Accessibility tickets for individual page
