### ISSUE TITLE
As a supervisor, I want to be able to edit the mandatory/suggested status of goal I create for my team in the Goal Bank

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#744]
Currently, when a supervisor adds a goal to their team goal bank they choose whether the goal is mandatory or suggested. Once they have created the goal, however, the ability to edit this choice disappears. We need to add this field back into the edit screen.

Let's add the mandatory/suggested drop down at the bottom of the edit goal function in the goal bank for supervisors.

**Comment by Travis-A-Clark** [comment]
This looks good in Dev. Have not been able to verify in Test yet. Thanks!

**Comment by Travis-A-Clark** [comment]
@jizhaogit Still don't see this in Test. Can you work with Dennis to push all your changes into Test?

**Comment by steffipravasi** [comment]
@Travis-A-Clark are we expecting the employees to receive notification on home page when the goal is updated?
