### ISSUE TITLE
Log-In > employee sees error message that says they do not have an active PeopleSoft HCM account

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#746]
Employee: Sue Grewal
Organization: Social Development and Poverty Reduction

The employee does have access to other services such as Time and Leave. The error message they receive when trying to log in to PDP says they do not have an active PeopleSoft HCM account.

**Comment by telusdcinco** [comment]
I could not find an exact match for first/last name in employee_demo table.  I found an users entry for sue.grewal@gov.bc.ca from SDPR but the account is locked, due to an existing date value in the date_deleted column (meaning resigned or terminated).

**Comment by telusdcinco** [comment]
Created a script to reset the last ODS Data Pull.  Then ran the ODS Data Pull and Sync User Profile.  Sue Grewal's account in Test is now unlocked.

![image.png](https://images.zenhubusercontent.com/60e88ef619e4760c8b3ee8bb/955801d7-2a9a-4ac4-8892-da3df9708790)

**Comment by Travis-A-Clark** [comment]
@telusdcinco Can you confirm that the same fix has now taken effect in Prod and that Sue Grewal can access the PDP?

**Comment by telusdcinco** [comment]
Sue Grewal's PDP profile is now unlocked in Prod.
