### ISSUE TITLE
Add content to list of goal tags and make goal tags mandatory

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#748]
We are adding four new goal tags to the list:
- Business Acumen
- Change Management
- Digital Dexterity
- Leadership

The new tags and definitions are highlighted in yellow in [this document](https://app.zenhub.com/files/329107952/1fd8dae0-3822-4a2b-8455-9af1cf89fe2c/download).

Once these tags have been added, we will need to make the goal tag a mandatory element of goal creation when:
- Employee creates a new goal
- Employee edits an existing goal
- Supervisor adds a goal to the goal bank
- Supervisor edits a goal in the goal bank
- HR/Sys Admin adds a goal to the goal bank
- HR/Sys Admin edits a goal in the goal bank

There are a couple thousand goals already in the system that do not have goal tags. They can stay that way, but if someone edits them, the app should require that they add a goal tag as part of the editing process.

The final thing we need to do is create an option for users to email if they have a suggestion for a new goal tag. We can put this link in the info tooltip next to the goal tag heading (see image below). After the "View full list of tag descriptions" leave a line space and then add a line that says "Don't see the goal tag you are looking for? Suggest a new goal tag." where the "Suggest a new goal tag." is a link that launches a mailto modal.

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/0965ff6f-36b3-4f8d-99e6-1e33668b1dac)

Mailto modal details
- Send to address: performance.development@gov.bc.ca
- Subject: Suggestion for New Goal Tag

Let me know if we are able to add more details to the body of the email in the modal as well. For example, can we add headers or text into the email body so that the user doesn't have to create this themselves?

Would also be good to have an interface to update tag list in the background.

**Comment by jizhaogit** [comment]
Items done:
1. add new tags
2. make tags field mandatory in goal create/edit, hradmin goalbank item create/edit, and sysadmin goalbank item create/edit pages
3. insert email link for suggest tags

items pending:
tags management tool

**Comment by Travis-A-Clark** [comment]
@jizhaogit I have moved the tags management tool into its own ticket #807. This ticket can move ahead and be tested/deployed as is. Thanks!

**Comment by steffipravasi** [comment]
1) While creating a new goal, the mandatary tag field if left empty must say "". 
Right now, the message says ' The tag ids field is required.'
![Screen Shot 2022-09-28 at 11.48.21 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/8330d7ac-e6e2-4858-aeb6-e87ce20da516)

**Comment by jizhaogit** [comment]
1. the system is using element's id as the attribute name for the auto filling information.  
2. it is not possible to pre-set MIME body in the mailto link. REF: https://www.rfc-editor.org/rfc/rfc6068

**Comment by jizhaogit** [comment]
modified system validation content as "The tags field is required."

**Comment by steffipravasi** [comment]
The validation content has been changed to "The tags field is required." for all users - create new goal and edit goal.
![Screen Shot 2022-09-29 at 2.35.10 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/e39bf1c0-a61b-44b0-a53d-7c9a50ba9fff)
New goal suggestions can be mailed to performance.development@gov.bc.ca. Ji confirmed that pre-defined text cannot be added in the body of the email. 
Ticket ready for PO review.
