### ISSUE TITLE
As a Sys/HR Admin, I want to be able to choose the name that displays when I add goals to the goal bank (i.e. SDPR Admin)

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#749]
Currently goals are posted to employee goal banks using the individual name of the Administrator that created them. This can be confusing for employees who don't know who that person is. It would be useful to have the option to post those goals under an organizational title rather than individual name. Perhaps this becomes a new field in the goal creation process: Display Name.

**Comment by telusdcinco** [comment]
@Travis-A-Clark Please confirm location for new field on the Add New Goal page.  Currently, it is added after the start/end dates.
![image.png](https://images.zenhubusercontent.com/60e88ef619e4760c8b3ee8bb/08279e20-f433-4183-9519-dd7b860b56ff)

**Comment by telusdcinco** [comment]
The related changes is also part of #701.

**Comment by telusdcinco** [comment]
@jizhaogit  Please review the code changes.

**Comment by jizhaogit** [comment]
@telusdcinco good to me. please go ahead for the testing migrate. thanks!

**Comment by SSubashree26** [comment]
**Observation 1:**
- Created a goal as a HR admin (Crystal Fischer) (Goal name : Test goal 2- 22 Feb 2023)
- In the "Manage Goals in Goal Bank" section, the Created by field displays the correct name that I entered in the "Display Name' field, while creating the goal.
- However, if we login as the employee to whom the goal was assigned ( Greig Ruth), and validate the  details in the goal bank section, Created By field still displays the HR admin's name and not the data entered in the "Display Name" field

![Screenshot 2023-02-22 at 6.18.19 PM.png](https://images.zenhubusercontent.com/63892df90d58261296a2b5c0/1641f559-8c81-4c59-b0c2-55c63f159bb6)

![Screenshot 2023-02-22 at 6.19.43 PM.png](https://images.zenhubusercontent.com/63892df90d58261296a2b5c0/8f1289f1-f9fa-4e66-9666-31b4ee038858)


**Observation 2:**
When we create a goal in the goal bank with the "Display Name" left blank, the "Created by" field displays different values for a HR admin and Sysadmin

For a  HR admin, when the Display Name is left blank, the name of the HR Admin is displayed in the "Created By" field
For a Sysadmin (sysadmin 1), when the Display Name is left blank, the "Created By" field is left blank

https://bcgov.sharepoint.com/:v:/r/teams/02915/Shared%20Documents/Product%20Team/Testing/Testing%20screenshots/Performance%20%23749/Performance%20%23749.mov?csf=1&web=1&e=0vgG4i

**Comment by telusdcinco** [comment]
@SSubashree26 
I've fixed the issue in Observation 1 and is pending migration to Test.
For observation 2...  The account sysadmin1 does not have an employee attached to it, there is no name that can be picked up for it.  It goes the same for hradmin1, 2, 3...  or employee1, 2, 3.  Using a login profile that is attached to employees will display a the employee name in the Created By column.

**Comment by SSubashree26** [comment]
@telusdcinco Hi Denis, Thanks for letting me know.

Observation 1: Fixed

![Screenshot 2023-02-23 at 5.04.10 PM.png](https://images.zenhubusercontent.com/63892df90d58261296a2b5c0/a42d211d-cdc5-4937-aa29-ba961ac1b81d)

Completed validating this ticket in the testing environment and it is working fine. Moving this ticket to "PO Review"
