### ISSUE TITLE
My Team > Team Members: as a supervisor I want to see the goal bank tab when I click to view my employee's profile

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#750]
Currently when a supervisor clicks on an employee on the My Team page, they see a view of the employee profile that includes the employee's current goals and the employee's past goals (see below). Let's also add the ability to view the employee's goal bank. Heading would be _EMPLOYEE'S_ Goal Bank. View only access.
<br>

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/ad709154-2655-491b-8dc6-e08f209dc701)

**Comment by steffipravasi** [comment]
Test status: Fail
1) The EMPLOYEE'S Goal Bank tab must be highlighted when it is selected.
![Screen Shot 2022-09-09 at 2.46.14 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/eac9e3ee-ed57-439f-b567-fbb5299e8d13)

2) The supervisor is able to add goals to the profile for the employee. 
Expected: The supervisor has View only access to the employees goal bank and cannot add/edit anything on the page.![Screen Shot 2022-09-09 at 2.50.19 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/4e49d1fc-bc3d-4824-8189-8062895b2d5a)

**Comment by steffipravasi** [comment]
Test status: Pass
The supervisor can view the team members Goal bank, it is highlighted and supervisor cannot edit goals from the goal bank.
![Screen Shot 2022-09-12 at 9.08.54 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/a922671c-e430-49a8-ba3e-0a1d7db406a5)
