### ISSUE TITLE
In DEV: assigning Sys Admin access breaks HR Admin access permissions

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#754]
As discussed briefly on a call last week, assigning Sys Admin access to a user in the Dev environment that already has HR Admin access breaks that user's HR Admin permissions.

Test case: Assign Travis HR Admin access for Public Service Agency. He see the HR Admin area and all tabs are populated with the correct employees. Then, assign Travis Sys Admin access. He sees the Sys Admin area and all tabs are populated correctly, but when he clicks into the HR Admin area, no employee data is loaded for any of the tabs.

This is not the case currently in Production where Travis can have both Sys and HR Admin access without any issues. I don't want to push updates that will mess this up in Prod.

**Comment by telusdcinco** [comment]
Fixed the issue when assigning Sys Admin access to a user, the HR Admin organization assignments disappears.  
Now a user can be assigned both Sys and HR admin access without impact to each access.

**Comment by steffipravasi** [comment]
Testing is blocked because of ticket 673 as no employee list can be seen in the HR admin section for an employee.

**Comment by steffipravasi** [comment]
Test status: Pass
User can access the HR admin section when Sys Admin access is given.
User: Jacob Genert
Env: Test
Ticket ready for PO review.
