### ISSUE TITLE
Goal bank -> Edit Goals -> End date needs validation

### ISSUE THREAD

**Issue by steffipravasi** [bcgov/performance#761]
Test env: Test
As a supervisor, when the user edits the goal from the goal bank, the end date must be validated. User can enter end date which is previous to the start date.
Expected result: The end date must be the same or after the start date. End date cannot be without a start date. An error must be prompted to let user know about it. 
![Screen Shot 2022-08-25 at 11.25.30 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/cd945589-edce-4595-bc5f-e1d9eac7dc31)

Also, when the status of the goal from the goal bank is changed to Achieve/Not met/ Cancelled, the test site gives a 404 Not found error

Bug is an outcome of ticket [#744](https://app.zenhub.com/workspaces/performance-development-60020b0a13a09c0014af2469/issues/bcgov/performance/744)

**Comment by jizhaogit** [comment]
1. fixed date picker for target date error
2. fixed 404 error for status update

**Comment by jizhaogit** [comment]
The system currently does allow empty date entry in goal edit/copy.    #Travis can you please verify if we need a mandatory verification for start date/target date in goal edit/copy  features?  thanks!

**Comment by Travis-A-Clark** [comment]
I don't think we need mandatory verification for start date. The date range on the goals is pretty relaxed and is meant to be really flexible to allow for employees and supervisors to update things whenever they need to.

**Comment by jizhaogit** [comment]
so, should we leave the start date as it for now and close this ticket?

**Comment by Travis-A-Clark** [comment]
Yes, I think so. The only scenario I wanted to avoid was the one that Steffi originally raised where an end date could be earlier than a start date because that wasn't logical. Having blank dates doesn't concern me too much at the moment.

**Comment by steffipravasi** [comment]
Moving this ticket to testing back as we are not focusing on blank dates.
