### ISSUE TITLE
Employee -> Tags not displayed when a Goal is added from the Goal Bank

### ISSUE THREAD

**Issue by steffipravasi** [bcgov/performance#762]
Environment: Test
Employee: Kelly Whitford, Kelly.Whitford@gov.bc.ca, Id: 006357
Supervisor: Shannon Baskerville, Shannon.Baskerville@gov.bc.ca,ID: 043323

The tags are not displayed in the goal for an employee when the goal is added from the goal bank regardless of the goal being current or past. Due to this issue, search by tag function is not working. There are no results displayed when the tag is selected.

Steps to reproduce:
i) Login as supervisor(Shannon) -> Add a new goal to the goal bank and fill out all the details including multiple tags -> Assign it to the team
ii) Login as employee(Kelly) -> Navigate to the goal bank -> Add the goal
iii) Navigate to my current goals and open the goal
iv) All the details are displayed _except the tags_
v) Update the status of the goal to Achieved/Not met/ Cancelled -> Goal must move to the pas goals column
vi) Try searching the recently added goal by the tags 

Expected result: The tags must be displayed in the employee view. The search function must work when a tag is searched by.

In the screenshot below, the right is the supervisor view and left is employee view.
![Screen Shot 2022-08-25 at 1.37.14 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/ac816678-bdbe-44c7-9d1e-7f3248409eaa)
![Screen Shot 2022-08-25 at 2.54.01 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/7b76dda8-cede-4021-8f46-232bf8d0da63)
![Screen Shot 2022-08-25 at 2.54.42 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/f3a16582-b3c7-4e09-a76b-0a46abae2f9f)

Ticket is related to [#500](https://app.zenhub.com/workspaces/performance-development-60020b0a13a09c0014af2469/issues/bcgov/performance/500)

**Comment by jizhaogit** [comment]
issue addressed:  tags are lost when copy goal from goalbank to current goal.

**Comment by steffipravasi** [comment]
@jizhaogit 
Test status: Fail
Env: Test
Employee: Kelly Whitford, Kelly.Whitford@gov.bc.ca, Id: 006357
Supervisor: Shannon Baskerville, Shannon.Baskerville@gov.bc.ca,ID: 043323
Description: The tags are not copied when goal is added through the check box.

Steps to reproduce: 
i) Supervisor: Add a new goal to goal bank by adding multiple tags and details
ii) Employee: Go to My Goals -> Goal Bank
iii) Find the added goal
iv) Click on the checkbox on the left hand side
v) Click the "Add Selected Goals to your Profile(1)" button at the bottom of the list
vi) Open the added goal from My current goals and see the tags are missing
![Screen Shot 2022-08-29 at 3.15.02 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/a7fa2478-cbdf-4114-ba0b-4309d30a5426)

**Comment by jizhaogit** [comment]
the bulk goals copy feature is calling another different module that is not including tags copy.  a fix will apply tomorrow.  good catch!

**Comment by jizhaogit** [comment]
1, fixed bulk goals adding feature with tags bug
2, fixed the "add selected goals to your profile" button behavior with mult checkbox
