### ISSUE TITLE
Redesign of Homepage Notifications 

### ISSUE THREAD

**Issue by jchow11** [bcgov/performance#763]
**Description**
Currently notifications appear on the app homepage. A user is notified for various reasons– they have an upcoming conversation due, comments on their goals, conversations are signed off, etc. When a user reads a notification, the notification is moved to the bottom of the notification list. This is an unexpected/unconventional interaction. In applications such as gmail or outlook, new emails stay in the same spot on the list, but are marked as read. We want to change our interaction to match this interaction as it is more conventional.

**Acceptance Criteria**
- It is clear and obvious which notifications have been read and which have not (increase differentiation)
- Notifications are sorted with the most recent notification at the top of the list
- Notifications do not re-sort when clicked; they remain in the same place in the list until they are deleted by the user

**User Story**
As a PDP user, upon clicking a new notification I want it to visually appear as "read", but remain in the same position in my notifications list, so that I can easily keep track of my notifications in the same manner as I do in other apps I commonly interact with.

**Design**
![Notifications.jpg](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/e5df4f75-71bb-4502-b1d6-7e5947539b0d)

**Comment by jchow11** [comment]
@Travis-A-Clark Design ready for your review. Please add acceptance criteria as you see fit!

**Comment by jp-Telus** [comment]
@Travis-A-Clark 

Development completed and tested in the DEV region. Please kindly confirm the TST region. Thanks

**Comment by Travis-A-Clark** [comment]
@jp-Telus Works for me. I don't know if the contrast between the grey background and black text is enough or too much or just right. Let's push it to test and have Steffi review. Thanks!

**Comment by jp-Telus** [comment]
@Travis-A-Clark 
Thank you and have requested the TEST migration.

**Comment by steffipravasi** [comment]
Test status: Pass
Env: Test
User: Shannon.Baskerville@gov.bc.ca, Nicola.Lemmer@gov.bc.ca
The notification when read does not move to the bottom and is marked as read. 

Although @Travis-A-Clark I am not much convinced with having black font on grey background as it is also confusing. Would you suggest removing the grey background? @jchow11 Tagging you for any thoughts you may have.
 ![Screen Shot 2022-09-01 at 7.02.41 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/9be0a8c8-9dd4-4ea7-a952-8a9b51492efa)

**Comment by jchow11** [comment]
@steffipravasi as long as contrast passes, I think we should keep the grey. It adds a distinction between the read and unread messages similar to what other email platforms like Gmail use.

**Comment by Travis-A-Clark** [comment]
As per team discussion, let's go with "Unread" tags to help identify new messages.

**Comment by Travis-A-Clark** [comment]
@jchow11 At our review earlier today, the team felt that including an "Unread" tag would be helpful. I believe someone mentioned Yahoo mail does those. Are you able to mock up a quick example of where the unread tag would look best given all the other info on the subject line? Thanks!

**Comment by jchow11** [comment]
@Travis-A-Clark Sounds good, I can put together some mockups.

**Comment by jchow11** [comment]
@Travis-A-Clark to keep you in the loop–
@jp-Telus created a version using the bootstrap badge for the "new" tag and we discussed via email about moving forward with this! I've added the screenshot James provided below:
![Unknown.png](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/07d74f9a-ba74-4a13-bb6f-dc2cd02d3047)

**Comment by jp-Telus** [comment]
@Travis-A-Clark 

The new tag was added and verified in DEV region. WIll request TEST migration on Tuesday. bundle with other ticket 474, 712, and 636.

Thank you.

**Comment by jp-Telus** [comment]
Migrated to TEST region.

**Comment by steffipravasi** [comment]
Test status: PAss
Env: Test
The new notification have a "New" tag, which is removed when notification is read.
