### ISSUE TITLE
SEE TICKET 772 - As an employee, I want to be automatically excused from the PDP process when I am on leave

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#764]
### This ticket has been replaced by ticket 772

An employee has three statuses in PeopleSoft: active, leave, and stop pay. When an employee goes on to leave or stop pay status, they should automatically be excused from the PDP process until they return to active status. This means that their excused status is changed to "Yes", their Next Conversation Due date is paused, a message is displayed on their conversation page stating that they are currently excused, and they are removed from Statistics and Reporting for Goals and Conversations (HR/Sys Admin view). 

Supervisors and HR/Sys Admin should be able to see that the employee is excused and also the reason the employee is excused. The PeopleSoft data contains a column that lists the reason for leave (i.e. parental leave) or stop pay (i.e. long term disability) that can be imported.

When they return to active status, their excused status should changed to "No", their Next Conversation Due date starts counting down again, and they appear in the Statistics and Reporting for Goals and Conversations (HR/Sys Admin view).

**Comment by telusdcinco** [comment]
Modified the following sections when employee is not Active status:
- Employee Conversation to reflect message "Employee is excused" when the employee is not Active status.
- My Teams to reflect "Yes" on excused column and "Paused" for Next Conversation date, for both the My Employees and Shared Employees.
- HR/Sys Admin Manage Excused page to hide "Update" button for auto excused.
- HR/Sys Admin Manage Excused page to display Employee Status column, based on PS status (ALPS: Active, Laid Off, Leave with Pay, Leave of Absence)

**Comment by telusdcinco** [comment]
Pending fix for Employee List to display correct Yes/No for Active employees, based on current date inclusion in start/end excused dates.

**Comment by Travis-A-Clark** [comment]
Lots of good stuff here, Dennis! Thanks for this. These things are all functioning as intended:

- [x] Employee Conversation to reflect message "Employee is excused" when the employee is not Active status.
- [x] My Teams to reflect "Yes" on excused column and "Paused" for Next Conversation date, for both the My Employees and Shared Employees.
- [x] Sys Admin Employee List updated to reflect Excused/Paused.
- [x] HR/Sys Admin Manage Excused page to hide "Update" button for auto excused.
- [x] HR/Sys Admin Manage Excused page to display Employee Status column, based on PS status (ALPS: Active, Laid Off, Leave with Pay, Leave of Absence)

A few things that still need work:

- The Next Conversation Due date is now different on the supervisor's My Team page and the employee's My Conversation page. For example, Sharron Larusson shows a due date of Nov 9, 2022 on her My Conversations page and a due date of December 27, 2022 on her supervisor's My Teams page.

- In Sys Admin > Employees: the Next Conversation, Excused, Shared, and Direct Reports column sorts don't work

- In HR Admin > My Org: employee list does not reflect Excused/Paused

- Can we please update the message on the employee profile to say "Employee is currently excused and their conversation deadline is paused."

**Comment by telusdcinco** [comment]
@Travis-A-Clark  Laravel currently disabled sorting for added columns such as Next Conversation, Excused, Shared, and Direct Reports.  These columns are manually added to the returned SQL dataset.  Usually these are calculated or processed after the SQL data becomes available.

Direct Reports. Should I just remove the sort icon beside the headers?

**Comment by telusdcinco** [comment]
@Travis-A-Clark  I will revisit the Next Conversation Date for additional changes based on what will be completed in another ticket, which will create a scheduled process to predetermine/calculate the next conversation dates for the employees.

If possible to bundle all the excuse changes together including the new conversation date process, since the changes are in related objects.  This will probably save on testing time since I expect some requirements to fail due to impact by other tickets.
