### ISSUE TITLE
As a supervisor, I should not be able to change the status of goals that I have added to my team's goal bank

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#765]
Currently, after a supervisor adds a goal to their team's goal bank, they can click the goal card to view the goal and change the status from "active" to any of the others (achieved, not met, cancelled). This functionality is not required for goals in the goal bank. They are either available for the team, or deleted and not available.

When they click a goal in their Team Goal Bank, let's remove the "view" step and take the supervisor right to the goal edit screen. 

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/9ad67dba-ce54-4283-b689-65118a46f16b)

DO NOT take them here: https://performance-332842-test.apps.silver.devops.gov.bc.ca/goal/5

DO take them here instead: https://performance-332842-test.apps.silver.devops.gov.bc.ca/goal/5/edit

**Comment by steffipravasi** [comment]
Test status: Pass
The goal card in the Team Goal Bank when opened takes the supervisor to the edit goal page. Supervisor is not able to edit the status of the goal.![Screen Shot 2022-10-12 at 5.41.31 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/fc951dad-4239-4fce-8e4c-77a134894ae5)

**Comment by Travis-A-Clark** [comment]
PO approved

**Comment by Travis-A-Clark** [comment]
@jizhaogit Please review to see if we can find the code fix and redeploy. Thanks!

**Comment by jizhaogit** [comment]
features recalled back.  please test again. thanks!

**Comment by steffipravasi** [comment]
The goal card in the Team Goal Bank when opened takes the supervisor to the edit goal page. Supervisor is not able to edit the status of the goal except deleting it.
Env: Test
User: Travis, Nicola Lemmer
![Screen Shot 2022-11-02 at 11.02.01 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/6178b40e-fcf9-4f2f-b705-fb5337d953e0)![Screen Shot 2022-11-02 at 11.01.51 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/b570f76f-83a0-4f4b-b18f-b9ae6d60eff2)

**Comment by Travis-A-Clark** [comment]
@steffipravasi For some reason, I still see the old goal screen when clicking on a goal card in the Team Goal Bank area. It's not going directly to the edit screen, still to the screen that has the overview and the status update.

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/cd1f1e1e-d5de-4765-9839-780899c9e940)

**Comment by steffipravasi** [comment]
@jizhaogit If we click on the dates at the top of the card, it goes to the edit screen. If we click on the goal title in the middle of the card, it takes to the old screen.
![Screen Shot 2022-11-02 at 12.36.29 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/234253a4-22de-46e9-b3c1-bd4d1df84793)
![Screen Shot 2022-11-02 at 12.35.39 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/e9d60dda-342d-4fdb-8edb-7e15cb494a5a)

**Comment by steffipravasi** [comment]
Env: Test
User: Shannon, Travis
Browser: Chrome, Edge
Edit page issue resolved. User navigated to the https://performance-332842-test.apps.silver.devops.gov.bc.ca/goal/#/edit on clicking the goal card or the title of the goal. 
![Screen Shot 2022-11-03 at 3.06.14 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/9dff7ebf-95be-40e5-a2d9-3130f8b883b6)
