### ISSUE TITLE
My Goals > Past Goals: Remove "Inactive" from status drop down filter

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#766]
There is no "inactive" goal status so it should be removed from the drop down options when sorting past goals. Thanks!

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/da3a5243-a373-478d-9329-b7afbe08bbcb)

**Comment by steffipravasi** [comment]
Test status: Pass
The 'Inactive' option in the drop down status has been removed from the past goal Status field. The options available now are Achieved, Not Met, Cancelled or Deferred and Any as the default option.
![Screen Shot 2022-10-19 at 4.55.13 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/98ecccd2-5a73-4097-963c-0db1cfec11c5) 
Ticket ready for PO review.

**Comment by Travis-A-Clark** [comment]
PO approved
