### ISSUE TITLE
My Conversations > Open Conversations: checking "disagree" should save progress in template

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#767]
Currently, an employee can check "disagree" in a conversation template. When they go to close the template it warns that any unsaved progress will be lost. There is no way to save the "disagree" selection without also signing off with the employee ID. Checking the "disagree" option should save that choice to the template without having to take an additional step.

**Comment by steffipravasi** [comment]
The disagree selection option is not stored when selected. Ji working on the fix.

**Comment by jizhaogit** [comment]
issue is addressed.  can you @steffipravasi please try again? thank!

**Comment by steffipravasi** [comment]
@jizhaogit I have discussed with Travis and we actually don't need either of those messages displayed at the bottom of the disagree checkbox. The pop-up modal warns that continuing will send a notification and the check box remains checked so there is a visual indicator already.

So, would it be okay to remove both the messages saying - You agreed with this performance review / Your disagree notification has been sent.

**Comment by jizhaogit** [comment]
a question for "change mind to AGREE" (which is UNCHECK the checkbox).  if it will cause any concern when a user UNCHECK the disagree checkbox?

**Comment by Travis-A-Clark** [comment]
@jizhaogit No, it should be okay without the message. Unchecking the box is not a concern since it doesn't generate any notifications or anything. Thanks for asking!

**Comment by jizhaogit** [comment]
message removed

**Comment by steffipravasi** [comment]
The messages has been removed. The disagree option is stored when conversation is closed. Supervisor receives notification when disagree option selected. User can agree to the disagreed option. 
Ticket ready for PO review.
