### ISSUE TITLE
Quick fixes from Ji - conversation template error

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#769]
Conversation templates error

**Comment by jizhaogit** [comment]
error description:  log in as sysadmin1@example.com.   then goto page https://performance-332842-test.apps.silver.devops.gov.bc.ca/conversation/templates. Got 500 error. 

Current status: change applied and bug fixed

**Comment by steffipravasi** [comment]
Test status: Pass
sysadmin1@example.com can now view the conversation templates.
