### ISSUE TITLE
As a System Admin I want to be able to send notifications and to-do items to any BCPS employee

### ISSUE THREAD

**Issue by Abuchana** [bcgov/performance#77]
- Similar to HR Admin notification option but expanded to include all of BCPS
- Fields: Notification or Action Item (select one or other); Email or Home Page Alert (select one or both); Send to (list of participants grouped by organizational units; Message (text box)

**Comment by phoebesolomon** [comment]
![HR Functions - Notify Employees Function Page 1.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/67e2592c-eb48-42eb-bf0a-8cb855618569) ![HR Functions - Notify Employees Function Page 2.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/837cc28d-5aea-487f-89c3-d0b9c1c7cba4) ![HR Functions - Notify Employees Function Page 3.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/c574a5e2-3c87-41b2-bf5a-38992d7065a0) ![HR Functions - Notify Employees Function Page 4.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/d9b25c7e-5d21-4e15-807b-89756db8fba5) ![HR Functions - Notify Employees Function Page 5.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/c0fb0584-48f2-45b6-be22-5e21b7e662ff) ![HR Functions - Notify Employees Function Page 6.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/ea66992c-b9fe-4090-95bf-efe74d9b08a9) ![HR Functions - Notify Employees Function Page 7.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/1d58fb96-a16e-4f87-8363-4239995b753b)

**Comment by phoebesolomon** [comment]
![HR Functions - Notify Employees Function Page 1.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/8418413c-d078-4e1e-89e7-b9d1ec8cae14) ![HR Functions - Notify Employees Function Page 2.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/57513950-2927-4586-a3f3-576b9b218eb6) ![HR Functions - Notify Employees Function Page 3.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/cb1775e1-cf35-44cc-b0bf-5901ab3aee8d) ![HR Functions - Notify Employees Function Page 4.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/6b2e8306-ef52-4e6a-a2d7-9b34695f5bd2) ![HR Functions - Notify Employees Function Page 5.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/4a3a5b76-9043-4e32-a5c0-b09b164f48ce) ![HR Functions - Notify Employees Function Page 6.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/9d2dc230-404d-4a7e-9208-6d36d260fa68) ![HR Functions - Notify Employees Function Page 7.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/c1836d49-72e3-484e-926d-171596e13ce3)

**Comment by phoebesolomon** [comment]
![HR Functions - Notify Employees Function Page 1.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/b31dadcc-7154-4156-b102-b318f4d3680c) ![HR Functions - Notify Employees Function Page 2.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/06651e94-9d84-471c-a857-fcae74a95de2) ![HR Functions - Notify Employees Function Page 3.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/7b27a9cd-34f3-4f5e-83df-260f709c494a) ![HR Functions - Notify Employees Function Page 4.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/251f25b3-827e-4b74-b344-3a013ea51243) ![HR Functions - Notify Employees Function Page 5.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/745a4e86-a912-42ca-ad31-86a6234a3543) ![HR Functions - Notify Employees Function Page 6.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/e2ecf001-7d8c-4ac7-97b9-32929d51b56f) ![HR Functions - Notify Employees Function Page 7.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/f2dc7adb-9484-497f-8e1a-3330bfe5eabf) ![HR Functions - Notify Employees Function Page 8.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/398ea5bf-2dc5-4d89-9b1d-6cd9a7944871) ![HR Functions - Notify Employees Function Page 9.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/ca61cb9b-b24f-4544-8271-35f12e07b95b)![HR Functions - Notify Employees Function Page 10.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/4b291721-0b7c-4120-a1c2-f4c480892d8b)
