### ISSUE TITLE
CSS/SCSS pushing Fix

### ISSUE THREAD

**Issue by telusdcinco** [bcgov/performance#770]
CSS/SCSS pushing Fix

**Comment by Travis-A-Clark** [comment]
@telusdcinco @jizhaogit Is there anything I can or should do to test this in the Test environment? Or can we push to Prod on Friday?

**Comment by jizhaogit** [comment]
@Travis-A-Clark this fix is for updating css/scss after James pushed his changes. the purpose is to make the navigation bar's behaviors as same as product.
