### ISSUE TITLE
PDP past employees list is inaccurate

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#775]
### Update: Jan 10, 2023

- Update Production ODS so that date_updated matches date_deleted in our data set. Already deployed successfully in DEV.

- Run a one time refresh of data in the PDP to search for past terminated / resigned employees that were not properly captured by the app since its launch.

### Original ticket

We have an area in the PDP called “Past Employees” that we need in order to be responsive to records management and freedom of information requirements. That list is populated based on the “date deleted” status provided by the ODS. When the PDP sees that “date deleted” has anything other than a null value, it moves the employee record from our current employees to our past employees list. We are seeing two main issues:

1) Names drop off of the past employees list. We checked multiple employee IDs that showed up and then disappeared from our past employee list (IDs 004342, 008723) between July and November. In PeopleSoft, it accurately shows them as retired, but in the PDP they are simply gone. What happens to these records in ODS / PDP and how can the app best track this going forward?
<br>

2) Employees are not being moved to past employees list at all and are remaining active and visible in the app even significantly after they have left the public service. Is this information not being captured in ODS or is the PDP failing to capture it? 

Examples include: 
Taylor Kallstrom (185431) - terminated Oct 7
Olivia Saunders (181499) - terminated Sept 10
Brenda Carr (158354) - terminated Oct 1
Laura Monner (125514) - left in August
Michelle Wilson (185160) - last day August 19

<br>
My understanding is that records stay in the ODS for a total of 7 days before being deleted. The PDP is supposed to import any deltas from the data in ODS every day, so 7 days should be plenty for the PDP to get what it needs.

**Comment by telusdcinco** [comment]
Exported Past Employees list as of 2022-09-08.

**Comment by telusdcinco** [comment]
Latest export from dev.
[https://app.zenhub.com/files/329107952/71dc9c14-089c-49b9-9045-fc40359fe732/download](https://app.zenhub.com/files/329107952/71dc9c14-089c-49b9-9045-fc40359fe732/download)

**Comment by Travis-A-Clark** [comment]
As discussed with Jon and Dennis earlier today:

- We are going to ask Justin to update the ODS so that date_updated matches date_deleted in our data set. This should allow the PDP to properly capture and move terminated / resigned employees to the Past Employees list and remove them from the active app view.

- We will need to run a one time refresh of data in the PDP to search for passed terminated / resigned employees that were not properly captured by the app since its launch.

As of Dec 2, Justin has made the change to match date_updated with date_deleted in the DEV environment.

**Comment by Travis-A-Clark** [comment]
In DEV environment right now, our Past Employees page only has 32 entries. I have exported the list and saved on my local. If the the update in date_update field from ODS behaves as expected, we should see this list grow in the PDP and can compare to source data.

**Comment by JonTelus** [comment]
@Travis-A-Clark I found that the two EEs listed in point #1 are now present in the Past Employees list in DEV.  It appears that the DEV ODS feed now contains all past terminations, as the EEs listed in point #2 are also showing as terminated, despite the dates of their terminations being older than 7 days.  

This lines up with the approximate growth of the Past Employee list by ~1000.  Spot checking the list looks correct.

I did see that the Past Employee list is created based on a view, which is two tables joined with guid.  I don't want to say that the unreliability of guid could be causing issues, but I don't NOT want to say it either.  We could try modifying the view to join on employee_id and see if the fluctuations disappear.

**Comment by Travis-A-Clark** [comment]
@JonTelus Thanks for this. Very helpful!

Does the fact that those old employees from point 1 are now captured in the PDP indicate that the changes made by Justin will actually retroactively capture all the necessary changes to our entire employee list? We had assumed that we would need to run a one time refresh to capture historical departures, but those employees left many months ago and were captured by the shift in ODS date_deleted methodology. Maybe it all gets sorted once Justin pushes to Prod?

I'm going to do a few other checks on the DEV data and how it's showing up in various places in the PDP. Looks promising though!

**Comment by Travis-A-Clark** [comment]
@JonTelus Can you please check the status for Laura Monner (125514). She is the only one of the examples in point 2 of this ticket that still shows as a current employee even though she left in August. Just wondering what might be different about her situation and how it is being represented in PeopleSoft / ODS. Thanks!

**Comment by Travis-A-Clark** [comment]
@telusdcinco The employees showing up on the Past Employees list are still being displayed on the My Team page for their supervisors. An employee in Past Employees should be removed from all reporting relationships and statistics/reporting in the app.

**Comment by JonTelus** [comment]
@Travis-A-Clark Justin says the 7 day retention isn't activated in DEV.  In order to sync up older records in PROD we'll have to coordinate something with him.

For that one record, it has been deleted from DEV as they had to rebuild it at one point, losing older terminations.  So the list of past employees we see in DEV isn't complete.
