### ISSUE TITLE
Deletion from HR/Sys Admin Goal Bank Leaves Orphaned Dashboard Notification Entries

### ISSUE THREAD

**Issue by telusdcinco** [bcgov/performance#776]
With the introduction of the Dashboard Notification for HR/Sys Admin created Goal Bank, it is necessary to perform cleanup on the Dashboard Notifications generated.

This change should also apply for situations wherein the Goal Bank is deleted or no longer shared with the user.

If possible to explore make use of soft deletion to track users which already received the notification, so that the user do not need to get new notification in cases where the user have deleted the notification entry.

**Comment by telusdcinco** [comment]
@jp-Telus #776 looks good.  Please proceed to migrate to Test.

**Comment by jp-Telus** [comment]
@steffipravasi, migrated to Test region and ready for test.

**Comment by steffipravasi** [comment]
As the notifications are not received for any new goal is added or goal updated, blocking the testing till ticket #700 is fixed.

**Comment by steffipravasi** [comment]
Test validated. 
Notifications are deleted from the Dashboard once page is refreshed, or if the notification is read.
No additional notification received after the notification is deleted.
Ticket ready for PO review.
