### ISSUE TITLE
As an HR/Sys Admin or supervisor, I want to see the total number of reports (direct and shared) displayed on the employee tables

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#779]
Currently, all tables (Supervisor > My Team, HR Admin > My Org, Sys Admin > Employees) display the number of direct reports for each employee. However, some supervisors don't have any direct reports but have many delegated (shared) reports or have some combination of both direct and shared. Is it possible to have this heading change to "Reports" and display both direct and delegated?

I would also want this to carry through so that if the number was clicked on, the data displayed on the following page showed both direct and delegated employee rows.

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/4f13cc9a-b224-41fe-a7de-0f0ee3ea9567)

**Comment by Travis-A-Clark** [comment]
@telusdcinco As discussed in our meeting earlier today, let's change the column heading to "Direct / Shared Reports". Let's also add an info toggle tip with the following text:

Direct Reports are employees that report directly to you in PeopleSoft.

Delegated Reports are employees that report to a vacant position in the org chart and have therefore been delegated to you as the next supervisor in the org hierarchy.

Shared Reports are employees that have been shared with you by another supervisor or administrator in the PDP. This is separate from any PeopleSoft data.

**Comment by steffipravasi** [comment]
@telusdcinco I noticed a couple of issues 
1) Employee Hung-Yu Tseng missing from supervisor Baskerville,Shannon Direct/Shared Report count. 
Shannon is supposed to have total 19 reportees. 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdDRMIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--f5a000abf051958bed3ed087d0aeda303105b888/Screenshot%202023-08-16%20at%209.53.20%20AM.png)
2) Supervisor: Travis Clark has total 13 direct/shared reporters and can see 13 in the column, but when the report /modal is opened, there are only 12 employees in total. Milum,Paula is missing
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBak1NIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--58379616d9d5bc70e1c1fe24ceae3dabbdb607f5/Screenshot%202023-08-16%20at%2010.34.10%20AM.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBalFNIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--bd6c3342868c3df89986b07ef46f462f6a33a53c/Screenshot%202023-08-16%20at%2010.34.03%20AM.png)
3) Supervisor: Miller,Jeffrey J can see a total of 8 members in the team on the Team members page, but in the Direct/Shared report column the number is 9. There is one employee displayed extra 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbEFNIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--8753e2af68b242bc69e0ec4d21adcbf261757151/Screenshot%202023-08-16%20at%2010.44.58%20AM.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbE1NIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--eac747d06b52951d3dc5740b649f945af6869102/Screenshot%202023-08-16%20at%2010.48.37%20AM.png)

**Comment by telusdcinco** [comment]
For issue #2, Paula Milum is a past employee, but is currently part of count.  Have fixed the count to remove shared employees who are past employees.

**Comment by telusdcinco** [comment]
For item #3, Thor is not a valid PDP user.  Does not have GUID and is not yet validated in PS.  Will exclude from list.

**Comment by telusdcinco** [comment]
For Item #1, is showing different supervisors from ODS and Position data...  ODS shows Shannon as direct manager, but positions shows that Shannon is 2 levels up in position, and there 2 levels of active managers in between.

**Comment by Travis-A-Clark** [comment]
I don't think it's worth the additional time at this point to solve item 1 in the list. It's a case of very messy PeopleSoft data with a reporting structure that includes double and triple bunked positions.

@steffipravasi please create a new ticket with the specifics for item 1 and put it in the icebox column for future reference in case we find similar cases in the future.

@telusdcinco i think it would be helpful to add that backend reporting structure query you sent me on Teams to the new ticket as well.

Thanks!

**Comment by steffipravasi** [comment]
@telusdcinco Unfortunately, I was still able to find a couple of instances in the variations of numbers from the Team members page and Direct/Shared Reports count column.
1) User: 009065	Leong,Richard L H	Rick.Leong@gov.bc.ca
Count in Employee list is 8/2
Count in Team members page is **10/3**
Difference employees: 
150340	Shaw,Carly A
027432	Cheveldeaw,Arlene D
_Bobbi Sadler (past employee) Ticket: #1088_
2) 000164	Richmond,Dave
Count in Employee list is 6/2
Count in Team members page is **7/2**
Difference employees: 
125380	Welstead,Kym
3) 000404	Redl,Kemp
Count in Employee list is 11/2
Count in Team members page is **0/2**
4) 000588	Sundhu,Sandra R.
Count in Employee list is 13/1
Count in Team members page is **9/1**
Difference employees: 
142447	Massey,Clinice
149304	Cardwell,James
137372	Blakely,Thea Marie
144842	Reid,Michael
5) 000639	Williams,Stephen T
Count in Employee list is 3/1
Count in Team members page is **0/1**

**Comment by Travis-A-Clark** [comment]
I will check in with the PeopleSoft and ODS teams to understand what manual overrides might exist in place of position hierarchy data.

**Comment by Travis-A-Clark** [comment]
Deploying this ticket as it is related to other changes being pushed. The current direct report count is incorrect in PROD, this ticket is a step forward even if not yet perfect. We can continue to spot check and troubleshoot.

**Comment by Travis-A-Clark** [comment]
@steffipravasi  I checked all the edge cases you identified in the comment from August and all look consistent and correct now. Will need to do another round of checks to see if issues still exist, but am comfortable moving this along for now since it is relatively minor and non-destructive.
