### ISSUE TITLE
BUG:  Error 500 When Updating Goal Bank Individual Audience List for HR Admin Access

### ISSUE THREAD

**Issue by telusdcinco** [bcgov/performance#782]
Error 500 shows when adding new employees to the Goal Bank's Individual Audience when using HR Admin access.

Test laravel.log entry:
 ![image.png](https://images.zenhubusercontent.com/60e88ef619e4760c8b3ee8bb/eb52b625-d7e0-4882-99f2-d4a0b93c9b26)

My Local error message:
 ![image.png](https://images.zenhubusercontent.com/60e88ef619e4768b3ee8bb/8d166dcb-3e5e-48bf-9678-39b4dbe1c325)

**Comment by telusdcinco** [comment]
Issue due to route file parameter mismatch.   Issue resolved in my local by adding the missing parameter in the route file entry as shown below.

Before change in hramin.php:
![image.png](https://images.zenhubusercontent.com/60e88ef619e4760c8b3ee8bb/66ebc9f7-c131-47ac-aea3-73e7c0e239a5)

After change in hradmin.php:
![image.png](https://images.zenhubusercontent.com/60e88ef619e4760c8b3ee8bb/c420c839-97ab-4b94-ada2-51804dbd2f61)

**Comment by telusdcinco** [comment]
@Travis-A-Clark  Fix deployed to Dev.

**Comment by Travis-A-Clark** [comment]
@telusdcinco  The fix seems to work for me in Dev. Please push it forward to Test. Are we able to Deploy to production as a one off or are there dependencies / conflicts with other work going on in Test that we should wait for before pushing things together?

**Comment by telusdcinco** [comment]
@Travis-A-Clark   Last change in the file was for #690 which was migrated to prod July 27, 2022.  It should be fine to move to prod by itself.

**Comment by Travis-A-Clark** [comment]
Seems to be good in Test as well. Please deploy to Prod after hours as discussed. Thanks!

**Comment by telusdcinco** [comment]
@Travis-A-Clark   Change deployed to Prod.
