### ISSUE TITLE
HR/Sys Admin loses content when creating or editing goals in the Goal Bank due to window resize / refresh

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#784]
Scenario:

HR/Sys Admin enters information in the Add New Goal to Goal Bank area; fills out one or more input fields, then resizes or minimizes their browser window. The window refreshes and all of the content is erased. This is true whether creating a new goal or editing an existing goal.

This does not appear to be an issue for employees when they create a goal in the new goal modal or edit an existing goal on the edit page.

**Comment by telusdcinco** [comment]
Pushed fix to Dev

**Comment by Travis-A-Clark** [comment]
@telusdcinco I am still losing content every time I minimize or resize the window in Dev environment. Will share screen at team review this morning.

**Comment by telusdcinco** [comment]
@Travis-A-Clark  Re-tested in local and Dev.

**Comment by steffipravasi** [comment]
Test status: Fail
Env: Test
User: SysAdmin
Browser: Chrome
When trying to add a new goal, the page keeps on loading when screen is minimized and then a 504 error is displayed after some time
![Screen Shot 2022-10-05 at 2.58.29 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/650838a7-93db-4f5f-92fe-98ebcaa21a31)
![Screen Shot 2022-10-05 at 2.59.34 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/eaf8a694-f3b9-4843-8a4b-7abaa40d2d62)

**Comment by steffipravasi** [comment]
Changes are not reflected on test environment yet.

**Comment by Travis-A-Clark** [comment]
PO approved
