### ISSUE TITLE
Goal added multiple times in the Goal Bank by SysAdmin/HRAdmin

### ISSUE THREAD

**Issue by steffipravasi** [bcgov/performance#787]
Login as SysAdmin
Go to System Administration -> Goal Bank -> Add a new Goal to the Goal Bank -> Enter the goal details -> Hit the Add Goal button -> Hit Add New Goal

The site takes some time to process that and the button Hit Add New Goal can be clicked multiple times which adds the same goal many times in the Goal history.

Solution: We can show the Add New Goal button processing once the button is clicked so that it won't be clicked again.
![Screen Shot 2022-09-21 at 2.29.52 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/4bb436af-22d6-49ca-bfb7-be6647bc2ddb)

![Screen Shot 2022-09-21 at 2.31.41 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/f7094025-0936-4df6-be33-f8019c8f7067)

**Comment by steffipravasi** [comment]
Test status: Fail
Env: Test
User: Sys Admin
@jizhaogit The 'Hit New Goal' button can be still be clicked multiple times and multiple goals are added in the list 
![Screen Shot 2022-10-25 at 1.15.25 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/75155ea1-42d1-4fbb-82f2-7c990c3a6538)

**Comment by jizhaogit** [comment]
chatted with Steffi @steffipravasi that i modified the submit limitation function for supervisor. But not for the HRadmin/Sysadmin.   Will keep the supervisor's fixing and include the HR/Sys admin fix as well.

**Comment by steffipravasi** [comment]
Test status: Pass
Env: Test
USer: Shannon, Sys Admin
Administration -> Goal Bank -> Add new goal HR Admin/SysAdmin not able to click on the Add New Goal button multiple times, hence only one goal is added. 
Ticket ready for PO review.
