### ISSUE TITLE
HR Admin > Goal Bank: HR Admins cannot see goal bank goals created by other HR Admins

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#791]
**Scenario 1**

Evelyn Carty was added as the HR Admin for the Service Delivery Division at Social Development and Poverty Reduction (SDPR) when we launched in July. SDPR just asked that Leah Good also be added as an HR Admin for the Services Delivery Division to act as a backup to Evelyn Carty.

Evelyn created a number of goals in the Goal Bank and assigned them to the business unit before Leah was given HR Admin access. Now, Leah has HR Admin access but cannot see or edit the goals that Evelyn created. When Leah looks in the Goal Bank as an HR Admin it is empty.

HR Admins should have equal access to current and historical info for the business units they are assigned to.

**Scenario 2**

Carolyn Babakaiff is HR Admin for all of SDPR. There are also HR Admins for each Division of SDPR. These other HR Admins report to Carolyn. When Carolyn views HR Admin > Goal Bank, she doesn't see any of the goals created by the other HR Admins.

**Desired Solution**

All HR Admins tagged to a business unit should have the ability to see and edit all goal bank goals created for that business unit.

**Comment by telusdcinco** [comment]
Changes ready for Test validation.

**Comment by steffipravasi** [comment]
1) Goal added to Individual Audience is not displayed to other HR
Travis added the following goal, but cannot be viewed by Shawna. Both have access to BC PSA
![Screenshot 2023-06-06 at 9.24.38 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/c628b24f-0656-4530-ba5f-0b55ed2c6d34)

**Comment by telusdcinco** [comment]
The goal bank sharing between HR admins have been fixed.  The sharing will occur when both HR admin share at least one org in Access & Permissions.

**Comment by telusdcinco** [comment]
Travis shares common orgs (BC PSA) with Jessica and Shawna.  This considers the 3 as co-HR admins for the orgs and will be responsible for goal bank created by each one.  Since HR goal bank was created by Travis (regardless of which org the goal bank was shared to), Jessica and Shawna will have access to the goal bank.

@Travis-A-Clark Is this what was expected?

**Comment by Travis-A-Clark** [comment]
@telusdcinco The intent was that the HR Admins would only see goals assigned to the business units they have access to. It should be a check to see what business unit a goal is assigned to cross referenced against what business unit an HR Admin has access to. In the scenario you mentioned, Jessica and Shawna should only see goals created for the BC PSA since that's the only org they have access to. If the goal is not assigned to their business unit, the shouldn't see it. The fact that they share some access attributes with Travis is not the determining factor.

Happy to chat further as needed.

**Comment by telusdcinco** [comment]
@Travis-A-Clark Funny thing is that's what the filter was before I recently changed it.  I'm reverting the last fix to restore the original filter.

The previous scenario stated above should have been fine, since the goal bank was not assigned to any org as shown below.

![Screenshot 2023-06-06 at 9.24.38 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/c628b24f-0656-4530-ba5f-0b55ed2c6d34)

**Comment by steffipravasi** [comment]
User 1: Trystan Jones 
Org: Health, Municipal Affairs, Jobs Economic Development & innovation
User 2: Sushant Soman
Org: BC PSA, Municipal Affair
1)  Trystan added a goal 'Annual Data Protection' to the Health org
Sushant cannot see the goal (As expected) ,
Trystan updated the goal by adding 100 individual audience from the 'Municipal Affairs' org
Sushant has access to Municipal Affairs but cannot see the goal in his list
2) Same issue as above also persists when a goal is created for individual audience.
Sushant added a goal 'Business Presentations' with 100 employees from Municipal Affairs
Trystan cannot see the goal

**Comment by steffipravasi** [comment]
@Travis-A-Clark Sorry if this got repetitive but can I confirm if the goal must not be displayed if assigned to individual audience? Eg: Travis added a goal for 10 individuals in BC PSA, should that goal be displayed to other co-HR having access to BC PSA?

**Comment by steffipravasi** [comment]
@telusdcinco 
Assigning ticket back to you
User 1: Trystan Jones 
Org: Health, Municipal Affairs, Jobs Economic Development & innovation
User 2: Sushant Soman
Org: BC PSA, Municipal Affair
1)  Trystan added a goal 'Annual Data Protection' to the Health org
Sushant cannot see the goal (As expected) ,
Trystan updated the goal by adding 100 individual audience from the 'Municipal Affairs' org
Sushant has access to Municipal Affairs but cannot see the goal in his list
2) Same issue as above also persists when a goal is created for individual audience.
Sushant added a goal 'Business Presentations' with 100 employees from Municipal Affairs
Trystan cannot see the goal

**Comment by telusdcinco** [comment]
Added HR Admin access to individually assigned goals.

**Comment by steffipravasi** [comment]
Test validated for Individual Audience and Business Unit for HR admin.
The tree version is still having some issues of sub-branches selection but we'll address that issue in a separate ticket as it is Medium Priority and Medium Severity.
Moving the ticket for PO review.
