### ISSUE TITLE
When I add a goal to my team's goal bank, I want my own name to appear in the audience drop down

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#792]
Scenario

I am a supervisor and I go to My Goals > Goal Bank > Add Goal to Bank. I create a goal. In the audience drop down list, I see all of my direct reports and shared / delegated employees. This all functions correctly. However, I'd also like my own name to appear in the audience drop down list so that I can assign the goal to myself. This saves me from having to recreate it if I want to use it as well.

**Comment by steffipravasi** [comment]
Test status: Pass
The supervisor can see their name in the Audience list when adding a goal to the goal bank![Screen Shot 2022-10-12 at 4.55.50 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/492e3b1b-b4c1-4e7f-8088-c9aabd3bdf30)

**Comment by Travis-A-Clark** [comment]
@jizhaogit One small change: please change the default selection to say "All" instead of "All Direct Reports". Everything else looks good and works well. Thanks!

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/380338e5-1864-4582-9dba-4c96f5ca5df7)

**Comment by Travis-A-Clark** [comment]
@jizhaogit I am still seeing the term "All Direct Reports" on the My Goals > Goal Bank > Team Goal Bank display. The cards and drop down menus (as show below). Please change to "All".

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/c9a17dba-604c-418e-8b8e-61485a49e740)

**Comment by steffipravasi** [comment]
The 'All Direct Report' term is changed to 'All' in My Goals -> Goal Bank -> Team Goal Bank.
![Screen Shot 2022-10-27 at 3.23.24 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/ff4788cb-31ba-40c2-8641-0871858f2655)

**Comment by Travis-A-Clark** [comment]
@jizhaogit It looks like the recent updates in TEST have removed this function. Still works well in PROD. Can you take a look and make sure this function is not deleted? Thanks.

**Comment by SSubashree26** [comment]
Validated this ticket in the testing environment and it is working fine. Moving this story to "PO Review"

![Screenshot 2023-02-15 at 3.18.41 PM.png](https://images.zenhubusercontent.com/63892df90d58261296a2b5c0/eb4e6571-870e-4189-a69d-7020c27faf1e)
