### ISSUE TITLE
Bug: Clicking Access & Permissions Remove Access Button, removes both HR/Sys admin access for the user

### ISSUE THREAD

**Issue by telusdcinco** [bcgov/performance#793]
When clicking on the Remove Access button on the Edit Employee Access modal page, removes both access for HR and Sys admin, if user has both.

![image.png](https://images.zenhubusercontent.com/60e88ef619e4760c8b3ee8bb/42e352c9-555f-4249-b681-b619d955bc7c)

![image.png](https://images.zenhubusercontent.com/60e88ef619e4760c8b3ee8bb/f09c1b43-64c5-4c41-a2b7-dd9d36ab9db0)

![image.png](https://ima![image.png](https://images.zenhubusercontent.com/60e88ef619e4760c8b3ee8bb/2cc0f6e6-311b-4ec5-b200-a1e4eab4bf5c)ges.zenhubusercontent.com/60e88ef619e4760c8b3ee8bb/fee2f368-c520-4d09-ae60-0cee184fd41d)

![image.png](https://images.zenhubusercontent.com/60e88ef619e4760c8b3ee8bb/c040a5ed-aa6d-4331-8ed8-01045824dbc8)

**Comment by steffipravasi** [comment]
Test status: PAss
Env: Test
User: Lauren Stocks,
