### ISSUE TITLE
Revise manual "Excuse" modal for supervisors

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#794]
My Team > Team Members > Excused

**Updates to the modal**

- [x] Update modal text: Excusing an employee will remove them from any reporting and will pause the employee’s conversation deadlines. Employees will automatically be excused if 1) they are on leave or inactive status in PeopleSoft; or 2) if they are a DM, ADM, or Executive Lead covered by a different performance review process. You should only use this form to manually excuse an employee if they fit into one of the categories listed in the dropdown box below. 
<br>
- [x] Remove "during the date range selected" in the declaration statement
<br>
- [x] Remove date range drop downs
<br>
- [x] Introduce dropdown to excuse employee; this is just binary Yes/No that defaults to No.
<br>
- [x] Change header "Reasons" to "Reason" and change the options to Casual Employee, Leave Not Captured in PeopleSoft, Student
<br>
- [x] If the employee has already been excused through PeopleSoft status or classification check, change excuse employee dropdown to Yes, grey out the Yes / No dropdown, Reason dropdown, and the Update button.

**Comment by steffipravasi** [comment]
@telusdcinco 
Test status: Fail
Remove "during the date range selected" in the declaration statement - is not removed 
![Screen Shot 2022-10-18 at 1.39.51 PM (2).png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/060dad79-d723-468c-b249-a70a981915a3)

**Comment by steffipravasi** [comment]
Test status: PAss
The statement for date range has been removed
![Screen Shot 2022-10-19 at 1.19.15 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/479bf2c6-0fed-4842-8c15-9419e92c053c)
Ticket ready for PO review.

**Comment by Travis-A-Clark** [comment]
@telusdcinco When an employee has been auto excused due to PeopleSoft status, the supervisor modal still shows "No" in the Excused dropdown. I think this situation was solved for the HR/Sys Admin view. Can we apply same fix here?

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/3cf54cfd-ac10-4a04-8b1a-94864fcfb993)

**Comment by telusdcinco** [comment]
Displaying Yes for Auto excused employees fixed for My Team modal page.

**Comment by steffipravasi** [comment]
Env: Test
User: Jackie Morrison, Dana Askew
The auto excused employee from PeopleSoft is displayed in the Supervisor's my team page modal. 
![Screen Shot 2022-11-02 at 11.17.58 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/77919563-35b6-484d-975c-7d91143e4f7b)
![Screen Shot 2022-11-02 at 11.21.02 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/0f5ef530-fb01-4146-907a-b1fc3e0b5199)
