### ISSUE TITLE
Add edit / delete functions to comments made on goals

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#797]
Currently, when you add a comment on a goal it is permanent. There is no option to edit or delete (see below)

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/82862558-d259-400b-831d-ef9b37a96174)

Back in Feb 2022 we introduced the ability to edit or delete comments. Somewhere along the way it got lost with all the other work going on. It looked like below (we don't want the headshot anymore).

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/9a17126c-0d50-47ad-944d-e0df2a156927)

If a comment is edited, the timestamp is updated and the word "(edited)" is added to the end of the timestamp. If a comment is deleted, the text is removed and replaced by "_EMPLOYEE NAME_ deleted this comment" with an updated timestamp.

**Comment by steffipravasi** [comment]
@jizhaogit 
Test status: Fail
Env: Test
Users: Sup: Chad Hoskins, Emp: Rebecca Fontaine

i) The supervisor is still not able to edit/delete the comments
![Screen Shot 2022-10-17 at 3.31.31 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/e6abcc10-8922-4f95-962d-7f92d619930f)

**Comment by steffipravasi** [comment]
Test status: Pass
Env: Test
Browser: Chrome, Safari, Edge
Users: Emp: Fiona Cubitt, Supervisor: Nicola Lemmer, Emp shared with supervisor: Shannon Baskerville
The supervisor is now able to add/edit/delete the comments with their name and timestamp. Supervisor and employee cannot edit each others comment. 
As discussed in the Sprint planning with Travis and Ji, we are not changing the text after deletion of comment changed to 'EMPLOYEE NAME deleted this comment'. Keeping it the way it is as the name already appears on top. 
![Screen Shot 2022-10-19 at 5.51.50 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/21edbdd8-c2a5-484c-898a-129ca8f7275b)
Ticket ready for PO review

**Comment by Travis-A-Clark** [comment]
PO approved
