### ISSUE TITLE
Add the hyperlink option to the text editor in the goal comments area

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#798]
Please add the hyperlink option to the formatting bar of the text editor for goal comments. Currently missing (see screenshot below). Thanks!

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/4f1318ff-ca8b-43c9-853b-70131a08fed4)

Related to work in ticket #897

**Comment by steffipravasi** [comment]
@jizhaogit 
**Test status: Fail**
The hyperlink function is seen in the new comments section, but not displayed when '**Edit Comment**' option is selected.
![Screen Shot 2022-11-27 at 11.56.52 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/309e30a5-aee7-49bc-84c0-4e69bf61663b)
![Screen Shot 2022-11-27 at 11.56.34 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/f0b1fc92-69bf-4e91-a843-97a29a8acc72)

**Comment by steffipravasi** [comment]
Test status: Pass
Hyperlink option added to the goals comment section for new comment, edit and reply comments.
![Screen Shot 2022-11-29 at 1.15.08 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/53d44f1c-303c-4b50-b1a6-766df74fc204)
![Screen Shot 2022-11-29 at 1.19.30 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/96575718-ad09-4be2-bca8-1a761dd0a9f1)
Ticket ready for PO review.

**Comment by Travis-A-Clark** [comment]
@steffipravasi All looks good for adding or editing comments on goal. However, I get a couple of extra buttons in the formatting bar when I use the reply function: unlink and about the editor icons. Can this be consistent with adding/editing? I am using Chrome to test.

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/c3011f34-206f-4ce0-98c3-1de01f22784c)

**Comment by steffipravasi** [comment]
@jizhaogit Assigning the ticket back to you to remove the additional buttons from the goal's reply section. Thank you!

**Comment by jizhaogit** [comment]
unlink and about button are removed from replay textarea.

**Comment by SSubashree26** [comment]
Test status: Fail

The text editor has all the buttons while adding, editing and replying in the "My Current goals" and the "My Supervisor's Goals" tab. However, in the "My Past Goals" tab, clicking on the "Reply" button, displays a normal text editor with no buttons in it.

I am able to see this behaviour in all four browsers.

![image.png](https://images.zenhubusercontent.com/63892df90d58261296a2b5c0/d411306c-4f12-4520-8043-0610ac6684c8)

@jizhaogit can you please have a look at it?

**Comment by Travis-A-Clark** [comment]
@jizhaogit I created ticket #897 to deal with the formatting function for the Reply area of the goals comments. We can move the rest of the ticket into production.

@SSubashree26 Can you please confirm that everything else works and is ready for PO Review? Thanks!

**Comment by SSubashree26** [comment]
@Travis-A-Clark I did a quick regression and everything else looks good. Moving this ticket to PO Review column
