### ISSUE TITLE
Supervisor cannot see completed conversations after sign-off

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#805]
Issue is arising for specific supervisors and employees. Both can set up a conversation, comment on the open conversation, and sign-off the conversation. However, when the conversation is signed-off, it only appears in the employee's Completed Conversations area. It disappears from the supervisors view.

In production env, this came to light with:

Supervisor - Kristen Perri - 162806
Employee - Tia Mayer - 168436

Able to recreate the issue with the same users in Dev and Test. Does not happen with everyone.

**Comment by telusdcinco** [comment]
@Travis-A-Clark  Fix deployed to Test for testing.

**Comment by Travis-A-Clark** [comment]
@telusdcinco Creating a new conversation and signing off with Kristen Perri (supervisor) and Tia Mayer (employee) leads to the same result as before: the completed conversation shows for Tia but not for Tia. Looks the same as before the test.

**Comment by telusdcinco** [comment]
@Travis-A-Clark Re-fixed and ready for re-test.

**Comment by steffipravasi** [comment]
Test status: Pass
The user Kristen Perri can view the list of completed conversations the same way as Tia Mayer does.![Screen Shot 2022-10-05 at 3.44.34 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/1bb2e84f-63a7-4eec-8cfc-b832165a40e3)
Ticket ready for PO review
