### ISSUE TITLE
Supervisor has lost access to employees on My Team page

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#806]
Supervisor: Linda Dyck

Situation: Linda had access to her full team under the My Team page up until the latest updates to Prod. Now, she does not see any of her employees on the My Team page and receives an Ajax error when she tries to load the page.

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/36576c1a-5065-4118-aea2-400a55ed9249)

Linda still has all the other normal access to her employees. She can set up conversations with them, share goals with them, add goals to their goal bank, etc. Just not visible on the My Team page.

Now receiving multiple reports of same issue. My Teams page returning Ajax error message. Another example: Rosanna Armeni. Has 13 direct reports, can see them in goal and conversation drop down functions but receives an error message when loading My Team page.

**Comment by jizhaogit** [comment]
updated /app/DataTables/SharedEmployeeDataTable.php for handling errors about reading empty jr query array.

**Comment by Travis-A-Clark** [comment]
This seems to have been resolved with a fix pushed in ticket #825. I am just going to leave this ticket open for now in case the issue returns.
