### ISSUE TITLE
Employee showing up multiple times in the PDP

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#808]
**Scenario:**

Multiple examples of one employee showing up with different records in the PDP. The examples below are from SDPR where the employee moved between SDPR and another organization (not an org that is part of the pilot group of users) and now they are appearing twice in employee lists and admin reports, even if they no longer actually work for SDPR.

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/608cb3ea-90ee-4291-92f4-3fb7ed2b7805)

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/9ed8b355-9caa-493c-a790-d824d384758a)

**Expected Result:**

Employees show up once in the PDP for the organization that they currently work for.

**Comment by jizhaogit** [comment]
sample reproduced in test: Employee ID 124304

**Comment by jizhaogit** [comment]
confirmed with Dennis that the system didn't load inactive data/incorrect data.  the duplicate records are all active.  that means they are all right.  System is currently designed for 1 to 1 employee/manager. But data from ODS is multi because they cannot decide on which one to send - both are active.

**Comment by jizhaogit** [comment]
@steffipravasi Steffi could you please help check with @Travis-A-Clark Travis if we should hold this ticket since we currently don't solution for this ODS problem.  thanks.

**Comment by steffipravasi** [comment]
Moving the ticket to the waiting pipeline.

**Comment by Travis-A-Clark** [comment]
I think the only remaining issues are with people that have more than one valid concurrent record (two active jobs at the same time). That is being addressed in ticket #857.

Closing this ticket.
