### ISSUE TITLE
Bug: Using a Sys Admin access on the Manage Access & Permissions; SQL Error displayed when updating HR Admin access to a Sys Admin, while a Sys Admin record already exist

### ISSUE THREAD

**Issue by telusdcinco** [bcgov/performance#810]
Bug: SQL Error displayed when updating HR Admin access to a Sys Admin, while a Sys Admin record already exist.

![image.png](https://images.zenhubusercontent.com/60e88ef619e4760c8b3ee8bb/6ba8c53d-07e5-4d54-8b9f-ce83ca79737e)

![image.png](https://images.zenhubusercontent.com/60e88ef619e4760c8b3ee8bb/71fd0f43-0cb8-415d-9d61-9763b0388a36)

![image.png](https://images.zenhubusercontent.com/60e88ef619e4760c8b3ee8bb/5f01e469-d4fd-4884-91e0-50d3703738c0)

**Comment by steffipravasi** [comment]
Test pass
Sys Admin not able to update the access from HR admin to Sys admin or vice versa if employee already has a HR admin and Sys admin right. 
![Screen Shot 2022-11-10 at 2.32.12 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/9b4dcd76-59fa-4709-96a3-31936990dd27)
![Screen Shot 2022-11-10 at 2.32.22 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/7c519958-dfe6-4dc2-a014-1152b77e89e1)
If employee has only HR Admin access, then admin can update it to Sys Admin. 
![Screen Shot 2022-11-10 at 2.36.23 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/0700a307-62a4-4859-af69-8f4f2e8ba67c)
