### ISSUE TITLE
Tags missing when goal is copied from My Supervisor’s Goal

### ISSUE THREAD

**Issue by steffipravasi** [bcgov/performance#811]
When supervisor creates a goal and shares it with an employee. Employee copies the goal, other details are seen but the tags are missing. 

Env: Test
User: Shannon.Baskerville@gov.bc.ca, Nicola.Lemmer@gov.bc.ca
Login as supervisor -> Add a new goal -> Share it with a team member -> Login as team member -> Go to My Supervisor’s Goal -> Copy the goal -> Open it from my current goals  

Employee view:  
![Screen Shot 2022-10-04 at 1.46.24 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/b7bbe9be-0a33-47ab-a21f-11af6a19738a)

Supervisor view:
![Screen Shot 2022-10-04 at 1.47.23 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/31008106-930b-4b8e-95c3-cfc8838bfa8d)

**Comment by steffipravasi** [comment]
Test status: Fail
Env: Test
Users: Chad Hoskins - Chad.Hoskins@gov.bc.ca(Supervisor), Blaine Ferguson
Steps to Reproduce: 
- Login as Chad 
- Create a new goal 
- Share it with Blaine 
- Login as Blaine 
- Go to My Supervisor’s Goal 
- Copy the goal 
- Open it from my current goals
Refer to the recording if needed:
https://bcgov.sharepoint.com/:v:/r/teams/02915/Shared%20Documents/General/Test%20cases/MissingGoalTags.mov?csf=1&web=1&e=KQTE9c

**Comment by JonTelus** [comment]
@steffipravasi I failed to finish the push to Test yesterday, but it is complete now.  This fix is present for your review.

**Comment by steffipravasi** [comment]
Test status: Pass
Env: Test
Users: Shannon(supervisor), Cory Scott
The tags are displayed when goal is copied from the supervisor's goal
![Screen Shot 2022-11-23 at 2.49.06 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/6eabc831-0b83-4eff-b367-83bb9e006c4e)
![Screen Shot 2022-11-23 at 2.47.48 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/8ab502e6-13f6-438a-bdeb-5303d30f3de6)
Ticket ready for PO review
