### ISSUE TITLE
Goal Bank -> Date Added Column shifts to the right-hand side on 1st and 2nd page 

### ISSUE THREAD

**Issue by steffipravasi** [bcgov/performance#813]
User: Nicola.Lemmer@gov.bc.ca 
Env: Test 
Device: MacBook 13-inch, browser: Edge/Chrome, Screen is zoomed to 100% 
This user has 3 pages full of goals in the goal bank, when user is on the 1st page the Dates are displayed in 3 lines 
![Screen Shot 2022-10-04 at 2.28.26 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/997cca29-be42-4ef4-acea-5719faeb998c)

In the second page, there are goals with more tags, the view buttons goes out of the frame from the right-hand side 
![Screen Shot 2022-10-04 at 2.30.07 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/8191043c-ebca-44d5-b730-92633467fdaf)

Whereas the goals are displayed perfectly on 3rd page
![Screen Shot 2022-10-04 at 2.32.10 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/8dcbc030-59a5-4633-b807-36cdab1736a5)

**Comment by JonTelus** [comment]
This is due to the length of the text in the title and tag fields.  One solution is to limit the length of those fields being displayed to a certain number of character before it trails off with ...

![image.png](https://images.zenhubusercontent.com/633b378bc8f55808cbd55226/6f0a1f92-dc00-4963-bfa1-e5e58a407896)

**Comment by Travis-A-Clark** [comment]
@JonTelus Thanks for looking into this. I think the limit length for goal titles makes sense. For the tags, could we move from comma separated strings to one tag per line? It would make the list longer vertically but shorter horizontally.

Or can we set hard limits for each column width and force new lines in any input that exceeds the limit?

**Comment by JonTelus** [comment]
@Travis-A-Clark As discussed, I've included a space between tags, and a space after the / in Mandatory/Suggested column name.

**Comment by JonTelus** [comment]
![image.png](https://images.zenhubusercontent.com/633b378bc8f55808cbd55226/8ae3d587-e8e6-4663-9657-22a1c6434195)

**Comment by Travis-A-Clark** [comment]
@JonTelus Thanks for this. I think it looks good to push in to Test and have Steffi try to break it. :-)

**Comment by JonTelus** [comment]
Ready for test.  Added spaces after commas in tag list.  Added space after '\' in Mandatory\Suggested column name.

**Comment by steffipravasi** [comment]
Test status: Pass
Env: Test
Goal bank columns shifting out of frame issue fixed. The solution of adding spaces after commas works well for goals with combinations of title length, tags length and date. 
![Screen Shot 2022-11-28 at 10.49.26 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/b6a38f87-aa72-4f8b-85b5-bf09c3b66a08)
Ticket ready for PO review

**Comment by Travis-A-Clark** [comment]
For some reason, I am not consistently seeing the space between goal tags. Seems about half the time based on screenshot below. Logged in as Travis Clark in TEST. Any ideas as to why?

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/297bdec5-f547-4119-bdd3-7560eb4ccb6e)

**Comment by JonTelus** [comment]
@Travis-A-Clark  There was another section of code that built out the tag list for those goals.  I've updated it to match, and all goals now have the extra space.
