### ISSUE TITLE
Supervisor seeing duplicate version of employee

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#817]
Supervisor Nina Kansakar has duplicate listings for an employee on her team in PDP. The Roberta King listing with 5 goals is correct (see screenshot below)

When I looked up Roberta King in the Sys Admin > Employee List, I only see one record. However, there are clearly two in the supervisor view and they lead to different profiles.

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/aa40568b-3082-437c-a067-bcff588d8259)

**Comment by jizhaogit** [comment]
details:  there are duplicate employee records in **users** table for "Roberta King" but one of the records does not mapping **employee_demo** record.  i updated the query for filtering out the un-matched user record.  And need to check with Dennis to see if any further checking we need to do.

**Comment by steffipravasi** [comment]
The supervisor Nina Kansakar can now see only one entry for team member Roberta King, however @Travis-A-Clark the ticket description says the profile with 5 goals is the correct one, but the profile with 0 goals is displayed in the list now (username is: Robbi.King@gov.bc.ca) @jizhaogit Hopefully we are displaying the right profile.
![Screen Shot 2022-10-25 at 3.34.01 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/1d57d078-b559-4d26-b465-0959acd49875)
![Screen Shot 2022-10-25 at 3.51.53 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/12440d9f-c804-432f-8934-8148e3ad5d03)

**Comment by Travis-A-Clark** [comment]
@steffipravasi I think we are safe with the way it is deleting records. I spoke with Ji and I think it will keep the active record. The screen shot that I supplied in the initial description was actually from Production environment. That's why there's 0 goals there in Test. Thanks!

**Comment by Travis-A-Clark** [comment]
@jizhaogit as you mentioned in a comment above, can you please connect with @telusdcinco to discuss any further checks required to complete this ticket? I'd like to deploy the fix to Dev as soon as possible. Thanks!

**Comment by jizhaogit** [comment]
Talked with Dennis and shared what i found with him. Dennis agreed the join employee_demo with avaliable guid is the way we can take for solving this problem.
