### ISSUE TITLE
Comments are being cut-off in conversation templates; problem with character limit?

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#818]
An employee entered all their comments but the system cut them off mid-word/sentence. This is in the career planning conversation template. Is there a character limit that is being exceeded? If so, we need to greatly expand the character limit for all text boxes.

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/4f93d0b9-0044-4e5b-8635-c20735c2e97c)

**Comment by steffipravasi** [comment]
@jizhaogit 
Test status: Fail
Env: Test
User: Sup:Chad Hoskins, Emp: Rebecca Fontaine

Performance Check-In -> Action Items (optional) 
The supervisor side conversation's Action Items (Optional) cuts off the characters to 187 characters. Other fields are accepting more characters. I can type as many characters as I want but when saved, the text box only saves 187 characters.
![Screen Shot 2022-10-17 at 3.00.48 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/29ad4e77-7c29-4c8a-a43c-4298d020d59d)

**Comment by steffipravasi** [comment]
Test status: Pass
The Action Items in Performance Check-In accepts more characters then 187 on saving.
Issue fixed. 
![Screen Shot 2022-10-18 at 3.49.53 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/0f121059-8837-46c7-a06a-8e259f31d581)
Ticket ready for PO review.
