### ISSUE TITLE
Conversations: save function should only save "my" half of the conversation page

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#819]
**Current Situation**

Travis and Zehra both have the same conversation open. As they are talking, Travis is typing his comments into the comment boxes. They conclude the conversation, Travis saves his input and closes the window.

Problem 1
Zehra still has her window open. She adds comments and saves her input. This effectively erases Travis' input since his half of the screen was still blank in Zehra's window.

Problem 2
Zehra still has her window open. The auto save function is triggered because the window has been open for more than 15 minutes. It saves blanks over everything that was previously entered.

**Desired Outcome**

Travis can only save his side of the conversation and Zehra can only save her side of the conversation. They have no ability to save blank comment boxes over top of previously entered text from the other person.

**Comment by steffipravasi** [comment]
Test status: Pass
The problem 1 and problem 2 has been resolved. 
Along with that, if sup and emp both have windows open, sup add comments, signs and closes the window. Emp adds his comment and closes the window. When opened again emp can see his and sup's comments. 
When both close window by adding comments and signing at same time, the conversation goes to closed conversation and both side comments can be seen.
Ticket ready for PO review.
