### ISSUE TITLE
Completed Conversations: remove two sections of template

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#820]
Once a conversation is signed by both parties and moves to the Completed Conversations area, we should no longer display the "Suggested Discussion Questions" or the "Preparing the Conversation" sections of the template. These should only be visible in the Open Conversations state. 

Please hide these sections in all Completed Conversations. Thanks!

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/812c22a9-cf30-408d-a95e-6c61be17723b)

**Comment by steffipravasi** [comment]
[https://bcgov.sharepoint.com/:v:/r/teams/02915/Shared%20Documents/General/Test%20cases/820.mov?csf=1&web=1&e=OxdXGd](https://bcgov.sharepoint.com/:v:/r/teams/02915/Shared%20Documents/General/Test%20cases/820.mov?csf=1&web=1&e=OxdXGd)

**Comment by jizhaogit** [comment]
@steffipravasi the session show/no-show is controlled by js **after** the conversation be loaded.  you can only see the 2 sessions in a completed conversation when the conversation modal is opened but the conversation itself is not loaded.

**Comment by jizhaogit** [comment]
talked with Travis @Travis-A-Clark the 1 second UI delay is acceptable.  he suggested we still go what it is now.

**Comment by steffipravasi** [comment]
Ticket functioning as expected. The "Suggested Discussion Questions" or the "Preparing the Conversation" sections are hidden when the conversation is completed
Both the sections can be seen if the completed conversation is signed and opened again. Not displayed when again signed and closed the convo.
Ticket ready for PO review.
