### ISSUE TITLE
As an employee, I want the ability to "hide" goals in my goal bank that I no longer want to see.

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#822]
Add the ability for employee's to hide/unhide goals in their employee goal bank to allow them to minimize the list of goals and not have to sort through goals they have already decided are not relevant to them. This would not permanently delete the goals.

This update an possibly be combined with the My Goals redesign in ticket #620.

Design:
![My Goals _ My Goal Bank.png](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/1505e1cc-3233-4959-a652-6e6e0ae79f1b)

![My Goals _ Hidden Goals.png](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/be06b05c-a133-45dc-a534-64826644d155)

**Comment by jchow11** [comment]
@Travis-A-Clark Should an employee be able to hide all goals ("Mandatory" and "Suggested") or only "Suggested" goals?

**Comment by Travis-A-Clark** [comment]
@jchow11 Both types of goals. The fear is the list may get quite long over time, especially if the HR Admins for the org don't do a good job keeping things up to date and removing old content. This is just a way to non-destructively allow users to clean up their view. Thanks!

**Comment by jchow11** [comment]
@Travis-A-Clark Let me know what you think of this solution! Thanks.

**Comment by Travis-A-Clark** [comment]
@jchow11 I like it! Doesn't add additional clutter to the table and takes advantage of the select function already in place. Thanks for this. :-)

**Comment by jchow11** [comment]
Excellent! I agree, I wanted to avoid adding additional columns to the table. Let me know if there's anything else you need from me!

**Comment by jizhaogit** [comment]
ticket is ready for test

**Comment by steffipravasi** [comment]
@jizhaogit The goal bank page gives a 500 error when opened. 
Testing blocked.

**Comment by jizhaogit** [comment]
a db migrate script was missing.  the 500 error is addressed. Please go ahead for the testing. thank you!

**Comment by steffipravasi** [comment]
1) Spelling mistake: change to relevant![Screenshot 2023-07-28 at 11.11.46 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/c7b52055-14c0-4c74-a01d-255829e43511)
2) Goals are not hidden when selected and the hide button is clicked. Goals still remain in the my goal bank section.https://bcgov.sharepoint.com/:v:/r/teams/02915/Shared%20Documents/Product%20Team/Steffi%20-%20Testing/822.mov?csf=1&web=1&e=28uIbP

**Comment by jizhaogit** [comment]
issue addressed. please verify. thanks

**Comment by steffipravasi** [comment]
@jizhaogit The hidden goals section looks good. Can I request a small button name change.
Change the button name to 'Move Selected Goals to My Goal Bank'![Screenshot 2023-07-28 at 4.04.26 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/4ce9dcb6-f06d-4599-a647-0c9faf314317)

**Comment by steffipravasi** [comment]
Test validated. Button has been renamed. Tracking the date added field issue in #1077. 
Moving for PO review.
