### ISSUE TITLE
Disappearing Conversation Comments - Case Details

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#830]
Environment: Production

Supervisor: Carolyn Babakaiff (ID 022540)
Employee: Priya Kullar (ID 146315)

Conversation topic: Performance Check-In
Data ID: 1071

Scenario

- Supervisor entered comments. Saved comments and did not sign.
- Employee opened conversation. Did not see supervisor comments. Refreshed page, opened conversation again, and could see supervisor comments.
- Employee entered their comments. Employee signed off.
- Supervisor comments disappeared. Employee comments remain.

-----

Environment: Production

Supervisor: Margaret Burrows (ID 128100)
Employee: Jennifer Reid (ID 153145)

Conversation topic; Onboarding
Data ID: 776

- Supervisor added comments and signed off
- Supervisor un-signed so that employee could add comments
- Employee added comments and signed-off
- Supervisor's comments disappeared

**Comment by steffipravasi** [comment]
Scenario 1: Pass
Users: Carolyn.Babakaiff@gov.bc.ca(supervisor), Priya.Kullar@gov.bc.ca
Browsers: Edge, Firefox
Followed the steps listed in the scenario. 
Actual result matched the expected results. Comments are not lost.
![Screen Shot 2022-11-24 at 3.15.11 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/99935623-32ad-4311-9104-0ea02d2c647a)
![Screen Shot 2022-11-24 at 3.14.50 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/cb781795-953a-45a3-abb9-7416a799e2f7)

**Comment by steffipravasi** [comment]
@jizhaogit 
Scenario 2: Fail
Users: Meg.Burrows@gov.bc.ca(supervisor), Jenny.Reid@gov.bc.ca
Browsers: Supervisor: Safari, Firefox, team member: Edge
When a new conversation is created from the supervisor(Margaret's side) and Jenny added to the conversation, the conversation is not displayed on Jenny's profile.

Convo templates tried are Onboarding, Performance - CheckIn
Please refer to recordings:
1. https://bcgov.sharepoint.com/:v:/r/teams/02915/Shared%20Documents/General/Test%20cases/830%20-%20Safari-edge.mov?csf=1&web=1&e=Cxie5T
2. https://bcgov.sharepoint.com/:v:/r/teams/02915/Shared%20Documents/General/Test%20cases/830%20-%20Firefox-edge.mov?csf=1&web=1&e=nliSUe
Data (For onboarding template: data-id: 156

**Comment by steffipravasi** [comment]
@jizhaogit 
Scenario 2: Fail
Users: Meg.Burrows@gov.bc.ca(supervisor), Jenny.Reid@gov.bc.ca
Browsers: Supervisor: Safari, Firefox, team member: Edge
When a new conversation is created from the supervisor(Margaret's side) and Jenny added to the conversation, the conversation is not displayed on Jenny's profile.

Convo templates tried are Onboarding, Performance - CheckIn
Please refer to recordings:
1. https://bcgov.sharepoint.com/:v:/r/teams/02915/Shared%20Documents/General/Test%20cases/830%20-%20Safari-edge.mov?csf=1&web=1&e=Cxie5T
2. https://bcgov.sharepoint.com/:v:/r/teams/02915/Shared%20Documents/General/Test%20cases/830%20-%20Firefox-edge.mov?csf=1&web=1&e=nliSUe
Data (For onboarding template: data-id: 156

**Comment by jizhaogit** [comment]
@steffipravasi the Jennifer Reid has 3 records in test env. By some reason the superviso/employee relationship with Margaret Burrows  is the one who does not have Employee ID. please see the screenshot below:

![image.png](https://images.zenhubusercontent.com/620163b737f8d3386467e70d/da20e9f5-7434-4099-8290-3681ac48f2d7)

![image.png](https://images.zenhubusercontent.com/620163b737f8d3386467e70d/db5ab427-dc9f-4306-8dd2-e1476d908981)

**Comment by steffipravasi** [comment]
The second scenario is not possible to test on the Test environment because of the incorrect user profile attached to the supervisor. The user Jennifer Reid's account does not show any employee Id to test. 
But we have tested the same scenario for other employee/supervisor pair and seems to be working as expected now. 

Moving this ticket for PO review.
