### ISSUE TITLE
Conversation comments are not displayed when accessed through home page notifications

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#832]
If I click on this home page notification to enter the conversation:

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/b2762797-a3ee-4818-b1e2-6a69fbd081f7)
<br>

I don't see any comments in the conversation template:

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/c31ad4c5-8908-4c68-b3bd-578c334fc19a)
<br>

But if I click on the same conversation through My Conversations > Open Conversations:

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/8054f59b-a848-47f4-b0b3-c7c27c6e265d)
<br>

I do see comments in the the conversation template:

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/ad8c6672-39b2-4cd5-b782-75e7ae6b7393)
<br>

An additional complexity is that once I have opened the template through My Conversations > Open Conversations one time, then the home page notification link works as expected. In other words, it seems to remember the content and display it properly. However, clicking the home page link again sometimes shows only part of the comments. Not sure what the pattern is. Potential cache issue?

**Comment by Travis-A-Clark** [comment]
@jp-Telus As mentioned on the call this morning, if we can't get the home page notifications links to consistently display the correct conversation template information, we will have to disable these notifications on the site to avoid confusion. 

Also, there are a couple of small edits to make to the home page notifications for conversation due dates as well. 

When the notification is for the employee themselves it should say: Your next conversation is due by _DATE_

When the notification is for a supervisor about on of their employees it should say: _EMPLOYEE NAME_'s next conversation is due by _DATE_

Thanks!

**Comment by Travis-A-Clark** [comment]
Env: TEST
Supervisor: Travis Clark
Employee: Olurotimi Famodile

Clicking on home page notification on employee home page:

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/0cdf52c7-f876-4cf0-80c1-c9b32d0332cc)
<br>
Launches conversation template and shows no info:

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/e9b4e09b-f926-49d4-b5fa-7a0b20a5eb04)
<br>

Going to My Conversations > Open Conversations and clicking on the same template directly shows all the comments:

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/3c8bd06d-9930-407d-8321-59ad0f2c9b3a)

**Comment by jp-Telus** [comment]
@Travis-A-Clark 

Per discuss, I have disabled the "view" button for any conversation notification on the Home Page. And update the wording on the In-App notification.  I also fixed a minor bug on the notification log, search not working properly,

Already migrate to DEV and TEST regions.

Thanks.

**Comment by Travis-A-Clark** [comment]
@jp-Telus Thanks! We are going to push this to Prod this morning along with one of Dennis' tickets.
