### ISSUE TITLE
Incorrect count on Open and Completed Conversation Count (related to #733 Remove Excused employees from Goals, Conversations, and Shared reports) 

### ISSUE THREAD

**Issue by jp-Telus** [bcgov/performance#833]
The Open and Completed conversation reports is showing wrong numbers. The count in the reports is not matching to the actual data regardless of the excused status. James looking into that issue. 

Other reports such as Shared Employees Summary, Excused Employee and Goals Summary reports are displaying the right numbers. Test data used is in this [document ](https://bcgov.sharepoint.com/:w:/r/teams/02915/_layouts/15/doc2.aspx?action=editNew&sourcedoc=%7Bcf13a53a-20aa-4c12-868f-caafb430e2c0%7D&wdOrigin=TEAMS-ELECTRON.teamsSdk.openFilePreview&wdExp=TEAMS-CONTROL&wdhostclicktime=1667516601510&web=1&cid=9d707f19-3da1-4028-9e24-889ff7be116c) 

Will verify all reports again once James fixes the conversation report.

**Comment by jp-Telus** [comment]
@steffipravasi 

The fix was applied on both DEV abd TEST regions. Please kindly retest.

**Comment by steffipravasi** [comment]
The testing is blocked due to the Statistics and Reports tab being disabled in the My Teams menu.

**Comment by jp-Telus** [comment]
@steffipravasi 

The menu was enabled now on DEV and TEST now. Thank you.

**Comment by steffipravasi** [comment]
@jp-Telus I see some differences in numbers which we might need to discuss. They are documented in this [Document](https://bcgov.sharepoint.com/:w:/r/teams/02915/_layouts/15/doc2.aspx?action=editNew&sourcedoc=%7Bcf13a53a-20aa-4c12-868f-caafb430e2c0%7D&wdOrigin=TEAMS-ELECTRON.teamsSdk.openFilePreview&wdExp=TEAMS-CONTROL&wdhostclicktime=1667516601510&web=1&cid=9d707f19-3da1-4028-9e24-889ff7be116c)
Env: Test
Users: 
Nicola Lemmer 
Anthony Loughran
Shannon Baskerville 
Chad Hoskins 
Kristen Perri

**Comment by jp-Telus** [comment]
@steffipravasi 

Per discuss, I have modified the criteria for classify the 'Open Conversation' and 'Completed Conversion':
1. For Open Conversation, both are not signoff 
2. For Closed Conversation, both are signoff

Thank you,

**Comment by steffipravasi** [comment]
There are some instances where an employee is no more a team member for the supervisor but they have an open conversation. That conversation is displayed in the 'Open Conversation' tab but will not be included in the Statistics and Reports.

**Comment by steffipravasi** [comment]
Supervisor: Chad Hoskins, Team member: Martha Williams(Marty.Williams@gov.bc.ca)
The conversation for Onboarding is displayed in the Statistics and Reports but not displayed in the Open Conversation list for Chad. 
Conversation displayed in Martha's list.

**Comment by jp-Telus** [comment]
@steffipravasi 

Per my findings, the current page was design with limit 10 rows on the 'Open Conversation' tab. Per our discussion, you will create a new ticket for that. Thanks.

**Comment by steffipravasi** [comment]
@jp-Telus Yes. I have addressed that issue in a separate ticket #852. 
Will leave this ticket in the Testing pipeline until 852 is fixed.

**Comment by steffipravasi** [comment]
Test status: PAss
Env: Test
Users: Chad Hoskins, Shannon
- The count for Open and Closed conversations is displaying accurate results now with excused employees not added in the count. 
- There are cases where an open conversation can be seen but count in statistics and reports is different is because of changing Supervisor-Team members or the employee having a different supervisor now.
- For conversation number exceeding more than 10 will be resolved in ticket 852 and can be tested then. The count in statistics and report is correct but the conversation cannot be seen in Open and Closed conversations list.

Marking this ticket as completed and ready for PO review.

**Comment by Travis-A-Clark** [comment]
@steffipravasi just to confirm: this was only applicable for the supervisor view of statistics and reporting. This particular thing was not an issue for Sys or HR Admin, correct?

**Comment by telusdcinco** [comment]
@jp-Telus @Travis-A-Clark 
Pushed change to Dev/Test/Prod to hide the My Team Stat & Report menu item.  Will not reflect in Prod until the pods are restarted.
