### ISSUE TITLE
My Team > Goal Bank > Team Goal Bank

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#835]
There are still a few old fixes that don't seem to have taken hold in PROD. 

The goal Tags area is not auto sorted alphabetically (see all new tags are shown together at bottom of list):

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/6aed36ce-6703-4308-a3b7-6f848b14dfb7)

Once a goal is created in the Team Goal Bank, the dropdown still says "All Direct Reports" instead of "All". Related to ticket #792.

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/5cfc77e3-b284-45c7-bf02-28449a817e05)

**Comment by steffipravasi** [comment]
Env: Test
i) The last few goal Tags in My Goal -> Goal Bank -> Team Goal bank are still not sorted alphabetically.
![Screen Shot 2022-11-17 at 11.57.29 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/3f22812f-db97-42e4-9461-8333a70159cb)

**Comment by jizhaogit** [comment]
a new updated is deployed. should be good now.

**Comment by steffipravasi** [comment]
Env: Test
Status: Pass
The goal Tags in My Goal -> Goal Bank -> Team Goal bank are now sorted alphabetically.
![Screen Shot 2022-11-18 at 12.50.59 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/b3c63004-8537-4eb2-b5eb-2f41a84f036e)
![Screen Shot 2022-11-18 at 12.51.12 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/e9fc3488-81bd-4d71-ac10-86c6e3cdf280)
Ticket ready for PO review
