### ISSUE TITLE
Trigger Re-Calc of Next Conversation Due Dates when Conversations are completed.

### ISSUE THREAD

**Issue by telusdcinco** [bcgov/performance#836]
Trigger Re-Calc of Next Conversation Due Dates when Conversations are completed.

Separated from #834 as the ticket was marked as done.

**Comment by telusdcinco** [comment]
@Travis-A-Clark As discussed, I've pushed the fix for Next Conversation Due Date calculation to Dev & Test.
Additional trigger added to save a new row in the employee_demo_jr table for cases where the conversation is updated resulting in a new Next Conversation Due Date.
This fix will trigger for any user whose Last calculated Next Conversation Due Date does not match the current calculated one. In essence, this can be the auto-correct for conversation due dates on a daily basis.
The new row inserted will be exactly as the last entry with he exception of the incremental counter id number and the new Next Conversation Date.

**Comment by Travis-A-Clark** [comment]
Tested overnight and it seems to solve the issue in TEST. Pushing to PROD this morning. Thanks!
