### ISSUE TITLE
New Conversation Due Date Calculation process failing to complete in Prod.

### ISSUE THREAD

**Issue by telusdcinco** [bcgov/performance#841]
New Conversation Due Date Calculation process failing to complete in Prod.

![image.png](https://images.zenhubusercontent.com/60e88ef619e4760c8b3ee8bb/90b0c8c6-ff7b-41c5-8281-d9c69d0bd38a)

**Comment by telusdcinco** [comment]
Replication in local completed with proposed work-around solution, until permanent solution can be fully tested and deployed.  Please refer to doc below for details.

![image.png](https://images.zenhubusercontent.com/60e88ef619e4760c8b3ee8bb/7c9617ea-17b7-4890-8716-5f1d7988e1f2)

**Comment by telusdcinco** [comment]
@Abuchana  The employee ID with issue is EE 168883.  Please let me know if "Leave Not Captured in PeopleSoft" is a good enough reason to temporarily assign to the employee.

![image.png](https://images.zenhubusercontent.com/60e88ef619e4760c8b3ee8bb/6f1dd665-582e-435f-9a43-5036d118407d)

Once the reason is updated, we can either trigger the Calc process manually so the Next Conversation Dates are immediately fixed for employees with changes since last Thursday, or we can wait for the scheduled overnight process to trigger to fix the dates for recently updated employee excuses.  Either way, the correct inapp or email notification will be sent as per scheduled (2:30am, daily).

**Comment by Abuchana** [comment]
@telusdcinco, yes that reason is good for now at least.

**Comment by telusdcinco** [comment]
@Abuchana Updated the employee's excused reason.

![image.png](https://images.zenhubusercontent.com/60e88ef619e4760c8b3ee8bb/fa6332b2-70c9-471a-bf4f-f160cddceb26)

**Comment by telusdcinco** [comment]
@Abuchana The overnight Next Conversation Date Calc process completed successfully.  The 2am run should have taken care of all the missed employee next conversation due date re-calculations due to process error since Friday morning.

![image.png](https://images.zenhubusercontent.com/60e88ef619e4760c8b3ee8bb/0b2d2310-1e6c-4b8f-ace2-1f50aeb59a7d)

@jp-Telus Please confirm if 2:30am notification process triggerred emails correctly.  Thanks.

**Comment by telusdcinco** [comment]
The permanent fix to the Excuse modal page have been deployed to Dev and Test.  Solution will display the default initial value for Reason as per normal loading, even when there is an invalid value from previously saved rows.

![image.png](https://images.zenhubusercontent.com/60e88ef619e4760c8b3ee8bb/44457384-b3cb-4246-a008-21f46c8ca5f6)

@steffipravasi Testing for this scenario requires old data setup, for a saved excuse from when PDP was still using excused start/end dates.  Please refer to previously attached  Word doc for replicating the issue prior to this fix (PDP_841_Issue.docx).  Please let me know when you are validating in Test so I can assist in setting up your test employee to match the issue.

Please note that the fix applies to both HR/Sys Admin Excused and MyTeam Excused modal pages.

**Comment by steffipravasi** [comment]
Denis and Me will test the ticket together, scheduled on Monday Oct 21,2022 (10:30-11:30 AM PT)

**Comment by steffipravasi** [comment]
Test: Pass
Env: Test
Users: 000124-Enderton,Torri
000135- Milum,Paula
000136- Malkinson,Leah M
Manually Excused the users first, set their reason id's to 1 and 2. Since the value of 1 and 2 for reason_id are reserved for PeopleSoft Status, and Classification, the modal page should default Reason to "Casual Employee"
![MicrosoftTeams-image (4).png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/d76ea4bf-301c-4ae7-8c3c-fab19a3bcd2e)
![Screen Shot 2022-11-21 at 2.36.57 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/edd5849d-58b6-4d47-bea5-39d3e8be9701)
