### ISSUE TITLE
ISSUE: User Maisonneuve, Cheri does not have access to the PDP - Possible double GUID

### ISSUE THREAD

**Issue by Abuchana** [bcgov/performance#842]
Can you please check employee CHERI MAISONNEUVE (ID#138584) in the backend of the PROD environment to let me know if you see anything blocking them from accessing the system? When they try to authenticate they are receiving error message:

![image.png](https://images.zenhubusercontent.com/6005ca03d883b372a058fe50/ebc7ed86-c153-4187-96ca-e5ee6ce86826) 

Here are their responses to the background questions:
•	I am a PSA at the Learning Centre
•	What browser are you using? (I tried all three, chrome, edge, firefox)
•	What authentication method did you try (IDIR, Azure IDIR, both)? IDIR
•	Are you having issues accessing any other services (Time and Leave, Learning Management, etc)? I have, but think they have now been mostly resolved.

**Comment by jp-Telus** [comment]
@telusdcinco 

Here is my findings:
1. The user profile in PDP (Cheri.Maisonneuve@gov.bc.ca  138584) was created on 2022-07-15 13:58:55, and the GUID is 6278xxxxxxxxxxxxxxxxx.
2. She never logged in to Performance system
3. the GUID in Employee demography data now is B77AFxxxxxxxxxxxxxxxxx

I am not sure when the GUID was changed for this users. 

In order to fix this login issue, GUID should be updated to new GUID.

Any comments? How to fix the data in Production ?

Thank you.

**Comment by JonTelus** [comment]
Within PeopleSoft, I can see that this user validated, for what appears to be the first time, on Oct 14.  The GUID associated with them is the B77AFxxxx James mentions.

**Comment by telusdcinco** [comment]
Fix deployed to Dev for  validation.  User can be replicated in Dev, not being able to sign in.  After update script executed in Dev, user should be able to sign in.

**Comment by steffipravasi** [comment]
![Screen Shot 2022-11-17 at 1.31.02 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/9246acb5-cb2f-4a84-a787-e0de650aa91c)

**Comment by Abuchana** [comment]
Approved as acting PO

**Comment by telusdcinco** [comment]
@Abuchana I have pushed the changes to Prod, but the users will not be able to sign in until, the App Servers are restarted, and the update scripts are executed.  I will try to perform the App Server restart and script execution after 5pm today.  Will update after if completed successfully.

**Comment by telusdcinco** [comment]
![image.png](https://images.zenhubusercontent.com/60e88ef619e4760c8b3ee8bb/0478fc68-3d08-4d92-92bb-3035ae7dc215)
