### ISSUE TITLE
ISSUE: User Faludi, Gabrielle  does not have access to the PDP - Possible double GUID

### ISSUE THREAD

**Issue by Abuchana** [bcgov/performance#843]
From: Performance Development PSA:EX <Performance.Development@gov.bc.ca> 
Sent: November 16, 2022 11:00 AM
To: Faludi, Gabrielle PSA:EX <Gabrielle.Faludi@gov.bc.ca>
Cc: Buchanan, Alison L PSA:EX <Alison.Buchanan@gov.bc.ca>; Ramirez, Eddie PSA:EX <Eddie.Ramirez@gov.bc.ca>
Subject: RE: Faludi Sign In issues

Hi Gabrielle,

Thank you for checking in with us. The IT group that Travis referred to in his email is specific to the Performance Development Platform, so you would not be able to reach out to them directly. However, my colleague Alison whom I have cc’d on this email with look into this and we will work on getting an update to you as soon as we can. In the meantime, can you please confirm that you still cannot access the Performance Development Platform?

I’m sorry it’s taking so long but we appreciate you patience as we work through this.

Thanks,
Zehra

The Performance Management Team

From: Faludi, Gabrielle PSA:EX <Gabrielle.Faludi@gov.bc.ca> 
Sent: November 16, 2022 9:59 AM
To: Performance Development PSA:EX <Performance.Development@gov.bc.ca>
Subject: RE: Faludi Sign In issues

Hi there, 

I thought I’d follow up with this as I never heard back from IT. Is there a ticket number I can reference when I call them today?

Gabrielle

From: Performance Development PSA:EX <Performance.Development@gov.bc.ca> 
Sent: October 19, 2022 3:49 PM
To: Faludi, Gabrielle PSA:EX <Gabrielle.Faludi@gov.bc.ca>
Subject: RE: Faludi Sign In issues

I can escalate it with our IT folks that work specifically on the PDP to see if they can track down your employee record and figure out why it is not successfully being imported. If you already have access to PeopleSoft, it seems likely it’s a situation for my team to resolve rather than the broader IT team.

I’ll let you know as soon as I have an update for you.

Thanks for your patience,
Travis

Travis Clark, Performance Management Lead
Corporate Workforce Strategies | BC Public Service Agency
865 Hornby Street | Vancouver, BC | V6Z 2G3
Tel: 778-360-2044

From: Faludi, Gabrielle PSA:EX <Gabrielle.Faludi@gov.bc.ca> 
Sent: October 19, 2022 3:45 PM
To: Performance Development PSA:EX <Performance.Development@gov.bc.ca>
Subject: RE: Faludi Sign In issues

I’ve been here for a couple of months now. I’m pretty sure my IDIR is verified and I do have access to People Soft and use it daily. Is it time to go to IT?

From: Performance Development PSA:EX <Performance.Development@gov.bc.ca> 
Sent: October 19, 2022 2:57 PM
To: Faludi, Gabrielle PSA:EX <Gabrielle.Faludi@gov.bc.ca>
Subject: RE: Faludi Sign In issues

Hi Gabrielle,

Thanks for following up. The Performance Development Platform (PDP) syncs with our PeopleSoft system (primary HR system of record) every night to pull the current list of active employees. When I look in the PDP, I don’t see your name in the master employee list which would indicate that it just needs time to catch up to PeopleSoft.

When did you activate your IDIR and get set up on the other services?

Regards,
Travis

Travis Clark, Performance Management Lead
Corporate Workforce Strategies | BC Public Service Agency
865 Hornby Street | Vancouver, BC | V6Z 2G3
Tel: 778-360-2044

From: Faludi, Gabrielle PSA:EX <Gabrielle.Faludi@gov.bc.ca> 
Sent: October 19, 2022 2:30 PM
To: Performance Development PSA:EX <Performance.Development@gov.bc.ca>
Subject: RE: Faludi Sign In issues

Oh, and here’s the sign in error visual I get. 

 

From: Faludi, Gabrielle PSA:EX 
Sent: October 19, 2022 2:29 PM
To: Performance Development PSA:EX <Performance.Development@gov.bc.ca>
Subject: Faludi Sign In issues

Hi there, 

I was the one that had questions about signing in. My IDIR is validated and all that but maybe you can help me determine if this is an IT problem or if there is something else that’s blocking me. 

If you need it my IDIR is GFALUDI              

Gabrielle Faludi, Recruitment Support, Recruitment Service Delivery
Talent Acquisition & Classification Services | BC Public Service Agency
333 Victoria Street | Nelson, BC | V1L 1N2
AskMyHR | www.gov.bc.ca/myhr/contact

**Comment by jp-Telus** [comment]
@telusdcinco 

Here is my findings, GUID changed on this employee
Gabrielle Faludi (Employee ID 178381) 
1. User Profile created on 2022-08-23 00:26:45 with GUID 38817xxxxxxxxxxxxxxxxxxxxx
2. never signon to PDP
3. per latest employee demography data, the guid is D10BD8xxxxxxxxxxxxxxxxx (last updated is 2022-09-02 09:06:30)

**Comment by telusdcinco** [comment]
Fix deployed to Dev for  validation.  User can be replicated in Dev, not being able to sign in.  After update script executed in Dev, user should be able to sign in.

**Comment by steffipravasi** [comment]
![Screen Shot 2022-11-17 at 1.25.41 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/4889926d-40a7-45a3-b447-0b3344d5d514)

**Comment by Abuchana** [comment]
Approving as the acting PO

**Comment by telusdcinco** [comment]
@Abuchana I have pushed the changes to Prod, but the users will not be able to sign in until, the App Servers are restarted, and the update scripts are executed.  I will try to perform the App Server restart and script execution after 5pm today.  Will update after if completed successfully.
