### ISSUE TITLE
ISSUE: Spelling error, change "perticiapants" to participants

### ISSUE THREAD

**Issue by Abuchana** [bcgov/performance#845]
Note from user: I’m not sure if you are aware of this or not but I’ve been having conversations with my staff and every time I go to the My Conversation page I see this.  Thought I would point it out in hopes it can be fixed.  😊 

Once you've selected a template for use, select participants and hit "Use this template" to alert perticiapants you want to meet. Conversations will still need to be scheduled independently in your outlook calendar.

**Comment by steffipravasi** [comment]
Env: Test
Status: Pass
Spelling error fixed to 'participants'
![Screen Shot 2022-11-18 at 1.13.10 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/a0624bb2-c195-481e-9c4c-b6fd6d70e061)
Issue to be verified on Prod after deployment
Ticket ready for PO review
