### ISSUE TITLE
ISSUE: User name change has not been updated in the PDP

### ISSUE THREAD

**Issue by Abuchana** [bcgov/performance#846]
ID: 160168
Name in PeoplSoft: Siera Hicks (correct)
Name as it appears in PDP: Siera McGilp-Palmer

**Comment by Abuchana** [comment]
@steffipravasi can you test this or does it have to be the user or Sys Admin?

**Comment by steffipravasi** [comment]
Employee username changed to Siera Hicks
Env: Test
![Screen Shot 2022-11-21 at 11.22.27 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/418b7584-2dc6-4e43-8cbd-f3973262b8b2)
Username: Siera.McGilpPalmer@gov.bc.ca	
ID: 160168
Ticket ready for PO review
