### ISSUE TITLE
ISSUE: Shared goal not showing up on dashboard (Greg Winston --> Jeremy Scott)

### ISSUE THREAD

**Issue by Abuchana** [bcgov/performance#850]
From Jeremy Scott: My employee (Greg Winston – 189094) has screen-shared his goals with me in our PDP conversations but I am unable to view any of the goals he has input on my PDP. I have confirmed he has published them and even watched him click “Notify Supervisor” but I still see nothing in my dashboard

**Comment by telusdcinco** [comment]
@Abuchana I checked in prod backend and don't see any goals created by Gregory Winston.  PDP does not have a "Notify Supervisor" button.

@kevindavidb Please confirm if "Notify Supervisor" is a legacy functionality.

**Comment by kevindavidb** [comment]
Yes, the "Notify Supervisor" button is legacy.  I see in the legacy system the Gregory has created goals and set the first two tabs to publish on Nov 16. , and using Jeremy's account and opening Gregory's plan, I see the goals there. 

Can we confirm this is for sure a PDP issue and not a MyPerformance usage issue? Or would he be using both systems simultaneously?
![image.png](https://images.zenhubusercontent.com/600a0f4bd3610785b8e87cad/d2614d11-0248-4309-9ed4-ed12ab55111f)
