### ISSUE TITLE
Open and Closed Conversations list do not display more than 10 conversations

### ISSUE THREAD

**Issue by steffipravasi** [bcgov/performance#852]
The Open and Closed Conversations tab right now does not show more than 10 conversations. When new conversations are added to the list, the older one's are disappeared. 
Hence, we need to have a pagination to divide and display the older conversations in the next page.  

Example:
Supervisor: Chad Hoskins(Chad.Hoskins@gov.bc.ca), Team member: Martha Williams(Marty.Williams@gov.bc.ca)
Login as Chad: The conversation for Onboarding is displayed in the Statistics and Reports but not displayed in the Open Conversation list for Chad.
Conversation displayed in Martha's list.

![Screen Shot 2022-11-22 at 10.39.16 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/46a7f3b4-4b35-4c22-8656-f911cd1bbec0)

**Comment by steffipravasi** [comment]
@Travis-A-Clark We need your suggestion on this issue. If we are displaying 10 conversations on one page. What if there are 10 conversation with the supervisor? The Conversations with My Team will be displayed on the next page?
Or would we need 2 separate pagination for the supervisor and my team?

**Comment by Travis-A-Clark** [comment]
@steffipravasi I think I am going to combine this with ticket #623 that has a bunch of other redesign elements for the conversations area. This is already in Ji's backlog, Thanks!

**Comment by steffipravasi** [comment]
We can close this ticket, as pagination issue will be solved in ticket 623.
