### ISSUE TITLE
Create chron job to update mismatched GUIDs overnight

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#854]
I know that we have a process that we run when an employee loses access because of multiple GUIDs in the system. Can we run an auto check and update for double GUIDs as part of our overnight processes?

**Comment by telusdcinco** [comment]
@Travis-A-Clark 

Testing the process locally uncovered another data issue relating to GUID.  Found some employees with multiple GUID values.

Below is from Prod.  Other environments have more rows.
![image.png](https://images.zenhubusercontent.com/60e88ef619e4760c8b3ee8bb/e984d6b1-e853-4f23-a762-a401ff9d933b)

**Comment by Travis-A-Clark** [comment]
@telusdcinco These looks to be the cases where the employee has more than one legitimate job with the public service at the same time. Ticket #857 is meant to explore solutions for this.

**Comment by Travis-A-Clark** [comment]
@telusdcinco These looks to be the cases where the employee has more than one legitimate job with the public service at the same time. Ticket #857 is meant to explore solutions for this.

**Comment by telusdcinco** [comment]
Ticket #892 created for the creation of the audit table to be used by scheduled jobs for tracking field changes/updates.

**Comment by telusdcinco** [comment]
@jizhaogit Ready for you review before pushing to Test.

**Comment by jizhaogit** [comment]
@telusdcinco Thank you, That looks good to me.

**Comment by SSubashree26** [comment]
Performed the following to validate this story in the testing environment
- Picked up some random employees with whom I was able to login, and shared their IDs with Dennis
- Dennis modified the GUIDs of those employees
- Validated that I was not able to login with the employees for whom the GUID was modified
- Dennis ran an overnight job, which updated the employee IDs to their previous GUID value 
- I was able to login with those employee IDs again 
- Also audit logs were created for the overnight that was run (for UpdateGUIDByEmployeeId process)

Screenshots:
Initial IDs that were chosen for performing the test 
![Screenshot 2023-01-24 at 4.49.46 PM.png](https://images.zenhubusercontent.com/63892df90d58261296a2b5c0/7b697ecc-9a65-4d73-9d82-1505f673ff0f)

Dennis added "test" in front of the GUIDs and modified them
![Screenshot 2023-01-24 at 4.50.53 PM.png](https://images.zenhubusercontent.com/63892df90d58261296a2b5c0/18221302-1152-4d49-bb19-62f342a8a311)

Was not able to login to the application with the employees whose GUIDs were modified
https://bcgov.sharepoint.com/:v:/r/teams/02915/Shared%20Documents/General/Testing/Testing%20screenshots/Performance%20%23854/854%20-%20Not%20able%20to%20login%20after%20modifying%20the%20GUID.mov?csf=1&web=1&e=bhUaEy

Dennis ran an overnight and the employee IDs were modified back to the previous correct values ![Screenshot 2023-01-24 at 4.56.37 PM.png](https://images.zenhubusercontent.com/63892df90d58261296a2b5c0/1adbff96-4954-48bb-b151-3d859e0de214)

Was able to login to the application with the employees again
https://bcgov.sharepoint.com/:v:/r/teams/02915/Shared%20Documents/General/Testing/Testing%20screenshots/Performance%20%23854/854%20-%20able%20to%20login.mov?csf=1&web=1&e=O5dK5F

Audit logs for the overnight
![Screenshot 2023-01-24 at 4.58.39 PM.png](https://images.zenhubusercontent.com/63892df90d58261296a2b5c0/8dbfb895-8168-4b0e-8b8e-77f1a97e2465)

Moving this story to "PO Review" column, as it is working fine.
