### ISSUE TITLE
PDP must deal with employees with concurrent (multiple) active job records

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#857]
There are approximately 200 employees across the BC Public Service that have more than one, legitimate, employee record at the same time. These employees may be working two part-time jobs in two different organizations, for example.

The PDP needs to build consistent logic to deal with these employees. Can we ask the employee on first log-in to identify their "primary" job and use that as the basis for their profile? Would it be possible to create separate profiles for each active record and give the employee the ability to toggle between them? 

Testing: https://bcgov.sharepoint.com/:w:/r/teams/02915/_layouts/15/Doc.aspx?action=edit&sourcedoc=%7B0a728c8e-a0a5-4edf-b65e-174eb8dfd694%7D&wdOrigin=TEAMS-ELECTRON.teamsSdk.openFilePreview&wdExp=TEAMS-CONTROL&web=1

**Comment by telusdcinco** [comment]
@Travis-A-Clark I forgot to ask about the tooltip content.  Can you provide the content?

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaWsrIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--399942f29bb922f16dbf2a68f5c813b8a0faf857/image.png)

**Comment by Travis-A-Clark** [comment]
Text for tooltip:

This option only appears for employees that have more than one active position with BC Public Service. Please select the position that you would like to link to your PDP profile.

**Comment by telusdcinco** [comment]
Restored multiple job listing to allow searching of employees having more than 2 jobs.

**Comment by steffipravasi** [comment]
181150	Lenarduzzi,Sophia	Sophia.Lenarduzzi@gov.bc.ca
178226	Diaz,Maria Delia	Maria.DeliaDiaz@gov.bc.ca
177102	Nadan,Devisha	Devisha.Nadan@gov.bc.ca
173226	Karas,Ellie	Ellie.Karas@gov.bc.ca
159617	Dureault,Bronte	Bronte.Dureault@gov.bc.ca
71231	Dashwood,Barbara Anne	bdashwood@islandstrust.bc.ca

**Comment by steffipravasi** [comment]
Issues found till now: https://bcgov.sharepoint.com/:w:/r/teams/02915/_layouts/15/doc2.aspx?action=editNew&sourcedoc=%7B514ec2d3-61cb-43d4-943d-5c6bd1e1d87b%7D&wdOrigin=TEAMS-ELECTRON.teamsSdk.openFilePreview&wdExp=TEAMS-CONTROL&wdhostclicktime=1694458486876&web=1

**Comment by telusdcinco** [comment]
New rule in #857 will show manager info based on sequence. 
(1)	if manager override is defined ⁠  
(2)	if valid preferred manager is selected 
(3)	if manager info available from ODS 
a.	supervisor details from employee demo
b.	employee demo details based on supervisor position number, if available (the supervisor position number is usually blank when supervisor employee id is blank, so the supervisor position number usually ends blank as well)
c.	employee demo details based on the position number roll up (next level up)
d.	employee demo details based on the position number roll up from 3c(2 levels up) if no employee matches the next level position in 3c.

**Comment by Travis-A-Clark** [comment]
**Updates to supervisor override**

Currently, the supervisor override only seems to be visible in the Sys Admin > Employee List area. It is not having the desired effect anywhere else. Example below, Karen Zilke's regular supervisor is Colin Briscoe. There is a supervisor override to Jane Erickson. This shows up in the Sys Admin > Employee List, but not anywhere else.

**Sys Admin view - reflects the supervisor override to Jane Erickson**
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemdpQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--60508edb1e2c31e4ed47329f05b3abbfb49beb28/image.png)

**Employee dashboard**
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenNpQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--80fa9613ce601a822b5b8b6aeabf44db3300a038/image.png)

**Jane Erickson's profile - no My Team tab, Karen Zilke not visible**
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejBpQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9d9c7fce0fd71f4adbbac97b0886a222fde66393/image.png)

**Colin Briscoe's profile - Karen Zilke still visible on My Team page**
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMEVpQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1f16d2513be1dbf0b5795a664f303c34ab64b943/image.png)

**Comment by Travis-A-Clark** [comment]
**Updates to job select / supervisor select**

Employee: 177102 Nadan,Devisha

Nadan defaulted to job "Social Prog Off" that reported to Terrence Cardle. I switched her job to "Child Care Counsellor" that reports to Konstantine Salkeld (see pic below).

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFVpQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dee891dc8f0dd12ac4cdd9a866e863df9927ace3/image.png)

Despite the change, when Nadan navigates to the My Conversation page to start a conversation with her supervisor, she still sees her old supervisor (Terrence) instead of the one I just selected (Konstantine).

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFlpQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1dc4ac7f5a2f6d948c36bb56ec81b9ad8f0b2b91/image.png)

Nadan also does not appear on Konstantine's My Team page:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGdpQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1f213801165a2b168dc7982affc02b302a27427f/image.png)

Nadan still appears on her old supervisor's My Team page. The change to the supervisor is not having any impact.

**Comment by telusdcinco** [comment]
Fixes  completed:
1) Dashboard - My Current Supervisor - Updated to reflect appropriate supervisor based on Supervisor Override (priority), Preferred Supervisor (for double bunked cases), or ODS/Position manager details.
2) My Team not showing for selected Supervisor Override.  The selected employees are not actual supervisors and was not granted supervisor permissions.  Supervisor Override is updated to list out only managers for Step 2 selection.
3) My Team Direct Report listing updated to reflect based on dashboard selection.
4) My Conversation - Participant selection on template was fixed to list the supervisor/employee correctly.
5) Conversation template modal editor not displaying when selecting updated participants.  New function created for determining supervisor/employee relationship between participants in Conversations.
6) My Goals notifications updated to follow new rules for determining supervisor in notifications.  This change can only be verified in Dev/Test.
Supervisor Override - Step 2 changes - updated the Step 2 employee list to only reflect users with supervisor role.  This is to prevent issue assigning non-supervisors to manage employees.  Will there be cases where the a Supervisor Override will be needed to be designated to a non-supervisor user???

**Comment by Travis-A-Clark** [comment]
Employee: 177102 Nadan,Devisha

Nadan defaulted to job "Social Prog Off" that reported to Terrence Cardle. I switched her job to "Child Care Counsellor" that reports to Konstantine Salkeld.

Konstantine logs in and can see Nadan on the My Team tab and can also select Nadan from the conversation participant drop down list. However, when he clicks "Start Conversation" he is taken to the Open Conversations page where nothing happens. The conversation is not created or launched. Noticed in the bottom left corner beneath the navigation bar there was random text displayed: "// when redirect from dashboardController, and then open the modal box". Thinking we missed some formatting in the code somewhere that removed the modal box pop up?

Also noticed that URL on this page was: https://performance-332842-test.apps.silver.devops.gov.bc.ca/conversation/upcoming?id=541&ownerrole=emp. I think the issue might be that it says "ownerrole=emp" at the end when Konstantine should be the supervisor of Nadan in this case.

**Comment by telusdcinco** [comment]
@Travis-A-Clark 
I fixed the same issue (5) yesterday.  If the supervisor change is recent, the relationship may not be picked up by the code right away, as the details are processed overnight.  I can run the static data process as needed for testing.

**Comment by Travis-A-Clark** [comment]
@telusdcinco Hmm. It's going to be confusing for users if people show up as their supervisor or on their My Team page right away but the functionality won't work until the following day. For now, can you please run the process in Test so I can verify Nadan's user case?

A few other notes:
- Even though no conversation was created, Nadan received an email notification that Konstantine set up a conversation with her. Nada did not receive an in-app dashboard notification.
- The team goal bank functions seem to work right away after the supervisor switch. Konstantine sees Nadan in his Goal Bank > Team Goal area and when he creates a goal it is effecitvely assigned to Nadan. Any chance the conversation code can be updated to include whatever magic is in the goal bank code?

**Comment by Travis-A-Clark** [comment]
@telusdcinco I'm still a bit confused about some of this because I thought we solved much of it with ticket #858 back near the beginning of the year. We made a big deal out of allowing employees to be able to select their supervisor from a double-bunked position. The testing on that ticket (videos, etc) show that the process was immediate and that conversations could be set up right after selecting a different supervisor.

Has the logic changed since? We have received complaints about this not working in PROD anymore as I mentioned to you earlier this week. It feels like we've gone backwards on this one.

**Comment by Travis-A-Clark** [comment]
Employees that report to double-bunked positions are not seeing the supervisor drop down menu to select preferred supervisor as they did in the past.

Kathryn Gregory reports to position 00124679.

There are two people in that position.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekUxQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--619c492b98e398ea0198f93b484dd233ec7efad5/image.png)

Kathryn does not have the drop down supervisor selection menu available on her homepage.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekkxQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--47b5e18b6df566590d7834dee1fc7a1cedaa4aa5/image.png)

**Comment by telusdcinco** [comment]
Kathryn' supervisor is provided by ODS employee demo (Stobart is the designated supervisor).  The system does not consider the scenario as double bunked.  
The manager details utilized follows the sequence of availability...   (1) Override, (2) Preferred, (3) ODS employee demo, (4) employee demo next supervisor, (5) Position data, (6) next level Position data.  The system will use the lowest number sequence of supervisor details available.  
If ODS supervisor details was empty, Kathryn's case would be a double-bunked case because position data have 2 managers for the supervisor position number.

Below is an example of a double bunk in the system, showing the drop down working.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2cyQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b37d75db8ec09ba26e662c99f77d4f509057bf74/image.png)

**Comment by telusdcinco** [comment]
A double-bunked case may look like below in the Employee Listing for having 2 different managers for the supervisor position number.

[Uploading... image.png]

**Comment by Travis-A-Clark** [comment]
@telusdcinco Who decides that ODS supervisor selection from a double bunked position though? The intent was to allow the end user to select the correct supervisor when their the supervisor position is double bunked. Ticket 858 established this process.

For example, in PROD, user Paula Georgescu reports to a position # that is double bunked. The two potential supervisors in the position are Melissa Holman and Mikayla Wierenka. Paula has selected Melissa Holman from the drop down list as being the correct supervisor. When I look in TEST, Paula does not have a choice. She is automatically assigned to Mikayla Wierenga and there is no drop down. This defeats the purpose.

**Comment by telusdcinco** [comment]
As discussed, we are applying the sequence below for using supervisor details from multiple sources.

1.  Supervisor Override
2.  Preferred Supervisor selected from My Current Supervisor on the Dashboard
3.  Positions Data
4.  Next Level Positions Data
5.  Employee Demo
6.  Next Level manager from Employee Demo

**Comment by Travis-A-Clark** [comment]
@steffipravasi I am not going to be able to finish testing this before leaving today. Please pick this ticket up as a priority when you can.

@telusdcinco Two things I noticed in my brief testing of latest push in Test.

Logged in as Konstantine Salkeld

1. Even after selecting a preferred supervisor (Ridding), both supervisors still appear for me in the conversation participants area.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOE0yQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--84c89fb1ac4bef466bab1d38282540e1912d2722/image.png)

2. The other supervisor (McSweeney) that I did not select still sees the employee (Konstantine Salkeld) on their MyTeam page and has all the same access.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFkyQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a2e1dbaff8076dc98c33923259cf1a0d390470a6/image.png)

3. As mentioned on our call, an employee that has a single position that reports to a double-bunked position (like Konstantine Salkeld above) should only have one row in the employee list and related reports. They have a single job and a selection of supervisors to choose from. Only one row needed as currently in PROD. Two rows are needed only when the employee has TWO active jobs. A record 0 and a record 1 for example that are both active. Those two jobs could be in completely different orgs, and therefore there needs to be two rows.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGcyQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fc6cca40a99a745731fc51faff2371dd5aa59d65/image.png)

**Comment by Travis-A-Clark** [comment]
To clarify that last point....

This person SHOULD have two rows because they have two different records (0 and 1) with two different position numbers (they have two jobs).

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUEyQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--450cbdf6855d34b7c9d3696c87fc9772e57023e4/image.png)



This person should NOT have two rows. They have one record (record 0) and one position number. They report to a double-bunked position, but we don't want to count the employee twice (they only have one job).

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUUyQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fa4a3a41f2da58c12e16b2ca6285c0c09481d929/image.png)

**Comment by steffipravasi** [comment]
@telusdcinco I have added a couple of issues in the document here. https://bcgov.sharepoint.com/:w:/r/teams/02915/_layouts/15/doc2.aspx?action=editNew&sourcedoc=%7B514ec2d3-61cb-43d4-943d-5c6bd1e1d87b%7D&wdOrigin=TEAMS-ELECTRON.teamsSdk.openFilePreview&wdExp=TEAMS-CONTROL&wdhostclicktime=1694458486876&web=1
We can go through them together if needed :)

**Comment by steffipravasi** [comment]
Issue: When selecting a job from the primary job list, the changes does not reflect on the profile.

**Comment by steffipravasi** [comment]
@telusdcinco Assigning ticket back to you for fixing the 4 issues reported in this doc:
https://bcgov.sharepoint.com/:w:/r/teams/02915/_layouts/15/doc2.aspx?action=editNew&sourcedoc=%7B514ec2d3-61cb-43d4-943d-5c6bd1e1d87b%7D&wdOrigin=TEAMS-ELECTRON.teamsSdk.openFilePreview&wdExp=TEAMS-CONTROL&wdhostclicktime=1694458486876&web=1

**Comment by telusdcinco** [comment]
Added comment in the #857 document for items 1 to 4.  The result should be expected as the employee have 2 separate jobs.  The additional user issue in Item 3 was fixed and is ready in Test.

**Comment by steffipravasi** [comment]
As discussed with Travis, we nee to fix the rest of the issues too. Putting back to in progress.

**Comment by telusdcinco** [comment]
Fixed multi-job employees showing in the respective manager My Teams listings.  Ready for re-test in Test.

**Comment by steffipravasi** [comment]
Test validated. 
Note: We might to discuss with Travis regarding the 3-4 seconds of pause when reflecting details on switched profile.

**Comment by Travis-A-Clark** [comment]
@telusdcinco @steffipravasi I think this looks good! We may have finally killed the ticket that won't die!! :-)

Two edits to text pop ups below to clarify things on the homepage and we are good to go. Dennis, just let me know when they are in place and I will mark PO Approved and we can get this ticket moving. Thanks!

Let's change the "i" icon for My Current Supervisor on the homepage to say: 

"If you have a dropdown menu below it means that there are multiple people sharing your supervisor's position #. Please select the correct supervisor from the list. This may take up to 5 seconds to process.

If your current supervisor is not visible below, please have your actual supervisor submit a service request through AskMyHR and choose the category: My Team or Organization > HR Software Systems Support > Position / Reporting Updates."

Let's change the the "i" icon for My Primary Job on the homepage to say: 

"This option only appears for employees that have more than one active position with the BC Public Service. Please select a position to connect with the appropriate supervisor. 

This may take up to 5 seconds to process."

**Comment by telusdcinco** [comment]
@Travis-A-Clark @steffipravasi Dashboard (i) tooltips updated.  Pending build in Test.

**Comment by steffipravasi** [comment]
@telusdcinco I am guessing that the # after the position in My current supervisor is added my mistake. @Travis-A-Clark can you please confirm?
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOG5BQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b529705f0904bed78349fda1da0bf74902772892/Screenshot%202023-11-09%20at%205.22.39%20PM.png)
