### ISSUE TITLE
PDP must deal with "double bunked" supervisors

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#858]
There are approximately 1,000 supervisors that do not have unique position numbers. For example, Supervisor A with employee ID 123 and Supervisor B with employee ID 456 may actually both share position # 9999.

The PDP users position # to identify the correct supervisor for each employee and grant the appropriate access to their profiles for access and sign-off.

Currently, there is no way for the PDP to separate and identify which supervisor associated to a position number is the "correct" supervisor for that employee. For example, employee F reports to position # 9999. The system looks up that position #, sees that there are two supervisors associated with it, and has no idea which of the two is accurate. 

The PDP needs to build logic to deal with these situations in a consistent way. 

Can we move from using only position # to using a combination of position and employee # to better identify individuals? Would it be possible to list all supervisors associated with a position number and have the employee select the correct one when they log in?

Replace the "My Current Supervisor is" at the top of the home page with a drop down that lists all supervisors in the position #.

**Comment by telusdcinco** [comment]
@jizhaogit Please review code changes.

**Comment by jizhaogit** [comment]
@telusdcinco looks good to me. please go ahead about the test migrate. thanks.

**Comment by SSubashree26** [comment]
Completed validating this story in the testing environment and it is working fine. Moving to "PO Review"

https://bcgov.sharepoint.com/:f:/r/teams/02915/Shared%20Documents/Product%20Team/Testing/Testing%20screenshots/Performance%20%23858?csf=1&web=1&e=Nb7F4C
