### ISSUE TITLE
Auto Save for Comments/Goal occurs before 15 mins on inactivity

### ISSUE THREAD

**Issue by steffipravasi** [bcgov/performance#865]
Environment: Test

We have the auto save feature for conversations and goals now. 
Expected: Auto save feature must occur after 15 mins of inactivity by the user.

Actual: For conversations, the auto save happens within few mins of opening the conversations.
Please check the recordings below: 1) https://bcgov.sharepoint.com/:v:/r/teams/02915/Shared%20Documents/General/Test%20cases/Screen%20Recording%202022-11-29%20at%202.22.31%20AM.mov?csf=1&web=1&e=ArPvdb
2) https://bcgov.sharepoint.com/:v:/r/teams/02915/Shared%20Documents/General/Test%20cases/Screen%20Recording%202022-11-29%20at%202.27.53%20AM.mov?csf=1&web=1&e=26PSDo
3) https://bcgov.sharepoint.com/:v:/r/teams/02915/Shared%20Documents/General/Test%20cases/Screen%20Recording%202022-11-29%20at%202.35.35%20AM.mov?csf=1&web=1&e=EktKQN

**Comment by jizhaogit** [comment]
After console log testing i believe it is because the 15 minutes time count is triggered when the page opened but not the modal loaded.   will update the trigger logic to track the right modal behavior.

**Comment by steffipravasi** [comment]
Test status: Pass
The auto save function looks fixed now. The save happens only after 15 mins of inactivity for conversation and goals.
The saving message popping up every few mins has been fixed and does not appear now.

**Comment by jizhaogit** [comment]
Changed the auto-save function from one-time trigged to time rolling trigged.  
For testing purposes, the rolling time is set to 1 minute.

@telusdcinco code is ready for you to review. thanks.

**Comment by telusdcinco** [comment]
@jizhaogit Code changes looks ok.

**Comment by SSubashree26** [comment]
The autosave message is not displayed for the second time, when an error was already displayed and corrected. Will validate it along with story #[780](url)

**Comment by SSubashree26** [comment]
Completed validating this ticket in the test environment. Moving it to PO Review

Screen Recording:
https://bcgov.sharepoint.com/:v:/r/teams/02915/Shared%20Documents/General/Testing/Testing%20screenshots/Performance%20%23865/Performance%20%23865.mov?csf=1&web=1&e=jDpvRI
