### ISSUE TITLE
Delegated (shared) supervisor can add comments as employee

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#867]
Zehra LeRoy reports to Travis Clark. Zehra is shared with Eleanor Mulloy.

Eleanor sees Zehra in her My Team list. Eleanor clicks on Zehra's name to view Zehra's profile, goes to the Open Conversations area, and clicks on a conversation between Zehra and Travis. Eleanor is able to add comments on Zehra's side of the template, making it look like Zehra has filled in the information. Eleanor should have view only access for any conversation in which she is not a participant.
<br>

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/0828f9d7-cb90-4be1-afdd-bceb66ac6e28)
<br>

The audit log shows it as Zehra making the comments, even though it was Eleanor.
<br>

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/c631949f-e997-4eab-9a10-6369bd9c31cd)

**Comment by Travis-A-Clark** [comment]
@steffipravasi can you confirm this is happening more widely? It was not an issue in Production, so looks to be something introduced more recently. 

Once confirmed with other examples, please assign to Ji. Thanks!

**Comment by SSubashree26** [comment]
I am able to see two sign off sections for shared employees 

- Login in as Supervisor of a shared employee
- Navigate to My Teams > select the shared employee > My conversations (of the shared employee) > Open Conversations
- View one of the shared employee's conversation
- When we scroll down, we are able to see two sign off sections one with the title "Employee Sign-off  and Supervisor Sign-off" and the other with the title "Employee Unsign-Off and Supervisor Unsign-off"

I am not able to see these two sections for all the conversations. Only some of them have it.
The supervisor ID I used is : Chad Hoskins
The employee that I chose is Rebecca Fontaine
The conversation that I chose was Performance Check in with Julie Muir and Rebecca Fontaine 

https://bcgov.sharepoint.com/:v:/r/teams/02915/Shared%20Documents/General/Testing/Testing%20screenshots/Performance%23%20867/Two%20sign%20off%20sections%20for%20shared%20employees.mov?csf=1&web=1&e=FUO959

**Comment by jizhaogit** [comment]
this bug is caused by some role is not save as expected. get fixed.

**Comment by SSubashree26** [comment]
Completed validating the main functionality of this ticket. The shared supervisor is no longer able to edit the conversation that they are not part of.

**Screen Recordings:**
https://bcgov.sharepoint.com/:u:/r/teams/02915/Shared%20Documents/General/Testing/Testing%20screenshots/Performance%23%20867/Performance%20867.zip?csf=1&web=1&e=fhhFkW

**Note to Travis:**
Though the shared supervisor is no longer able to add comments to conversations that they are not part of, they are still able to edit the answers for the yes or no questions in both the employee and supervisor sign off section. Ji confirmed that the supervisor still cannot sign off without providing a matching employee ID and therefore we agreed that it has less impact and thought of bringing it to your attention.

Leaving this story in the testing column until JI fixes the above observation of two sign off sections

**Comment by SSubashree26** [comment]
The observation for two sign off sections being displayed is fixed and retested. Two sign off sections are no longer displayed for shared employees

Screen Recording:
https://bcgov.sharepoint.com/:v:/r/teams/02915/Shared%20Documents/General/Testing/Testing%20screenshots/Performance%23%20867/867%20-%20two%20sign%20off%20sections%20-%20working%20fine.mov?csf=1&web=1&e=8eeCN7
