### ISSUE TITLE
Avoid duplicates on the My Team listing

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#868]
On the My Team tab, if an employee shows up on the "My Direct Reports" list, they should not show up in the "Shared with me" list even if they have been shared.

**Comment by jizhaogit** [comment]
@telusdcinco please help do the code review. thanks!

**Comment by SSubashree26** [comment]
Completed validating this ticket in the testing environment and it is working fine. Moving this story for "PO Review"

Screen Recordings:
https://bcgov.sharepoint.com/:u:/r/teams/02915/Shared%20Documents/General/Testing/Testing%20screenshots/Performance%20%23868/Performance%20%23868.zip?csf=1&web=1&e=OUiF2j
