### ISSUE TITLE
My Conversations: save roles for supervisor and employee when conversation is created

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#869]
As discussed on the call, we want to add a row to the participant table that will store the role of each participant in the conversation when it is created. This role should stay consistent. This should help solve issues with supervisors and delegated (shared) supervisors that change over time to ensure that the conversations don't disappear or break.

We will also need to create a script to store this value for conversations that have already been created in the system.

**Comment by SSubashree26** [comment]
Julie Muir is shared with 2 supervisors and when I try to create a career development conversation with Deborah Schwartz, I am not seeing the participants in the conversation created.

![image.png](https://images.zenhubusercontent.com/63892df90d58261296a2b5c0/c4be9d3d-2a3c-4471-8fd4-cdbf2f466b8f)

![image.png](https://images.zenhubusercontent.com/63892df90d58261296a2b5c0/3059b120-c91d-4502-827e-29d2084a5836)

**Comment by jizhaogit** [comment]
get fixed. multi shared items blogged the role saving query

**Comment by SSubashree26** [comment]
The above observation has been fixed and retested.

Validate this ticket with @jizhaogit by performing the following
- Created a conversation for a shared employee and 
- validated if the DB was capturing the correct participants involved in the conversation

Testing details:
Employee: Julie Muir
Supervisor: Shannon Baskerville
Employee shared with: Deborah Schwartz and Monica Lust
Created a conversation for Julie and Deborah and validated if the participant IDs matched Julie and Deborah. It was captured correctly.

Screen Recording:
https://bcgov.sharepoint.com/:v:/r/teams/02915/Shared%20Documents/General/Testing/Testing%20screenshots/Performance%23%20869/869.mov?csf=1&web=1&e=1oVV6w
