### ISSUE TITLE
Clicking goal card when viewing employee profile launches edit screen instead of view screen

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#870]
**Environment**: TEST

**Scenario:** Supervisor goes to My Team page and clicks on an employee to view the employee profile. In the employee profile, they click on the title of a goal card on the My Current Goals page. This launches the edit goal page with the URL ending "goal/#/edit".

**Expected result:** clicking on the title of the goal card goes to the same place as clicking the view button on the goal card and launches the view page with URL end "goal/#".

This is not an issue in PROD. It has just recently appeared in TEST.

I also noticed that goal cards themselves are now larger. There is more empty space around the goal title in TEST than there is PROD. Can this be changed back?

**Comment by Travis-A-Clark** [comment]
@jizhaogit Somehow this error has now made it into Production, even though I don't believe we pushed anything related to the My Current Goals or the My Team pages. After the missing conversations comments (#829) is ready to go, this should be the next priority so that we can get the fix into Prod as soon as possible. Thanks.

**Comment by jizhaogit** [comment]
based on the request, now when the supervisor click the goal title/card top border page will be redirected to view goal page.

**Comment by steffipravasi** [comment]
Test status: Pass
The goal card viewed by switching to team members profile opens up the page with URL https://performance-332842-test.apps.silver.devops.gov.bc.ca/goal/#
Supervisor not able to edit the goal by clicking on the card/title or the View button.

**Comment by Travis-A-Clark** [comment]
@steffipravasi the link to view looks good!

The goals card are now larger in both TEST and PROD. There's more white space around the goal title. Unfortunately, I can't send you a screenshot of what it looked like before because all three environments are now enlarged!

**Comment by jizhaogit** [comment]
The is no changes for the layout of the goal card.  maybe something related in the css file changes the card's white space. may need some time to check the detail about this issue.

**Comment by Travis-A-Clark** [comment]
@jizhaogit Yeah, no worries. We will move ahead without the change and sort it out later. Not critical. Thanks!
