### ISSUE TITLE
When an employee reports to a vacant position, the PDP should change the reporting relationship to the next level up the hierarchy

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#872]
**Current scenario**: if an employee reports to a vacant position (i.e. they report to a valid position number with no one in it), their employee record looks like the screenshot below.

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/110dcc53-d8f0-425f-97e0-f92ea66950cd)

And their homepage says their current supervisor is "No supervisor".

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/f05876e0-9b74-422b-9896-156bbc398a3f)
<br>

**Desired outcome**: if the reports to position is vacant, the PDP will search one level higher in the org hierarchy and assign that position as the "reports to position" for the employee instead.

In the example above, that means that instead of reporting to position # 00081753, Jennifer Todd would report to the position that supervises position # 00081753.

This should only happen once. If the higher position in the org hierarchy is also vacant, then the PDP should return a null value and display information as it does currently (i.e. "Current supervisor is: No supervisor".

**Comment by telusdcinco** [comment]
@Travis-A-Clark Will this be a cosmetic fix to display the next level manager on the page?  Or, the next level manager will have the functionality to perform what the supposed manager should be doing, which will require that we assign the next level manager as the current manager right from the profile creation, or an overnight process to repopulate next level manager details to the user profile for those with blank managers?
Maybe we can have a meeting on this.

**Comment by telusdcinco** [comment]
Deployed to Dev for testing.

**Comment by telusdcinco** [comment]
Deployed to Test for verification.

**Comment by telusdcinco** [comment]
@Travis-A-Clark 
The process to update the next level manager for employees with vacant managers, will execute daily at 12:45am.  I have not run the process manually in Test, so manager changes will not be visible until tomorrow morning.

**Comment by telusdcinco** [comment]
Ticket #892 created for the creation of the audit table to be used by scheduled jobs for tracking field changes/updates.

**Comment by telusdcinco** [comment]
ODS endpoint created for providing position data information.

**Comment by telusdcinco** [comment]
@jp-Telus @jizhaogit Requires .env changes below:

ODS_POSITIONS_URI=https://analytics-testapi.psa.gov.bc.ca/apiserver/api.rsc/Datamart_eperform_peoplesoft_position_data/

# On/Off Switches
PRCS_PULL_ODS_POSITIONS=on



@jizhaogit Please review code changes for #872.

**Comment by jizhaogit** [comment]
looks good to me.  please go ahead with the test migration. thanks!

**Comment by telusdcinco** [comment]
@Travis-A-Clark Position data endpoint deployed in ODS Prod.
