### ISSUE TITLE
Sys Admin > Goal Bank > Manage Existing: individual audience shows up twice in all lists

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#873]
Goal assigned to 639 individuals:

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/8fa97426-36b8-499b-99a2-34d2d63b268e)

Clicking on the link displays doubles of each employee:

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/70f86ec4-6e81-4852-8220-01c88cb2cd11)

**Comment by telusdcinco** [comment]
@Travis-A-Clark 
It seems that HR filter code was applied/added to the SysAdmin version of the Goal Bank page; as part of #722 changes.

**Comment by telusdcinco** [comment]
Issue can be replicated by assigning multiple HR admin to the same Dept ID as the employee on the list.

![image.png](https://images.zenhubusercontent.com/60e88ef619e4760c8b3ee8bb/bb0fe574-177b-4577-8554-75da99e8b817)

**Comment by telusdcinco** [comment]
Reverted the changes from Test to troubleshoot Prod issue with adding orgs to existing goals.
