### ISSUE TITLE
My Conversations > Completed Conversations: receiving incorrect pop-up message; unable to close window

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#874]
@jp-Telus I am including you on this because I wonder if it is related to the work you are doing on the unlock conversations function. If not, Ji can lead. Thanks!

---
**Scenario**

User navigates to Completed Conversations. Clicks to view any of the conversations. Modal launches and content is displayed. User clicks to "X" out of the modal and receives a warning message:

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/abc94088-8fee-4e01-80db-9228d592d715)

The only option is to click OK. That takes them back to the modal. User cannot close modal or navigate away. Has to click back button in browser to get out.

This warning message should not be displayed as it is not related to simply viewing or X-ing out of a completed conversation.

**Comment by SSubashree26** [comment]
Completed validating this story in the testing environment and the incorrect popup is no longer displayed. 

Screen Recordings
https://bcgov.sharepoint.com/:u:/r/teams/02915/Shared%20Documents/General/Testing/Testing%20screenshots/Performance%23%20874/Performance%23%20874.zip?csf=1&web=1&e=E7uYJh
