### ISSUE TITLE
HR/Sys Admin > Goal Bank > Manage Goals: Business Unit org tree is failing

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#875]
As an HR or Sys Admin, I can't add additional business units to an existing goal. Selecting an org level fails to properly register in the drop down. The tree view "flickers" and the selection is not properly processed.

**Comment by telusdcinco** [comment]
@Travis-A-Clark 

The fix to take care of the Org Tree flicker was pushed to prod Friday.  A data fix to delete the invalid Goal Bank Org was also pushed and executed to cleanup the invalid entries created while the flicker issue existed.

Please try adding the missing Orgs in Prod.

**Comment by Travis-A-Clark** [comment]
@telusdcinco Unfortunately, I am getting an ajax error when I try to edit the business unit audience for an existing goal in the HR Admin Goal Bank. Nothing loads.

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/14019a36-4379-44f6-bd51-af07452c6635)

**Comment by Travis-A-Clark** [comment]
@telusdcinco When I try through Sys Admin, I can edit the business unit audience but it still assigns it to different business units than the ones I selected. See below for all example of orgs other than Social Development and Poverty Reduction. Total of 205 business units across gov even though I selected less than 150 all in SDPR.

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/98fb420d-7c6c-43c4-889b-50d2311a7e41)

**Comment by telusdcinco** [comment]
The Ajax error is resolved in HR Admin.
![image.png](https://images.zenhubusercontent.com/60e88ef619e4760c8b3ee8bb/3fe104ca-c4a8-49bc-9dd7-c0c4800d4015)
The org count may need to be fixed for HR Admin.

SysAdmin org selection needs more investigation.

**Comment by Travis-A-Clark** [comment]
@telusdcinco I can confirm that the problems still exist in Production.

Evelyn Carty is an HR Admin for SDPR. She is responsible for the Service Delivery Division. Her HR Admin access has 152 business units associated with it. When she edits a goal in the goal bank and assigns access to her full division, only 128 business units are reflected. No additions are shown.

The org tree also continues to "flicker" and collapse when adding new business units.

**Comment by telusdcinco** [comment]
@Travis-A-Clark I have a 1 line code fix for saving HR Goal Bank Org list changes.  Please let me know if it can be pushed to prod.

**Comment by Travis-A-Clark** [comment]
@telusdcinco I like how simple and easy that sounds! :-) Please go ahead and push to prod and restart the pods before you sign off for the day. Thanks!

**Comment by telusdcinco** [comment]
@Travis-A-Clark Prod App pods have been restarted.

**Comment by telusdcinco** [comment]
@Travis-A-Clark The fix for duplicate org row issue is ready for deployment to Prod.  Please let me know if okay to migrate to prod, and when to restart the pods.
Please try to remove the duplicate rows manually.

**Comment by Travis-A-Clark** [comment]
@telusdcinco As discussed, the fix in Prod has solved the issue with pushing goals to new business units. Users in those new units can now see the appropriate goals. However, from an HR Admin view, we are seeing duplicate rows for business units when pushing out to the organization as per screen shot below. This didn't used to be the case.

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/e53e075c-a485-4789-9843-07ffc2550e53)

**Comment by telusdcinco** [comment]
@Travis-A-Clark Fix for duplicate org row issue deployed to prod.  Pods restarted.  Ready for your validation.
