### ISSUE TITLE
Save button gets enabled incorrectly

### ISSUE THREAD

**Issue by SSubashree26** [bcgov/performance#877]
When the supervisor opens an unlocked conversation, even before unsigning it, they are able to see the “Save” button enabled when the click on the text boxes in the conversation of the employee. And clicking on those save buttons is showing the message “Comments saved” even if the user is not able to type anything in the conversation 

**Steps to recreate:**
- Login as a Sysadmin and unlock a completed conversation 
- Login as the supervisor and sign the conversation
- While the employee has still not signed the conversation, click on the employee's comments section and type (logged in as a supervisor)
- The comments do not appear in the text box, however the save button gets enabled 
- Clicking on the save button shows the message "Comments Saved"

**Screen recording:**
https://bcgov.sharepoint.com/:v:/r/teams/02915/Shared%20Documents/General/Testing/Testing%20screenshots/Performance%23377/Save%20button%20enabling%20even%20after%20signing.mov?csf=1&web=1&e=VWAiph

**Comment by jizhaogit** [comment]
get fixed.  this bug can be trigged by key press event.

**Comment by SSubashree26** [comment]
Completed validating this ticket in the test environment and it is working fine. In the recordings the save button appeared the first time a conversation was open in Safari and FF. However, after clearing the cache, the Save button did not appear if the text box is not editable.

Screen Recordings:
https://bcgov.sharepoint.com/:u:/r/teams/02915/Shared%20Documents/General/Testing/Testing%20screenshots/Performance%23%20877/Performance%20877.zip?csf=1&web=1&e=6VRHOv
