### ISSUE TITLE
Supervisor can only enter comments and sign-off on employee side of conversation

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#880]
Environment: Prod
Supervisor: Chantal Pylatuk

Chantal has multiple conversations with employees set up in her profile. Previously, she was able to enter comments on the supervisor side of the conversation. Since the updates yesterday, she has lost access to the supervisor side of the conversation and instead can only enter comments on the employee side. She can also sign off on the employee side. Her access has reversed.

The conversations still show up under her "Conversations with My Team" list, so they are displayed properly. 

This is also happening for supervisor Philip O'Shea. I am assuming it is happening for many other as well.

Seems like an issue with the script that was run?

**Comment by jizhaogit** [comment]
+-------+-----------------+----------------------------------+
| id    | name            | guid                             |
+-------+-----------------+----------------------------------+
| 25195 | Chantal Pylatuk | A47BCC5E725640B9A7E2710DA6695909 |



+-----------------+----------------+------+
| conversation_id | participant_id | role |
+-----------------+----------------+------+
|            1588 |          25195 | emp  |
|            1589 |          25195 | emp  |
|            1792 |          25195 | emp  |
|            1794 |          25195 | emp  |
|            1795 |          25195 | emp  |
|            1796 |          25195 | emp  |
|            2214 |          25195 | emp  |
|            2621 |          25195 | emp  |
|            2635 |          25195 | emp  |
|            2661 |          25195 | emp  |
|            2677 |          25195 | emp  |
|            2723 |          25195 | emp  |
|            2724 |          25195 | emp  |
+-----------------+----------------+------+
13 rows in set (0.00 sec)

script error causes the supervisor's role be marked as 'emp'

need an update to correct the role flag.

**Comment by Travis-A-Clark** [comment]
@jizhaogit Will the same script correct for all supervisors that are having this issue, or do we need to know the participant_id for each supervisor before we can fix it for them?
