### ISSUE TITLE
Open conversation cannot be signed by either participant

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#882]
Environment: Prod
Supervisor: Jennifer Erickson
Employee: Travis Clark

Jennifer and Travis have an open conversation. It is displayed in the list of open conversations. However, the area for either person to sign-off has disappeared.

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/720c5b80-2b62-4f25-8e72-e954b67c4ebd)

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/309fd531-0a02-4185-a99a-1a05fba4bb1f)

**Comment by jizhaogit** [comment]
Can you provide the details of the conversation? for example, the conversation id?

**Comment by Travis-A-Clark** [comment]
I believe the conversation ID is 12.

It's a Performance Check-In conversation between Jennifer Erickson and Travis Clark.

**Comment by jizhaogit** [comment]
bug addressed:  the conversation has supervisor sign off time at 2022-08-30 20:22:32 and no user sign off time.  js script only checked the time with locked time but didn't check the conversation status with current open or closed.

**Comment by SSubashree26** [comment]
Completed validating this ticket in the testing environment and it is working fine. Moving it to "PO Review" column.

Screen recording:
https://bcgov.sharepoint.com/:v:/r/teams/02915/Shared%20Documents/General/Testing/Testing%20screenshots/Performance%23%20882/Performance%23%20882.mov?csf=1&web=1&e=DKlG1u
