### ISSUE TITLE
Conversations not showing up for employees

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#886]
After running the updates in PROD on Jan 7, some conversations are showing up for supervisors, but not employees.

Examples include:

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/911769cb-56a5-4035-8daa-b4c5b2756ff4)

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/fa9b178a-f71c-46f2-ae63-60cbb06f68d1)

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/f9ee2101-0306-42c5-8e18-e26f75165421)

Can you please investigate? Thanks!

**Comment by jizhaogit** [comment]
the root reason is addressed. it happens when completed conversations lost the supervisor/employee relationship. the complete query has bug that still search the uncompleted conversations.  That caused the lost relationship will not be included in the result.
