### ISSUE TITLE
Enhancements for Employee List

### ISSUE THREAD

**Issue by SSubashree26** [bcgov/performance#887]
The following observations were noticed while validating the story #866

**Observation 1:**
We are not displayed with the search results when we type the full name of a person. For example, typing "May Cathy" with a space in between displays no search results.

![image.png](https://images.zenhubusercontent.com/63892df90d58261296a2b5c0/a8764365-98c1-4b05-a632-44853ad5f475)

However, if we type the first name and the last name separated by a comma, we are able to see the search results
![image.png](https://images.zenhubusercontent.com/63892df90d58261296a2b5c0/ecf76200-4500-4339-8404-253a685bea0d)

**Observation 2:**
We are not able to download a particular result set on which a data is applied
For example: If we have 700 results for a filter, clicking on "Export All Rows" downloads the entire list of employees (39,308 entries), instead of downloading just the 700 results. I understand that the results in the .csv file can be filtered afterwards. However, if the user wants to download just these 700 entries, we don't have a provision for that.

**Observation 3:**
The value chosen in the "Show _ entries" field overrides the arrow symbol in it.

![image.png](https://images.zenhubusercontent.com/63892df90d58261296a2b5c0/9c22afe8-9967-4153-ae80-aee475bd4c5b)

**Observation 4:** (Nice to have feature)
After a search is performed, the progress bar is being displayed in the middle of the search results table.
If there is a huge result set, the system takes a little longer before the results appear(especially while sorting with the employee ID). The user might not know if the results are appearing or not and might be tempted to click on the filter button multiple times. It would be nice to have it displayed on the top. This sometimes causes the Ajax error mentioned in the defect #884.

**Comment by SSubashree26** [comment]
The following observations were noticed while validating the story #866

Observation 1:
We are not displayed with the search results when we type the full name of a person. For example, typing "May Cathy" with a space in between displays no search results.
Screenshot 2023-01-10 at 12.31.54 PM.png

However, if we type the first name and the last name separated by a comma, we are able to see the search resultsScreenshot 2023-01-10 at 12.33.00 PM.png

Observation 2:
We are not able to download a particular result set on which a data is applied
For example: If we have 700 results for a filter, clicking on "Export All Rows" downloads the entire list of employees (39,308 entries), instead of downloading just the 700 results. I understand that the results in the .csv file can be filtered afterwards. However, if the user wants to download just these 700 entries, we don't have a provision for that.

Observation 3:
The value chosen in the "Show _ entries" field overrides the arrow symbol in it.
Screenshot 2023-01-10 at 12.43.59 PM.png

Observation 4: (Nice to have feature)
After a search is performed, the progress bar is being displayed in the middle of the search results table.
If there is a huge result set, the system takes a little longer before the results appear(especially while sorting with the employee ID). The user might not know if the results are appearing or not and might be tempted to click on the filter button multiple times. It would be nice to have it displayed on the top. This sometimes causes the Ajax error mentioned in the defect #884.

**Comment by Travis-A-Clark** [comment]
@JonTelus Can you please add an estimate to this ticket when you have a chance? Thanks!

**Comment by JonTelus** [comment]
@SSubashree26 Hi, I see screenshots referenced in the issue description.  Where can I view these?
Thanks

**Comment by SSubashree26** [comment]
@JonTelus Hi Jon, my bad. I copy pasted my last comments from the story #886. The screenshots can be found in #866. I will have them pasted here again

**Comment by JonTelus** [comment]
@SSubashree26 Thanks!

In looking at the export all rows button, it does exactly that.  I agree it would be easier if the button just exported what was filtered.  ie, 700 rows.  If I make that change, then if the user actually wanted all 32000 rows, they'd have to return them all and use the button.  Is that okay?

**Comment by SSubashree26** [comment]
@JonTelus Sounds great!.  I was even wondering if we could retain the functionalities as it is, and have a new button named "Export filter result" to download the results of any filter applied.

@Travis-A-Clark can you please let us know what would be the most efficient implementation?

**Comment by Travis-A-Clark** [comment]
@SSubashree26 @JonTelus It would be great to be able to have the option to "Export All" or "Export Results". The one thing that isn't super useful is the  current "Export Displayed". Thanks!

**Comment by steffipravasi** [comment]
Sort features for the following columns is not working for Employee List (Sys admin) and My Org(Hr admin):
-Active Goals
-Next Conversation
-Shared
-Direct Reports

**Comment by telusdcinco** [comment]
@steffipravasi 
Pushed all changes to Test for validation, including the items added last Firday.

**Comment by steffipravasi** [comment]
1)Observation 1 has been fixed for Sys admin but not for HR admin
![Screenshot 2023-05-30 at 12.04.20 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/1d07ecb2-9da8-45bd-b92c-7d4cde4c438d)

**Comment by steffipravasi** [comment]
Travis creating a new ticket for My org page in Hr admin. 
Moving the ticket for PO review.

**Comment by steffipravasi** [comment]
Similar ticket created for HR - My Org #986
