### ISSUE TITLE
Remove Past Employees from the rest of the app

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#888]
The employees showing up on the Past Employees list are still being displayed on the My Team page for their supervisors and other areas of theapp. An employee in Past Employees should be removed from all reporting relationships and statistics/reporting in the app.

**Comment by telusdcinco** [comment]
@jizhaogit Please review #888 changes.

**Comment by jizhaogit** [comment]
@telusdcinco see we are using 'employee_demo.date_deleted' to identify available employee now.  all are good to me.  please go ahead to do the migrate. thank you!

**Comment by Travis-A-Clark** [comment]
Additional work to be carried out on ticket #906
