### ISSUE TITLE
Determine PIA requirements for Application

### ISSUE THREAD

**Issue by Abuchana** [bcgov/performance#89]
Jared is looking into requirements for us to create a separate PIA for our OpenShift use or whether we're completely covered under the Corporate one

**Comment by freshjwarren** [comment]
I don't think that this is a separate task from the PIA for the application.

**Comment by Abuchana** [comment]
I agree. I will straighten out all the PIA cards…


Alison Buchanan
Project Manager/Scrum Master
Business Performance Division | BC Public Service Agency
810 Blanshard St | Victoria BC | Tel 778.698.2133
