### ISSUE TITLE
Statistics and Reporting - update query to focus stats on employee role in conversations

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#890]
Update conversation reports based on new conversation participant roles. Ji added clear employee and manager roles to the conversation set up process and storage. All conversation statistics should be based on employee roles. We want to know when the due dates for the employee are, what the open topics for the employee are, and what the completed topics for the employee are. Currently it seems to be based on who set up the conversation. This shows up in the Excel exports where there will be multiple entries focused on a supervisor since they set up the conversation. 

In the screenshot below, you will see the report focuses on Ian Hennem (a supervisor) and highlights his next conversation due date over and over. Each row should actually focus on the employee (shown under the employee sign-off row) and their individual conversation due dates.

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/1545325d-c60e-464a-b005-599a8e9684fe)

**Comment by Travis-A-Clark** [comment]
@JonTelus I know you were doing some work on this but we are transferring your tickets to Ji and Dennis. Can you please let Ji know of any progress you've made so he doesn't redo the work? Thanks!

@jizhaogit This is related to ticket #898 so you might want to work on them both during the same sprint.

**Comment by JonTelus** [comment]
@jizhaogit  The only changes I have done is to Statisticsreportcontroller, to the functions conversationSummary and conversationSummaryexport.  I added joins to conversation_participants to pull out the 'emp' participants.  I tested this locally but didn't have enough data to fully test it.

**Comment by steffipravasi** [comment]
Testing blocked: 'Statistics and Report' option is not available under My Team drop down menu for any user![Screenshot 2023-03-01 at 9.21.41 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/59076401-719d-4c98-819e-a1a72a366f48)

**Comment by steffipravasi** [comment]
The HRAdmin charts are showing incorrect data as reported in ticket #898. Can test this ticket once 898 is fixed.

**Comment by steffipravasi** [comment]
The chart contents for HRAdmin and SysAdmin is still displaying incorrect data as mentioned in ticket 898. Will validate the ticket once 898 is fixed. 
![Screenshot 2023-03-08 at 1.55.21 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/128e1e56-f038-4401-aba1-0c3dc0feab4a)

**Comment by steffipravasi** [comment]
Assigned the following users HR Access. Will wait for the overnight process and validate this ticket tomorrow. 
1. Walter.Dagenais@gov.bc.cav- Water, Land & Resource 
2. Joseph.Jaffey@gov.bc.ca - Forests
3. Terry.Jones@gov.bc.ca - BC PSA
4. Rod.Allen@gov.bc.ca - Energy, mines and low carbon
5. Michelle.Glassel@gov.bc.ca - Justice

**Comment by steffipravasi** [comment]
Statistics and Reporting charts are employee oriented for Employee: Open and Conversations. ![Screenshot 2023-03-14 at 5.15.54 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/c51dd1d4-2e90-4c06-80aa-3e8d5176264a)![Screenshot 2023-03-14 at 5.14.34 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/42a258d0-93a8-4cd9-b220-4a7885d34736)
The charts for Open and Closed conversations are not employee based, but Travis has suggested to remove those charts as they are unnecessary in ticket 898. 
Moving this ticket for PO review.
