### ISSUE TITLE
Move to Employee ID as primary identifier in the app

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#891]
As per discussions with James and Justin, the PDP will move to employee ID as the primary link to information once a user has been authenticated into the application. This will replace instances in which GUIDs or user IDs have been used.

GUIDs will still need to be used as part of the authentication process to access the app.

**Comment by telusdcinco** [comment]
@jizhaogit Please review code changes.

**Comment by jizhaogit** [comment]
![query_error_891.jpg](https://images.zenhubusercontent.com/620163b737f8d3386467e70d/934d19a7-1252-4b39-a8a6-d36011863288)

@telusdcinco I got an error when running php artisan migrate. please kindly find the details from the attachment.  thanks!

**Comment by jizhaogit** [comment]
@telusdcinco Thanks Dennis for helping figure out the ODS data pull. code are good to me.  please go ahead the migration.  thanks!

**Comment by telusdcinco** [comment]
For Developers:
Please make sure to pull the latest ODS employee demo data before performing the "php artisan migrate".

**Comment by telusdcinco** [comment]
@Travis-A-Clark 
Fixed duplication of Goal Bank Individual Audience list for Sys Admin due to incorrect filter.
