### ISSUE TITLE
Create data audit record for tracking changes committed by scheduled jobs.

### ISSUE THREAD

**Issue by telusdcinco** [bcgov/performance#892]
Create data audit record for tracking changes committed by scheduled jobs.

New Table Name:  job_data_audit.

![image.png](https://images.zenhubusercontent.com/60e88ef619e4760c8b3ee8bb/fdb89e34-3bbc-4163-87eb-6ae94d39d51c)

CREATE TABLE `job_data_audit` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `job_sched_id` bigint(20) unsigned NOT NULL,
  `old_values` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `new_values` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `job_data_audit_job_sched_id_index` (`job_sched_id`),
  CONSTRAINT `job_data_audit_job_sched_id_foreign` FOREIGN KEY (`job_sched_id`) REFERENCES `job_sched_audit` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=6735 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci

**Comment by telusdcinco** [comment]
@jizhaogit Ready for you review before pushing to Test.

**Comment by jizhaogit** [comment]
@telusdcinco Thank you, That looks good to me.

**Comment by SSubashree26** [comment]
Performed the following to validate this story in the testing environment

Picked up some random employees with whom I was able to login, and shared their IDs with Dennis
Dennis modified the GUIDs of those employees
Validated that I was not able to login with the employees for whom the GUID was modified
Dennis ran an overnight job, which updated the employee IDs to their previous GUID value
I was able to login with those employee IDs again
Also audit logs were created for the overnight that was run (for UpdateGUIDByEmployeeId process)

Screenshots are available in the story #854
