### ISSUE TITLE
As a user, when I click outside of a dropdown menu, I want the menu to close without launching any new elements or links.

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#893]
On My Current Goals, if I use the Shared With drop down menu and then click anywhere outside of the menu area, the app launches the element that I clicked on.

Is there a way to have the Shared With drop down be the only active element when it is in use so that clicking anywhere outside of it just closes the menu and returns to the original page?

**Comment by jizhaogit** [comment]
removed onclick to redirect page js

@telusdcinco Code is ready for review in dev. thanks.

**Comment by telusdcinco** [comment]
> removed onclick to redirect page js
> 
> @telusdcinco Code is ready for review in dev. thanks.

Looks good

**Comment by SSubashree26** [comment]
@jizhaogit  Hi Ji, 

Noticed that while clicking on the "Start Date" field, while the "Shared With" drop down is open, it opens the calendar picker. Can you please have a look at it?

https://bcgov.sharepoint.com/:v:/r/teams/02915/Shared%20Documents/General/Testing/Testing%20screenshots/Performance%20%23%20893/Performance%20%23893%20-%20Part%202.mov?csf=1&web=1&e=rE1Ike

**Comment by jizhaogit** [comment]
@SSubashree26 i cannot see your movie. can you provide more details about the issue?

**Comment by SSubashree26** [comment]
@jizhaogit I am reattaching the screen recording here https://bcgov.sharepoint.com/:v:/r/teams/02915/Shared%20Documents/General/Testing/Testing%20screenshots/Performance%20%23%20893/Performance%20%23893%20-%20Part%202.mov?csf=1&web=1&e=xdxVMD

**Comment by SSubashree26** [comment]
It was confirmed in the sprint review meeting that the observation that I mentioned earlier is fine and therefore moving the story to PO review
