### ISSUE TITLE
Change the pop-up message on exit from conversation / goal modals

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#895]
Currently when a user closes the conversation modal or the create goal modal they receive the message: If you continue you will lose any unsaved information.

Please update this message to: If you continue you will lose any unsaved changes.

Thanks!

**Comment by Travis-A-Clark** [comment]
@jizhaogit This is a super small change that I'd like to make this sprint. Thanks!

**Comment by SSubashree26** [comment]
Completed validating this ticket in the testing environment for both goals and conversations, and it is working fine. Moving this story to "PO Review" column

Screen Recordings:
https://bcgov.sharepoint.com/:u:/r/teams/02915/Shared%20Documents/General/Testing/Testing%20screenshots/Performance%20%23895/Performance%20%23895.zip?csf=1&web=1&e=YIfmRa
