### ISSUE TITLE
Statistics and Reporting - Update to Conversation Summary Chart

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#898]
Currently, the conversations summary for open and completed conversations is focused on the topic of the conversation (see screenshot below). There is no indication of how many unique employees are assigned to those conversations. For example, in the screenshot below there are 101 total open conversations. It could be one employee having 101 conversations on a variety of topics or it could be 101 unique employees having 1 conversation each. The pie chart  would look the same regardless. 

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/ca3b9d60-981b-45d2-9bc5-2a68b9c411a3)

We need to add an indicator on Open Conversations and Completed Conversations charts that shows the percentage of the population represented by the topics displayed (i.e. how many unique employees are represented by the pie chart). If one employee was responsible or all 101 conversations, this additional indicator would show that. If the total size of the organization was 200, so it might show: "1/200 employees (0.5%)" above the pie chart.

This is related to ticket #890 that @JonTelus is working on to ensure the pie charts and downloadable CSV files are pulling the correct queries from the database.

**Comment by jizhaogit** [comment]
@Travis-A-Clark A question.  if supervisor A has 2 team members. A created 2 same topic conversations and assigned them to each of his team members. How many total participants for this topic should count?  4 or 3?

**Comment by jizhaogit** [comment]
@telusdcinco Please help the code review about 898 and 890.  thanks

**Comment by jizhaogit** [comment]
Currently for HR report version,  the Chart 2 and Chart 4 (and Chart 3/Chart 5) may not match, the reason is because in test/dev the "role" column is not updated as prod did.

**Comment by steffipravasi** [comment]
@Travis-A-Clark Confirming if we wanted to add an employee count indicator on the top of the Open and Closed Conversations or did we want to add 2 more charts for employees? ![Screenshot 2023-03-02 at 10.07.10 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/e7f3e355-5285-4221-9918-9872da40eb1f)

**Comment by steffipravasi** [comment]
Once Travis confirms the charts, we can fix the title label cutting from both the ends for 'Employees: Completed Conversations'
![Screenshot 2023-03-02 at 11.22.38 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/082c23bf-c780-42f5-ae05-7149dd8c5fbb)

**Comment by jizhaogit** [comment]
@steffipravasi ,  i checked the database and found that there only 2 employees are assigned to Briault,Barbara that is Paul Squires, and Ai Nakahama.   i created a conversation as Ai Nakahama and you can see the result is listed in the report.  maybe we need to wait till tomorrow after the access permission process is done and do the test again.  thanks

**Comment by Travis-A-Clark** [comment]
@steffipravasi Ideally, we would have a count of the number of unique employees represented in the pie chart. I'm not sure this is something that we can easily do, so it might need to be a separate ticket.

I don't think we will need the Topic: Open Conversations or Topic: Completed Conversations charts anymore; I don't think they add anything that the new ones don't have.

@jizhaogit In the excel file, can we please add the employee and supervisor sign-off columns back in? They were in the Topic: Open Conversations before (see below). Also can you change the name of the excel file to Open Conversations by Employee? Thanks!

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/37187ae8-54a5-4ce1-8b73-b7410efa6bbb)

**Comment by steffipravasi** [comment]
Difference in data for Employees: Open Conversations for Hr admin and Sys admin
Hr Admin: Travis Clark, Org: Advance education and skills training
![Screenshot 2023-03-08 at 12.35.26 PM copy.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/dfc7b6d5-ebef-4a5b-af71-140473735e38)

**Comment by jizhaogit** [comment]
@steffipravasi as we discussed in the meeting i did a data clean for all the conversations that do not have the right role settings.  you can still see the difference chart between the HR admin and Sys admin for Travis account. And that should be expected. because the HR admin chart ONLY shows the data that assigned access permission to the account and the system admin chart will show ALL data. 

@Travis-A-Clark Can you please help verify if a user have both HR admin access and System admin access that he/she should get the same charts in HR admin and System admin modules?

**Comment by jizhaogit** [comment]
@steffipravasi the query for the hr chart is updated, currently the HR chart of the organization "BC Public Service Agency" is matched with the System admin ones.  for the one of "Advance education and skills training" please re-assign the access permission, and test in the next day (for letting the backend process finish the permission assigning process.) Thanks.

**Comment by steffipravasi** [comment]
Assigned the following users HR Access. Will wait for the overnight process and validate this ticket tomorrow. 
1. Walter.Dagenais@gov.bc.cav- Water, Land & Resource 
2. Joseph.Jaffey@gov.bc.ca - Forests
3. Terry.Jones@gov.bc.ca - BC PSA
4. Rod.Allen@gov.bc.ca - Energy, mines and low carbon
5. Michelle.Glassel@gov.bc.ca - Justice

**Comment by steffipravasi** [comment]
Noticed that the Excel sheet for Employees: Open Conversations does not update with the Employees / Supervisor's sign off.  I signed off the Goal Setting conversation as an employee Frances Sasvari. But the excel sheet does not show the employee sign off column as signed.

**Comment by jizhaogit** [comment]
@steffipravasi thanks Steffi, the sign-off names are updated in the export result.  the 2 topic chart are also removed.  thanks!

**Comment by steffipravasi** [comment]
@jizhaogit The employee and supervisor columns are now fixed and updates after signing off, but somehow the employee name column is not displaying the names now. 
User: Michelle Glassel (HRadmin)
Issue only observed in Employees: Open Conversations chart.
![Screenshot 2023-03-15 at 9.32.05 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/1c883379-b74a-4872-90f2-3a1f42da4817)

**Comment by steffipravasi** [comment]
Ticket validated. 
![Screenshot 2023-03-20 at 11.27.51 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/c8915c1a-e553-431e-bfdd-f5629526ae88)

**Comment by steffipravasi** [comment]
Ticket validated. 
![Screenshot 2023-03-20 at 11.27.51 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/c8915c1a-e553-431e-bfdd-f5629526ae88)

**Comment by jizhaogit** [comment]
@steffipravasi i added "[]" for making the employee id as text but not a number.

**Comment by steffipravasi** [comment]
@jizhaogit I can see the employee id's in 6 digits now, but can also see '[]' before and after the id. Anything we can do here?![Screenshot 2023-03-20 at 5.47.09 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/6836ea9d-3d99-4987-ae46-3fb4d0f63c90)

**Comment by jizhaogit** [comment]
@steffipravasi this is what the fix do for. the "[]" forces excel process employee_id as a text but not a number.

**Comment by steffipravasi** [comment]
Ticket Validated. 
Employee id's displayed as 6 digits but with [] because of the reason mentioned above by Ji.![Screenshot 2023-03-22 at 1.48.00 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/7fd1298a-f99d-4f5d-8ee4-29fb43c177b9)
Moving ticket for PO review

**Comment by Travis-A-Clark** [comment]
1) In the completed conversation Excel file, can we please replace the Conversation Due Date column with the Conversation Sign-off Date?
<br>

2) Also, the name of the Excel file needs to be edited to just "Completed Conversations by Employee". There is an extra word "Open" in the title at the moment.

**Comment by jizhaogit** [comment]
updated as @Travis-A-Clark requests

**Comment by jizhaogit** [comment]
@steffipravasi it is a deployment issue.  a new push is on its way. will update you when it is ready. thanks!

**Comment by jizhaogit** [comment]
@steffipravasi the fix is pushed in test

**Comment by steffipravasi** [comment]
Ticket validated. 
-'[]' added to Employee ID for Completed Conversations 
- Completed conversation excel sheet renamed to Completed Conversations by Employee.csv
- Conversation due date column removed from completed conversation sheet
Moving ticket for PO review

**Comment by Travis-A-Clark** [comment]
@steffipravasi @jizhaogit 

Three things to follow up on here:

1. Can we combine Conversation Status back into the Conversation Summary tab? I know we separated out as part of troubleshooting performance issues. Is it safe to put back on the same tab now?
<br>

2. The Conversation Status queries need to filter out Excused employees before results are displayed. As HR Admin for BC Public Service Agency, I can see that 643 employees are not excused. This 643 should be the same total seen in all other reports.
![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/fc5fbdd2-b429-450f-937d-d429808f9bde)
Currently, the total of 643 is correctly displayed in Goals Summary and Conversations Summary tabs. However, the Conversations Status tab shows all 697 employees. Please apply the same filter.
<br>

3. There is a mismatch in information being displayed in Conversation Summary > Open Conversations and Conversation Status > Has Open Conversation. 

Conversation Summary shows 8 open conversations with two employees (Heather and Zehra) having two each. That means there are 6 unique employees with open conversations. 
<br>
![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/99029018-acb4-4565-b372-7b8e9dca69f4)

However, on Conversation Status > Has Open Conversation, it shows 10 unique employees with open conversations.
<br>
![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/07eaf7c8-09b0-407b-a2cb-73753236632d)

When I check the actual profiles, it looks like this second chart is incorrect. I don't see any open conversations for employees like Margaret Burrows or Jessica Wu, and yet they are shown in the chart.

**Comment by steffipravasi** [comment]
Conversations Summary page is not loading for Sys admin. Receiving time out error
![Screenshot 2023-05-05 at 2.47.48 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/d1763c0b-b2b4-45a7-8f71-62dfebf83492)

**Comment by steffipravasi** [comment]
Test update: Testing blocked with 504 time out error on the Conversation summary page

**Comment by steffipravasi** [comment]
Number of open conversations in the chart and in the excel sheet does not match. Eg: The number of Onboarding conversations in chart is 6 but in sheet is 5. 
Org: BC PSA
USer: Mark Bakusko (Sys admin), Shawna Wilson(HR)
![Screenshot 2023-06-01 at 2.39.58 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/41c72528-6068-47e4-8be5-39d830c65c00)

**Comment by jizhaogit** [comment]
@steffipravasi #1 number is matched now.

**Comment by steffipravasi** [comment]
The numbers mismatching issue has been resolved and validated for HR and Sys admin

**Comment by Travis-A-Clark** [comment]
@steffipravasi A couple of issues to check (logged in as Travis Clark looking at HR Admin view):

1. The total number of employees in the Conversations Summary area is 1303. In the Shared summary and Goals Summary it's 1322. Why is this different for conversations?
2. When I download the Open Conversation by Topic file, it shows that I have 4 conversations but the My Conversations page shows I have 6.

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/9627c998-ce96-4ce4-b855-df5c062efe34)

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/6164b27c-609d-4552-adc9-68c4cd54965e)

**Comment by steffipravasi** [comment]
@Travis-A-Clark 
For the issue number 1, the difference is because the Shared Employees list has a total of 38 entries which contains duplicate users which are getting filtered out in the Conversations chart. This issue is similar to the one I reported in ticket #923 where each case for user is different. The entries are duplicate because either the employee id, email or org is different.

**Comment by Travis-A-Clark** [comment]
Okay. I thought Dennis had created a process to fix this (just looking at Ji's last comment in ticket 923). We can discuss at the meeting this PM. If they are being filtered out in Conversations, they should also be filtered out in goals, shared, excused.

**Comment by steffipravasi** [comment]
@jizhaogit 
As discussed, Assigning ticket to you to check the Open and completed conversations chart.

**Comment by jizhaogit** [comment]
@steffipravasi please help verify if the numbers are matched. thank you!

**Comment by steffipravasi** [comment]
The requirements of this ticket are met. 
Charts with User has open and completed conversations has been added in the conversation summary.
