### ISSUE TITLE
Goals - "Shared With" and "Audience" dropdown menus display inconsistent information

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#899]
### Current Result

Currently, the menu can show different names depending on which goal is clicked.

For example, in Prod, Travis Clark clicks the Shared With for goal ID 1910 and sees two entries:

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/5710dfa8-e7c7-4802-8818-890c1b8d0a15)

Then Travis Clark clicks the Shared With for goal ID 3621 and sees three entries:

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/b15accf9-9128-4c6f-8da0-4a2ab5005855)

### Desired Result

When a supervisor clicks on the Shared With dropdown menu on their Goals page or the Audience dropdown menu on the Goal Bank page, they should see a current list of their direct reports and shared employees. These should be the same as the ones displayed on their My Team page. 

If a goal was shared with an employee who is no longer on the team, that employee should be removed from the drop down and should no longer have access to that goal.

**Comment by SSubashree26** [comment]
Also noticed that if a supervisor has a direct employee who is also a shared employee for the supervisor, the employee's name is duplicated in the audience field, while creating a goal in the goal bank

![Screenshot 2023-01-31 at 2.36.19 PM.png](https://images.zenhubusercontent.com/63892df90d58261296a2b5c0/eaffc349-a5f1-49b2-b0fe-0176f9a4e1db)

**Comment by jizhaogit** [comment]
the dropdown issue can be fixed with #900.  the time spent will be more on no-shared employees' access restrictions.

**Comment by jizhaogit** [comment]
@telusdcinco Please help do the code review. thanks.

**Comment by SSubashree26** [comment]
Completed validating this story in the testing environment and it is working fine. The Shared with and the audience fields reflect only the employees displayed in the My Team members page.

@Travis-A-Clark 
Did not validate the scenario in which the goal is shared with an employee and later the employee was no longer reporting to the Supervisor. Ji mentioned that the sharing logic needs to be updated to validate this scenario, and the goal will be displayed, even if the employee is no longer reporting to the supervisor.

@jizhaogit please feel free to add more details if I had missed any.

**Comment by Travis-A-Clark** [comment]
@SSubashree26 This ticket, and a few others, are now blocked by a larger ticket #905 Ji is working on re: sharing employees. We will have to wait and then test these again once 905 has been validated. Thanks!

**Comment by Travis-A-Clark** [comment]
As discussed, we will nee to introduce a daily chron job to clean up instances where a shared employee has become a direct report.

**Comment by steffipravasi** [comment]
Ticket validated. 'Shared with' and 'Audience' remains consistent. Issues listed above by Subashree has been fixed with the fix of ticket #905.
