### ISSUE TITLE
Goal gets created with automatically assigned audience if no audience is selected

### ISSUE THREAD

**Issue by SSubashree26** [bcgov/performance#900]
Observed this issue while validating the ticket #864 

**Observation 1:**
When a supervisor creates a goal in the goal bank, with no audience, no error message is displayed. Also, the goal created has audience selected automatically. This does not happen to all the supervisors and happens for supervisors who have their directly reporting employees, also as their shared employees.

Observed in: Test environment

Steps to recreate:
- Login with a supervisor (Supervisor used : Stefan Zeglan)
- Navigate to My Goals > Goal Bank > Add Goal to Bank 
- Fill in all the mandatory fields to create a goal 
- In the Audience field, the "All" value is selected by default
- Uncheck the "All" value in the Audience field and click on "Save changes" button

Expected Result:
The error message "Please select at least one employee" must be displayed

Actual Result:
No error message is displayed. The goal gets created, with automatically assigned employees

Screen Recording:
https://bcgov.sharepoint.com/:v:/r/teams/02915/Shared%20Documents/General/Testing/Testing%20screenshots/Performance%20%23864/Assigning%20two%20audience%20automatically.mov?csf=1&web=1&e=U0mSaW

**Observation 2:**
After creating a goal, the supervisor is able to delete all the employees from the Audience field. However, if they do so, the value in the audience field is not retained. When the goal is edited, the employees who were selected earlier, in the audience field, reappear.

Screen Recording:
https://bcgov.sharepoint.com/:v:/r/teams/02915/Shared%20Documents/General/Testing/Testing%20screenshots/Performance%20%23864/Editing%20goal%20-%20audience%20reaapear.mov?csf=1&web=1&e=QwOKfV

**Comment by SSubashree26** [comment]
Assigning to @Travis-A-Clark for review

**Comment by SSubashree26** [comment]
@jizhaogit  Observation 1 is working fine. However, I am still able to recreate observation 2. Can you please have a look at it?

https://bcgov.sharepoint.com/:u:/r/teams/02915/Shared%20Documents/General/Performance%20%23900%20-%20Ob%202.zip?csf=1&web=1&e=iQmkdg

**Comment by Travis-A-Clark** [comment]
@jizhaogit as per our call where i shared my screen, i was able to recreate the issue Subashree highlighted. If you de-select all audience members, the goal will initially show "Audience: None Selected" but once you refresh the page the audience members show as selected again. It is only an issue when you are trying to remove all audience. As long as at least 1 audience member remains, it properly saves all the changes. Sending back to you to investigate. Thanks!

**Comment by jizhaogit** [comment]
remove required check for the shared with items because the "goal shared with" accepts none select option

**Comment by Travis-A-Clark** [comment]
@SSubashree26 There are a few tickets around creating goals in the goal bank and selecting goal audience that I think need to be tested again all together before we push the changes to Production environment. 

Tickets #900, #899, #864, #792

I am going to put these tickets back in Ready for Testing until you have the chance to see them all at the same time. Thanks!

**Comment by SSubashree26** [comment]
Retested this ticket in the testing environment and it is working fine.
- An error message is displayed correctly when the audience field is left blank and 
- also, after creating a goal in the goal bank, when all the values in the audience field are unselected, they are not retained while editing the goal.

Therefore moving this ticket to PO Review column.

https://bcgov.sharepoint.com/:v:/r/teams/02915/Shared%20Documents/Product%20Team/Testing/Testing%20screenshots/Performance%20%23900/Performance%20%23900%20-%20Feb%2015.mov?csf=1&web=1&e=ju7tIB
