### ISSUE TITLE
Closing the Create New Goal modal before the autosave message is displayed

### ISSUE THREAD

**Issue by SSubashree26** [bcgov/performance#902]
**Current behaviour:**
While creating a goal, if the user is inactive for 15 minutes, we receive the auto save message. Post which the "Save changes" button disappears from the modal. The user has to close the create new goal modal and then reopen it and edit it.  

Incase if the user kept the modal open and had been typing after the autosave message was displayed, the user loses all the changes. 

Screen recording: https://bcgov.sharepoint.com/:v:/r/teams/02915/Shared%20Documents/General/Testing/Testing%20screenshots/Performance%20%23902/Performance%20%23%20902%20-%20issue.mov?csf=1&web=1&e=2sUKKn

**New behaviour:**
As the user loses the changes after the autosave message, Travis suggested the following behaviour for better user experience

- After 15 mins of inactivity, the "Create new goal" modal closes if all the mandatory fields are inputed 
- Then the user is displayed the auto save message 
- The user can then pick the goal that was created and continue editing it

**Comment by SSubashree26** [comment]
Assigning to @Travis-A-Clark for review and adding more details if required

**Comment by jizhaogit** [comment]
@telusdcinco please help do the code review. thanks

**Comment by SSubashree26** [comment]
Completed validating this ticket in the test environment and the modal closes after the auto save message is displayed. The user is then able to pick it up and edit it. Working as expected. Moving the story to "PO Review"

**Comment by Travis-A-Clark** [comment]
I just created a goal, filled out type, title, tag and description. The autosave created the goal but it did not give me a message to say that it had been saved.

**Comment by jizhaogit** [comment]
lets have a chat and check the details about the result. 

![image.png](https://images.zenhubusercontent.com/620163b737f8d3386467e70d/c6fcd0ba-66da-468b-87fb-d380dcfa7241)
