### ISSUE TITLE
Add instruction message to Create New Goal modal

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#903]
@jizhaogit As per our discussion during the product team call yesterday.

When a use creates a new goal, they have to fill in the top mandatory section before they are allowed to fill in the main content boxes. Currently, those boxes are just grayed out and inactive until the top section is complete. Let's add a message in the boxes that says: "Please complete goal type, title, and tags before entering this content."

**Comment by jizhaogit** [comment]
@telusdcinco Please review the code changes. thanks

**Comment by SSubashree26** [comment]
Completed validating this ticket in the testing environment.

@Travis-A-Clark when the user fills in all the mandatory details in the correct order, "Please complete goal type, title, and tags before entering this content."message disappears, as expected. However, if the user unselects any of the tags, then the message that was displaying earlier is no longer displayed and the main content boxes are still greyed out. Can you please let me know if this is fine? If this is fine, the story can be moved to PO Review column.

**Comment by SSubashree26** [comment]
Completed validating this ticket in the testing environment.

@Travis-A-Clark when the user fills in all the mandatory details in the correct order, "Please complete goal type, title, and tags before entering this content."message disappears, as expected. However, if the user unselects any of the tags, then the message that was displaying earlier is no longer displayed and the main content boxes are still greyed out. Can you please let me know if this is fine? If this is fine, the story can be moved to PO Review column.

**Comment by Travis-A-Clark** [comment]
Talked to Ji at scrum about saving of content when mandatory fields are filled out and then removed (i.e. tags added and then removed and then added again).
