### ISSUE TITLE
As an employee, I want to see contact information for my own organization on the PDP Contact page

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#906]
**Current Situation**

The Contact page has the same information for all users. There is a link to a central PDP inbox and a suggestion to go to AskMyHR for additional help.

**Desired Solution**

The contact page contains collapsible headers (accordions like on all the other pages in the Resources section) for each organization that display contact info for their specific ministry rather than the generic corporate contacts.

See comments below for the specific headers and contact information to display.

**Comment by Travis-A-Clark** [comment]
**For all the information below:**

### Header text is the name of an organization and should be displayed on the header / accordion when it is collapsed
Regular text below is the contact information that should be shown when the header is clicked and the accordion is expanded.

---
### Agriculture and Food
To be confirmed

### Attorney General
To be confirmed

### BC Public Service Agency
To be confirmed

### Children and Family Development
To be confirmed

### Citizens' Services
To be confirmed

### Education and Child Care
To be confirmed

### Emergency Management and Climate Readiness
To be confirmed

### Energy, Mines and Low Carbon Innovation
To be confirmed

### Environment and Climate Change Strategy
To be confirmed

### Finance
To be confirmed

### Forests
To be confirmed

### Health
To be confirmed

### Housing
To be confirmed

### Indigenous Relations and Reconciliation
To be confirmed

### Jobs, Economic Development and Innovation
To be confirmed

### Labour
To be confirmed

### Mental Health and Addictions
To be confirmed

### Municipal Affairs
To be confirmed

### Post-Secondary Education and Future Skills
To be confirmed

### Premier's Office
To be confirmed

### Public Safety and Solicitor General
To be confirmed

### Royal BC Museum
To be confirmed

### Social Development and Poverty Reduction
To be confirmed

### Tourism, Arts, Culture and Sport
To be confirmed

### Transportation and Infrastructure
To be confirmed

### Water, Land and Resource Stewardship
To be confirmed

**Comment by steffipravasi** [comment]
Contact page updated.

**Comment by Travis-A-Clark** [comment]
@telusdcinco Now that I see it on the page, I think we need a quick description sentence up top. Can you please add:

If you need assistance and can't find the answer in the resources section, please send an email to your organization's PDP contact listed below.

**Comment by telusdcinco** [comment]
@steffipravasi Fix pushed to Test.

**Comment by steffipravasi** [comment]
Sentence added to the Contact us page![Screenshot 2023-07-13 at 2.35.55 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/ccebf930-de48-4705-b3ea-126d6e48f7a2)

**Comment by jessicahjwu** [comment]
Added contact info for: Forests, GCPE, Transportation, and WLRS

**Comment by telusdcinco** [comment]
Latest change migrated to Training.

**Comment by jessicahjwu** [comment]
Updated contact info for : Citizens' Services, Post-secondary Education and Future Skills

**Comment by telusdcinco** [comment]
Pushed to Dev/Test pending build.

**Comment by telusdcinco** [comment]
@Travis-A-Clark Changes migrated to Test, ready for validation.

**Comment by steffipravasi** [comment]
Contact info updated on test

**Comment by Travis-A-Clark** [comment]
@telusdcinco 
Sorry, just received additional email addresses to include. 

Updated:
Agriculture and Food
Energy Mines and Low Carbon
Environment and Climate Change
Health
Indigenous Relations and Reconciliation
