### ISSUE TITLE
Update autosave pop-up message when creating a new goal in the Goal Bank

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#908]
Need to edit the pop-up message when creating a new goal in the goal bank and the autosave activates to fix a grammar issue.

Second sentence should be: "Your goal has been automatically saved."

**Current scenario**

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/46d81521-ae8f-4b37-b899-c6b40566f31d)

**Desired result**

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/2c6e02e7-36ed-4405-9c1c-1a572c478135)

**Comment by SSubashree26** [comment]
Completed validating this ticket in the testing environment and it is working fine for goals added and edited in the goal bank . Moving it to "PO Review"

![Screenshot 2023-02-15 at 5.15.18 PM.png](https://images.zenhubusercontent.com/63892df90d58261296a2b5c0/2122bbc0-3402-4e82-80ab-dbcd6d1df341)
