### ISSUE TITLE
Failed Process in Prod: CalcNextConversationDate overnight process failed in prod 2023-02-16

### ISSUE THREAD

**Issue by telusdcinco** [bcgov/performance#910]
Investigate failure of CalcNextConversationDate overnight process on 2023-02-16 2am.

2 issues found:

![image.png](https://images.zenhubusercontent.com/60e88ef619e4760c8b3ee8bb/58209853-bbb9-4e03-ba70-cdadf8cd91f8)

![image.png](https://images.zenhubusercontent.com/60e88ef619e4760c8b3ee8bb/9b6b9ded-eff2-400e-a40a-a439fb1c2c3f)

**Comment by telusdcinco** [comment]
Issue #1:  Scheduled process for pulling ODS Department data is not yet ready for prod.  Needs to be remove from scheduled list.
Issue #2:  Missing line in migrated code in the CalcNextConversationDate process, but is found in Dev/Test.  Needs to be urgently migrated to prod.

**Comment by telusdcinco** [comment]
@jizhaogit   Please review urgent code changes.

**Comment by jizhaogit** [comment]
@telusdcinco looks good to me.  please go ahead for the migration. thanks

**Comment by telusdcinco** [comment]
@Travis-A-Clark  This fix needs to go to prod for the Calc process to work successfully.  There is no change, just adding a line missed during migration.  The change was previously validated in Dev and Test.

**Comment by Travis-A-Clark** [comment]
@telusdcinco Can we do this now or should we wait until later in the afternoon / after business hours?

**Comment by telusdcinco** [comment]
@Travis-A-Clark  I can migrate now, but bounce the app pods later at 5pm.

**Comment by telusdcinco** [comment]
Missing code line was re-migrated yesterday.  The Calc process ran to success in the early morning.
