### ISSUE TITLE
As a user, I want to be notified when my session has expired and I have been automatically logged off the system 

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#913]
**Current Status**

Users are automatically logged out of the system when their session expires (I believe session length is 2 hours in Prod). However, they are not given any indication that they have been signed out. The user may try to enter additional information or access another page when they return to the app which can result in various error messages and potentially lost data.

**Desired Outcome**

When a session expires, the user is logged off and taken to a page that says: "Your session expired. Click here to log in again." with a link to the sign-on page.

**Comment by jizhaogit** [comment]
a redirect process is applied.  
@steffipravasi our test PDP session life time is set to 2 hours.  So it may be better to leave a PDP page loaded and back to check if it is redirected to the notification page.

**Comment by steffipravasi** [comment]
@jizhaogit Is it possible to change the session timeout timer to fewer mins like 2 or 3 mins? Maybe we can change the time today after 5pm PST and change it back to 2 hrs tomorrow morning?

**Comment by jizhaogit** [comment]
Hi Steffi, the session life time need to modify the global environment variable and clean the system cache. i will suggest let's not modify this to avoid any system issue and take an overnight testing. how do you think?

**Comment by steffipravasi** [comment]
Okay, I understand. My concern is that I won't be able to verify the behaviour of multiple pages. Will that be okay? Or do we want to check what Travis suggests?

**Comment by jizhaogit** [comment]
i dont think we need to verify multi pages.  what we need to test in this ticket is keep a random picked PDP page loaded in the browser and leave it there. after more than 2 hours, this page should be redirected to the notify page automatically.  and based on the requirement, there should be a link on that notify page, click the link will go to the PDP  login page.   that should be good enough for verify the process.  please correct me if it is wrong.

**Comment by steffipravasi** [comment]
Alright. Lets not change the time if it might create any issues in the system. I can verify the ticket after 2 hrs and overnight with multiple browsers. Will let you know the results. Thanks!

**Comment by jizhaogit** [comment]
thanks Steffi. but you can leave the page open and back to check tomorrow. 2 hours is really long for waiting.

**Comment by steffipravasi** [comment]
@jizhaogit One thing I noticed while testing is that the session does not expire when I am on the home page. Why is that? I left user on Home page for overnight, and in the morning saw that the session is not expired. Shouldn't it function the same way as others? 
Got the session expire msg for pages like My goals, conversation, team members![Screenshot 2023-07-11 at 10.40.38 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/8815d062-0f65-4a90-b5de-819776c4cb3a)

**Comment by jizhaogit** [comment]
@steffipravasi That is strange!!  the session life time should be global which currently in TEST is set as 2 hours.  no idea why the dashboard can keep it alive.....

**Comment by steffipravasi** [comment]
Do we want to look into it? Even after 2 hrs on the home page, I was able to access the website without the system logging me out. I was hoping that maybe on the click event of any button, the time out might trigger.

**Comment by jizhaogit** [comment]
sure we can look into it but should this be another issue out of this ticket?

**Comment by steffipravasi** [comment]
Tracking the home page issue in ticket #1026.
