### ISSUE TITLE
Ajax error displayed for Share Employees page - User: Fischer,Crystal N

### ISSUE THREAD

**Issue by steffipravasi** [bcgov/performance#916]
The pages Share Employees and Goal Bank are giving the Ajax error after loading for a while. 

User: Name: Fischer,Crystal N, HR Admin, Org: Justice, Email: cfischer@provincialcourt.bc.ca, Id: 000118![Screenshot 2023-03-01 at 12.03.24 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/97142d5f-81d0-4bf6-8d20-9eac6f8c02f7)

Page also shows a 504 error
![Screenshot 2023-03-01 at 12.53.51 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/66e245db-f1e9-42ef-adcf-31d26991404e)

Ticket has been discussed with Ji.

**Comment by jizhaogit** [comment]
remark it as 2 because data difference in local/dev and test.
