### ISSUE TITLE
Employee shared with Goals only appears in Participants list of conversation

### ISSUE THREAD

**Issue by steffipravasi** [bcgov/performance#921]
When an employee is shared with goal only to a supervisor, the expected result is that employee should only be displayed in the goals list for supervisor and not in the participants list.

Currently, the employee appears in the 'participants' list of conversation bank.

Emp: 011913 | Gowans,Mark P | Mark.Gowans@gov.bc.ca

Supervisor: 009065 | Leong,Richard L H | Rick.Leong@gov.bc.ca

![Screenshot 2023-03-08 at 5.01.38 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/a988f107-5c38-40b1-a042-f7b17d01229d)![Screenshot 2023-03-08 at 5.02.33 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/36254403-3344-4a83-bafd-4fd1e03d7514)

**Comment by Travis-A-Clark** [comment]
Moving this to the icebox because it likely won't be relevant after the work on ticket #860 and #940
