### ISSUE TITLE
Statistics & Reporting : HRadmin Conversation due date chart mismatches the Sysadmin charts

### ISSUE THREAD

**Issue by steffipravasi** [bcgov/performance#923]
The Next Conversation Due date chart in Statistics & Reports for HR admin differs the numbers from Sys Admin

1) Org: Justice
Hr admin: Michelle.Glassel@gov.bc.ca
Sys admin: Travis Clark

2) Org: BC Public Service Agency
Hr: Terry.Jones@gov.bc.ca
Sys admin: Travis Clark

![Screenshot 2023-03-14 at 4.19.58 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/fb64ffb6-053d-431c-86a4-4ae745c6f93c)![Screenshot 2023-03-14 at 4.28.59 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/afa10312-28fd-44c7-92d5-41e8ad745941)

**Comment by jizhaogit** [comment]
@telusdcinco Found the following users are assigned in the organization "Justice" but didn't be listed in the employee list of justice filter. that cause those users didn't be assigned to the HR admin. Would you please help take a look?  thanks!

+-------+------------------+
| id    | name             |
+-------+------------------+
| 14207 | Victoria Nygaard |
| 19606 | Susan Williams   |
| 25276 | Sheldon Johnson  |
| 30898 | Tony Nelson      |
| 33991 | Olivia Atwal     |
| 35847 | Jeffrey Noonan   |
| 37959 | Ryan Wainwright  |
| 39068 | Wendy Kellam     |
| 42513 | Jason Roberts    |
| 42976 | Amelia Hill      |
| 44358 | Bethany Wren     |
| 45052 | Noah Snell       |
| 45234 | Leila Darwish    |
| 45945 | Brendan Tallon   |
| 46121 | Jeremy Bissett   |
| 46275 | Jeremy Stone     |
| 48460 | Gillian Craig    |
| 48879 | Elizabeth Rennie |
| 49389 | Arshdeep Singh   |
| 49805 | Jake Styles      |
| 50068 | Karen Drake      |
+-------+------------------+
21 rows in set (0.00 sec)

**Comment by jizhaogit** [comment]
need to add employee_demo.deleted_at = null in the query to filter out past employees.

**Comment by jizhaogit** [comment]
@steffipravasi i chatted with @telusdcinco  this issue is related to organization processing changes. please hold it for now. thank you!

**Comment by telusdcinco** [comment]
There is a bug in the BuildAdminOrgUsers overnight process that needs to be fixed to correctly assign users to HR admin.  The bug is causing some employees from being accessed by HR Admin.

**Comment by telusdcinco** [comment]
The bug fix was done under ticket #809.  
#809 contains Org Tree Version 2 changes that needs to go at same time as #923.

**Comment by jizhaogit** [comment]
@telusdcinco thanks Dennis we finally get it fixed. 

@steffipravasi due to the rebuild process of the user grand access process, please re-grand access permission before you do the hradmin chart test.  thanks!

**Comment by steffipravasi** [comment]
Ticket validated. 
Gave new access to HR admins and numbers match for conversation due date charts for HR admin and Sys admin

**Comment by jizhaogit** [comment]
@steffipravasi could you please recheck the hradmin/sysadmin chart? i didnt see difference about them. thanks.

**Comment by steffipravasi** [comment]
With an employee having HR admin access to only one organization, the default charts will be the same as when the organization is selected. 
Currently, The default chart numbers are a little different. 
Example: User: Lorna Wollner with Citizens Services
![Screenshot 2023-03-31 at 12.28.02 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/dc24a39f-a7a4-4fc8-8949-a74c47f4140f)

**Comment by steffipravasi** [comment]
Ticket validated. 
Numbers are matching for default charts as well as when organization is selected.

**Comment by Travis-A-Clark** [comment]
@steffipravasi Numbers still look off to me. 

Sys Admin > Statistics and Reporting > Excused Summary shows 673 no and 58 yes for BC Public Service Agency.
![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/c00ca84e-1b48-41ee-bb3a-0c87fbca9487)

HR Admin > Statistics and Reporting > Excused Summary shows 643 no and 54 yes for BC Public Service Agency.
![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/803e20c7-da0d-408c-bdbd-3c24afe37c66)

**Comment by steffipravasi** [comment]
@jizhaogit Confirming the issue Travis mentioned. 
Numbers in Statistics and Reports are again differing in Sys admin and Hr admin view for all of the tabs:
-Goals Summary
-Conversations Status
-Conversations Summary
-Shared Employees Summary
-Excused Employee Summary
Verified for BC PSA and Citizens Services

**Comment by jizhaogit** [comment]
@steffipravasi @telusdcinco Me and Dennis spent some time for check this situation and found that the BC Public Service Agency was not registered as "Inherited", that caused the new department users that belong with BC Public Service Agency can not be auto granted access to Travis. We updated the organzation BC Public Service Agency as "Inherited" checked and data miss matching issue addressed. thank you Dennis for your great help!

**Comment by steffipravasi** [comment]
Conversations Summary page is not loading for Sys admin. Receiving time out error
![Screenshot 2023-05-05 at 2.47.48 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/d1763c0b-b2b4-45a7-8f71-62dfebf83492)

**Comment by steffipravasi** [comment]
1) HR Warrellow,William has access to BC PSA
In Shared Employees Summary reports with BC PSA, the numbers are 0-yes, 0-no
![Screenshot 2023-05-12 at 10.15.49 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/263b180b-5069-47f5-84a7-8fbde4c21c4c)
Found the same issue with the Conversation summary page, and Excused Summary page, Goal summary page
![Screenshot 2023-05-12 at 10.18.00 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/a126ac29-5646-48a0-a285-fa3a253881bc)
Charts Employee has Open/Completed Conversation shows wrong data
Same issue with ![image.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/21fc8b79-84fe-4b2e-a211-9bd6e672009b)
With Tourism, Arts and Culture org

**Comment by jizhaogit** [comment]
@steffipravasi  due to the org changing process.  Our grant access process is also changed.  that means so old access grant may not working.  If you found the data is not matching, please try to remove the existing access and re-grant as a new one.  
i tried with Warrellow,William,  remove the old access and re-grant new access for BC PSA and his data is look okay now:

![image.png](https://images.zenhubusercontent.com/620163b737f8d3386467e70d/b9e8c0df-b092-4afc-9af1-ba56b68b7137)

**Comment by jizhaogit** [comment]
![image.png](https://images.zenhubusercontent.com/620163b737f8d3386467e70d/fa6f4219-ca2d-408e-a014-1bf19936037e)

**Comment by jizhaogit** [comment]
![image.png](https://images.zenhubusercontent.com/620163b737f8d3386467e70d/ab63ffe7-87af-407e-8845-93736a442a09)

**Comment by steffipravasi** [comment]
@jizhaogit The total number of employees in the charts and in an org does not match due to the duplicate entries of some users. Although the user is the same, there are some differences such as the Status or Reports to.
For eg: The follow entries are duplicate in BC PSA
![Screenshot 2023-05-30 at 6.31.03 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/cde6f294-2b62-4a0d-baaf-6a0d8e666d17)
![Screenshot 2023-05-30 at 6.21.00 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/b49b5bc8-e1d0-45f4-a563-8c48352e0212)
![Screenshot 2023-05-30 at 6.40.30 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/99af38a9-5323-4217-b922-0ea969c71621)
@Travis-A-Clark Should these entries be displayed as duplicates? If yes then would it be considered as 2 users?

**Comment by jizhaogit** [comment]
pull back to in progress but waiting for business verification

**Comment by jizhaogit** [comment]
Dennis prepared a data cleaning process to deal with the old duplicate employee records

**Comment by jizhaogit** [comment]
data cleaning is done in DEV, Training and Test environments.

**Comment by steffipravasi** [comment]
The requirements for this ticket are met and the numbers mismatching between Hr and Sys admin is resolved. For some charts there is numbers discrepancy which is a data issue addressed in ticket #1007
Moving this ticket for PO review.
