### ISSUE TITLE
Examine usage of goal status and delete functions in PROD environment

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#929]
As per our discussion, generate data to understand how goals are being used in the Production environment. The intent is to see:
- How many goals are deleted?
- What goal statuses are being used to move items to the Past Goals area? I.e. how many goals are being achieved, not met, or cancelled?

**Comment by Travis-A-Clark** [comment]
Thanks, Jon!

Let’s use August 1, 2022 as a start date to see if that has any impact.

Is there anything we can glean about the goals that were deleted? Can we tell if they were deleted right after being created because they were mistakes or were kept for months and then tossed? I am trying to understand the data to figure out when someone would delete a goal rather than mark it as cancelled, for example. The raw numbers are helpful (more deleted than achieved, etc) but any additional insights you think you can tease out would be appreciated.

If nothing seems obvious, I can work with what you’ve already provided.

Travis Clark
Manager, Performance Development and Competencies
Corporate Workforce Strategies | BC Public Service Agency
865 Hornby Street | Vancouver, BC | V6Z 2G3
Tel: 778-360-2044

**Comment by Travis-A-Clark** [comment]
Thanks! This is super useful.

Can you send me the name or employee ID associated with those two prolific user IDs 44384 and 14944?

Travis Clark
Manager, Performance Development and Competencies
Corporate Workforce Strategies | BC Public Service Agency
865 Hornby Street | Vancouver, BC | V6Z 2G3
Tel: 778-360-2044

**Comment by JonTelus** [comment]
44384 is emplid 182208, Seyedmehdi Hashemirahaghi

14944 is 100870, Evelyn Carty
