### ISSUE TITLE
Fix Apache Folder Permissions Causing Deployments To Fail

### ISSUE THREAD

**Issue by telusdcinco** [bcgov/performance#931]
Fix Apache Folder Permissions Causing Deployments To Fail

![image.png](https://images.zenhubusercontent.com/60e88ef619e4760c8b3ee8bb/94c65e89-2cbe-415d-b331-1c8b81c257f5)

**Comment by telusdcinco** [comment]
Solution:

Add these lines in the DockerFile.


RUN chmod -R 755 /var/log/apache2
RUN chown -R www-data:www-data /var/log/apache2

**Comment by telusdcinco** [comment]
Nothing to test.  Change in DockerFile should allow access to the apache folders for logging.

**Comment by Abuchana** [comment]
@kkapoor-fresh I think this is the ticket you're looking for, yes?

**Comment by kkapoor-fresh** [comment]
Yes. Thanks. @Abuchana

**Comment by steffipravasi** [comment]
This ticket doesn't require testing.
Moving for PO review.
