### ISSUE TITLE
Notifications errors

### ISSUE THREAD

**Issue by steffipravasi** [bcgov/performance#932]
1) With the Select All option, select all the notifications and mark them as Read. Again Select all the notifications, and un-select a few of them. Mark them as unread. All the entries including the un-selected are now marked as unread.
Expected result: The selected entries must remain read. 
https://bcgov.sharepoint.com/:v:/r/teams/02915/Shared%20Documents/General/Testing/Notification3.mov?csf=1&web=1&e=CTG8yD

The same issue as above occurs if we mark all as unread, and try marking a few selected as read.

For a user with Notifications on more than one page, the following scenarios need to be fixed.
2) With the Select All option, select all the notifications. De-select a few notifications from the first page and navigate to the second page. The unselected notifications now appear at the end of the second page.
Expected result: The unselected notifications must remain 
in their place when selected/deselected
https://bcgov.sharepoint.com/:v:/r/teams/02915/Shared%20Documents/General/Testing/Notification1.mov?csf=1&web=1&e=aIa1I9

3) Select a few notifications from the first page and navigate to the second page. When navigated back to the first page, the selected notifications are unselected
https://bcgov.sharepoint.com/:v:/r/teams/02915/Shared%20Documents/General/Testing/Notification2.mov?csf=1&web=1&e=3CWNMw

**Suggestion: Right now, if we click on Select All, then all the notifications from the next pages are also selected. Should we limit the Select All for one page currently open only?**

**Comment by jp-Telus** [comment]
I can replicated the issue on my local and noticed that 2 issues:

1) The status of notification message were updated correctly in the database when the user click on 'mark as read' or  'mark as unread' on the home page. But when the page get refresh after the clicked, the data was reordered incorrecly and the changed rows were getting shuffled and relocated on the last page.
2) The checked rows were reset after navigate to difference page and come back.

In fact, the notification message are displayed in the descending order of created datetime.

**Comment by jp-Telus** [comment]
Migrated to DEV and verified.

**Comment by steffipravasi** [comment]
1) Select all the notifications and mark them as Read. Again Select all the notifications, and un-select a few of them. Mark them as unread. All the entries including the un-selected are now marked as unread.
Expected result: The selected entries must remain read.
Actual: All of the notifications, including selected becomes Read
https://bcgov.sharepoint.com/:v:/r/teams/02915/Shared%20Documents/General/Testing/Screen%20Recording%202023-04-11%20at%209.55.38%20PM.mov?csf=1&web=1&e=sW8ceG

**Comment by jp-Telus** [comment]
@Steffi, good findings. The 3 issues are fixed and all related to the same typo bug. You could retest. Thank you,

**Comment by steffipravasi** [comment]
1) To replicate the issue a user with more than one page of notifications will be needed. 
Click on Select all and mark them as unread -> Unselect a few from the page page only and navigate to the second page -> From drop down select Delete selected. Notice that all notifications are cleared out including the un-selected.
https://bcgov.sharepoint.com/:v:/r/teams/02915/Shared%20Documents/General/Testing/Screen%20Recording%202023-04-14%20at%203.53.48%20AM.mov?csf=1&web=1&e=VMRMQ0

**Comment by telusdcinco** [comment]
@jp-Telus #932 looks good.  Please proceed to migrate to Test.

**Comment by jp-Telus** [comment]
@steffipravasi, migrated to Test region and ready for test.

**Comment by steffipravasi** [comment]
Test validated and issues are resolved. Moving ticket for PO review.
