### ISSUE TITLE
Statistics and Reporting > display all Goal Tags and sort alphabetically

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#934]
Can we please sort the goal tags in Statistics and Reporting alphabetically? Screenshot below shows that not all of them are in order. Thanks!

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/66ad55e3-9d5c-4f64-b9be-d100c49bb568)

Also, it appears that we have lost some of the goal tags again in the TEST environment. Screenshot below shows TEST. Screenshot above shows TRAINING. Can we please ensure we are displaying all tags for both HR an Sys Admin? Thanks!

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/29ad78ed-9f0e-4fc6-8a73-ba85ef047368)

**Comment by steffipravasi** [comment]
1) I see that not all goals are displayed for HR admin view. I am guessing that the expected view must be to display all the goal tags for HR admin and Sys admin regardless of the tag being used. If he tag is not active or not used in any if the goal, its value must be zero. 
![Screenshot 2023-05-30 at 11.03.10 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/959667ae-de54-4b9e-a11f-39f36c98f2c8)
2) No value for tags are displayed when an org is selected from the search fields for Hr and Sys admin
![Screenshot 2023-05-30 at 11.15.07 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/27ec2b6f-d861-4fa2-9f6b-2bc602f54520)

_(Note for testing: Values to be matched for Sys and Hr admin once issue no 2 is fixed)_

**Comment by jizhaogit** [comment]
should all addressed

**Comment by steffipravasi** [comment]
@jizhaogit 
4) Fail: HR admin tags are still not sorted (a-Z). User: Shawna Wilson, Org: BC PSA
![Screenshot 2023-06-02 at 10.00.32 AM copy.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/91537615-b89e-4bb1-8716-5839c6158a59)

**Comment by jizhaogit** [comment]
issue should addressed

**Comment by steffipravasi** [comment]
@jizhaogit 
Test failed
1) The marked tags for HR admin are still not sorted
![Screenshot 2023-06-06 at 11.29.55 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/d483b6a5-2acd-4ef6-b380-cb495c78c4d0)
2) The new tag added is not displayed in the sorted order but at the end of list
![Screenshot 2023-06-06 at 11.32.15 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/f276e17b-af1c-434c-89b5-c69bda792622)
3) Remove the [Blank] tag

**Comment by jizhaogit** [comment]
should all be addressed.

**Comment by steffipravasi** [comment]
All issues mentioned above are addressed and validated on test for Hr and Sys Admin. 
Moving the ticket for PO review.
