### ISSUE TITLE
Statistics & Reports: Search fields does not store data after Search button is clicked

### ISSUE THREAD

**Issue by steffipravasi** [bcgov/performance#935]
For all the search fields on all pages of Statistics & Reports 
Actual result: If any value/ entry is selected for Organization/Level1/Level2/Level3/Level4 and Search button is clicked, the selected value from the fields disappears. 
Issue occurring on both HRadmin and Sysadmin.

Expected result: Any selected value in of the fields must remain selected and displayed until the 'Reset' button is hit or the value is changed

Issue found on: 
Goals Summary
Conversation Summary
Shared Employees Summary
Excused Employee Summary https://bcgov.sharepoint.com/:v:/r/teams/02915/Shared%20Documents/General/Testing/935.mov?csf=1&web=1&e=f0ikaw

**Comment by steffipravasi** [comment]
The selected fields are getting replaced by some other fields.
https://bcgov.sharepoint.com/:v:/r/teams/02915/Shared%20Documents/Product%20Team/Steffi%20-%20Testing/Screen%20Recording%202023-07-10%20at%2010.34.11%20AM.mov?csf=1&web=1&e=F1oZFL

**Comment by jizhaogit** [comment]
issue addressed

**Comment by jizhaogit** [comment]
issue addressed

**Comment by steffipravasi** [comment]
Test validated and issue has been resolved.
The selection of search in the Search Fields persists until the Reset button is clicked. 
Validation done for HR and Sys admin: Goals Summary, Conversation Summary, Shared Employees Summary, Excused Employees Summary. 
Account: Mark Bakusko
Moving for PO review.

**Comment by steffipravasi** [comment]
Yes, It's added to ticket #981 with some other issues related to Statistics and Reporting.
