### ISSUE TITLE
Supervisor cannot view his shared goal with the team member when switched profile

### ISSUE THREAD

**Issue by steffipravasi** [bcgov/performance#937]
Users: 
emp - 
000422	Dunn,K Patricia	Patricia.Dunn@gov.bc.ca
sup - 
126519	Bargen,Cory Russel	Cory.Bargen@gov.bc.ca
- Cory created a new goal and shared it with Dunn.
- Dunn copied the Goal from My Supervisor's Goal and the goal now appears in Dunn's My Current Goals list
- Cory navigated to My Team and can see that Dunn has 4 Active Goal, but when he switches his profile to Dunn's, he can only see 3 active goals in My Current Goal's list

Expected result: The supervisor must be able to view all the current goals
![Screenshot 2023-04-03 at 1.40.24 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/7e4d31a8-c510-416d-940f-6f2ba715464d)![Screenshot 2023-04-03 at 1.43.05 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/b745e8a4-0daa-4196-a68b-c78288d8af74)![Screenshot 2023-04-03 at 1.44.03 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/47d66b4b-236e-4163-9886-7f97b538c5b1)

**Comment by Travis-A-Clark** [comment]
Pending changes to goal sharing in ticket #860

**Comment by Travis-A-Clark** [comment]
Changed the way we share goals. Ticket no longer required.

Closing.
