### ISSUE TITLE
Upgrade Developer Tool 'adminer.php' and add dynamic security control feature 

### ISSUE THREAD

**Issue by jp-Telus** [bcgov/performance#938]
Fix the GUI issue by upgrading adminer.php and also add a feature to control access without restart POD.

**Comment by jp-Telus** [comment]
Work Done on DEV and Test regions for your testing

To use the adminer tool, please update the setting in file 'adminer' under storage/app directory:

ADMINER_ENABLE=on
WHITELIST=<ip address, ip address>

Note: ** Please disable the tools once you done. by reset setting in the adminer file **

**Comment by telusdcinco** [comment]
@jp-Telus Looks good.
