### ISSUE TITLE
Update Resources Section of App

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#940]
1.  Update user guide to reflect new functions
2.  Add FAQ tab
3.  Update Goal Setting and Performance Conversations if required

**Comment by Travis-A-Clark** [comment]
@JonTelus I will provide all of the updated content in Word format and will ask that you code the updates into the resources section. Hoping it will be fairly straightforward.

**Comment by Travis-A-Clark** [comment]
**Update the User Guide tab:**

[https://app.zenhub.com/files/329107952/a8bd9798-6fd6-4d91-9abb-adf002400f45/download](https://app.zenhub.com/files/329107952/a8bd9798-6fd6-4d91-9abb-adf002400f45/download)

**Add a "Video Tutorials" tab after the User Guide tab:**
- Placeholder for now. Just put "Videos will be provided soon." on this tab.

**Update to the Performance Conversations tab:**

[https://app.zenhub.com/files/329107952/e690c241-ced4-460e-b0fc-dcd40f87c85e/download](https://app.zenhub.com/files/329107952/e690c241-ced4-460e-b0fc-dcd40f87c85e/download)

**Add an "FAQ" tab after the Performance Conversation tab:**

[https://app.zenhub.com/files/329107952/0d22d9c0-724c-4727-bc95-3788436d93ea/download](https://app.zenhub.com/files/329107952/0d22d9c0-724c-4727-bc95-3788436d93ea/download)

**Comment by Travis-A-Clark** [comment]
@telusdcinco Maybe we could pull Jon in to make these updates? I had thought he might be available before, but not sure if he is now.

**Comment by steffipravasi** [comment]
1) User guide -> My Current Goals: Word 'just' missing![Screenshot 2023-05-31 at 11.55.12 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/90dabb82-0171-4336-b9b6-af84842fed5b)
2) User guide -> My Current Goals: Add 'ed' to the word display
![Screenshot 2023-05-31 at 11.57.36 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/42b1bbea-5e21-427e-ba8b-c5de3c8d18d5)
3) User guide -> Goals Shared with Me: Add word 'that![Screenshot 2023-06-01 at 12.04.13 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/7267e2cc-6136-4745-a04d-cb8d91dc060b)
4) User guide -> My Conversations Section: Remove the sentence - Visit the Performance Conversations resource for more information on best practices.![Screenshot 2023-06-01 at 12.21.01 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/c306f501-5286-4259-9f95-3cd57f3405d7)

**Comment by Travis-A-Clark** [comment]
Two things from my side of things:

a) Can we please reverse the order of the two sections in the FAQ area so that questions about the PDP go on top. That was my bad in the document I sent.

b) In reference to Steffi's comment #8 above, I was actually going to ask if we could have all URLs that are internal to the app be tied to the environment that it is published in. We are going to use this section in our Training environment, so the links will need to work for people that are logged in to the training environment without them having to also log in to the production environment.

Thank you!

**Comment by JonTelus** [comment]
I've made the changes noted.  @Travis-A-Clark the internal URLs are all coded to open in a new (same) tab, and are relative to the environment the user is in.  Test/PROD, etc, so this will work as you expect.
I have the changes in DEV, if there are no more updates I'll look to push to TEST again soon.

**Comment by Travis-A-Clark** [comment]
Thanks, @JonTelus ! Nothing else from my side, and I think Steffi has all her stuff up above. Please do push the updates to test.

**Comment by Travis-A-Clark** [comment]
@JonTelus Hey Jon! Hope you had a good weekend. Are you able to push these updates into Test today? I'm hoping to get them into our training environment by Wednesday. Thanks!

**Comment by JonTelus** [comment]
@Travis-A-Clark It was good!  I hope yours was good too.  :)   I actually pushed this to test this morning.  It's ready for Steffi.

**Comment by Travis-A-Clark** [comment]
@JonTelus I just took a quick look (haven't looked through any of Stefi's requests) but see that the order of the two sections in the FAQ still need to be updated and the links in the FAQ section still reference the production URL instead of the relative environment. Maybe the build didn't complete?

**Comment by JonTelus** [comment]
@Travis-A-Clark I missed a final button click to commit the changes.  It's done now, so when the build is done, it'll be ready.

**Comment by Travis-A-Clark** [comment]
@JonTelus Thanks! Only one change that I missed last time (sorry!). I developed these for a different audience and forgot to change out some of the language. In the FAQ for the PDP, bullet B:

Last sentence currently ends with "If you cannot find the answer, we can forward your email to someone who can investigate."

Please change to "If you cannot find the answer, please submit a service request through [AskMyHR](https://psa.frontlinesvc.com/app/ask) to My Team or Organization > HR Software Systems Support > Performance Development Platform."

**Comment by steffipravasi** [comment]
@JonTelus Can we open this links in a new tab since this links are not internal
- FAQ -> Questions about PD Approach and Process -> link 'Accountability Framework for Human Resource Management' 
- FAQ -> Questions about PDP -> Coaching link

**Comment by Travis-A-Clark** [comment]
@JonTelus Since you will be pushing a new version anyway, can you please also add the question below to the FAQ on the PDP. It will be bullet "n". Thank you!

### n. I do not see the correct supervisor in the PDP / I do not see the correct direct reports in the PDP. What do I do?

Reporting relationship data is pulled from PeopleSoft (our HR system of record) once every 24 hours. This data cannot be modified in the PDP. 

If you want to add a shared supervisor for an employee in the PDP, you can have the current supervisor share the employee by clicking on the Yes / No under the “Shared” column on their My Team page.

If the data in PeopleSoft is incorrect, you will need to submit a service request through AskMyHR using the category HR Software Systems Support > Position / Reporting Updates.

**Note:** Employees that report to a position number in PeopleSoft that is vacant are automatically assigned one level higher in the organization hierarchy. If that next level is also vacant, the employee will see on their home page that their current supervisor is “No supervisor”.

**Note:** Employees that report to a position number in PeopleSoft that has more than one active employee associated with it (“double-bunked” positions) will see a dropdown menu on their homepage that allows them to select which of the supervisors associated with the position number is correct for them. 

If a supervisor shares a position number with one or more additional employees in PeopleSoft (i.e. the supervisor is “double-bunked” in their position) they may not see the correct employees by default. In this case, their employees will be able to select the correct supervisor from a dropdown menu on the homepage under the “Current supervisor” heading. Once the employee has made the selection, the supervisor will gain access to that employee in the PDP.

**Comment by Travis-A-Clark** [comment]
@JonTelus If you haven't pushed anything yet, please add one more to the FAQ on the PDP. Bullet "o".

### o. What notifications and reminders will the PDP send me? Can I choose how often to receive an email from the PDP?

By default the PDP will generate in-app notifications on your homepage and send an email whenever someone:
•	Makes a comment on one of your goals
•	Adds a new goal to your goal bank
•	Shares your profile with another supervisor
•	Wants to set up a performance conversation with you
•	Signs-off on a performance conversation with you
•	Disagrees with the content of a performance conversation with you

And also:
•	One month before your next conversation due date
•	One week before your next conversation due date
•	When your conversation is past due
•	One month before your team member's next conversation due date (supervisors only)
•	One week before your team member's next conversation due date (supervisors only)
•	When your team member's conversation is past due (supervisors only)

Users have the option of opting out of receiving some of these emails. Notification options can be set on the [Account Preferences](https://performance.gov.bc.ca/user-preference) page. You can access this page by clicking on your username in the top right corner of the app.

**Comment by JonTelus** [comment]
I've updated my local with these changes.  We are having an issue with DEV, so I can't verify the changes there before  moving to TEST yet.

**Comment by JonTelus** [comment]
All changes in TEST now.

**Comment by steffipravasi** [comment]
@JonTelus Seems like the fix is not reflected on Test yet

**Comment by telusdcinco** [comment]
@JonTelus @steffipravasi It seems the build was not yet initiated for any of Jon's changes.  Last build I can see was at 9am this morning.
