### ISSUE TITLE
Update profile share options - remove Goals only option

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#941]
**Current Situation**

HR/Sys Admin and supervisors can choose to share only the goals section, only the conversations section, or both.

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/ff68d49e-2f62-4db7-ac9f-7c7d09431312)

**Desired Outcome**
The work being done on ticket #860 means that individual goals can now be shared with anyone across the public service. This makes it redundant to have the "goals section only" option. Sharing is now just yes/no and includes the full profile.

This will need to be updated in HR/Sys Admin views as well as My Team view for supervisors.

Also need to ensure the Statistics and Reporting Share Summary is updated and continues to display correct numbers of shared employees.

**Comment by telusdcinco** [comment]
Changes on the Sys/HR Admin pages.

![image.png](https://images.zenhubusercontent.com/60e88ef619e4760c8b3ee8bb/3c947421-3a29-4348-b0c3-93af5867fcba)

Column removed in Managed page.

![image.png](https://images.zenhubusercontent.com/60e88ef619e4760c8b3ee8bb/83d985df-e231-42ca-9880-24a5be63a4a5)

**Comment by steffipravasi** [comment]
My Team still shows the items to share options: 
![Screenshot 2023-05-03 at 11.59.01 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/111a0142-b0f8-461a-89b9-1785f774aeb2)![Screenshot 2023-05-03 at 11.59.18 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/73b30d60-f744-4653-9ad5-1360a28ed2ce)

**Comment by Travis-A-Clark** [comment]
Also recognizing we need to update the messaging on the HR Admin, Sys Admin and My Team pages. I had this captured in another ticket, but it makes sense to do it here.

- [ ] Update instructions on each page: "Supervisors and administrators may share an employee's PDP profile with another supervisor or staff for a legitimate business reason. The profile should only be shared with people who normally handle employees' permanent personnel records (i.e. Public Service Agency or co-supervisors). An employee may also wish to share their profile with someone other than a direct supervisor (for example, a hiring manager). In order to do this - the employee's consent is required."

- [ ]  Update the info toggle tip on Reason to Share to: 

Provide a brief explanation of why the profile is being shared. For example:

Sharing profile with co-supervisor
Sharing profile because of inaccurate data in PeopleSoft
Sharing with hiring manager per employee request

**Comment by Travis-A-Clark** [comment]
And we will need to remove the Shared Elements column in the My Team > Share modal at the top where it shows when a profile has already been shared.

**Comment by steffipravasi** [comment]
The instruction text has been updated on Sys admin, Hr admin and Team members page and so is the tool tip.

**Comment by telusdcinco** [comment]
@steffipravasi 1 & 2 is fixed in Test.
3. My understanding is that the profile sharing includes both Goals and Conversation.  I've also removed the Shared Elements column from that modal.
4. I'm looking in to the the Orgs not saving for New access, but this is not related to this ticket.  I'll be tracking the org changes/fixes under 785.

**Comment by steffipravasi** [comment]
Shared element section has been removed from the My team and shared with section on home page
![Screenshot 2023-05-09 at 3.47.42 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/01547386-d532-46d6-a95c-d3a28da32d1d)![Screenshot 2023-05-09 at 3.47.58 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/b1bcc677-aa6b-4b7f-9489-fadc2588ecbe)

**Comment by telusdcinco** [comment]
@steffipravasi  Issue resolved in Test.  Please retest.

**Comment by steffipravasi** [comment]
Test validated for Sys admin and looks good. 
Will validate for HR admin once the issue for 809 is fixed.
