### ISSUE TITLE
Past conversations due emails are sent out after Allowing email messages from Access Organization

### ISSUE THREAD

**Issue by steffipravasi** [bcgov/performance#944]
The conversations emails which were are not sent out because the Configuration Allow e-mail messages in Access Organizations is turned off are sent out once we turn the setting on. 
The emails for conversations past due date in Dec '22 and Jan '23 were received on April 4th and 5th. 
The emails generated for one month reminder of conversations not sent out were also received.
Environment: Test 
Expected result: The past emails must not be sent
![Screenshot 2023-04-05 at 2.50.22 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/2142de72-4744-487d-ac03-145c85031374)![Screenshot 2023-04-04 at 10.45.34 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/ee40606e-65b9-4feb-a93a-75dadc2879b9)![Screenshot 2023-04-05 at 5.15.23 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/c90be5fc-86d5-47cc-9813-8f6bd582d4a3)

**Comment by jp-Telus** [comment]
@Steffi, I brought this issue up daily scrum. Travis explained that the overdue date will be updated by Dennis' program/script to make sure they will update to the future date before switch on "Email or In App" notification message under system security control page.  

I would not to proceed my suggestion to add the email notification "start date" to be used in the overdue notification process to determine the overdue date after the "start date". 

Any comment?

James

**Comment by steffipravasi** [comment]
Will test this ticket after the overnight process on April 14

**Comment by steffipravasi** [comment]
April 14 - No changes were made to the Access Organization setting: No emails for past conversations due were received.

**Comment by steffipravasi** [comment]
As discussed, James to confirm if the following users received emails due to supervisor changed
April 16 (Received few emails for may 16)
Examples:

Sangeeta Ashby's Next Conversation Due Date is May 16, 2023
Palwinder Brar's Next Conversation Due Date is May 16, 2023
Ainsley Girvan's Next Conversation Due Date is May 03, 2023
Teresa Good's Next Conversation Due Date is May 01, 2023

Date: April 14 
Heather Shea's Next Conversation Due Date is May 09, 2023
Jenine Sanders's Next Conversation Due Date is May 09, 2023

Also, the emails received for next conversation due are calculated as: 
- For 1 week, emails are received for the 7th day. Eg: On april 17, the emails for due date Arpil 24 are received.
- For 1 month, emails are received for 1month + 1 day. Eg: On april 17, the emails due date for May 18 are received.

**Comment by steffipravasi** [comment]
As discussed with James, he will be adding 6-day buffer for the Reminder emails sent out on the day of the conversation due date. It means if for any reason the 'Reminder' emails are are not sent out due to any reason, the email will be sent as a Overdue email after 6 days.

**Comment by telusdcinco** [comment]
@jp-Telus #944 looks good.  Please proceed to migrate to Test.

**Comment by jp-Telus** [comment]
@steffipravasi, migrated to Test region and ready for test.

**Comment by steffipravasi** [comment]
Changed the System Security settings of the following org to allow in-app and email. 
Post-Secondary Education and Future Skills
Social Development and Poverty Reduction
Health
Forests
Education and Child Care
Will check the emails tomorrow after the overnight process

**Comment by steffipravasi** [comment]
The issue of this ticket No past emails were sent out is solved.
When the settings for the above-listed organizations are turned on the observations made are: 
- Overdue Notifications are received for conversation dates due for the past 6 days
- Notifications within one-month reminders are sent out because they weren't sent out before one month. some examples are May3, May16, May23, May19, May 30
@Travis-A-Clark are we okay with these emails are being sent out ?

**Comment by steffipravasi** [comment]
Moving the ticket to PO as no changes needs to be made for now.
