### ISSUE TITLE
Users receive in-app notifications even when the Allow in-app msg setting is turned off

### ISSUE THREAD

**Issue by steffipravasi** [bcgov/performance#945]
The users receive in-app notifications for goals even when the Allow in-app messages configuration in the Access organization is turned off
 Notifications are received when: 
- A goal is added to their goal bank
- Individual is added to an existing goal in goal bank
- Org is added to an existing goal in goal bank

Expected results: In-app notifications must not be received. 
Env: Test

Test data used:
1) Sys admin added Karen.Tunkara@destinationbc.ca to the goal Financial crime. System Security does not have allow in-app and e-mail messages. 
Expected result: User must not be notified through in-app and email 
Actual result: In-app notification is received 

2) Sys admin added new goal to the Org ‘Education and child care’. System Security does not have allow in-app and e-mail messages. 
Testing employee Troy.Yanulik@gov.bc.ca if he received in-app or email notification. 
Expected result: User must not be notified through in-app and email 
Actual result: In-app notification is received

**Comment by jp-Telus** [comment]
@telusdcinco, Please kindly perform code review before migrate to TEST. Thank you

**Comment by jp-Telus** [comment]
@steffipravasi  

The new coding was added and to check the "Allow in-app msg" global setting to determine whether to sent out In-app notification.

**Comment by steffipravasi** [comment]
Following the https://bcgov.sharepoint.com/:w:/r/teams/02915/Shared%20Documents/General/Testing/945%20test%20data.docx?d=wef8adc5716474468a8be7217cac6272e&csf=1&web=1&e=TsEyO3 test data.

**Comment by steffipravasi** [comment]
There has been a lot of inconsistency in the in-app notifications. 
Some of them has been documented here: https://bcgov.sharepoint.com/:w:/r/teams/02915/_layouts/15/Doc.aspx?sourcedoc=%7BEF8ADC57-1647-4468-A8BE-7217CAC6272E%7D&file=945%20test%20data.docx&action=default&mobileredirect=true
Ticket to be discussed with James

**Comment by steffipravasi** [comment]
@jp-Telus Assigning this ticket back to you to add the following fixes
Users receive in-app notifications for the following regardless of the In-app settings being turned off from Sys admin rights:
- Profile shared
- Conversation opened/scheduled/signed/disagreed

Also need to verify:
- New goal added 
- Conversation due



_Test case used: 
User: Nicol,Linda A. | Linda.Nicol@gov.bc.ca | 007680 
From Community Living BC – the org has only allow in app notifications and emails notification turned off 
Supervisor: 128126 | Rose,Sharon  
Profile shared with – 192985 (Notification received) 
Conversation open/scheduled - (Notification received) 
Conversation signed - (Notification received) 
Shared Robinson,Carol | 000648 with Linda  
Conversation scheduled by Carol - (Notification received) 
Carol selected disagree - (Notification received) 
Carol signed -  (Notification received) 
No notifications received for conversation due and past_

**Comment by jp-Telus** [comment]
The following areas have been updated to check "In-app settings" under Sys admin rights before create in-app message:

- Profile shared (my team, HR Admin, Sys Admin)
- Conversation opened/scheduled/signed/disagreed
- New goal added

**Comment by telusdcinco** [comment]
@jp-Telus Review completed.  Looks good.

**Comment by jp-Telus** [comment]
@steffipravasi, migrated to Test region and ready for test.

**Comment by steffipravasi** [comment]
Test status: Pass
Users do not receive in-app notifications when the Settings in access organizations is turned off.
Test data: 
012227, Wilkins,Grant, Grant.Wilkins@gov.bc.ca 
- Profile shared with 000426, Lemp,Donald (Not received) 
- New Conversation scheduled (not Received) 
- Conversation signed (not Received) 
- Employee selecting disagree (not Received) 
- Next conversation due (reminder and overdue) (not Received) 
- Goal added to goal bank (not Received) 
Moving ticket for PO review
