### ISSUE TITLE
Update Pop-Up Message when Signing-off on a Conversation

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#948]
**Current State**
When a user signs off on a performance conversation with their employee ID, a pop-up window comes up with the warning: 

"Signing off will lock the content of this record. Supervisor _(or employee depending on who signs)_ signature is still required."

**Desired Update**
Let's make the language stronger and more clear. Update the pop-up window warning to: 

"ATTENTION: Make sure both supervisor and employee have entered their comments before you sign-off. Signing off will "lock" both sides of this conversation and prevent additional edits by either participant."

**Comment by steffipravasi** [comment]
@Travis-A-Clark Can I confirm if we want this pop-up message before the msg in the ticket description is displayed?
![Screenshot 2023-05-05 at 12.25.19 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/dea2d2bb-4c56-4a3b-83e9-19d603b94ba3)
The below pop-up appears after the above msg
![Screenshot 2023-05-05 at 12.20.57 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/1ce7759f-3a2d-4a0f-9c6e-e8cc827da991)

**Comment by steffipravasi** [comment]
Test validated. 
Pop-up message updated. The attention msg is only displayed when none of the participants have signed the conversation.
Ready for PO review.
