### ISSUE TITLE
My Goals -> Goal Bank page gives 500 error

### ISSUE THREAD

**Issue by steffipravasi** [bcgov/performance#949]
The Goal bank page for employee when opened gives a 500 error
My Goals -> Goal Bank
My Goals -> Add Goal from Goal Bank
![Screenshot 2023-04-19 at 12.42.59 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/d4796e79-ea9a-4846-99bf-86d2dfc25b0f)

**Comment by telusdcinco** [comment]
@steffipravasi @Travis-A-Clark  Issue resolved.  The fix is part of #785

**Comment by Travis-A-Clark** [comment]
@telusdcinco Can we close this ticket then? Nothing to push to production from this? All captured in code for 785?

**Comment by telusdcinco** [comment]
@Travis-A-Clark  We can close this one if issue is resolved. Solution is part of #785.
