### ISSUE TITLE
PDP - Overnight Maintenance Process

### ISSUE THREAD

**Issue by telusdcinco** [bcgov/performance#951]
Create a process to perform clean up on audit logs (generated by overnight processes) older than x amount of time.

**Comment by telusdcinco** [comment]
Technical details for this change:

.env change (if not setup in .env, the default values used are PRCS_SCHED_LOG_RETENTION=30 and PRCS_DATA_LOG_RETENTION=7.
![image.png](https://images.zenhubusercontent.com/60e88ef619e4760c8b3ee8bb/6a27b7e0-3d9f-46e0-8aff-601bdb961d90)

Scheduled added for daily 6am.
![image.png](https://images.zenhubusercontent.com/60e88ef619e4760c8b3ee8bb/b3614666-0204-4a86-b5ec-4c9f7391eae2)

Terminal output expected when run manually.
![image.png](https://images.zenhubusercontent.com/60e88ef619e4760c8b3ee8bb/6135b193-c1e0-47e8-ace1-cbe578aedfd6)

Log entry example.
![image.png](https://images.zenhubusercontent.com/60e88ef619e4760c8b3ee8bb/d9089cc4-0a24-460c-921f-c17948822af5)

**Comment by telusdcinco** [comment]
@jizhaogit Please review new overnight maintenance process.

**Comment by telusdcinco** [comment]
Corrected typo on the log page details.
![image.png](https://images.zenhubusercontent.com/60e88ef619e4760c8b3ee8bb/5fa4ecf7-cffd-45dd-bde0-7ed476606aa2)

**Comment by jizhaogit** [comment]
@telusdcinco thanks Dennis, all good for me

**Comment by steffipravasi** [comment]
Moving this ticket for PO review as there is nothing to test the front end. The over night process is running successfully every night.
