### ISSUE TITLE
Sort feature for Goal Type in My Past Goal is not working

### ISSUE THREAD

**Issue by steffipravasi** [bcgov/performance#952]
The Goal Type title in My Past Goal when clicked, must sort the results in Ascending or Descending order according to the Goal Type results.

Actual result: Neither of the sort(Ascending or Descending) is working

![Screenshot 2023-04-20 at 2.40.41 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/547de885-c993-487a-bc7d-c0e9b5180615)![Screenshot 2023-04-20 at 2.40.32 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/b0682b0a-af8d-4632-8d4c-1298ac4ff644)

**Comment by Travis-A-Clark** [comment]
@steffipravasi Can you confirm if this is still an issue for you? It appears to work in my TEST environment using Chrome.

**Comment by steffipravasi** [comment]
@Travis-A-Clark I verified this issue on Edge and can still see that the sorting doesn't work. When I click on title Goal Type I can see the following results:
![Screenshot 2023-04-25 at 2.11.11 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/a8b011f3-f42c-4c9e-87c5-e3730099068c)
![Screenshot 2023-04-25 at 2.11.23 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/3d926f06-aa2a-459c-800f-c450f434c49d)
User: Nicola Lemmer

**Comment by SubashreeS** [comment]
Retested in test environment in Chrome and Edge browsers, and it is working fine.

**Screen Recording:**
https://bcgov.sharepoint.com/:f:/r/teams/02915/Shared%20Documents/Product%20Team/Steffi%20-%20Testing/Subashree%20-%20testing/Performance%20%23952?csf=1&web=1&e=6IPEeE
