### ISSUE TITLE
Enable background queue daemon process on multiple pod and make sure the notify job only run once on background.

### ISSUE THREAD

**Issue by jp-Telus** [bcgov/performance#953]
In order to offload the real time process to improve user experience, consider to implement background queue feature on the application server. 

Work to do
========
1. request Kunal to setup a autmatic startup of the queue:work daemon on the application server
2. update the background email notification process to ensure only one and one queue job run under multiple pod envrionment e.g. Production

**Comment by telusdcinco** [comment]
@jp-Telus #953 looks good.  Please proceed to migrate to Test.

**Comment by jp-Telus** [comment]
@telusdcinco ,

To enable queue or no queue on region, you just change the QUEUE_CONNECTION in .env file.
 
            QUEUE_CONNECTION=sync                           mean – no queue. real time 
            QUEUE_CONNECTION=database                   mean – use queue. Will process by the queue:work daemon on backgound.
 
             
![image.png](https://images.zenhubusercontent.com/60e73283e3a918390563e770/0df629ac-c747-4401-9f98-1b65dc5346ec)

**Comment by telusdcinco** [comment]
@jp-Telus Looks good to migrate to Test.

**Comment by steffipravasi** [comment]
No testing needed from front end
