### ISSUE TITLE
Change Default Account Preferences for Notifications

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#954]
**Current Situation**
Currently, a number of the account email notification preferences default to not sending emails to users. This means that, unless the opt in, they don't receive emails for things like a new goal in their goal bank or a new comment on their goal.

**Desired Solution**
I'd like to default to opt in for all the individual user notifications and force the employee to opt out if they no longer want to receive the emails. The default selection should look like the below.

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/8e01c4fa-2913-4787-9d8d-406dd04ecea5)
<br>

To make sure that employees aren't annoyed by the email volume, I will also update the email template messages to let users know they can change their email preferences in their accounts settings.

**Comment by jp-Telus** [comment]
@telusdcinco, Could you please perform code review? Thanks.

**Comment by telusdcinco** [comment]
@jp-Telus All good to deploy to Test.

**Comment by jp-Telus** [comment]
@steffipravasi 
Migrate to TEST and ready for testing. Thanks.

**Comment by steffipravasi** [comment]
The default account preference has been set as expected:
![Screenshot 2023-05-09 at 12.28.30 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/03f67a47-dd8b-4b41-989e-bca0690d4686)
Moving ticket for PO review.
