### ISSUE TITLE
Look into configuration or cron to manage the application log files, like laravel.log

### ISSUE THREAD

**Issue by telusdcinco** [bcgov/performance#955]
laravel.log file and similar files are currently growing in size.  We need to look at configuration changes to manage the files, or a new process in cron job if needed.
- change config to limit the file size
- create cron job to manage the files

**Comment by jizhaogit** [comment]
@telusdcinco  Please help review the new log config setting.  thanks!

**Comment by jizhaogit** [comment]
![image.png](https://images.zenhubusercontent.com/620163b737f8d3386467e70d/3103a987-78c2-4940-8f86-8cc013131367)

daily log setting is working as expected in test environment.
