### ISSUE TITLE
Increase PVC  size for MySQL volume from 4GB to 8GB in Prod

### ISSUE THREAD

**Issue by telusdcinco** [bcgov/performance#956]
Increase PVC  size for MySQL volume from 4GB to 8GB in Prod.

This is already done in Prod.  Ticket is created for tracking the action/activity.

**Comment by warrenchristian1telus** [comment]
I've also increased data-mysql-1 and data-mysql-2 PVC storage to 8Gi in case we ever scale up.

**Comment by kkapoor-fresh** [comment]
@warrenchristian1telus I was thinking of deleting the redundant mysql PVCs that aren't being used anyways and they are just utilizing sapce that can be freed up and used elsewhere. When we need to add more replicas to the Mysql cluster, we can scale it up and additional PVCs will get created.

**Comment by warrenchristian1telus** [comment]
Good call @kkapoor-fresh. Rather than adjust those PVC's, please delete them, and instead change the volumeClaimTemplates > requests.storage in the mysql StatefulSet to match (8Gi).
