### ISSUE TITLE
In PROD - goals with the same name / type are not shown on current and past goals list

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#958]
**Current Scenario**

In PROD, if a user creates a goal with an identical name to an already existing goal, only one will be displayed in the goal list. This is true in both current and past goals.

For example, a user has a Learning Goal called "Training". They then add a second Learning Goal, also called "Training". Only one of the two will be displayed.

I have checked in the audit log and the second goal has been created and assigned a goal ID. But the list only displays one of them.

It appears to be working properly in TEST where multiple goals with the same name are displayed without issue.

**Desired Solution**

Push the fix from TEST into PROD so that the goal lists display all goals regardless of duplicate names / types.

**Comment by Travis-A-Clark** [comment]
Example: Goal ID 12356 with goal title "Testing private goal" was created on Feb 15.

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/ff464ef7-99f7-461c-99b3-7b3a2d8f9026)

Then, today I created goal ID 14170 also with title "Testing private goal".

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/1f736014-f840-4d23-bb06-089f34edf5c3)

I can access them both if I type in the appropriate goal ID in the URL bar. However, my current goals list only displays one instance of a goal with that name (goal ID 14170). The original goal is bumped off the list.
![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/e851bba3-a1e8-4f57-b250-789aa9f8e569)

**Comment by Travis-A-Clark** [comment]
In TEST, goals with the same name are displayed without issue:

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/8d0650af-c033-4584-9b61-66c0b30c810a)

**Comment by jizhaogit** [comment]
The fix is located in Zenhub #455.  

\app\Http\Controllers\GoalController.php   LINE: 231
$goals = $query->groupBy('title');  -> $goals = $query->groupBy('id');

**Comment by steffipravasi** [comment]
Issue verified on test:
![Screenshot 2023-05-05 at 12.12.46 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/7bc07e2e-9ebe-4446-b414-e55bd74cbfd3)![Screenshot 2023-05-05 at 12.12.01 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/a647ffea-5dfe-4cd3-82bf-0b5ef2bb7e49)
We still need to verify it on Prod after deployment as this is a Prod env issue.
Moving ticket for PO review
