### ISSUE TITLE
Improve the UI when an employee creates a new conversation from the Conversations Template page

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#962]
**Current Situation**

On My Conversations > Conversation Templates: when an employee selects a participant and clicks "Start Conversation" they are taken to the Open Conversation page, but all of the accordion headings remain closed and it's really hard to know what happened to the conversation you opened. 

**Desired Solution**

Could the appropriate accordion header also be opened so you can see where the conversation template went? Maybe even launch the conversation template modal that was just created?

**Comment by steffipravasi** [comment]
Test pass and requirements have been met.
The conversation template modal opens up once the Start conversation button is hit. 
The appropriate accordion header also opens up if the modal is closed.
Moving ticket for PO review.
