### ISSUE TITLE
Add personal information collection notice on the homepage

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#963]
At the bottom of the homepage, below the notifications, please add the following text:

Your personal information is collected by the BC Public Service Agency and your Ministry pursuant to section 26(c)and 27(1)(f) of the _Freedom of Information and Protection of Privacy Act_ for the purpose of managing and developing, staff training, educational and career development.

**Comment by steffipravasi** [comment]
Notice added on the home page:
![Screenshot 2023-05-09 at 10.36.40 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/343f5810-ba8e-48c3-bb85-c5a5fbafc68e)
Ticket ready for PO review.
