### ISSUE TITLE
Re-assigning HR access to employee restores previous assigned orgs

### ISSUE THREAD

**Issue by steffipravasi** [bcgov/performance#964]
User: 000425 |	Allen,Roderick    |   Rod.Allen@gov.bc.ca
Had HR admin access to the following orgs: 
-BC Pension Corp
-Community Living BC
-Finance
-Justice
-Social Development & Poverty Reduction

Removed HR access and reassigned HR access to only one org i.e Justice

Issue: When logged in as Roderick, the org list under HR admin shows the list of previously assigned list of orgs (mentioned above)
Expected result: The org list must only display Justice

When in Manage Existing Access of Sys admin, we see Allen is only assigned to Justice
![Screenshot 2023-05-09 at 10.30.49 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/2c1ee207-7be9-4911-9983-1f976d3cab6a)
But from Allen's profile, can see all orgs
![Screenshot 2023-05-09 at 10.32.04 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/083c79d1-f98b-4727-b15d-8ce3e3f497d7)

-----------------------------------------------------------------------
Additional observation: If an employee is assigned HR access to multiple orgs, there is no way to revoke access for one particular org. We'll have to revoke access completely and assign the access again.

**Comment by steffipravasi** [comment]
If HR access to an org is granted by selecting the Inherited checkbox only, and when access is removed for that org from Manage Existing Access, the employee can still access the organization. 
User: 000018	May,Cathy
Assigned org BC PSA![Screenshot 2023-08-11 at 7.16.29 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/fe0b1865-d4f2-4353-995a-0f4651a68e21)
Removed the access for BC PSA, but Cathy can still access the BC PSA org![Screenshot 2023-08-11 at 7.21.43 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/91ab321f-8cb8-4b6b-baa7-6e80346d67f7)

**Comment by steffipravasi** [comment]
Test validated and issue has been resolved. 
Sys admin: Bakusko,Mark L
Hr admin: Zilke,Karen

**Comment by telusdcinco** [comment]
Latest change migrated to Training.
