### ISSUE TITLE
Duplicate entries in participants list of conversation

### ISSUE THREAD

**Issue by steffipravasi** [bcgov/performance#965]
Noticed a couple of users having duplicate entries in the participant's drop-down menu for conversation templates.
We had fixed this issue in the new conversation template ticket, so not sure if this is a data clean-up issue.
![Screenshot 2023-05-10 at 11.09.08 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/c98ac617-8997-49eb-a4ab-5784833079bd)
![Screenshot 2023-05-10 at 11.22.41 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/523931ff-09a9-44d7-8f65-82950d7f941e)

**Comment by steffipravasi** [comment]
@jizhaogit The account Blyth,Debbie can still see 2 entries of user Bauer,Connie
Although user Bauer,Connie has only one accountn in the employee list
![Screenshot 2023-06-24 at 2.31.55 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/e6cddbde-9cd0-44a7-93de-9b07a7b275db)

**Comment by jizhaogit** [comment]
@steffipravasi fix deployed, please help verify. thanks

**Comment by steffipravasi** [comment]
Test validated. 
No duplicate entries can be seen now. 
Accounts: Blyth,Debbie and Clark,Travis
![Screenshot 2023-06-29 at 12.25.55 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/9bb92f4f-861e-4abe-af2f-701233715091)![Screenshot 2023-06-29 at 12.25.42 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/6d234fcc-ca30-4bcd-bb25-d077b28d4fa6)
