### ISSUE TITLE
Create simple URL for the resources section of the PDP

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#966]
**Current Situation**

The URL for the resources section of the app is https://performance.gov.bc.ca/resource/user-guide

**Desired Solution**

Since there are different types of resources available and we will be adding more, I'd like to have a more generic URL that loads the page. Please change the main URL to https://performance.gov.bc.ca/resources

**Comment by telusdcinco** [comment]
@Travis-A-Clark 
Changes deployed to Test.

**Comment by steffipravasi** [comment]
Test env link changed to : https://performance-332842-test.apps.silver.devops.gov.bc.ca/resources
![Screenshot 2023-05-17 at 12.23.31 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/8f187b88-834d-4e5e-a154-753d3faa2147)
Can be verified on prod after deployment. 
Assigining ticket for PO review
