### ISSUE TITLE
Create New Goal shows duplicate tags fields

### ISSUE THREAD

**Issue by steffipravasi** [bcgov/performance#967]
My Current Goals -> Create new goal shows duplicate info toggle and tags field
![Screenshot 2023-05-17 at 1.12.53 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/b9ada95f-1f94-4998-b92b-fabf91b1b416)

**Comment by jizhaogit** [comment]
fixed with #860

**Comment by steffipravasi** [comment]
Test validated and issue resolved on test. Moving ticket for PO review.
