### ISSUE TITLE
Sort icons missing besides the column for My Current and Past Goals

### ISSUE THREAD

**Issue by steffipravasi** [bcgov/performance#969]
Title: Missing sort icons
Environment: Test
Steps: 
- Go to My Goals
- Open the My Current Goals/My Past Goals tab
- View the results table. 

Actual result: The titles are clickable but icons are not visible
Expected results: The column titles Title, Goal Type, Tags, Start Date and End Date need a sort icon on the right of the title to let the user know that the columns are sortable.
Severity: Low
Issue on My Current Goals and My Past Goals
https://bcgov.sharepoint.com/:i:/r/teams/02915/Shared%20Documents/Product%20Team/Tickets%20Requirements/969/147d9666-dc6e-43d4-a18c-88e7be33cc92.png?csf=1&web=1&e=Jd81NR
![Screenshot 2023-05-18 at 12.11.33 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/147d9666-dc6e-43d4-a18c-88e7be33cc92)

Additional comment: Match the colour of title 'Shared With' to other titles

**Comment by jessicahjwu** [comment]
@steffipravasi can you verify if this is still an issue? Thanks.

**Comment by jessicahjwu** [comment]
Duplicated with Accessibility elements, ticket closed.
