### ISSUE TITLE
Shared employee does not appear in the 'Shared with' list of My Current Goals

### ISSUE THREAD

**Issue by steffipravasi** [bcgov/performance#970]
User: Mark Bakusko 
Mark has 2 shared users in his Team members list: Shannon and Olurotimi
But cannot see Shannon in the shared with drop-down list in My current goals
![Screenshot 2023-05-18 at 1.19.56 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/21c9c17d-2650-4a7e-8231-5de24fa5824f)
I am guessing that the 'Conversation' part for Shannon was only shared with Mark which did not get converted to sharing the full profile after we fixed this issue.
![Screenshot 2023-05-18 at 1.29.01 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/1abf406e-5c9f-4ea0-94c3-46a5bc910037)

**Comment by Travis-A-Clark** [comment]
@steffipravasi I don't think this should be an issue anymore since the Shared With list is now open to all employees as per ticket #860. Is it safe to delete this ticket?

**Comment by steffipravasi** [comment]
Yes Travis. I am closing this ticket as Shared With list is not an issue anymore.
