### ISSUE TITLE
Resizing the 'Back to List' button in Goals

### ISSUE THREAD

**Issue by steffipravasi** [bcgov/performance#972]
The 'Back to List' button appears on the pages of viewing and editing the goal. 
The font size of the button/link is smaller than the regular fonts on the site which can make it less readable. 

We can either change it to a primary button style: ![Screenshot 2023-05-18 at 9.34.11 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/35f24aba-a692-49f1-9561-815421f1f1cc) or secondary button style : ![Screenshot 2023-05-18 at 9.35.36 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/dd52e77e-2dc2-4277-85bb-46f2156c45f0)or just display it as a link with bigger font

![Screenshot 2023-05-18 at 9.37.29 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/8ec9bf57-1610-4885-b1db-ade66715977a)

**Comment by jessicahjwu** [comment]
Pipelines: To be estimated
No sprints assigned
epics: Emp - Goal Setting

**Comment by steffipravasi** [comment]
Button has been resized
<img width="1286" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0h1QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ad971b4a90b2ffee5c781d15eee006af3450ed96/Screenshot%202024-03-19%20at%201.56.54%E2%80%AFAM.png" alt="Screenshot 2024-03-19 at 1.56.54 AM.png" />
<img width="1016" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0x1QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b9e925ee50cf232bc0a367b400e1f801baa6d107/Screenshot%202024-03-19%20at%201.56.41%E2%80%AFAM.png" alt="Screenshot 2024-03-19 at 1.56.41 AM.png" />
