### ISSUE TITLE
Updates to My Goals > Goals Shared with Me

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#975]
Please change the URL from:

https://performance-332842-test.apps.silver.devops.gov.bc.ca/goal/supervisor

to:

https://performance-332842-test.apps.silver.devops.gov.bc.ca/goal/shared

Please make sure that none of the links in the app break as a result.

Please change the pop up message that says "...without impacting your supervisor's goal." to say "...without impacting the original goal."
![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/ad95bb85-60c6-43f4-abcc-b9c4f24571f4)

**Comment by steffipravasi** [comment]
Issue addressed and validated on test.
Accounts used: Mark Bakusko, Barbara Briault, Chad Hoskins
 ![Screenshot 2023-05-31 at 3.07.55 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/58474410-f468-4edc-8f93-5e86f4261795)
