### ISSUE TITLE
Statistics and Reporting > Updates to Titles / Formatting

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#976]
Please make these changes for both HR and Sys Admin views.

**Statistics and Reporting > Goals Summary Page**

Updates to the Active Goals per Employee downloadable excel spreadsheet:
- Column D is currently "Active Goals Count"; can we please change this to "Total Active Goals"
- Add columns E, F, G, H that show "Active Work Goals", "Active Learning Goals", "Active Career Development Goals", and "Active Private Goals"

**Statistics and Reporting > Conversations Summary Page**

Apologies, as I know we are reverting back to some old names here!

Employees: Open Conversation 
- Change name of pie chart and downloadable excel to Open Conversations by Topic
- Change column D of the excel file from "Conversation Name" to "Conversation Topic"

Employees: Completed Conversation
- Change name of pie chart and downloadable excel to Completed Conversations by Topic
-  Change column D of the excel file from "Conversation Name" to "Conversation Topic"

**Comment by jizhaogit** [comment]
@Travis-A-Clark Please see my comment below:
Add columns E, F, G, H that show "Active Work Goals", "Active Learning Goals", "Active Career Development Goals", and "Active Private Goals"

The excel is a plugin **ONLY** for exporting the result of the chart. We cannot export a result that has different structure with the chart displaying. if we need the export result show the "Active Work Goals", "Active Learning Goals", "Active Career Development Goals", and "Active Private Goals" we need these elements be displayed in the chart too.

**Comment by jizhaogit** [comment]
Update: i found a way to do the export with additional information based on different queries. please ignore my comments

**Comment by steffipravasi** [comment]
@jizhaogit 
1) Column Active Private Goals missing in the Active Goals per Employee downloadable excel spreadsheet. Needs to be added in column 'H'
2) Conversation summary - Change name of the downloadable excel to Open Conversations by Topic for chart Open Conversations by Topic. 
3) Conversation summary - Change name of the downloadable excel to Completed Conversations by Topic for chart 'Completed Conversations by Topic'

**Comment by steffipravasi** [comment]
Test validated.
Issue 1,2,3 - Pass
![Screenshot 2023-06-02 at 10.37.28 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/b2e60c37-81e1-4f51-9bf8-72732dec144f)
Ready for PO review
