### ISSUE TITLE
Change the Validation message for Reason for sharing field

### ISSUE THREAD

**Issue by steffipravasi** [bcgov/performance#977]
Please just change message to: "This field is required."

![Screenshot 2023-05-26 at 4.47.47 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/951c3ea4-9013-445e-b322-87b8ec2e6ed2)

**Comment by jizhaogit** [comment]
@steffipravasi sorry, which page it is?

**Comment by jizhaogit** [comment]
validation message is changed

**Comment by steffipravasi** [comment]
@jizhaogit Sorry its the Share employee page for HR and Sys admin

**Comment by steffipravasi** [comment]
@jizhaogit The error message needs to be changed for the Share employee page for HR and Sys admin![Screenshot 2023-07-07 at 2.14.42 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/90d5e335-fd02-429e-84a8-50bba64ad886)

**Comment by jizhaogit** [comment]
its there both sysadmin and hradmin. please double check. thanks

**Comment by steffipravasi** [comment]
@jizhaogit Sorry but I did confirm and issue is not addressed for HR admin -> Share Employees and System Admin -> Share employees page Step 3: Enter Sharing Details
User account: Mark Bakusko
![Screenshot 2023-07-07 at 2.14.42 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/11abcdc5-23c3-48bc-b3b6-bf10c58f1c3e)

**Comment by jizhaogit** [comment]
talked with @steffipravasi found it not only in the popup modal but also in the button of the page needs the modification. a new change will be applied soon

**Comment by jizhaogit** [comment]
fix is ready for testing

**Comment by steffipravasi** [comment]
Test validated and issue has been addressed for all pages![Screenshot 2023-07-07 at 3.44.23 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/65d7efa8-29ba-4617-9ca4-231c6d3e7541)
Moving for PO review.
