### ISSUE TITLE
Sys / HR Admin > Stats and Reporting > Goal Summary: Optimize response times

### ISSUE THREAD

**Issue by steffipravasi** [bcgov/performance#979]
We rolled back some of the goal summary optimization in order to get the correct numbers displayed in the production environment for launch. Let's work to speed up the response time while keeping accurate data.

**Comment by jizhaogit** [comment]
@Travis-A-Clark @steffipravasi Please help me create some testing case for verifying the result after applied optimized query and logic.  Thank you!

**Comment by telusdcinco** [comment]
@jizhaogit As discussed, please manually create the Test data as needed for Stats & Reports.

**Comment by steffipravasi** [comment]
@jizhaogit Not able to access or download any reports from any charts in Goal Summary. Receiving the 500 error.

**Comment by steffipravasi** [comment]
The response time to load the Goals summary page is quick. Although for Orgs like Justice, when downloading the charts, it takes about 12-14 seconds to load. 
The general excel sheet for Active Goals Per Employee will display all the goals in 3 different entries for each goal type. Eg: Travis has 7 goals in total but the sheet will have 3 entries for Travis. 1) 5 work goals 2) 1 Learning goal 3) 1 Career Development goal.

**Comment by Travis-A-Clark** [comment]
It looks like we are missing the columns for the different goal types on the Excel download for Active Goals per Employee.


In Production, the Excel file looks correct:
![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/01e42acf-72ee-4d0c-8e43-5d3e10f551ee)

In Test, it only has one column:
![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/6a9003ac-e833-4dbf-8a83-b838a4ccafcd)

**Comment by telusdcinco** [comment]
The code changes for this one seem to impact #1069.

**Comment by steffipravasi** [comment]
Logged in as Sys admin: Travis Clark
Org: BC PSA
1) The Total Active Goals column is missing From the general excel sheet
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdFFWIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--804c3b3658c5f635e0ea774f182e840d698b4b5c/Screenshot%202023-08-17%20at%205.18.36%20PM.png)[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdFVWIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--c1127bd436e1a96249c9a03f6949aa612b8e042b/Screenshot%202023-08-17%20at%205.19.03%20PM.png)
2) Goals 1-5 has a total count of 18 on the chart, but in the excel sheet there is only 12 employees
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdGNWIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--635caf9020789f7ba6f82223897cb8444a7329fb/Screenshot%202023-08-17%20at%205.23.48%20PM.png)[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdGdWIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--f9a5b778d9d462d0c2a2e198bcba0a0f30c2a408/Screenshot%202023-08-17%20at%205.26.44%20PM.png)
3) The employees with 0 goals when clicked, downloads the sheet with 669 employees. The chart shows number of 651
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdUVWIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--e2f73ef22a32423a0d3e64c87d6ed9fabf902366/Screenshot%202023-08-17%20at%205.31.28%20PM.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdVlWIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--955458e2e860501ef5634376975e13799ca593b0/Screenshot%202023-08-17%20at%205.33.20%20PM.png)
4) All the charts have a Reporting To column but its empty for all the charts
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdW9WIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--26229d7027e9c0243456c148cc35b0a47d8880c7/Screenshot%202023-08-17%20at%205.36.02%20PM.png)

**Comment by jizhaogit** [comment]
@steffipravasi as we discussed. the reporting to column is fixed. thanks!

**Comment by jizhaogit** [comment]
@steffipravasi chart is modified as we decided in the meeting. Please help verify. thanks!

**Comment by steffipravasi** [comment]
1) Remove the undefined word from chart title
2) Reporting to column does not display data for the Active Work/Learning/Career Development Goals Per Employee charts

**Comment by steffipravasi** [comment]
Sys admin -> Receiving 500 Server Error for Active Goals Per Employee chart

**Comment by jizhaogit** [comment]
issue addressed

**Comment by steffipravasi** [comment]
Test validated and all the issues have been addressed and verified on test env.
