### ISSUE TITLE
My Goals > Goal Bank > Team Goal Bank: update Add Goal to Bank modal

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#980]
Update the Add Goal to Bank modal to match the same input verification, data verification and autosave functionality that exists in the Create New Goal modal from my current goals.

I.e. The user should have to add goal title, type, and tags before the goal content comment boxes are enabled., etc.

**Comment by jizhaogit** [comment]
@steffipravasi for testing purpose i set the time duration checking as 1 minute.  we will change it to 15 minutes once we get verified.  Thanks!

**Comment by steffipravasi** [comment]
1) After auto-save, the mandatory fields where data is already entered, display the *required error
Expected result: The fields must not display error and auto save 
![Screenshot 2023-07-06 at 12.02.31 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/1af3f35d-eaba-43a9-b5ba-082d8ea98ca3)

**Comment by jizhaogit** [comment]
detected issues are fixed

**Comment by steffipravasi** [comment]
@jizhaogit The second pop-up message displayed for Add Goal in Team Goal Bank is incorrect. Can we change it to  'Your goal has been saved' similar to My current goals
My Current Goals:
![Screenshot 2023-07-07 at 12.22.49 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/577fac11-10ce-4a13-b808-5283b54f215e)
Team Goal Bank:
![Screenshot 2023-07-07 at 12.19.24 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/f3c255e6-06c1-44ba-a328-b4c454a05d3f)

**Comment by jizhaogit** [comment]
issue addressed

**Comment by steffipravasi** [comment]
Test validated and issue has been addressed. 
The Goal bank modal for My Current Goals and Team Goal behaves identically. 
@jizhaogit Can you please change the Auto save time back to 15 mins for both the pages.
Will move the ticket for PO review once time is changed.
