### ISSUE TITLE
Statistics & Reporting Enhancements

### ISSUE THREAD

**Issue by steffipravasi** [bcgov/performance#981]
Goals Summary:

Incorrect title displayed for Conversation Summary page. Change it to 'Conversation Summary' instead of Goal Summary. ![Screenshot 2023-07-10 at 12.35.41 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/babd3773-13dc-4f13-8c9a-d514118b0a03)

**Comment by Travis-A-Clark** [comment]
Rest of work being take care of on ticket #1040.

**Comment by steffipravasi** [comment]
![Screenshot 2023-07-13 at 4.41.42 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/87effa74-957a-47ad-8f03-0413374cd8c4)![Screenshot 2023-07-13 at 4.41.56 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/a92e673d-fea9-435e-98f0-0dbcf7d29495)
