### ISSUE TITLE
Fix email notifications for comments on goals

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#984]
**Current Situation**

Currently, when a shared / delegated supervisor comments on an employees goal, the employee receives the correct notification on the app homepage, but an incorrect notification via email. The in-app notification shows the name of the person who made the comment while the email shows the name of their PeopleSoft supervisor as the person that made the comment, even if it was someone else. The notification template defines that variable as "the person that made the comment" regardless of whether it was a supervisor or a colleague, etc. but it seems like the logic in the background is grabbing the direct supervisor name and using that.

**Desired Result**
The email and in-app notifications both correctly identify the person who made the comment on the employee's goal.

**Comment by steffipravasi** [comment]
@telusdcinco The delegate supervisor when adds a comment to the goal, his name is not displayed in the email
In the following email![Screenshot 2023-07-12 at 12.44.11 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/cd72c55d-7bff-455a-992d-caa5d15a4665), the name expected is Bauer,Connie
Comment:![Screenshot 2023-07-12 at 12.44.48 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/e0aa4a60-02e4-4249-a2e1-f51f6dc2b451)
In-app:![Screenshot 2023-07-12 at 12.46.23 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/df091406-2c00-4a67-9281-dd26aba37ff8)

**Comment by telusdcinco** [comment]
Previous fix was not pushed to Test.  Re-pushing fix to match in-app name in the email notification.

**Comment by steffipravasi** [comment]
Test validated.
Correct names are displayed for in-app and email notifications when a direct or delegate supervisor adds a comment to a goal.
Ready for PO review.
