### ISSUE TITLE
Update Excuse status column in real time on HR / Sys Admin tabs

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#985]
**Current Situation**

On the My Team tab, changing the excused status of an employee is immediately reflected on the employee list. However, changing the excused status of an employee from HR Admin > Excuse Employees is not reflected in real time. The result is that an HR Admin can go in and manually excuse an employee but the page will still show "No" on the excused column until the overnight process is run. This is confusing for the user.

**Desired Result**

The HR Admin sees their action to excuse an employee reflected in the status column when the page reloads.

**Comment by steffipravasi** [comment]
Test validated for HR and Sys admin
Employees excused from HR/Sys admin -> Excuse employees, My team -> Team members are updated real time and displayed in the employee list and excuse employee tables.
