### ISSUE TITLE
My Organization List Enhancements for HR

### ISSUE THREAD

**Issue by steffipravasi** [bcgov/performance#986]
This ticket content for HR admin is copied from the ticket number #887 

**Observation 1:**
We are not displayed with the search results when we type the full name of a person. For example, typing "May Cathy" with a space in between displays no search results.

![image.png](https://images.zenhubusercontent.com/63892df90d58261296a2b5c0/a8764365-98c1-4b05-a632-44853ad5f475)

**Observation 4:** (Nice to have feature)
After a search is performed, the progress bar is being displayed in the middle of the search results table.
If there is a huge result set, the system takes a little longer before the results appear(especially while sorting with the employee ID). The user might not know if the results are appearing or not and might be tempted to click on the filter button multiple times. It would be nice to have it displayed on the top. This sometimes causes the Ajax error mentioned in the defect #884.

**Observation 5**
Sort features for the following columns is not working for Employee List (Sys admin), My Org(Hr admin) and Past Employees(Sys admin):
-Active Goals
-Next Conversation
-Shared
-Direct Reports

**Comment by Travis-A-Clark** [comment]
@telusdcinco Can we also please display the same columns in HR Admin > My Org that we do in Sys Admin > Employee List?

Specifically the additional reporting to, status, and record # info:

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/a58a3f89-70cb-4ce2-bd5e-baa44e819cfe)

**Comment by Travis-A-Clark** [comment]
@telusdcinco New columns look good in My Org view! Can we please also update the search function and drop down list to match Sys Admin > Employee List? Thanks!

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/5ecdaaaf-986f-484f-a078-05139cc789f4)

**Comment by steffipravasi** [comment]
Test validated for HR admin -> My org list
The issues in the ticket description have been added
The additional columns are added to the list
Acc used: Shawna Wilson
Moving for PO review

**Comment by steffipravasi** [comment]
@telusdcinco The Reset button when clicked, does not keep the 'Name' (default) search criteria selected![Screenshot 2023-07-11 at 11.57.32 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/5f540419-23aa-4441-b51f-9c5418acaf0b)

**Comment by telusdcinco** [comment]
Search Criteria reset fixed.

**Comment by steffipravasi** [comment]
Test validated for HR admin -> My org list
The issues in the ticket description have been added
The additional columns are added to the list
Additional search fields have been added.
Acc used: Shawna Wilson
Moving for PO review
