### ISSUE TITLE
Sys/Hr admin > Goal Bank > Selected multiple entries in Individual audience on different pages are not stored

### ISSUE THREAD

**Issue by steffipravasi** [bcgov/performance#987]
1) If option Select All is selected, all the entries on all pages are displayed as selected, but only the entries on the current/open page are added to the goal

2) If we select few entries from page 1 and navigate to page 2 -> select few entries -> Add/ update goal. Only entries on page 2 are added to the goal,

3) When trying to add multiple employees by searching them through the search fields, results in only the last one remaining selected and being added to the goal. 
Expected result: We must keep all the selected employees saved and add them to the goal
Issue for Hr and Sys admin - Add and Edit goals
Additional: It would be nice to have a list that displays all the selected employees added through the search fields

https://bcgov.sharepoint.com/teams/02915/_layouts/15/stream.aspx?id=%2Fteams%2F02915%2FShared%20Documents%2FProduct%20Team%2FSteffi%20%2D%20Testing%2F1114%2Emov&referrer=OneDriveForBusiness&referrerScenario=OpenFile

Issue to be addressed at Add and Update Goal pages

**Comment by Travis-A-Clark** [comment]
@steffipravasi Could it be linked to the current page but also add an option to the "Show # entries" list drop down so that users can select 10, 50, 100 or All?

**Comment by Travis-A-Clark** [comment]
Message for confirmation text:

Are you sure you want to create the goal and assign to # employees?

Only click "Add New Goal" one time. It can take up to 30 seconds to process. Clicking multiple times will generate multiple copies of the goal and all notifications

----

As discussed, make the confirmation pop up scarier with font, colour, icons, etc.

**Comment by steffipravasi** [comment]
The issues listed in the ticket description have been addressed. The confirmation message has been updated. 
Test validated. 
As discussed we'll move forward with the current fix.

**Comment by Travis-A-Clark** [comment]
@telusdcinco Is it possible to have a different confirmation message when you add individual audience members to an existing goal? It's currently the same as when you create the goal for the first time. If possible, please change to:

"Are you sure you want to assign this goal to # additional employees?

Only click "Add New Goal" one time. It can take up to 30 seconds to process. Clicking multiple times will generate multiple copies of the goal and all notifications."

**Comment by steffipravasi** [comment]
Confirmation message on edit goal updated for individual audience.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFBCQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--103a1eaaa8157e8c89d1fee282c92b1b69803324/Screenshot%202023-11-09%20at%207.39.54%20PM.png)
