### ISSUE TITLE
Query Code Issue:  orWhereRaw use may require open/close parenthesis for grouping where clause elements

### ISSUE THREAD

**Issue by telusdcinco** [bcgov/performance#991]
Query Code Issue:  orWhereRaw use may require open/close parenthesis for grouping where clause elements

**Comment by telusdcinco** [comment]
Impacted items:
- overnight Next Conversation Calc process
- Employee Shares
- Goal Bank
- Notification

**Comment by steffipravasi** [comment]
Issue addressed and validated for Hr and Sys admin on page Share Employee and Manage Existing Shared employees
Test data: Palmer,Courtney Lyn
Larusson,Sharron
Sampson,D Sheila
