### ISSUE TITLE
Add environment indicator so users know what environment they are logged in to

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#992]
**Current Situation**
Some users have access to multiple PDP environments (dev, test, training, production) and it can be confusing to know which version you are logged in to at any given time. There is no clear indication, other than the URL.

**Desired Solution**
Add an indicator across the top that identifies when you are in the dev, test or training environment. No indicator is needed for production. Is it possible to add it in the existing header that has the user name in top right? Maybe centered in that bar?

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/521bdbcd-d363-42ac-80a7-655a58977f99)

**Comment by Travis-A-Clark** [comment]
@JonTelus Hey, Jon! Sorry to just assign this to you without any conversation. Are you able to assist with this ticket or should I add to the backlog for Dennis/Ji? Thanks!

**Comment by JonTelus** [comment]
I don't mind working on this, I might need to ask Dennis for assistance...

**Comment by JonTelus** [comment]
I have a preliminary version of this in DEV, if you can log in to check it out.  It's top right, next to the user name.  I'm not sure what it would take to center it....   I made the text red and bold to stand out, but can modify it.

**Comment by Travis-A-Clark** [comment]
I think it needs to be even more obvious. Maybe use the whole name so that it takes up more space: "Development Environment", "Test Environment", "Training Environment". Possible to up the font size a touch? Or does that mess up the header margins?

Thanks!

**Comment by JonTelus** [comment]
Updated with changes in DEV.

**Comment by Travis-A-Clark** [comment]
I like it. It's just obnoxious enough without being overpowering. Please apply to test and training as well. Thanks!

**Comment by Travis-A-Clark** [comment]
@JonTelus Are we able to push this into TEST and TRAINING soon? Thanks!

**Comment by JonTelus** [comment]
It's in Test now.  

Dennis will push it to training when it's approved. @telusdcinco
