### ISSUE TITLE
Supervisors does not receive conversation due emails notifications

### ISSUE THREAD

**Issue by steffipravasi** [bcgov/performance#995]
Supervisors are not receiving email notifications when users have multiple current supervisors. 
Expected result: The current supervisor selected must receive both the email and in-app notifications
Actual: Only in-app notifications are received

Same issue is with the Delegate supervisor
Expected result: The delegate supervisor selected must receive both the email and in-app notifications
Actual: Only in-app notifications are received

Test data:
User 1:  60290	Swan,Chris L
Supervisor: 1) Current Supervisor:  Wiebe,Heather - Did not receive email
2) Mikkelsen,Kye 
3) Delegate supervisor: Clark, Travis- Did not receive email

User 2: 27950	     Wahl,Diane M
Supervisor: 1) Current Supervisor: Gill,Randher - Did not receive email
2) Morishita,Sheri 
3) Delegate supervisor: Clark, Travis- Did not receive email

User 3: 117609	Partridge,Elizabeth
Supervisor: 1) Hamel,Nicole 
2) Current Supervisor: Lim,Catherine - Did not receive email
3) Sall,Nelampal 
4) Ivanova,Vessela 

User 4: 29879	Schultz,Beverly
Supervisor:
1) Current Supervisor: Reynolds,Catherine - must not receive email
2) Noseworthy,Deborah 
3) Delegate - Zilke,Karen

**Comment by jp-Telus** [comment]
The logic for identify the supervisor/manager similiar to the "Home Page" now. Per dicussion with Steffi, only the current supervisor and the supervisor who shared with the profile will get the email/in-app notification. 

@Dennis, please kindly provide the code review when you has chance. The branch name is bugfix-995, Thanks you

**Comment by jp-Telus** [comment]
@telusdcinco , please kindly provide the code review when you has chance. The branch name is bugfix-995, Thanks you

**Comment by jp-Telus** [comment]
@steffipravasi,  deployed on TEST region. Ready for re-test. Thank you

Thank you Dennis for the code review

**Comment by steffipravasi** [comment]
Test data setup - https://bcgov.sharepoint.com/:x:/r/teams/02915/Shared%20Documents/Product%20Team/Steffi%20-%20Testing/995.xlsx?d=w1787af77f6d2473490a5ea6fbb860d8b&csf=1&web=1&e=0Mt5G2

**Comment by steffipravasi** [comment]
Last night the overnight process ran for almost half a day causing some slowness in the application. James is going to look into the issue and will be continue the testing with Dennis tomorrow.

**Comment by steffipravasi** [comment]
@jp-Telus The supervisors and delegate supervisors are still not receiving emails. We can refer to this spreadsheet to track the test data and accounts used: https://bcgov.sharepoint.com/:x:/r/teams/02915/_layouts/15/Doc.aspx?sourcedoc=%7B1787AF77-F6D2-4734-90A5-EA6FBB860D8B%7D&file=995.xlsx&action=default&mobileredirect=true

**Comment by jp-Telus** [comment]
@steffipravasi , Finally we did see the email notifications were sent out to the supervisor. Only one employee 140450 who the conversation due date is Nov 27, 2023. 

Thank you for your great finding. I noticed that the name of the reciptent are incorrectly shown inside the email body content (at line of the body). That's why you confuse that the same email was sent out to the same person. Actually, the email address is difference but the name in the email body was incorrect, I have fixed this bug, deployed on both DEV and TEST for your retest.

Thank you so much.

**Comment by steffipravasi** [comment]
@jp-Telus Supervisor Mikkelsen,Kye didn't receive email and in-app notification for user Swan,Chris L.
Reference [document](https://bcgov.sharepoint.com/:x:/r/teams/02915/_layouts/15/Doc.aspx?sourcedoc=%7B1787AF77-F6D2-4734-90A5-EA6FBB860D8B%7D&file=995.xlsx&action=default&mobileredirect=true&cid=8d35d95d-4138-4a14-ab59-1f2c5abe808f)

**Comment by steffipravasi** [comment]
### **Comment from James:** 
I saw the issue related to getting current supervisor (some bug) and I fixed it in DEV and TEST regions. And also ran the notification process again. The In-App and Email was generated. You can see them in the notification log  or the Schedule Job Audit's  log message.![MicrosoftTeams-image.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/8d265705-df54-4a31-9117-0798affece8f)![MicrosoftTeams-image (1).png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/d9e31bea-08ff-417c-82a4-13c03362e67d)

**Comment by steffipravasi** [comment]
Test validated and issue has been addressed. 
Test data used: [Document](https://bcgov.sharepoint.com/:x:/r/teams/02915/_layouts/15/Doc.aspx?sourcedoc=%7B1787AF77-F6D2-4734-90A5-EA6FBB860D8B%7D&file=995.xlsx&action=default&mobileredirect=true&cid=8d35d95d-4138-4a14-ab59-1f2c5abe808f)
Moving for PO review.
