### ISSUE TITLE
Fix Tinker in Dev/Test/Training/Prod

### ISSUE THREAD

**Issue by telusdcinco** [bcgov/performance#997]
Currently Tinker is not working in any environment.  Showing error message below.

![image.png](https://images.zenhubusercontent.com/60e88ef619e4760c8b3ee8bb/c2c5a3cf-f744-474c-a5a6-ae7b4f2f7869)

**Comment by telusdcinco** [comment]
@warrenchristian1telus 

Issue resolved by adding line below in config, and bouncing the pods.
XDG_CONFIG_HOME=/var/www/html/storage

**Comment by telusdcinco** [comment]
Change applied to Dev/Test/Training.  Pending Prod, on next scheduled deployment.

**Comment by steffipravasi** [comment]
No front-end testing is needed here. Moving to PO review.
