### ISSUE TITLE
Allow full data pull of employee demographic data from ODS

### ISSUE THREAD

**Issue by telusdcinco** [bcgov/performance#998]
Currently, the daily pull from ODS employee demographic data is filtered to last updated value.  For current run, the process will pull data updated since the last run.

Add an option to allow full data pull regardless of last run date.

**Comment by Travis-A-Clark** [comment]
Just following up to say that I believe the concept was to run the full data pull once per week, in the early hour mornings between Saturday and Sunday.

**Comment by telusdcinco** [comment]
New scheduled for the ODS Employee Demographics data pull.

- Monday to Saturday at 12:10 AM
- Sunday at 12:10 AM

![image.png](https://images.zenhubusercontent.com/60e88ef619e4760c8b3ee8bb/e33d0e66-ad16-4967-9181-c8f2bcb40f14)

**Comment by telusdcinco** [comment]
Additional change added is the output log file.  1 for daily and 1 for weekly.  Both files are overwritten every time the program runs, so there is no risk of the files getting too big.
